### ISSUE TITLE
Could not search folders after install

### ISSUE THREAD

**Issue by haolly** [Flow-Launcher/Flow.Launcher#1000]
**Describe the bug/issue**
Could not search folders after install

**Screenshots**
![image](https://user-images.githubusercontent.com/2383231/151500450-2e50c990-654b-4edb-93bb-980a8635dfc0.png)

**Your System**
windows 10, 20h2
```
Windows build number: (run "ver" at a command prompt)   10.0.19042.1348
Flow Launcher version: (Settings => About)     1.9.1
```
**Flow Launcher Error Log**

[2022-01-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7956393/2022-01-28.txt)

**Comment by taooceros** [comment]
This path is not in the default windows index, so you won't be able to search it. Either you can add it into windows index or use everything plugin. Though I think what you want may be launching python, so for that, you can add the folder into the program plugin index list in the setting panel.

**Comment by haolly** [comment]
@taooceros  So the index functionality is rely on Windows's index or Everything plugin?

**Comment by taooceros** [comment]
> @taooceros  So the index functionality is rely on Windows's index or Everything plugin?

Yes. Though you can still explore folder with path in flow without indexing.
