### ISSUE TITLE
Add a way to reach the right click menu using keyboard

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1007]
Hi,
I think that it would be great if there was a way to reach the right click menu using just the keyboard.
![Flow Launcher_TZAzSwYVUX](https://user-images.githubusercontent.com/47380919/152163094-86ad54dc-d48e-48c6-af47-8b89cb155d58.png)

**Comment by taooceros** [comment]
Shift enter or right arrow when cursor is at the end.
