### ISSUE TITLE
Windows Store Apps

### ISSUE THREAD

**Issue by gnimor** [Flow-Launcher/Flow.Launcher#1010]
I am running the latest version of Flow.Launcher (1.9.2).

It seems that the installed apps via Microsoft Store are not listed in the search result (e.g. Windows Terminal).

**Comment by Garulf** [comment]
You can have Flow launcher added all installed programs by going to `Settings > Plugins` and scrolling to the "Program" plugin.
Add the path manually by hitting "Add" at the bottom or hit "All Programs" to have it automatically added.


![image](https://user-images.githubusercontent.com/535299/152569140-b1c0feb2-b7bb-4e39-b1c5-5ebd15620a95.png)

**Comment by taooceros** [comment]
Huh I think it will be automatically loaded without manually actions. Try reindex in program plugin, and if it still doesn't work, share the log.

**Comment by Garulf** [comment]
My mistake as @taooceros pointed out it looks like "Reindex" is what you want to hit. You can hit "All Programs" to verify it was indexed however.

**Comment by gnimor** [comment]
Sorry - the reindex solved the issue
