### ISSUE TITLE
Flow Launcher got an error when I added a new web search.

### ISSUE THREAD

**Issue by laiqilong** [Flow-Launcher/Flow.Launcher#1011]
Exception message:
> Flow Launcher version: 1.9.2
> OS Version: Microsoft Windows NT 10.0.19043.0
> IntPtr Length: 8
> x64: True
>
> Python Path: 
> Date: 02/07/2022 13:53:01
> Exception:
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
>    at Flow.Launcher.Plugin.WebSearch.SearchSourceSettingWindow.EditSearchSource() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\SearchSourceSetting.xaml.cs:line 109
>    at Flow.Launcher.Plugin.WebSearch.SearchSourceSettingWindow.OnConfirmButtonClick(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\SearchSourceSetting.xaml.cs:line 76
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    at System.Windows.Controls.Button.OnClick()
>    at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-02-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8012744/2022-02-07.txt)

**Comment by jjw24** [comment]
what's the new web search you are trying to add?

**Comment by laiqilong** [comment]
I didn't add any web search service, it crashed when I edited it in the interface of plugins.
<img width="793" alt="Snipaste_2022-02-07_17-49-13" src="https://user-images.githubusercontent.com/69301112/152764585-fcea4db0-b1bd-4f05-9cea-c341885123ae.png">

**Comment by jjw24** [comment]
I cant replicate the issue.

Are you able to reset Flow by deleting the contents of your UserData ?
1. Type `userdata` select the result and it should take you inside the UserData folder.
2. Exit flow. 
3. Delete all everything:
![image](https://user-images.githubusercontent.com/26427004/152770405-1edc6622-5dd2-47cb-9319-8a1d94757ad0.png)
4. Start flow and see if the same issue still happens.

If you are unable to reset flow, let me know and we can look at whether the settings file is corrupted or not for WebSearch.

**Comment by laiqilong** [comment]
Well, my description may be wrong, I want to "add" a new web service but just "edit" an unspecified option, if I just want to add one, it works. 
And the bug reproduces after resetting Flow.

**Comment by jjw24** [comment]
Sorry I am still unable to replicate, anyone else able to give it a shot? @Flow-Launcher/team
