### ISSUE TITLE
Is there a way to 're-enable displaying a program' 

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1012]
![Flow Launcher_Bdau82l6fO](https://user-images.githubusercontent.com/47380919/152816682-36eb620a-7475-464d-82fa-ad274304fd1a.png)

I selected the 'disable this program from displaying' option by mistake on one of the 
search results.

Is there any way to re-enable  the program to display?

Thanks

**Comment by taooceros** [comment]
Check the setting of program plugin and there's a list of program that is included or excluded.

**Comment by rp1231** [comment]
Thanks
