### ISSUE TITLE
Empty last Query & Ctrl+Enter didn't work in some case

### ISSUE THREAD

**Issue by AirDays** [Flow-Launcher/Flow.Launcher#1021]
**Describe the bug/issue**
1. the ```Empty last Query``` didn't work when i right click the search result to select other options, the last query wouldn't empty when reactivate;and if i only right click and do not select any options, reactivate will keep the option list(i have to click the left arrow key to back to the search menu)
2. the ```Ctrl+Enter``` didn't work when some search results come from **Program** plugin's "Index Start Menu"

**Your System**
```
Windows build number: Windows10 21H2
Flow Launcher version: 1.9.2
```

**Comment by AirDays** [comment]
> you mean run as administer? It has been changed ctrl+shift+enter.


no,```Ctrl+Enter```, the hotkey for ```Open Containing Folder```, it didn't work in the case above(the operating results must come from that plugin that option) and seems to become a normal ```Enter```.

**Comment by taooceros** [comment]
> > you mean run as administer? It has been changed ctrl+shift+enter.
> 
> no,`Ctrl+Enter`, the hotkey for `Open Containing Folder`, it didn't work in the case above(the operating results must come from that plugin that option) and seems to become a normal `Enter`.

I don't think we have ctrl + enter open containing folder for program plugin? Probably some of the program works because their entries come from everything/explorer plugin.

**Comment by AirDays** [comment]
> I don't think we have ctrl + enter open containing folder for program plugin? Probably some of the program works because those entries come from explorer plugin.

Thanks for your reply, but it doesn't seem to make sense that ```Ctrl+Enter``` hotkey has taught user in Wizard but actually didn't work for some program's results when right click to select ```Open Containing Folder``` option is work.

**Comment by taooceros** [comment]
Ah I see the issue. We will discuss about whether to add `ctrl+enter` for opening containing folder for program plugin or adjust the wizard. Thanks for indicating this.

**Comment by jjw24** [comment]
> > I don't think we have ctrl + enter open containing folder for program plugin? Probably some of the program works because those entries come from explorer plugin.
> 
> Thanks for your reply, but it doesn't seem to make sense that `Ctrl+Enter` hotkey has taught user in Wizard but actually didn't work for some program's results when right click to select `Open Containing Folder` it work.

Good point. I have seldomly needed to check where a program is installed to when I wanted to open the containing folder. @AirDays do you have a use case that is frequent or is it more the inconsistency from the wizard's guide?

**Comment by AirDays** [comment]
> Good point. I have seldomly needed to check where a program is installed to when I wanted to open the containing folder. @AirDays do you have a use case that is frequent or is it more the inconsistency from the wizard's guide?

Mostly I don't need to check the program installed folder, but sometimes i will open installed folder multiple times to override and update some portable programs or check some setting files(also i think if someone use a program export files in the installed path, they will need it too).
I spent some time comparing other launchers(ueli/listary), and found their program search seem like Flowlauncher's ```Explorer``` plugin but more make sense to me because they put the program's .lnk to the top of results, ```Open Containing Folder```'s hotkey work and the result name will hide extension name when the result is a program's .Ink(that would be more friendly to user).In ```ueli``` case, i can easily open .Ink folder on the top of results then use windows context; In ```listary``` case, it include .lnk's windows context menu in the result's context menu so i can only use hotkey.
FlowLauncher seem to ranking drop the .Ink because Explorer&Program plugin have similar function, i try to disable ```Program``` plugin and set up the priority but it can't satisfy me because 1. .Ink still under some items come from same plugin 2. the extension name can't hide.

**Comment by AirDays** [comment]
And I guess the main reason of i don't want to use FlowLauncher result's context menu is ```Empty last Query``` function is not perfect yet and i didn't know which item i selected when i am in context menu. i have said too much;)

**Comment by taooceros** [comment]
Sorry I didn't see the later message. The behavior already has a development pr for displaying result panel when deactivating. So you may see that in the next release.

**Comment by jjw24** [comment]
To do before closing this issue, update wizards wording to be plugin specific:
![image](https://user-images.githubusercontent.com/26427004/216158273-283e5b51-a6a8-446b-bd6a-c7cb33672dc4.png)

Update to 'Open A File/Folder's Containing Folder'

**Comment by jjw24** [comment]
I have created a new issue to track this work. Please follow https://github.com/Flow-Launcher/Flow.Launcher/issues/1872 for updates.
