### ISSUE TITLE
Make bookmarks search can choose which browser to read

### ISSUE THREAD

**Issue by AirDays** [Flow-Launcher/Flow.Launcher#1022]
I notice that the ```Bookmarks Search``` built-in plugin will read all my browsers(chrome,firefox...) bookmarks at startup because it is hardcode, for some privacy reason I block FlowLauncher to read one of my browser's bookmarks so that it can only show the bookmarks i want, but the plugin will undoubtedly init failed.
It would be great if give user some checkboxs to choose which browser to read and others not.

**Comment by jjw24** [comment]
Yes it's currently showing all supported browsers' bookmarks, and adding this option does make sense.

**Comment by Joelman95** [comment]
It currently just support 3 browsers for bookmarks: chrome, firefox, edge. I do use Opera as my main browser and have 95% of my bookmarks there, so it would be great if it could support Opera (best productivity browser in my opinion) bookmarks too. Any plans on adding Opera or other browser? :)

**Comment by taooceros** [comment]
> It currently just support 3 browsers for bookmarks: chrome, firefox, edge. I do use Opera as my main browser and have 95% of my bookmarks there, so it would be great if it could support Opera (best productivity browser in my opinion) bookmarks too. Any plans on adding Opera or other browser? :)

I think opera use chromium? It should be already supported, but you may need to figure out the data directory and add that  to the setting. Refer to #1029

**Comment by Joelman95** [comment]
@taooceros thanks, I found the location. But not sure how to type the path? also which of the 3 selected alternatives for bookmarks to choose from (I guess just typing Bookmarks)?
![image](https://user-images.githubusercontent.com/102371213/160146953-753ea0f0-49e7-49f6-9ac4-109951cc7441.png)

**Comment by taooceros** [comment]
> @taooceros thanks, I found the location. But not sure how to type the path? also which of the 3 selected alternatives for bookmarks to choose from (I guess just typing Bookmarks)?
> ![image](https://user-images.githubusercontent.com/102371213/160146953-753ea0f0-49e7-49f6-9ac4-109951cc7441.png)
> 

Hm I am not quite sure whether direct putting the bookmark path works (it should though). You can try putting the first one without extension.

**Comment by taooceros** [comment]
@onesounds Could you take a look on the ui design for this. It should be relatively easy to implement the logic.

**Comment by jjw24** [comment]
@VictoriousRaptor was this already added by you?

**Comment by AlennGK** [comment]
Vivaldi user here, I think that every browser have the same json structure for bookmarks. So I don't get why FL dont want to load mine ʕノ•ᴥ•ʔノ ︵ ┻━┻

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor was this already added by you?

Damn why I didn't see it. No. That pr was about fixing firefox.
