### ISSUE TITLE
Add support for Brave-browser

### ISSUE THREAD

**Issue by s0902rx** [Flow-Launcher/Flow.Launcher#1029]
**Is your feature request related to a problem? Please describe.**

I can't access my browser bookmarks and history using flow launcher plugins because Brave-browser is not supported.

**Describe the solution you'd like**

Add support for Brave-browser.

**Describe alternatives you've considered**

Using both the Ueli and flow launcher.

**Comment by taooceros** [comment]
There's custom browser bookmark path. You can input the custom path of browser bookmark data path to flow's setting.
![image](https://user-images.githubusercontent.com/45326534/154156497-41afa1d9-b8e1-4f38-a413-33148b7548b3.png)

**Comment by taooceros** [comment]
Brave is from chromium so I think it will work.

**Comment by s0902rx** [comment]
> Brave is from chromium so I think it will work.

Brave doesn't have a bookmarks folder for some reason or i didn't find it. Why can't we just select the browser like the browser history plugin does for chrome and firefox?

**Comment by taooceros** [comment]
> > Brave is from chromium so I think it will work.
> 
> Brave doesn't have a bookmarks folder for some reason or i didn't find it. Why can't we just select the browser like the browser history plugin does for chrome and firefox?

We don't know the browser app folder (which is generally different from the executable). I don't get brave in my computer, but chrome store the bookmark here.
%localappdata%\Google\Chrome\User Data
Find the similar path for brave and enter to the setting. It should work if they share the similar structure.

**Comment by s0902rx** [comment]
I tried to find a bookmarks folder but there was none but i found a bookmarks file in 

C:\Users\s2\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default 

and added it's path to flow laucher and refreshed plugin data and restarted flow launcher and it didn't work.

**Comment by deefrawley** [comment]
Can confirm this doesn't work

**Comment by taooceros** [comment]
It works. set path like this
![image](https://user-images.githubusercontent.com/45326534/156826869-53f0c76d-0da1-4a9c-839f-e554a6248998.png)

**Comment by jjw24** [comment]
@s0902rx please confirm

**Comment by akash9080** [comment]
> @s0902rx please confirm

Yes, it's working. Thank you for your help.

**Comment by santiyounger** [comment]
thanks a lot @taooceros that worked for me too!
