### ISSUE TITLE
Request to add Wox Plugin Runner

### ISSUE THREAD

**Issue by sk209** [Flow-Launcher/Flow.Launcher#104]
Request to add support for [Wox.Plugin.Runner](https://github.com/CrazyCoder/Wox.Plugin.Runner) or include it in the defaults.

**Comment by jjw24** [comment]
Hey how's it going.

The port is ready at https://github.com/jjw24/Wox.Plugin.Runner/releases/latest, see release notes for instructions on how to install into Flow.

This is a current temp work around while we get Flow's plugin management implemented.

All behaviours should be the same as the original plugin, let me know if you run into any issues.

**Comment by jjw24** [comment]
Available already via `pm install runner`
