### ISSUE TITLE
 Switch apps when the app is already open

### ISSUE THREAD

**Issue by yayiji** [Flow-Launcher/Flow.Launcher#1043]
Switch apps when the app is already open. Often creating new instances is not what people want

**Comment by Garulf** [comment]
To clarify you would like the Program plugin to switch to an already open application if it's already running?

**Comment by yayiji** [comment]
Yes, almost all mac launcher applications behave like this, which is very convenient for cultivating muscle memory, which application I want to open. If the app already exists, switch to that app, and if the app has multiple windows, switch to the most recent window.

**Comment by Garulf** [comment]
Flow Launcher is just using default Windows behavior. But as a heavy Mac user I get what you mean. May I suggest the Window Walker plugin for switching between open apps?

**Comment by yayiji** [comment]
Thanks, but it wasn't a good experience. On Mac I can have a wonderful pattern:
```
xxco<cr>: vscode
xxch<cr>: chrome
xxid<cr>: intellij idea
```
And I never look at picklists, just use muscle. I've looked at a lot of Windows launchers, like powertoys, wox, and none of them can have such an experience, except for Fluent Search (a new Windows launcher), and I would love for Flow-Launcher to support this natively.

**Comment by Garulf** [comment]
I suppose it could be added as an option, we'd just have to detect opened windows and change focus instead of opening when detected. (Not sure when I can get around to this, unless someone else wants to take this up).

In the mean time I was able to set window walker as the top result when typing `cod`
![image](https://user-images.githubusercontent.com/535299/156033324-faeaa764-6f76-439f-9cdf-1d2f6919cb1b.png)
Allowing me to change to it's window when open and when it's not it wont be the top result thus launching code.

VS code currently open:
![image](https://user-images.githubusercontent.com/535299/156033487-a43f72be-bb65-4853-bde8-00b10b4dcfec.png)

VS code closed:
![image](https://user-images.githubusercontent.com/535299/156033509-1da6c45a-e427-4a35-82a8-f7a5cbefe4db.png)

**Comment by jjw24** [comment]
Yeah I have been doing the same as well, the already opened app process is always higher than the Program plugin's result. Don't remember if I needed to set priority or not. @yayiji give it a shot and let us know how it feels.

**Comment by yayiji** [comment]
Thank you so much for such a detailed reply, I tried and it work well, love you guys.

**Comment by yayiji** [comment]
> Yeah I have been doing the same as well, the already opened app process is always higher than the Program plugin's result. Don't remember if I needed to set priority or not. @yayiji give it a shot and let us know how it feels.

@jjw24 

#### After the trial, I have some suggestions, whether the window icon can be changed to be the same as the application icon so that the recognition will be better, otherwise, you have to take a closer look at what it is.
![image](https://user-images.githubusercontent.com/12449762/156077191-d79d5935-03a5-4639-ad27-91567d5f7f20.png)


#### Another is that the application name should be displayed first, followed by the window title.
![image](https://user-images.githubusercontent.com/12449762/156077257-3bbdd0d9-b242-44b8-b14f-60cb8956120c.png)

**Comment by taooceros** [comment]
The only concern with this is that it will make process and program a bit hard to be distinguished. We have a draft doing so.

**Comment by yayiji** [comment]
> The only concern with this is that it will make process and program a bit hard to be distinguished. We have a draft doing so.

#### In fact, on MacOS (like Alfred, Raycast), these two are one thing, not two, so I don't need to care if the app is running, I just want to switch to this app. I think it's a better way, I'm not judging windows by the behavior of mac, just my personal opinion.
![image](https://user-images.githubusercontent.com/12449762/156081407-ff16c71a-cc5d-4610-813d-9ce4cc1b5a36.png)

**Comment by onesounds** [comment]
> The only concern with this is that it will make process and program a bit hard to be distinguished. We have a draft doing so.

@taooceros Let's put in the icon. People who need this function will not be confused.

**Comment by taooceros** [comment]
> > The only concern with this is that it will make process and program a bit hard to be distinguished. We have a draft doing so.
> 
> @taooceros Let's put in the icon. People who need this function will not be confused.
> 

Ok

**Comment by onesounds** [comment]
and Title and Application name don't need to be repositioned.
1. If we insert an icon, we can know what app it is. 
2. In the same application, the window name is a unique ID, so it should take precedence.
