### ISSUE TITLE
Flow Launcher no longer shows up in system tray

### ISSUE THREAD

**Issue by luisraul-h** [Flow-Launcher/Flow.Launcher#1047]
After installing, Flow Launcher allowed me to open the settings through the icon in the system tray. Once I installed the "Google Search" plugin the icon no longer shows up, giving me no way to configure the launcher.

Attempted to uninstall, clean registry, and reinstall.. even restarted and no luck,

1. Install Google Search Plugin
2. Restart Flow Launcher

Windows build number: Version 10.0.22000.527
Flow Launcher version: v1.9.2
```
**Flow Launcher Error Log**
<!-- 
     The latest log file can be found here: %AppData%\FlowLauncher\Logs\<version>\<date>.txt
     or for portable mode: %LocalAppData%\FlowLauncher\<App-Version>\UserData\Logs\<version>\<date>.txt
     Drag and drop the log file below this comment.
-->
```
[2022-02-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8158372/2022-02-28.txt)

**Comment by taooceros** [comment]
You can also access setting via query settings. We will take a look on why the icon disappeared.

**Comment by Garulf** [comment]
While not a fix you can access the settings by typing "settings" in Flow Launcher.

**Comment by luisraul-h** [comment]
> While not a fix you can access the settings by typing "settings" in Flow Launcher.

I attempted this but the launcher did not show an option for the app settings.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/156097485-62cbd30a-861d-4480-b8cc-ce1f62f01f0d.png)
this doesn't work?

**Comment by luisraul-h** [comment]
Nope, it didn't. I uninstalled and deleted the files in %AppData folder that seemed to be the immediate fix once reinstalling.

**Comment by taooceros** [comment]
> Nope, it didn't. I uninstalled and deleted the files in %AppData folder that seemed to be the immediate fix once reinstalling.

I feel like it is because of some issue in the setting that block the setting to generate? Not quite sure the detail reason, but I will take a check while adjusting code in the future
