### ISSUE TITLE
Windows Subsystem for Android apps not listed

### ISSUE THREAD

**Issue by Ombrelin** [Flow-Launcher/Flow.Launcher#1049]
**Describe the bug/issue**

The apps installed on the Windows Subsystem for Android are not indexed by Flow, but they show on the start menu.

**To Reproduce**
1. Install WSA
2. Install an App
3. Search it in flow
4. It's not listed

**Screenshots**

![image](https://user-images.githubusercontent.com/47502331/156168300-d66b1393-a389-426a-9536-db8e34ef847c.png)

![image](https://user-images.githubusercontent.com/47502331/156168328-d27496f0-d8bd-42e8-97d1-7de315490879.png)

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.527] (Windows 11)
Flow Launcher version: 1.9.2
```

**Comment by Ombrelin** [comment]
Just tried that, no more success

**Comment by taooceros** [comment]
> @taooceros I dont think we implemented loading of WSA apps as it is relatively new. 
> 
> I think you can use Explorer plugin and have Windows Search (Index) set on start menu as a work around to find these WSA apps.

I think it partially work, though not quite sure the mechanism. Also it is possible that I get the result because of everything (haven't checked). Wsa will create a lnk shortcut so it may work.

**Comment by jjw24** [comment]
This needs to be addressed.

**Comment by VictoriousRaptor** [comment]
WSA apps are listed on my PC. (Windows 10, running modified WSA)

**Comment by Yusyuriv** [comment]
Seems like this works on my PC, but is this even relevant anymore, with [Microsoft ending support for WSA next year](https://learn.microsoft.com/en-us/windows/android/wsa/)?

**Comment by jjw24** [comment]
Unfortunately working on this will no longer be relevant, let's close it.
