### ISSUE TITLE
Show folder path in Explorer search result

### ISSUE THREAD

**Issue by sk209** [Flow-Launcher/Flow.Launcher#105]
**Current Behaviour:**
Explorer search results show subtitles as "Ctrl+Enter to Open Directory"

**Problem:**
There is no way to differentiate the search results because they all look the same

**Suggestion:**
Instead of "Ctrl+Enter to Open Directory", we should display the folder path (similar to how the 'everything' plugin does)

So the search results will be :
> 
> Folder Name
> C:/path/to/folder/Folder Name
> 
> Folder Name
> C:/path/to another/folder/Folder Name
> 
> Folder Name
> C:/path/to again/another/folder/Folder Name

instead of:
> 
> Folder Name
> Ctrl+Enter to Open Directory
> 
> Folder Name
> Ctrl+Enter to Open Directory
> 
> Folder Name
> Ctrl+Enter to Open Directory

Screenshot showing the issue (all search results look the same, showing the file path for each result will fix this)
<img width="953" alt="Screenshot (20)" src="https://user-images.githubusercontent.com/54979934/86507645-f0e8b180-bdea-11ea-868e-bbbf08ca638a.png">

**Comment by jjw24** [comment]
Hey how's it going. This has been fixed already and will be released in the next 30mins :)
