### ISSUE TITLE
Plugin Runner commands do not appear in global search results.

### ISSUE THREAD

**Issue by yayiji** [Flow-Launcher/Flow.Launcher#1057]
#### I use the Plugin Runner plugin, but commands don't appear in the global search results. It only appears when I type the action keyword r.
![image](https://user-images.githubusercontent.com/12449762/156344919-c0242604-21a9-4968-b999-d4450caa5eca.png)

#### Commands don't appear in the global search results. 
![image](https://user-images.githubusercontent.com/12449762/156344341-f15be688-5365-44ba-859f-3eede22394fe.png)

#### It only appears when I type the action keyword r.
![image](https://user-images.githubusercontent.com/12449762/156344365-27d79fe6-56d2-41d1-88f9-69222170d3d2.png)

**Comment by deefrawley** [comment]
This is exactly how the plugin is supposed to work if it has a hotkey assigned. If you want your Plugin Runner results to appear without a keyword then change that plugin keyword to `*` in settings.
