### ISSUE TITLE
Windows 11 Blur theme issue

### ISSUE THREAD

**Issue by shehabaldien** [Flow-Launcher/Flow.Launcher#1063]
when I have the flow launcher open and run in the background 
and I di windows drag, I notice there is a noticeable delay in moving and dragging the windows 
and when I close the flow launcher , the delay won't happen.
plz fix his issue

**Comment by Garulf** [comment]
> when I have the flow launcher open and run in the background 
> 
> and I di windows drag, I notice there is a noticeable delay in moving and dragging the windows 
> 
> and when I close the flow launcher , the delay won't happen.
> 
> plz fix his issue

Hi @shehabaldien , what version of Flow Launcher and Windows are you using?

**Comment by shehabaldien** [comment]
I use windows 11 
And I downloaded the last version of flow launcher

**Comment by Garulf** [comment]
I recall an issue with windows 11 and Blur in themes causing weird issues with window dragging. Not sure if that's been fixed or not because I stayed on Windows 10. 

@taooceros Is this related?

**Comment by shehabaldien** [comment]
If you want i can send you a video to see the problem

**Comment by taooceros** [comment]
Are you using the blur theme? It will cause this issue in win 11

**Comment by shehabaldien** [comment]
yes i use blur black theme of flow launcher

**Comment by shehabaldien** [comment]
when i changed it to another non blur theme , the issue is fixed

**Comment by taooceros** [comment]
> yes i use blur black theme of flow launcher
> 

It is win11 fault. I guess they depreciate the blur api we are using for now. We haven't finished the blurtheme based on new api, so for now you would need to use non blur theme.

**Comment by onesounds** [comment]
I think MS is no longer fixing this part, so we have to abandon the existing api and use a compatible api. But I haven't found an appropriate way yet.
It would be better to change the blur theme to simple translucent, and implement blur in the future.

**Comment by taooceros** [comment]
I think @jjw24 has pointed out that the blur seems to work on the latest win11 build.

**Comment by jjw24** [comment]
yep tried on:
![image](https://user-images.githubusercontent.com/26427004/173688553-ed0f5154-27b3-4bab-a9e4-a2c6dd90b294.png)


Let's close this. Feel free to reopen if not the case.
