### ISSUE TITLE
"Explorer" plugin can't search some folders

### ISSUE THREAD

**Issue by minawaheed9697** [Flow-Launcher/Flow.Launcher#1064]
Hi there, 

Thanks for this great app. It really changed my life.

I have an issue with "Explorer" plugin.
When I search folders in C:\, it doesn't find them. 
In indexing options, there are always excludes in search that I can't get rid of them. 
Can those exclude be the cause of this issue?? 

Window 10 [Version 10.0.19044.1526]

<img width="368" alt="04_03_2022 07_52_10_674" src="https://user-images.githubusercontent.com/73688266/156710114-5cc0746f-b1a7-4a86-afe8-9ddf20ee91a0.png">

**Comment by deefrawley** [comment]
Hi. Are the things you are searching for located in the excluded directories?
To change what is and isn't excluded click the Modify button and next to the displayed drive/folder checkbox, just to the right, you should see a greater than sign `>`. Click that and it expands the sub directories and you can change as needed (it's not easy to see unless you are looking for iti)

**Comment by minawaheed9697** [comment]
I know how to chick folders to be searched, but I can't find those exclude folders. 
The folders I want to search are located in AppData folder. I think AppData is a hidden folder. 
Can Explorer plugin search in those hidden files??

**Comment by minawaheed9697** [comment]
I installed "Everything" plugin and it's so good in search, but it doesn't have a great feature in "Explorer". Explorer can show the files and folders inside the searched folder, but Everything open the folder directly. 
If there is a way to make Everything make the same thing, it'll be perfect.

**Comment by deefrawley** [comment]
Just to confirm:

![2022-03-04 17_49_57-Window](https://user-images.githubusercontent.com/18594055/156714131-e0b72c7c-6f7d-4db9-954a-64bdcadd7fb5.png)

I do have Windows Explorer set to show hidden files and directories and I don't know if this affects what you see in the Indexing options.
I'm not sure what the `Data` and `CSC` folders are from your original screenshot. They don't seem to be standard Windows folders but I could be wrong.

**Comment by minawaheed9697** [comment]
I also made Windows Explorer to show hidden files, but nothing happened. It still can't search those folders.

**Comment by deefrawley** [comment]
Yeah I can confirm - I enabled the AppData folder, did a full reindex, restarted Flow and can't search for anything in the AppData folder. @jjw24 @taooceros is this expected behaviour?

**Comment by Garulf** [comment]
Odd, I don't have any issues?

![image](https://user-images.githubusercontent.com/535299/156775726-e7c1eb6b-bc88-423d-9a3e-345bedab6c67.png)

**Comment by taooceros** [comment]
> Yeah I can confirm - I enabled the AppData folder, did a full reindex, restarted Flow and can't search for anything in the AppData folder. @jjw24 @taooceros is this expected behaviour?

Possible that some of the folder inside appdata is under windows index, while the other are not. I remember the behavior is to use index as much as possible?

**Comment by minawaheed9697** [comment]
> Possible that some of the folder inside appdata is under windows index, while the other are not. I remember the behavior is to use index as much as possible?

How can I use index?? And is this a solution for the issue??

**Comment by taooceros** [comment]
> > Possible that some of the folder inside appdata is under windows index, while the other are not. I remember the behavior is to use index as much as possible?
> 
> How can I use index?? And is this a solution for the issue??
> 

One alternate is to index the whole folder, or exclude the whole folder in windows index.
I think we will need to adjust the behavior for this.

**Comment by minawaheed9697** [comment]
> One alternate is to index the whole folder, or exclude the whole folder in windows index. I think we will need to adjust the behavior for this.

As above screenshot, I indexed the whole "C" except the "Data" folder, I can't find it. 
Or is there another way to index the whole folder??

**Comment by taooceros** [comment]
Huh then just remove the exclusion of the Data folder in the index? It should be able to index everything except network folder (onedrive etc.).

**Comment by taooceros** [comment]
> I installed "Everything" plugin and it's so good in search, but it doesn't have a great feature in "Explorer". Explorer can show the files and folders inside the searched folder, but Everything open the folder directly. 
> If there is a way to make Everything make the same thing, it'll be perfect. 

I am thinking about this before, but probably it will need some new api, which seems not easy to be done due to the current implementation because Plugins are separate from each other.

**Comment by minawaheed9697** [comment]
> Huh then just remove the exclusion of the Data folder in the index? It should be able to index everything except network folder (onedrive etc.).

I can't remove "Data" from exclusion. I can't find it.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/156828884-56d3958e-58d7-4192-b09e-e845f88f04b9.png)
check here

**Comment by minawaheed9697** [comment]
> ![image](https://user-images.githubusercontent.com/45326534/156828884-56d3958e-58d7-4192-b09e-e845f88f04b9.png) check here

I made this, and it removed the exclusion from index, but still have the same issue. I can't search some folders in AppData and other folders.

**Comment by jjw24** [comment]
AppData should be shown, the indexer from windows can sometimes get a bit frustrating.  You need to make sure you check the two areas where paths can be excluded:

0. Explorer plugin setting also has an option to exclude paths, I am assuming you just started using flow and havent set anything yet.
1. https://github.com/Flow-Launcher/Flow.Launcher/issues/1064#issuecomment-1058887774
2. https://github.com/Flow-Launcher/Flow.Launcher/issues/1064#issuecomment-1059451536
Then **make sure** you reindex after making the change, otherwise the indexing won't update, option is in windows indexer see 1. comment

It's a bit of trial and error with 1. to make sure the paths is correctly indexed. Worst case scenario, index everything as a baseline, check that the AppData path works, then start unticking the paths you don't want.

>I installed "Everything" plugin and it's so good in search, but it doesn't have a great feature in "Explorer". Explorer can show the files and folders inside the searched folder, but Everything open the folder directly.
If there is a way to make Everything make the same thing, it'll be perfect.

Agree, I think it will be a good feature to add. @taooceros maybe potentially copy and paste the code that iterates through the folders if the Everything API returns the path? Maybe no need to expose this via flow's API.

**Comment by minawaheed9697** [comment]
I tried checking the first and second settings and both have no excludes. 
But, I don't know how to update the index database?? 
It stills search for some folders in AppData and doesn't search for other folders.

**Comment by jjw24** [comment]
yeah you can rebuild the index in the indexing options' settings:

![image](https://user-images.githubusercontent.com/26427004/157117746-e0f5982c-2ad9-41cd-8148-c32c0663f708.png)

**Comment by minawaheed9697** [comment]
@jjw24 
I rebuilt the index again, but still the same issue. 
When I search AppData, it searches Local only, not Roaming.
And I don't know if this issue can occur at other folders or not?

**Comment by jjw24** [comment]
So you removed all exclusions and rebuilt index, still not showing up?

Could you show me what your indexing looks like, expand AppData, Local and Roaming locations (blur out any personal directories you don't want to show).

**Comment by minawaheed9697** [comment]
Yes, I did all of those steps, but nothing happened. 

<img width="435" alt="10_03_2022 11_36_22_195" src="https://user-images.githubusercontent.com/73688266/157634343-caba5036-42cc-4e97-a566-a93efe17f09c.png">
<img width="368" alt="10_03_2022 11_36_34_980" src="https://user-images.githubusercontent.com/73688266/157634349-1721a58a-14b5-49c6-b20b-d2d511772c20.png">
<img width="265" alt="10_03_2022 11_36_55_860" src="https://user-images.githubusercontent.com/73688266/157634352-606834ce-5562-4f39-9e5f-f6d058d05aae.png">
<img width="265" alt="10_03_2022 11_37_27_230" src="https://user-images.githubusercontent.com/73688266/157634355-9831b1fb-5227-4a19-b21d-4c1883b6b2c8.png">
<img width="265" alt="10_03_2022 11_37_37_154" src="https://user-images.githubusercontent.com/73688266/157634359-913a8c10-694a-4a40-b46c-86d5a978271a.png">

**Comment by jjw24** [comment]
Does Roaming come up when you search via the windows start menu's search? (Window's own search should return the same files/folder as Flow's Explorer).

If you just want to traverse the folder paths like Roaming, you can actually exclude it from Index Search by going to the plugin's setting and add the path to the exclude index search option, e.g. add C:\ will allow you to traverse through entire location without writing about the index. Then if you want to search for a particular folder/file, use Everything plugin. This is a workaround to your issue, but do let me know if Window's Start Menu search actually brings up results like the Roaming folder, so we can determine if it's an issue with plugin or some windows misconfiguration.

**Comment by taooceros** [comment]
I think we needs to have a better check for whether using index, since path search should not exclude path that is excluded in index search.

**Comment by taooceros** [comment]
Regarding the integration of everything and the Explorer plugin, we will need to develop a integration api, which may takes a while.

**Comment by minawaheed9697** [comment]
> Regarding the integration of everything and the Explorer plugin, we will need to develop a integration api, which may takes a while.

So, it's possible, but will take some time?

**Comment by taooceros** [comment]
It is undetermined how to implement it yet, so will take a while.

**Comment by jjw24** [comment]
@minawaheed9697 are you able to get by with using both Explorer (for showing files and folders inside the searched path) and Everything (for searching directly the files or folder)?

**Comment by minawaheed9697** [comment]
> @minawaheed9697 are you able to get by with using both Explorer (for showing files and folders inside the searched path) and Everything (for searching directly the files or folder, replacing index search)?

@jjw24 Unfortunately, I can't as it doubles the same folders and files and makes me confused. 
E.g. if I search for any folder, there will be 2 of it and I can't differentiate which is Explorer and Everything.

**Comment by jjw24** [comment]
yeah so all you need to do is disable general search and activate path search in Explorer settings:

![image](https://user-images.githubusercontent.com/26427004/158040513-1f7ead67-063e-4bb5-9536-954d231f10c1.png)

Enabling path search on its own will allow you to just use the search for files/folders inside searched path, and disabling general search will remove the duplicate folders as index search wont be activated.

**Comment by minawaheed9697** [comment]
Okay, but Everything doesn't have this feature. 
So, disabling the General Search will disable this feature. 

> I installed "Everything" plugin and it's so good in search, but it doesn't have a great feature in "Explorer". Explorer can show the files and folders inside the searched folder, but Everything open the folder directly. If there is a way to make Everything make the same thing, it'll be perfect.

**Comment by taooceros** [comment]
There's a test build that has disabled the index search when doing traversal. https://ci.appveyor.com/api/buildjobs/0y1hra9fqwmf56o5/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

We are planning to merge everything to explorer plugin in the future, so theoretically they will share the feature in the future.

**Comment by jjw24** [comment]
I think the flow here is where user want to traverse the folder path with everything which doesn't happen. @taooceros since we still have to maintain largely two sets of code, might be better to expose directory traversal search in Flow's plugin project instead of merging in which is alot more effort involved?

**Comment by jjw24** [comment]
Completed and available in v1.11.0
