### ISSUE TITLE
Open an app with active session

### ISSUE THREAD

**Issue by gopibabus** [Flow-Launcher/Flow.Launcher#1065]
**Problem:** When I am trying to open an app like Microsoft edge using flow launcher, it is starting a new session and opening a new instance of Microsoft edge browser 

**Expected Solution**: Should open an app with existing session and if app doesn't have active session, then flow launcher should start new session and open a new window.

I searched for existing features in flow launcher, but I didn't find one, if you think this is already existed, please let me know. Thanks.

**Comment by Garulf** [comment]
Hi @gopibabus FLow Launcher uses Windows default behavior (the start menu does the samething for example).

If you'd like to switch to an already open app and not launch you may want to try the WindowWalker plugin. This plugin allows you to *switch* application focus.

![image](https://user-images.githubusercontent.com/535299/156773871-ef5e73ac-7e17-40f1-8ebf-9f2c73a5dfd9.png)

**Comment by gopibabus** [comment]
Thanks @Garulf . Window walker plugin works for me. Thanks.

**Comment by Garulf** [comment]
No problem! Glad to hear it works for you!
