### ISSUE TITLE
Font anti-aliasing

### ISSUE THREAD

**Issue by shifterest** [Flow-Launcher/Flow.Launcher#1066]
Font anti-aliasing would be a great feature to make reading results more pleasing to the eye.

**Comment by onesounds** [comment]
Anti-aliasing has been removed for several reasons.
Tell me the screen resolution/OS and show me your screenshot.
I will check the problem and find a way to solve it.

**Comment by onesounds** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/pull/1119 This PR will attempt to fix it.

**Comment by jjw24** [comment]
Addressed in the above linked PR, you can grab the early access build containing the fix from https://github.com/Flow-Launcher/Flow.Launcher/discussions/956
