### ISSUE TITLE
Add spanish translation

### ISSUE THREAD

**Issue by elvstejd** [Flow-Launcher/Flow.Launcher#1069]
Would love it if spanish was supported.

**Comment by jjw24** [comment]
hey how's it going. 

Spanish has been added. You can start translation at https://crowdin.com/project/flow-launcher or directly in the xaml.

**Comment by BanCrash** [comment]
Hi @jjw24 , spanish is at 100% on crowdin but I can't see it on the app, is this a bug for a separated issue?

![image](https://user-images.githubusercontent.com/11770760/184426902-220f48f6-96dc-4ddb-9fd0-c13e562a9667.png)

In language settings should appear "Español" (or "Spanish" if it's on english), but it doesn't appear:

![image](https://user-images.githubusercontent.com/11770760/184426967-e4b1dddc-4ec8-4d2c-a702-790e39a4f6aa.png)

![image](https://user-images.githubusercontent.com/11770760/184426944-17a94838-85b4-4702-98ed-409476b317e1.png)

**Comment by jjw24** [comment]
Hi @BanCrash, apologies for the confusion. Spanish has been added into the [pre-release version](https://github.com/Flow-Launcher/Flow.Launcher/discussions/956) and at the moment set for 1.10.0 release. You can still use the pre-release version of you are looking to change the language to Spanish right now.

**Comment by BanCrash** [comment]
> Hi @BanCrash, apologies for the confusion. Spanish has been added into the [pre-release version](https://github.com/Flow-Launcher/Flow.Launcher/discussions/956) and at the moment set for 1.10.0 release. You can still use the pre-release version of you are looking to change the language to Spanish right now.

@jjw24 oh, okay, thank you for the answer!
