### ISSUE TITLE
App Search Not working properly

### ISSUE THREAD

**Issue by skillhacker-code** [Flow-Launcher/Flow.Launcher#1073]
**Describe the bug/issue**

**To Reproduce**
1. Installed new app Atom Ide after installing Flow Launcher
2. searched for atom in flow launcher 
3. it is not showing in search result unless i put a fullstop after atom it give the atom.ink result 

**Screenshots**

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.493]
Flow Launcher version: 1.9.2 and 1.9.3(issue exist in both version )
```
**Flow Launcher Error Log**

**Comment by jjw24** [comment]
> it is not showing in search result unless i put a fullstop after atom it give the atom.ink result

I think this is coming from Explorer plugin instead of Program plugin that you want. We currently still in the process of implementing automatic detection of newly install apps, does Atom Ide come up when you reload the data via pressing F5 in the search window?

**Comment by skillhacker-code** [comment]
After pressing F5 ,it is showing atom in the search . Thank you
