### ISSUE TITLE
[Drag-and-drop for file to another location] 

### ISSUE THREAD

**Issue by Lyn6969** [Flow-Launcher/Flow.Launcher#1084]
**Describe the solution you'd like**

After searching for a file, I usually drag-and-drop (copy) it to another location (e.g., File Manager or WeChat, or QQ). Still, Flow doesn't support this feature now, so I think it is necessary. Will you consider adding drag-and-drop (just for file) in the future?

**Comment by jjw24** [comment]
Copying a file or folder when the result is highlighted via Ctrl + C has been added to 1.10.0 release, does File Manager or WeChat, or QQ allow pasting the file? Would this be faster than find mouse, point, drag and drop?

**Comment by Lyn6969** [comment]
> Copying a file or folder when the result is highlighted via Ctrl + C has been added to 1.10.0 release, does File Manager or WeChat, or QQ allow pasting the file? Would this be faster than find mouse, point, drag and drop?

They do allow copying of files; for example, if I want to send a file to my friend, after searching for the file, it is more intuitive to drag and drop it directly into the chat box to finish copying. Of course, this is optional, and I think it might be more convenient; others might prefer to use keyboard shortcuts.

**Comment by jjw24** [comment]
Wouldn't it be more intuitive to Ctrl + C, which also hides the search window bringing you back to WeChat, then you just Ctrl + V to paste it in, no need to touch the mouse?

**Comment by Lyn6969** [comment]
> Wouldn't it be more intuitive to Ctrl + C, which also hides the search window bringing you back to WeChat, then you just Ctrl + V to paste it in, no need to touch the mouse?
![111](https://user-images.githubusercontent.com/42564665/158974528-3c5965f6-4aed-42c5-b15b-73b7c0faa8fd.gif)
Like this, this is the Listary I was using before. Because I prefer to use the mouse to select the things searched, drag and drop may be simpler; after all, it takes two clicks to press the keyboard

**Comment by taooceros** [comment]
I would like to have this feature as well. Will implement it after a while.

**Comment by taooceros** [comment]
@Lyn6969 finally this is implemented and merge into dev. You can try with the latest prerelease.
