### ISSUE TITLE
The Shell plugin cannot parse file directory that contains blanks

### ISSUE THREAD

**Issue by a224515a** [Flow-Launcher/Flow.Launcher#1085]
**Describe the bug/issue**
The plugin `Shell` cannot handle the file directory that contains blanks.

**To Reproduce**
1. type `> mklink "root\..path1" "root\..path2"`, where path1 (path2) is the file directory containing blanks.
2. 
3. ...

**Screenshots**

**Your System**
```
Windows build number: 10.0.19044.1586
Flow Launcher version: 1.93
```

**Comment by jjw24** [comment]
Is this issue for both PowerShell and cmd prompt?

**Comment by a224515a** [comment]
cmd, in my case.
(sorry I am not familiar with PowerShell)

**Comment by a224515a** [comment]
this problem did not occur when using PowerShell.

hope it will be fixed soon.

**Comment by taooceros** [comment]
I will give it a fix today.

**Comment by jjw24** [comment]
Fix is now in pre-release version :)
