### ISSUE TITLE
Is it coming on Linux anytime soon?

### ISSUE THREAD

**Issue by anup514** [Flow-Launcher/Flow.Launcher#1090]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by taooceros** [comment]
It will wait to Flow 2.0 (when we change the whole framework). We haven't decided whether to use winui or some cross platform ui for 2.0, so I cannot make a answer for now. However, it should be quite far from now.

**Comment by hamzakat** [comment]
> It will wait to Flow 2.0 (when we change the whole framework). We haven't decided whether to use winui or some cross platform ui for 2.0, so I cannot make a answer for now. However, it should be quite far from now.

Any updates on the upcoming version? will we be able to use the existing plugins in Flow 2.0?

**Comment by jjw24** [comment]
No, not anytime soon, the focus is on Windows. There are good alternatives for Linux.

**Comment by Garulf** [comment]
> > There are good alternatives for Linux.
> 
> 
> 
> suggestions?
> 
> 
> 
> 

Rofi/Wofi may be your best bet?
