### ISSUE TITLE
Plugin to interact with Raindrop

### ISSUE THREAD

**Issue by fnfontana** [Flow-Launcher/Flow.Launcher#1092]
**Is your feature request related to a problem? Please describe.**

A plugin capable to connect to Raindrop.io and search saved item items and favorites. 

**Describe the solution you'd like**

After type a keyword (e.g. rd), the plugin will connect to Raindrop and search my collection of saved items and favorites. 
Will be very interest to have the capability of opening directly in the browser or in the raindrop desktop app. 

**Describe alternatives you've considered**

I know that for the macOS users, there's an app named Alfrad that is similar to Flowlancher and capable of search in Raindrop favorites. Would be very useful to have this functionality in Flow Launcher for us Windows users as well.

**Comment by Garulf** [comment]
Hello @fnfontana !

Thank you for bringing this application to my attention! I was able to piece together a plugin (with help from the python-raindropio package) that searches and launches items from your Raindrop.io account.

It has been submitted to the Plugin store and at this time awaiting approval. You may manually install by typing: 
```
pm install https://github.com/Garulf/Flow-Raindrop/releases/download/v0.0.1/Flow-Raindrop.zip
```
(Note: You would need Flow Launcher v1.9.1 or higher for this method to work.)

Once installed you will need to provide an API key in settings to access your account.

Screenshots:
![image](https://user-images.githubusercontent.com/535299/159684874-f320c2fc-4efd-45a4-a0f6-3772f928942b.png)

![image](https://user-images.githubusercontent.com/535299/159684903-e321dbc6-c54f-4e9c-9b2b-db00e968c5c0.png)

![image](https://user-images.githubusercontent.com/535299/159684936-5fea4f47-87b1-488d-af0a-1f430efbe321.png)

**Comment by fnfontana** [comment]
You're fantastic Garulf! I will test it!
