### ISSUE TITLE
CTRL + ENTER can't open the containing folder

### ISSUE THREAD

**Issue by fanhwid** [Flow-Launcher/Flow.Launcher#1094]
Version: 1.93
Everything plugin 1.7.2
When search a file like a .docx or .mp3 file, "CTRL+ENTER" can't open the containing folder,  instead, the file was justed opened directly.
But when search a file like .pdf or .xlsx file, "CTRL+ENTER" worked correctly.

**Comment by taooceros** [comment]
I guess it is because the .docx and .mp3 files are searched by the explorer plugin? Probably the everything plugin don't support ctrl+enter.

**Comment by deefrawley** [comment]
Hi @fanhwid - you opened an issue for this that is currently in the Everything plugin repo [here](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/issues/44) . Closing this issue
