### ISSUE TITLE
How to test a own Plugin? Documentation is incomplete! 

### ISSUE THREAD

**Issue by LouisMehring** [Flow-Launcher/Flow.Launcher#1100]
Hey guys, 
How exactly can I test my plugin? 
I created a Zip with the release.ps1 file but with Wox I could drag and drop it to the search field but this doesnt work in Flow Launcher sadly. 
Thank you already for helping me! 

Best regards,
Louis

**Comment by Garulf** [comment]
We had a similar discussion here: https://github.com/Flow-Launcher/Flow.Launcher/discussions/1033

No need to zip your plugin for testing. Just make sure you have a proper `plugin.json` file and restart Flow Launcher for it to detect your plugin.

**Comment by jjw24** [comment]
Closing, please feel free to re-open if wishing to discuss further.
