### ISSUE TITLE
add choco installer package (winget and scoop already available)

### ISSUE THREAD

**Issue by datadu-de** [Flow-Launcher/Flow.Launcher#1106]
**Describe the solution you'd like**

`choco install flowlauncher`

;-)

**Comment by Garulf** [comment]
Someone was able to parse winget to make a plugin?

**Comment by jjw24** [comment]
Hey there, It's wip atm, just haven't got around to finishing it off. Will do soon so closing this pr for now.

**Comment by jjw24** [comment]
https://github.com/Flow-Launcher/chocolatey-package
