### ISSUE TITLE
add an auto paste to the search bar.

### ISSUE THREAD

**Issue by ghost** [Flow-Launcher/Flow.Launcher#1110]
when copy something want to search.  there need 3 step. copy. alt+space. paste. This is very inefficient. i hope can add a new feature that auto paste to the search bar. 
eg. When you open search bar, the latest clipboard contents within five seconds are automatically copied into it.
utools is a similar tools in chinese implemented this feature. there also a lot feature that can be referenced. 
https://u.tools/

**Comment by taooceros** [comment]
I like the idea. Probably I will implement it in the future.

**Comment by VictoriousRaptor** [comment]
> I like the idea. Probably I will implement it in the future.

I'm trying to implement it. But I found some confict with Last Query Style when it's set to Select Last Query or Preserve. What if the clipboard is not empty? Preserve/select last query or use the clipboard/

**Comment by taooceros** [comment]
> > I like the idea. Probably I will implement it in the future.
> 
> I'm trying to implement it. But I found some confict with Last Query Style when it's set to Select Last Query or Preserve. What if the clipboard is not empty? Preserve/select last query or use the clipboard? Or only auto paste when Empty last query?

Let's assign it an extra keyword. 
![image](https://user-images.githubusercontent.com/45326534/193659956-de685b11-864d-4654-9445-454671820268.png)
maybe make a variable like `{copy}` or `{paste}` here to do the job?

**Comment by VictoriousRaptor** [comment]
> > > I like the idea. Probably I will implement it in the future.
> > 
> > 
> > I'm trying to implement it. But I found some confict with Last Query Style when it's set to Select Last Query or Preserve. What if the clipboard is not empty? Preserve/select last query or use the clipboard? Or only auto paste when Empty last query?
> 
> Let's assign it an extra keyword. ![image](https://user-images.githubusercontent.com/45326534/193659956-de685b11-864d-4654-9445-454671820268.png) maybe make a variable like `{copy}` or `{clipboard}` here to do the job?

What about make it a plugin? Auto-fill is easy but monitoring clipboard changes requires `MainWindow` derived from a monitoring class.

**Comment by taooceros** [comment]
I don't think there's need to monitor the clipboard? Just invoke a Ctrl+c and get the first Result of clipboard?

**Comment by VictoriousRaptor** [comment]
> I don't think there's need to monitor the clipboard? Just invoke a Ctrl+c and get the first Result of clipboard?

Well he wants to auto paste text that copied to clipboard within last 5 seconds. I did some research and it's too hard for a unexperieneced c# user like me. :(

**Comment by taooceros** [comment]
I don't think that's a good design Though (convince me if you think it is). A better way is to use a different set of hotkey to paste copied text.

**Comment by taooceros** [comment]
> > I don't think that's a good design Though (convince me if you think it is). A better way is to use a different set of hotkey to paste copied text.
> 
> 
> 
> Me too. It's too complicated.
> 
> 
> 
> > maybe make a variable like {copy} or {clipboard} here to do the job?
> 
> 
> 
> Does query or actionkeyword support variable? I can't see any reference.

Expand the variable before the query? See my shortcut pr for an example.

**Comment by VictoriousRaptor** [comment]
> > > I don't think that's a good design Though (convince me if you think it is). A better way is to use a different set of hotkey to paste copied text.
> > 
> > 
> > Me too. It's too complicated.
> > > maybe make a variable like {copy} or {clipboard} here to do the job?
> > 
> > 
> > Does query or actionkeyword support variable? I can't see any reference.
> 
> Expand the variable before the query? See my shortcut pr for an example.

Got it. Look like we need to merge that first.

**Comment by jjw24** [comment]
Available in 1.12.1
