### ISSUE TITLE
How to set the height of item in theme?

### ISSUE THREAD

**Issue by MasouShizuka** [Flow-Launcher/Flow.Launcher#1111]
I want to change the font size of item, but if I set a big font size, it would like as below:
![image](https://user-images.githubusercontent.com/44764707/161408690-878baf03-1024-4b8b-9bc7-4c6831518d75.png)

So I want to change the height of each search item, as below:
![image](https://user-images.githubusercontent.com/44764707/161408640-f47c9f8e-9575-4c6a-a058-eae02c797beb.png)
However, I can't find the related property in docs.

Query box has `Height` in `QueryBoxStyle`, so can set the height of querybox.

So is there any property to change the height of item?

**Comment by taooceros** [comment]
@onesounds

**Comment by onesounds** [comment]
There is a slight problem with this part, so it cannot be set in the theme at this time.
I think it would be nice to have this function, so I'll work on it.
