### ISSUE TITLE
Results are not shown when typing in Vietnamese keyboard layout

### ISSUE THREAD

**Issue by qhs11390** [Flow-Launcher/Flow.Launcher#1112]
**Describe the bug/issue**
Flow Launcher doesn't show results when i type in Vietnamese keyboard layout. I have to press Arrow keys or Spacebar in order to make it work.
*I tried with Chinese and French keyboard layout and it works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/87928635/161414886-babfcf0f-c89e-4f04-a8b7-08a5cdf8b0a9.png)

**System**
```
Windows build number: 10.0.22000.593
Flow Launcher version: 1.9.3
```

**Comment by taooceros** [comment]
I don't think we are able to fix this, since it it because the Vietnamese keyboard layout don't post the word to the text block until a space or an arrow.
