### ISSUE TITLE
Possibility to add a window switcher (in addition of application launcher).

### ISSUE THREAD

**Issue by alexandrenavarro** [Flow-Launcher/Flow.Launcher#1118]
Possibility to add a window switcher (in addition of application launcher).

For example, 
- On linux, Rofi (https://github.com/davatorium/rofi) does that.
- On windows, there is Switcheroo (https://github.com/kvakulo/Switcheroo) but it does only the window switcher, not application launcher.

Maybe it should a plugin activable or not.

Don't hesitate if it is not clear.

**Comment by deefrawley** [comment]
Hi @alexandrenavarro ,

Try the Window Walker plugin - https://github.com/taooceros/Flow.Plugin.WindowWalker

In Flow:

`pm install window walker`

**Comment by alexandrenavarro** [comment]
Thank you, it is what I'm searching.
