### ISSUE TITLE
Python plugin development- No module named 'demjson' from importing FlowLauncher

### ISSUE THREAD

**Issue by danielduckworth** [Flow-Launcher/Flow.Launcher#1126]
**Describe the bug/issue**

I'm writing a plugin using Python and the Hello World as a starting point. I'm importing FlowLauncher using lib.flowlauncher but I get an error when it tries to import demjson.

**Traceback**
Traceback (most recent call last):
  File "i:\Google Drive\Programming\03 Projects\notion-search\Flow.Launcher.Plugin.NotionSearch\main.py", line 8, in <module>
    from lib.flowlauncher import FlowLauncher
  File "i:\Google Drive\Programming\03 Projects\notion-search\Flow.Launcher.Plugin.NotionSearch\lib\flowlauncher\__init__.py", line 3, in <module>
    from .FlowLauncher import FlowLauncher
  File "i:\Google Drive\Programming\03 Projects\notion-search\Flow.Launcher.Plugin.NotionSearch\lib\flowlauncher\FlowLauncher.py", line 7, in <module>
    import demjson
ModuleNotFoundError: No module named 'demjson'

Any help would be much appreciated.

**Comment by jjw24** [comment]
Hey how's it going?

Could this be due to needing to pip install demjson on its own?

@Garulf

**Comment by danielduckworth** [comment]
I'm trying to follow the advice on the docs which suggests that the user doesn't need to have the modules pip installed if they are imported from a sub directory.

[https://www.flowlauncher.com/docs/#/py-develop-plugins](https://www.flowlauncher.com/docs/#/py-develop-plugins)

**Comment by Garulf** [comment]
Demjson is a requirement of the Flow Launcher Python package. If you’re pip installing the package it should be installing all requirements. 

What command are you using to pip install?

**Comment by danielduckworth** [comment]
I've got it installed and working in the dev environment. But I got the error when trying to run the plugin with the desktop app.

I've re-structured it based on some other plugins so I'll give it another go.

On a side note, how do I access a user setting from the flow launcher desktop app?

**Comment by danielduckworth** [comment]
> Can you link your code and possibly folder tree?

Yep, I'll do some editing and publish a repo soon.

**Comment by Garulf** [comment]
> On a side note, how do I access a user setting from the flow launcher desktop app?

The Flow Launcher package does not support accessing FLow's settings or user settings at this time. I have a project in progres that does have access to both.

https://github.com/Garulf/Flox

You can see an example in one of my plugins using settings here: https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/blob/main/plugin/main.py

**Comment by danielduckworth** [comment]
> The Flow Launcher package does not support accessing Flow's settings or user settings at this time. I have a project in progress that does have access to both.

Excellent! Thanks.

**Comment by danielduckworth** [comment]
@Garulf @jjw24  I've published an initial public repo for the plugin. This is my first Flow Launcher project so I'm a bit of a newbie and it needs some work.

[https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch)

**Comment by Garulf** [comment]
Looks good!! Notion looks very interesting!

**Comment by jjw24** [comment]
> @Garulf @jjw24 I've published an initial public repo for the plugin. This is my first Flow Launcher project so I'm a bit of a newbie and it needs some work.
> 
> https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch

Tested it out (you can do a manual install with `pm install <url to your zip>`), it is missing the requests module, which will be fixed by adding 'requests' to the requirements.txt.

Once you are ready don't hesitate to PR it to the PluginsManifest repo so it can be added to the Plugin Store.

**Comment by jjw24** [comment]
> I'm trying to follow the advice on the docs which suggests that the user doesn't need to have the modules pip installed if they are imported from a sub directory.
> 
> https://www.flowlauncher.com/docs/#/py-develop-plugins

Please feel free to update the documentation if something is not on point.

**Comment by jjw24** [comment]
Just for clarity on the solution to this issue, I think the problem was because the required packages 'flowlauncher' was not added to requirements.txt, which then the GitHub action did not install and include in the zip.

**Comment by jjw24** [comment]
Closing since no further discussion required, feel free to reopen if not the case :)
