### ISSUE TITLE
ESC to clear query, then ESC to close the launcher

### ISSUE THREAD

**Issue by HandwerSTD** [Flow-Launcher/Flow.Launcher#1133]
**Is your feature request related to a problem? Please describe.**

Sometimes I have to use other apps with the query in the launcher kept. This can be done by changing"Last Query Style". However, in this case, when I really want to clear the query, I can only select all and delete.

The two features (keeping or deleting the query) are both frequently-used for me, which is quite annoying when I have to lose one of them.

**Describe the solution you'd like**

Like macOS Spotlight Search, query in the launcher is kept by default. Pressing ESC for the first time clears the query, and pressing ESC for the second time closes the window. When you want to hide the window without clearing the query, simply click on other apps.

**Describe alternatives you've considered**

I've tried to set ESC as the hotkey of clearing query (quering nothing). But this conflicts with closing the window, which means, I cannot close the window using ESC after that.

**Additional context**

I can provide example videos if needed.

**Comment by jjw24** [comment]
There is another option in the 'Last Query Style which highlights the last query (don't remember the name), this then allows you to continue typing the next query, clear with a backspace or add onto the query with the right arrow, this option doesn't work?

**Comment by HandwerSTD** [comment]
> There is another option in the 'Last Query Style which highlights the last query (don't remember the name), this then allows you to continue typing the next query, clear with a backspace or add onto the query with the right arrow, this option doesn't work?

I've tried that, and the function does work well. However, I have been used to having a cleared window to type into...😂😂😂 just like Spotlight Search. So...maybe this is just my personal preference😂😂😂

**Comment by jjw24** [comment]
This won't be addressed as it comes down to personal preference and the option provided by last query style is sufficient.
