### ISSUE TITLE
Error:Unable to download the plugin

### ISSUE THREAD

**Issue by HardwayLinka** [Flow-Launcher/Flow.Launcher#1143]
When i attempt to download whatever plugin in the plugin store, this application popup this error 👇
![image](https://user-images.githubusercontent.com/45873697/164874618-8549baaa-c0e4-4409-8d69-c5046ff481d1.png)

My os is Win11.I think it's better to popup some precise error info when error happened which may help me find the correspond solution on Google.

**Comment by jjw24** [comment]
Hey how's it going. Can you check and attach the logs please- type `open logs`
