### ISSUE TITLE
Selected a different theme and updated to 1.9.3 but still had the old theme

### ISSUE THREAD

**Issue by kumar007git** [Flow-Launcher/Flow.Launcher#1150]
I had 1.9.2. I changed the theme from Metro to a different theme. Then I updated to 1.9.3. When I called the search box it was still the old theme.

1. Change theme in settings
2. Update to 1.9.3
3. Launch search box

**Your System**
```
Windows build number: (run "ver" at a command prompt) Windows 10, Build 19044.1645
Flow Launcher version: (Settings => About)  1.9.3
```
thanks.

**Comment by deefrawley** [comment]
Hi, were you running the portable install, or the full install?

**Comment by kumar007git** [comment]
yes, I was running portable version.

**Comment by deefrawley** [comment]
Did it keep your plugins after the upgrade?

**Comment by kumar007git** [comment]
yes, it did. I am not so much worried about this issue. I set the settings again in new version.

**Comment by taooceros** [comment]
I guess it is because of the update doesn't trigger save setting. I will give it a check recently.
