### ISSUE TITLE
Having the "Start button" as Hotkey leads to "Touchpad Three finger tap" working as Hotkey as well

### ISSUE THREAD

**Issue by SIVAH-AKASH** [Flow-Launcher/Flow.Launcher#1151]
I have changed my Hotkey to Start (which appears as "Win + LWin" in the Hotkey field). The popup appears perfectly fine when I click Start after that, but the popup also appears when I Three-finger-tap my laptop touchpad as well (which is currently mapped to 'Middle click' in Windows settings).

**Comment by taooceros** [comment]
Currently I don't believe that work. Quite a few effort is needed to implement this.

**Comment by taooceros** [comment]
duplicate of #662

**Comment by SIVAH-AKASH** [comment]
I was able to get the Start button to launch Flow Launcher by disabling the inbuilt Windows Start menu.

But that brings the problem I mentioned in this issue.

**Comment by taooceros** [comment]
oh I see. what do you mean by triple click? click with three fingers? My touchpad is set to open the start menu by default. Can that be an issue?

**Comment by SIVAH-AKASH** [comment]
My bad. I meant tap with three fingers (edited the issue topic).

I have mapped it to middle-click, so I don't think that's the issue.

**Comment by taooceros** [comment]
> My bad. I meant tap with three fingers (edited the issue topic).
> 
> 
> 
> I have mapped it to middle-click, so I don't think that's the issue.

Dry for the late reply. I think you can map triple tap to flow's key board shortcut that is (e.g. alt space).

**Comment by SIVAH-AKASH** [comment]
@taooceros, wouldn't I need a separate app for that?

**Comment by taooceros** [comment]
> @taooceros, wouldn't I need a separate app for that?

I don't think so. I remembered Windows allow you to have this kind of customization (i have set left right swap to be copy and paste). Though i think the option is kindly hidden.

**Comment by jjw24** [comment]
It would be under windows settings, maybe 'Touchpad', where you can set finger gestures and assign them to keyboard shortcuts, I think that's what you mean right @taooceros.

**Comment by TheBestPessimist** [comment]
hey @SIVAH-AKASH 3 finger tap = middle click is suuuuper weird implemented by Microsoft.

I have captured that behaviour in a commit for myself here: https://github.com/TheBestPessimist/AutoHotKey-Scripts/commit/487448281fe09ad6f8b1d74a83632fbe2d5280d6

Basically, M$ is sending all modifier keys as "down" event before sending middle click, then sending them in reverse as "up" event after the middle click. 
It does that every time you 3 finger tap middle click. 

Why? `¯\_(ツ)_/¯` ask microsoft why did it make it so retarded.
