### ISSUE TITLE
Flow-Launcher not removed entirely from Windows 11 after uninstalling it

### ISSUE THREAD

**Issue by tabrez** [Flow-Launcher/Flow.Launcher#1152]
**Describe the bug/issue**
I have uninstalled `Flow Launcher` app from my Windows 11 machine, restarted the machine several times but it still pops up when I press the alt-space key combo. I've searched & deleted all files/folders named `Flow Launcher`, there's no `Flow Launcher` icon in the system tray, but nothing seems to help with complete removal of `Flow Launcher` from my machine.

**To Reproduce**
1. Install `Flow-Launcher` using `winget install flow-launcher`
2. Uninstall `Flow-Launcher` using `winget uninstall flow-launcher`. Double-check it's gone from "Add or Remove Programs" in Control Panel. Make sure there's no icon related to Flow Launcher in the system tray.
3. Restart Windows machine
4. Search and delete everything related to `Flow Launcher` from Windows Explorer/`Everything` tool
5. Restart Windows machine

**Screenshots**
After uninstalling the app & restarting the machine:
winget output: https://gfycat.com/antiquewetbabirusa
Add or Remove Programs: https://gfycat.com/sharppaleeuropeanfiresalamander
Start Menu search: https://gfycat.com/simplisticshabbybobwhite
Flow Launcher: https://gfycat.com/simplisticshabbybobwhite

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.613]
Flow Launcher version: 1.9.3 (can't see it from Flow Launcher Settings -> About as the app is technically uninstalled but winget showed this version when I had installed it) 
```
**Flow Launcher Error Log**
I've deleted all files related to Flow Launcher from my disk.

**Comment by jjw24** [comment]
Do you have PowerToys installed? Show us a screenshot after pressing alt+space

**Comment by tabrez** [comment]
Yes, I've Powertoys installed(version 0.57.2)
screenshot after pressing alt+space: https://gfycat.com/ordinaryhighlevelduckbillcat
Is this Powertoys?

**Comment by jjw24** [comment]
That's PowerToys Run not flow :)

**Comment by tabrez** [comment]
My sincere apologies! I had never used this alt+space feature of Powertoys before, didn’t know that’s what it is. Thanks for the help.
