### ISSUE TITLE
Node.js environment support

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1157]
Same setup method as Python:
1. Add recognition of Node.js plugins - JavaScript and TypeScript plugins,
2. Download and extract the Node.js portable installation to UserData folder. 
3. Allow user to set their own path via Settings UI.
4. Submit changes to existing TS/JS plugins to utilize the Node.js set up.

**Comment by duurland** [comment]
https://github.com/google/zx

**Comment by duurland** [comment]
Just dropping these links here in case there's any interest for alternative JS environments.

**Deno** https://deno.land/
> Deno is a simple, modern and secure runtime for JavaScript, TypeScript, and WebAssembly that uses V8 and is built in Rust. -- single executable, supports TypeScript out of the box

**QuickJS** https://bellard.org/quickjs/
> QuickJS is a small and embeddable Javascript engine. It supports the [ES2020](https://tc39.github.io/ecma262/) specification including modules, asynchronous generators [..] -- Small and easily embeddable: just a few C files, no external dependency, 210 KiB of x86 code for a simple hello world program.

**Google ZX** https://github.com/google/zx
> A tool for writing better scripts -- JavaScript is a perfect choice, but standard Node.js library requires additional hassle before using. The zx package provides useful wrappers around child_process, escapes arguments and gives sensible defaults.

**Comment by jjw24** [comment]
> Just dropping these links here in case there's any interest for alternative JS environments.
> 
> **Deno** https://deno.land/
> 
> > Deno is a simple, modern and secure runtime for JavaScript, TypeScript, and WebAssembly that uses V8 and is built in Rust. -- single executable, supports TypeScript out of the box
> 
> **QuickJS** https://bellard.org/quickjs/
> 
> > QuickJS is a small and embeddable Javascript engine. It supports the [ES2020](https://tc39.github.io/ecma262/) specification including modules, asynchronous generators [..] -- Small and easily embeddable: just a few C files, no external dependency, 210 KiB of x86 code for a simple hello world program.
> 
> **Google ZX** https://github.com/google/zx
> 
> > A tool for writing better scripts -- JavaScript is a perfect choice, but standard Node.js library requires additional hassle before using. The zx package provides useful wrappers around child_process, escapes arguments and gives sensible defaults.

Deno sounds desirable, any experience in using that? Is it preferable to Nodejs?
