### ISSUE TITLE
Support PATH environment variables when searching for tools

### ISSUE THREAD

**Issue by giggio** [Flow-Launcher/Flow.Launcher#116]
**Describe the solution you'd like**

I have several tools installed with Chocolatey that end up on my path, but are not indexed by Flow Launcher, and also other tools that I drop at `~/bin`, for example. I need Flow Launcher to find those.

**Describe alternatives you've considered**

`Windows+R` and the shell plugin both work, but they don't auto complete.

**Additional context**

Using latest version, `1.1.2`.

**Comment by jjw24** [comment]
I think I might know what the issue is, so I can repro, can you give me a tool as an example

**Comment by giggio** [comment]
Sure, just download any tool which Chocolatey. I use Sysinternals: https://chocolatey.org/packages/sysinternals

If you don't want to install Chocolatey, just download "Process Explorer" directly (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and add it to your path somehow. I suggest creating a tools directory somewhere (like 'c:\tools'), add it there, and add to the path.

**Comment by Jaykul** [comment]
Yeah, I came to ask for this.

We can **work around** this (on a case-by-case basis) by manually adding `C:\ProgramData\Chocolatey\bin` to the Programs plugin. But really, the Proram plugin should (have a checkbox to) automatically search all the folders in my PATH environment variable (and should re-parse that variable on startup each time)

![image](https://user-images.githubusercontent.com/192942/163919647-cd3a2815-634b-47d3-a954-94cd0952a4cc.png)
