### ISSUE TITLE
Bug, the sound effect will lose efficacy sometimes and will take effect when I restart my PC. 

### ISSUE THREAD

**Issue by cobition** [Flow-Launcher/Flow.Launcher#1161]
**Describe the bug/issue**
Bug, the sound effect will lose efficacy sometimes and will take effect when I restart my PC.
**To Reproduce**
1. ...
2. ...
3. ...

**Screenshots**

**Your System**
``` windows11 21H2 22000.652
Windows build number: (run "ver" at a command prompt)
Flow Launcher version: (Settings => About) 
```
**Flow Launcher Error Log**

**Comment by deefrawley** [comment]
What does "lose efficacy" mean?

**Comment by cobition** [comment]
> What does "lose efficacy" mean?

It means there is no sound effect when I activate Flow-Launcher, and the  ''Sound Effect'' is on

**Comment by deefrawley** [comment]
Is it possible your sound device or even speakers have gone into a sleep mode sometimes?

**Comment by taooceros** [comment]
Hmm I forget whether this has been solved. I will check recently....

**Comment by cobition** [comment]
Hi, this problem has been solved !



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Kevin ***@***.***> |
| Date | 02/01/2023 10:44 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Flow-Launcher/Flow.Launcher] Bug, the sound effect will lose efficacy sometimes and will take effect when I restart my PC. (Issue #1161) |

Hmm I forget whether this has been solved. I will check recently....

**Comment by taooceros** [comment]
Thanks for checking!
