### ISSUE TITLE
AVG antivirus reported that FL is infected with IDP.Generic, and quarantined it

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1177]
**Describe the bug/issue**
AVG antivirus reported that FL is infected with IDP.Generic, and quarantined it

**To Reproduce**
Since this is a response from AVG, I cannot reproduce it manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/9047168/166625488-fcb8b3f8-9ef9-42b1-bfe8-37aa0a35b9ed.png)

**Your System**
```
Windows 10 Home, 64 bit 
Version	10.0.19044 Build 19044


 
```
**Flow Launcher Error Log**

**Comment by deefrawley** [comment]
Hi. There is no malicious code in Flow or any of the installs. It would be great if you could raise a false positive report with Avast.

**Comment by raindropsfromsky** [comment]
Sorry, I am unable to enclose the log, because I am unable to find the specified folder for the logs.

Since I am using the portable mode,  its logs is supposed to be at : 
%LocalAppData%\FlowLauncher\<App-Version>\UserData\Logs\<version>\<date>.txt

My File Manager (FreeCommander) resolves the path **%LocalAppData%\FlowLauncher\** to-
C:\Users\naray\AppData\Local\FlowLauncher

However, this folder does not have a subfolder called **UserData** at all.
(The entire directory below it is missing). I wonder if AVG deleted it??

Instead, it has a subfolder called "app-1.9.3".
This is strange: I expected it to be "app-1.10.0"!

**FWIW, here is some information that may be significant:**
Previous to downloading 1.10.0, I already had the 1.9.3 version installed (with installer).
I downloaded 1.10.0 two days ago, and to avoid any malfunctions, I exited from 1.9.3.
Now I am using 1.10.0 exclusively.

The log for 1.9.3 is two days old, in the following path:
 C:\Users\naray\AppData\Roaming\FlowLauncher\Logs\1.9.3
Since I had stopped using 1.9.3 two days ago, this sounds logical.

**Comment by taooceros** [comment]
The 1.10.0 is not yet 1.10.0, it will be when we want to release the official version. I don't believe the log includes useful information for antivirus, but feel free to upload them.

**Comment by deefrawley** [comment]
Use this link, no log file needed

https://www.avast.com/false-positive-file-form.php

As pointed out by others v1.10 is a preview of the upcoming release to test new features. Latest stable is v1.9.3

**Comment by raindropsfromsky** [comment]
Thanks for this link. I had already filed a false positive report with AVG, and I provided mode details to the AVG agent who contacted me. 

although I didn't receive any closing mail from him, AVG updated its virus definitions, and FL has started working now. It seems that AVG has taken FL off the list.

**Comment by raindropsfromsky** [comment]
AVG has officially cleared FL from its virus database.
If anyone faces a problem, they recommend downloading and re-installing the latest version.

**Comment by deefrawley** [comment]
Thanks @raindropsfromsky - appreciate your help for the Flow project
