### ISSUE TITLE
When the 1.10.0 portable is unzipped, its directory has folders named as 1.9.3, and it runs as 1.9.3

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1178]
**Describe the bug/issue**
When the 1.10.0 portable is unzipped, its directory has folders named as 1.9.3, and it runs as 1.9.3 only.

**To Reproduce**
Unzip the zip file. 
Check out its structure. 
The folders are named 1.9.3 (should be 1.10.0)

**Screenshots**

**Your System**
Windows 10 Home, 64 bit.
Version 10.0.19044 Build 19044

**Comment by taooceros** [comment]
By design to allow later auto update to official version.
