### ISSUE TITLE
When a plugin is downloaded and installed, please show its name in the notification popup near System Tray

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1189]
When a plugin is installed, two popups appear one after another:

![image](https://user-images.githubusercontent.com/9047168/167259477-3f1f3035-ec70-44fb-8ef2-ef1f02da2150.png)
![image](https://user-images.githubusercontent.com/9047168/167259566-085d03de-1289-454f-a29a-28aecfe0e835.png)

But these boxes do not show the name of the plugins being installed.
This is a little unexpected. (But not a big bug, of course)

The messages are generic.

Instead of "plugin", please insert the name of the plugin in both messages.

**Describe alternatives you've considered**

**Additional context**

**Comment by jjw24** [comment]
Good pickup 👍
