### ISSUE TITLE
Exact wording: Flow Launcher vs FlowLauncher

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#12]
Is it `Flow Launcher`?

**Comment by jjw24** [comment]
Flow Launcher is the full name, 

FlowLauncher/flowlauncher/flow.launcher/flow.launcher is used only in code,

Flow is the nickname 

Let me know if it makes sense, or you have a suggestion.

**Comment by Kalaschnik** [comment]
No that’s perfect. Just wanted this to be clear.
