### ISSUE TITLE
Not Launching [app not opening]

### ISSUE THREAD

**Issue by GreyHatGod15** [Flow-Launcher/Flow.Launcher#1215]
The Flow Laucher app never launched

**To Reproduce**

1. Open app

**Screenshots**
![Annotation 2022-05-20 143954](https://user-images.githubusercontent.com/77605763/169495565-6234bf41-3016-4dc8-a2ef-46924b209f9c.png)

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.18362.1082]
Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**
bruh the app is not opening at all

**Comment by Garulf** [comment]
Please paste any log file output from this folder:
```
%appdata%\FlowLauncher\Logs\1.9.3
```
