### ISSUE TITLE
FL cannot detect new files for an unknown length of time

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1219]
**Describe the bug/issue**
FL cannot detect new files for an unknown length of time after the file is created.

**To Reproduce**
1. Download a file Or create a new file
3. Launch FL, and search for the same file name
4. Observe that most often FL cannot detect the newly created file.
5. Wait for some time. Repeat step 3 again. FL still does not show the result. <br> In fact, it is difficult to tell when FL detects it. <br>There is no visual indication that the indexing is refreshed. [BUG]<br> There is no manual command to refresh the index. 
 
Note that I have installed both **Explorer** and **Everything** plugins, and both are turned on.
As a result, I see double entries in the search results. 
Yet the new file is not detected, which means both plugins are failing simultaneously (??).

**Screenshots**
-NA-

**Your System**
Windows 10 Home, 64 bit
FL: 1.10.0 beta

**Flow Launcher Error Log**

**Comment by jjw24** [comment]
> There is no visual indication that the indexing is refreshed. [BUG]

There is not much we can do about this I think unless Windows Search Or Everything service provides API library to query (I have not checked). I think the expected behaviour should be newly created files/folders should show up in flow within seconds by default.

**Comment by jjw24** [comment]
@raindropsfromsky is this still happening to you with newly created files? 

It's not normal that both Explorer and Everything fail to find them though.

**Comment by raindropsfromsky** [comment]
I checked this by reaming an existing file and then immediately searching for that new name using Flow.
I am able to see the new name immediately.
I see only one name, though.
So I conclude that only one of the two plugins is working immediately.

**Comment by jjw24** [comment]
Can you shift enter on that result to go to context menu then scroll down to the last result to double check if it is from the Everything plugin please.

Can you paste the new file name into the windows search via pressing the Windows key and see if it comes up. This search is also using the windows indexing service. If it also doesn't come up, then it's the indexing settings (find via windows settings=>windows search) you need to take a look at, maybe the path to the file is not indexed or is excluded by the windows search.

**Comment by raindropsfromsky** [comment]
I launched Flow search, which showed me the last search result (a single result instead of the usual duplicate results I see). 
I pressed SHFT+Enter. 
The context window showed a list, in which the last entry was **Everything** (ALt+8).

But I did the same experiment again, and now I don't see any search results, even after close to 30 seconds.

I did it the third time, and two results appeared immediately.
I did a SHFT+Enter on both of them (one by one), and found that one is found by Everything, and the other is found by Explorer.

To conclude, the problem appears randomly.

**Comment by raindropsfromsky** [comment]
> it's the indexing settings (find via windows settings=>windows search) you need to take a look at, maybe the path to the file is not indexed or is excluded by the windows search.

I think this is not an issue, because all my experiments are in the same folder location: In my D drive.
(I have created this 500 GB logical partition on my 1 TB HDD. The C partition on the same physical drive has Windows 10 Home, and all 3rd party apps. The D drive has data.).

Thus the drive's discoverability is not a factor, AFAICT.

**Comment by taooceros** [comment]
I guess the issue is because of HDD won't allow windows and everything to easily index? I am not particularly sure about this. You can try whether you can search result directly in everything. If not, we cannot help.

**Comment by jjw24** [comment]
> > it's the indexing settings (find via windows settings=>windows search) you need to take a look at, maybe the path to the file is not indexed or is excluded by the windows search.
> 
> I think this is not an issue, because all my experiments are in the same folder location: In my D drive. (I have created this 500 GB logical partition on my 1 TB HDD. The C partition on the same physical drive has Windows 10 Home, and all 3rd party apps. The D drive has data.).
> 
> Thus the drive's discoverability is not a factor, AFAICT.

Basically the discovering of files is done by the Everything service and Windows indexing service running in the background, flow just displays those results, so might still be worthwhile pinpointing where the problem sits with.

Can you actually check if the file is not displayed by Everything plugin, whether it is displayed inside the actual Everything program? Also same for windows search method mentioned above.
