### ISSUE TITLE
Flow Launcher not launching or fully installing

### ISSUE THREAD

**Issue by modernminimalist** [Flow-Launcher/Flow.Launcher#1227]
**Describe the bug/issue**
2 issues:
1.Flow Launcher would not launch when I installed it. Please advise how to launch it. I would like to use this app

2.I uninstalled it from add or remove programs and now it is still showing up in the startup section of of task manager but I can't find any files to delete. Please advise to remove it.

**To Reproduce**
1. Download Flow Launcher EXE file and install
2. Try to launch with key combo, clicking shortcut icon, launching app from windows start menu and no response
3. Uninstall from "add or remove programs"  and restart
4. get frustrated that it is still showing up in task manager startup

**Screenshots**
![image](https://user-images.githubusercontent.com/74276888/171925317-36fb98fd-f5d7-499b-86b1-4f005c27aebc.png)

**Your System**
```
Edition	Windows 10 Home
Version	21H1
Installed on	‎11/‎8/‎2020
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

Flow Launcher version: (Settings => About) 
v1.9.3 downloaded and ran the setup.exe file here
https://github.com/Flow-Launcher/Flow.Launcher/releases/tag/v1.9.3

**Flow Launcher Error Log**
<!-- 
No log files
-->

**Comment by modernminimalist** [comment]
Log File
[2022-06-03.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8835077/2022-06-03.txt)

**Comment by modernminimalist** [comment]
Looks like there was an issue with a previous installation that didn't fully remove files.
After manually deleting left over flowlauncher files from C/users/name/appdata/roaming and C/users/name/appdata/local I was able to install the app to get it to work correctly. 
If possible please update the uninstall process to delete these files automatically

**Comment by taooceros** [comment]
I think the uninstall will delete all files automatically. Probably you have encountered some weird issues during that process. However, I do suspect whether it may remove the registry entry for auto startup, which is why you may see that in task manager. We may need to inspect on it somehow.

**Comment by jjw24** [comment]
> C/users/name/appdata/roaming

Files in this folder are designed to be kept as they are custom user setting files.

> C/users/name/appdata/local

Files in this folder should be all deleted but sometimes due to certain process still holding on the the folder the squirrel uninstaller leaves a .dead file which I think may be deleted on startup.

@modernminimalist do you remember what type of files were left over in C/users/name/appdata/local ?

**Comment by JPRial** [comment]
Having the same problem, and even deleted Registry keys

**Comment by omarashraf307** [comment]
I'm having the same issue
After upgrading from winget the app is not launching 
Uninstalled and reinstalled again and same problem
I even deleted every trace of it on the registry and tried to install it again but still not opening at all

**Comment by homemadestea58** [comment]
Same issue here, I've uninstalled and reinstalled Flow Launcher from the github exe and it still hasn't let me open the settings UI

**Comment by jjw24** [comment]
>Having the same problem, and even deleted Registry keys. When I try to re-install, .exe files doesn't execute properly and "installs" it in Local Appdata folder. It is, however, usable, but unable to open Settings.

Local AppData folder is where flow would be installed.

@JPRial @homemadestea58 Could you confirm if flow can be triggered via hotkey and then once flow window has appeared press 'ctrl + i', this is the hotkey that opens flow's settings. Alternatively flow can be opened via the Windows tray by right clicking on the icon. If settings window not appearing still after doing either action, please upload the log.

@omarashraf307 could you check if flow has been installed into the Local AppData folder. If it's installed there, open task manager and check after launching flow that the process has started. If still not starting, try the portable version as it does not require installation or backup then remove your user data so flow can start fresh.

**Comment by JPRial** [comment]
@jjw24 Actually, I haven't been running with these issue anymore. I did a full restart of my PC and installed Win 11. So I don't know if I can be helpful anymore. But, regarding your request, FL settigns does get trigger when hotkeys are pressed.
