### ISSUE TITLE
Flow causes malfunctioning of clipboard: The latest content does not go into clipboard!

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1237]
**Describe the bug/issue**
Flow causes malfunctioning of clipboard: The latest content does not go into clipboard!
Strangely, I have observed this pattern for URLs only.

**To Reproduce**

Note that this bug is not easy to reproduce, but it is consistent.

1. Select any text and press CTRL+C to copy it on clipboard
2. Paste it in any suitable software that accepts a text string. Check the result.
3. Copy a URL (from the address bar of a browser).
4. Switch to the software mentioned in step#2, and paste. <br>You see the older string, instead of the URL. **[BUG]**
6. Exit Flow. Try the same sequence of steps (1-4). <br> Now the URL appears as expected.

Note that Flow causes malfunction only after a few days of operation.
I mainly try to find pdf and video files.
Use **Enter** or **CTRL+Enter** commands on folders and files listed in the search results.
I use other plugins only occasionally (e.g. google search, unit conversion, etc.)
But I guess one of these operations may be messing up the clipboard.

I thought that the **Clipboard History** plugin may be causing this issue.
So I turned it off and then restarted the laptop.
But that did not solve the problem.

**Note:** 
I do not shut down my laptop at night, but put it to sleep. <br>I rarely restart the laptop.
In my case, Flow is launched on system startup.
This may be a relevant factor.

**Screenshots**

**Your System**
Windows 10 Home, 64 bit.
Version	10.0.19044 Build 19044

Flow Launcher version: (Settings => About) 
1.0.0 alpha (reported as 1.9.3)

**Flow Launcher Error Log**
Flow does not sense this as error. 
In fact, this problem does not happen inside Flow at all.
It causes problems outside.

I have faced this issue multiple times, and each time closing Flow solved the issue.
When I restart Flow, the problem does not reappear immediately.
But it starts happening after a few days.

**Comment by raindropsfromsky** [comment]
**Update:** I have turned off the **clipboard history** plugin. But the clipboard hijacking continues!
So the problem is NOT in that plugin code.

**Comment by taooceros** [comment]
> **Update:** I have turned off the **clipboard history** plugin. But the clipboard hijacking continues!
> 
> So the problem is NOT in that plugin code.
> 
> 

I am not really sure whether turn off may work. Would you try uninstalling it?
