### ISSUE TITLE
Autofocus when clicking on Win + R

### ISSUE THREAD

**Issue by ameenaltajer** [Flow-Launcher/Flow.Launcher#1242]
Hello guys,

There is a slight mishap with this plugin, if you click on Win + R for the first time, the focus is not set to the text box, leaving the user typing in whatever is active in the background, making sure that the focus set when the key combo is used is important.

I'm using:
Microsoft Windows [Version 10.0.19044.1766]

Best,
Ameen

**Comment by taooceros** [comment]
Hi Ameen,
Does it happen everytime or only the first time?

**Comment by taooceros** [comment]
Thank you! I will give it a check recently.

**Comment by jjw24** [comment]
Please try this prerelease build and let us know if the issue is fixed:
https://github.com/Flow-Launcher/Prereleases/releases/latest/download/Flow-Launcher-Portable.zip

**Comment by jjw24** [comment]
Some themes may have been renamed or updated. If you are still wanting the original one after trying out the new ones you can download the xaml files from here https://github.com/Flow-Launcher/Flow.Launcher/tree/v1.9.5/Flow.Launcher/Themes. Remember to place the downloaded file in the UserData theme folder so updating again won't lose them.

**Comment by ameenaltajer** [comment]
I tested it out, and I had the same problem, unfortunately.

**Comment by ameenaltajer** [comment]
Hey guys, just keeping you all updated, the bug is still happening.

**Comment by ameenaltajer** [comment]
Still happening, I'm running version 1.12.1.

**Comment by ameenaltajer** [comment]
Could it be because I have two monitors somehow?
