### ISSUE TITLE
Ctrl + Backspace (Hotkey to delete and entire word/ line seperated by a space or special char) Throws error

### ISSUE THREAD

**Issue by Brickmaster1** [Flow-Launcher/Flow.Launcher#1248]
**Describe the bug/issue**

**To Reproduce**
Ctrl + Backspace in the search bar and watch 

**Your System**
Win11
Specs: 
RTX 3080
Intel Core i7 9700K
RAM 32GB

Windows build number: Microsoft Windows [Version 10.0.22000.739]
Flow Launcher version: Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**
<!-- 
     The latest log file can be found here: %AppData%\FlowLauncher\Logs\<version>\<date>.txt
     or for portable mode: %LocalAppData%\FlowLauncher\<App-Version>\UserData\Logs\<version>\<date>.txt
     Drag and drop the log file below this comment.
-->

**Comment by jjw24** [comment]
Hey @Brickmaster1 are you using the pre-release build by any chance when you got this error?
