### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RealPacket** [Flow-Launcher/Flow.Launcher#1250]
## Specs
Intel core i73770
75 Hz monitor
Intel iGPU
16 GB DDR3 RAM
400 GB SSD
## Log File
[2022-06-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8992809/2022-06-27.txt)

**Comment by taooceros** [comment]
I wonder is windows index services enabled in your computer?

**Comment by RealPacket** [comment]
> I wonder is windows index services enabled in your computer?

no LOL

**Comment by taooceros** [comment]
> > I wonder is windows index services enabled in your computer?
> 
> 
> 
> no LOL

Then you are unable to use explorer index search. You can try everything plugin.

**Comment by taooceros** [comment]
We shall be able detect whether Windows index is enabled.

**Comment by jjw24** [comment]
> We shall be able detect whether Windows index is enabled.

Pretty sure it does detect when Windows index is disabled.
