### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by DaveZag** [Flow-Launcher/Flow.Launcher#1268]
---------------------------

---------------------------
Failed to register hotkey: Alt + Space
---------------------------
OK   
---------------------------

**Comment by jjw24** [comment]
Hey how's it going, this error likely due to your alt+space being taken up by another app, do you have PowerToys Run running by any chance?

**Comment by tejaskerai** [comment]
I have the same issue, flow launcher is not opening with alt+space, even though nothing is using those hotkeys

**Comment by jjw24** [comment]
Can you check for me if flow icon is in your taskbar tray(bottom right hand corner). If not can you check in task manager if you have the flow.launcher.exe process running please.

**Comment by tejaskerai** [comment]
Yes, flow launcher was not onthe taskbar tray, I think this was the problem. It is working now

**Comment by tejaskerai** [comment]
Hi, I still have this issue persisting time to time. One day it is working fine, the next day the flow icon is not in the task bar and fails to launch when I try to run the program.

**Comment by taooceros** [comment]
> Hi, I still have this issue persisting time to time. One day it is working fine, the next day the flow icon is not in the task bar and fails to launch when I try to run the program. 

Could you share the log (you can fine where the log is stored by the issue template)? Lets see whether we have some exception causing flow stop working.

**Comment by tejaskerai** [comment]
[2022-08-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9337289/2022-08-15.txt)
Heres the log

**Comment by taooceros** [comment]
> [2022-08-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9337289/2022-08-15.txt) Heres the log

The log doesn't involve useful information. I feel like either it is because the access is denied (because `alt+space` is a context menu hotkey hosted by windows), or some other program is using `alt+space`.

**Comment by jjw24** [comment]
> Hi, I still have this issue persisting time to time. One day it is working fine, the next day the flow icon is not in the task bar and fails to launch when I try to run the program.

Do you mind attaching the log after it fails to launch, might be some info there.

If the icon is not there, flow must have crashed some how.

**Comment by tejaskerai** [comment]
[2022-09-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9606557/2022-09-15.txt)
Log for when it crashed. When clicker FL icon, it still does not open

**Comment by tejaskerai** [comment]
Hey, any update on this? It looks like it happened again, and trying to relaunch it doesn't work

**Comment by jjw24** [comment]
Hi there, I haven't had a chance to look at this yet, this is not related to the original issue anymore let's break it out to a seperate one.

**Comment by jjw24** [comment]
Closing, the original issue is related to Flow's default hotkey ready in use.
