### ISSUE TITLE
The magnifying glass icon replaced by the icon of the plugin that matches the selected result

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1278]
The magnifying glass icon could be replaced by the icon of the plugin that matches the selected result.

So if there's query results from multiple plugins, you can select any of them with the arrow buttons and the icon on the top right will tell you what plugin was responsible for that result.

This will make it immediately clear to users what plugin produced the result as we have had several cases where the user mistaken the result coming from a different plugin. 

_Originally posted by @JohnTheGr8 in https://github.com/Flow-Launcher/Flow.Launcher/issues/54#issuecomment-632106091_

**Comment by Garulf** [comment]
Wait isn't this added in dev?

**Comment by Garulf** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/pull/911 This?

**Comment by jjw24** [comment]
That pr added the change only when the hotkey is used, I want to investigate if possible to change the magnifying glass just when a result is highlighted, which onesound mentioned has some technical/design issue but I want this as a reminder for me to take a look.

**Comment by taooceros** [comment]
As what i remember, he said this is not a good design. It's unlikely to be a technical issue.

**Comment by jjw24** [comment]
hmm ok.
