### ISSUE TITLE
[Feature Request] Time in Query box

### ISSUE THREAD

**Issue by nachmore** [Flow-Launcher/Flow.Launcher#1286]
## Problem

As a user who hides the Start menu I want quick and easy access to the time. I tend to use Flow to launch applications and shortcuts a lot, and it would be super convenient to have the time in the query box for quick, at a glance (essentially) access to the time.

### Proposed Solution

Time tastefully embedded in the query box (configurable in Settings).

### Alternatives

1. Just hitting Windows to bring up Start -> even on relatively powerful device this is super slow
2. Having some kind of dedicated app just for this -> see
ms wasteful, also haven't been able to find a particularly good one
3. Use the timestamp plugin (ts) -> Often I want to actually run a command at the same time as seeing the clock. So then I would have to type "ts" and then delete that and type the command I actually want

### Performance Impact

There is no perceived performance impact for this feature - it changes the control structure of the query box slightly, adds a `Label` and a single `OneWay` binding and property update callback on invoke. The clock will not update while the query box is visible, only on invoke (to reduce the overhead of introducing a ticking timer).

### Screenshots

![flow_query](https://user-images.githubusercontent.com/68668/180373879-e5005fd3-8b6a-45e2-917a-b56726b1e0e1.png)
*time in the collapsed query box*

![flow_list](https://user-images.githubusercontent.com/68668/180373873-1d6b850e-aa0c-47e2-9a73-ef32c1f6905a.png)
*time with results*

![flow_settings](https://user-images.githubusercontent.com/68668/180373880-1a1e03e4-810a-4ef3-ba96-7fd93bdf523b.png)
*toggle to enable / disable time in Settings*

**Comment by Garulf** [comment]
Actually I like it. I'd place the icon to the right though.

**Comment by jjw24** [comment]
@onesounds I remember you have done some theming around this, can you PR it when you get some free time?

**Comment by nachmore** [comment]
@Garulf I looked at placing the icon on the right but then the clock interferes visually with long commands since they run into it (even with padding it looks a bit weird).

**Comment by nachmore** [comment]
Another addendum to the feature that I could see people asking for is date, akin to Window's allowing you to squeeze date into the clock:

![image](https://user-images.githubusercontent.com/68668/180705287-568278cd-6db7-46da-aa70-1e296fbd1ff3.png)
*time with date*

At which point, though, Flow would definitely need to expose some kind of date formatter, though folks may want that anyway (12hr vs 24 hr clock).

**Comment by taooceros** [comment]
I still wonder is it possible to make this extendable with plugins? Although i think it may be somewhat hard, but it's interesting to allow plugins to provide this kinds of information like time, whether, etc.

**Comment by Garulf** [comment]
> @Garulf I looked at placing the icon on the right but then the clock interferes visually with long commands since they run into it (even with padding it looks a bit weird).
> 

Oh in my mind I assumed the clock would disappear once text was entered.

**Comment by taooceros** [comment]
> > @Garulf I looked at placing the icon on the right but then the clock interferes visually with long commands since they run into it (even with padding it looks a bit weird).
> 
> Oh in my mind I assumed the clock would disappear once text was entered.

If that's the case, maybe we can display it in the results list panel when query is empty? So that we can reuse the current results system.

**Comment by nachmore** [comment]
I quite like the simplicity of showing results in the list panel - it could basically be keyed of a parameter on plugins that users could select to say "show default value" and they get populated.

The downside is that this will not work with the current default setting of `Select last Query` (for `Last Query Style`).

The other alternative is a UX plugin model where XAML producing plugins can provide small XAML snippets that are embedded (serially?) into a specific portion of the launcher. They can disappear, or not, when typing.

**Comment by taooceros** [comment]
> The other alternative is a UX plugin model where XAML producing plugins can provide small XAML snippets that are embedded (serially?) into a specific portion of the launcher. They can disappear, or not, when typing.

Yeah that's cool, but the issue is how to arrange them.

**Comment by onesounds** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/discussions/717

This work was done once before and There is already a working version..
1. Someone needs to check my code. (The clock eats up the process.)
2. It has also been talked about plugins. (Example:Weather) but I think we would better make it without much consideration.

Anyway, I'll work on it.
