### ISSUE TITLE
Make Python download dialog translatable

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#1292]
Python dowload dialog is in English only. Is needed to change it to translateable.

![obrázok_2022-07-24_065317867](https://user-images.githubusercontent.com/37414585/180632792-924eb106-b95c-4475-a3ae-81732ea77e30.png)

**Comment by taooceros** [comment]
It is harder than I expected, which requires quite a bit reorganize the architecture. Our Internationalization requires plugin to load before it is used (which is not super reasonable), but the method creating the messagebox is called before plugins are loaded, which makes things much harder.

I will leave it to the future after everything else that is prepared for 1.10.
