### ISSUE TITLE
Search entries of “WindowsSettings” unable to match the default language

### ISSUE THREAD

**Issue by dingxy1996** [Flow-Launcher/Flow.Launcher#1293]
**Describe the bug/issue**
The default language of Flow launcher has been set to Simplified Chinese(中文), but the entries of  “WindowsSettings” still show up in English, and also unable to use Chinese phrases such as “控制面板” to search the “Control Panel”.

**To Reproduce**
As shown in the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/93484341/180644770-c226cf7b-df86-4d7f-bd1d-c5a087b0d98b.png)

**Your System**
Windows 11 (Build 22000.832)
Btw, the default system language has also been set to Simplified Chinese, and the location has been set to Hong Kong.

Windows build number: 22000.832
Flow Launcher version: 1.9.4 (same issue as the previous build 1.9.3)
```
**Flow Launcher Error Log**
Not applicable

**Comment by taooceros** [comment]
The Windows setting plugin will match the Windows language you are using (which is because of a bug). But the behavior actually makes senses in a lot of cases.

**Comment by jjw24** [comment]
Is this not because we haven't updated/pushed out the Chinese translation for Windows Settings plugin?

**Comment by taooceros** [comment]
> Is this not because we haven't updated/pushed out the Chinese translation for Windows Settings plugin?

We do have Chinese translation for Windows Settings plugin (we don't have translation for the tasklink though). It's a design thing I talks with @onesounds previously.
