### ISSUE TITLE
Clear last request

### ISSUE THREAD

**Issue by skjerns** [Flow-Launcher/Flow.Launcher#130]
I'm not sure why this feature was removed, as it is present in Wox:

When I activate Flow, it will always display the most recent query. However in almost all cases that is not what I want. Can the option be brought back to clear the last query when the window is disappearing?

**Comment by sambarrowclough** [comment]
Settings > General > Last Query Style > Empty last Query is what you are after 👍

**Comment by skjerns** [comment]
![Capture](https://user-images.githubusercontent.com/14980558/89126840-52369a00-d4e9-11ea-9bcc-63da03dfc0a5.PNG)

that setting doesnt exist anymore

**Comment by jjw24** [comment]
hey does it show if you scroll down the page?
Should look something like this:
![image](https://user-images.githubusercontent.com/26427004/89144284-98930400-d590-11ea-8dc3-904a84ab39ae.png)

**Comment by skjerns** [comment]
you can scroll down. okay, that wasn't very obvious to me. 

I think that should be made more verbose
