### ISSUE TITLE
Search D:\ or any other drive by default

### ISSUE THREAD

**Issue by ahmedk1998** [Flow-Launcher/Flow.Launcher#1308]
I'm always frustrated when I have to type out "d:\>" to search for files in my D drive. By default flowlauncher only searches through C drive. 
Is there any method to directly search through D or any other drive as well when typing a query?

![image](https://user-images.githubusercontent.com/16254118/183241219-a3498c4b-7089-4d01-ad21-996bab84ea03.png)

**Comment by jjw24** [comment]
I am assuming you are using Explorer plugin which uses Microsoft Search, so you need to configure search (via windows settings) to index D drive. By default, the windows search only indexes some of your C drive folders.

**Comment by ahmedk1998** [comment]
alright thanks a lot!
