### ISSUE TITLE
Update WebSearch add url instruction text

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1309]
In the **web searches** plugin, when we add a new website, the instruction reads as follows:

If you have a web search service you want to use, you can add it to Flow. For
example, you can follow the url format in the address bar if you want to search
casino on Netflix: "https://www.netflix.com/search?q=Casino". To do this,
change the search term 'Casino' as follows.
https://www.netflix.com/search?q={q}
Add it to the URL section below. You can now search Netflix with Flow using any
search terms.

This is a bit confusing.

A better version is as follows:

If you want to add a search for a particular website to Flow, first enter a dummy text string in the search bar of that website, and launch the search. Now copy the contents of the browser's address bar, and paste it in the **URL** field below. Replace your test string with **{q}**.

For example, if you search for **casino** on Netflix, its address bar reads **https://www.netflix.com/search?q=Casino**. 
Now copy this entrire string and paste it in the **URL** field below.
Then replace **casino** with **{q}**. 
Thus, the generic formula for a search on Netflix is **https://www.netflix.com/search?q={q}**

_Originally posted by @raindropsfromsky in https://github.com/Flow-Launcher/Flow.Launcher/discussions/956#discussioncomment-2675845_

**Comment by dracp** [comment]
In Crowdin I have added an alternative translation in Spanish:

-Si dispone de un servicio de búsqueda web que desea utilizar, puede añadirlo a Flow. Por ejemplo, si desea buscar 'casino' en Netflix puede utilizar el siguiente formato url en la barra de direcciones: "https://www.netflix.com/search?q=Casino". **Para cualquier otra búsqueda sustituya el término "Casino" por el de la búsqueda deseada.**-

Replacing the last sentence in English “To do this, change the search term 'Casino' as follows.” por **"For any other search replace the term "Casino" with the desired search term."**

**Comment by jjw24** [comment]
See https://github.com/Flow-Launcher/Flow.Launcher/issues/1446
