### ISSUE TITLE
Plugin Store's plugins should have label to indicate installed/not-installed

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1310]
In the **Settings**, the **Plugin Store** tab shows a large list of plugins.

This screen should show which of these plugins are already installed.

Also, there should be a filter to show only those filters that are installed (or not installed).
- The "show only installed plugins" filter will allow us to check whether to disable any of them.
- The "show only not-installed plugins" filter will allow us to focus on new plugins

_Originally posted by @raindropsfromsky in https://github.com/Flow-Launcher/Flow.Launcher/discussions/956#discussioncomment-2678598_

**Comment by raindropsfromsky** [comment]
Further suggestion: If the plugin is installed, show its card differently.
(e,g, different line/fill color, or line thickness)

Once this feature is implemented, there is no need to keep two separate pages for plugins in the **Settings**. 
- The **Plugin** page lists only the installed plugins with a facility to turn it off
- The **Plugin store** page gives a master list of all plugins, but without any controls.

So, the **plugin** page can be eliminated.

And in the **Plugin Store** page, please provide the following controls for each plugin:
1. A **Toggle** button to turn the plugin on/off
2. A **uninstall/remove** button (should appear only when the plugin is installed)

**Comment by taooceros** [comment]
The plugin page also serves a functionality that allows plugins to provide setting control. I think it would be messy if the that is mixed with the plugin store.

**Comment by ptournet** [comment]
My take on this issue is that the **Plugin Store** should only display the plugins that have not been installed yet.
And there should then be an uninstall button on the **Plugin** page (in addition to the turn off switch).
Moreover, if would be great, in the **Plugin Store**, when clicking on a plugin to have a description of what it's supposed to do...
