### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by Tigarcen** [Flow-Launcher/Flow.Launcher#1323]
how can i use "Flow-Launcher-Setup.exe" to install this software not to C drive
thank you very much

operating system: windows 11

**Comment by jjw24** [comment]
Hi @Tigarcen, due to the library we are using, there is not an option to do so with the exe. We recommend downloading the portable install instead where you can place it anywhere you like after extracting.

**Comment by Tigarcen** [comment]
> Hi @Tigarcen, due to the library we are using, there is not an option to do so with the exe. We recommend downloading the portable version instead where you can place it anywhere you like after extracting.
thanks a lot (●'◡'●)
