### ISSUE TITLE
Explorer plugin allow Ctrl + Shift + Enter to run file as administrator

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1329]
**Describe the bug/issue**
Ctrl + Shift + Enter shortcut is not running file as administrator.

**To Reproduce**
1. Search for the required file
2. Highlight it via arrow keys
3. Press the Ctrl+Shift+Enter shortcut

**Screenshots**
The file I'm trying to run
![Flow Launcher_e90XBBLRwv](https://user-images.githubusercontent.com/47380919/184468191-f6ba9794-fdb9-468a-957f-83e43338fa89.png)

**Your System**
```
Windows build number: (run "ver" at a command prompt)
Microsoft Windows 11 [Version 10.0.22000.856]
Flow Launcher version: (Settings => About) 
1.9.4
```

**Comment by taooceros** [comment]
I guess it is searched by explorer or everything plugin, and thereby doesn't support that feature.

**Comment by taooceros** [comment]
Maybe in the future. Currently the best solution is to let program plugin index this file.

**Comment by taooceros** [comment]
You can annually add the path to program plugin. Check its setting page.

**Comment by taooceros** [comment]
No problem

**Comment by VictoriousRaptor** [comment]
@jjw24 why do we need to repoen it? It's implemented.

**Comment by VictoriousRaptor** [comment]
> We haven't added to Explorer plugin have we? Thought it's only available for Program plugin.

We have.

https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs#L239-L258
