### ISSUE TITLE
https://github.com/Flow-Launcher/Flow.Launcher/issues/new

### ISSUE THREAD

**Issue by rafiathallahg** [Flow-Launcher/Flow.Launcher#1333]
C:\Users\Rafi Athallah G\AppData\Local\Temp\Rar$EXa1664.35615\FlowLauncher\app-1.9.4\UserData\Logs\1.9.4\2022-08-17.txt

**Comment by taooceros** [comment]
Could you describe what happens and reupload the log? I think you simply paste the path to the log that we cannot see anything.

**Comment by Garulf** [comment]
Looks like Flow is being run from the windows temp directory. This is not supported by Flow Launcher and may cause issues. Please install or extract Flow to a proper directory.

**Comment by jjw24** [comment]
Should be fine, it's running in portable mode. 

@rafiathallahg  please let us know how you got the error and upload the log.
