### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#1336]
i hope bookmarks search can auto refresh in every search.  New add bookmarks cannot be search unless restart the flow.launcher.

**Comment by taooceros** [comment]
Try reload plugin data. We are trying to do so, but there's some techibical hardness.

**Comment by jjw24** [comment]
This change has been merged into early access build and will be going out with v1.10.0 release in the future. In the meantime you can use this feature straight away by downloading early access build [here](https://github.com/Flow-Launcher/Flow.Launcher/discussions/956)
