### ISSUE TITLE
[Describe Your Feature] Read localized Names from DESKTOP.ini

### ISSUE THREAD

**Issue by Moe1369** [Flow-Launcher/Flow.Launcher#1339]
**Is your feature request related to a problem? Please describe.**
Incomplete Localization (German).

Example: Control Panel  should be called "Systemsteuerung" but it shows up as "Control Panel"

**Describe the solution you'd like**
Read from the provided (at least I hope there is one)  DESKTOP.INI where the localized name is stored.

.

**Comment by jjw24** [comment]
Our localization is done via [crowdin](https://crowdin.com/project/flow-launcher), @Moe1369 have you had look whether it can be translated there?
