### ISSUE TITLE
Small graphical glitch with "Query window shadow effect" 

### ISSUE THREAD

**Issue by ArttuLai** [Flow-Launcher/Flow.Launcher#134]
### Describe the bug/issue
If you enable "Query window shadow effect" under theme settings, the drop shadow doesn't draw itself properly around the whole query window, it has sharp cuts in the corners.

### To Reproduce
1. Open Flow's settings --> Theme tab
2. Enable "Query window shadow effect"
3. Observe that the corner shadows of the query window are cut improperly

### Screenshots
<img width="614" alt="buggyShadow-FlowLauncher" src="https://user-images.githubusercontent.com/42007282/89732524-215de400-da58-11ea-91d8-5bb4ff54d602.png">

### Your System
```
Surface Laptop 3 i7
Windows build number: 10.0.19042.423
Flow Launcher version: 1.1.2 
```
**Flow Launcher Error Log**
[2020-08-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/5047551/2020-08-09.txt)

Also, just wanted to say that really enjoy using Flow these couple weeks. It works fast and reliably, and is my go-to favorite of the Windows launchers.

**Comment by jjw24** [comment]
This is now resolved.
