### ISSUE TITLE
Need A way to index all my coding projects directory but exclude folders like node_modules[Describe Your Feature]

### ISSUE THREAD

**Issue by SciSaif** [Flow-Launcher/Flow.Launcher#1348]
I need a way to index my projects folder but I want to exclude the node_modules folder as it has thousands of files and there is no need to index it.

**Comment by gregorysl** [comment]
if you're using Everything plugin this will help 
![image](https://user-images.githubusercontent.com/3129241/187269049-f7693291-0be8-4095-93aa-4bfc38223a51.png)

**Comment by taooceros** [comment]
I feel like you don't need to exclude. The program plugin will only index file with provided suffix.

**Comment by jjw24** [comment]
You can also use Explorer plugin by setting the 'Indexing Options' (from flow search indexing options) to index your projects directory and untick the folders you don't want it to index. You can also exclude the folders you don't want to index via Explorer plugin's settings by adding their paths to 'Index Search Excluded Paths'.

**Comment by jjw24** [comment]
Closing. Please reopen if you would like to discuss further.
