### ISSUE TITLE
[Dev] Program plugin settings enable/disable buttons

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1356]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

- Program plugin settings' enable/disable program button text not updating based on program status anymore 
- disabling a program via search result no longer reindex the programs consequently the disabled program is still showing in results.

### To Reproduce

Use Dev branch version disable program via results or settings 

### Flow Launcher Version

Dev branch

**Comment by VictoriousRaptor** [comment]
Fixed in #1496.
