### ISSUE TITLE
Acronym search (or more feature) for programs

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#136]
Does Flow have a plan to implement the search with acronym? I have tried the latest preview in Wox, which contains fascinating implementation of the indexing and searching using the acronym of programs name.

For example, when I want to open the program like Visual Studio Code, I can simply type vsc and select the first query result, which will be much faster and possibly more precious than typing "visual...." in order to open the same program.

On the other hand, I have met a significant issue in wox. When I use more than 3 or 4 letters to search the result, it will cause huge latency for the result to appear and may cause high CPU usage and stunt of wox in 1196 version ([#3093](https://github.com/Wox-launcher/Wox/issues/3093)). I don't know whether this issue is due to the implementation of acronym search. This cause me whenever I want to search a program with wox, I need to find a shortcut of the program so that it won't crash wox and my computer🤣.

Besides, I will be hugely pleased if Flow can implement the pinyin feature in Wox, since there are quite a lot of programs in my computer named with Chinese. 😃😃😃

**Comment by jjw24** [comment]
Hey how's it going, pinyin feature is already there, you just need to turn on 'Should Use Pinyin' in settings. Let me know if this is what you are after.

In terms of acronym search, should already be there as well, let me take a look with the 'vsc' example and get back to you.

**Comment by taooceros** [comment]
> Hey how's it going, pinyin feature is already there, you just need to turn on 'Should Use Pinyin' in settings. Let me know if this is what you are after.
> 
> In terms of acronym search, should already be there as well, let me take a look with the 'vsc' example and get back to you.

Thank you so much for responding so quickly. I think the situation for now is quite similar to the query situation in wox 1129, which require "space" between the acronym, otherwise it will not be considered in the fuzzy search.

**Comment by taooceros** [comment]
I have checked wox for version 1.4.1129, which provides the same query result when I try to search query with acronym. I think wox in 1.4.1196 or higher has fixed the issues if you are using the same algorithm as wox. However, these versions also brough up an issue as I mentioned before.

**Comment by jjw24** [comment]
Just to clarify, you were able to find and use the Pinyin search feature?

When you say needs 'space', do you mean needing to type 'v s c' for visual studio code?

**Comment by taooceros** [comment]
Yes, I found that selection for pinyin search. Thank you!
Yes, "v s c" is working, though in a weird way which match the 'v' and 's' in visual, with 'c' in code, while "v s s c" doesn't work here.

**Comment by jjw24** [comment]
> Yes, I found that selection for pinyin search. Thank you!
> Yes, "v s c" is working, though in a weird way which match the 'v' and 's' in visual, with 'c' in code, while "v s s c" doesn't work.

Good to hear 👍 

It's not suppose to do that with the acronym search, I will investigate and get back to you.

**Comment by taooceros** [comment]
I have checked the code and added a manually acronym search (by picking up the first letter and do another search). If you think it is a good idea to do that, I can create a pull request for that.
I think Wox has implemented a native search for acronym search, but I am unable to understand Bao's change for fuzzy search for now, so I just manually added one, and it seems that the performance won't be affected because there are quite a lot duplicate search in our current Result method for win32 and uwp.

**Comment by jjw24** [comment]
> I have checked the code and added a manually acronym search (by picking up the first letter and do another search). If you think it is a good idea to do that, I can create a pull request for that.
> I think Wox has implemented a native search for acronym search, but I am unable to understand Bao's change for fuzzy search for now, so I just manually added one, and it seems that the performance won't be affected because there are quite a lot duplicate search in our current Result method for win32 and uwp.

Sorry I still havent got around to this, but I believe the problem is scoring (where scoring is not enough to make the standard score of 50) rather than missing behaviour. I will need to confirm this.

**Comment by taooceros** [comment]
That's true, I have checked a few days ago by changing the accuracy of search.
However, I think it would be better to have a seperate search of acronym search since that is useful. With current fuzzy search, search with acronym will result a low score and make the result rank low.

**Comment by jjw24** [comment]
I think we could easily embed into current fuzzy search, whether the character from the query matches the start of each substring to determine if it is acronym search. If it is, bump the score of the search result. My concern is introducing a separate search where the code traverses fuzzy search then traverses acronym search if this is what you mean.

**Comment by taooceros** [comment]
Yes, that what I mean.
I implement that in the Result method for IProgram so that other utility of fuzzy search won't change. If you want, you can take a look on the change of code of Win32 and UWP Result method in my branch AcronymSearch.
I also think that acronym search can be used quite common, and it can reduce quite a lot typing when opening program, so that there may not be a need to determine whether it is an acronym search for program.

**Comment by jjw24** [comment]
> Yes, that what I mean.
> I implement that in the Result method for IProgram so that other utility of fuzzy search won't change. If you want, you can take a look on the change of code of Win32 and UWP Result method in my branch [AcronymSearch](https://github.com/taooceros/Flow.Launcher/tree/AcronymSearch).

I am actually thinking we can expand fuzzy search to adopt acronym search rather than adjusting the search behaviour for Programs plugin

> I also think that acronym search can be used quite common, and it can reduce quite a lot typing when opening program, so that there may not be a need to determine whether it is an acronym search for program.

Agree

**Comment by taooceros** [comment]
> I am actually thinking we can expand fuzzy search to adopt acronym search rather than adjusting the search behaviour for Programs plugin.

That sounds great. I think Wox may have made the changes for that, though I haven't understood how they have done this job, since @bao-qian has changed quite a lot for the fuzzy search algorithm.
However, without changing the algorithm is not hard and I can finish it by migrating my change for program plugin easily. I will create a pull-request later for that so that it will be easier for us to take a look on how we should do the job.
