### ISSUE TITLE
BUG: Calculator displays 0 or 0.000000000000000 if the result is too small.

### ISSUE THREAD

**Issue by MooshiMochi** [Flow-Launcher/Flow.Launcher#1364]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

![image](https://user-images.githubusercontent.com/83987369/188622436-4cf1a4a9-1dfa-4d4b-a644-12cc180c52b3.png)
If you try to use a calculation that results in a very small number, the calculator will return a rounded result as seen in the picture or 0.

Would recommend to introduce Standard Form notation to solve this issue.
Would also recommend to add an option to select the number of Sig Figs or Decimal points to represent the result.

### To Reproduce

1. (6.6*10^-34)*(7*10^14)-(8.4*10^-20)  - Type this in the query

### Screenshots

Already pasted one above, but here it is again.
![image](https://user-images.githubusercontent.com/83987369/188622796-24632a17-a91e-4dce-8125-6ddde07bd4dc.png)
![image](https://user-images.githubusercontent.com/83987369/188622805-d5fd6f6a-4da7-4b17-a0b1-b3c099675adc.png)

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by MooshiMochi** [comment]
uh, it looks like the query string was formatted by the markdown syntax.. Here it is again:
`(6.6*10^-34)*(7*10^14)-(8.4*10^-20)`

**Comment by jjw24** [comment]
Will keep this closed since can't be fixed, if a solution found feel free to reopen for implementation.
