### ISSUE TITLE
BUG: always open in new windows tab

### ISSUE THREAD

**Issue by anishkumar127** [Flow-Launcher/Flow.Launcher#1370]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

when i try to open vs code or other running app. its not open running app. always open new windows tab of vs code. 
is there is a way to open running app only instead of new windows tab open. ?

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
You can install WindowWalker, which will allow you to switch to running apps.

Closing, feel free to reopen if you above any questions.

**Comment by anishkumar127** [comment]
@jjw24  thank you so much ❤️
