### ISSUE TITLE
New default plugin: Registry

### ISSUE THREAD

**Issue by LeLocTai** [Flow-Launcher/Flow.Launcher#1377]
It is very useful to be able to paste registry path directly to Flow without opening regedit. PowerToy Run already have [one ](https://github.com/microsoft/PowerToys/tree/main/src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry) which should be easy to port.
Obviously this can be implemented as a 3rd party plugin. But I believe this is useful enough to most people to be included by default.

**Comment by jjw24** [comment]
Good plugin idea. 

At this stage I think might be better off as a 3rd party plugin, since plugins are so accessible let's keep the bundled plugins to a minimum.
