### ISSUE TITLE
Crash when using Spell-checker plugin

### ISSUE THREAD

**Issue by Sinan-Karakaya** [Flow-Launcher/Flow.Launcher#1389]
Whenever using the spell command, flow-checker will crash thus making the plugin unusable.

### How to reproduce:

1. Install Spell-Checker plugin
2. Launch Flow Launcher and input the spell command

Here is the log: 
[2022-09-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9591739/2022-09-17.txt)

And here is the exception message:
https://pastebin.com/07TM14zV

### Environnement
Windows 11 x64
Flow Launcher 1.9.4

**Comment by Garulf** [comment]
This is due to a bug in my plugin and how scoop names it's folders. It's already been fixed and I'll have a new version released by tonight. Sorry for the trouble.

**Comment by Garulf** [comment]
Fix version is released. Please feel free to reopen if the problem persists.

**Comment by Sinan-Karakaya** [comment]
Issue still persiste unfortunately @Garulf 

[Log]
[2022-09-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9636851/2022-09-23.txt)

[Exception message](https://pastebin.com/SnWATfVT)

**Comment by Garulf** [comment]
Looks like an issue with a third party library. Sorry about that, I'll take a look.

**Comment by Garulf** [comment]
Due to a dependency issue this plugin relies on it can crash on systems that are not compatible. I'll be takign this plugin off the "Plugin Store" until a work-around is possible.
