### ISSUE TITLE
Keyword that will show specific app or category of apps

### ISSUE THREAD

**Issue by Alexnoj** [Flow-Launcher/Flow.Launcher#1394]
Thanks

**Comment by onesounds** [comment]
There is a Favorite plug-in in the store,(https://github.com/stax76/Flow.Launcher.Plugin.Favorites) but it is not an easy to use interface. (text editor!)
personally, It's a function that I want to put in too. but we don't have enough time. 😂 I hope it helps.

**Comment by VictoriousRaptor** [comment]
#930
