### ISSUE TITLE
Permissions and teams set up

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#14]
@NickSeagull @SysC0mp @Kalaschnik @theClueless I have not had a chance to look at in the organisation how to give you the access you need to start PRs and what not. Let me know if something obvious I need to set up straight away like access.

Also do we want to use a platform for group discussions or just stick to issues?

**Comment by Kalaschnik** [comment]
Thats a good idea. I do also have some general questions. Since we distributed from Las Palmas (UTC+1) to Melbourne (UTC+10)—where are you located @theClueless ?—I think a general feasible time window for us is from 9:00 – 13:00 UTC. We could do a 30 minutes talk tomorrow around 10:00 UTC? What do you think? Do you prefer zoom, or rather to chat?

**Comment by jjw24** [comment]
> Thats a good idea. I do also have some general questions. Since we are distributed from Las Palmas (UTC+1) to Melbourne (UTC+10)—where are you located @theClueless ?—I think a general feasible time window for us is from 9:00 – 13:00 UTC. We could do a 30 minutes talk tomorrow around 10:00 UTC? What do you think? Do you prefer zoom, or rather to chat?

Was thinking of doing more of a chat group / workspace on Slack or some other forms so we are not too time constrained and can still communicate and spit out ideas.

**Comment by SysC0mp** [comment]
I would agree with jjw here as i have no fixed times when i'm available at the moment.

**Comment by NickSeagull** [comment]
I had good experiences using spectrum.chat, we can make async conversations over there :)

**Comment by Kalaschnik** [comment]
I’m fine with everything

**Comment by jjw24** [comment]
> I had good experiences using spectrum.chat, we can make async conversations over there :)

I have not use it before. My main go to is Slack haha. I am happy to give it ago. Would you have time to set it up?

**Comment by jjw24** [comment]
> I would agree with jjw here as i have no fixed times when i'm available at the moment.

Are you okay with spectrum as well?

**Comment by SysC0mp** [comment]
I'm fine with that 👍

**Comment by SysC0mp** [comment]
I created a Spectrum community. Join should be able to join using following link:
https://spectrum.chat/flow-launcher/join/f0eff2ed-7792-4ae0-a1cd-a432dc63f95a

**Comment by SysC0mp** [comment]
Regarding permissions: 
Currently i think we cannot create branches in this repository. Should we change that or rather develop in our own forks and pull from there?

**Comment by NickSeagull** [comment]
I'd use our own forks, I think that works very well

**Comment by jjw24** [comment]
> I'd use our own forks, I think that works very well

From my perspective, I would go with whatever is easiest for you to contribute. I would think it would be faster and neater for people that are part of the org they could create branches/repos directly from within the org rather than forking it?

I am not familiar with how permissions should be set up in orgs, will take a look later on. If it is something I should set up, please direct me to help.

**Comment by jjw24** [comment]
I have changed base permission for organisation members from read to write, this should solve the above. Let me know if does not still.

**Comment by gdziedzic** [comment]
@jjw24 Hey, I love your idea about making Wox shine again. I'm a passionate user of Wox and I have multiple custom made plugins that I wrote for myself. Recently, I thought It'd be nice to have in Wox the feature that Alfred already has - launching list item using some keyboard shortcut (ctrl+num). Nevertheless, assuming I'd love to contribute somehow... can I join your team?

**Comment by SysC0mp** [comment]
Every helping hand is welcomed :)
Regarding the keyboard shortcut: I think you can launch result items using alt+[1-9], but this is a feature that is not really shown to the user like in Alfred, so it can definitely be improved.

**Comment by jjw24** [comment]
> @jjw24 Hey, I love your idea about making Wox shine again. I'm a passionate user of Wox and I have multiple custom made plugins that I wrote for myself. Recently, I thought It'd be nice to have in Wox the feature that Alfred already has - launching list item using some keyboard shortcut (ctrl+num). Nevertheless, assuming I'd love to contribute somehow... can I join your team?

Absolutely. Helping hand is very welcome.

Please check email for the invite.

**Comment by jjw24** [comment]
@gdziedzic let me know the email to reach you so I can send you the invite for Spectrum community

**Comment by jjw24** [comment]
Created a team for this org. You can now @Flow-Launcher/team
