### ISSUE TITLE
BUG: no internet connection when connected to nordvpn

### ISSUE THREAD

**Issue by SchittBull** [Flow-Launcher/Flow.Launcher#1401]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

When I am connected to NordVPN (via NordLynx) the Pluginstore is offline. I also can not install via pm.
Probably not really a bug but maybe there is a solution :)

###Flow Version
v1.9.4

### Windows Build Number

10.0.22000.978

**Comment by onesounds** [comment]
Depending on your vpn connection country, you might have blocked the server where the plug-in data is located. Please change the connection area of vpn and let me know if there is a difference.

**Comment by SchittBull** [comment]
Thank you. Tried multiple countries/Servers. No change.

**Comment by onesounds** [comment]
If so, I think GitHub is blocking the vpn. These access problems are difficult for us to solve because our plug-in data are all in GitHub. 😅

**Comment by taooceros** [comment]
try this? https://stackoverflow.com/questions/52452455/httpclient-getasync-times-out-when-connected-to-vpn

I don't think the cdn will ban nordvpn though, so let's see whether it's some other issue. I don't have nordvpn, so would you please share the log?

**Comment by SchittBull** [comment]
Thank you for the replies!

> try this? https://stackoverflow.com/questions/52452455/httpclient-getasync-times-out-when-connected-to-vpn

Unfortunately I don't have this option.
![ApplicationFrameHost_czQ8FiVblu](https://user-images.githubusercontent.com/53765158/192146764-86bb6276-1a27-49b2-9d34-108415c7f5e2.gif)
 
> I don't think the cdn will ban nordvpn though, so let's see whether it's some other issue. I don't have nordvpn, so would you please share the log?

do you need a specific part of this log?

**Comment by taooceros** [comment]
Yeah would you please share the log related to http error?

**Comment by SchittBull** [comment]
I am not sure where to find this log, sorry. But I found out, that it only won't work if I turn on split tunneling in NordVPN. I had this problem with other software before as well. Even though the software isn't even in the  "Diable VPN for selected apps" list.

**Comment by taooceros** [comment]
just type `open log location` and upload the latest one.

**Comment by taooceros** [comment]
Then it might be NodeVPN's issue? Are you able to connect to pluginstore without opening vpn?

**Comment by jjw24** [comment]
A simple test I suppose is to see with your vpn on, can you open this url: 
https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
This is literally the url flow downloads the manifest from.

If not, what about directly via GitHub?
https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json

If both above not working, it would be the definitely the VPN

**Comment by Traxmaeus** [comment]
Hi @SchittBull , I've encountered the same problem as you and solved it on my end!

> ### Problem Description
> When I am connected to NordVPN (via NordLynx) the Pluginstore is offline. I also can not install via pm. Probably not really a bug but maybe there is a solution :)

I was using **Split-Tunneling** setting in **NordVPN** (**FlowLauncher**  added/not-added) and had the same problem with **GoogleSearch**/**GoogleSearchPlus**(_crashing_)/**PluginStore**(_Not loading_).

I've disabled the split tunneling option which is unnecessary in my case since (**NordLynx** = implementation of **WireGuard**) to have maximum possible download speed.

- Disable the split tunneling option
- Reconnect to any server with /NordLynx protocol
- Test if the FlowLauncher has access to the internet
