### ISSUE TITLE
Typing sound

### ISSUE THREAD

**Issue by Textic** [Flow-Launcher/Flow.Launcher#1402]
It would be nice if there was a sound every time you type a letter

**Comment by jjw24** [comment]
Hi, what would be the use case for this one?

**Comment by Textic** [comment]
idk, satisfaction I think

**Comment by onesounds** [comment]
I've thought of a similar idea. It is used in typing learning software or virtual keyboard environments. But there are some problems.
1. Basically, there's a real typing sound on the keyboard.
2. Delay (lagging) in sound playback.  

so, it is common not to put sound separately in a general input environment. If we have time in the future, we can test it under the name of "laboratory." But it is difficult to find an appropriate sound and there is no intention to apply it at this time.
