### ISSUE TITLE
Easy way of removing (external) plugins (button)

### ISSUE THREAD

**Issue by Remzi1993** [Flow-Launcher/Flow.Launcher#1407]
**Is your feature request related to a problem? Please describe.**

Not really.

**Describe the solution you'd like**

Users should be able to easily remove (external) plugins in the plugin section and/or plugin store. (A remove button will do).

**Comment by onesounds** [comment]
yep. we have plan. But it's being delayed because we can't afford to work.
in now, try type the 'pm uninstall'.

**Comment by Remzi1993** [comment]
> yep. we have plan. But it's being delayed because we can't afford to work. in now, try type the 'pm uninstall'.

Thanks for your quick reply 🙂👍

**Comment by onesounds** [comment]
added in https://github.com/Flow-Launcher/Flow.Launcher/pull/1419

**Comment by Remzi1993** [comment]
> 

Nice! I left you some feedback there. I'm very grateful for your hard work. I'm a software engineering student and I'm currently doing a Java project with JavaFX. I would like to help out, but I don't have any understanding of (objective) C and/or C++. I only know JavaScript, Java, SQL (full web stack) and some .NET and C#. And a little bit of Python.

**Comment by taooceros** [comment]
Our project is completely in c#, which is easy to understand if you have knowledge in Java.

**Comment by Remzi1993** [comment]
> Our project is completely in c#, which is easy to understand if you have knowledge in Java.

Nice, I will look into it next week. 👍
