### ISSUE TITLE
BUG: Ctrl + backspace does not go one directory back

### ISSUE THREAD

**Issue by NolanNolan** [Flow-Launcher/Flow.Launcher#1411]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

when searching eg for a folder name, and seleecting a folder from the result list, then pressing Ctrl +  Backspace does not take me 1 level back, it does nothing

am i missing something here ?

using windows 11

Nolan

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.94

### Windows Build Number

21H2 22000.1042

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
This is a feature for v1.10.0 release, we probably accidentally updated the shortcut in the readme. You can use this feature now with the early access version: https://github.com/Flow-Launcher/Flow.Launcher/discussions/956

**Comment by jjw24** [comment]
Closing. Please feel free to reopen if you require further discussion. I will remove the shortcut from the readme.
