### ISSUE TITLE
BUG: Flow Launcher priority

### ISSUE THREAD

**Issue by SchittBull** [Flow-Launcher/Flow.Launcher#1414]
### Problem Description

even though I have "window walker" at priority 7 and the "Programs" plugin on 5. It only works the first time I open the flow search. The 2nd Time it shows Programs in higher priority:
![yymterZlTR](https://user-images.githubusercontent.com/53765158/192150516-37ed2f01-0e62-4b65-8aae-51c90aa7a38a.gif)

### Flow Launcher Version

v1.9.4

### Windows Build Number

 10.0.22000.978

**Comment by jjw24** [comment]
I saw you typed 'v' instead of 'vi' for the second time, can you try 'vi' for both times.
