### ISSUE TITLE
An option to automatically clear logs 

### ISSUE THREAD

**Issue by VictoriousRaptor** [Flow-Launcher/Flow.Launcher#1416]
**Is your feature request related to a problem? Please describe.**

The logs are not small. Log folder can be quite big after several months. And old logs are useless most of the time.

**Describe the solution you'd like**

An option to automatically clear old logs, or clear the folder after reaching a certain size.

**Describe alternatives you've considered**

Maybe a button to clear old logs.

**Additional context**

**Comment by Remzi1993** [comment]
This should also be opt-in rather than opt-out. Logs should be turned off by default and there should be an option to turn on logs with a checkbox and beneath the checkbox a link to the logs directory so users can easily find the logs directory and upload it here.

**Comment by onesounds** [comment]
We will not turn off the log by default. (Because it's a problematic program. 😂) I added a button to check the log folder in about panel last time. I will add a function to erase the log.

**Comment by VictoriousRaptor** [comment]
It would be better to show the size of log folder, to let users decide when
they should clear the logs.

DB P ***@***.***> 于 2022年9月27日周二 09:03写道：

**Comment by onesounds** [comment]
> It would be better to show the size of log folder, to let users decide when they should clear the logs. DB P ***@***.***> 于 2022年9月27日周二 09:03写道：

Nice idea. I'll add it to button label.

**Comment by Remzi1993** [comment]
> We will not turn off the log by default. (Because it's a problematic program. 😂) I added a button to check the log folder in about panel last time. I will add a function to erase the log.

Haha 🤣 Maybe after it reaches stability 😅
