### ISSUE TITLE
BUG: Find files that does not have the content searched for

### ISSUE THREAD

**Issue by NolanNolan** [Flow-Launcher/Flow.Launcher#1421]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Hi
if i search for a text string items are found that does not contain this text string. I searched for a msg file that was located on my local drive but search returned items that when opened did not contin the string (nor the file or foldername maching)

Further, searching cmd and clicking "command" that popups returns error "unabe to start...."

Nolan

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.8.3

### Windows Build Number

11 1000.22000.1042.0

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi. This will be plugins returning data. If you didn't specify a keyword, then every plugin without a keyword set will run and send its results. Can you go into settings and see which plugins have a '*' as the keyword (whcih means none) and can you give an example of what is returned that doesn't have your search terms in it?

**Comment by NolanNolan** [comment]
Hi

there are many apps that has * as keywword. 

for example i searched for "det skal være så kompliceret" (is danish) and returned:

pdf (scientific paper), docs, msg

none of these contained the search string

any idea ?

Nolan

**Comment by deefrawley** [comment]
Hard to tell. Do you use the Everything plugin?  Try giving the Explorer plugin a keyword, like 'ex', and then run the explicitly and see what it returns.

**Comment by NolanNolan** [comment]
Hi

i do not use everything plugin, it didnt seem to find anything else that without it. If i use a keyword like ex in Explorer plugin it returns many  pdf files docx and msg files but most hereof do not contain the search string but only some or 1 of the words in the string. That is not to be expected is it ?

thanks

Nolan

**Comment by NolanNolan** [comment]
Is it not expected that a string of words like eg "this is an example" would only return these documents that has that exact string and not just ne of the words ?

Or dont the app understand this syntacs?

See post above, is that a bug?

Nolan

**Comment by taooceros** [comment]
Are you using the content search? `doc:` maybe? could you check the actionkeyword for that (in the explorer plugin)?

**Comment by NolanNolan** [comment]
i use the cintent search via actionkey fs which is what i set for this in explorer plugin. 

So you say it should find a string text and not just return results for any arbitrary word in the string ? IE work precisely as windows buildin search ? Because as it is now it does not

**Comment by NolanNolan** [comment]
Sorry for reopening this, but am i correct that flwo launcher, even though it uses the windows search setting, cannot find text strings as eg "This paper unravels " ie an exact sentence ? Flow launcher returns some files but none of which the exact phrase is to in the content, the singular words are however.

Windows search can this and i thought since flow launcher uses windiws search it works 100 % like windows search (just more conveniant) ?

thanks
nolan

**Comment by jjw24** [comment]
Hi @NolanNolan with Explorer's content search it does not look for exact sentence, will look for each word in the sentence separately, e.g. if I search for 'hello world' using content search, it will return results containing 'hello', 'world', 'hello world'. You can verify the results by opening them and search for each of the words.

**Comment by jjw24** [comment]
> Further, If i select search method in settings as "everything" i ge tthis error below, i thought "everything" was natively integrated from the latest version, what does it mean?
> 
> ![image](https://user-images.githubusercontent.com/30736282/215325667-c4be161b-d40f-401d-8c83-7e1a385a7ebf.png)
> 
> thanks nolan

This warning means Flow couldn't find a running instance of Everything, so it needs Everything to be either installed if not or launched if not running.

**Comment by NolanNolan** [comment]
Hi thanks yes I know but I thought it was not necessary to install it separately anymore because it from the last version is integrated in the file plugin
Further I tried to install it manually and point to the directory but that didn't solve the problem with the error message I got maybe you could try to recreate it?

Hilsen Jørn

On 1. februar 2023 21.35.16 Jeremy Wu ***@***.***> wrote:

Further, If i select search method in settings as "everything" i ge tthis error below, i thought "everything" was natively integrated from the latest version, what does it mean?

[image]<https://user-images.githubusercontent.com/30736282/215325667-c4be161b-d40f-401d-8c83-7e1a385a7ebf.png>

thanks nolan

This warning means Flow couldn't find a running instance of Everything, so it needs Everything to be either installed if not or launched if not running.

**Comment by jjw24** [comment]
>Hi thanks yes I know but I thought it was not necessary to install it separately anymore because it from the last version is integrated in the file plugin

The functionalities are built in, but as it still requires actual Everything to work Everything is required to be installed still. We don't bundle it with setup because it's not necessary as users can just install it on-demand and there will be users who do not use Everything.


>Further I tried to install it manually and point to the directory but that didn't solve the problem with the error message I got maybe you could try to recreate it?

I will test it out with the current prd release. Could you let me know what Everything version you are using please.

**Comment by NolanNolan** [comment]
Hi

Thanks for trying to solve this, I use the only  everything version that can index file content, is version Everything-1.5.0.1335a.x64-Setup.exe.

I hope you can make sense of this, as flow launcher  is a great app and it would be very helpful if searching file content would work and even be shown with newest files at the top of the list.

But I cant make it work , indexing file content, and flow launcher still shows "everything service is not running" even after installing Everything-1.5.0.1335a.x64-Setup.exe.



***@***.***

Hilsen Jørn

On 1. februar 2023 22.06.30 Jeremy Wu ***@***.******@***.***>> wrote:

Hi thanks yes I know but I thought it was not necessary to install it separately anymore because it from the last version is integrated in the file plugin

The functionalities are built in, but as it still requires actual Everything to work Everything is required to be installed still. We don't bundle it with setup because it's not necessary as users can just install it on-demand and there will be users who do not use Everything.

Further I tried to install it manually and point to the directory but that didn't solve the problem with the error message I got maybe you could try to recreate it?

I will test it out with the current prd release. Could you let me know what Everything version you are using please.

-

**Comment by NolanNolan** [comment]
Hi

Yes it does, it is not correct that you write below, if I use file explorer and search for at complete sentence, only files with the exact sentence is presented. Therefore I was convinced that the same behaviour would apply using flow launcher with the “explorer plugin”

Hilsen Jørn

Fra: Jeremy Wu ***@***.***>
Sendt: 1. februar 2023 21:34
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Mention ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Find files that does not have the content searched for (Issue #1421)


Hi @NolanNolan<https://github.com/NolanNolan> with Explorer's content search it does not look for exact sentence, will look for each word in the sentence separately, e.g. if I search for 'hello world' using content search, it will return results containing 'hello', 'world', 'hello world'. You can verify the results by opening them and search for each of the words.

**Comment by NolanNolan** [comment]
I know, but it was installed see my previous answer where I write which version I used

thanks

Hilsen Jørn

Fra: Jeremy Wu ***@***.***>
Sendt: 1. februar 2023 21:35
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Mention ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Find files that does not have the content searched for (Issue #1421)


Further, If i select search method in settings as "everything" i ge tthis error below, i thought "everything" was natively integrated from the latest version, what does it mean?

[image]<https://user-images.githubusercontent.com/30736282/215325667-c4be161b-d40f-401d-8c83-7e1a385a7ebf.png>

thanks nolan

This warning means Flow couldn't find a running instance of Everything, so it needs Everything to be either installed if not or launched if not running.

**Comment by jjw24** [comment]
> Hi Thanks for trying to solve this, I use the only everything version that can index file content, is version Everything-1.5.0.1335a.x64-Setup.exe. I hope you can make sense of this, as flow launcher is a great app and it would be very helpful if searching file content would work and even be shown with newest files at the top of the list. But I cant make it work , indexing file content, and flow launcher still shows "everything service is not running" even after installing Everything-1.5.0.1335a.x64-Setup.exe. 

Everything 1.5a is currently not supported, please refer to this for working with 1.5a https://github.com/Flow-Launcher/Flow.Launcher/issues/1716

**Comment by jjw24** [comment]
> Hi Yes it does, it is not correct that you write below, if I use file explorer and search for at complete sentence, only files with the exact sentence is presented. Therefore I was convinced that the same behaviour would apply using flow launcher with the “explorer plugin” 

Just to clarify, you mean when you use Windows Explorer to do content search, only files with the exact sentence is presented, and this is the behavior you are expecting from Explorer plugin?
Apologies I mistaken the issue was with Windows Search's content search mechanism.

**Comment by NolanNolan** [comment]
Hi

regarding "Everything 1.5a is currently not supported, please refer to this for working with 1.5a https://github.com/Flow-Launcher/Flow.Launcher/issues/1716"

But that means Flow launcher cannot search file content using "everything" because versions of "everythinh below 1.5 does not index file content. 

So please explain why "everything" plugin can be chosen in settings for index file content ?

Nolan

**Comment by jjw24** [comment]
> Hi
> 
> regarding "Everything 1.5a is currently not supported, please refer to this for working with 1.5a #1716"
> 
> But that means Flow launcher cannot search file content using "everything" because versions of "everythinh below 1.5 does not index file content.
> 
> So please explain why "everything" plugin can be chosen in settings for index file content ?
> 
> Nolan

It can be chosen, but is very slow.

**Comment by jjw24** [comment]
> Yes if i you use windows file explorer to search for a complete text string for example "find this sentence" windows file explorer returns only files containing this exact sentence. But this is not the case using flow launcher plugion "Explorer"
> 
> Why is that ?

They should be both return the same result set, this is what I get with Windows File Explorer and it does return files that do not contain the exact prhase.

![image](https://user-images.githubusercontent.com/26427004/219174276-df6963bb-0228-4c49-8d92-07fb68d389ff.png)

Flow's content search does a search of the entire pc, same as Win File Explorer's 'Search Results In This PC'

**Comment by NolanNolan** [comment]
Hi

That is strange my file explorer returns only the files with content that match the exact text string

Hilsen Jørn

Fra: Jeremy Wu ***@***.***>
Sendt: 15. februar 2023 22:42
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Mention ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Find files that does not have the content searched for (Issue #1421)


Yes if i you use windows file explorer to search for a complete text string for example "find this sentence" windows file explorer returns only files containing this exact sentence. But this is not the case using flow launcher plugion "Explorer"

Why is that ?

They should be both return the same result set, this is what I get with Windows File Explorer and it does return files that do not contain the exact prhase.

[image]<https://user-images.githubusercontent.com/26427004/219174276-df6963bb-0228-4c49-8d92-07fb68d389ff.png>

Flow's content search does a search of the entire pc, same as Win File Explorer's 'Search Results In This PC'
