### ISSUE TITLE
Slovak language is not up to date

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#1423]
All strings in Crowdin are translated, but Slovak translation file is old.

**Comment by jjw24** [comment]
Hey, is this the 1.9.5 version? Dev branch would have the latest, but I haven't released any updated translations except for Spanish due to complications they could cause with the release.

**Comment by kubalav** [comment]
Yes, it is v1.9.5.

**Comment by taooceros** [comment]
@jjw24 what do you think about having an additional pipeline for master branch translation? Crowdin can share translation for the same string.

**Comment by jjw24** [comment]
So does this mean when you update the string in Crowdin, change is pushed to the Crowdin branches pointing to dev and master?

**Comment by taooceros** [comment]
> So does this mean when you update the string in Crowdin, change is pushed to the Crowdin branches pointing to dev and master?

The strings are shared, so we won't duplicate work. However, I am not really sure whether this may create conflict between dev and master.

**Comment by jjw24** [comment]
I think in the short term, I can just merge each Crowdin pr to the hot fix release pr after it's merged into dev. This is probably the easiest way to release quicker.

**Comment by jjw24** [comment]
Closing, no further action is required at this stage.
