### ISSUE TITLE
BUG: Segoe UI font looks bad in some languages

### ISSUE THREAD

**Issue by VictoriousRaptor** [Flow-Launcher/Flow.Launcher#1425]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Some text blocks like `TabMenu` has property `FontFamily` explicitly set to "Segoe UI", which looks bad in some languages like Chinese and Japanese (see screenshots below). Just simply delete the property `FontFamily` and let the program use system default font will fix it. It looks fine in Chinese, but not sure if it causes issues in other languages.

### Screenshots

Segoe UI vs system default font, Chinese
![Segoe UI vs system default font, Chinese](https://user-images.githubusercontent.com/10308169/192784188-c4bfcce2-8d19-4334-a4b1-14d42d12a0e7.png)

### Flow Launcher Version

v1.9.4-v1.9.5

### Windows Build Number

10.0.19044.2006

**Comment by onesounds** [comment]
Fixed. https://github.com/Flow-Launcher/Flow.Launcher/pull/1427
Thanks.
