### ISSUE TITLE
Index for Onedrive-Business

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#143]
**Question**
I am considering whether the explorer plugin may be able to search content in onedrive business, since the windows search seems provide this feature after many updates.

I think windows have done some limit to the windows index settings, while it is not available to index the onedrive-business folder as other folder.

**Comment by jjw24** [comment]
OneDrive is indexed by Explorer, even though it may not appear in the Window's indexing options.

Tested:
OneDrive version 20.134.0705.0008
Win1909

**Comment by taooceros** [comment]
> OneDrive is indexed by Explorer, even though it may not appear in the Window's indexing options.
> 
> Tested:
> OneDrive version 20.134.0705.0008
> Win1909

I know that Onedrive is indexed by Explorer, but Onedrive for business seems indexed in a different way.

Windows version: 2004

![image](https://user-images.githubusercontent.com/45326534/91014884-ca8e0800-e61c-11ea-97fa-85b59d2d9ef9.png)

**Comment by jjw24** [comment]
> > OneDrive is indexed by Explorer, even though it may not appear in the Window's indexing options.
> > 
> > Tested:
> > OneDrive version 20.134.0705.0008
> > Win1909
> 
> I know that Onedrive is indexed by Explorer, but Onedrive for business seems indexed in a different way.
> I have recently found that this search is working, while in the previous windows version I cannot search documents in Onedrive for Business.
> 
> The path shows differently, which seems like remotely?
> 
> ![image](https://user-images.githubusercontent.com/45326534/91014884-ca8e0800-e61c-11ea-97fa-85b59d2d9ef9.png)
> Windows version: 2004
> 

Yeah sorry I wasn't exact, I tested with OneDrive for Business and was able to get the files and folders.

Have you changed your OFB location?

Strange because if you are able to find them with windows search then Explorer should be picking them up as well.

**Comment by taooceros** [comment]
> Have you changed your OFB location?

If OFB means onedrive for Business, I do change it to D:, while I have also changed my personal onedrive to D: as well.

I have tried explorer, which seems unable to search files in OFB with index, but can only search it directly. However, windows search seems work in a different way.

**Comment by fdawans** [comment]
I was messing up with the indexing options as Flow was not finding VSCode.
For me, OFB and My Documents are not indexed.

I didn't have those issues when using Wox with Everything.
I could use the Everything plugin for Flow but unfortunately I don't have admin rights.
I don't know if the Everything plugin works without admin rights.

**Comment by fdawans** [comment]
I also had issues with indexing but it seems that adding 'C:\Users\_username_' to the index makes it works for me.

**Comment by jjw24** [comment]
> I added OneDrive for Business to the index by going to OneDrive settings > Settings > Files on demand (untick).
> Then OneDrive for Business is added to the user folder  'C:\Users\username' in indexing options.
> Windows Search finds the OneDrive files but Flow does not.

Thanks for letting me know. I don't have OFB anymore so will take some time to investigate this again.

> However, 'My Documents' folder is not indexed as it is on a server location.
Explorer won't be able to index a server location, as this is a limitation of Windows Index Search.

**Comment by jjw24** [comment]
> > Have you changed your OFB location?
> 
> If OFB means onedrive for Business, I do change it to D:, while I have also changed my personal onedrive to D: as well.
> 
> I have tried explorer, which seems unable to search files in OFB with index, but can only search it directly. However, windows search seems work in a different way.

i have a suspicion that this is caused by Explorer not searching drives other than C:\

**Comment by taooceros** [comment]
It should because it is server location, but I don't know how windows explorer handles the search when files is on demand. Explorer do search drives other than C:\ (but not all of them, only Document, Download, etc.).

**Comment by huutinh2712** [comment]
Though I change index options in Explorer, It's still can't search anything except C disk. That's weird. Can you told me how can I search on all disk in my computer with Flow

**Comment by jjw24** [comment]
> Though I change index options in Explorer, It's still can't search anything except C disk. That's weird. Can you told me how can I search on all disk in my computer with Flow

Are u running win 10? If so also check if some paths are being excluded by going to windows settings, search for windows search, and windows may automatically added in paths to be excluded from indexing.

**Comment by deefrawley** [comment]
Very old issue. Many updates have occurred since this was raised. Please update and if the problem persists we can reopen. Thanks

**Comment by jjw24** [comment]
Also just FYI I been able to use Explorer via Windows Indexer engine to search my OneDrive folder. The OneDrive path should obviously be configured to be indexed and my OneDrive folder is in C drive.
