### ISSUE TITLE
BUG: Graphical interface FL 1.9.5 Spanish Language

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1439]
In graphical interface FL 1.9.5 the description of "Finalizador de procesos" (Process Killer) does not match the translation in Crowdin.

![221002 FL 1 9 5_Configuración_Finalizador Procesos_Error con Crowdin](https://user-images.githubusercontent.com/102802425/193474275-83f9d708-6d44-45ae-b2e5-eccd5ee3f5fc.png)

**Comment by jjw24** [comment]
Hi there, this will be addressed by this PR here
https://github.com/Flow-Launcher/Flow.Launcher/pull/1429/files#diff-21411a273a7b67995f8f2ca9abfc8275ef2c395d0cec36114f54645ae6dd7724

Once merged, will be available in pre-release version.

**Comment by dracp** [comment]
**BUG: Graphical interface FL 1.9.5 Spanish Language_2**
In graphical interface FL 1.9.5 the description of "Marcadores del navegador" (Browser Bookmarks) does not match the translation in Crowdin.

![221003 FL 1 9 5_Configuración_Marcadores Navegador_Error con Crowdin](https://user-images.githubusercontent.com/102802425/193552208-3f618305-1e81-4a34-880b-36659eb43b64.png)

**Comment by jjw24** [comment]
I haven't checked but I think the prerelease build will have these changes if they are done via Crowdin. To verify Crowdin translations, should check against prerelease because Crowdin's translations are pushed to the prerelease build first and may or may not go out in the hot fix releases.

**Comment by jjw24** [comment]
>One question, can I have both versions installed?

Yep you can, you just need to have one of them as a portable version. I recommend download the portable version of pre-release, this way you can always go back to your installed production release version while testing/verifing the upcoming features, and if you can also fully switch across to it if you like as well because our pre-release is stable. UserData is transferrable too.

**Comment by dracp** [comment]
> 

Thanks.
