### ISSUE TITLE
BUG: Fl commadns only working when Taskmannager is wide open  behind FL search bar

### ISSUE THREAD

**Issue by Dyn4m00** [Flow-Launcher/Flow.Launcher#1444]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I tryed portable mode and then everything gone wrong, some plugings were not working, and the results of the searchs changed, for example alt+space then settings (at this point the settings of flow launcher with logo would appear) but this changed and just appear files that contain "settings" word

I turned off again the Portable mode as i noted this.... but i got an error, something like i should delete some %appdata% FL folder, so i desinstalled FL, and clean all registry issues with CCleaner, restarted my computer and reinstalled FL. it appears with portable mode-OFF as it should, but again... NOT all commands are working, i tried to "reinstall" plugins but FL says that it is already installed.

Also if i write "settings" or "exit" it not works as FL functions, they works as file search.

I was very happy and motivated installed and gettin  more efficient at my workflow, what could i do to get its functionallity back?

I regret a lot to try that "portable mode" i without the appropiate knowledge, now i f*ckd up my FL and even resintallation fails to solve the issue.

Thank you for your attention

### To Reproduce

1. ...Installed FL
2. ...Installed and configured a lot of plugings
3. ...they all worked very good
4. stupidly i tried to turn on portable-mode
5 some plugin commands stopped working, also FL basic commands as settings and exit become web searches
6Turned off portable mode
7 got an error about delete some %appdata% folder
8 uninstalled FL for good and clared registry with CCLEANER (solve the appdata issue)
9 restart PC
10 Reinstall FL and portable mode is off!!!
11 some commands and plugings still NOT WORK, its like if i did not anything

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

![IHPANnr](https://user-images.githubusercontent.com/89666469/193976975-d67229cd-74ab-4b3e-8813-20207815bf0f.png)

Check  yt command not working but appeared ON and fully installed

NEW INFORMATION

1 When i restart my computer and lounch FL for first time, IT WORKS!!!! but then if i close the search bar and call it again... after some time it wont work again... like if another process imhibits it after windows is allready start

2 if start taskmannager (ctrl+alt+supr) FL start to work fine with all comands, but if i close taskmannager FL remain to fail with pluging commands this is VERY WEIRD in my opinion! 

3 The thask mannager should be back and open, if i minimize it.. then it would lost its power to help FL
![UaiH411](https://user-images.githubusercontent.com/89666469/193985470-da4b10da-be9a-43c4-8186-ce77eeadcbd8.png)
working again ONLY IF with taskmannager open and behind FL

**Comment by Dyn4m00** [comment]
![IHPANnr](https://user-images.githubusercontent.com/89666469/193976904-8187abcc-5789-4704-9353-ad9a6db44d99.png)

**Comment by jjw24** [comment]
Hi, from the screenshot it looks like you have PowerToys installed, which is probably what is appearing when you press alt + space because it uses the same keyboard shortcut. Turn off PowerToy's Run and you should see flow when pressing alt+space. You can also change Flow's keyboard shortcut via its settings.
