### ISSUE TITLE
BUG: Graphical interface FL 1.10.0 Spanish Language.

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1454]
1. String "Open (Alt + Space)", not found in Crowdin

![221006 FL 1 10 0_Modificar cadena en Crowdin_IconTrayOpen](https://user-images.githubusercontent.com/102802425/194273952-8dd3e196-ba77-4b33-af46-4d9f0131edca.png)

2. Developer (Desarrollador) is spelled with LL (two els), instead of one. "Desarrollador" instead of "Desarrolador".

![221006 FL 1 10 0_Modificar traducción_Desarrollador](https://user-images.githubusercontent.com/102802425/194280338-c2968932-fe15-459f-aeac-52098c92b51d.png)

**Comment by VictoriousRaptor** [comment]
> String "Open (Alt + Space)", not found in Crowdin

"(Alt + Space)" is dynamically generated based on the hotkey, not a translation. See #917.

**Comment by dracp** [comment]
Revised FL 1.10.0, installed on October 08
**Fixed Developer (Desarrollador)**

![221008 FL 1 10 0 10 08 22_Herramientas del desarrollador_Corregido](https://user-images.githubusercontent.com/102802425/194702656-0122fa0e-5de1-4326-adb0-e93a9adc3db4.png)
