### ISSUE TITLE
Duplicate strings at Crowdin

### ISSUE THREAD

**Issue by smarquespt** [Flow-Launcher/Flow.Launcher#1456]
@taooceros 

Kevin, in Crowdin we have duplicate strings.

![image](https://user-images.githubusercontent.com/1302668/194419933-58f37343-d3d4-47ff-bfa8-53dbac707492.png)

Already exist at:

![image](https://user-images.githubusercontent.com/1302668/194419986-30b6ac05-15c3-4eb7-8809-9ac8b56584fa.png)

Please consider removing one.

Thanks

**Comment by taooceros** [comment]
There's some old translation that has been add to the first one I believe. I keep it there so we don't have to translate that again (crowdin will merge duplicate string I believe).

**Comment by smarquespt** [comment]
If you think necessary, fine for me, closing.
