### ISSUE TITLE
BUG: Graphical interface FL 1.10.0 (10.08.2022) Spanish Language and Others

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1461]
In the **"Everything" plugin**, in several languages, the different classification types are displayed without the upward ↑ and downward ↓ arrows that are displayed in English.

![221008 FL 1 10 0 10 08 22_Everything Complemento_Español y Otros_SIN flechas Ascendente_Descendente2](https://user-images.githubusercontent.com/102802425/194706026-77187a77-7dc3-4c59-8049-4cce21cd2cd6.png)

**Comment by taooceros** [comment]
It has now been fixed.

**Comment by dracp** [comment]
> ~It has now been fixed.~ It will be fixed soon

Revised FL 1.10.0 (October 12)
Not modified.

**Comment by taooceros** [comment]
> > ~It has now been fixed.~ It will be fixed soon
> 
> Revised FL 1.10.0 (October 12) Not modified.

yeah the pr is not being merged. Have you proposed all the change in crowdin?😉

**Comment by taooceros** [comment]
It should be done here https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/pull/61

**Comment by dracp** [comment]
Revised "FL 1.10.0 (October 17)", bugs remain.

**Comment by jjw24** [comment]
Please update to latest Everything plugin. If translations still missing please reopen.

**Comment by dracp** [comment]
> Please update to latest Everything plugin. If translations still missing please reopen.

FL 1.10.0. (October 18)
**Plugin Everything 1.7.7. Fixed.**

![221018 FL 1 10 0 (October 18)_Plugin Everything 1 7 7_OK](https://user-images.githubusercontent.com/102802425/196369475-9690e393-9fb5-46ba-9d48-ef98e992ba20.png)
