### ISSUE TITLE
BUG: Always having duplicate results

### ISSUE THREAD

**Issue by Hamybal** [Flow-Launcher/Flow.Launcher#1473]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

![image](https://user-images.githubusercontent.com/73068767/195581660-1c33c551-8598-4b5c-a28f-fef615b9f37a.png)
With every search i do on any of the drive I'll get a duplicate result which at first didn't happen.
I've tried "Delete and Rebuild Indexes" which didn't solve it so afterwards i uninstalled FlowLauncher and delete all it's folders and reinstalled it and reindexed everything but the same thing happened.

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19044.2006

### Error Log

</details>
[2022-10-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9776077/2022-10-12.txt)
[2022-10-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9776078/2022-10-13.txt)

**Comment by onesounds** [comment]
you can see what plugin provide result in context menu. for example, if you have two plugin (everything, explorer), you'll get result like that. check this. If not, try to press f5 in querybox.

**Comment by jjw24** [comment]
Hi, are you using Everything plugin as well by any chance? If not, can you go to context menu of both results and scroll down to bottom to see which plugin they are from.

**Comment by onesounds** [comment]
> you can see what plugin provide result in context menu. tell me both result what plugin provided. for example, if you turned on two plugin (everything, explorer), you'll get result like that. check this. If not, try to press f5 in querybox.

**Comment by jjw24** [comment]
> you can see what plugin provide result in context menu. for example, if you have two plugin (everything, explorer), you'll get result like that. check this. If not, try to press f5 in querybox.

Lol @onesounds beat me to it, you too fast 🤣

**Comment by Hamybal** [comment]
You guys are extremely fast with responding!
Yeah when turning of "everything" in flow settings it stopped doing it, is it possible to only use the everything searches because i noticed searching with everything is a bit easier because you can search for ex. Breaking Bad S02E03 to get the episode where as flow itself doesn't work and have to be more precise.

Thank you guys for the support.

**Comment by Hamybal** [comment]
Well now I'm disapointed that I couldn't figure that out myself and good to know that it will merge in the future, well none the less I appreciated your guys work Sonichu(s)!

Have a splendid day.
