### ISSUE TITLE
BUG: Graphical interface FL 1.10.0 (October 20) Spanish Language

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1495]
FL 1.10.0 (October 20)
**1. The string "Icons" is not translated. Not found in Crowdin**

![221021 FL 1 10 0 (October 20)_Icons_No traducido_No está en Crowdin](https://user-images.githubusercontent.com/102802425/197180155-eac9b948-f437-45cb-8f7c-3c746969e356.png)

**2.  Mouseover popup on folder and file, is not translated. Not found in Crowdin** 
"Ctrl+Enter to open the directory"
"Ctrl+Enter to open the containing folder"

![221021 FL 1 10 0 (October 20)_Ratón sobre Carpeta_Archivo_No traducido_No está en Crowdin](https://user-images.githubusercontent.com/102802425/197247523-86e30f9c-9d65-497b-9750-6835e39398af.png)

**Comment by onesounds** [comment]
**memo**
- first issue fix in https://github.com/Flow-Launcher/Flow.Launcher/pull/1548
- 2nd issue in explorer plugin's constant.cs. Must be applied in merge explorer pr.
