### ISSUE TITLE
Changes is source strings

### ISSUE THREAD

**Issue by smarquespt** [Flow-Launcher/Flow.Launcher#1497]
@taooceros 
Follow up for crowdin discusssion:
![image](https://user-images.githubusercontent.com/1302668/197344287-595eaf72-265c-440a-a168-4b3014383af5.png)

<b>Following strings:</b>
![image](https://user-images.githubusercontent.com/1302668/197344317-c47a5b1c-6b74-4a01-82e3-3636191bab79.png)
![image](https://user-images.githubusercontent.com/1302668/197344331-f4d30cc8-bb79-4411-a09f-6c1958b16286.png)

If all these are related, shouldn't following string be:

<i>Remember last launch position</i>
<i>Remember Last Position</i>

**Comment by smarquespt** [comment]
Another:
![image](https://user-images.githubusercontent.com/1302668/197344593-a1f45e5d-0549-4256-8539-aefeb89e40e8.png)

Shouldn't this be:

You can also quickly adjust this by using Ctrl+[ and Ctrlcolor="red"-].

**Comment by taooceros** [comment]
> Another:
> 
> ![image](https://user-images.githubusercontent.com/1302668/197344593-a1f45e5d-0549-4256-8539-aefeb89e40e8.png)
> 
> 
> 
> Shouldn't this be:
> 
> 
> 
> You can also quickly adjust this by using Ctrl+[ and Ctrl-].

Oh i think this is correct? The + is only saying key combination but not the actual key

**Comment by smarquespt** [comment]
Typo in this string:

![image](https://user-images.githubusercontent.com/1302668/204060419-06fd5e85-ef60-4baa-96cb-1fd6355c8f00.png)

**Comment by taooceros** [comment]
> Typo in this string, "alreaday" should be "already"
> 
> ![image](https://user-images.githubusercontent.com/1302668/204060419-06fd5e85-ef60-4baa-96cb-1fd6355c8f00.png)

Thanks! I will check recently
