### ISSUE TITLE
BUG: Some files and folders can't be searched 

### ISSUE THREAD

**Issue by MW-J97** [Flow-Launcher/Flow.Launcher#1502]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

Hi there, 
When I search some folders and files that are not hidden or excluded in the "Search index", they are not shown. I use the "Explorer plugin" not "Everything".
Can this issue be fixed?? 

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19044.2130

### Error Log

[2022-10-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9881813/2022-10-27.txt)

**Comment by minawaheed9697** [comment]
If there is no fix for this, can I make "Everything plugin" like "Explorer"? "Explorer" has a great feature of searching subfolders, i.e. when I search a folder and click it, it doesn't open the folder in a window, but it searches its subfolders and files like this https://imgur.com/a/tpFxf4g

**Comment by taooceros** [comment]
We are working on that.

**Comment by minawaheed9697** [comment]
> We are working on that. #1097

Thanks for replying. So, this will fix the search issue, but will not affect the Explorer feature explained above??

**Comment by taooceros** [comment]
This is for merging explorer and everything so you can search with everything service but using explorer feature.

**Comment by minawaheed9697** [comment]
Okay, that you so much for help.
Will it be added soon?

**Comment by minawaheed9697** [comment]
> We are working on that.

**Comment by taooceros** [comment]
It should be included in the next major release. However we are approaching it slowly. I wouldn't say when will it be released. Once we finish that pr, i will notify you.

**Comment by minawaheed9697** [comment]
Okay, thank you so much for help.
Waiting for it ❤

**Comment by taooceros** [comment]
By the way the reason explorer cannot search some folder is because windows doesn't index all folder by default. You can check what is being index by opening the index option.

![image](https://user-images.githubusercontent.com/45326534/198400644-27065a0e-bd08-4a74-8c5c-54644e72b7a5.png)
It's the context menu for explorer.

**Comment by minawaheed9697** [comment]
> You can check what is being index

I checked it, but the folders that are not searched are indexed, not excluded.

**Comment by jjw24** [comment]
> > You can check what is being index
> 
> I checked it, but the folders that are not searched are indexed, not excluded.

Can you see if those folders come up with windows start menu search, golden rule for files and folder search, Explorer plugin results should mirror start menu because they both use Windows search indexed data. If it doesn't come up in windows start menu search, then even though it is ticked in windows search index, maybe index data needs a rebuild.

**Comment by minawaheed9697** [comment]
> Can you see if those folders come up with windows start menu search

Yes, it comes up on Windows start menu search. 
Should I rebuild the index??

**Comment by jjw24** [comment]
Hm if it shows on start menu search then it should in Explorer. Do a rebuild of index see if it makes a difference.

 Also can you show me in the Explorer plugin settings, what are your settings for the hotkeys.

**Comment by minawaheed9697** [comment]
> Also can you show me in the Explorer plugin settings, what are your settings for the hotkeys.
![31_10_2022 11_35_28_077](https://user-images.githubusercontent.com/73688266/198977540-30a1db69-bc82-43cb-9379-5afd39ed604b.png)

> Additonally, the files you are looking for are they in C drive?
No, they are in another drive.

**Comment by jjw24** [comment]
Hmm settings looks fine.

>Additonally, the files you are looking for are they in C drive?
No, they are in another drive.

I don't have any machines with multiple drives to test, can you check for me please if other files in the that drive show up at all? Wonder if the problem is because it's not in C drive.

**Comment by jjw24** [comment]
So other files inside the folder where these files are missing can be searched? That's strange. What's the name of the file and the location path?

Can you create a new file in the same folder and see if it can be searched also please.

**Comment by minawaheed9697** [comment]
> What's the name of the file and the location path?

It's a folder called "Fun" and the files and folders inside it can be searched normally.

**Comment by jjw24** [comment]
Do if you make a copy of those missing files do they show up? 

If some files can be searched while others can't, I still think it may be related to windows indexing.

**Comment by minawaheed9697** [comment]
> Do if you make a copy of those missing files do they show up?

I didn't try as the folder is very big. 


> If in the same location some files can be searched while others can't, I still think it may be related to windows indexing.

I rebuilt the index.

**Comment by jjw24** [comment]
> > Do if you make a copy of those missing files do they show up?
> 
> I didn't try as the folder is very big.

If just some files missing while other files in the folder can be found, do a copy of those missing files and see if they show up, no need for the entire folder.
