### ISSUE TITLE
BUG: lnk files appear instead of app.

### ISSUE THREAD

**Issue by JPRial** [Flow-Launcher/Flow.Launcher#1513]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

lnk file appear instead the app of League of Legends. Maybe it's Everything plugin what is causing this search, but this doesn't happen when I search for other programs. I'm sharing SS's.

Also, just checked the log files and having a lot of WARN and ERROR (Errors involving WindowsApps not showing when i search for them with FL). Anyways, I couldn't find anything related to League of Legends client. I'm attaching the log files.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/98665840/199613128-46a9262c-2879-409c-816e-68e3221bca0c.gif)
This is how it appears

However, when I search other app, it doesn't show the .lnk file as the first search, but the program itself.

![Issue Programs Search 3](https://user-images.githubusercontent.com/98665840/199612743-cafea0f1-9d41-4773-b663-863dcba40a36.gif)

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19045.2193

### Error Log

<details>

```shell

Log file attached.

```
[2022-11-02.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9924397/2022-11-02.txt)

</details>

**Comment by jjw24** [comment]
Hi, we have added proper handling of these type of programs and is available in prerelease version, could you give it a go and see if it resolves this please.

**Comment by JPRial** [comment]
How do i download prerelease version?

**Comment by JPRial** [comment]
Ok managed to find out where's the prerelease version at 😁. But, the problem remains the same. 

Although, WhatsApp appears now appears correctly (and all Microsoft Store Apps), League of Legends still as a file .lnk. 

https://user-images.githubusercontent.com/98665840/199635513-ca6311a7-a51f-4ff8-a2c0-4b93fe550506.mp4

**Comment by jjw24** [comment]
Hmm, is that link lol file from steam or epic games?

**Comment by JPRial** [comment]
They are brought up by explorer Plugin. Both of them. 
![image](https://user-images.githubusercontent.com/98665840/199641057-d5295ddc-0742-4778-b203-2b32f6beaacb.png)

And it's not from steam or epic games. It is a shortcut made when you install the app. It redirects here:
![image](https://user-images.githubusercontent.com/98665840/199641292-aba65f44-3d77-48e0-bcad-529b70817c64.png)

And the second one:
![image](https://user-images.githubusercontent.com/98665840/199641431-a5a3e9ba-bec0-4045-88d6-9472b6ef314f.png)
To the Start Menu > Programs. 

Actually, dunno why I have two shortcuts.

**Comment by jjw24** [comment]
Can you go to program plugin's settings, I'm afk, I don't remember if it indexes lnk files by default, can you check and tick if not. If ticked, press f5 on the search window to reload data. Basically this file should be loaded by program plugin if I remember correctly.

**Comment by JPRial** [comment]
Indeed. Program plugin searchs this. I managed to fix it by adding the folder when LeagueOfLegends.exe was in. Now it looks like it should. 
![image](https://user-images.githubusercontent.com/98665840/199647591-db6e671a-56f4-441f-b792-da2d91459307.png)

**Comment by JPRial** [comment]
Thanks for the patience!! 👏

**Comment by jjw24** [comment]
strange it should be indexing that start menu location, did you happen to do a reload of plugin data or was index start menu not ticked?
