### ISSUE TITLE
flow launcher settings

### ISSUE THREAD

**Issue by RamBeladia** [Flow-Launcher/Flow.Launcher#1517]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

i have been trying to get into the flow launcher settings to change the way the search bar looks but it is not letting me open it every time I try it shows a notification. 

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://user-images.githubusercontent.com/94926810/200171045-0d91cec4-0aeb-456c-ba46-9c9219ed9528.png)

it just says ' all Flow Launcher settings saved'.

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19044.1466

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by VictoriousRaptor** [comment]
Sorry about your problem. Please upload your log file (by default it's at `%APPDATA%\FlowLauncher\Logs\x.x.x`) so we can further investigate this issue.

**Comment by jjw24** [comment]
@RamBeladia can you also screenshot us the result you are selecting to go into settings please.

**Comment by RamBeladia** [comment]
Hello
Sorry for the mistake it was my fault I kind of had to figure out how to do
it.
Since I was not opening when i tried pressing on the application it was not
opening

I go rid of the problem



King regards


Ram beladia

**Comment by jjw24** [comment]
No worries :)
