### ISSUE TITLE
UWP programs icon cannot be found after it has been updated

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#152]
**Describe the bug/issue**
UWP programs icon cannot be found after it has been updated.
My windows terminal app's icon cannot be found after it has been automatedly updated.
I have checked the log, and it indicates that the index for windows terminal is still on the old version.
It can be fixed by manually reindex program.
I think it may be possible to fix this by reindex the specific app whenever it fail to found the files.

It has been a little werid

**Your System**
```
Windows build number: 2004  [版本 10.0.19041.450]
Flow Launcher version: 1.2.1
```
**Flow Launcher Error Log**
`
2020-08-31 16:01:44.9255|ERROR||------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
2020-08-31 16:01:44.9255|ERROR||
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: ImageFromPath
Program path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2233.0_x64__8wekyb3d8bbwe\Images\Square44x44Logo.scale-100.png
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: Unable to get logo for Microsoft.WindowsTerminal_8wekyb3d8bbwe!App from C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2233.0_x64__8wekyb3d8bbwe\Images\Square44x44Logo.scale-100.png and located in C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2233.0_x64__8wekyb3d8bbwe
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
2020-08-31 16:01:44.9255|ERROR||------------- END Flow.Launcher.Plugin.Program exception -------------`

![image](https://user-images.githubusercontent.com/45326534/92227178-7b778b00-eed8-11ea-8ca8-d51440e658e9.png)

You can see that the path showing in log is older than the actual version of the program.

*Note*
I am not sure whether this is happening generally since only I doesn't meet this issue for other UWP Programs.

**Comment by jjw24** [comment]
At the moment the reindex is set to every 3 days if I remmeber correctly. This is why it is still pointing to the old location.

It's an interesting suggestion to reindex the specific app if it fails to load. Let me think about it and have a play.

**Comment by taooceros** [comment]
hhh that's a possible way.
For the UWP loading, even if the image cannot be loaded, it can be opened. That's really interesting.

**Comment by taooceros** [comment]
I am really interested about how flow open UWP program.
Could you give me a hint?

**Comment by jjw24** [comment]
Sure, current release version uses an old library to load the uwp program. Take a look in the Infrastructure project => ImageLoader class.

The loading of UWP thumbnail image is separate to the loading of UWP itself that's why sometimes it fails to load a UWP app's thumbnail image but the app itself can be run.

In the PR list I put through one that improved on the loading of UWP images using an updated code which has solved a few more UWP image loading issues. It's still being tested so not done yet.

**Comment by taooceros** [comment]
Thanks, that helps.

Big change is usually hard to test. Hope to see it done in the future.
