### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SuperSayf** [Flow-Launcher/Flow.Launcher#1531]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

High CPU usage with windows explorer when searching for directories, and the high usage does not stop after that. On a fresh restart, windows explorer is at normal usage. While searching for a directory using flow launcher alt+space, windows explorer usage is fine, but as soon as I hit enter on a directory, my windows explorer usage spike to about 15-20% with multiple instances, and it stays at that until I manually restart windows explorer though task manager

### To Reproduce

1. Launch flow launcher using alt+space
2. Search for a directory (Ex. Downloads)
3. Hit enter

### Screenshots

Before search:
![Taskmgr_jhcKTXRmp7](https://user-images.githubusercontent.com/47222381/201480332-c2e19740-980e-466d-8af2-176890b1c79e.png)

After search:
![Taskmgr_8OGxorupDa](https://user-images.githubusercontent.com/47222381/201480336-4b711d98-a591-4775-bea2-ad7f3be828bb.png)

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.22621.819

### Error Log

[2022-11-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9995223/2022-11-12.txt)

**Comment by jjw24** [comment]
I can not reproduce this issue, is there method I can try? 

Flow doesn't use Windows Explorer to do anything during the search until opening the selected path with it via the 'open current directory' result, so not sure why that would be related when you are just doing searches.

When you pressed enter, did you enter into the directory via flow (where all subdirectories are listed in the search window) or open the directory with Windows Explorer?

**Comment by SuperSayf** [comment]
> I cannot reproduce this issue, is there another method I can try?
> 
> Flow doesn't use Windows Explorer to do anything during the search until opening the selected path with it via the 'open current directory' result, so not sure why that would be related when you are just doing searches.
> 
> When you pressed enter, did you enter into the directory via flow (where all subdirectories are listed in the search window) or open the directory with Windows Explorer?

Hey, so I'm exactly sure what is the issue, so I attached a video of the problem, hopefully it helps

[Link to video](https://sayf.tixte.co/FlowIssue.mp4)
