### ISSUE TITLE
BUG: Disabling a program from being display in Programs should reindex data

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1532]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Disabling a program from being display in Programs plugin should reindex data, otherwise the program is still showing up until next plugin data reload.

### To Reproduce

1. Disable a program from the Programs plugin via context menu and select 'Disable this program from displaying'
2. Message acknowledges success
3. Program still shows up during searches until plugin data reload is triggered.

### Flow Launcher Version

v1.9.5

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by VictoriousRaptor** [comment]
Already fixed in #1496.

**Comment by Da3n0n** [comment]
how do I re enable program for displaying. I have accidentally disabled program form displaying ? please help

**Comment by Da3n0n** [comment]
never mind have found it underneath the "program" Plugin in the plugin settings . tks
