### ISSUE TITLE
Program Plugin browse button too narrow

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#1533]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Browse button to edit program source is too narrow to display translations.
I suggest to make the "Browse" button more widely. Button text is cutted off in multiple translations.

### Screenshots

![obrázok_2022-11-14_112840195](https://user-images.githubusercontent.com/37414585/201637366-2b243724-a301-47b5-a3ae-680a53bbd3a1.png)

### Flow Launcher Version

v1.9.5 dev

### Windows Build Number

10.0.19045.2251

**Comment by onesounds** [comment]
It's my mistake, When I was not familiar with WPF, I put the buttons size as a fixed value. I'll fix it.
