### ISSUE TITLE
HelloWorldPython can not properly load

### ISSUE THREAD

**Issue by ianzhuo** [Flow-Launcher/Flow.Launcher#155]
Hi there,

Trying test HelloWordlyPython plugin template, but get error log as below.

**Flow Launcher Error Log**

2020-09-18 19:11:06.7834|ERROR|JsonRPCPlugin.Execute|  File "C:\Users\ianzh\AppData\Roaming\FlowLauncher\Plugins\HelloWorldPython\main.py", line 3
    from flow.launcher import Flow.Launcher
                                  ^
SyntaxError: invalid syntax

**Comment by ianzhuo** [comment]
In `HelloWorldPython/main.py` use code as below will import the correct module `wox.py`.

`from flow.launcher import Flow.Launcher ---> from wox import FlowLauncher`

It make sample code worked.

**Comment by jjw24** [comment]
Hey thanks for letting me know. That should be the behaviour. Let's keep this issue open so I can circle back to this.

**Comment by Zeroto521** [comment]
fixed.
see the following links.
[HelloWorldPython](https://github.com/Flow-Launcher/plugin-samples/tree/master/HelloWorldPython) & [Flow.Launcher.JsonRPC.Python](https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python)
