### ISSUE TITLE
BUG: No plugins in Plugin Store 

### ISSUE THREAD

**Issue by yanxxx08cn** [Flow-Launcher/Flow.Launcher#1565]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

why my plugin store is empty？

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://user-images.githubusercontent.com/60805462/203341670-00640598-06ad-4e21-b0a7-660b59f5c1ba.png)

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by raremang0** [comment]
click refresh is nothing

**Comment by VictoriousRaptor** [comment]
Please check your connectivity to GitHub and proxy settings. And try to type `pm install ` in the search window and wait for it. It should list some plugins if network is ok.

**Comment by taooceros** [comment]
Are you in China? Could you check the prerelease version?

**Comment by raremang0** [comment]
sorry, my version is 1.9.5, my network is ok, I input pm install is still nothing, Maybe it's because I'm in China？

**Comment by taooceros** [comment]
> sorry, my version is 1.9.5, my network is ok, I input pm install is still nothing, Maybe it's because I'm in China？

Could you check the prerelease version? We use cdn there. China is known to have connection issue with github (sucks)

**Comment by taooceros** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/discussions/956

**Comment by jjw24** [comment]
@raremang0 for prelease download: https://github.com/Flow-Launcher/Flow.Launcher/discussions/956
