### ISSUE TITLE
Python template advice

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#157]
From https://github.com/jjw24/Wox/issues/195

![image](https://user-images.githubusercontent.com/26427004/93664073-8a049b80-faaf-11ea-8084-8c1dc4cdbe40.png)

[Wox.Plugin.PythonTemplate](https://github.com/Zeroto521/Wox.Plugin.PythonTemplate)
[Wox.Plugin.Timestamp](https://github.com/Zeroto521/Wox.Plugin.Timestamp)

**Comment by Zeroto521** [comment]
If you like it, we can rich it.
Also I can **transfer ownership** to Flow-Laucher team. I think it is the better to the project.
