### ISSUE TITLE
Should the JsonRPC/wox.py stay with the main solution

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#158]
From https://github.com/jjw24/Wox/issues/196

![image](https://user-images.githubusercontent.com/26427004/93664271-c71d5d80-fab0-11ea-9162-e6b84ab54632.png)

[Wox.Plugin.Timestamp](https://github.com/Zeroto521/Wox.Plugin.Timestamp/blob/master/plugin/wox.py).

**Comment by jjw24** [comment]
I dont think it's a good idea to put it in a plugin. We need it to be a common library so it can be referenced and developed rather than each python plugin has its own version of it.

**Comment by Zeroto521** [comment]
@jjw24 I agree. Build `wox.py` as a package. That's why I issued this problem.

**Comment by Zeroto521** [comment]
I'm not a `C#` developer, so I don't know how useful the `wox.py` is.
But as a `Python` developer, I think it's no use in Wox. And it has trouble with Python developer.
`¯\_(ツ)_/¯ `

**Comment by jjw24** [comment]
> I'm not a `C#` developer, so I don't know how useful the `wox.py` is.
> But as a `Python` developer, I think it's no use in Wox. And it has trouble with Python developer.
> In my option, using `Json RPC` just likes to exchange data information.
> `C#` gets data by `python.exe` running `wox.py`. And the `JsonRPC` is the data.
> Therefore, `wox.py` can be anywhere. If the plugin is the subclass of `Wox`.
> `¯\_(ツ)_/¯ `

From your points I think it makes sense to bring it out as a separate one. I have not had the chance to play around with it yet as I am working on another part of Flow. Flow's non-c sharp areas need a uplift for sure. If you like you can let me know or create your own repo show how best wox.py should be developed. Otherwise I will circle back to this any way once I am done as it's next on my plate.

Good discussions.

**Comment by Zeroto521** [comment]
May be you should create an empty project called **JsonRPC** or else in **Flow-Launcher** organization.
I can finish it as a total Python package. When we check it already, we can upload it to PyPI.

**Comment by jjw24** [comment]
> May be you @jjw24 should create an empty project called **JsonRPC** or else name in **Flow-Launcher** organization.
> I can finish it as a total Python package. When we check it already, we can upload it to PyPI.

Sure thing. 

I can do with some help in the Python development, would you like to be part of the team?

**Comment by jjw24** [comment]
Created here https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python. We can rename the repo later on if need be

**Comment by Zeroto521** [comment]
> > May be you @jjw24 should create an empty project called **JsonRPC** or else name in **Flow-Launcher** organization.
> > I can finish it as a total Python package. When we check it already, we can upload it to PyPI.
> 
> Sure thing.
> 
> I can do with some help in the Python development, would you like to be part of the team?

That's my pleasure.

**Comment by jjw24** [comment]
I have sent you an invite to the team

**Comment by Zeroto521** [comment]
I got it, 🤝.
