### ISSUE TITLE
BUG: Win+R still call the system "run" out

### ISSUE THREAD

**Issue by Darkluna999** [Flow-Launcher/Flow.Launcher#1584]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

1. Sometimes after I input `Win+R` it will have a short flash of Flow Launcher then the window of system `run` will come out.
2. And will you supply an option of `windows terminal` to run the code? powershell is not beautiful.

### Flow Launcher Version

v1.9.5

### Windows Build Number
dev Bulid 25247

**Comment by Newedge-Isaiah** [comment]
Here’s a workaround:

1. Open the Registry Editor (regedit)
2. Navigate to: “HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced”

4. Right click on the Advanced folder on the left pane and select New -> String Value
5. Name it “DisabledHotkeys”
6. Set its value to “R”. This will disable the default Windows Key + R shortcut that launches Windows Run.

**Comment by onesounds** [comment]
Reproducable. No problem with the old version. I think the code related to the shortcut has changed.
This issue needs to be fixed. @taooceros @jjw24 

related https://github.com/Flow-Launcher/Flow.Launcher/issues/1242

**Comment by Darkluna999** [comment]
> 

sorry, it does not work, and I think it need be fixed by the developing of this software but not in the regedit

**Comment by Darkluna999** [comment]
> Here’s a workaround:
> 
> 1. Open the Registry Editor (regedit)
> 2. Navigate to: “HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced”
> 3. Right click on the Advanced folder on the left pane and select New -> String Value
> 4. Name it “DisabledHotkeys”
> 5. Set its value to “R”. This will disable the default Windows Key + R shortcut that launches Windows Run.

sorry, it does not work, and I think it need be fixed by the developing of this software but not in the regedit

**Comment by Newedge-Isaiah** [comment]
> > Here’s a workaround:
> > 
> > 1. Open the Registry Editor (regedit)
> > 2. Navigate to: “HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced”
> > 3. Right click on the Advanced folder on the left pane and select New -> String Value
> > 4. Name it “DisabledHotkeys”
> > 5. Set its value to “R”. This will disable the default Windows Key + R shortcut that launches Windows Run.
> 
> sorry, it does not work, and I think it need be fixed by the developing of this software but not in the regedit

You need to reboot in order for changes to take effect

**Comment by Darkluna999** [comment]
> > > Here’s a workaround:
> > > 
> > > 1. Open the Registry Editor (regedit)
> > > 2. Navigate to: “HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced”
> > > 3. Right click on the Advanced folder on the left pane and select New -> String Value
> > > 4. Name it “DisabledHotkeys”
> > > 5. Set its value to “R”. This will disable the default Windows Key + R shortcut that launches Windows Run.
> > 
> > 
> > sorry, it does not work, and I think it need be fixed by the developing of this software but not in the regedit
> 
> You need to reboot in order for changes to take effect

Ah, I forgot it, and now it's work, but I still want it fix in the softwore development

**Comment by onesounds** [comment]
Let me also look at the additional issues mentioned.
I think it's not related with the IME. (Some of our team members use Chinese IME.)
 This issue is of high priority and will be corrected as soon as possible.

**Comment by Darkluna999** [comment]
> Let me also look at the additional issues mentioned. I think it's not related with the IME. (Some of our team members use Chinese IME.) This issue is of high priority and will be corrected as soon as possible.

Thanks

**Comment by jjw24** [comment]
Thanks for trying our prerelease build, please try the latest upload which should fix this issue:
https://github.com/Flow-Launcher/Prereleases/releases/latest/download/Flow-Launcher-Portable.zip

Please reopen the issue if issue persists.

**Comment by Darkluna999** [comment]
> Thanks for trying our prerelease build, please try the latest upload which should fix this issue: https://github.com/Flow-Launcher/Prereleases/releases/latest/download/Flow-Launcher-Portable.zip
> 
> Please reopen the issue if issue persists.

Yeah, it was fixed!
