### ISSUE TITLE
Let setting UI support for other program languages

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#159]
## Question

As title.

More can see [jjw24/Wox#178](https://github.com/jjw24/Wox/issues/178).

## Discussion

I think just like using **JSON-RPC** for supporting other program languages. 

Why not using some **template file** for support setting UI. 

But at the same time, we need a **tool** to compile the file and  **inject in** the Flow main program.

To make it just like a `C#` plugin.

![Interaction](https://user-images.githubusercontent.com/25895405/93783646-85321a00-fc5e-11ea-8f8b-19f55721d03b.png)

**Comment by jjw24** [comment]
Interesting indeed. Let me think how we can do this
