### ISSUE TITLE
BUG: Virustotal reports 3 positives including two trojans

### ISSUE THREAD

**Issue by acorazza** [Flow-Launcher/Flow.Launcher#1592]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

![flow](https://user-images.githubusercontent.com/10003207/205400341-11d7b937-478e-40a4-8737-f9c49f54c6c7.png)

### To Reproduce

1. Upload the Windows installer to Virustotal

### Flow Launcher Version

v1.9

**Comment by Garulf** [comment]
Please see: https://github.com/Flow-Launcher/Flow.Launcher/issues/1279

**Comment by acorazza** [comment]
Sorry about that, I searched for "virus" but not "trojan" will close this.

**Comment by Garulf** [comment]
NP, just wish virustotal was a little more helpful in explaining whats flagging our program so we can fix these false positives.
