### ISSUE TITLE
Don't search WindowsApps folders by default

### ISSUE THREAD

**Issue by voltagex** [Flow-Launcher/Flow.Launcher#1599]
**Is your feature request related to a problem? Please describe.**

Don't search WindowsApps folders (maybe if the related UWP app is also shown)

The top result is C:\Program Files\WindowsApps\Microsoft.SysinternalsSuite_2022.11.2.0_x64__8wekyb3d8bbwe\Tools\Procmon.exe where the second result is the UWP (?) shortcut for the same thing.

![image](https://user-images.githubusercontent.com/83080728/205804203-2330c98f-b3c5-4f1f-9809-f29d02892a66.png)

![image](https://user-images.githubusercontent.com/83080728/205804186-55350d18-b122-4f4b-a7af-2b7ed4d82abe.png)

**Describe the solution you'd like**

Allow a list of excluded folders, and exclude WindowsApps by default.

**Describe alternatives you've considered**

**Additional context**

**Comment by VictoriousRaptor** [comment]
The first result is possibly from registry. Try to disable the registry option in the plugin and see if it shows up.

**Comment by voltagex** [comment]
Yep, that seems to fix it
![image](https://user-images.githubusercontent.com/83080728/210919640-e74fc0f7-a9c2-4e9c-8ca8-ba0eef8428b1.png)
