### ISSUE TITLE
BUG: The Windows is freezing 

### ISSUE THREAD

**Issue by minawaheed9697** [Flow-Launcher/Flow.Launcher#1604]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

All I noticed that my Windows is keeping freezing.
After each freeze, the "Flow Launcher" is the only app that does not respond.
Also, when I end task it, the Windows works fine. 

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19044.2251

### Error Log

[2022-12-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10177287/2022-12-07.txt)

**Comment by taooceros** [comment]
This kinds of bug is very hard to reproduce and our log generally won't be able to log anything useful of it. Would you please check the event viewer and see whether flow is throwing any exception there when issue happening?
