### ISSUE TITLE
BUG: issue in Browser Bookmarks i use brave browser

### ISSUE THREAD

**Issue by logann99** [Flow-Launcher/Flow.Launcher#1619]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

Browser Bookmarks its not working for me in V1.9.5 and 1.9.4
i use brave browser
![206919079-276ac8d4-7478-4cfd-8d00-9ca345df29f6](https://user-images.githubusercontent.com/101401329/206919491-e8572674-111d-4eaf-99df-a7da916b6e55.png)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Brave is not in the default loading. You will need to configure yourself.

**Comment by onesounds** [comment]
![image](https://user-images.githubusercontent.com/6903107/206928058-9a5cbe37-4460-4b81-9aa6-97a2c18af237.png)
- The bookmark of the brave is located in this directory.
- After adding 1. close the setting window 2. reload the plug-in data by pressing F5 in search box.

**Comment by logann99** [comment]
thanx it works but  why its not like your app ? y know more than one browser
![image](https://user-images.githubusercontent.com/101401329/207145408-bfc7672a-36ec-4044-a8b1-76c5be74b93b.png)

**Comment by taooceros** [comment]
> thanx it works but why its not like your app ? y know more than one browser

He is in the latest prerelease, which we have made some change to allow customize which browser should be loaded (the current releases load all by default).

**Comment by logann99** [comment]
> > thanx it works but why its not like your app ? y know more than one browser
> 
> He is in the latest prerelease, which we have made some change to allow customize which browser should be loaded (the current releases load all by default).

can i download it ? if yes link please

**Comment by taooceros** [comment]
Sure https://github.com/Flow-Launcher/Flow.Launcher/discussions/956

**Comment by logann99** [comment]
> Sure #956

thnx <3
