### ISSUE TITLE
BUG: Cannot open files of which the path contains blanks (v1.10.0)

### ISSUE THREAD

**Issue by a224515a** [Flow-Launcher/Flow.Launcher#1632]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I have activated the embed Everything plugin in v1.10.0, and set Notepad++ as the default editor.
I could find every files I need, but the files cannot be open from within the FlowLauncher.
I've tested for several times.
I think this problem might be due to the blanks in the file pth.

This never happened in the pervious version using the external [plugin](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything).
Hope it coud be fixed soon.

Very thanks!

### To Reproduce

1. enable the embeded Everything plugin
2. sereach files
3. it prompt that file inexist if the filepath contains blanks

### Flow Launcher Version

v1.10.0

### Windows Build Number

 10.0.19045.2251

**Comment by a224515a** [comment]
@VictoriousRaptor. The file can be correctly opened with its associated program (e.g., `*.m` could be opened with Matlab).
But it can not be opened when I specified "Open With Editor: notepad++"

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor. The file can be correctly opened with its associated program (e.g., `*.m` could be opened with Matlab). But it can not be opened when I specified "Open With Editor: notepad++"

Thank you! We are fixing this issue.

**Comment by jjw24** [comment]
Please try the fix in pre-release https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.10.0.6345
