### ISSUE TITLE
Open folder in visual studio code

### ISSUE THREAD

**Issue by fihorvat** [Flow-Launcher/Flow.Launcher#1633]
**Is your feature request related to a problem? Please describe.**

Is it possible to show `open with code` command when I select some file or directory?

**Describe the solution you'd like**

When we select the file/folder and press right we get this list of options available. It would be great if we could add an option to open files/folders in visual studio code (if installed). 
![image](https://user-images.githubusercontent.com/14946119/207287368-7d37e428-751a-4fd0-92d6-a28d18e213ad.png)

It would be great if there would be `Open in Code` plugin that would be displayed like `Everything` in this image.

**Describe alternatives you've considered**

The alternative (and what I do now) is to use the `show context menu`  but it takes some time to load and is one step more to do.
![image](https://user-images.githubusercontent.com/14946119/207288224-865042f7-8080-4cd7-969d-89dca8a4c8e5.png)

**Comment by VictoriousRaptor** [comment]
you can set the editor path in plugin's setting.

**Comment by fihorvat** [comment]
@VictoriousRaptor could you please be so kind and tell me what am I doing wrong?
I tried to set vscode as the default editor for explorer but it doesn't work
![image](https://user-images.githubusercontent.com/14946119/207297766-46f22557-83f4-4aac-8285-195911e6c7b3.png)

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor could you please be so kind and tell me what am I doing wrong? I tried to set vscode as the default editor for explorer but it doesn't work ![image](https://user-images.githubusercontent.com/14946119/207297766-46f22557-83f4-4aac-8285-195911e6c7b3.png)

Sorry about that. Could you describe how it doesn't work? Is it poping up any error message?

**Comment by fihorvat** [comment]
When I press ➡ on `file` I get the option to open with code: 
![image](https://user-images.githubusercontent.com/14946119/207301959-b0d68b04-a550-4c64-af67-ff4de24e5a03.png)

When I press ➡ on `directory` (I want to open `directory` in vscode (project))
![image](https://user-images.githubusercontent.com/14946119/207302219-eef611fc-3e2e-4757-9e4f-35b62878117e.png)

Whatever command I chose it opens Windows explorer.

**Comment by VictoriousRaptor** [comment]
I see. Sorry but currently we don't support that feature. You can try the VS Code workspace plugin.

**Comment by z1nc0r3** [comment]
You can use **Plugin Runner** to open a folder in VS Code. In this case, I just type `r code` while focusing on the folder.

![image](https://user-images.githubusercontent.com/64279853/207527925-9ce84d98-dec9-4d22-8677-6ebee793d335.png)

**Comment by deefrawley** [comment]
Actually the way that plugin runner shortcut works is you navigate to the directory you want to open in File Explorer, then bring up Flow and type `r code`. It will automatically pick up the highlighted explorer path.

**Comment by shellwhale** [comment]
I managed to find a solution that I find okay-ish.

First I created a bat file called code-add-folder.bat

```
@echo off
REM This bat file takes all of its arguments and passes them to code

set arglist=
set argcount=0

REM Loop through all arguments and build a space-separated list of arguments
for %%a in (%*) do (
    set arglist=%arglist% "%%a"
    set /a argcount+=1
)

REM Call code with the argument list
code --add %arglist%
```

Then I set the Folder Editor Path in the Explorer plugin to that .bat file and now I can use it here.

![image](https://user-images.githubusercontent.com/36083584/224561611-a3a2af42-457e-427c-bd51-7d4ff655293d.png)
