### ISSUE TITLE
Add the ability to display the current language layout

### ISSUE THREAD

**Issue by fervulp** [Flow-Launcher/Flow.Launcher#1640]
**Describe**
Add the ability to display the current layout, as with time
![изображение](https://user-images.githubusercontent.com/77237424/207470436-dedfc5b3-10ac-4126-9e13-59ad3fa43c32.png)

**Solution**
I would like to see the following
![изображение](https://user-images.githubusercontent.com/77237424/207471012-fe00d099-3dac-4053-9704-5d92ef332a2b.png)

**Additional context**
Many people start typing right away without paying attention to the layout, I think this is not difficult. Even if you refuse this idea, could you show how it can be implemented by yourself by changing the code.

**Comment by jjw24** [comment]
@fervulp @onesounds since always start typing in English feature has been rolled out, is this display input in the search window still relevant?

**Comment by VictoriousRaptor** [comment]
> @fervulp @onesounds since always start typing in English feature has been rolled out, is this display input in the search window still relevant?

Kind of. imo always start typing in English is generally enough.

**Comment by onesounds** [comment]
> > @fervulp @onesounds since always start typing in English feature has been rolled out, is this display input in the search window still relevant?
> 
> Kind of. imo always start typing in English is generally enough.

yep I think it's enough. If fervulp has not other feedback, let's close the issue.
