### ISSUE TITLE
Switch SpotifyPremium Plugin to SpotifyPlugin

### ISSUE THREAD

**Issue by dennyamarojr** [Flow-Launcher/Flow.Launcher#1641]
**Is your feature request related to a problem? Please describe.**
Yes, my problem is related to a problem when you try to use the command of spotify in Flow Launcher. If you didn't have an premium account you're not allowed to use the plugin.

**Describe the solution you'd like**
The solution is simple, make the extension switch to SpotifyPlugin and not SpotifyPremium, so everyone could use this feature even if the spotify account is free. In the moment, only premium accounts are allowed to use the extension.

**Describe alternatives you've considered**
An alternative is try to built an plugin that allow the users to experience the same experience as SpotifyPremium plugin offers, but for the free users in Spotify.

**Additional context**
Sorry if I miss some information, or just type something wrong filling the feature request. It's my first time, opening a feature request.

![image](https://user-images.githubusercontent.com/36896116/207492677-b65946b8-88d3-4c57-835c-f942e156523a.png)

**Comment by dennyamarojr** [comment]
Hi @taooceros thanks for replying, I know a project that uses free APIs to get spotify songs that is Spotube. 
https://github.com/KRTirtho/spotube

**Comment by onesounds** [comment]
> Hi @taooceros thanks for replying, I know a project that uses free APIs to get spotify songs that is Spotube. [KRTirtho/spotube](https://github.com/KRTirtho/spotube)

I checked the project, but this project is more like using YouTube's api. 
(It looks for spotify's library information, but it's YouTube that gets the actual music data.)
and I think, it's hard to make it similar and we need to respect the policy part of Spotify.

**Comment by Rajbir98** [comment]
well this extension is also similar and its free https://addons.mozilla.org/en-US/firefox/addon/spotify-player/
I think you can check its source to get some solutions.

**Comment by Rajbir98** [comment]
Hey, offtopic but where you got this wallpaper it's pretty cool.

**Comment by Garulf** [comment]
> well this extension is also similar and its free https://addons.mozilla.org/en-US/firefox/addon/spotify-player/ I think you can check its source to get some solutions.

Looks like a plugin that interacts directly with the website itself. Not ideal for a plugin.

**Comment by dennyamarojr** [comment]
I find a spotify API, not sure if is the same used in this project
https://github.com/zackelia/spotifyapi
