### ISSUE TITLE
BUG: I cannot disable indexing of PATH (Program plugin)

### ISSUE THREAD

**Issue by patrik-martinko** [Flow-Launcher/Flow.Launcher#1659]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

After the latest update, the Program plugin started showing me results from the PATH environment variable (C:\Program Files\WindowsApps, ...). For example:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/12855743/207875795-40a8f2bb-95d6-4fdf-bf34-41ddb3764aa1.png">

I don't want to show these results (It worked in the previous version of Flow Launcher). I have my own list of links (.lnk files) that I want to show only. I've unchecked these checkboxes but the programs from PATH are still showing:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/12855743/207876710-3fc7a024-3466-48bc-821b-0ea0d54895aa.png">
<img width="477" alt="image" src="https://user-images.githubusercontent.com/12855743/207876875-5c6a935a-1971-49ba-908d-e8662fcf621f.png">

### Flow Launcher Version

v1.10.0

### Windows Build Number

10.0.22621.963

**Comment by VictoriousRaptor** [comment]
Hi, this result seems to be a uwp program, which will be indexed anyway. Currently we don't have setting to disable it.

**Comment by onesounds** [comment]
You can hide program from the context menu.
<img src="https://user-images.githubusercontent.com/6903107/207990440-7ebc9723-d23d-47fa-9181-da0d0c8dee71.png" width="300">

**Comment by patrik-martinko** [comment]
> Hi, this result seems to be a uwp program, which will be indexed anyway. Sorry but Currently we don't have an option to disable it.

Ok, I understand. I thought it was the PATH option because these items didn't display me before the update.

> You can hide program from the context menu.

I know, but it's hard to maintain so many items.

**Comment by onesounds** [comment]
Let me ask for confirmation, What you want is to hide all the uwp apps?
We(Team)'re talking about adding the option because you want you to hide all the uwp apps, 

I'm only saying it's not. I don't think anyone needs the option to hide all the uwp, and I don't think it needs to be provided even if there is someone who needs it. What's your opinion?

**Comment by patrik-martinko** [comment]
Yes. I don't use UWP apps at all and a lot of them cannot be uninstalled from Win. A lot of them interfere when I use Flow Launcher, but it's not a priority for me. I thought it was a bug with the PATH settings so I wanted to help with reporting.
