### ISSUE TITLE
Empty last query is not working (neither is select last query)

### ISSUE THREAD

**Issue by Ciantic** [Flow-Launcher/Flow.Launcher#166]
**Describe the bug/issue**
When I open FlowLauncher with hotkey <kbd>Win</kbd>+<kbd>N</kbd>, the launcher appears but it contains the last query.

This also happened to me in old Wox, as well as sometimes with your fork. But with Flow.Launcher it seems to happen all the time.

**To Reproduce**
1. <kbd>Win</kbd>+<kbd>N</kbd>
2. Type e.g. "g foo"
3. Hit enter
4. Notice Launcher starts a new browser window and disappears.
5. Hit <kbd>Win</kbd>+<kbd>N</kbd>
6. Notice that "g foo" is still there.

**Screenshots**

![image](https://user-images.githubusercontent.com/64731/95689341-ae6c1780-0c18-11eb-8bf0-ce049af71e98.png)

**Your System**
```
Windows build number: Version 10.0.19041.508
Flow Launcher version: 1.2.1 Portable mode
```

**Comment by Ciantic** [comment]
There is some race condition I bet, the problem seems to come and go. Now it works again as I restarted the program, but on last run it didn't work at all.

Does the "empty last query" or "select last query" expect that the window is already fully visible? Somehow the old query flashes in there, maybe sometimes it starts work incorrectly.

**Comment by Zeroto521** [comment]
I firstly used FLow and changed the default config just as your way. It didn't work the same as yours.

But reload the Flow or restart the Flow, it worked again.

I think Flow can't load the config instantly when you change.

**Comment by jjw24** [comment]
> There is some race condition I bet, the problem seems to come and go. Now it works again as I restarted the program, but on last run it didn't work at all.
> 
> Does the "empty last query" or "select last query" expect that the window is already fully visible? Somehow the old query flashes in there, maybe sometimes it starts to work incorrectly.
> 
> # Suggestion
> Clear or select the last query when the window closes or hides and _not_ when it shows up. This way it wouldn't flash there, and maybe it would work better.

Yeah currently it seems it clears the query when it shows up. makes sense to clear when it hides.

**Comment by jjw24** [comment]
> There is some race condition I bet, the problem seems to come and go. Now it works again as I restarted the program, but on last run it didn't work at all.

Strange I am not able to replicate with a fresh install. Are you still running to this problem with the new run?

**Comment by Ciantic** [comment]
Yeah, it doesn't work at the first start I have to close the app and restart to get the setting working.

However I think it would be better to run the command on window hide, because for instance with "Select last query" there is slight delay until it selects. I'm not sure can user actually hit keys during that time but it might be possible.

**Comment by taooceros** [comment]
I have taken a try, but seems making the visibility collapsed will stop the rendering, which means even we mark the action when hiding, the rendering process will still need to wait until it shows up……🤔

**Comment by Warden20** [comment]
I have the same bug with the last release

**Comment by taooceros** [comment]
> I have the same bug with the last release

Try restart Flow. It happens occasionally and we are not sure about the actual reason.
