### ISSUE TITLE
Enhance the 'Clock' feature to show seconds in the time.

### ISSUE THREAD

**Issue by z1nc0r3** [Flow-Launcher/Flow.Launcher#1678]
**Is your feature request related to a problem? Please describe.**

- There is no certain way to view seconds in Windows 11 clock.

**Describe the solution you'd like**

- Since there is a new feature called 'Clock' in the launcher, it'll be good to add an enhancement to show seconds also. Just add the hh:mm:ss format to the list.

**Describe alternatives you've considered**

- No, alternatives.

**Additional context**

- No additional context.

**Comment by onesounds** [comment]
We can add seconds, but there may be some little memory problems. (It won't be a big problem.) It's not a feature with many users, so I'll just add the format hh:mm:ss.
