### ISSUE TITLE
[Program Plugin] Some icons shrink while typing

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#1679]
I've noticed that some of the icons get smaller during the search. I can't explain it because it's just some specific programs (eg. FireDM, WizTree or Sandboxie).

FL version: 1.10.1 Portable

Watch the video:

https://user-images.githubusercontent.com/37414585/208287277-c84937d3-30de-4f17-8d27-1892dd5b2974.mp4

**Comment by Garulf** [comment]
I've noticed this when Flow tries to display icons from executables.

**Comment by VictoriousRaptor** [comment]
Seems like it's fixed by #1727 or #1709. @kubalav Could you please check if it still happens in the latest prerelease?

**Comment by kubalav** [comment]
@VictoriousRaptor The prerelease version works!
One question yet. Why some apps have square border like that?
![image](https://user-images.githubusercontent.com/37414585/210070221-2547bf30-ecf8-4f1e-8dea-901532089394.png)

and without border
![image](https://user-images.githubusercontent.com/37414585/210070340-11500dd4-c7a1-4460-8bf3-9ebde67ad7a7.png)

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor The prerelease version works! One question yet. Why some apps have square border like that? ![image](https://user-images.githubusercontent.com/37414585/210070221-2547bf30-ecf8-4f1e-8dea-901532089394.png)
> 
> and without border ![image](https://user-images.githubusercontent.com/37414585/210070340-11500dd4-c7a1-4460-8bf3-9ebde67ad7a7.png)

Sorry but I don't really know. Maybe because the icon size is too small?
