### ISSUE TITLE
Inform user when version update is not successful via windows notification

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#168]
Flow should inform the user when an error occurs or failure to update version manually or automatically via windows notification.

Currently error is written to log.

https://github.com/Flow-Launcher/Flow.Launcher/issues/149

**Comment by Zeroto521** [comment]
How about `window notification`?

**Comment by jjw24** [comment]
> How about `window notification`?

What do you mean? I was thinking of a notification from Flow , the one that pops up briefly.

**Comment by Zeroto521** [comment]
Like this.

![image](https://user-images.githubusercontent.com/25895405/95932561-c30a0480-0dfe-11eb-9c0a-830dcced00f2.png)

It is useful for me. It can group all notifications.

**Comment by jjw24** [comment]
> Like this.
> 
> ![image](https://user-images.githubusercontent.com/25895405/95932561-c30a0480-0dfe-11eb-9c0a-830dcced00f2.png)
> 
> It is useful for me. It can group all notifications.

Is this from the windows 10 sidebar notification area?

**Comment by Zeroto521** [comment]
Yes. You can see it.

![image](https://user-images.githubusercontent.com/25895405/95933135-4bd57000-0e00-11eb-8787-8ea3d02ec42a.png)

**Comment by Zeroto521** [comment]
Yes. You can see it.

![image](https://user-images.githubusercontent.com/25895405/95933135-4bd57000-0e00-11eb-8787-8ea3d02ec42a.png)

Unless you start up the `focus assist`. But notifications are still can show on here.

![image](https://user-images.githubusercontent.com/25895405/95933243-acfd4380-0e00-11eb-8de6-3b3c6dc57d70.png)

**Comment by jjw24** [comment]
Yeah ok. We might have to do this in two prs. I want to roll this out relatively quicker so I will just do the usual pop up notification, the second pr could add this new message toast in for all notifications from Flow, which is a bigger change, bearing in mind also of win 7, 8 support as well.

**Comment by Zeroto521** [comment]
Use window API to do this, notification will have a bubble at the taskbar in win7, 8 as I remember.
