### ISSUE TITLE
How to exclude files in everything + Some folders are not searched by Everything engine in Explorer plugin

### ISSUE THREAD

**Issue by minawaheed9697** [Flow-Launcher/Flow.Launcher#1686]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

After the last update, it's really greater than before in search.
But, there are some folders are not searched except searched in Everything app. 
All the search settings are Everything index.
Those folders are not excluded. 

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.10.1

### Windows Build Number

10.0.22000.1335

### Error Log

[2022-12-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10254466/2022-12-18.txt)

**Comment by deefrawley** [comment]
What folders aren't searched and are they excluded in Windows Index search?

**Comment by minawaheed9697** [comment]
> What folders aren't searched and are they excluded in Windows Index search?

A folder called (Data) and another (Media).
No, they are not excluded in the index and I use (Everything) index not the windows and also, it's not excluded in both of them.

**Comment by kubalav** [comment]
Have you set Everything as Index Search Engine in Explorer Plugin settings?

**Comment by minawaheed9697** [comment]
> Have you set Everything as Index Search Engine in Explorer Plugin settings?

Like that?
![image](https://user-images.githubusercontent.com/73688266/208491244-af724c35-f66d-4914-9849-8742d6b969f3.png)

**Comment by minawaheed9697** [comment]
> Yes, exactly so.

So, what's the problem??

**Comment by deefrawley** [comment]
Your "Everything Settings" doesn't look like this does it?

![image](https://user-images.githubusercontent.com/18594055/208569666-f87f5425-3650-4dae-bfe7-9aaa3e5eeb0e.png)

**Comment by minawaheed9697** [comment]
> Your "Everything Settings" doesn't look like this does it?
> 
No, there is no this warning message. 
It's working on almost files and folders except those. And even those are searches in Everything app

**Comment by kubalav** [comment]
Go to **Everything** and **Force Rebuild** index manually.

**Comment by minawaheed9697** [comment]
> Go to **Everything** and **Force Rebuild** index manually.

I made it twice. 
It's already working on Everything app. The issue in Flow launcher

**Comment by kubalav** [comment]
> > Go to **Everything** and **Force Rebuild** index manually.
> 
> I made it twice. It's already working on Everything app. The issue in Flow launcher

I can't reproduce this issue. Maybe @jjw24 would be help.

**Comment by minawaheed9697** [comment]
> I can't reproduce this issue. Maybe @jjw24 would be help.

I think it's something related to some folders or files. I don't know.

**Comment by deefrawley** [comment]
Perhaps send us a screenshot of every setting tab for the plugin and perhaps show us a search working in the Everything UI and then failing in Flow?

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/208768382-029a3925-dd4f-4cc7-b56d-e4f9e314f45d.png)
Have you disabled any path for index search?

**Comment by jjw24** [comment]
> A folder called (Data) and another (Media). They are in (D) local drive, not the system one.

@minawaheed9697 'Data' and 'Media' sound very generic names, what do you get when you actually search for them, do you get other 'Data' or 'Media' folders? Please show us a screenshot (blur out any sensitive results)

Are you getting results from folders in the same parent folder as 'Media' and 'Data'?

As mentioned above also check if you have excluded any path in that tab.

**Comment by minawaheed9697** [comment]
@deefrawley @taooceros @jjw24 
This link is containing all the screenshots you want https://imgur.com/a/gl90VpK

> Are you getting results from folders in the same parent folder as 'Media' and 'Data'?

Yes, except for a folder called (Videos), I think it's related to the common names as you said.

**Comment by deefrawley** [comment]
Seems an odd one. If you type `D:\M`... does the `Media` folder show up so you can tab autocomplete it? I also have a `Media` folder under my C: Windows user folder but when I search just `media` (using Everything) I get a heap of other hits instead even if I scroll for many pages.
Perhaps create a unique filename in that folder and see if Flow can find it?

**Comment by minawaheed9697** [comment]
> If you type `D:\M`... does the `Media` folder show up so you can tab autocomplete it?

That's what happen as Media is a subfolder of Data.
![image](https://user-images.githubusercontent.com/73688266/209121918-da5c7615-720f-40ab-826c-9240b0ad429f.png)





> Perhaps create a unique filename in that folder and see if Flow can find it?

There is a subfolder in Data and it's searched normally.

**Comment by deefrawley** [comment]
Thanks for all the screenshots and assistance. Might need to hand over to the core devs to troubleshoot further.

**Comment by minawaheed9697** [comment]
> Thanks for all the screenshots and assistance. Might need to hand over to the core devs to troubleshoot further.

Thank you very much for help.
Okay, take your time. Hoping it'll be fixedd soon.

**Comment by jjw24** [comment]
@minawaheed9697 I see you have a lot of results named 'data' from Everything app screenshot. I wonder if Explorer's results have hit a limit (assuming we have a total results limit?) and the desired 'Data' result is buried.

I dont use Everything to search, do you guys know if there is a way to exclude locations in the Everything app? If so, can you exclude all locations but the desired 'Data' location. This will determine if the result is buried.

**Comment by kubalav** [comment]
> @minawaheed9697 I see you have a lot of results named 'data' from Everything app screenshot. I wonder if Explorer's results have hit a limit (assuming we have a total results limit?) and the desired 'Data' result is buried.
> 
> I dont use Everything to search, do you guys know if there is a way to exclude locations in the Everything app? If so, can you exclude all locations but the desired 'Data' location. This will determine if the result is buried.

I can find Data folder if I exclude repeated locations. I enter this command in FL: 

`data !_meta`

**Comment by minawaheed9697** [comment]
> I can find Data folder if I exclude repeated locations. I enter this command in FL:
> 
> `data !_meta`

Please, I don't know where to put this command. Can you explain further?

**Comment by kubalav** [comment]
> > I can find Data folder if I exclude repeated locations. I enter this command in FL:
> > `data !_meta`
> 
> @kubalav Please, I don't know where to put this command. Can you explain further?

Simply to search box in FL. **Data** is search term and exclamation mark exclude term **_meta**.

**Comment by minawaheed9697** [comment]
> Simply to search box in FL. **Data** is search term and exclamation mark exclude term **_meta**.

It's still searching for metadata.

**Comment by kubalav** [comment]
If you want to exclude .metadata type **!.metadata**.

**Comment by minawaheed9697** [comment]
> If you want to exclude .metadata type **!.metadata**.

@kubalav Thanks, I Used ! to exclude those words (metadata, appdata and amd) 😂 to be able to search the Data folder I want.
So, it's buried as you said @jjw24 
![image](https://user-images.githubusercontent.com/73688266/209461022-07b1d39d-0f04-4cbb-b8b2-f427f25f96e0.png)

**Comment by minawaheed9697** [comment]
Is there anything else I can do??

**Comment by deefrawley** [comment]
Under the Explorer plugin - Quick Access Links tab and add that `data` folder. It should then be returned in the first few results. From there you can right click and choose "Set as topmost for this query" and it should be number one for that search term.

**Comment by jjw24** [comment]
@minawaheed9697 yep you can do what deefrawley mentioned, add that folder to quick access via context menu and then set your quick access hotkey. You can then use the quick access hotkey to quickly list that folder and any additional folders you added.

**Comment by jjw24** [comment]
Data is such a common name, I wonder if there is a better solution to find in this sort of scenario?

**Comment by minawaheed9697** [comment]
@deefrawley @jjw24 
Thank you so much for help. 
Is there any way to add these words to exclusion?? Not the folder I mean a word like "metadata"

**Comment by jjw24** [comment]
>Is there any way to add these words to exclusion?? Not the folder I mean a word like "metadata"

We dont have anything like that atm, sounds like an idea to implement to resolve the issue with common names. Thoughts @Flow-Launcher/team ?

**Comment by minawaheed9697** [comment]
> We dont have anything like that atm. 

Does it exist in Everything app itself? I think if it's in it, they can be excluded

**Comment by jjw24** [comment]
I am not sure myself, I havent used Everything much, perhaps check the app settings.

**Comment by kubalav** [comment]
> > We dont have anything like that atm.
> 
> Does it exist in Everything app itself? I think if it's in it, they can be excluded

Try to exclude in Everything app: **Tools – Options… – Indexes – Exclude**

**Comment by minawaheed9697** [comment]
> Try to exclude in Everything app: **Tools – Options… – Indexes – Exclude**

It excluded only (metadata), I can't exclude (amd), although they are with the same code form.

**Comment by kubalav** [comment]
**amd64\*data\*** can exclude amd folders.

**Comment by minawaheed9697** [comment]
> **amd64*data*** can exclude amd folders.

It works, thank you so much.
For amd64, amd64*, but for metadata, *metadata. Why is the location of (*) different?

**Comment by kubalav** [comment]
> It works, thank you so much. For amd64, amd64*, but for metadata, *metadata. Why is the location of * different?

Folders named amd starts with amd and you need to exclude all folders that starts with amd following any characters. \*(asterisk) represent any character(s). Regarding the folders called metadata, these folders start with _(underscore). If you want exclude only folders start with _metadata you can use _metadata\*. If you want exclude folders named (any characters)metadata(any characters) you can use \*metadata\*.

**Comment by minawaheed9697** [comment]
Okay, I got it.
Really thank you so much for your help.
