### ISSUE TITLE
[Explorer Plugin] Copy File from explorer plugin

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#169]
Sometimes when we search for files, we want to just copy the file and send it to others. Is it possible to add an option to copy the file when searching them with explorer plugin.

This links to [Wox #2691](https://github.com/Wox-launcher/Wox/issues/2691)

**Comment by jjw24** [comment]
> Sometimes when we search for files, we want to just copy the file and send it to others. Is it possible to add an option to copy the file when searching them with explorer plugin.
> 
> This links to [Wox #2691](https://github.com/Wox-launcher/Wox/issues/2691)

Hey how's it going. This option should already exist via shift + enter on the file:
![image](https://user-images.githubusercontent.com/26427004/95836917-ba2c1b00-0d8b-11eb-836e-8575a5eb7682.png)

Is this what you are after?

**Comment by taooceros** [comment]
Oh sorry, that option is kindly invisible without rolling down. Thank you for telling me about it.

**Comment by jjw24** [comment]
no problem :)
