### ISSUE TITLE
Crashes when typing with clipboard empty through a Remote Desktop session

### ISSUE THREAD

**Issue by ghostflyby** [Flow-Launcher/Flow.Launcher#1697]
I'm using Microsoft Remote Desktop on Mac

> Flow Launcher version: 1.10.1
> OS Version: Microsoft Windows NT 10.0.22621.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: 
> Date: 12/21/2022 16:46:54
> Exception:
> System.Runtime.InteropServices.COMException (0x800401D3): 剪贴板上的数据无效 (0x800401D3 (CLIPBRD_E_BAD_DATA))
>    at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
>    at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
>    at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
>    at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
>    at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
>    at System.Windows.DataObject.GetData(String format, Boolean autoConvert)
>    at System.Windows.Clipboard.GetDataInternal(String format)
>    at System.Windows.Clipboard.GetText(TextDataFormat format)
>    at System.Windows.Clipboard.GetText()
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass121_0.<ConstructQuery>b__0() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 767
>    at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
>    at System.Windows.Threading.Dispatcher.Invoke(Action callback)
>    at Flow.Launcher.ViewModel.MainViewModel.ConstructQuery(String queryText, IEnumerable`1 customShortcuts, IEnumerable`1 builtInShortcuts) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 763
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Here is the log file.
[2022-12-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10276121/2022-12-21.txt)

**Comment by VictoriousRaptor** [comment]
related #1629. Could you please try to copy some text  and then type, see if it makes a difference?

**Comment by ghostflyby** [comment]
There's **Nothing wrong** with text/file copied
