### ISSUE TITLE
Favourite plugin port requests

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#170]
Visit [here](https://flow-launcher.github.io/docs/#/port-plugins) on how to port .Net or Python plugins 

Please only request Wox plugins you were using regularly.

Currently ported plugins, use `pm install` to install them:

- WoxDictionary https://github.com/jjw24/WoxDictionary/releases/latest

- Google Search Plus https://github.com/jjw24/Wox.Plugin.GoogleSearch/releases/latest

- SpotifyPremium https://github.com/jjw24/Wox.Plugin.SpotifyPremium/releases/latest

- Runner https://github.com/jjw24/Wox.Plugin.Runner/releases/latest

- Clipboard Manager https://github.com/Xenolphthalein/Flow.Launcher.Plugin.ClipboardHistory

- WindowWalker https://github.com/taooceros/Microsoft.Plugin.WindowWalker

- ipadr https://github.com/taooceros/Flow.Plugin.IPAddress

- UrlEncode https://github.com/taooceros/Flow.Plugin.UrlEncode

- Putty https://github.com/jjw24/Flow.Launcher.Plugin.Putty

- Todoist
https://github.com/DanielBV/Wox.Plugin.Todoist

- isPrime
https://github.com/lvonkacsoh/Flow.Launcher.Plugin.IsPrime

**Comment by jjw24** [comment]
From https://github.com/Flow-Launcher/Flow.Launcher/issues/95

![image](https://user-images.githubusercontent.com/26427004/95836097-c1065e00-0d8a-11eb-870f-c590b5330101.png)

-  Discogs **http://www.wox.one/plugin/90** 
-  SwiftTweet http://www.wox.one/plugin/63
-   Todoist http://www.wox.one/plugin/292
- Timer https://github.com/creativitRy/WoxTimer
- Graphical Timer https://github.com/JaroslawPokropinski/Wox.Plugin.GraphicalTimer

**Comment by jjw24** [comment]
Hey @jeremymeyers, unfortunately the repo Wox.Plugin.Discogs is no longer available. I wont be able to port it.

**Comment by Xenolphthalein** [comment]
Hey i would love to see the Clipboard History Tool from Wox in FlowLauncher.
https://github.com/Wox-launcher/Wox.Plugin.ClipboardManager
That always was my most used tool from Wox / Alfred / Albert.

**Comment by pc223** [comment]
I use this plugin a lot :smile:, crucial to my workflow (a lot of windows switching), 

https://github.com/Wox-launcher/Wox.Plugin.Switcheroo

This's a plugin base on [this](https://github.com/kvakulo/Switcheroo)

Another similar one call [WindowWalker](https://github.com/betsegaw/windowwalker), heard them ported to PowerToys Run, but I never tried it.

**Comment by Xenolphthalein** [comment]
I created a port of the ClipboardManager Plugin. You can find it here:
https://github.com/Xenolphthalein/Flow.Launcher.Plugin.ClipboardHistory

**Comment by Francesco270** [comment]
Here are my favourites, sorted from most used to less:
- Translating plugins: Google Translate https://github.com/lances101/Wox.Plugin.GoogleTranslate, Gtranslate https://github.com/CN-DXTZ/Wox.Plugin.Gtranslate, Yandex Translate http://www.wox.one/plugin/173
- ToggleCase https://github.com/sobujbd/Wox.Plugin.ToggleCase
- Recall https://github.com/ZzzGin/wox-recall
- Todos https://github.com/alannotnerd/Wox.Plugin.Todos
- SimpleClock https://github.com/magicdmer/Wox.Plugin.SimpleClock
- Tinyurl https://github.com/Failip420/Wox-Tinyurl or Bitly http://www.wox.one/plugin/160
- YouTubeQuery https://github.com/TheDoctor0/YouTubeQuery
- Timer https://github.com/creativitRy/WoxTimer
- FancyEmoji https://github.com/821C3/Wox.Plugin.FancyEmoji
- Faver https://github.com/shawlq/Wox.Plugin.Faver
- Giphy https://github.com/skttl/Wox.Plugin.Giphy
- CurrencyPlus https://github.com/imsh/wox-currency-converter
- Forecast https://github.com/RomanKornev/Forecast
- Weather.Open http://www.wox.one/plugin/118
- Thesaurus https://github.com/jonathanvisser/wox-thesaurus

**Comment by jjw24** [comment]
Can YouTubeQuery https://github.com/TheDoctor0/YouTubeQuery be replaced with the youtube search in WebSearch plugin (have not looked at what that plugin does)?

**Comment by Francesco270** [comment]
> Can YouTubeQuery https://github.com/TheDoctor0/YouTubeQuery be replaced with the youtube search in WebSearch plugin (have not looked at what that plugin does)?

YouTubeQuery actually shows the video results, so title + image preview which is quite handy.

**Comment by taooceros** [comment]
https://github.com/taooceros/Microsoft.Plugin.WindowWalker
Port for WindowsWalker

**Comment by Francesco270** [comment]
Another plugin I love is Ueli's Shortcut Plugin
https://github.com/oliverschwendener/ueli
![image](https://user-images.githubusercontent.com/57621306/100607343-1da5e400-330b-11eb-8590-eadf357bad93.png)

**Comment by bartlibert** [comment]
My favourites:
[Wox.Plugin.Bang](https://github.com/JohnTheGr8/Wox.Plugin.Bang): search with duckduckgo bangs directly
[wox-mpv-plugin](https://github.com/stax76/wox-mpv-plugin): control mpv
[Wox.Plugin.Media](https://github.com/JulianGi/Wox.Plugin.Media): play, pause, etc...
[wox.plugin.volume](https://github.com/rohm1/wox.plugin.volume): control audio volume

**Comment by Francesco270** [comment]
> > > Can YouTubeQuery https://github.com/TheDoctor0/YouTubeQuery be replaced with the youtube search in WebSearch plugin (have not looked at what that plugin does)?
> > 
> > 
> > YouTubeQuery actually shows the video results, so title + image preview which is quite handy.
> 
> Might investigate whether we can merge into WebSearch plugin because it's quite useful to search like this

Yeah I agree, but even a separate Plugin would work just fine.

**Comment by jjw24** [comment]
> I use this plugin a lot 😄, crucial to my workflow (a lot of windows switching),
> 
> https://github.com/Wox-launcher/Wox.Plugin.Switcheroo
> 
> This's a plugin base on [this](https://github.com/kvakulo/Switcheroo) and [this](https://github.com/mwinapi/mwinapi)
> 
> Another similar one call [WindowWalker](https://github.com/betsegaw/windowwalker), heard them ported to PowerToys Run, but I never tried it.
> 
> Note: this plugin currently have a 1-2 hundred ms delay when query, potentially because of icon getter.

Now that Window Walker is available for Flow, do you still need Switcheroo?

**Comment by pc223** [comment]
> > I use this plugin a lot 😄, crucial to my workflow (a lot of windows switching),
> > https://github.com/Wox-launcher/Wox.Plugin.Switcheroo
> > This's a plugin base on [this](https://github.com/kvakulo/Switcheroo) and [this](https://github.com/mwinapi/mwinapi)
> > Another similar one call [WindowWalker](https://github.com/betsegaw/windowwalker), heard them ported to PowerToys Run, but I never tried it.
> > Note: this plugin currently have a 1-2 hundred ms delay when query, potentially because of icon getter.
> 
> @pc223 Now that Window Walker is available for Flow, do you still need Switcheroo?

I'm running the new plugin right now, it works, no bugs or anything, just that Im still have to getting by with my current setup for now, because of a bit of customized code for Switcheroo plugin and not yet port to the new Walker plugin (maybe in the lunar new year holiday :smile:). 

Ultimately, it depends on you guys, to do what good for Flow 😄 personally, I believe windows switching is a really useful feauture that many users need.

**Comment by jjw24** [comment]
Ok cool. Yeah feel free to put in an issue to window walker plugin if you want those features from switcheroo that are not there. Or if u code c# just chuck a pr in

**Comment by katchy3132** [comment]
I use the Putty plugin constantly !

https://github.com/kosz78/wox.plugin.putty
http://www.wox.one/plugin/13

**Comment by harrynull** [comment]
Thank you for porting my Dictionary plugin!

**Comment by jjw24** [comment]
@harrynull would you be keen to create an empty Flow.Launcher.Dictionary (or any name you like) and I can push to the port to it, because it is currently under me as a fork and not discoverable via github search. It would be nice if people can also search for it.

**Comment by harrynull** [comment]
@jjw24 Definitely! I've created an empty repo and granted you write access to it if that is what you mean :)

**Comment by jjw24** [comment]
Done, future downloads from Flow will be from that repo 👍

**Comment by zany130** [comment]
so a couple of wox plugins I was able to get to work by just copy pasting them from the wox plugins folder into flow plugin folder.
these are:

define
http://www.wox.one/plugin/94

FancyEmoji 
https://github.com/821C3/Wox.Plugin.FancyEmoji

isPrime 
https://github.com/lvonkacsoh/wox-plugin-isPrime

Synonymer 
https://github.com/Plasma-Paris/Wox.Plugins/tree/master/Wox.Plugin.Synonym

Translator 
http://www.wox.one/plugin/280

wox.plugin.DiskSpace 
https://github.com/roose/Wox.Plugin.DiskSpace

wox-Dash-Velocity
https://github.com/etiago/wox-dash-velocity


These 6 however did not work

Wox.Plugin.Timezone
https://github.com/arkraft/Wox.Plugin.Timezone

Wox.Plugin.UrlEncode
https://github.com/cxfksword/Wox.Plugin.UrlEncode

Wox.Plugin.IPAddress
https://github.com/ishu3101/Wox.Plugin.IPAddress

Base64 Encode/Decode
http://www.wox.one/plugin/150

Wox.Plugin.ProcessKiller
https://github.com/cxfksword/Wox.Plugin.ProcessKiller

Wox.Plugins.HexRgb
https://github.com/vladimirantos/Wox.Plugins.HexRgb

**Comment by taooceros** [comment]
@zany130 I port UrlEncode and IPAddress, and they will be in the manifest soon.

**Comment by jjw24** [comment]
@katchy3132 Putty has been ported

**Comment by 7yang7** [comment]
Hello. I really need a translator, one of these or another:
http://www.wox.one/plugin/173
http://www.wox.one/plugin/60

**Comment by taooceros** [comment]
> Hello. I really need a translator, one of these or another:
> http://www.wox.one/plugin/173
> http://www.wox.one/plugin/60

Both of them don't share the source code, so I guess it maybe hard to port them to flow.... 😂

**Comment by 7yang7** [comment]
> > Hello. I really need a translator, one of these or another:
> > http://www.wox.one/plugin/173
> > http://www.wox.one/plugin/60
> 
> ~Both of them don't share the source code, so I guess it maybe hard to port them to flow.... 😂~
> Oh I found the sourcecode for google translation, will take a look soon.
> 
> Which language do you need for translation?


Russian translation needed

**Comment by taooceros** [comment]
> > > Hello. I really need a translator, one of these or another:
> > > http://www.wox.one/plugin/173
> > > http://www.wox.one/plugin/60
> > 
> > 
> > ~Both of them don't share the source code, so I guess it maybe hard to port them to flow.... 😂~
> > Oh I found the sourcecode for google translation, will take a look soon.
> > Which language do you need for translation?
> 
> Russian translation needed

I am not able to port the Google Translate plugin because of the change of googel api. However, I do create a plugin based on LibreTranslation (it seems not as good as Google Translation for Chinese, but I am not sure about russian. However, thank them so much for providing the free api).  You can take a try on it.

**Comment by 7yang7** [comment]
> > > > Hello. I really need a translator, one of these or another:
> > > > http://www.wox.one/plugin/173
> > > > http://www.wox.one/plugin/60
> > > 
> > > 
> > > ~Both of them don't share the source code, so I guess it maybe hard to port them to flow.... 😂~
> > > Oh I found the sourcecode for google translation, will take a look soon.
> > > Which language do you need for translation?
> > 
> > 
> > Russian translation needed
> 
> @7yang7 I am not able to port the Google Translate plugin because of the change of googel api. However, I do create a plugin based on LibreTranslation (its translation seems not as good as Google Translation for Chinese, but I am not sure about Russian). However, thank them so much for providing the free api). You can take a try on it.
> 
> https://github.com/taooceros/Flow.LibreTranslate

Thanks for the plugin! Unfortunately, some words are not translated into Russian :( . But this is better than nothing.

**Comment by taooceros** [comment]
> Thanks for the plugin! Unfortunately, some words are not translated into Russian :( . But this is better than nothing.

Yeah that's happening in Chinese translation as well. Hope they will get through that issue soon. 🙂

**Comment by jjw24** [comment]
We now have a document on how to port .Net plugins, if you are a .net dev interested in bringing some plugins across to Flow:
https://flow-launcher.github.io/docs/#/port-plugins

Updates to make it more clearer is welcome too

**Comment by Warden20** [comment]
FancyEmoji
https://github.com/821C3/Wox.Plugin.FancyEmoji

**Comment by jeremymeyers** [comment]
If someone could convert https://github.com/DanielBV/Wox.Plugin.Todoist that would be fabulous.

**Comment by jjw24** [comment]
I am porting Todoist :)

**Comment by jjw24** [comment]
Todoist plugin is ported over

**Comment by jeremymeyers** [comment]
@jjw24 opened an issue over there

**Comment by jeremymeyers** [comment]
Also noticed this is a thing, maybe the list of plugins should be here too/instead/linked to from here? https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest

**Comment by jjw24** [comment]
> Also noticed this is a thing, maybe the list of plugins should be here too/instead/linked to from here? https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest

sorry not sure what you mean. This issue is going to be temporary, once the plugins here have been ported I plan to close this. The purpose of this issue is to gather popular/regularly used Wox plugins from users as a lot of Wox plugins are out of date and not maintained, so not planning to port over all of them.

**Comment by jjw24** [comment]
@Francesco270 I will fork yours so the original name of the project is kept

**Comment by Francesco270** [comment]
> @Francesco270 porting Todos plugin, do you know the difference between alannotnerd's and the original from caoyue?

I don't remember it unfortunately.

**Comment by jjw24** [comment]
@Francesco270 the Wox.Plugin.Todos port is done, should be available soon.

Very nice project

**Comment by lvonkacsoh** [comment]
Hey, I recently discovered this and was surprised that my IsPrime wox plugin got listed. Didn't even know someone but me would use it. Huh.
Your plugin site lists it as working but I can't install it via the `pm install` command. From your plugin manifest I'm not quiet sure what I can do port it properly. Is it only making a pr with an updated `plugin.json` file? Since the code is written in python and uses the `wox` package I assume it wouldn't work out of the box.
Sorry for asking via this thread - your documentation left me kind of insecure about how to help and it seemed to be an easy way 😅

**Comment by jjw24** [comment]
@lvonkacsoh no problem at all. Yep please add to it to Flow's plugin manifest to share it with the community. 

I think it's listed here as to port, and in the doc site as working for Flow, but we havent added in to the plugins manifest. The documentation for porting plugins is for ones written in .net, i havent got around to writing for python. 

I think the best way to go about it is to follow one of the python plugins here:
https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/tree/main
it's something along the lines of updating json file->change wox package to flowlauncher-> fix any obsolete methods

and then once you have it published, just create a pr for the plugins manifest here:
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest

Also if you can please add a documentation for how to port Python plugins.

**Comment by lvonkacsoh** [comment]
@jjw24 Thanks for the reply and plugin reference - it was very helpful!
I ported the plugin and created a PR. Actually my first time doing that so I hope that I didn't fuck up haha.
Added a small part about the porting at the bottom of the plugins readme file.

**Comment by jjw24** [comment]
@zany130, @lvonkacsoh's isPrime plugin has been ported to Flow

**Comment by Ma-ve** [comment]
I'd love to have https://github.com/821C3/Wox.Plugin.FancyEmoji ported over. I tried it myself, got it running, but couldn't get the set-to-clipboard working in Python. :<

**Comment by taooceros** [comment]
> I'd love to have https://github.com/821C3/Wox.Plugin.FancyEmoji ported over. I tried it myself, got it running, but couldn't get the set-to-clipboard working in Python. :<

There's some bug between the second time transmission between flow and python plugin. Sorry for the bug. The late dev branch has fixed it. You can take a try. https://ci.appveyor.com/api/buildjobs/txc943l7v5j1kmpt/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe

@jjw24 Should we release a hot fix for that? That has broke some python plugin functionality.

**Comment by jjw24** [comment]
> @jjw24 Should we release a hot fix for that? That has broke some python plugin functionality.

we are getting close to 1.8.0, let's wait :)
