### ISSUE TITLE
Enable regex when querying Everything

### ISSUE THREAD

**Issue by thunderousleader10** [Flow-Launcher/Flow.Launcher#1717]
With the main Everything app it is possible to search using regex. Would it be possible to enable this functionality within the FlowLauncher plugin?

**Comment by kubalav** [comment]
> With the main Everything app it is possible to search using regex. Would it be possible to enable this functionality within the FlowLauncher plugin?

You can use regular expressions. Only activate regular expression with "**regex:**", e.g.:

`regex:^(\d{2,2})\s-.+\.mp3`
