### ISSUE TITLE
[ Plugin: Windows Settings ] Some search results not launching.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Flow-Launcher/Flow.Launcher#1718]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Some search results are not launching.

### To Reproduce

1. Search for `Create and format`
2. press enter to launch the result
3. Nothing happens

### Screenshots

![image](https://user-images.githubusercontent.com/75798544/209471058-dfc92f4d-8f85-4a1a-bfdc-c439b385940d.png)

### Flow Launcher Version

v1.10.1

### Windows Build Number

10.0.22621.963

### Error Log

<details>

```shell

19:39:40.3675+05:30 - ERROR - Flow.Launcher.Plugin.WindowsSettings.Helper.ResultHelper.DoOpenSettingsAction - can't open settings
EXCEPTION OCCURS: System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'C:\Windows\system32\mmc.exe' with working directory 'C:\Windows\system32'. The requested operation requires elevation.
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at bool System.Diagnostics.Process.Start() x 2
   at bool Flow.Launcher.Plugin.WindowsSettings.Helper.ResultHelper.DoOpenSettingsAction(WindowsSetting entry) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs:line 201


```
</details>

**Comment by z1nc0r3** [comment]
It seems like the operation needs administrator privilege to run.

**Comment by PhoenixCODE2322** [comment]
> It seems like the operation needs administrator privilege to run.

yes , i read the log , is there no other way ? . 
I looked at power toys search and ` create and format disk` does not exist there
