### ISSUE TITLE
PROPOSAL: Include "Everything" in Key: plugin_explorer_plugin_description

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1720]
I understand that the description of the Explorer plugin should be modified to include the option of Everything. 

**Key: plugin_explorer_plugin_description**
"Search and manage files and folders. Explorer utilises Windows and **Everything** Index Search" (or equivalent)

![221223 FL 1 10 1 6489_Propuesta_Incluir Everything en la descripción del complemento Explorador](https://user-images.githubusercontent.com/102802425/209546152-454c42fa-9dc7-4210-bcd2-d588c2ad7dca.png)

**Comment by jjw24** [comment]
Good pick up as always @dracp 👍
