### ISSUE TITLE
BUG: Flowlauncher loses focus when using Ditto

### ISSUE THREAD

**Issue by RalfRoemling** [Flow-Launcher/Flow.Launcher#1729]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I'm using Ditto, a systemwide clipboard history which is activated via shortcut e. g. Strg-= (https://github.com/sabrogden/Ditto)

When opening FL and using the shortcut for Ditto 
- FL prompt closes 
- Ditto gets activated
- I'm unable to paste the items found in Ditto into FL

### To Reproduce

see above

### Flow Launcher Version

v1.10.1

### Windows Build Number

10.0.19043.1288

**Comment by z1nc0r3** [comment]
When the shortcut key is pressed **Ditto** runs as a separate process (**Ditto.exe**). So the user focus will transfer to the Ditto window. The FL prompt will hide if the FL sets to **hide when the focus is lost**.

Turning on the `Hide Flow Launcher when focus is lost` setting will fix the issue. But not recommended.

_Or else you can use the default Windows clipboard service which is also good._

**Comment by jjw24** [comment]
Hey how's it going?

When flow is hidden there is no window kept, that's probably why Ditto is unable to find flow to automatically paste into, hence the suggestion by z1nc0r3 works as when set to not hide the window is kept in the background. 

Does Ditto have a way to just copy the item and you can then paste into flow normally?

There is also a clipboard history plugin, not as powerful as Ditto but does allow you to access the copied items currently in memory.

**Comment by SpyderZT** [comment]
You can simply double click the item you want to paste into FL prior to launching FL. At that point it is loaded into the default paste cache and can be pasted to Flow without needing to launch Ditto.

So instead of **Alt+Space -> "Ditto Keys" -> Click to Paste** it's **"Ditto Keys" -> Click to Paste -> Alt+Space -> Paste**.

**Comment by RalfRoemling** [comment]
Hi Everybody, 
sorry for not answering in a timely manner and thx a lot for your explanations and suggestions. 

@z1nc0r3 and @SpyderZT describe my actual workflow and what I understood from the process explanation that's the best way to go when using Ditto.
