### ISSUE TITLE
Explorer Plugin - Change Default Editor

### ISSUE THREAD

**Issue by robertoleonardo** [Flow-Launcher/Flow.Launcher#173]
Hi - is there a setting (within flow or by editing the appropriate file extensions/types in the registry) to change the default text editor using the explorer plugin?  I would like to be able to right click on, for example, a txt file when i've found it within flow and have the option to open with my preferred text editor instead of the default option to open with notepad.

Thanks for all your work on flow?

**Comment by jjw24** [comment]
Hey how's it going. It's not built in yet so it always open up in Notepad. It is something good to build in. I will change this to feature request.
