### ISSUE TITLE
BUG: Malicious file accusation

### ISSUE THREAD

**Issue by MasterK79** [Flow-Launcher/Flow.Launcher#1730]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem
I was having a problem with Avast, it was accusing the app of having the "IDP.Generic" malware, I completely uninstalled and installed it again 2 times, and after that, avast was still showing this malware. So, I uploaded the file "Flow-Launcher-Setup.exe" to Virustotal and it finds 2 malicious files. So, I like the app but just don't know what I could do, I will be grateful if this problem can be solved.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![Virustotal - Malicious file accusation ](https://user-images.githubusercontent.com/110700112/209884675-76a08849-8ba4-4586-9f1b-c8d36831817d.png)

### Flow Launcher Version

v1.10.1

### Windows Build Number

10.0.22000.1335

**Comment by jjw24** [comment]
Hi there, make sure the exe setup file you have downloaded is from flowlauncher.com or the GitHub repo.

 AVG and Virustotal's alerts are false positives. The alert you are getting from AVG is the same as this issue here https://github.com/Flow-Launcher/Flow.Launcher/issues/1177, please help us raise a false positive report with Avast.

**Comment by MasterK79** [comment]
I've disabled the AVG alerts and marked it as a false positive, downloaded the .exe file directly from flowlauncher.com, and tried to install it again but this Error occurs, I apologize for causing so much trouble.

[SquirrelSetup -Log- InstallationError.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10317205/SquirrelSetup.-Log-.InstallationError.txt)

**Comment by jjw24** [comment]
All good, no stress.

It's likely setup has some left over files. Can you check if AppData's Local folder has a folder called FlowLauncher? If exists delete it.

If still no good try the portable version, that doesn't require any installation.

**Comment by MasterK79** [comment]
I've tried the portable version, now it's working properly, thank you so much.
