### ISSUE TITLE
index with localized name of file/folder

### ISSUE THREAD

**Issue by u-Sir** [Flow-Launcher/Flow.Launcher#1732]
**Is your feature request related to a problem? Please describe.**

As non-English user, some windows files/folders display localized in windows explorer, but can't search by localized name in Flow launcher. e.g. `control panel`- `控制面板`(Chinese)
just like start menu, support search in Pinyin
![图片](https://user-images.githubusercontent.com/93647031/209914752-901f8b89-c7ad-49cc-a117-dd3ce86fc978.png)

something may help :
https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shgetlocalizedname
http://archives.miloush.net/michkap/archive/2007/01/18/1487464.html

```powershell
    $FilePath = "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\Windows Defender Firewall with Advanced Security.lnk"
    $ChildObj = Get-ChildItem $FilePath 
    $FldrName = $ChildObj.DirectoryName 
    $FileName = $ChildObj.Name 
    $Shell    = New-Object -ComObject Shell.Application 
    $Folder   = $Shell.Namespace($FldrName) 
    $File     = $Folder.ParseName($FileName) 
    echo $($Folder.GetDetailsOf($File,0))
```

![图片](https://user-images.githubusercontent.com/93647031/209914956-75164528-2ce2-4d09-a319-31ec4a5e052a.png)

**Comment by jjw24** [comment]
Available in pre-release.

**Comment by VictoriousRaptor** [comment]
> Available in pre-release.

Folders are not available yet.

**Comment by u-Sir** [comment]
> > Available in pre-release.
> 
> Folders are not available yet.

ok, for folders check this:
http://archives.miloush.net/michkap/archive/2007/01/18/1487464.html

**Comment by VictoriousRaptor** [comment]
Though we can get localized folder names, Everything doesn't allow you to search localized names. If we want use localized name as search terms, we need to create a mapping from localized name to actual path which is difficult.
