### ISSUE TITLE
Merge performance improvements from Wox

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#174]
**Discussion**
I think @bao-qian has made quite a lot of performance improvements at the new prerelease version of wox. 
Should we merge some of the change to flow?

**Comment by jjw24** [comment]
> 
> 
> **Discussion**
> I think @bao-qian has made quite a lot of performance improvements at the new prerelease version of wox. 
> Should we merge some of the change to flow? 

I had a look earlier and tried some of the new changes, they don't seem to be applicable for Flow.

Are there any particular changes you are thinking of?

**Comment by taooceros** [comment]
There is some of the changes that are useful for us.
1. Index for win32 App (seems that the code can be optimized quite a lot).
2. Some code in Win32 App
3. @bao-qian has changed the pinyin library to [url](https://github.com/toolgood/ToolGood.Words.Pinyin). I have taken a look on the pinyin library, and it seems that the current one is somewhat inefficient (though work fine), and the startup time has been used a lot for loading pinyin cache.

**Comment by jjw24** [comment]
I think the above is done right?

**Comment by taooceros** [comment]
Yes, almost done.
