### ISSUE TITLE
BUG: AVG antivirus reports "flow.launcher.exe is infected with idp.alexa.53" and wants to quarantine it

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1741]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I am using Windows 10 Version 10.0.19044.

I updated flow.launcher to the latest version using its own "check for updates" feature. When I restarted flow.launcher, my antivirus (SVG) reports "flow.launcher.exe is infected with idp.alexa.53" and wants to quarantine it.

There is a provision to add it to exceptions. But that seems risky without knowing what exactly the issue is!

### To Reproduce

1. Just update Flow.launcher
2. ...
3. ...

### Flow Launcher Version

v1.11.0

### Windows Build Number

10.0.19043.1288

### Error Log

SVG e303e5333422/2022-12-30T14:45:30.264Z

```shell

Replace this line with the important log contents.

```
</details>

**Comment by raindropsfromsky** [comment]
I have filed a report with AVG

**Comment by deefrawley** [comment]
Thanks. This is a false positive so every report to the AV company letting them know helps.
