### ISSUE TITLE
BUG:  lag/freeze during input Program Plugin

### ISSUE THREAD

**Issue by mohcow** [Flow-Launcher/Flow.Launcher#1746]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Since v1.10.0 i get a 2-5 second freeze when input something in in flow launcher. I use program plugin with * keyword which worked flawlessly with 1.9.5 and still works after going back to it with the same settings as 1.10.0. after disabling program it work fine.

### To Reproduce

1. input anything
2. freeze for a few seconds
3. flow launcher shows results

### Flow Launcher Version

v1.10.0 - v1.11.0 

### Windows Build Number

10.0.19045.2364

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by VictoriousRaptor** [comment]
Sorry about that. Does it freeze every time or just the first query after launching?

**Comment by pavelsafre** [comment]
For reference: here is a description is a similar issue for `PowerToys Run` with a lot of analysis:
[Searching feels really slow #4918](https://github.com/microsoft/PowerToys/issues/4918)

**Comment by jjw24** [comment]
Please confirm if it freezes every time or just the first query after launching? Our issue might be different to PT Run's.

**Comment by mohcow** [comment]
It is very weird. Started the PC this morning everything was fine, no freezes, FL worked flawlessly. Used the PC, play some games and whatnot for a few hours, tried to use FL again and the freezing happened. Right after enter the first letter it just freezes. Trying to troubleshoot this I closed every program that isn't on startup and it still happened. After entering a different first letter/character for 20-30 times it went away. 

I have no clue how to troubleshoot this.

**Comment by pavelsafre** [comment]
Is there a way to e.g. set the logs to the debug level to see the more details about the processes, happening inside?

**Comment by taooceros** [comment]
I believe it's some ui issue and log may not help. pt run's issue comes from disabling virtualization, which we didn't introduce for 1.10. I cannot think of a specific reason that may cause this issue, but one thing worth notice is we have introduced the drag and drop feature, which may change something in the resultlists?

**Comment by VictoriousRaptor** [comment]
Is it related to #1787?
