### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Projeet1002** [Flow-Launcher/Flow.Launcher#1749]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

It showed me an error after updating it and then it is not opening

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Looks like you are using a very old version 1.8.3. Were you able to successfully update flow on second try?
