### ISSUE TITLE
About the Flow website

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#175]
I saw you @jjw24 have forked [Website](https://github.com/jjw24/Website).

I can rewrite a website belongs to Flow.

I'm also a full-stack developer (by Bootstrap as frontend, Flask as backend). 
An example, its name called [iPicture](https://github.com/Zeroto521/ipicture) ~(one of the website projects in my college period, and not enough good, it will be private again in later days)~.

But I'm not good at the **design**. So about what the website looks like should be a problem.

**Comment by jjw24** [comment]
That would be legendary.

I forked the website only because there was a period that it went down so I thought it is needed to have a back up. So by no means we need to stick to the tech stack used there.

We should have a standalone branch called Flow.Launcher.Website

Any ideas, content, layout suggestions @Flow-Launcher/team ?

**Comment by Zeroto521** [comment]
OK, we discuss this topic here.

But it seems strange, @Flow-Launcher/team no GitHub's notification for me. I can see this only click this link.

> ![image](https://user-images.githubusercontent.com/25895405/96327374-7a0ab800-106b-11eb-98ea-91201f3bcdbb.png)

Did you get some notifications from the team discussion?

**Comment by jjw24** [comment]
Yeah I don't think I get a notification with the team mentions.


Can you join our official Flow discord channel https://discord.gg/AvgAQgh, we can bring the discussion over there.

**Comment by jjw24** [comment]
repo has been created, https://github.com/Flow-Launcher/Flow.Launcher.Website

**Comment by jjw24** [comment]
closing. Future website related discussion can be made at the website repo
