### ISSUE TITLE
Flow stopped working with Windows 11 Home (64 bit)

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1767]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Till last week, I was using **Flow** and **Everything** on my laptop that ran on Windows 10 Home.

Last week my laptop OS crashed. 
My Acer Authorized service center upgraded Windows to Win 11 Home, 64 bits. 
I had to re-install all the apps afresh.

But after the upgrade, now I am having problem with **Flow**: It simply does not show ANY results!

My internal hard disk has a non-Windows partition. 
In addition, I have connected four external HDDs. 
But **Flow** is unable to find anything from any of these drives.

In the same set up, **Everything** works fine: It shows results from all my drives.
Therefore I am concluding that file indexing is working fine in Windows 11.

I tried the **Portable** version of Flow, but that does not work, either!

What could be wrong?

### To Reproduce

1. Install Flow and run.
2. Check out existing files in the drives and search word(s) from their names 
3. Expect Flow to discover these files
4. Actual result: Flow fails to "discover" even these known test cases.

### Flow Launcher Version

v1.11.0

### Windows Build Number

Version 10.0.22621 Build 22621

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Please upload some log. I am using win11 as well and cannot reproduce what you are experiencing. 

Is flow showing 0 result or only programs are not showing? (for example do 1+1 works? )

**Comment by raindropsfromsky** [comment]
Formula works fine.

Error log is attached.
[2023-01-08.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10368155/2023-01-08.txt)

**Comment by raindropsfromsky** [comment]
![image](https://user-images.githubusercontent.com/9047168/211191702-20d7431a-dd45-4696-af34-04e25c9bc902.png)
This is just an example: I have tons of files that have the "dataviz" word in their name.
But Flow fails to discover any of them.

**Comment by z1nc0r3** [comment]
Make sure you have selected **Everything** as the search engine is the _Explorer plugin_.

![image](https://user-images.githubusercontent.com/64279853/211231619-bbcefe61-b915-441a-a905-a3c31d793ebb.png)

And also, please try searching by considering the case of the word. I have experienced that sometimes **Everything** is case-sensitive (no idea why).

**Comment by raindropsfromsky** [comment]
I changed all three options to "Everything", but that has not restored the performance.

BTW I suspect that there are two separate installations of Everything on my laptop: A plugin within Flow, and a stand-alone version that I installed separately (I downloaded Everything and installed it manually).
- The plugin version has not shown any results
- The stand-alone version works fine

**Comment by z1nc0r3** [comment]
> Everything plugin is now part of Explorer plugin (remember to remove the existing standalone Everything plugin if installed)

From FL v1.10.0, **Everything** is integrated into FL. So no need to install the plugin. Please uninstall the **Everything** plugin and try.

**Comment by taooceros** [comment]
You need to run everything to use the plug-in.

**Comment by z1nc0r3** [comment]
You have to install the Everything desktop application and **uninstall the plugin that was installed through FL**. You can find it in **FL Settings > Plugin**

**Comment by raindropsfromsky** [comment]
> Oh I guess I misunderstood your issue. So now the everything plug-in is not working but the program plug-in is still working?

No I was tinkering with Flow while waiting for response here. I may have found an issue during such random experiments: In my old installation, I had increased the max results to 15. After my OS crashed, my fresh installation had a max results of 5.  This limit is reached _even before_ Flow starts showing files and folders! (For example, the first few entries are about Google search, etc. See the screenshot I have posted above!)

So while tinkering with the settings, I increased the max results to 15, and now I am able to see the results.

**Comment by taooceros** [comment]
I think there's consistency issue with the settings when system crash. We are trying to fix it in #1763. Just to let you know, you can scroll the result down and see further results.

**Comment by raindropsfromsky** [comment]
> ...you can scroll the result down and see further results.

Actually, this did NOT happen!

I was actually expecting FL to display x entries at a time (where x is a selectable number in the range 5-15). That means I should be able to see the rest of the results by scrolling down. But that did NOT happen when the default count was 5 in my fresh installation. (You can see that in both my screenshots in this thread, there is no scrollable list at all.)

So there is some issue with the display. When I changed the count to 15 (the max allowable in the settings), FL started showing more results. That's not normal.

Although this behavior has a bug, I am not able to catch a pattern.

**Comment by jjw24** [comment]
@raindropsfromsky it sounds like the original issue is Explorer not the everything service that's why you are seeing the warning. Is this still an issue?

I have been using max results displayed at 5, not able to reproduce what you mentioned in the above comment. When you increase to 15 and see the results, can you then decrease to 10 and see if you can still scroll through all the results, then try 5.

**Comment by raindropsfromsky** [comment]
I changed the settings to 10 and then again to 5.
But now FL works fine consistently.
AFAIK nothing has changed!

But if you see my screenshots above, you will clearly see that the problem did exist.
(The scroll bar is large or non-existent, which means that there are very few results, or no results at all.)

But since there is no consistency, we should probably close this bug...
