### ISSUE TITLE
BUG: Incompatibility of plugin `Flow.Launcher.Plugin.Explorer` with Everything (1.5a)

### ISSUE THREAD

**Issue by oSumAtrIX** [Flow-Launcher/Flow.Launcher#1769]
### Checks

- [X] I have checked that this issue has not already been reported.

#### If [Everything 1.5a](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787) is used and properly installed as a service instead of Everything 1.4, the current latest version, `IsEverythingRunningAsync` will return `false`:

https://github.com/Flow-Launcher/Flow.Launcher/blob/c0f46f24de3ad1bf80f329f46be375fb18115596/Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingAPI.cs#L92-L106

#### More context on this might be revealed through the comment here:

https://github.com/Flow-Launcher/Flow.Launcher/blob/c0f46f24de3ad1bf80f329f46be375fb18115596/Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs#L405-L425

### To Reproduce

1. Install Flow Launcher and Everything 1.4, and observe that the Flow Launcher Explorer plugin works
2. Install Everything 1.5a (It is stated, that it seamlessly migrates from 1.4 to 1.5a which it does indeed), and observe the Flow Launcher Explorer plugin does not work

### Screenshots

![image](https://user-images.githubusercontent.com/13122796/211292952-6bc79391-8a0b-449e-81ab-6f0f2cda6b1a.png)

![image](https://user-images.githubusercontent.com/13122796/211293103-370c667e-ec07-434d-ab55-0264670ba7d3.png)

![image](https://user-images.githubusercontent.com/13122796/211293114-7f8e760e-5c9c-4ffe-be93-1500055485bc.png)

### Flow Launcher Version

v1.11.0

### Windows Build Number

10.0.22621.963

**Comment by VictoriousRaptor** [comment]
Dup #1716. Please try the fix in the comment. This is a known issue, and it's because Everything SDK is uncompatible with its alpha version.

**Comment by oSumAtrIX** [comment]
Following up on your suggestion, https://github.com/Flow-Launcher/Flow.Launcher/issues/1716#issuecomment-1364573775 worked.
