### ISSUE TITLE
BUG: Constant crash due to graphics card

### ISSUE THREAD

**Issue by NolanNolan** [Flow-Launcher/Flow.Launcher#1792]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

after a short while the app crashes. 

### To Reproduce

1. ...well it just crashes. 
2. ...
3. ...

### Flow Launcher Version

1.11.0

### Windows Build Number

[Version 10.0.22621.1105]

### Error Log

```shell
[2023-01-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10412258/2023-01-13.txt)

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Unfortunately there's no enough information for us to debug. Could you check the event viewer and see whether any crash event related to flow?

**Comment by NolanNolan** [comment]
Beskrivelse
A problem caused this program to stop interacting with Windows.
Sti for fejlbehæftet program:                          C:\Users\FamilienBue\AppData\Local\FlowLauncher\app-1.11.0\Flow.Launcher.exe

Problemsignatur
Problemhændelsesnavn:       AppHangB1
Application Name:                   Flow.Launcher.exe
Application Version:                1.11.0.0
Application Timestamp:         63558578
Hang Signature:                        0000
Hang Type:      0
OS-version:     10.0.22621.2.0.0.256.48
Landestandard-id:                   1030
Additional Hang Signature 1: 00000000000000000000000000000000
Additional Hang Signature 2: 0000
Additional Hang Signature 3: 00000000000000000000000000000000
Additional Hang Signature 4: 0000
Additional Hang Signature 5: 00000000000000000000000000000000
Additional Hang Signature 6: 0000
Additional Hang Signature 7: 00000000000000000000000000000000

Ekstra oplysninger om problemet
Filsæt-id:         45e93f3d4c7468076cbc2c12ff88005f (2070578388791722079)


Hilsen Jørn

Fra: Kevin ***@***.***>
Sendt: 13. januar 2023 15:30
Til: ***@***.***>
Cc: Jørn Bue ***@***.***>; ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Constant crash (Issue #1792)


Unfortunately there's no enough information for us to debug. Could you check the event viewer and see whether any crash event related to flow?

**Comment by taooceros** [comment]
This seems to be a very specific error related to your computer....and I don't really have idea about why it is happening. Probably you can try some resolution in the internet with related to the AppHangB1 error.

**Comment by jjw24** [comment]
Would antivirus if you have on @NolanNolan be related?

**Comment by NolanNolan** [comment]
Hmm maybe, thanks, ill do some testing


Hilsen Jørn

Fra: Jeremy ***@***.***>
Sendt: 13. januar 2023 22:45
Til: ***@***.***>
Cc: Jørn Bue ***@***.***>; ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Constant crash (Issue #1792)


Would antivirus if you have on @NolanNolan<https://github.com/NolanNolan> be related?

**Comment by NolanNolan** [comment]
If i reduce the no of apps open, I seems not to crashs, can you make anything of this ?

E.g., the app is closed by the system because it has a lower “rank” than e.g., pef editor, word etc?

Hilsen Jørn

Fra: Jeremy Wu ***@***.***>
Sendt: 13. januar 2023 22:45
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Mention ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Constant crash (Issue #1792)


Would antivirus if you have on @NolanNolan<https://github.com/NolanNolan> be related?

**Comment by jjw24** [comment]
>If i reduce the no of apps open

Do you mean reducing the number of apps open on your computer and then flow does not crash?

**Comment by NolanNolan** [comment]
Yes exactly 🙂

Hilsen Jørn

On 15. januar 2023 22.07.43 Jeremy Wu ***@***.***> wrote:

If i reduce the no of apps open

Do you mean reducing the number of apps open on your computer and then flow does not crash?

**Comment by jjw24** [comment]
That sounds like a computer memory problem?

**Comment by NolanNolan** [comment]
I don't think so, because it's just this app that shows that behaviour

Hilsen Jørn

On 15. januar 2023 22.10.35 Jeremy Wu ***@***.***> wrote:

That sounds like a computer memory problem?

**Comment by NolanNolan** [comment]
Hi

Could it be possible to make the preview much bigger så it´s actually possible to see what it is, that would be very helpful… 😊 See below

***@***.***

Hilsen Jørn

Fra: Jørn Bue Madsen ***@***.***>
Sendt: 15. januar 2023 22:11
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Constant crash (Issue #1792)


I don't think so, because it's just this app that shows that behaviour

Hilsen Jørn

On 15. januar 2023 22.10.35 Jeremy Wu ***@***.******@***.***>> wrote:

That sounds like a computer memory problem?

**Comment by taooceros** [comment]
@onesounds

**Comment by onesounds** [comment]
preview area size is not changable. (I have a plan for the function but not this time)

**Comment by NolanNolan** [comment]
Hi

I now teste "powertoys run" and "Fluent search application", the crash does not happen for these applications, it´s only flow launcher that crashes, even when no other applications are running.

Any ideas of how to solve this ?

Hilsen Jørn

Fra: Jørn Bue Madsen ***@***.***>
Sendt: 15. januar 2023 22:11
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Constant crash (Issue #1792)


I don't think so, because it's just this app that shows that behaviour

Hilsen Jørn

On 15. januar 2023 22.10.35 Jeremy Wu ***@***.******@***.***>> wrote:

That sounds like a computer memory problem?

-

**Comment by VictoriousRaptor** [comment]
Just Googled about `AppHangB1` and most results are related to DirectX and graphic card drivers. Any idea?

**Comment by NolanNolan** [comment]
Hi

it so far seems the culprit was enabling both PCI graphic card and the intel onboard graphic card. This caused drivers for both cards to be loaded in windows. I disabled onboard graphic card in bios again, and so far the crash has stopped.

fingers crossed...

thanks for your input

best Nolan

**Comment by deefrawley** [comment]
Going to close as issue seems to be resolved.

**Comment by NolanNolan** [comment]
Hi
the crash is back, didnt seem to relate to graphical drivers. Flow launcher keeps crashing randonly with the errer AppHangB1

**Comment by NolanNolan** [comment]
yes, ill try to disable, but it does work with same antivirus on other PCs so my evaluatin is its not that

**Comment by NolanNolan** [comment]
ok, is there a smar way to gather all that data for you ?

**Comment by deefrawley** [comment]
CPU-Z and GPU-Z are good utilities to have, then you can post screenshots:

https://www.cpuid.com/softwares/cpu-z.html
https://www.techpowerup.com/gpuz/

**Comment by NolanNolan** [comment]
Hi attached data as requested
![data](https://user-images.githubusercontent.com/30736282/220675485-70c05ff2-96f3-48ee-84b2-88517dbff293.gif)
[Driver.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10805601/Driver.txt)

can you make anything of this ?

**Comment by deefrawley** [comment]
Your system is very similar to mine. Try booting Windows in Safe Mode and then starting Flow and see if the crashes occur. Also try disabling any AV/firewalls and see if that makes a difference

**Comment by NolanNolan** [comment]
Thanks, how would that shed new light on the issue ?

best Nolan

**Comment by deefrawley** [comment]
> Thanks, how would that shed new light on the issue ?
> 
> best Nolan

Starting in safe mode disables all the extra drivers and startup apps in Windows so will show if the issue is with those or with Flow itself.
Flow has also been upgraded several times so first thin is to upgrade to the latest version and see if the issue still happens.

**Comment by NolanNolan** [comment]
Thanks, yes I know, I referred to
Windows Sandbox

**Comment by jjw24** [comment]
Sandbox suggestion is similar as well, it is a faster option if you have it enabled. Sandbox provides you with a vanilla Windows with no user installations on boot up. This will be useful because it would align our test environments and hopefully figure out whether its something specific to user installed apps causing issue or maybe computer configuration.

**Comment by NolanNolan** [comment]
I see thanks, I'll test it and get back

Hilsen Jørn

On 22. marts 2023 22.55.56 Jeremy Wu ***@***.***> wrote:

Sandbox suggestion is similar as well, it is a faster option if you have it enabled. Sandbox provides you with a vanilla Windows with no user installations on boot up. This will be useful because it would align our test environments and hopefully figure out whether its something specific to user installed apps causing issue or maybe computer configuration.
