### ISSUE TITLE
Incorrect names of system commands

### ISSUE THREAD

**Issue by reko001** [Flow-Launcher/Flow.Launcher#1819]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

According to README.md, names of commands should be Flow Launcher UserData and Flow Launcher Tip but in they are: Flow Launcher UserData Folder and Flow Launcher Tips

### To Reproduce

1. Open FlowLauncher
2. Open window search (alt + space)
3. Write command
4. Current result: command is not present but there is a command with slightly different name
5. Expected result: command should be found with correct name

### Flow Launcher Version

1.11.0

### Windows Build Number

10.0.22621.1105

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Hey @reko001 thanks for letting us know about this.

I want to update these commands similar to `Open Log Location`

![image](https://user-images.githubusercontent.com/26427004/216153040-87f37c9b-91f8-4da7-b387-3acee40f2936.png)

So they will be 'Open UserData Folder' and 'Open Tips Documentation'
