### ISSUE TITLE
Maximum window width size

### ISSUE THREAD

**Issue by reko001** [Flow-Launcher/Flow.Launcher#1820]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

Maximum window width size to set is always 1920 even if the screen resolution is lower

### To Reproduce

1. Change screen resolution with width lower than 1920
2. Open FlowLauncher and Theme tab
3. Set maximum window width size
4. Current result: Width is set to 1920
5. Expected result: Width is set to current resolution width

### Flow Launcher Version

1.11.0

### Windows Build Number

10.0.22621.1105]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
I believe this slider is fixed at 1920 regardless of window size. What happens to the Flow window when you set the width wider than the screen res?

**Comment by deefrawley** [comment]
I've confirmed this is a known limitation with this function. We are yet to implement the settings getting the current screen width.

**Comment by onesounds** [comment]
This problem will be improved.
