### ISSUE TITLE
BUG: Priority search does not work correctly for input: -2147483648

### ISSUE THREAD

**Issue by reko001** [Flow-Launcher/Flow.Launcher#1822]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

After setting priority to: -2147483648 the searches in this plugin should appear on the bottom but they are still on top.

### To Reproduce

1. Set priority of web search to -2147483648
2. Set priority of explorer to -1
3. Create file named "test" in indexed directory
4. Search for "test"
5. Current result: Web search appears before explorer search
6. Expected result: Web search appears on bottom

### Flow Launcher Version

1.11.0

### Windows Build Number

10.0.22621.1105

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Don't do that. We use a simple int to calculate the scores. Setting the priority to such a low number will definitely result in overflow and probably some weird behavior. Just set to a reasonable number like -10 or -20 or even -100 is sufficient for most case possible.

**Comment by onesounds** [comment]
> Don't do that. We use a simple int to calculate the scores. Setting the priority to such a low number will definitely result in overflow and probably some weird behavior. Just set to a reasonable number like -10 or -20 or even -100 is sufficient for most case possible.

yeah it is not normal use case. but I think it will be better set the maximum/minimum value (by xaml). I'll handle the issue.
