### ISSUE TITLE
Change the default shortcut for Plugin Indicator to `?`

### ISSUE THREAD

**Issue by TheBestPessimist** [Flow-Launcher/Flow.Launcher#1825]
**Is your feature request related to a problem? Please describe.**

For a power user who is new to FlowLauncher (FL), quickly learning the tricks which make FL good and fast is the "do or die".

One way to improve this is by quickly showing the available commands.

#### Status quo

The way I see this possible is by the manually-intensive work of going through all plugins, then expanding each plugin individually, then reading the plugin shortcut:
![image](https://user-images.githubusercontent.com/4482210/213864895-a7ff31c3-2b78-4091-acaa-d271a50af18f.png)

The problem with this approach is that I easily forget what i read. 
So i know i want to do something, but i don't know its shortcut. So i need to move back and read all the keyboard shortcuts again 🙄 .

Another problem imo is that the current shortcut is `*`, which i interpret as "type something and hope that your 10TB of files from the company NAS do not hide the "names of all the possible shortcuts/functionality" FL has.

**Describe the solution you'd like**

In my opinion, the following makes so much sense: open FL, type <kbd>?</kbd> and see all the available commands.
This is similar to how you can type <kbd>?</kbd> while browsing github, or discourse to see the available shortcuts.

**Describe alternatives you've considered**

Leave everything as it is and let beginner users struggle to learn. Also: make users have to add shortcuts manually instead of providing them OOTB.

**Additional context**

Would you accept a PR for that? 
It looks like a simple change here: https://github.com/Flow-Launcher/Flow.Launcher/blob/b6120ac4fe20607deaeb77d7d9f5f668a4d3bb27/Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json

Note that i'm a kotlin dev, not a c# dev, so idk if anything else needs fixing, so your guidance is welcome.

**Comment by z1nc0r3** [comment]
I really don't know whether I got your idea correctly. But you can change the shortcut for the **Plugin Indicator**, to `?`. Then you can type `?` in FL and get all available shortcut lists for the plugins.

**Comment by TheBestPessimist** [comment]
You're right, i can and i did it. My wish is to make it <kbd>?</kbd> by default, to make the OOTB experience better for everybody, not just for me.

**Comment by jjw24** [comment]
>It looks like a simple change here: https://github.com/Flow-Launcher/Flow.Launcher/blob/b6120ac4fe20607deaeb77d7d9f5f668a4d3bb27/Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json

Hi @TheBestPessimist, yep that's the location for changing, it's a simple one. Please go ahead, thank you for bringing this to our attention.
