### ISSUE TITLE
System.NotSupportedException: 'Non+D1' key and modifier combination is not supported for KeyGesture.

### ISSUE THREAD

**Issue by CuteNickychan** [Flow-Launcher/Flow.Launcher#1828]
Hey, ich just downloaded flow launcher yesterday and when starting my pc today i get this error, i think it might be because i accidentally assinged the number1 button to see preview.

Im pretty sure i can fix the issue myself by deleting the settings file, but i wanted to bring it to light, since its an issue that persistes through reinstalls of the launcher

UPDATE: i was not able to find out how to fix it myself
UPDATE 2: i was looking in the wrong place
[2023-01-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10473994/2023-01-22.txt)

**Comment by VictoriousRaptor** [comment]
> Hey, ich just downloaded flow launcher yesterday and when starting my pc today i get this error, i think it might be because i accidentally assinged the number1 button to see preview.
> 
> Im pretty sure i can fix the issue myself by deleting the settings file, but i wanted to bring it to light, since its an issue that persistes through reinstalls of the launcher
> 
> UPDATE: i was not able to find out how to fix it myself UPDATE 2: i was looking in the wrong place [2023-01-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10473994/2023-01-22.txt)

#1755, please look for a fix there. uninstall doesn't clear your settings so it doesn't fix this problem.
