### ISSUE TITLE
Explorer plugin - Everything: Recognize the default filter

### ISSUE THREAD

**Issue by gisturbance** [Flow-Launcher/Flow.Launcher#1831]
**Is your feature request related to a problem? Please describe.**

When using Everything (1.5a) to search through files and folders, one can use built-in or create custom filters, f.e. to limit search to specific file types, or to only include online volumes. Everything has a built-in filter named "Everything" that is set as default - filtering nothing by default, unless manually specified.

Currently, the default filter is not respected when using the Explorer plugin (with Everything).

**Describe the solution you'd like**

Add a setting to manually specify a default filter. If empty, use the built-in filter "Everything", or, if possible, detect which filter is set as default in Everything itself.

**Describe alternatives you've considered**

One has to manually add "filtername:" for every single search, which does not work with the default filter named "Everything", leaving no alternative for it.

**Comment by taooceros** [comment]
I don't think this is possible given the current everything sdk. If you have any idea about how to implement this feature, please feel free to fire a pr or shares an implementation idea.

**Comment by gisturbance** [comment]
After further research, accessing filters doesn't seem to be possible currently, but will be added in future.

As an alternative, one could allow the manual creation of filters directly in Flow Launcher.
Since filters are a collection of [functions](https://www.voidtools.com/forum/viewtopic.php?t=10176), simply concatenated with the search string and passed using [Everything_SetSearch](https://www.voidtools.com/forum/viewtopic.php?f=10&t=11247&p=43931#p43931), that should be fairly easy to accomplish.

**Comment by gisturbance** [comment]
@taooceros What do you think about implementing the manual creation of filters directly in FlowLauncher, as suggested above? Pardon me, if that belongs in a separate issue.

**Comment by gisturbance** [comment]
> @gisturbance i think you can just concat the filter to your query. Either use a shortcut or a special keystroke shall not be bad.

Indeed an alternative. For some reason it didn't work for me at the time I created the issue.

However it pollutes the search field, which could be ommited by specifying a hidden default filter.

**Comment by taooceros** [comment]
You can specify a shortcut to simulate that, which might help the pollution?
