### ISSUE TITLE
Selecting the end of a long string causes the text to overlap

### ISSUE THREAD

**Issue by nullnullnullnull0** [Flow-Launcher/Flow.Launcher#186]
![copied-2020-10-18-21_34_43](https://user-images.githubusercontent.com/21099726/96449313-3d93b380-1247-11eb-9bea-4786e1a4cdc9.png)
![copied-2020-10-18-21_34_56](https://user-images.githubusercontent.com/21099726/96449324-41bfd100-1247-11eb-9ccb-338c09102769.png)

g pneumonoultramicroscopicsilicovolcanoconiosis

**Comment by gundamhyl** [comment]
I think the problem is caused by auto suggestions, is there an option to turn off this feature?

**Comment by Zeroto521** [comment]
Really have we this problem？I mean we may not key in such strange keywords.
But this is a bug for Flow indeed.

**Comment by jjw24** [comment]
There is currently no option to turn that off, I prefer to have this fix though haha. I am aware of it but never got around to looking into why.
