### ISSUE TITLE
[URL PLUGIN] providing empty string should launch default browser.

### ISSUE THREAD

**Issue by KAGEYAM4** [Flow-Launcher/Flow.Launcher#1865]
**Is your feature request related to a problem? Please describe.**

In PowerToys i used to `//` `Enter` to directly launch the Browser, instead of searching for it.

**Describe the solution you'd like**

Currently if activation command is provided with empty string this error pops up --> `Can't open url:https://`
Instead of this, Lauch the Browser or maybe provide a toggle option at plugin setting for user to choose.

**Comment by jjw24** [comment]
Hi there, you can use Custom Query Shortcut to achieve this:

![image](https://user-images.githubusercontent.com/26427004/216842518-0258891c-420e-4cb2-b969-ed3030fd3947.png)
