### ISSUE TITLE
BUG: Trackpad scrolling is too fast.

### ISSUE THREAD

**Issue by tarikjaber** [Flow-Launcher/Flow.Launcher#1868]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

Scrolling is too fast in the flowlauncher settings pages when using a trackpad (mouse is fine). It is also not smooth with noticeable jumps even for the smallest scrolls.

### To Reproduce

1. Go to flowlauncher settings
2. Try to scroll in any of sections.

### Flow Launcher Version

1.12.1

### Windows Build Number

Version 10.0.22000.1455

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Can repro using touchpad when increasing the lines to scroll in Mouse settings. Please try adjusting to see if makes a difference:

![image](https://user-images.githubusercontent.com/26427004/216844626-b3109fea-e5d9-477b-88e4-407b6ec944fa.png)

**Comment by tarikjaber** [comment]
Sorry for the late reply. I appreciate the feedback.

Unfortunately it seems like updating that setting doesn't improve the scrolling. It still is quite jittery. 

Is it possible to make the scrolling smooth like in the settings app of windows 11? It is substantially smoother. I'd be willing to investigate and try to update the code if necessary.

**Comment by onesounds** [comment]
Smooth scroll is technically possible, but we're not currently implementing it due to some issues.
(There's a problem on the framework side we're using.)
I have some improvements planned for smooth scroll, but I don't know when they will be available. (And I'm not sure if this improvement will affect touchpad usage.) 😂

**Comment by tarikjaber** [comment]
Thank you very much for your responses!
