### ISSUE TITLE
error with plugins

### ISSUE THREAD

**Issue by jcmn100** [Flow-Launcher/Flow.Launcher#1876]
[2023-02-03.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10579164/2023-02-03.txt)

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Utilizador\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/03/2023 13:12:27
Exception:
System.TypeLoadException: Could not load type 'Flow.Launcher.Infrastructure.Storage.JsonStrorage`1' from assembly 'Flow.Launcher.Infrastructure, Version=1.12.1.0, Culture=neutral, PublicKeyToken=null'.
   at Flow.Launcher.Plugin.Everything.Main.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 53
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 146
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 81
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 106
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by T1CkShot** [comment]
Same here also with the Flow youtube plugin

**Comment by deefrawley** [comment]
Hi. When logging an error report can you please tell us what you were actually doing or typing in Flow when the error occurred otherwise we can't replicate.
@T1CkShot - that error shows the problem in the Epic Games Store plugin. Is that what you were using?

**Comment by T1CkShot** [comment]
Flow launcher gave a notification saying the plugins FlowYoutube, Epic games store search were unable to initialize and disabled. I enabled the plugins again and when I input the action for the plugins the launcher crashes.

**Comment by Garulf** [comment]
> Same here also with the Flow youtube plugin
> 
> ```
> 
> Flow Launcher version: 1.12.1
> 
> OS Version: Microsoft Windows NT 10.0.22621.0
> 
> IntPtr Length: 8
> 
> x64: True
> 
> 
> 
> Python Path: C:\Users\UserName\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
> 
> Node Path: 
> 
> Date: 02/03/2023 22:56:09
> 
> Exception:
> 
> Epic Games Store Launcher Exception: 
> 
> Websites: https://github.com/Garulf/epic_games_store_launcher
> 
> Author: Garulf
> 
> Version: 2.0.0
> 
> Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\run.py", line 9, in <module>
> 
>     from plugin.main import EpicGamesStoreLauncher
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\plugin\main.py", line 3, in <module>
> 
>     from flox import Flox, ICON_WARNING
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\lib\flox\__init__.py", line 50, in <module>
> 
>     raise FileNotFoundError("Unable to locate Launcher directory")
> 
> FileNotFoundError: Unable to locate Launcher directory
> 
> 
> 
>  ---> System.IO.InvalidDataException: Traceback (most recent call last):
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\run.py", line 9, in <module>
> 
>     from plugin.main import EpicGamesStoreLauncher
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\plugin\main.py", line 3, in <module>
> 
>     from flox import Flox, ICON_WARNING
> 
>   File "C:\Users\UserName\AppData\Roaming\FlowLauncher\Plugins\Epic Games Store Launcher-2.0.0\lib\flox\__init__.py", line 50, in <module>
> 
>     raise FileNotFoundError("Unable to locate Launcher directory")
> 
> FileNotFoundError: Unable to locate Launcher directory
> 
> 
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
> 
>    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
> 
> --- End of stack trace from previous location ---
> 
>    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
> 
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
> 
>    --- End of inner exception stack trace ---
> 
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
> 
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
> 
> --- End of stack trace from previous location ---
> 
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
> 
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
> 
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> 
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> ```

Looks like the library i use in all my plugins, Flox, is having a hard time finding your installation of Flow Launcher. 


How was Flow Launcher installed?
Are you running Flow Launcher in a non-standard way?

**Comment by jcmn100** [comment]
This happens when startup the system.

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by T1CkShot** [comment]
No I installed Flow launcher using the .exe in the default location few days ago. The plugins were working fine. They stopped working yesterday. I've tried uninstalling and re installing the plugins too.

**Comment by T1CkShot** [comment]
I did a clean installation of Flow launcher and now all the plugins are working fine.

**Comment by jjw24** [comment]
> This happens when startup the system. Enviado de Outlook para Android<https://aka.ms/AAb9ysg>

This looks like a saving issue, please try this build here and let us know if addresses the problem https://ci.appveyor.com/api/buildjobs/fpolnta6i7na6npu/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
