### ISSUE TITLE
Enhance: Flow.Launcher.Plugin.Explorer set MaxResult

### ISSUE THREAD

**Issue by AETeK5** [Flow-Launcher/Flow.Launcher#1889]
**Is your feature request related to a problem? Please describe.**

Plugin doesn't have the option to set the maxresult in the flow launcher plugins settings. It has an attribute for it in the Settings.json file.

**Describe the solution you'd like**
Have an attribute field in the plugins settings to be able to change the attribute.

**Comment by deefrawley** [comment]
Hi, do you mean a different value to the global Maximum Results Shown setting?

**Comment by AETeK5** [comment]
Hey. More like a field in the general Settings or if it is a everything attribute in the everthing settings. So everybody can customize it to his preference.

![grafik](https://user-images.githubusercontent.com/25884354/217759973-7887b121-6d2f-4620-b140-b0764e279f4b.png)

**Comment by deefrawley** [comment]
What is the use case for having the explorer plugin max results differ from all the other plugins?

![image](https://user-images.githubusercontent.com/18594055/217786854-13da153a-f669-4a50-a68c-fa2adfb25439.png)

**Comment by AETeK5** [comment]
Because it could cluter the results. So for example following priorities:

Program Priority: 3
Explorer Priority: 2
Web Searches Priority: 1

Maximum results shown: 10

The results of the Explorer Plugins are more than the general max results, which causes the web search result to be out of the shown results and therefore we would have to scroll down the results till the end to could use it. If we would be able to set the explorer results to be, for example, 5 this means the web search result would be still in the shown results.

![grafik](https://user-images.githubusercontent.com/25884354/217880443-0db25eac-261f-4d5b-99c6-b81c868e175d.png)

Hope the request makes sense.

**Comment by taooceros** [comment]
I think it's a good feature. The only thing we are concerned is how to sort the result. Simply by name?

**Comment by deefrawley** [comment]
> Hope the request makes sense.

Yep, thanks for clarifying and I agree with tao, it would be a good feature to have.

**Comment by AETeK5** [comment]
> I think it's a good feature. The only thing we are concerned is how to sort the result. Simply by name?

Isn't this already an option for everything searches to set the sort option?
![grafik](https://user-images.githubusercontent.com/25884354/218061903-e6c8d062-e089-4462-99d3-4febbbaca57c.png)
