### ISSUE TITLE
BUG: Everything service not running

### ISSUE THREAD

**Issue by jsasasaaaaa** [Flow-Launcher/Flow.Launcher#1893]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

When i search for things using FL, it says that Everything service is not running.
I've enabled Everything as my default search engine. It works fine with Window's Index. I also have Everything installed on my PC.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://user-images.githubusercontent.com/93920954/217828682-e4f1172c-2b9c-4586-83d3-c37c1c74e52e.png)
![image](https://user-images.githubusercontent.com/93920954/217828688-03886b63-7fee-4149-bd20-269060bfc09f.png)

### Flow Launcher Version

1.13

### Windows Build Number

10.0.19044.2486

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Is this option checked in Everything?

![image](https://user-images.githubusercontent.com/18594055/217831450-7ff3f962-2ddc-4e51-bf18-65b8ce2eaa2f.png)

**Comment by jsasasaaaaa** [comment]
yes it is

**Comment by taooceros** [comment]
Are you using everything 1.5?

**Comment by jsasasaaaaa** [comment]
yes 
![image](https://user-images.githubusercontent.com/93920954/218009290-88d83399-b55e-4030-a10c-23efa0b0da99.png)

**Comment by z1nc0r3** [comment]
Make sure that this is enabled in the UI tab.

![image](https://user-images.githubusercontent.com/64279853/218335430-3c82d6d7-66bb-4e6f-a14f-c97ac458c9ff.png)

**Comment by taooceros** [comment]
There's an issue talking about everything 1.5 #1716

**Comment by jsasasaaaaa** [comment]
> There's an issue talking about everything 1.5 #1716

Thank you, this worked and now Flow Launcher works with Everything
