### ISSUE TITLE
[Enhancement] 程序插件的文件夹结果排序

### ISSUE THREAD

**Issue by KJH-x** [Flow-Launcher/Flow.Launcher#1894]
**Is your feature request related to a problem? Please describe.**

我想要通过直接输入文件夹名称来打开我想要的文件夹：
观察到【程序】插件会按照名称排序，导致此Z1A的文件夹排名靠后，在文件夹结构复杂的时候，甚至有可能找不到我想要的这个文件夹。
如图当我输入Z1A的时候，我希望默认选项应该是Z1A本身而不是它的子文件夹。
![截图_20230210110756](https://user-images.githubusercontent.com/53437291/217990860-73b09e35-5277-4689-b45b-74cfb870e48b.png)
> I want to open the folder I want by directly typing the folder name:
> It is observed that the [Program] plug-in will be sorted the result by alphabetical order, resulting in the lower ranking of the Z1A folder. When the folder structure is complicated, it may even not be possible to find the folder I want.
> As shown in the picture, when I enter Z1A, I hope the default option should be Z1A itself instead of its subfolders.

**Describe the solution you'd like**

将everything返回的列表重新二级排序，第一层是路径长度排序，第二层是文件夹名称排序，这样就能快速且符合逻辑地找到我想要的文件夹。
> Re-sort the list returned by everything. Sort by path length first, then by name, so that I can quickly and logically find the folder I want.

**Describe alternatives you've considered**

或者将全字匹配的返回项作为默认项。
> Or simply make whole word match first

**Additional context**

...

**Comment by KJH-x** [comment]
> I think you are using everything to index filenames. I also have this issue.
> I noticed that v13.0 changed the default search option for everything. But I don't like the change. v12.1 works well for me, so I rolled back to v12.1.
> According to the syntax of everything, adding the prefix "nopath:" could solve this problem. But I hope that is the default option.
> So I hope the developers could add some options for everything Settings, and let users choose the default search options.

Glad to hear similar voice.
To be clear that I’m using this new plugin which I’m not sure its name in English. I’ve switched to this plugin according to the following advice.
![848AF123-611A-4932-8948-D5536F5AF434](https://user-images.githubusercontent.com/53437291/218124864-e5757f5b-3378-4009-a7fc-9da54f39eeb0.jpeg)
As for your advice to add a prefix, I tried but received the same index.
It’s not such an urgency to add some relevant settings but would be a great improvement to the experience.
Sorry for my poor English if there is any incomprehensible sentence.

**Comment by taooceros** [comment]
I will make an option for that.

**Comment by KJH-x** [comment]
Is this option included in the latest version of the program? I'm afraid I need some guidance.

**Comment by jjw24** [comment]
@KJH-x yes, if you go to Explorer's settings you should now see an option called 'Search Full Path', and should be off by default.
