### ISSUE TITLE
[Allow to select "only numbers" or input regex for action keywords]

### ISSUE THREAD

**Issue by ThinkSalat** [Flow-Launcher/Flow.Launcher#1905]
**Is your feature request related to a problem? Please describe.**

Or at least a limited version such as when a number is detected.

Somehow the calculator only triggers if a number is entered. I'd like the same to be true for the general conversion plugin as well, however when I set the actionkeyword to "*" it opens up like 10 menu items. For certain use plugins, it makes sense to only activate if it's a number. I'm sure regex would be helpful to some as well.

A simple way to do this would be to allow "only numbers" as an option when selection action keywords. But more advanced such as allowing regex could be helpful. 

 
![image](https://user-images.githubusercontent.com/31082405/218612998-e4e44807-e4ae-4f5f-8357-6a4364b07440.png)

**Describe the solution you'd like**

I'd like to select "numbers" or '\d+' as a keyword expression for plugins.

**Describe alternatives you've considered**

Simple alternative would be to allow a "numbers" or other  more simple things like that to be used as keywords instead of full on regular rexpressions. The calcluator already does this

**Comment by deefrawley** [comment]
Hi, I'm the author of the general converter plugin. To be honest I hadn't considered using it without a keyword but I changed it to '*' as you did and it seemed to work fine

![image](https://user-images.githubusercontent.com/18594055/218628963-08282479-9e7c-446b-8774-6e651ed44643.png)

The ten menu items are meant to assist and show you what can be converted but should only trigger when a keyword is used and entered. Not sure why you see it when keyword is set to none as I don't.

**Comment by ThinkSalat** [comment]
This is the issue I'm speaking of: you enter any input and it shows up and clutters all the other results

![image](https://user-images.githubusercontent.com/31082405/218637134-8d7acaa7-39b4-4ada-bc08-6640ccbaf40e.png)

**Comment by deefrawley** [comment]
Ah yes I see, that is a problem. I'll look at adding the helper text as a setting that can be disabled

**Comment by ThinkSalat** [comment]
Awesome. That would be quite helpful - I am wondering, and really the best solution IMO, would be if the plugin only activated if numbers were entered. Just the way the calculator only appears if you enter numbers. Is there any reason that General Conversion plugin would take an amount that isn't a number? Can the plugin handle that or is that in the domain for Flow Launcher itself?
