### ISSUE TITLE
V 1.13.0 not searching desktop by default 

### ISSUE THREAD

**Issue by 3lsheikh** [Flow-Launcher/Flow.Launcher#1907]
I have a desktop folder with lots of shortcuts on it , starting with this version it can't search the desktop items

**Comment by z1nc0r3** [comment]
Can you describe your issue more specifically? Application shortcuts or File/Folder shortcuts?

**Comment by 3lsheikh** [comment]
Application shortcuts

**Comment by deefrawley** [comment]
Are you using Windows Index or Everything in the Explorer plugin?

**Comment by 3lsheikh** [comment]
Thank you all I Solve my problem by adding my shortcuts folder to the Program plugin 
![Screenshot 2023-02-15 132230](https://user-images.githubusercontent.com/1766430/219014576-d340defe-1214-432b-b481-50b5b68535c3.png)
