### ISSUE TITLE
Feature: Making "everything" path matching optional or new sorting options

### ISSUE THREAD

**Issue by alvinccli** [Flow-Launcher/Flow.Launcher#1911]
The version v1.13.0 added support for everything to also match the path of any files.
I definitely see the usefulness of this and thanks the update.

I just wanted to offer my personal feedback that I found that this change often counterproductive in my specific use case.
I often directly type in full name of the folders (e.g. "folder1") to have the folder open for work. If I look for files in that folder, I could also navigate into and search or directly search for "folder1\file1".

After the recent update where the search match any section of the full path of any files, when I search just the folder the matched list is 10x longer. My desired folder destination is way down in the middle regardless of which sorting option I choose. (There seems to be no way to make folders ranked top. If there is, please let me know I just missed that).

To my use case, it would be nice to either
- make path matching optional, or
- have a way to simply prioritize folder before files, or
- have a way to rank closest match to the file/folder name first. (To me it is more important to match the very last part of the full path instead of some middle keywords of the full path.)

Just my two cents. Maybe my use case is a little particular. It could also just me missing a way to do the above and in this case please let me know.

**Comment by z1nc0r3** [comment]
Thank you for the suggestion. This is already considered in #1899.
Closing this issue. Please feel free to reopen if you have any changes.
