### ISSUE TITLE
Unable to search files other than hard disk, such as SD card, network driver. Can the file content search engine be changed to a custom one and replaced by a more appropriate search engine

### ISSUE THREAD

**Issue by lanpeng1612** [Flow-Launcher/Flow.Launcher#1912]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lanpeng1612** [comment]
Unable to search files other than hard disk, such as SD card, network driver. Can the file content search engine be changed to a custom one and replaced by a more appropriate search engine

**Comment by z1nc0r3** [comment]
It totally depends on the search/index engine.
Yes, you can change the default search engine. Please go to  `Settings > Plugin > Explorer Plugin`.

![image](https://user-images.githubusercontent.com/64279853/219113447-e8e87bb4-32cc-4e5c-894f-5cce5f824179.png)

And if you use **Everything** as the search engine, there is an option to enable indexing for _removable media_.

![image](https://user-images.githubusercontent.com/64279853/219114023-7206fbdb-8d15-48cc-86c7-b5e9c365d469.png)

**Comment by deefrawley** [comment]
I think this one has been answered so closing
