### ISSUE TITLE
Open Folders in existing file manager window

### ISSUE THREAD

**Issue by onesounds** [Flow-Launcher/Flow.Launcher#1915]
## What's the Issue

- When opening a folder in Flow launcher with a file manager window already opened, there is no option to open the location in the existing file manager window. some people need the open folder with exist file manager window.

![image](https://user-images.githubusercontent.com/6903107/219267385-43b32ba5-a4d3-4df8-8c6d-1b138ce4f614.png)

## Other informations
- Everything, Power toy run defaults to this behavior, and Fluent Search has an on/off setting for this feature.
- Most other third-party managers can do this with arguments in flow launcher, but not explorer.
- I tested fluent search and it works with other file managers if this option is on, regardless of the arguments.

- I looked it up, and it looks like I need to implement the behavior with something other than arguments. (process.verb?) I tested a few things and looked for the code, but it's impossible with my ability, so I leave it as an issue.

@taooceros @VictoriousRaptor

**Comment by deefrawley** [comment]
Requested here - https://www.reddit.com/r/FlowLauncher/comments/123q5vq/how_to_open_folder_result_in_the_current_file/

**Comment by VictoriousRaptor** [comment]
Alternative solution provided in https://github.com/Flow-Launcher/Flow.Launcher/discussions/2680#discussioncomment-9291169
