### ISSUE TITLE
BUG: Flow Launcher keeps acting weird after I've installed Avast Anti-Virus software

### ISSUE THREAD

**Issue by postlemons** [Flow-Launcher/Flow.Launcher#1918]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

Greetings, hope you're having a good day!
My issue is whenever I hibernate or use the system normally during these days (after getting Avast), flow launcher either randomly crashes showing an error or just gets terminated silently.

I've tried to do a clean install yesterday with the .exe installer, at first it kept giving me errors saying that the access to a specific file (core files 'n some other files at "C:\Users\$USER$\AppData\Local\FlowLauncher\app-1.13.0") is/are denied, when I stopped the Avast Core Shield (from settings), the installation went normally as usual with no errors
yesterday, it crashed again on its own (not sure before hibernation process or during it), I've attached the logs for the crash down below
last thing, I've noticed that since I set flow launcher to replace the Shell run shortcut (winkey + R), it started to spam me (shows 5 crash windows at once) with random crash errors for the app (lost logs due to the fresh install)

Extra Details-
- Neither tray icon nor task manager shows any signs of life for the app after waking the windows up
- Tried re-installing the app after deleting all the files manually

### To Reproduce

1- Installing Avast Anti-virus software
2- Enabling the replace shell run shortcut
3- Hibernating the system for +5 hours instead of shutting it down (I do that almost all the time)
4- waking it up 'n trying to trigger the shortcut

### Flow Launcher Version

1.13.0

### Windows Build Number

10.0.19045.2604

### Error Log

<details>

[2023-02-16.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10768532/2023-02-16.txt) - The logs for yesterday's crash

</details>

**Comment by Garulf** [comment]
Hello @itsmohamed205 thank you for reporting your issue. In order to help you could you please link your Flow Launcher logs?

If installed they should be located in the logs folder inside the FlowLauncher folder:
`%AppData%\FlowLauncher`

**Comment by Garulf** [comment]
You meantioned using Anti-Virus and a sudden onset of issues. Can you check to see if your anti virus is flagging Flow Launcher?
