### ISSUE TITLE
BUG: Additional problems with the newest Everything / Explorer plugin change.

### ISSUE THREAD

**Issue by Sneakpeakcss** [Flow-Launcher/Flow.Launcher#1921]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

The newest addition creates [problematic behaviour](https://github.com/Flow-Launcher/Flow.Launcher/issues/1894) by completely flooding the limited results with unrelated folders in certain scenarios, and also creates additional bug that will persist for everyone that will be using this change.

For example in my case previously searching for **ffmpeg** using only `ffm` already provided good results, but now doing the same shows a somewhat "matching" Firefox cache folder that floods the results to the point where i cannot even use **"Set at topmost in this query"** option since the file doesn't display because it got pushed beyond the limit (100?).

![ResultsFlooding](https://user-images.githubusercontent.com/77424331/219895961-91bdbc82-02bc-4c5b-a874-730a851af586.png)

Going one letter deeper in search input `ffmp` provides similar good results as before, but if it happens that there's another folder with similar structure the same will happen here, so this is even more problematic since it can randomly affect any search input making it completely unusuable. 

For example:
![ProblematicFolderStructure2](https://user-images.githubusercontent.com/77424331/219896090-309d8009-0c6b-4a89-8b4c-9c6db25f7068.png)

There's a possibility to use **"Index Search Excluded Paths"** option, but it's a terrible way of dealing with this because you need to do it by hand every time you find a problematic result. In case of searching for often used files you could use **"Quick Access Links"**, but in my case with addition of "**Index Search Excluded Paths**" something weird happens…

When the folders containing 100s of flooding sub-folders are excluded (using "**Index Search Excluded Paths**") the search query that was previously flooded (`ffm`) doesn't display anything at all, it's simply empty at that point, where you would hope that it would fetch results beyond the ones that were filtered. 

And now the amusing part:

Since the results are empty let's try using the build-in button to add our file to **Quick Access Links**… 

_You can't…_ It only allows to add folders and not individual files, so after doing exactly that the previously empty search query finally shows something, and in this example(`ffm`) we can now add ffmpeg by navigating through the folder and adding ffmpeg.**exe** from the context menu to **Quick Access Links** so it properly shows in a now bugged empty `ffm` as the only result.

### To Reproduce

1. Either find or create a folder with 100+ subfolders that in part shares the name as your search input.
2. Try searching for your file using the mentioned shared part.
3. Add the created folder to the **Index Search Excluded Paths**.
4. Search for your file again using the same part of the name.
5. Add your searched file to **Quick Access Links** using 'Add' button in Explorer's plugin settings.
6. Search for your file again using the same part of the name

### Screenshots

https://user-images.githubusercontent.com/77424331/219899743-01fcc9b9-d1f7-4439-ae0b-efd9a7ab2ea2.mp4

`

As a btw, while the Everything Plugin didn't follow the same behaviour as Explorer when navigating into a directory, the option of instantly opening the folder rather than using ctrl + enter _(or clicking 2 times into nested "Open in Default File Manager")_ was very convinient so it would be nice if that option also came back in future updates.

_++ On the Video it also shows that the last query is still remembered after adding **Quick Access Links** from context menu, even when "Empty Last Query" is selected in options, which feels a little bit wrong._ 

### Flow Launcher Version

1.13.0

### Windows Build Number

10.0.19044.1826

### Error Log

[2023-02-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10775217/2023-02-18.txt)

**Comment by Da3n0n** [comment]
use " .  " before your file extennsion for finding that file type

**Comment by Da3n0n** [comment]
so, in flow launcher type " .ffmpeg " and they should show.
