### ISSUE TITLE
BUG: Files app as default file manager invalid search argument

### ISSUE THREAD

**Issue by Beszamel** [Flow-Launcher/Flow.Launcher#1922]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

When trying to search for a folder through Flow Launcher, if Files is set as defualt files manager, path to the folder is preceded by „Files” as shown in screenshots attached below.

### To Reproduce

1. Set Files as default files manager
2. Search for a directory through Flow Launcher
3. Get an error saying: Did you delete this folder?

### Screenshots

![Files_sv4VsdwIR6](https://user-images.githubusercontent.com/120752248/219948856-b87b9527-67f1-4bc5-a260-41481dd895fe.png)
![Files_ftsnuiygi2](https://user-images.githubusercontent.com/120752248/219948857-88eba0e9-0c91-4dcb-81a6-647dfdaac857.png)

### Flow Launcher Version

1.13

### Windows Build Number

10.0.19045.2604

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by enoversum** [comment]
Same here. If I just pick the profile and want to open a folder (e.g. o:\downloads), I'm getting back the wrong path for Files, which is `"Files" -select "o:\downloads"` instead of just `o:\downloads`.

![Files_X0SgWTpQXY](https://user-images.githubusercontent.com/8190174/220593242-5178e5c1-cb86-491e-8481-5c3f0f7a6379.jpg)
![Files_mjEf6aPZeT](https://user-images.githubusercontent.com/8190174/220593264-36527a56-d5fb-4418-9d34-195feae50cb4.jpg)

**Comment by enoversum** [comment]
@Beszamel 
Update: When just using the preset "Files" from the file explorer list, Files opens, but has "Files" (in double quotes) plus the arguments in the path name, thus is failing. If I _manually_ set the path to the `Files.exe` from its installation folder, arguments are working and Files successfully opens my desired folder. While this is fine for a one-computer default usage of Flowlauncher, using a portable installation (like me) would lead to the .exe not being found on other computers, i.e. different folder that is being created by the Windows Store app on those other computers.

**Comment by enoversum** [comment]
Update II: While this is working as described above, instead of the actual folder, Files opens the parent folder, not the actual folder. This is different with the regular Explorer.
