### ISSUE TITLE
Plugin Program - open containing folder in custom file explorer

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#193]
I don't use Windows Explorer. I would like to open containing folder in Total Commander. Plugin Everything works like a charm.

Can you implement this feature?

**Comment by taooceros** [comment]
Which plugin are you using? Everything or the Explorer plugin?

**Comment by kubalav** [comment]
I mean Program plugin. Everything plugin works with folders (single click), but not with Open parent folder (right click on item).
Program plugin doesn't work to open containing folder (right click on item).

**Comment by taooceros** [comment]
Got it, and I will try to implement that soon. Thank you for the suggestion.

**Comment by jjw24** [comment]
Hi @kubalav could you please test this build to see if it is as intended: https://ci.appveyor.com/api/buildjobs/2dcxc0jwdsg7x2ta/artifacts/Output%2FPackages%2FFlow-Launcher-v1.3.1.zip

**Comment by kubalav** [comment]
I entered path to the Total Commander executable and it is works. It opens new instance of Total Commander.
Can you adjust it to open in existing instance?

**Comment by taooceros** [comment]
Check out here http://www.ghisler.ch/wiki/index.php/Command_line_parameters. Take a try on add /O to the path? If that doesn't work, I will create another textbox to allow adding customized arguments.

**Comment by kubalav** [comment]
It unable to start with `"C:\Program Files\Total Commander\TOTALCMD64.EXE" /O`

**Comment by taooceros** [comment]
OK, I will add another textbox to do the job. Thank you for testing!

**Comment by taooceros** [comment]
@kubalav take a try on this one. [](https://ci.appveyor.com/api/buildjobs/dr2p3y5na9mubina/artifacts/Output%2FPackages%2FFlow-Launcher-v1.3.1.zip).
I don't have an explorer that is useful with arguments, so I am not sure whether this works. But I have tested it with explorer and it seems works.

**Comment by kubalav** [comment]
Wow! It's working. Thank you!

Can you make it for Everything plugin too?

**Comment by taooceros** [comment]
Sure, I will do that tomorrow.

**Comment by taooceros** [comment]
Just to make sure, are you using the everything plugin, which is built in on wox, or the explorer plugin, which is built-in on Flow.

**Comment by kubalav** [comment]
From Wox.

**Comment by taooceros** [comment]
ok

**Comment by taooceros** [comment]
Sorry for being troublesome, would you please tell me which version of everything plugin is you using so that I can fork the right repository, since everything plugin is not built in with the main repository of Flow.

**Comment by kubalav** [comment]
I use this version: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/releases
v1.1.0

**Comment by taooceros** [comment]
[Flow.Launcher.Plugin.Everything.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/5492131/Flow.Launcher.Plugin.Everything.zip)
@kubalav Take a try.

**Comment by kubalav** [comment]
It's working partially. Opening file parent folder works. Folders opens in Explorer.exe. (Single click to result folder)

**Comment by taooceros** [comment]
> Everything plugin works with folders (single click), but not with Open parent folder (right click on item).

Oh from the quote I think the everything plugin already work for single click, so I only change the part for the parent folder. I will implement that, too.

**Comment by taooceros** [comment]
[Flow.Launcher.Plugin.Everything.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/5493723/Flow.Launcher.Plugin.Everything.zip)
@kubalav Take a try.

**Comment by kubalav** [comment]
@taooceros Working as expected!

╰(*°▽°*)╯

**Comment by kubalav** [comment]
Everything plugin have problem opening folder containing space. It opens path without space.
E.g.:
"C:\Users\Vlado\AppData\Roaming\7+ Taskbar Tweaker\"
it opens
"C:\Users\Vlado\AppData\Roaming\"

**Comment by taooceros** [comment]
I think it may due to that I didn't add another "" for the path in the location, I will fix that, tomorrow. Thank you for pointing out the issue.

**Comment by taooceros** [comment]
[Flow.Launcher.Plugin.Everything.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/5505103/Flow.Launcher.Plugin.Everything.zip)
I have added the fix, but don't have time to tested it. You can take a try on it.

**Comment by kubalav** [comment]
It is fixed now. Thanks a lot.

**Comment by taooceros** [comment]
Good to hear!
