### ISSUE TITLE
BUG: Everything File Indexer Not working

### ISSUE THREAD

**Issue by Gaaruda** [Flow-Launcher/Flow.Launcher#1937]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I installed Flow launcher today only.
I changed my defaults for explorer to Everything, but it seems that it is not utilizing the everything search index
My settings are as follows
![image](https://user-images.githubusercontent.com/80031164/221397921-b2a82309-6ea3-4249-8d70-8f6e65a639aa.png)
![image](https://user-images.githubusercontent.com/80031164/221397935-9282421d-ad16-4458-a347-b774bf478732.png)

### Flow Launcher Version

1.13.0

### Windows Build Number

Microsoft Windows [Version 10.0.19045.2604]

### Error Log

[2023-02-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10833211/2023-02-26.txt)

**Comment by jjw24** [comment]
What happens when you start typing afterwards?

**Comment by Gaaruda** [comment]
It shows it is loading but nothing comes up, also when I see task manager everything starts consuming more resources.But when I search using keyphria everything works normallySent from my Galaxy
-------- Original message --------From: Jeremy Wu ***@***.***> Date: 26/02/2023  1:14 pm  (GMT+05:30) To: "Flow-Launcher/Flow.Launcher" ***@***.***> Cc: Garuda ***@***.***>, Author ***@***.***> Subject: Re: [Flow-Launcher/Flow.Launcher] BUG: Everything File Indexer Not working (Issue #1937) 
What happens when you start typing afterwards?

**Comment by jjw24** [comment]
Squats the version of Everything you are using?

**Comment by Gaaruda** [comment]
Version 1.4.1.1009 (x64)

**Comment by Gaaruda** [comment]
> Hmm, what's the version of Everything you are using?

Updated to Latest version

**Comment by Gaaruda** [comment]
@jjw24 I think I figured out the bug after searching using doc: If we try to search for file then it does not shows any result

**Comment by jjw24** [comment]
Yeah, when you selected Everything for Content Search you should have gotten something like this:
![image](https://user-images.githubusercontent.com/26427004/221434413-73600bb8-05ab-4084-b0e8-77780b1ecd94.png)

So recommended is to stick with Window Search. You can switch to Everything v1.5+ by following this workaround https://github.com/Flow-Launcher/Flow.Launcher/issues/1716

**Comment by oliviercarizzoni** [comment]
I have same issue, and windows search is not working as well for me though indexer is configured and ready

**Comment by deefrawley** [comment]
Hi @oliviercarizzoni , if you have the same issue the same fix/workaround should work for you. If not, please open a new issue and we will investigate.
