### ISSUE TITLE
[Issue] No sound with corresponding setting enabled

### ISSUE THREAD

**Issue by LinguaOccultus** [Flow-Launcher/Flow.Launcher#1944]
Hello!

I have set the sound setting under design to enabled, but it does not make any sound as intended. I can reproduce this on at least three systems (Windows 11 Pro 22H2) and the only audio issues on all three systems are those with Flow Launcher.

However, I lately installed this for a friend on his system and suddenly the sound worked on that fourth system.

I am very technically experienced but I cannot find the problem. Any idea what I could try? I also tested around with all the audio settings on Windows, but nothing changed.

Greetings!

**Comment by onesounds** [comment]
There's nothing special about the code that plays the sound - it's just normal sound playback code. Are the devices you were having trouble with all using the same speakers? Depending on the speaker, you may not be able to hear the sound. Try replacing the sound file (there is a wav file inside the flow folder).  I purposely chose file with low volume, so you may not be able to hear them in some situations.

**Comment by LinguaOccultus** [comment]
I thought so, too. But still haven't found the cause and it is the only application not playing sounds — and on different systems, also!

No, I tested on two desktops with different surround sound speakers and also on headsets. My notebook only has the internal ones but I used external ones connected by Bluetooth. All the same.

I am using FXSound, which is an audio enhancement installed as a driver and virtual sound device and I set to the default device instead of the normal speakers and I thought, this is the cause (while still working fine with everything else) but it still fails without.

I found the file »open.wav« on the path »C:\Users\USER\AppData\Local\FlowLauncher\app-1.13.0\Resources« which seems to be the sound file you mentioned. However, I can play it normally and hear it also (it is a soft clicking sound). Still not, when I open Flow Launcher, where it is intended to.

I changed the shortcut to Strg + Space instead of the default and just a few details in the settings and reinstalled Windows and everything on a desktop and the notebook but still ... :-D

Seems like a really strange one this time ...

**Comment by traintochromacity** [comment]
I have the same problem on win10

**Comment by onesounds** [comment]
I'll look into this a bit more, and once I've tweaked the code for sound output, I'll share a separate build for testing.

**Comment by LinguaOccultus** [comment]
Thanks for the effort!

I'd like to give a bit better information but at the moment I cannot think of anything else to test. If you need something, just tell me. I'll be glad to test new builds also and give feedback on them. It's a quite strange issue and as i said I am normally able to find issues and solutions on my own. But in this case it seems this really is something on Flow Launcher side; at least somehow.

But when I am now officially not the only one affect ... keep me updated on this! :-)

**Comment by onesounds** [comment]
https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/46407389/artifacts

@traintochromacity @LinguaOccultus 
Please get this build and see if it resolves your issue. I've fixed the suspected issue.

**Comment by LinguaOccultus** [comment]
> https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/46407389/artifacts
> 
> @traintochromacity @LinguaOccultus Please get this build and see if it resolves your issue. I've fixed the suspected issue.

Hooray! :-) Just downloaded you 1.14.0.7032 build using the installer version and just installed it on top of the existing one on my notebook and it immediately worked! I had the sound still enabled anyway and when i opened Flow Launcher via shortcut, I did the sound this time. It seems a bit delayed sometimes, but that might be the notebooks fault. Will test on the desktops also to see the results there.

That was a REALLY quick fix! :-D Let's see if @traintochromacity can also confirm that it works on his end ... I guess, it will then be included in the next official build, right?

**Comment by onesounds** [comment]
> > [ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/46407389/artifacts](https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/46407389/artifacts)
> > @traintochromacity @LinguaOccultus Please get this build and see if it resolves your issue. I've fixed the suspected issue.
> 
> Hooray! :-) Just downloaded you 1.14.0.7032 build using the installer version and just installed it on top of the existing one on my notebook and it immediately worked! I had the sound still enabled anyway and when i opened Flow Launcher via shortcut, I did the sound this time. It seems a bit delayed sometimes, but that might be the notebooks fault. Will test on the desktops also to see the results there.
> 
> That was a REALLY quick fix! :-D Let's see if @traintochromacity can also confirm that it works on his end ... I guess, it will then be included in the next official build, right?

Yes, it will be included in the next build unless there are any particular issues.

**Comment by traintochromacity** [comment]
Yes, working for me as well. Great stuff!
