### ISSUE TITLE
Typo in Readme Screenshot

### ISSUE THREAD

**Issue by tdnzr** [Flow-Launcher/Flow.Launcher#1946]
In the [main readme](https://github.com/Flow-Launcher/Flow.Launcher), in the section [Web Searches & URLs](https://github.com/Flow-Launcher/Flow.Launcher#web-searches--urls), the screenshot of the search for wikipedia.com currently has a typo and reads "wikpedia.com". (Side note: the canonical Wikipedia URL is wikipedia.org, not .com.)

**Comment by onesounds** [comment]
Fixed in https://github.com/Flow-Launcher/Flow.Launcher/pull/1954.
Thanks.
