### ISSUE TITLE
Change Explorer plugin's default behavior for "Enter" key on folders

### ISSUE THREAD

**Issue by luopa** [Flow-Launcher/Flow.Launcher#1957]
**Is your feature request related to a problem? Please describe.**

- Search for a folder (via explorer plugin)
- Hit _Enter_ and flowlauncher 'browses' into the folder, offering the options "Open in default file manager" and all the subfolders present.

I perceive this behavior to be counterintuitive: my expected default Enter-Key action on a folder would be to open the folder rightaway. (Similarly like files or apps are executed rightaway, or bookmarks are opened rightaway).

Moreover, the current behavior is redundant: Hitting _Tab_ produces the exact same effect as hitting _Enter_. 
However, _Tab_ seems perfectly intuitive to me in this regard - in line with the autocomplete behavior across other plugins and also in-line with the behavior of various commandlines and editors.

**Describe the solution you'd like**

Change the default behavior of Enter-Key for folders to open the folder right away. 
Leave behavior of Tab-Key unchanged.

**Describe alternatives you've considered**

Add an option to the explorer plugin, offering users a choice on the behavior of Enter-key, eg:

_Default Enter-Key behavior for folders:_
[ ] Hit _Enter_ to open folder in Default File Manager
[ ] Hit _Enter_ to autocomplete Folder Name and present subfolders

**Additional context**

The flow.launcher global option "Open Results Modifier Key" is also somehow related, as it indeed does directly open the folder (but with an additional key - obviously).

**Comment by onesounds** [comment]
@Flow-Launcher/team 
- If I remember correctly, this is how it used to work. Or is it not?
- If not, this is the correct behavior. This needs to be worked on.

**Comment by taooceros** [comment]
> @Flow-Launcher/team 
> 
> - If I remember correctly, this is how it used to work. Or is it not?
> 
> - If not, this is the correct behavior. This needs to be worked on.

Yes it is how it used to work

**Comment by TheBestPessimist** [comment]
I can piggyback this in https://github.com/Flow-Launcher/Flow.Launcher/pull/1950 if allowed

**Comment by jjw24** [comment]
> It was the behavior of the old Everything plugin.

Yes correct, enter for Explorer plugin has always been used to browse into the folder and for Everything plugin has been used to open the folder directly.

I personally have found Everything's opening folder directly with enter annoying and I know there has been a request to allow Everything the ability to also browse into the folder tree, iirc that request triggered the merge of both plugins so to align code and behaviour.

Best solution for this is to add an option in Explorer's settings to change the behaviour of enter key press either browse into folder or open directly.
