### ISSUE TITLE
BUG: The kill plugin shows old list when flow launcher is reactivated.

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1963]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

When you kill a process and activate flow launcher again, the old process list is displayed including the process that had been killed.
To  get the updated list, you have to retype the kill command and repopulate the list.

It would be good UX if the process list repopulated itself on reactivation.

### To Reproduce

1. Kill a process
2. Activate flow launcher again

### Flow Launcher Version

1.14.0

### Windows Build Number

10.0.22621.1344

**Comment by jjw24** [comment]
This should be able to be resolved by adding an additional call to re-query via API after the kill execution.
