### ISSUE TITLE
[FEATURE REQUEST] Update Process Killer plugin to kill all named instances of a process

### ISSUE THREAD

**Issue by fischgeek** [Flow-Launcher/Flow.Launcher#1968]
**Is your feature request related to a problem? Please describe.**

Currently the Process Killer plugin only lets you kill 1 process at a time. For example, I can't just kill teams I have to kill all the processes that make up teams.exe. Which is usually like 10. Where as, pskill does all of them. 

**Describe the solution you'd like**

Process Kill should kill all running processes that match the exe selected.

**Describe alternatives you've considered**

Not using this plugin and continuing to use pskill from the run line.

**Comment by deefrawley** [comment]
Hi @fischgeek . I've update the issue title to be a little more descriptive but I understand what you are after. Will let one of the plugin devs respond as to best way to acheive this

**Comment by fischgeek** [comment]
Not sure how I missed it or if an update was deployed, but I now see the option to "kill all instances of" at the top of the list. Thank you!
