### ISSUE TITLE
Can we get an "Primary Monitor" option in the Search Window Position options?

### ISSUE THREAD

**Issue by fischgeek** [Flow-Launcher/Flow.Launcher#1969]
**Is your feature request related to a problem? Please describe.**

I would like to always have the search pop-up on my primary monitor regardless of my mouse.

**Describe the solution you'd like**

I would like to always have the search pop-up on my primary monitor regardless of my mouse.

**Describe alternatives you've considered**

I currently use AutoHotkey to force the position.

**Additional context**

![image](https://user-images.githubusercontent.com/4293840/224101814-c9b2a88a-0472-457f-b8d5-75d344a654b1.png)

**Comment by deefrawley** [comment]
If your primary monitor doesn't change, then use Remember Last Position and it should always appear where you first trigger it.

**Comment by fischgeek** [comment]
Sure. I get it. Not an obvious solution (though it should've been). I do wonder if it wouldn't be more clear if this option was added regardless?

**Comment by onesounds** [comment]
I had an implementation plan. The "Primary" setting is implementable. 
but I haven't implemented it yet because 2nd and 3rd are problematic.
I will try to implement it.

**Comment by onesounds** [comment]
![primary2](https://user-images.githubusercontent.com/6903107/224604334-a67a1409-b9fa-4a45-883a-734688cd01a3.gif)

@fischgeek You can get a build for testing below. Give it a try and let us know if it works for you
https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/46481098/artifacts
