### ISSUE TITLE
Upgrade to .Net 5

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#197]
.Net 5 has released. Should we upgrade the project to .Net 5?

**Comment by jjw24** [comment]
yep we should, but the main [goal](https://github.com/Flow-Launcher/Flow.Launcher/projects) at the moment is to fix up and improve the plugin model, and address the high memory/cpu issue https://github.com/Flow-Launcher/Flow.Launcher/issues/128

**Comment by taooceros** [comment]
Yes, I have taken a try on updating, not too hard to do the job except changing part of the configuration file for browser bookmark and websearch, and updating the modernwpf package.

**Comment by jjw24** [comment]
yeah cool. I meant feel free to work on which ever enhancements you like, just for myself though I will be give time priority to those above main area of focuses.

**Comment by taooceros** [comment]
Yes sure, of course we should spend more time on the more important things. Just to mark a potential future improvement.
