### ISSUE TITLE
Unable to initialize WoxDictionary Plugin (dev branch)

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#198]
**Describe the bug/issue**
After updating the new plugin dependency update, I am unable to initialize the WoxDictionary plugin.

**Flow Launcher Error Log**
![image](https://user-images.githubusercontent.com/45326534/99021962-c4188800-259c-11eb-94bb-a907d7d9f0be.png)

**Comment by jjw24** [comment]
You are using the Dev branch I see. The plugins need to have project attribute to output all assemblies files. I will fix that up for all exported plugins tonight

**Comment by taooceros** [comment]
Thank you!

**Comment by jjw24** [comment]
All done :) https://github.com/jjw24/WoxDictionary/releases/tag/v2.0.1

**Comment by taooceros** [comment]
Thanks!
