### ISSUE TITLE
[FEATURE REQUEST] Personalized search in Spotify plugin

### ISSUE THREAD

**Issue by nikolicpetar17** [Flow-Launcher/Flow.Launcher#1981]
When I search for song on spotify it almost always shows up first but when I search for the same song on plugin it shows way below.

**Comment by deefrawley** [comment]
@nikolicpetar17  The Spotify plugin isn't part of the core Flow app. Can you post this in the author's repo:

https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
