### ISSUE TITLE
Default plugins installable from Plugin Store

### ISSUE THREAD

**Issue by fourteen-1** [Flow-Launcher/Flow.Launcher#1984]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I uninstalled Explorer because it kept crashing so i could reinstall it from the store but turns out its not in the store probably because it in an internal plugin??? (then why can i uninstall it??) Now I can't reinstall it. How do I fix this???

### To Reproduce

1. Uninstall Explorer Plugin
2. Can't install it back
3. ???
4. ~~Profit~~ _loss_

### Flow Launcher Version

1.14.0

### Windows Build Number

10.0.19044.2604]

**Comment by taooceros** [comment]
You would have to reinstall flow, because it is a built in plugin that is not Available in the store. If you are not using portable mode, this will preserve your data.

**Comment by fourteen-1** [comment]
It would be really useful to add an option to "reset" the internal plugins data to replace the "uninstall" option to hopefully deal with unexpected crashes.

**Comment by jjw24** [comment]
We can block or we can try use the CI to actually publish the internal plugins to the store during release.

I think keeping the behaviour consistent is probably better? So that users are freely to uninstall/install all plugins including the internal (default) ones.

**Comment by jjw24** [comment]
Hmm that adds extra logic to the UI and code behind to grey out an uninstalled plugin, I think using the CI to publish these plugins out to their individual repos might be simpler in that the heavy lifting is done by the CICD and you get the same behaviour as other plugins where uninstalling them will actually removing the plugin (except the plugin settings data) and they can be reinstalled via plugins store.
