### ISSUE TITLE
[SUGGESTION] Extend sound on typing when using Flow Launcher

### ISSUE THREAD

**Issue by LinguaOccultus** [Flow-Launcher/Flow.Launcher#1991]
After we analysed and fixed #1944 that fast and the sound implementation seems not to be that problematic oder complex, can we have an option for extending the sound on typing also? I mean, we currently have that »click« sound for opening Flow Launcher, but I would find it nice when the same sound was extended (optionally also, of course) on each key press when typing into the Flow Launcher dialogue. This can be seen already in the Opera GX browser which also has a really similar sound played when typing.

This, of course, is just a cosmetic feature, but also could help as a auditive feedback; example for typing blind etc. Also, I do like the sound and it is a very nice experience (just try a portable Opera GX installation). I am not really into uneccessary knick-knack, but this is a subtle one which makes sense in an application all about typing, right? We also would not necessarily need theming, but it makes the application more pleasing, also, right? And on top of that: we already do have the sound and playback, it just must be a bit expanded to each keypress ... sounds not too complicated to me and like resonable effort.

Just a thought ... (and when made optional; no ones »hurt« :-D )

**Comment by nikolicpetar17** [comment]
It would be even better if you could be able to change volume of sound

**Comment by jjw24** [comment]
Hi there, thank you for the suggestion. 

Playing sound by capturing each keystroke is unfortunately is not easily implemented. Additional concerns also include https://github.com/Flow-Launcher/Flow.Launcher/issues/1402#issuecomment-1256845013. 

We won't be proceeding with this feature request.

This is a dup of #1402
