### ISSUE TITLE
Support %appdata% in Folder plugin

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#20]
As an example, I type I %appdata% Folder plugin will switch that text to the appdata director + \\ so i can continue to type the folder I want to go to:
Type %appdata%\Microsot it will change the text to c:\users\blahuser\appdata\microsoft\

**Comment by SysC0mp** [comment]
We could add that in a way to work with all the currently existing environment variables on the system.

**Comment by jjw24** [comment]
> We could add that in a way to work with all the currently existing environment variables on the system. 

Hey, can you expand a bit on what you mean?

**Comment by duurland** [comment]
> Hey, can you expand a bit on what you mean?

Beside `%appdata%` it would be nice if it supported other environment variables too.

- `%localappdata%`
- `%temp%`
- `%username%`
- etc..

Run `set` in windows command prompt for a list.

**Comment by jjw24** [comment]
> > Hey, can you expand a bit on what you mean?
> 
> Beside `%appdata%` it would be nice if it supported other environment variables too.
> 
> - `%localappdata%`
> - `%temp%`
> - `%username%`
> - etc..
> 
> Run `set` from `cmd` for a list.

Will be great if we can do that. I know you can do it with appdata and localappdata. Haven't checked others yet.

**Comment by JohnTheGr8** [comment]
I can tackle this tomorrow if nobody's working on it already...

**Comment by JohnTheGr8** [comment]
Done in #32
