### ISSUE TITLE
Everything plugin error after update

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#200]
After FlowLauncher update to 1.4.0 version, Everything (1.1.0 and 1.1.1 version) plugin throw error:

> Object reference not set to an instance of an object.
>    at Flow.Launcher.Infrastructure.StringMatcher.FuzzySearch(String query, String stringToCompare)
>    at Flow.Launcher.Plugin.Everything.Main.CreateResult(String keyword, SearchResult searchResult) in C:\Workbench\Git\delete\Flow.Launcher.Plugin.Everything\Main.cs:line 95
>    at Flow.Launcher.Plugin.Everything.Main.Query(Query query) in C:\Workbench\Git\delete\Flow.Launcher.Plugin.Everything\Main.cs:line 54

**Comment by taooceros** [comment]
This is because of the plugin depency update. @jjw24 please take a look to fix that.

**Comment by jjw24** [comment]
Hey @kubalav how's it going.

It is resolved. Try the latest release of Everything with Flow 1.4.0: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/releases/latest

**Comment by kubalav** [comment]
It is working now! Don't forget to increase version number to 1.1.2 in plugin.json

**Comment by jjw24** [comment]
> It is working now! Don't forget to increase version number to 1.1.2 in plugin.json

Yeah it shud already be done with the fix

**Comment by kubalav** [comment]
Try to download the latest version and see version, you will see 1.1.1

**Comment by jjw24** [comment]
> Try to download the latest version and see version, you will see 1.1.1

Oh ok, must have packed the previous commit, I will fix that up. Thank you for letting me know.
