### ISSUE TITLE
BUG: i can't open system programs (error)

### ISSUE THREAD

**Issue by Martelokk** [Flow-Launcher/Flow.Launcher#2002]
### Check New Issue

- [ ] I have checked that this issue has not already been reported.

### Check Latest Version

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

i just can't open programs file, and i dont know why

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![Captura de tela 2023-03-23 133332](https://user-images.githubusercontent.com/128729585/227272279-f8b8ec0a-5c98-4be4-a79a-cc2ca7a3e13f.png)

### Flow Launcher Version

1.14.0

### Windows Build Number

10.0.22621.1413

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi. Please follow the issue template and let us know the exact steps you do before getting that error.
