### ISSUE TITLE
Make it easier to add a custom theme

### ISSUE THREAD

**Issue by giggio** [Flow-Launcher/Flow.Launcher#201]
**Describe the solution you'd like**

Currently the theme settings tab already has a link to "Browse for more themes" and that is super useful. But it is not clear where to put the theme you created.

I found out reading the code that it is supposed to be at `%APPDATA%\FlowLauncher\Themes`, so I added it there and it worked. If it is a portable installation it will be different.

It would be nice if there was another link to that folder, on the same settings tab (or the apropriate folder if it is a portable instalation).

**Describe alternatives you've considered**

The alternative is searching in the docs (I couldn't find it, hopefully this issue will help others find it) or reading the code. Docs could help, but the link would make it more intuitive and simpler to use.

**Additional context**

The code is this:

https://github.com/Flow-Launcher/Flow.Launcher/blob/fd56af77dc96d0e2e10a5b43254c4981d915afe4/Flow.Launcher.Core/Resource/Theme.cs#L26-L32

And this:

https://github.com/Flow-Launcher/Flow.Launcher/blob/fd56af77dc96d0e2e10a5b43254c4981d915afe4/Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs#L15-L21

From the second code file you can see that if the installation is portable the directory will not be on `%APPDATA%`.

**Comment by jjw24** [comment]
This new enhancement will go out in the next release :)
