### ISSUE TITLE
BUG: "Empty last query" does not reset the context menu

### ISSUE THREAD

**Issue by blueputty01** [Flow-Launcher/Flow.Launcher#2019]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Context menu from previous query will still be active despite "Last query style" set to "Empty last query".

### To Reproduce

1. Set "Last query style" to "empty last query" (and "Hide Flow Launcher when focus is lost" to true)
2. Enter query and open context menu for a result item
3. Blur focus for launcher (launcher hides at this point)
4. Reactivate flow launcher. Context menu from previous query will still be active

### Screenshots

![image](https://user-images.githubusercontent.com/65861156/228977781-401b6674-69ff-45c2-83d8-13d4f68c6e05.png)
![image](https://user-images.githubusercontent.com/65861156/228977870-88635735-6f37-4aec-89f7-a23d1ae69131.png)

### Flow Launcher Version

1.14.0

### Windows Build Number

22621.1413

### Error Log

Not an error

**Comment by onesounds** [comment]
I was aware of this issue, but had forgotten that it needed to be fixed. The fix will be in the next release. Thanks for report.
