### ISSUE TITLE
[FEATURE REQUEST] Search that learns your preferences

### ISSUE THREAD

**Issue by nikolicpetar17** [Flow-Launcher/Flow.Launcher#2021]
I think it would be nice if flow launcher could automaticaly show results that i used earlier on top of query

**Comment by deefrawley** [comment]
Hi, Flow already does this and ther is a new feature for Everything that uses one of its features to do the same thing

**Comment by luopa** [comment]
> I think it would be nice if flow launcher could automaticaly show results that i used earlier on top of query

In regards to the explorer plugin: You can achieve the behavior you're looking for by setting _everything_ as search results provider within the explorer plugin.

Then, make sure to set the sorting setting of the explorer plugin accordingly: 
![image](https://user-images.githubusercontent.com/5087420/229276425-e7eedfdf-680c-4c5e-ad27-7429027629f8.png)

**Comment by nikolicpetar17** [comment]
Thanks, it's probably up to priority settings in my case

**Comment by deefrawley** [comment]
Thsnkd @luopa - that is what I was referring to (answering in a hurry earlier).
Will close the issue but if there is anything else that you think isn't working @nikolicpetar17 raise another issue, or if you would like to ask questions about how Flow works head over to our Discord.

**Comment by nikolicpetar17** [comment]
Thanks
