### ISSUE TITLE
Control Panel > Unknown

### ISSUE THREAD

**Issue by TheStxfan** [Flow-Launcher/Flow.Launcher#2022]
I think there is an issue with flow's Control Panel shortcuts. It doesn't seem to be an issue with all the shortcuts, but as you can see in the attached image when I try to access the windows group editor trough the shortcut "s" in flow launcher, it gives an unknown path to that setting. The shortcuts seem to be working (redirecting to the correct "page" in settings and in the control panel) even with this issue. The only one that does not work is the group editor though. When I click on it, it just doesn't do anything. I tried to uninstall flow launcher completely, even manually removed all the remaining save files in the %appdata% folder.
Please, fix this issue.

![image](https://user-images.githubusercontent.com/109021123/229169217-0f7dfcc9-5f75-46f8-8a4f-e059979fd5e4.png)

Unfortunately, in the above image I cannot show you the full "Unknown" list, but you can imagine how long it was from the small scrolling bar on the right. The results for "Unknown" were more than 200.

**Comment by VictoriousRaptor** [comment]
This is plugin ported from PT run. I think those commands are just not place under a certain category so maybe we can change it to "Others"?

**Comment by jjw24** [comment]
Place in Others if we can't determine which category they are from. If I remember correctly it's marked as Unknown because it's not clear where it's from.
