### ISSUE TITLE
URL's in Settings don't respect default system browser and just use Google Chrome

### ISSUE THREAD

**Issue by deefrawley** [Flow-Launcher/Flow.Launcher#203]
**Describe the bug/issue**
Settings - Theme, Plugin and About pages. All URL's start a Google Chrome instance despite Brave Browser being my default browser.

**To Reproduce**
1. Set a browser default to something other than Chrome
2. Open Settings either from Flow or from the tray menu
3. Click on any hyperlink

**Your System**
```
Windows build number: 10.0.19042.630
Flow Launcher version: 1.4.0
```

**Comment by jjw24** [comment]
Hey how's it going.

I haven't looked into opening with default browser yet, but can you open brave browser by setting the path to brave's exe in the plugin?

**Comment by deefrawley** [comment]
Hi Jeremy,

I added the explicit Brave path to the URL and the Web Search plugin and restarted Flow. It still uses Chrome.

**Comment by taooceros** [comment]
I think the brower used to open the link in setting windows won't link to the brower path in web search plugin and url. I think Jeremy has misunderstood your question.
I have taken a look on the implementation of the hyperlink, and the default is chrome.
https://github.com/Flow-Launcher/Flow.Launcher/blob/98630d1af58998e76b24bf8f5c2423d1b1f747a0/Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs#L14-L20
Let me check if it is possible to change that to the default brower.

**Comment by deefrawley** [comment]
Thanks @taooceros. I did temporarily switch my default browser to Edge and restarted Flow to try that (and make sure it wasn't something specific to Brave) but it still used Chrome. I could try uninstalling Chrome altogether to see what happens if that would help?

**Comment by taooceros** [comment]
I found out that why in my computer it works, because I don't have chrome installed😅. If that is not too troublesome for you, you can try that. However, let me take a try to find out the way to use default browsers to open url if no specific browser path has provided. I think using chrome as default is not working as intended.

**Comment by taooceros** [comment]
[Flow.Launcher.Plugin.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/5557361/Flow.Launcher.Plugin.zip)
@deefrawley I am not sure whether it is possible to take the change via changing one specific dll, but take a try to replace the dll with the one in the zip. For now, the behavior should open the default browser in a new window.

**Comment by deefrawley** [comment]
Yes, that new DLL worked thanks.
