### ISSUE TITLE
BUG: Shell plugin cannot open startup folder

### ISSUE THREAD

**Issue by DNM1008** [Flow-Launcher/Flow.Launcher#2036]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When I typed `> shell:startup`, it just returns an error instead of opening the startup folder. I have ticked the option to replace Win + R.

### To Reproduce

1. Open Flow Launcher
2. Type `> shell:startup`
3. Error

### Screenshots

![image](https://user-images.githubusercontent.com/54259825/230700821-bc06dbb3-8768-42be-907b-7e37d92f5095.png)
![image](https://user-images.githubusercontent.com/54259825/230700850-a18b4165-73b3-49d2-8079-67f61f8ca4c5.png)

### Flow Launcher Version

1.14.0

### Windows Build Number

11H2

### Error Log

[2023-04-08.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11182404/2023-04-08.txt)

**Comment by jjw24** [comment]
Can you show us what's in your configured file manager:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/26427004/8e25f935-466c-43df-8ad3-ade5126a97c9)
