### ISSUE TITLE
BUG: Run program via Plugin.Program may case the opened program act not as expected

### ISSUE THREAD

**Issue by WayneFerdon** [Flow-Launcher/Flow.Launcher#2038]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Run program via Plugin.Program may case the opened program act not as expected

Such as：Run MKVToolNix GUI（Latest tested and reproduced by v75.0.0 ('Goliath') 64-bit: [download link])(https://mkvtoolnix.download/windows/releases/75.0.0/mkvtoolnix-64-bit-75.0.0-setup.exe))
which may cause the drag-and-drop import disabled, yet it works while run by Plugin.Explorer

用程序插件打开某些程序时，可能会出现该程序未能正确运行某些功能的情况
例如：运行MKVToolNix GUI（最新测试重现过的版本为v75.0.0 ('Goliath') 64-bit [下载链接])(https://mkvtoolnix.download/windows/releases/75.0.0/mkvtoolnix-64-bit-75.0.0-setup.exe)）
将导致拖放导入素材无法使用，而通过文件管理器插件运行时则正常

### To Reproduce

1. Install and run MKVToolNix GUI via Plugin.Program
2. try to drag and drop a source such as video/audio/subtitles/etc. into MKVToolNix GUI
3. the attempt above failed

1. 安装并使用程序插件运行MKVToolNix GUI
2. 尝试拖放导入视频/音频/字幕等素材到MKVToolNix GUI中
3. 尝试失败

### Screenshots

![image](https://user-images.githubusercontent.com/47738396/230768431-6357a3d0-0f5d-4a24-91cb-cb206b8fe3fe.png)

### Flow Launcher Version

1.14.0

### Windows Build Number

System: Windows 11 Pro 22H2; OS Ver. 22621.1485; Exp. Ver. Windows Feature Experience Pack 1000.22639.1000.0

**Comment by WayneFerdon** [comment]
Might be related to how the ‘run’ function implementation

**Comment by deefrawley** [comment]
Hi. I can run the GUI from Flow and still drag and drop files into it. Is this what you were doing?

**Comment by WayneFerdon** [comment]
> 

yes. in that case, it seems to be a individual case. i'll check further then.

**Comment by WayneFerdon** [comment]
I tried vscode as well, in which the same thing happened again.
I noticed that run the GUI from the program plug in will run it as administrator by default, so I tried to run the GUI as administrator manually, which leads to the same result.
Which might be part of the reason of this. In that case, it seems to be a windows issue or something else instead of flow's.

**Comment by WayneFerdon** [comment]
Wait, if programs can run as administrator throw the context menu, should it default to be run as current user?

**Comment by WayneFerdon** [comment]
Oh, I might found the reason:
I set flow run as administrator for some reason, which makes the 'Verb = runAsAdmin ? "runas" : ""' in [Flow.Launcher.Plugin.Program/Programs/Win32.cs#L184](https://github.com/Flow-Launcher/Flow.Launcher/blob/8f58d53b8a3a9eedc13e2be1cf7fb5f9e0950ad9/Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs#L184) run all program as flow's set user, in my case, the administrator.
Which leads to this issue.

**Comment by WayneFerdon** [comment]
Yes, it is the reason leads to this issue.
I reset the flow to run as the current user, and everything works just fine as they should be.
Meanwhile, run flow via some administrator ways, such as run from a administrator shell, will also leads to what happens above

**Comment by deefrawley** [comment]
Some nice detectiver work. If I launch MVKNixGUI from the Windows start menu as admin then I can't drag and drop files to it either.
Going to call this one closed. If you have any other issues create a new one here or jump over to our Discord to discuss.
