### ISSUE TITLE
[Enhancement][Appearance] Individual Font/FontWeight for Item Subtitles

### ISSUE THREAD

**Issue by KJH-x** [Flow-Launcher/Flow.Launcher#2041]
> I am not a native English speaker and may have grammar and wording issues. 
> If you're not sure what I'm talking about, feel free to ask.

**Is your feature request related to a problem? Please describe.**

- Enhance the visual order and hierarchy of search results.

**Describe the solution you'd like**

- Add a font option for Item Subtitles.

**Describe alternatives you've considered**

- Add a font option in style sheet.
- Add a font Weight option. (Using same font as Title)

**Comment by onesounds** [comment]
This is something we'll be working on. It's something I've been meaning to work on for a while now, but it's been pushed back due to prioritization. I'm a little busy right now, so it's not going to happen anytime soon, but it will happen.
