### ISSUE TITLE
Update docs to include `@<shortcut> ` to allow shortcuts with addl arguments

### ISSUE THREAD

**Issue by ThinkSalat** [Flow-Launcher/Flow.Launcher#2044]
For example, you create custom shortcut query: `todo` expands to `> todo -arg` and you want to pass in a parameter to the shell. ie: `todo 'eat breakfast'` would expand to `> todo -arg 'eat breakfast'`

Normally, typing in `todo` followed by a space would remove the custom shortcut, so to add an argument to the custom shortcut, you need to type in the custom shortcut using `@todo` for example.

In this case, typing `@todo 'eat breakfast'` gives you the output you want: `> todo -arg 'eat breakfast'`

I don't see mention of this in the docs, at least not clearly. This is a good feature that should be more easily understood!

Additionally, perhaps there could be an option when creating the shortcut. A checkbox called "accept arguments" or something. This would just add the "@" at the beginning when you call the shortcut, or just make it so you don't need to do so!

**Comment by onesounds** [comment]
> @taooceros @onesounds Where should we add this documentation? In the custom shortcut window or just link it to our website? I'm afraid it might be too long to fit in the window.


Basically, I think it's better to do it in a window because of translation issues, since the image can show some of it (anyway, is this feature implemented?).

**Comment by ThinkSalat** [comment]
I think it’s fine to just add it to the site’s documentation.  As long as there’s a reference that’s fairly easily found.

**Comment by jjw24** [comment]
> BTW: should shortcuts be case-sensitive? currently it is but it seems doesn't make much sense. @taooceros

I dont think it makes much sense to make it case sensitive so lets change it.

**Comment by VictoriousRaptor** [comment]
Fixed in #2350.
