### ISSUE TITLE
BUG: My system default browser is Edge Dev, but Browser Bookmarks plugin uses Edge everytime.

### ISSUE THREAD

**Issue by Yaotian-Liu** [Flow-Launcher/Flow.Launcher#2050]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

My system default browser is Edge Dev, but Browser Bookmarks plugin uses Edge to open the selected bookmark everytime. I've double-checked that my system default browser setting, which is Edge Dev.

### To Reproduce

1. Install Edge Dev and Edge.
2. Open a website with Browser Bookmarks

### Flow Launcher Version

1.14.0

### Windows Build Number

22621.1555

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi. System default has nothing to do with the bookmarks. Just add Edge Dev as a new browser location in the plugin settings.

**Comment by Yaotian-Liu** [comment]
This is my current setting:
![image](https://user-images.githubusercontent.com/58876108/232280204-271de35b-94b1-49b4-bec0-e0772eabe979.png)
It works fine indexing my bookmarks. But it keeps using Edge, instead of Edge Dev to open.

**Comment by Yaotian-Liu** [comment]
Sorry there might be some misunderstanding. I've modified the "Problem Description". What I want is use Edge Dev to open selected bookmarks instead of Edge.

**Comment by deefrawley** [comment]
I understand now. Do other URLs open with Edge Dev as default?

**Comment by Yaotian-Liu** [comment]
Yes. URLs in other files, and in my terminals (Windows Terminal & Alacritty), just work fine opening with Edge Dev.
And here is my setting on Windows:
![image](https://user-images.githubusercontent.com/58876108/232280988-f6a6ee67-792f-4775-bdb5-8cf13cedf1fc.png)

**Comment by Yaotian-Liu** [comment]
> Please check if you specify Edge as your default browser in Flow's settings (Settings->General->Default Browser)

Oh, here's a setting for this. Now it's working. Thanks! 😃
