### ISSUE TITLE
Plugin request: Search open tabs

### ISSUE THREAD

**Issue by jamie9090** [Flow-Launcher/Flow.Launcher#2069]
I love how on Mac, Alfred has extensions to help you search open tabs in Edge. Would love something similar here?

**Comment by MandeepCodes** [comment]
That would be a great enhancement to Flow launcher, I upvote for it.

**Comment by emkay5771** [comment]
Tried doing that... Unfortunately, window walker groups all tabs as 1 window, even with the tabs being split out in the Alt-Tab menu.

**Comment by jjw24** [comment]
I see this as a feature for WindowWalker plugin. So will be keeping this issue closed here.

**Comment by KingPsychopath** [comment]
Any updates on this before I make a solution myself?

**Comment by jjw24** [comment]
Not that I am aware of here or at WindowWalker plugin project unfortunately.

**Comment by Chaoscontrol** [comment]
> Any updates on this before I make a solution myself?

Did you end up working in some solution? This would be my most loved feature in the entire Launcher.

**Comment by glenviewjeff** [comment]
Me too

**Comment by Garulf** [comment]
I investigated if this feature was possible. Due to security/privacy most browsers do not allow access to browser tab information. 

The best workaround I could find was to have a plugin read the GUI and invoke keyboard shortcuts. This implementation would have a lot of drawbacks.

**Comment by glenviewjeff** [comment]
You could definitely do it in combination with a custom chrome extension,
but that could be a lot of extra work.

**Comment by glenviewjeff** [comment]
Here's how one would access the tabs:
https://developer.chrome.com/docs/extensions/reference/api/tabs

Here's how you would send the open tabs to the plugin:
https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging

[Here's some potential AI help](https://www.perplexity.ai/search/how-can-i-programmatically-acc-vlwOghrRQDypU93wOTH05g)

**Comment by Chaoscontrol** [comment]
Recently  I've been playing with time tracking apps, and while it's true most request you to install a browser extension to track URLs, there was one in particular that didn't, and it started tracking my browser URLs automatically just with the desktop app and no additional setting. 

This app was: https://desktime.com/ in case it's useful to find out how they do it.

**Comment by jjw24** [comment]
A new plugin will be available for this
https://github.com/Flow-Launcher/Flow.Launcher.Plugin.BrowserTabs
