### ISSUE TITLE
BUG: i can't install hackernews plugin

### ISSUE THREAD

**Issue by DLRAM** [Flow-Launcher/Flow.Launcher#2078]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

it says it failed to install 

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.14.1

### Windows Build Number

10.0.22621.1

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi, could you please give us a bit more information such as attaching your logs or a screenshot of the error? Does it happen with other plugins?

**Comment by DLRAM** [comment]
![Flow Launcher_mpNuwyr46A](https://user-images.githubusercontent.com/59944300/233879648-8c7b37d7-a521-48ba-8634-2cc9bd811ea1.png)
hi, here is the screenshot..., some plugins are showing like this

**Comment by deefrawley** [comment]
Can you please post your logs? Type `open log location` in Flow to get to the log folder and post the latest file here. Thanks

**Comment by DLRAM** [comment]
Hey,  It's working perfectly now. Turns out the log showed that the file already existed, so I just deleted it and reinstalled. Thanks a bunch!
