### ISSUE TITLE
Clipboard shortcut causes crashes & visual defects with large selection

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#2084]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

BUG: The text in the search box is not displayed correctly.

### To Reproduce

1.
![image](https://user-images.githubusercontent.com/109513632/233792399-4b32cbe5-0539-4b14-9515-6170d54fedaf.png)

2. enter https://github.com/Flow-Launcher/Flow.Launcher.  copy and press alt +~. tap something.
3. ![image](https://user-images.githubusercontent.com/109513632/233792376-050e2383-c395-4a86-9022-168609e82ab3.png)

### Screenshots

![image](https://user-images.githubusercontent.com/109513632/233792292-6a7164c1-e18a-4c83-9577-b780725aed13.png)
![image](https://user-images.githubusercontent.com/109513632/233792376-050e2383-c395-4a86-9022-168609e82ab3.png)

### Flow Launcher Version

1.14.1

### Windows Build Number

10.0.22621.1555]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Garulf** [comment]
Very strange behavior. It almost looks like text is getting wrapped to a new line which should not be possible.

**Comment by thomasTAT** [comment]
I hope this can also be solved. [https://github.com/Flow-Launcher/Flow.Launcher/issues/2039](url)
Thank you to the developers who contributed

**Comment by deefrawley** [comment]
Please update to the latest version and if the problem persists we can reopen. Thanks.
