### ISSUE TITLE
BUG: TS Plugins aren't showing up/running

### ISSUE THREAD

**Issue by medatehief** [Flow-Launcher/Flow.Launcher#2093]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I've recently updated and now all my typescript plugins aren't working. I double checked by downloading the npm plugin just in case it was something on my end.

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.14.1

### Windows Build Number

Version	10.0.22621 Build 22621

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Garulf** [comment]
Hello @medatehief 

Could you please provide us with your Flow Launcher log so we can take a look at your issue?
