### ISSUE TITLE
[FEATURE] > WebSearch > Search on multiple sites at once

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2097]
**Is your feature request related to a problem? Please describe.**

Now the WebSearch feature only works on one page at once.

**Describe the solution you'd like**

I would like to add multiple websites to search the same query or just open their homepages

In Keypirinha App, it looks like this:

```
[site/My Multi Search]
url = 
    https://www.google.com/search?q=%s
    https://duckduckgo.com/?q=%s
    https://www.startpage.com/sp/search?query=%s

[site/My Search on New Sites]
url = 
    https://www.news_1.com/search?q=%s
    https://news_2.com/?q=%s
    https://www.news_3.com/search?query=%s
```
So when I trigger the "My Multi Search" + "my keyword", it opens up every defined site with my search query. If a keyword (%s) is not defined, it opens the homepage.

**Additional context**

[Here is a fast video about it](https://drive.google.com/file/d/1xnSzWJY3oGcKv1RMSl-m2Jf2DWZsv34U/view?usp=share_link)

**Comment by nikolicpetar17** [comment]
it would probably be better if it just shows you opition to chose which site to search, for examle:


Query: MultiSearch How fast is speed of light
1) Google search: How fast is speed of light
2) Youtube search: How fast is speed of light
3) Bing search: How fast is speed of light


i think you get what i am trying to say

**Comment by jjw24** [comment]
There is a workaround currently by separating the URLs with a space.

**Comment by DRYN07** [comment]
> it would probably be better if it just shows you opition to chose which site to search, for examle:
> 
> Query: MultiSearch How fast is speed of light
> 
> 1. Google search: How fast is speed of light
> 2. Youtube search: How fast is speed of light
> 3. Bing search: How fast is speed of light
> 4. Wikipedia search: How fast is speed of light
>    ...
> 
> i think you get what i am trying to say

Sorry, but it is not better at all. I can search on almost any website separately, but I need to search my predefined sites at once. 

Here is a practical example:

I want to search "Lenovo Legion" on every second-hand website I use. If I use your method, I have to search it one by one selecting the websites one after the other. How I use It now with Keypirinha is I just type "IT Lenovo legion" and it opens up 10+ websites with the results. It's way faster. Moreover what you say is implemented in any browser nowadays, so I don't really care that the launcher has this feature or not :D

**Comment by jjw24** [comment]
I believe the Shortcuts plugin is now built for this request, please try the plugin.

Feel free to reopen if not the case.

**Comment by DRYN07** [comment]
> I believe the Shortcuts plugin is now built for this request, please try the plugin.
> 
> Feel free to reopen if not the case.

Thanks for the reply. Although I don't see a Shortcuts plugin in the settings -> Apps/plugins area or on GitHub :/ 

Can you specify please where I should check it?

**Comment by jjw24** [comment]
You should be able to see a plugin called Shortcuts in the Plugin Store.

The project is located here https://github.com/mantasjasikenas/flow-launcher-shortcuts-plugin

**Comment by DRYN07** [comment]
Wow, this looks amazing. And sorry for my noobyness but I can't get it to work. I tried to paste the files into the Plugins folder but nothing happened.

And this is the plugin area where I should have seen the plugin if I understand correctly. On the plugin's GitHub page I could not find any description about the installation.

Thank you very much for your help by the way.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/29770761/8ece2457-8032-432d-b62c-22cabfa6bca3)

**Comment by DRYN07** [comment]
Oh, man... I mixed up two similar issue pages... Now I understand everything you said... Of course I don't find Flow Launcher plugins in the Fluent Launcher plugin area... 

Thank you for your help by the way, I am testing both of them so I really appreciate this plugin as well.
