### ISSUE TITLE
Customizable Workflows (similar to Alfred's)

### ISSUE THREAD

**Issue by assadtony** [Flow-Launcher/Flow.Launcher#2114]
As a user, I would like to have customizable workflows that allow me to trigger a series of events, apps launches, and more so that I can automate an entire workspace or series of repetitive tasks.

I'm always frustrated when I need to stream in Twitch and open every dependent app that it needs for it to work.

**Describe the solution you'd like**
Would like a customizable UI like the one on Alfred Workflows. Example of OSX equivalent: https://www.alfredapp.com/workflows/

**Describe alternatives you've considered**
- Going to OSX and using Alfred :) 
- Creating a .bat file with a series of commands to open all of the apps that I need to have open. Then link that with a custom plugin in Alfred that I can then just trigger quickly from my Launcher.

**Comment by taffit** [comment]
This is the only feature preventing me from switching from Ueli to FlowLauncher.    
While in Ueli you can just provide a list of single paths, URLs or command line tools (beside a name, description, tags and an icon for each workflow), Alfred's workflows seem to be way more sophisitcated and powerful (not being an Apple-user, I've never seen it).    
I tought to create a simple plugin myself, however I couldn't find the documentation for fields in the settings, and so was lost.

**Comment by taffit** [comment]
Oh, no reason to say sorry! Thank you for this wonderful software!    
I already took a look at the other plugins, but beside the ones written in C# I couldn't find what I'm looking for. Garulf's Steam search plugin has a yaml-file with some input fields, but I wasn't able to find a list of possible values/controls or how these where connected to the code. For this to work, basically an editable list of commandlines would be all it needs for a first prototype.

Can you point me to some resource where I could find possible controls (I would strongly prefer to write the plugin in Python)?

**Comment by jjw24** [comment]
@taffit this is where you want to look at for the available controls https://github.com/Flow-Launcher/Flow.Launcher/blob/e03b9930c0c43999351b75e3bb21ae8347ee9ea2/Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs#L425. We don't dont provide too many at this stage unfortunately.

**Comment by jjw24** [comment]
Dup of #1128

**Comment by youtextme** [comment]
Alfred workflows are the right research path here. If Sandy users don’t have Powerpack, a **free Raycast** Script Command can wrap the same CLI/API as a stopgap so the integration isn’t gated on a paid Alfred license.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
