### ISSUE TITLE
Text rendering issue on HiDPI screen

### ISSUE THREAD

**Issue by mimecry** [Flow-Launcher/Flow.Launcher#212]
**Describe the bug/issue**
On a HiDPI screen, the interface seems to be _somewhat_ blurry and lacking in sharpness.

**To Reproduce**
1. Install Flow on a machine with HiDPI display (i'm using a 14" 2560x1440 screen at 150% scaling)
2. Launch the software

**Screenshots**
The following is a screenshot comparison between Flow 1.4.0 (top, dark blue) and the latest Wox pre-release (1.4.1196) (bottom, teal), both using Ebrima font at regular size.
![image](https://user-images.githubusercontent.com/10742312/99479712-4cc26a00-2989-11eb-9946-46a4466183b5.png)

When zoomed in, you can see that the text on Flow is more pixelated
![image](https://user-images.githubusercontent.com/10742312/99480101-0588a900-298a-11eb-8d51-50eb39c3df27.png)

Edit: Perhaps this issue also applies to other UI elements aside from text. Here is a zoomed in screenshot of the search icon
![image](https://user-images.githubusercontent.com/10742312/99480510-ce66c780-298a-11eb-8dd8-1009a433633b.png)

**Your System**
```
Windows build number: Version 10.0.18363.418
Flow Launcher version: 1.4.0
```

**Comment by mimecry** [comment]
recently redownloaded Flow and it looks great now, thank you for all your work

**Comment by taooceros** [comment]
> recently redownloaded Flow and it looks great now, thank you for all your work

it has been fixed??? Surprise🤣

**Comment by Garulf** [comment]
Great to hear the issue was resolved!
