### ISSUE TITLE
FlowLauncher.exe locks places.sqlite in Firefox profiles folder even if Browser Bookmarks plugin is disabled.

### ISSUE THREAD

**Issue by ryokash** [Flow-Launcher/Flow.Launcher#2120]
FlowLauncher.exe locks places.sqlite in Firefox profiles folder even if Browser Bookmarks plugin is disabled. And it prevents to backup Firefox profile.

We can uncheck "Firefox" from "Load Browser From" as a workaround, but it is unexpected behaviour.

**Comment by VictoriousRaptor** [comment]
Hi, could you tell us which version of Flow Lanucher are you using? I can't reproduce your issue.

**Comment by ryokash** [comment]
FlowLauncher version is 1.15.0.

**Comment by VictoriousRaptor** [comment]
Is Flow constantly locking `places.sqlite` or just occasionally? It should only get locked while Flow is loading bookmarks (which should be fast). And after loading it monitors changes of the file (which doesn't stop you copying file). How do you backup your profile?

Trying to load when disabled is an issue though. @jjw24 @taooceros @Garulf any idea?

**Comment by ryokash** [comment]
Sorry, I tried reproduce, but I cannot any longer by unknown reason.
But when I reported this issue, Windows Resource Monitor
telled FlowLauncher.exe was keeping places.sqlite, places.sqlite-shm
and places.sqlite-wal open.
