### ISSUE TITLE
BUG: 'Start Flow launcher on system startup' does not work where account path contain spaces

### ISSUE THREAD

**Issue by xmichelo** [Flow-Launcher/Flow.Launcher#2131]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

'Start Flow launcher on system startup' does not work. 
I investigated a bit using Sysinternals Autoruns,  and I think the issue might be link to the fact that my Windows local account contains a space. The Image path is clearly missing what's after the space character. It lists  `C:\Xavier` when it should be something last `C:\Xavier Michelon\...` 

### To Reproduce

Potentially, test the feature with an account that contains a space in it username.

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1926756/e690c39b-a064-436d-9ee7-8acb20dfbfb1)

### Flow Launcher Version

1.15.0

### Windows Build Number

Microsoft Windows [Version 10.0.19045.2965]

### Error Log

[2023-05-11.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11448351/2023-05-11.txt)

**Comment by VictoriousRaptor** [comment]
#2000. Can't test it now. Will try to investigate later this week. Can you please try to navigate to `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` and add quotes to Flow's entry, then check if it's fixed?

**Comment by xmichelo** [comment]
It's odd, other entries in the list are double quoted, so it did it. it fixed the path in Autoruns. I logged out and logged it again, but the app did not launch. The path in the registry is correct, i tested it in a "Run" box. Not surprisingly, when Flow launches, it replaces the quoted version by the previous one, but I took care and repeated the test twice without success.
In

**Comment by taooceros** [comment]
@xmichelo could you take a check on this build? https://ci.appveyor.com/api/buildjobs/7cb1p4hkf72s18xf/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

**Comment by xmichelo** [comment]
Hi @taooceros . 

It works now! Thanks a lot.

Note: I do not have the original setup anymore, as the machine was update to Windows 11, but I still have a Windows 10 VM. I created an account with a space in the username, installed the build, enabled autostart and rebooted. Flow properly started on login.

**Comment by VictoriousRaptor** [comment]
> Hi @taooceros .
> 
> It works now! Thanks a lot.
> 
> Note: I do not have the original setup anymore, as the machine was update to Windows 11, but I still have a Windows 10 VM. I created an account with a space in the username, installed the build, enabled autostart and rebooted. Flow properly started on login.

Well that's a surprise. I didn't expect it can fix this issue.

**Comment by taooceros** [comment]
That's nice, then let's get it merged.

**Comment by Manfred73** [comment]
I'm experiencing the same issue. When I turned on "automotiacally run at startup", I see this in the registry.
It doesn't start up though if I restart windows.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13829887/6a8c06ed-1ac5-43c8-b35f-0cb7a73682b5)
