### ISSUE TITLE
[API to Hide MainWindow] Add new plugin api to hide mainwindow or clear focus

### ISSUE THREAD

**Issue by rainyl** [Flow-Launcher/Flow.Launcher#2132]
**Is your feature request related to a problem? Please describe.**

For a plugin like clipboard manager, it will be convenient to click a query result to paste to the background application such as a chatting dialog, but for now, the FlowLauncher will get focus and there is no such api in IPluginAPI to hide the focus, the only way to paste a result is copy it to clipboard and paste it manually.

**Describe the solution you'd like**
Just add an api like ShowMainWindow(), but something like `HideMainWindow()` or `ClearFocus()` to IPluginAPI and a corresponding implementation.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by VictoriousRaptor** [comment]
Good point and I'm a bit curious how this could help your plugin?

**Comment by rainyl** [comment]
Now, when a result is clicked, it seems the query box will close only when the action returns true, and the paste action won't work due to the focus is not on the input dialog, if we can make mainwindow (i.e., the query box) unfocused before paste, then the application got focused before will get focus again, and it will be easy to paste the selected query result.

The ideal result will looks as:
![preview](https://github.com/Flow-Launcher/Flow.Launcher/assets/30213663/3fcf0016-5c0e-4e4e-908d-d4e2a2be347c)
