### ISSUE TITLE
[Linux]

### ISSUE THREAD

**Issue by ChheavBunHeng** [Flow-Launcher/Flow.Launcher#2136]
The software in question boasts an impressive combination of potency and user-friendliness. Its exceptional performance is a testament to the hard work and dedication of its developers, who have created a tool that meets the needs of many users. However, it appears that the software is currently not available for use on Linux platforms, which is a missed opportunity to expand its reach to a large and growing community of Linux enthusiasts. Therefore, it would be greatly appreciated if the developers could consider making the software available for Linux users as well. By doing so, they would not only enhance the software's already impressive reputation but also open up a whole new audience to its capabilities and potential. It's a win-win situation that could lead to even greater success and recognition for this powerful and user-friendly software.

**Comment by deefrawley** [comment]
Hi, thanks for the suggestion but currently Flow is Windows only and there are no current plans to make it cross platform.

**Comment by JJOAKING16** [comment]
whyy???  windows 11 is running out all  24gb ram 😢
