### ISSUE TITLE
Recursive file scan or in-depth file scan

### ISSUE THREAD

**Issue by Codingkingsman** [Flow-Launcher/Flow.Launcher#2139]
The Flow Launcher is very useful and I love the UI. The only issue is that I can't search within my folders for different files, only the main parent directory is shown. Please do bring in a feature for in depth scanning for files for selected folders (like the feature in Ueli launcher). Thanks in advance!

**Comment by deefrawley** [comment]
Hi. Flow does this.
What file indexer are you using (Windows or Everything)?

**Comment by Codingkingsman** [comment]
I'm using Windows file indexer. I'm sorry for raising this issue, apparently I had not read the Flow Launcher docs properly. Now I'm able to find my files no matter where they are located :)
Thanks for replying to my issue and helping me out. I apologize once again and great job done on this application and I wish you luck for the future!

**Comment by deefrawley** [comment]
No problems, happy to help with any issue. Good that you got it working
