### ISSUE TITLE
Add arabic language 

### ISSUE THREAD

**Issue by asmpro7** [Flow-Launcher/Flow.Launcher#2146]
arabic is the fifth most-spoken language globally which there are  313 million Arabic speakers.

**Comment by jjw24** [comment]
Including the language in flow is a simple change, but when displaying Arabic, since it is read right to left, would this change the way the text is displayed in flow?

**Comment by asmpro7** [comment]
arabic to display well should be UTF-8 as encoder 
we can try to add it and see if there are any problems.

**Comment by asmpro7** [comment]
arabic to display well should be UTF-8 as encode 
we can try to add it and see if there are any problems.

**Comment by jjw24** [comment]
Which sidebar are you referring to?

**Comment by asmpro7** [comment]
![Screenshot_2023-06-09-03-41-32-79_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Flow-Launcher/Flow.Launcher/assets/114514662/d1cd43f8-3906-486b-bc69-3b7fa178cb71)

this one but it dosent important

**Comment by jjw24** [comment]
To change the UI RTL will be a fair bit of effort to do, is it acceptable to just display the the language text in Arabic?

**Comment by asmpro7** [comment]
It will be enough for now
but it will be annoying, 
so add arabic for now it will fulfill the purpose.

**Comment by VictoriousRaptor** [comment]
![图片](https://github.com/Flow-Launcher/Flow.Launcher/assets/10308169/dfd7ccf4-66ce-4435-ae2d-3a87a36872dc)

@asmpro7 Are these variants of Arabic language very different? Is adding "plain" Arabic enough?

**Comment by asmpro7** [comment]
Yes, a plain arabic is enough. 
there arent any different.
