### ISSUE TITLE
BUG: "Kill" command not deleted after use

### ISSUE THREAD

**Issue by WolfyGreyWolf** [Flow-Launcher/Flow.Launcher#2147]
### Checks

- [X] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

https://github.com/Flow-Launcher/Flow.Launcher/assets/77587065/ff60ceaf-7c1e-43aa-b1cf-b677090ea83b

### To Reproduce

1. Open Flow launcher
2. Type "kill <app>"
3. Reopen Flow launcher

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.19045.2965

**Comment by deefrawley** [comment]
Hi,
There is an option to contril this. You may have it set to show last query. Does it happen with all Flow commands?

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/18594055/9c9185d4-4545-4604-9573-a1022f80a266)

**Comment by WolfyGreyWolf** [comment]
No , it happen only with the "kill" instruction , not with other commands ..

**Comment by VictoriousRaptor** [comment]
#2088

**Comment by JohnTheGr8** [comment]
This is caused by the 500ms delay before re-query that the ProcessKiller plugin does. Without the delay, `Last Query Style` is honored by the kill command and this issue is resolved.

#2161 is thus an unnecessary change... I'll open a new PR.
