### ISSUE TITLE
[FEATURE REQUEST] Include in global result

### ISSUE THREAD

**Issue by nikolicpetar17** [Flow-Launcher/Flow.Launcher#2148]
I've noticed that Microsofts PowerToys Run has this toggle called "Include in global result" which makes it possible to show results of plugin without needing to type in keyword, but when you want to get more specific results you can still type it in and get more specific answers.

 
![Screenshot 2023-05-21 232816](https://github.com/Flow-Launcher/Flow.Launcher/assets/127212737/471bbd00-6294-463d-9917-357e79bfb1ed)

I think this feature could make using flow launcher much easier

**Comment by jjw24** [comment]
A plugin can actually set multiple action keywords in its plugin.json, so it can have `*` and `a` as its action keyword, and implement showing results when either action keyword is triggered.

I don't think this is necessary to implement in flow, plugins can implement it themselves.

**Comment by VictoriousRaptor** [comment]
> A plugin can actually set multiple action keywords in its plugin.json, so it can have `*` and `a` as its action keyword, and implement showing results when either action keyword is triggered.
> 
> I don't think this is necessary to implement in flow, plugins can implement it themselves.

It's kinda different. An additional **user-side** option to choose "Include in global result" allows user to trigger plugin by both `*` and `keyword`.

BTW: By manually adding keywords to `ActionKeywords` in `setttings.json`, you can achieve this.
