### ISSUE TITLE
BUG: Flow crash, out of memory error

### ISSUE THREAD

**Issue by KilmongerSimp** [Flow-Launcher/Flow.Launcher#2153]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

it crashes when I type anything
/
[2023-05-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11533304/2023-05-22.txt)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.19045.2846]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi, how much RAM (memory) does your PC have?
