### ISSUE TITLE
Accidentally Removed Program Plugin

### ISSUE THREAD

**Issue by arthackrc** [Flow-Launcher/Flow.Launcher#2169]
I accidentally uninstalled the program plugin that built-in flow.
Then I search in the plugin store but doesn't exist, also I use pm install but doesn't exist too.
How can I reinstall this plugin?

**Comment by deefrawley** [comment]
Hi. Reinstall Flow

**Comment by arthackrc** [comment]
How about all my settings? I need to re-setting all one by one again?

**Comment by JohnTheGr8** [comment]
alternative fix:

1. download [the latest release nupkg](https://github.com/Flow-Launcher/Flow.Launcher/releases/download/v1.15.0/FlowLauncher-1.15.0-full.nupkg)
2. extract the file's contents with 7zip (or similar app of choice)
3. copy the extracted sub-folder `\lib\net7.0\Plugins\Flow.Launcher.Plugin.Program\`
4. paste inside `%AppData%\FlowLauncher\Plugins\`
5. restart flow launcher

**Comment by Garulf** [comment]
> How about all my settings? I need to re-setting all one by one again?

Your settings will be safe.

**Comment by arthackrc** [comment]
it works, thank you.

**Comment by jjw24** [comment]
Dup of https://github.com/Flow-Launcher/Flow.Launcher/issues/1984
