### ISSUE TITLE
Question: Should we allows multiple plugins uses same action keyword?

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#217]
https://github.com/Flow-Launcher/Flow.Launcher/blob/69a5f291512edac4237269b1e047f89f15597f78/Flow.Launcher.Core/Plugin/PluginManager.cs#L122-L126

Based on this code, it seems that if action keyword conflict, only the last one will be kept.

**Comment by jjw24** [comment]
The current behaviour is warn and stop user from assigning duplicate action keywords.

Not sure how it behaves with downloaded plugin having duplicate action keywords, I think it might throw plugin loading error?

But current design is to not allow duplicates.

**Comment by taooceros** [comment]
> The current behaviour is warn and stop user from assigning duplicate action keywords.

That's true.
> Not sure how it behaves with downloaded plugin having duplicate action keywords, I think it might throw plugin loading error?

Not sure about that. I tried to modify the plugin.json file from plugin directory, and restart flow, but nothing happens. However, nothing in the code shows potential about plugin action keywords conflict will throw an error on loading, even though we do prevent users from assigning duplicate action keywords. Maybe we should add the check on it?

**Comment by jjw24** [comment]
What would actually happen if action keywords are duplicated in two plugins, you get two sets of results right, one from each set right? But other than that any potential problems?

**Comment by taooceros** [comment]
> What would actually happen if action keywords are duplicated in two plugins, you get two sets of results right, one from each plugin, but other than that any potential problems?

Well, I think only one of the sets of results will be displayed, because the later one registering the action keyword will overwrite the earlier one.

**Comment by jjw24** [comment]
Oh ok, I think the behaviour then would be to load and disable the external plugin and output a message to let user know why it is disabled?

Or do we just want to automatically update it to a new keyword?

**Comment by taooceros** [comment]
Maybe we can allow duplicate key, so that we put the control to users about whether they want to search those two plugin with the same duplicate key.

> Or do we just want to automatically update it to a new keyword?

That seems also good, but we need to notify user when doing that.

**Comment by jjw24** [comment]
I am ok with allowing duplicate keys as long as there are no side effects
