### ISSUE TITLE
Translation for Czech

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#2171]
Allow translation for Czech (@Asherro).

**Comment by asherroderg** [comment]
Yes, I'd welcome that!

**Comment by asherroderg** [comment]
Hey there,
I hate to remind you, but It's been some time and I am still interested in translating this project on Crowdin. 

I am looking forward to it, thanks!

**Comment by taooceros** [comment]
Hey there, I am so sorry for the delay. This shall be done by tonight.

**Comment by taooceros** [comment]
Czech is now avaliable on Crowdin. Flow will have the option to show as Czech after #2219 is merged.
