### ISSUE TITLE
Update Flow's Python installation from 3.8 to 3.11

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#2176]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The Embedded Python v3.8 installed by Flow is becoming out of date. Need to update to 3.11.

Need to consider if this update will impact Python plugins that has a hard dependency on 3.8.

**Comment by Garulf** [comment]
This change should only affect Python plugins that are packaged with C extension code for 3.8. 

Any plugins using pure Python should be fine in theory. 

I don't think we should hold off for these plugins as they have alternative ways to get around this issue using nuitka or pyinstaller.

**Comment by deefrawley** [comment]
Didn't 3.10 introduce some breadking changes?

**Comment by jjw24** [comment]
Maybe a better approach is to create an GH action, run the Python test code against 3.11, see how many breaks, we can then warn the authors.
