### ISSUE TITLE
BUG: Flow Launcher has a problem when starting with Workflowy Plugin

### ISSUE THREAD

**Issue by lastscoutboy** [Flow-Launcher/Flow.Launcher#2181]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Trying to start the Workflowy plugin, I get an error message (see logs below). 

### To Reproduce

1. Open FLow Launcher
2. Type WF
3. Crah Screen

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/31166095/b2d9342a-3003-4e18-96a1-6ee5cb4230f9)

### Flow Launcher Version

1.15.0

### Windows Build Number

22000.1936

### Error Log

<details>

</details>
[2023-06-11.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11715369/2023-06-11.txt)

[2023-06-11.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11715371/2023-06-11.txt

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\henni\AppData\Roaming\FlowLauncher\Logs\1.15.0\2023-06-11.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 22000.1936
IntPtr Length: 8
x64: True

Python Path: C:\Users\henni\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
Date: 06/11/2023 19:55:44
Exception:
System.IO.InvalidDataException: C:\Users\henni\AppData\Roaming\FlowLauncher\Plugins\Workflowy-1.0.0\node_modules\axios\lib\core\createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 404
    at createError (C:\Users\henni\AppData\Roaming\FlowLauncher\Plugins\Workflowy-1.0.0\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\henni\AppData\Roaming\FlowLauncher\Plugins\Workflowy-1.0.0\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\henni\AppData\Roaming\FlowLauncher\Plugins\Workflowy-1.0.0\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      cookie: 'sessionid=undefined',
      'User-Agent': 'axios/0.26.0'
    },
    method: 'get',
    url: 'https://workflowy.com/get_initialization_data',
    data: undefined
  },
  request: <ref *4> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: <ref *1> TLSSocket {
      _tlsOptions: {
        allowHalfOpen: undefined,
        pipe: false,
        secureContext: SecureContext { context: SecureContext {} },
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined,
        enableTrace: undefined,
        pskCallback: undefined,
        highWaterMark: undefined,
        onread: undefined,
        signal: undefined
      },
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'workflowy.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype] {
        close: [
          [Function: onSocketCloseDestroySSL],
          [Function: bound onceWrapper] {
            listener: [Function (anonymous)]
          },
          [Function: onClose]
        ],

**Comment by deefrawley** [comment]
Hi, can you post this issue in the Workflowy repo as this is an external plugin. Thanks.

https://github.com/brunolm/workflowy-wf/issues/2
