### ISSUE TITLE
BUG: Failed to initialize Browser bookmarks plugin

### ISSUE THREAD

**Issue by pratyakshm** [Flow-Launcher/Flow.Launcher#2184]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher fails to initialize the Browser bookmarks plugin on launch... regardless of it being disabled.

This bug occurs even when Browser bookmarks plugin is disabled in Flow Launcher settings.

### To Reproduce

1. Open Flow Launcher Settings
2. Go to Plugins in the sidebar
3. Disable the Browser Bookmarks plugin
4. Restart Flow Launcher
5. Observe issue

### Screenshots

Windows notification post crash
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/54220235/d022e1c6-e5f1-487b-87c5-1786b560e4a1)

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.22621.1778

### Error Log
[2023-06-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11727280/2023-06-13.txt)

**Comment by VictoriousRaptor** [comment]
Are you using edge's workspace feature?

**Comment by pratyakshm** [comment]
@VictoriousRaptor I was, it was not active. What I mean to say is, there was a workspace, but it was not open.

And I deleted that workspace too, and the bug still persists.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/54220235/eb785a0d-147a-4751-8a7d-1402f6499f4f)

**Comment by jjw24** [comment]
@pratyakshm is the Bookmark plugin giving you the error when enabled or disabled?

I think this is same as #1216, it may be that the plugin is not properly disabled or the error message is wrong.

**Comment by pratyakshm** [comment]
@jjw24 the error always occurs, turning it on and off does not make a difference.

Might be related to the mentioned issue, but I cannot say for sure.

**Comment by jjw24** [comment]
I have a strong feeling it's related to that. Let's close this one.

**Comment by jjw24** [comment]
Had a quicklook at your log, it looks like the error that caused the failure to load the plugin is from the code that loads Edge bookmarks. Are you by any chance using the new Workspaces feature? If so, I would say it's similar to existing issue 2158.

**Comment by pratyakshm** [comment]
Hey @jjw24 as I mentioned earlier, I deleted all instances of Edge Workspaces, which should bring it back to the default - OFF state.

That being said, I'd like to note that I'm no longer facing the issue on either of my devices.
However, I'll continue testing and let you know of any changes.
