### ISSUE TITLE
BUG: `Open Result Modifier Key` changes behaviour of Explorer plugin

### ISSUE THREAD

**Issue by JamesNZL** [Flow-Launcher/Flow.Launcher#2191]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

#### With `Open Result Modifier Key` set to `Alt`

`Alt`+`2` will open the file.

To me, this makes the most sense—I want to quickly open the file I've just searched for.

#### With `Open Result Modifier Key` set to `Ctrl`

`Ctrl`+`2` will open the file *in explorer*.

This is different behaviour, and not what I'm after.

### To Reproduce

1. Set `Open Result Modifier Key` to `Alt`
2. Use result modifier key to open a file with the `Explorer` plugin
3. Set `Open Result Modifier Key` to `Ctrl`
4. Use result modifier key to open a file with the `Explorer` plugin
   > A different behaviour is observed.

#### With `Open Result Modifier Key` set to `Alt`

`Alt`+`1` will open the file.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/35556b3a-708a-4e19-9d63-220b8cdfa6b5)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/a47e13b6-3d5b-4ff3-84bd-73e1cb0fd55b)

#### With `Open Result Modifier Key` set to `Ctrl`

`Ctrl`+`1` will open the file *in explorer*.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/d1f2dc2a-bdcf-4c4f-ba93-a9088441a1b2)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/1139e07e-ff13-4173-a568-fb6428021ecb)

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.22621.1848

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
I think this is because `ctrl + enter` will open the result differently, and it is only detected by whether ctrl is pressed. @Flow-Launcher/team should we make the special key behavior avaliable to `enter` only?

**Comment by jjw24** [comment]
>of course. And what about special key + mouse click?

Should act the same as special key + enter.
