### ISSUE TITLE
multiple action keywords belonging to the same plugin

### ISSUE THREAD

**Issue by 3roman** [Flow-Launcher/Flow.Launcher#2192]
If a plugin provides a set of functions, can we active these functions by different action keywords belonging to the same plugin.
Different action keywords will call the function accordingly with a if...else.. statement like below.

```CSHARP
public List<Result> Query(Query query)
{

    if (0 == string.Compare("pt", query.ActionKeyword))
    {
        ....
    }
    else if (0 == string.Compare("px", query.ActionKeyword))
    {
        ...
    }
    else if (0 == string.Compare("tx", query.ActionKeyword))
    {
       ....
    }
    
    return ...;
}
```

plugin.json
```JSON
ActionKeywords": ["pt", "px", "tx"],
```

**Comment by jjw24** [comment]
Hi there, yes this is how you could code your plugin. A good (a bit complex C# code) example is the Explorer plugin. This code does exactly what you mentioned in your snippet:
https://github.com/Flow-Launcher/Flow.Launcher/blob/e1c63af06184d3993128da09373307566265e425/Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs#L131-L147

**Comment by jjw24** [comment]
Feel free to reopen if any further questions :)

**Comment by 3roman** [comment]
Great! It worked!
Thanks for the quick reply.
One lesson to share:
If the updated keywords or keywords don't work, try uninstalling the plugin, then create a new plugin folder and copy the relevant stuffs into it.
