### ISSUE TITLE
BUG: Flow Launcher plugins not loading

### ISSUE THREAD

**Issue by postlemons** [Flow-Launcher/Flow.Launcher#2195]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

the plugins store doesn't show any plugins, neither does the PM command, I've tried re-installing the app, but no clue

### To Reproduce

Not sure how did this happen

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/66541630/6a9d3b8c-a1e3-46e8-9cec-a2e6354ad686)

### Flow Launcher Version

1.15.0

### Windows Build Number

[Version 10.0.19045.3086]

### Error Log

<details>

[2023-06-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11823771/2023-06-21.txt)

</details>

**Comment by JohnTheGr8** [comment]
> 21:52:08.9258+03:00 - ERROR - PluginsManifest.UpdateManifestAsync - Http request failed
EXCEPTION OCCURS: System.Net.Http.HttpRequestException: No such host is known. (cdn.jsdelivr.net:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.

Flow is having problems fetching plugin information data because of a network issue... there's many possible causes for this.

Can you access [this cdn.jsdelivr.net link](https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json) ?

**Comment by JohnTheGr8** [comment]
> is it being blocked by the firewall or what?

yes, probably. My assumption is that your system DNS is blocking that domain, but your browser is configured with DNS over HTTPS and bypasses that block...

**Comment by JohnTheGr8** [comment]
try `nslookup cdn.jsdelivr.net 8.8.8.8`

**Comment by JohnTheGr8** [comment]
(assuming you're located in Egypt) I'm seeing other reports of Egyptian ISPs blocking `cdn.jsdelivr.net` so this is 99% that...

**Comment by JohnTheGr8** [comment]
> nice, so VPN?! you gotta be kidding me...

We'll have a solution for this soon alongside #2048 

You can use `pm install direct-url-to-plugin` in the meantime

> now jsdelivr after Patreon... what else?! Google?

😂

**Comment by JohnTheGr8** [comment]
> I can still access the website somehow?! although it should be blocked (I can't access Opera, which means that the filter is applied even with custom DNS)

DNS over HTTPS should bypass the block, check your browser settings

**Comment by JohnTheGr8** [comment]
> chrome://settings/security

is `Use Secure DNS` checked?

**Comment by JohnTheGr8** [comment]
it's probably cached for a while, that's why it works for now

> why'd they ban a CDN from the first place...

don't ask me, man 😄

**Comment by JohnTheGr8** [comment]
No worries.... You can see all available plugins here:

https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/plugin_api_v2/plugins.json

the direct URL is in the `UrlDownload` field (should end with .zip)
