### ISSUE TITLE
BUG: Issue when attempting to build and run Flow Launcher from source

### ISSUE THREAD

**Issue by AlexDavies8** [Flow-Launcher/Flow.Launcher#2198]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I'm having issues when attempting to build from source. The actual build process finishes with no errors, but when running via  Visual Studio (or Rider), an error is thrown, where the Theme resources are being loaded from a non-existent path.
More specifically, the project is located in `D:\Documents\Programming\C#\Flow.Launcher\` and the path it's attempting to load from is `D:\Documents\Programming\Themes\Win11System.xaml`. The built project is at `D:\Documents\Programming\C#\Flow.Launcher\Output\Debug` (or release, same issue with both). 

This happens in both Debug and Release configurations. When attempting to build or publish without running in the debugger, again, the build process completes with no errors, but the application won't start when run via either terminal or double clicking the exe in explorer.

### To Reproduce

1. Clone the repository from the dev branch
2. Open the Solution File in Visual Studio
3. Select FlowLauncher as the startup project (FlowLauncher.Tests appears to be default).
4. Press Run (in either Debug or Release).

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/52012013/2973141c-e1de-4ae6-a970-d472262bd911)

### Flow Launcher Version

dev branch commit e1c63af06184d3993128da09373307566265e425

### Windows Build Number

10.0.22621.1848

**Comment by taooceros** [comment]
Maybe the issue is the path. # may have a different behavior sometimes?

**Comment by AlexDavies8** [comment]
Yep, that appears to have been the issue 👍
