### ISSUE TITLE
Trigger option for custom query hotkey

### ISSUE THREAD

**Issue by usernamehw** [Flow-Launcher/Flow.Launcher#2213]
**Is your feature request related to a problem? Please describe.**

I would like to have an action to be automatically performed when assigning a hotkey (without having to press <kbd>Enter</kbd>).

**Describe the solution you'd like**

New checkbox when adding a hotkey "Trigger search".

**Additional context**

<img width="500" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/9638156/e964cc85-9c56-4bef-9ecb-5817a178d1eb" alt="trigger search checkbox">

**Comment by taooceros** [comment]
@onesounds what do you think about this?

**Comment by EnigmaSolved** [comment]
I am interested in this as well and would find it very useful in some cases!

**Comment by EnigmaSolved** [comment]
It occurs to me that one potential solution to this would be adding `{enter}` to the Built-in Shortcuts as a way to trigger the Enter key.
