### ISSUE TITLE
Alias for log off

### ISSUE THREAD

**Issue by usernamehw** [Flow-Launcher/Flow.Launcher#2214]
It seems that MS renamed `log off` to `sign out` in Windows 10 (and later versions).

It might make sense to add an alias ("subtitle") to include `sign out` words.

**Comment by jjw24** [comment]
Why we closing this one? I think this is a good correction to do.

**Comment by usernamehw** [comment]
I'm tired of bots. And this seems like an easy ~2min fix. If you want - create a new issue.

**Comment by jjw24** [comment]
Oh that's easy, I will add the tag to stop the reminder. Let's keep it open.
