### ISSUE TITLE
[Add Network Mapped Drives]

### ISSUE THREAD

**Issue by metheofanis** [Flow-Launcher/Flow.Launcher#2221]
Windows Indexing does not allow indexing network mapped Drives. e.g. from my QNAP NAS
I wonder if it's possible to add this functionality in flow launcher!
Thanks.

**Comment by deefrawley** [comment]
Flow just uses Windows Indexing or Everything search. If you can set up the search in either of those, Flow will return results. Other than that Flow doesn't do its own indexing.
