### ISSUE TITLE
"open containing folder" should open a new tab in Windows 11

### ISSUE THREAD

**Issue by Ravencentric** [Flow-Launcher/Flow.Launcher#2224]
**Is your feature request related to a problem? Please describe.**
When you click on`open containing folder`, it opens in a new file explorer window.

**Describe the solution you'd like**

Windows 11 File Explorer now supports tabs (much like browser tabs). So `open containing folder` should open in a new tab if an explorer window already exists and fall back to opening it in a new window if one doesn't exist.

**Describe alternatives you've considered**

Having multiple windows open, adding to more clutter

**Additional context**

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/78981416/406b8d96-c95a-4691-9623-c8e9ef4805c9)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/78981416/4e70dda1-48ea-44c3-8053-cdc3d5322406)

**Comment by jjw24** [comment]
We still support Win 10, so when adding this feature, it will need to be compatible by detecting os version.

**Comment by Ravencentric** [comment]
Not stale

**Comment by GeorgeG92** [comment]
this would be awesome
