### ISSUE TITLE
Still Alt + Space after changed hot keys

### ISSUE THREAD

**Issue by imbee10** [Flow-Launcher/Flow.Launcher#2228]
**Point to the corresponding file and line number(s) which could be improved.**

Click on the line number in GitHub to create an anchored link to the corresponding code section. For example:

https://github.com/Flow-Launcher/Flow.Launcher/blob/master/Flow.Launcher/Storage/TopMostRecord.cs#L8

Provide your alternative implementation idea:

```
Code
```

**Comment by Garulf** [comment]
Please see my response here: https://github.com/Flow-Launcher/Flow.Launcher/discussions/2229#discussioncomment-6393116
