### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by pamskye** [Flow-Launcher/Flow.Launcher#2234]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

[2023-07-10.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12006173/2023-07-10.txt)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.19045.3155

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Hi there, please provide what the error is in the problem description.
