### ISSUE TITLE
BUG: Jumping between duplicate items on selecting using the arrow keys

### ISSUE THREAD

**Issue by DrafaKiller** [Flow-Launcher/Flow.Launcher#2238]
### Problem Description

Selecting duplicate items using the arrow keys will make it jump back to the first occurring item.

- It only happens when using the arrow keys, not when using the mouse.
- Both items need to have the same title and subtitle, it won't happen if it has different subtitles.

### To Reproduce

1. Setup 2 or more items with the same displaying text
2. Hover the second item, using the arrow keys
3. Observe how it jumps back to the first occurring item

I'm using TypeScript to make the plugin.

### Screenshots

![Flow Launcher Bug - Duplicate Item](https://github.com/Flow-Launcher/Flow.Launcher/assets/42767829/747ae43b-728e-4c3d-abf1-c7574025c578)

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.22621

**Comment by taooceros** [comment]
The issue seems to be that they shares these results are treated as the same results. However, I am not really sure why this happens as we modify the `SelectedIndex` instead of `SelectedItem`.

**Comment by taooceros** [comment]
I see, I think the issue is from hovering seleciton.

**Comment by taooceros** [comment]
I do have reproduced the bug, but later on failed to reproduce again. I believe different score will also make this behavior disappear, so use a customized score to order it might be a workaround. I don't see that we can fix it easily so maybe we will need to bear with it as it is pretty minor.
