### ISSUE TITLE
Update wiki Flow Launcher APIs docs

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#224]
wiki Flow Launcher APIs docs link is https://github.com/Flow-Launcher/Flow.Launcher/wiki/Flow-Launcher-APIs

I have written some APIs from https://github.com/Flow-Launcher/Flow.Launcher.JsonRPC.Python/blob/master/flowlauncher/FlowLauncherAPI.py.

This doc may help other developers.

I issue this for Are there any new APIs that missed?

**Comment by jjw24** [comment]
I don't see Flow.Launcher.ShellRun, where is that at?

**Comment by Zeroto521** [comment]
There are also see this https://github.com/Flow-Launcher/Flow.Launcher/blob/6617d03c32bba290f9cd93105dea4feb24772820/JsonRPC/wox.py#L55-L59

**Comment by jjw24** [comment]
Oh ok, so that list is for the JsonRPC api right, maybe we need to make it clear in the wiki

**Comment by jjw24** [comment]
just updated the wiki changed name from Flow Launcher API to JsonRPC.Python API and added location of the api. Let me know if it's ok.

I think they are all there, we can always add to it

**Comment by Zeroto521** [comment]
Well, I think the JSON RPC does not belong to Python. 
So why change to **JsonRPC.Python API**?
