### ISSUE TITLE
BUG: After update, cannot open FlowLauncher Settings from search

### ISSUE THREAD

**Issue by pinetreemoonlight** [Flow-Launcher/Flow.Launcher#2241]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Cannot search Flow Launcher for Flow Launcher Settings. This only happens since the latest update. I can still open the settings panel by mouse (right-clicking the search bar --> Settings).

### To Reproduce

1. open Flow Launcher via keyboard shortcut (alt+Spacebar for me)
2. search for "Settings", "Flow Launcher Settings" (I also tried many combinations of "options" and "preferences"
3. the Flow Launcher settings panel does not show up

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.22621.1992

**Comment by taooceros** [comment]
Could you try reinstall flow? Or check whether system command is avaliable in the plugin list.

**Comment by pinetreemoonlight** [comment]
Hi, thanks for the reply. I disabled and re-enabled System Settings plugin, and now it works. Thanks and sorry for the inconvenience.
