### ISSUE TITLE
BUG: Error while querying Everything (as of Flow.Launcher 1.16)

### ISSUE THREAD

**Issue by meiersa78** [Flow-Launcher/Flow.Launcher#2243]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Since Flow Launcher 1.16 was updated on my system (Win 10 Home 22H2, 19045.3208), the integration with Everything (1.4.1.1024) stopped working, i.e. I can't search anything anymore via Flow Launcher.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/94736630/d4e144da-120b-4fc3-8cdd-8483734e75ec)

I tried to disable and re-enable the Everything plugin in FL, restart the system, but the issue persists.

As soon as I downgraded Flow Launcher back to 1.15, the Everything plug-in and search works flawlessly again. I'll keep 1.15 for now.

### Flow Launcher Version

1.16

### Windows Build Number

19045.3208

**Comment by VictoriousRaptor** [comment]
Hi, the Everything plugin is now deprecated and please follow [this guide](https://www.flowlauncher.com/docs/#/plugin-explorer-usage) to set up Everything in Explorer plugin.

**Comment by eyobaaa** [comment]
Having same issue here any clear step by step procedure how to fix it

**Comment by meiersa78** [comment]
> Having same issue here too any clear step by step procedure how to fix it

Go to the Settings in FlowLauncher, enable the 'Explorer' plugin (and disable the 'Everything' plugin while you're there.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/94736630/e34fa1ae-5801-4b6b-afeb-6c6f3774a8c9)

Then open the plugin settings and change it all to 'Everything' (unless you want to use Windows indexing, then leave the middle one on that).

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/94736630/af21dba1-fde4-4412-a3cb-2f4d603e8540)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/94736630/f50be031-e58e-4cf6-8183-a3f5ba95991e)

**Comment by eyobaaa** [comment]
> > Having same issue here too any clear step by step procedure how to fix it
> 
> Go to the Settings in FlowLauncher, enable the 'Explorer' plugin (and disable the 'Everything' plugin while you're there.
> 
> ![image](https://user-images.githubusercontent.com/94736630/255321776-e34fa1ae-5801-4b6b-afeb-6c6f3774a8c9.png)
> 
> Then open the plugin settings and change it all to 'Everything' (unless you want to use Windows indexing, then leave the middle one on that).
> 
> ![image](https://user-images.githubusercontent.com/94736630/255321861-af21dba1-fde4-4412-a3cb-2f4d603e8540.png)
> 
> ![image](https://user-images.githubusercontent.com/94736630/255321874-f50be031-e58e-4cf6-8183-a3f5ba95991e.png)

Problem solved
