### ISSUE TITLE
Both flow launcher installer and exe portable detected as viruses by virustotal

### ISSUE THREAD

**Issue by Theoldnation** [Flow-Launcher/Flow.Launcher#2244]
Both are detected by 2 antiviruses by yomi hunter and C2AE, i had classified this issue as code review as didn't had much of a choice to report this
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/76594044/0babb8f0-76c2-468e-9cf4-50fef2180cc4)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/76594044/1018a4bb-e4cd-404a-8b86-a3a348eb1a28)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/76594044/9b7badb2-af70-4c84-bb24-d637ee3e7995)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/76594044/c2fb6f86-6ae7-48e9-92c1-5b94ba5d8cef)

**Comment by deefrawley** [comment]
Flow Launcher does not contain any viruses. This is a false positive. It would be appreciated of you could report it as such to your AV vendor.

**Comment by jjw24** [comment]
Hi there, they would be false positives. 

We have had one or two false positives from VirusTotal's vendors prior to this before and I have contacted these individual vendors to rectify the false positives, have not heard back from them yet.

As long as you have downloaded from flow's GitHub repo, it will be safe.
