### ISSUE TITLE
BUG: All plugins give an error

### ISSUE THREAD

**Issue by WhereIsPink** [Flow-Launcher/Flow.Launcher#2247]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When I install any plugin after reloading the program I get a message that the plugin failed to load and it gives errors. This happens with absolutely any plugin. What can I do about it?

### To Reproduce

1. Install any plugin from plugins store
2. Wait for Flow Launcher restarted

### Screenshots

![chrome_Uxl66hlsny](https://github.com/Flow-Launcher/Flow.Launcher/assets/124764727/f071cafa-9679-420f-9ae4-84439ddcc074)

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.19043.1200

### Error Log

[2023-07-19.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12093365/2023-07-19.txt)

**Comment by WhereIsPink** [comment]
Log file doesn't loading, so here:

https://pastebin.com/Wb67LNJR

**Comment by JohnTheGr8** [comment]
What plugin other than the Unity one is giving you errors? 

Or do you mean you keep getting the same error (about the Unity plugin) on each restart?

**Comment by WhereIsPink** [comment]
> What plugin other than the Unity one is giving you errors?
> 
> Or do you mean you keep getting the same error (about the Unity plugin) on each restart?

Any plugin cause this error

**Comment by jjw24** [comment]
Looks like Unity plugin is causing this, could you try removing it.
