### ISSUE TITLE
BUG: Position does not reset on width change

### ISSUE THREAD

**Issue by Erik-vdb** [Flow-Launcher/Flow.Launcher#2248]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When you change the width of the search bar, it's position remains unchanged. Since the searchbar's origin for position is top left corner, the bar ends up offset to the right unless you change position to, say Center Top and back to center.

This behavior is most noticeable if your serachbar is positioned to the center or to the right

### To Reproduce

1. Change search bar width
2. Change position to any other option
3. Return position to desired position

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/88503855/dafd9226-e9ea-43c0-a607-c4c2d08a6fe3)
Before width change

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/88503855/9cbb8028-606d-469c-ac47-3f67ebcdaa0f)
After width change

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/88503855/106ec844-624d-4d70-a8e0-32f74e40274c)
Manual position reset by changing it to Center Top

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/88503855/29f213f3-160f-493a-aa47-8b1c89f1f691)
Re-position it to center

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.22621.1702

**Comment by jjw24** [comment]
Hi there, doesn't it reset the position after width change if you hide then show the search window?

**Comment by Erik-vdb** [comment]
> Hi there, doesn't it reset the position after width change if you hide then show the search window?

In order to change the width, I need to

**Comment by deefrawley** [comment]
Please update to the latest version and if the problem persists we can reopen. Thanks.
