### ISSUE TITLE
Bring to front (similar to MacOS spotlight or alfred)

### ISSUE THREAD

**Issue by raicubogdan** [Flow-Launcher/Flow.Launcher#2256]
**Is your feature request related to a problem? Please describe.**
Every time I search an app that is already opened and tap enter, a new instance of the app is created. Coming from a Mac environment, this is something counterintuitive to me. If there is already an option for it, it's quite well hidden.

When I try to bring to front all instances of an app, a new instance of the app is created and that is frustrating for me as I have a habit of switching apps on Mac by using spotrlight/alferd. If the app already has this option, then the interface isn't really helpful in bringing it to attention.

**Describe the solution you'd like**
I want to be able to set an option whether FlowLauncher opens a new instance of an app or brings to front all opened instances when I search for it and press enter. It's a general feature that should be available by default, as it gives the user more freedom to customize the app's behavior.

**Describe alternatives you've considered**
Momentarily, there is no alternative that has this behavior from what I know. There is [keypirinha](https://www.berrycast.com/conversations/728e68f6-1fa9-5d81-af85-2766e8bc2b87), but i have to always do one more extra step (typing swt.) to switch, which breaks the flow.

**Comment by jjw24** [comment]
Hi there, try the WindowWalker plugin, it will achieve this.

**Comment by raicubogdan** [comment]
Heh, thanks, it really does what I want if I give it a priority of 5.
