### ISSUE TITLE
Calculator: add setting to unify decimal separators

### ISSUE THREAD

**Issue by SaalBC** [Flow-Launcher/Flow.Launcher#2257]
In many other languages the comma is used as a decimal separator, but in a programming environment always the dot is used. So there are many instances where the decimal separators are mixed.

It would be nice to have a setting to unify these. So that the comma is automatically replaced with a dot in the calculation.

Example:
0.5\*3000\*0,24

Current result is no output

Should be
0.5\*3000\*0.24 = 360

**Comment by jjw24** [comment]
Hi there, the plugin should have a settings already to change this.

**Comment by SaalBC** [comment]
The decimal separator can be changed, but only one is used and the other one is not converted.
Another solution would be to add a "Both" option to the dropdown:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/19954128/6b7fbbc5-52d1-4e6a-83a4-9d999759a044)
