### ISSUE TITLE
BUG: Runned process throught FlowLauncher copy its System Env Variables

### ISSUE THREAD

**Issue by NiTiSon** [Flow-Launcher/Flow.Launcher#2263]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

OS: Windows 10

The new launched processes uses the old Flow.Launcher system environments instead of modified system ones

### To Reproduce

1. Launch FlowLauncher
2. Edit/Remove/Add system environment
3. Launch anything via Flow

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.19045.2965

### Error Log

// LOGS NOT REQUIRED

**Comment by jjw24** [comment]
Hi, closing as this is a duplicate issue of https://github.com/Flow-Launcher/Flow.Launcher/issues/1602.

Feel free to reopen if not the case.
