### ISSUE TITLE
Better window filtering

### ISSUE THREAD

**Issue by DatHypnoboi** [Flow-Launcher/Flow.Launcher#2268]
**Is your feature request related to a problem? Please describe.**

I frequently try to use my activation hotkey while watching a video in fullscreen, resulting in it failing since I have the "Ignore hotkeys in fullscreen mode" setting enabled.

**Describe the solution you'd like**

It would be useful to be able to do more than just disabling the hotkeys on fullscreen windows. Ideally this would be some sort of enhanced filtering system, such as setting a window title whitelist/blacklist.

**Describe alternatives you've considered**

A simpler fix would be to just have a hotkey to enable or disable the main hotkey. This hotkey could be set to a less common and convenient combination, as it would be used less often.

**Comment by jjw24** [comment]
Dup of #1998

Closing. Please track over at the issue for updates.
