### ISSUE TITLE
BUG: Sleep(System Commands) don't work

### ISSUE THREAD

**Issue by Maoyeedy** [Flow-Launcher/Flow.Launcher#2280]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

"Sleep" does nothing, but "Restart", "Shutdown", "Log off", "Lock" all works fine.

### To Reproduce

1. Enable "System Commands" plugin
2. Search for "Sleep"
3. Nothing happens upon enter or left click

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100255436/1657732f-e403-4b4e-a9e2-45e41c70f07f)

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.22621.0

### Error Log

1. Clear existing logs
2. Exec the action again
3. No log printed to \UserData\Logs\

**Comment by deefrawley** [comment]
Works fine for me. 
Can you send your PC to sleep from the Windows Start menu?

**Comment by Maoyeedy** [comment]
@deefrawley 

I was using a scoop installed portable version:
1. Upgraded to the latest 1.16.1, dont work.
2. Run as admin, dont work.
3. Tried a fresh install, using v1.16.1/Flow-Launcher-Setup.exe, dont work.
4. Reset windows power plan settings to default, dont work.

However, powerbutton sleep and startmenu sleep all works fine.

I'm on Rog Strix G16 Laptop, me myself didn't find any BIOS setting that could prevent flowlauncher executing the sleep command.

**Comment by Maoyeedy** [comment]
@deefrawley 

I found a post that claim running "rundll32.exe powrprof.dll, SetSuspendState Sleep" in cmd would send windows to sleep, however my laptop won't respond to that command.

Seems like a hardware issue, not flowlauncher's fault, sry🥲
