### ISSUE TITLE
BUG: Service is not running for Everything 1.5

### ISSUE THREAD

**Issue by One1Tick** [Flow-Launcher/Flow.Launcher#2284]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I am using the Everything search engine with flow launcher. It works fine with the latest version of Everything but it tells that the service is not running with the latest **beta** release of Everything (beta-1.5.0.1352a (x64)) that I always use for many reasons. 

Is it a config issue or the beta version is not yet supported ?

Thanks for feedback.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![mmc_fW5261OOGr](https://github.com/Flow-Launcher/Flow.Launcher/assets/35428340/9627eb12-96fc-47c3-9f67-aee458b994d4)

### Flow Launcher Version

1.16.1

### Windows Build Number

Microsoft Windows [version 10.0.22621.2070]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Everything 1.5 isn't supported. See [this link](https://www.flowlauncher.com/docs/#/plugin-explorer-usage?id=using-everything) for more info

**Comment by One1Tick** [comment]
> Everything 1.5 isn't supported. See [this link](https://www.flowlauncher.com/docs/#/plugin-explorer-usage?id=using-everything) for more info

That's clear, thanks for your answer. However, there nothing in this [this link](https://www.flowlauncher.com/docs/#/plugin-explorer-usage?id=using-everything) stating 1.5 is not supported or I missing something ?

**Comment by deefrawley** [comment]
@One1Tick  sorry it was at the top of the page I linked which wasn't very clear. This is the github issue that discusses 1.5

https://github.com/Flow-Launcher/Flow.Launcher/issues/1716

**Comment by One1Tick** [comment]
@deefrawley It works perfectly, thx!
