### ISSUE TITLE
[Feature request] Preview more files

### ISSUE THREAD

**Issue by ThePython10110** [Flow-Launcher/Flow.Launcher#2285]
I would love it if the Explorer plugin allowed users to preview more kinds of files (especially text files) in the preview pane. It would be especially nice if there was an editable list of file extensions that would count as "previewable" text files, sort of like the screenshot below (from Fluent Search).
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/87204246/168e053d-04f1-43c4-b0d0-36307f149207)

**Comment by jjw24** [comment]
QuickLook will be supported in version 1.19.0. In the mean time you can try it out with this build of [portable version](https://ci.appveyor.com/api/buildjobs/fg7j4dffpc9eqbmd/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip)
