### ISSUE TITLE
BUG: Preview window(F1) stays draggable while hidden.

### ISSUE THREAD

**Issue by Sneakpeakcss** [Flow-Launcher/Flow.Launcher#2289]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

While in hidden state the border is still draggable, possibly blocking mouse actions if you manage to hit the perfect spot.

### To Reproduce

https://github.com/Flow-Launcher/Flow.Launcher/assets/77424331/c8ad9255-719e-4744-8578-f2f72629bfb9

### Flow Launcher Version

1.16.1

### Windows Build Number

10.0.19044.1826

**Comment by onesounds** [comment]
Fixed in #2354.
