### ISSUE TITLE
Space between Pinyin translation

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#229]
Should we add space as the separation of words translated to Pinyin? So that it won't be possible to use `gd` to search something like `DingDing`, which should not be the target.

**Comment by jjw24** [comment]
i dont use Pinyin, is it natural to use space when typing pinyin?

**Comment by taooceros** [comment]
Well, it depends on personal habit. I don't type space when searching, but the fuzzy allow us to not type space but search, only the score may be lower. I just feel that we shouldn't treat the translation as one word so that some search only containing the ending of one translation and beginning of next translation won't result in a high score.

**Comment by jjw24** [comment]
> Well, it depends on personal habit. I don't type space when searching, but the fuzzy allow us to not type space but search, only the score may be lower. I just feel that we shouldn't treat the translation as one word so that some search only containing the ending of one translation and beginning of next translation won't result in a high score. 

Oh ok, you mean when Chinese is translated to Pinyin, add spaces to the translated Pinyin? Like translated to 'Ni Hao Ma' instead of 'NiHaoMa'?

**Comment by taooceros** [comment]
Yes

**Comment by jjw24** [comment]
I think it makes sense, string matcher would treat the translation with spaces as substrings instead of one single string right. Yeah sounds good
