### ISSUE TITLE
Accidentally deleted the built-in plugin

### ISSUE THREAD

**Issue by Curicano** [Flow-Launcher/Flow.Launcher#2294]
Accidentally deleted the built-in plugin "Programs". How do I restore it by reinstalling or is there an easier way?

**Comment by jjw24** [comment]
Hi there, at the moment there is not an easy way to install just the plugin itself back, you will have to reinstall. 

If you are not running portable mode, just reinstall flow, your userdata will be kept. If you are running in portable mode, you need to re-download the portable version and move your userdata from existing to this new one.

Relates to #1984
