### ISSUE TITLE
Issue in README.md

### ISSUE THREAD

**Issue by HorridModz** [Flow-Launcher/Flow.Launcher#2300]
https://github.com/Flow-Launcher/Flow.Launcher/blob/da4ec61de0898b683ff9b404740eddb6b7cccc44/README.md?plain=1#L19

```
Dedicated to making your **workflow flow** more seamless.
```

Is `workflow flow` intentional, or a typo? Maybe this is intentional, but it sounds very redundant IMO. I would recommend changing `seamless` to `seamlessly` or changing `workflow flow` to `workflow`.

**Comment by flooxo** [comment]
Is there already a decision for this issue?
