### ISSUE TITLE
BUG: Environment variables unrecognized on path strings

### ISSUE THREAD

**Issue by Novack** [Flow-Launcher/Flow.Launcher#2301]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Environment variables on the query input field work when they are isolated, but not when they are part of a larger path string.

**Case in point:**

`%localappdata%` will work correctly:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1981463/45cdb8e0-76d8-401d-9e6d-3e62da2bdfbf)

`%localappdata%\Unity\Editor\` is not anymore considered a path
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1981463/dc52ada5-35f7-4641-a407-0391a6bccd3e)

### To Reproduce

Use the example described, should repro the same behavoiur.

### Flow Launcher Version

1.16.1 & 1.18.0

### Windows Build Number

10.0.19045.3324

**Comment by Novack** [comment]
...

**Comment by deefrawley** [comment]
Please update to the latest version and if the problem persists, we can reopen. Thanks

**Comment by Novack** [comment]
> Please update to the latest version and if the problem persists, we can reopen. Thanks

There are no changes whatsoever on latest version (1.18.0), bug remains, please reopen.

Btw, randomly closing issues without any kind of verification, is a usual corporate malpractice that I really hope does not translate to open source projects.

**Comment by deefrawley** [comment]
Hi, this issue has been re-opened but please don't throw such ridiculous "usual corporate malpractice" hyperbole at a team that is producing and managing an awesome tool for free, in their own time. The issue was six months old with several updates happening since then, This was part of a repo issue cleanup and reopening an issue is not a big deal. As an open source project feel free to jump in and add a PR to solve this issue.

**Comment by Novack** [comment]
The only ridiculous thing here, was is closing issues without any reason or purpose than testing waters to make it easier on yourself, at the expense of the reporters (which **also** take time of their lives to create the reports).

For what matters, dont throw at us the  shallow "awesome tool for free" bs. Im also an open source projects contributor, dont need you to explain what it means, and is not related **at all** with poor practices like closing issues at your convenience without proper underlying work.

In fact such malpractice goes **against** the quality of the project **and** the QoL of the people _actually_ maintaining the project, so we shall keep denouncing it as malpractice, be from microsoft, or from a small floss project on the interwebs.

Have a nice day.

**Comment by jjw24** [comment]
Hi there, you are correct, this bug still persists and the right behaviour should be the ability to use an env variable as part of a path. This issue needs to be addressed.

deefrawley is doing this as part of wider clean up of orphaned and potentially resolved issues, and this one may have been mistakenly caught in the process. I know it is frustrating when a ticket gets closed without the correct course of action, so it is absolutely ok to request for it to be reopened if we get it wrong and we will readdress it, but please don't extend words beyond this.
