### ISSUE TITLE
Fix flowlaucher

### ISSUE THREAD

**Issue by Bii1305** [Flow-Launcher/Flow.Launcher#2304]
C:\Users\bilun\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-08-22.txt

**Comment by jjw24** [comment]
Hi, please let us know what error are you getting, how to reproduce it and a screenshot of the error.

**Comment by ThePython10110** [comment]
It seems that you're still using an old version of Flow Launcher (1.14.0); maybe try updating.
