### ISSUE TITLE
BUG: Plugin Store is empty

### ISSUE THREAD

**Issue by Hit4man47** [Flow-Launcher/Flow.Launcher#2307]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The Plugin Store empty and i cannot install any plugin via pm install cmd

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/94435395/f4b7f841-1c2e-434d-95a7-127f85a9c9a0)

### Flow Launcher Version

1.16.1

### Windows Build Number

23H2 25931.1010

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by csmikle** [comment]
So it's not just me then. I did all kind of reinstalling

**Comment by JohnTheGr8** [comment]
Seems like a json issue, possibly related to commit https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/commit/c005f0787c21a1246cc6acab7744af0c2cb0962d#diff-18d7f9b905f83805c42db6d239a7fb0207d4b32193202eb13ba077caed424c3c which set a bunch of `LatestReleaseDate` fields to null. @Garulf could you take a look at the update script?

**Comment by swg168** [comment]
same problem

**Comment by jjw24** [comment]
This is a wide spread issue affecting everyone. We are working on fixing this.

**Comment by Hit4man47** [comment]
ok sure

**Comment by jjw24** [comment]
Fixed.
