### ISSUE TITLE
Program - Add option "Open final path"

### ISSUE THREAD

**Issue by Inirdin** [Flow-Launcher/Flow.Launcher#2308]
**Problem**
When opening the context menu of searched program the "open containing folder" opens folder where the .lnk file is. That is fine, but it would be great if there was also option to open containing folder of the actual .exe where the .lnk is pointing to.

Current items in context menu:
![flow launcher context menu showing the "open containing folder" option](https://i.imgur.com/F631lqX.png)

**Solution**
Add option "Open final path" in the context menu to Program plugin.

**Comment by jjw24** [comment]
Dup #2390
