### ISSUE TITLE
Disable cursor hover interaction when the panel first shows

### ISSUE THREAD

**Issue by PRO-2684** [Flow-Launcher/Flow.Launcher#2314]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I open the panel and my cursor, on the center of the screen, *chooses* an item for me. Note that this behavior is unintended, because I haven't moved my mouse at all. I've got to use keyboard to navigate to the top of the list.

**Describe the solution you'd like**

Disable cursor hover interaction when the user opened the launcher, and enable it again when user has moved or clicked their mouse.

**Describe alternatives you've considered**

Hovering over an item doesn't **select** it, just hint that it will be invoked if you click. Like in the screenshot of Windows Explorer below, my cursor was hovering over "map.jpeg". But when I hit enter, "alternative.jpg" will be opened instead. Themes will have to be updated though.

![alternative](https://github.com/Flow-Launcher/Flow.Launcher/assets/54608551/04818fb7-0674-43fa-9e36-f9354fbbf924)

**Additional context**

Here's a gif that will address the issue (hopefully):

![record](https://github.com/Flow-Launcher/Flow.Launcher/assets/54608551/798c2e85-a000-4cd5-b7e5-2935e43c854b)

When I type "c", it is most likely that I'd like to run `Clash`, but my cursor made the launcher select the third item, `LocalSend`.

**Comment by Garulf** [comment]
Hey @onesounds you have any thoughts on this?

**Comment by onesounds** [comment]
> Hey @onesounds you have any thoughts on this?

I agree that this is a problem. It needs to be fixed. This also happens in keyboard scrolling situations, so we need proper logic. I tried to fix it before and failed.

**Comment by onesounds** [comment]
ref : https://stackoverflow.com/questions/5235118/wpf-listbox-scrolling-with-keyboard-issue

**Comment by CartCaved** [comment]
Would it an approach to disable the mouse (cursor) when panel opens, and have it be re-enabled if the user moves it?
Or separate the interactions, so that only the mouse click runs what is under the cursor and enter runs what has been selected with the keyboard?

**Comment by jjw24** [comment]
I think this is the same issue in https://github.com/Flow-Launcher/Flow.Launcher/issues/2595.

@PRO-2684 or @CartCaved could you disable animations and see if the same problem still occurs

**Comment by jjw24** [comment]
Since we got the right cause in 2595, let's track this issue over there instead.
