### ISSUE TITLE
More flexible fuzzy searching with regard to word order

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [Flow-Launcher/Flow.Launcher#2315]
I was thinking about tagging my bookmarks with keywords so I could more easily find them in Flow Launcher. For example, I would have a bookmark with the following keywords in the title `myproject,backend,logs,staging` that links to the backend logs on the staging environment.

Unfortunately, Flow Launcher doesn't find the bookmark when the entered keywords are out of order. For example the query `b myproject logs staging` will find the bookmark:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1670232/a9c3d809-e5ab-48dc-9ab6-13ef65652aff)

but the query `b myproject staging logs` will not:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1670232/6bdaf779-34ec-475f-8972-edba12f6369a)

Obviously (?) for my use case, it would be more flexible if both queries would find the bookmark.

**Comment by taooceros** [comment]
you can use space instead of `,`. That will allow the order to be changed.
