### ISSUE TITLE
Let the program start in the directory where it is located

### ISSUE THREAD

**Issue by huoyan1231** [Flow-Launcher/Flow.Launcher#2316]
Programs launched by the Flow launcher now seem to work in a fixed working directory, which most of the time breaks the program's file integrity leading to some "cannot find file" errors

**Comment by deefrawley** [comment]
If you're executing them through the Explorer plugin you could try this setting

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/18594055/89dd9a05-fd42-4e65-b202-3de9c48bf1e7)
