### ISSUE TITLE
Copy file/folder path: built-in hotkey `ctrl-shift-c` and remove notification.

### ISSUE THREAD

**Issue by Maverickx0** [Flow-Launcher/Flow.Launcher#2329]
I'm used to fill the file path for some app's config or go to one deep path folder to handle something. Based above requirement, I need to get the file/folder path quickly. 

I has known that I can do this by `ctrl + o` with `alt + 4` key combination and get notification when I copy done successfully. But it has some questions:

* Two key combination is slow.
* Copy notification will get the bad sense of delayed feedback and it's none-necessary. 

**For Q1**, I think copy file/folder path for most people is necessary. So, I hope that you add one built-in hotkey like `ctrl-shift-c` for copy file/path.

**For Q2**, When I copy successfully, the search panel will be close correctly. So, we don't need to get the notification.

Lastly, thanks for the nice app you brought, I love it.

**Comment by TheBestPessimist** [comment]
This was implemented in https://github.com/Flow-Launcher/Flow.Launcher/pull/2612, so we can close it 🎉
