### ISSUE TITLE
Allow Plugins to utilize the CancellationToken from MainThread

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#233]
**Discussion**

Should we allow plugins to utilize the CancellationToken from Flow so that they can cancel their works properly when the query is updated.
This can be done by adding another method to IPlugin like QueryAsync with an default implementation pointing back to the Original Query method since c# 8 has added that feature so that we can expand the interface without potential compatibility issue.
Also, should we change Parallel.Foreach(plugins,=>) to Task.run for each plugin so that every plugin can query at the same time theoretically instead of waiting potential previous one due to potential query before it on work splitting for Parallel.Foreach. Or we can simply make all things async that change the result type of the potential new QueryAsync method to Task<Result> and make everything async.

**Comment by jjw24** [comment]
@taooceros is there anymore to do on this one?

**Comment by taooceros** [comment]
> @taooceros is there anymore to do on this one?

That's done!

**Comment by jjw24** [comment]
Legend!
