### ISSUE TITLE
BUG: Custom Query Shortcuts expansion, does not allow addition input text, e.g. text to translate

### ISSUE THREAD

**Issue by bluckholl** [Flow-Launcher/Flow.Launcher#2337]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Custom Query Shortcuts expansion, does not allow addition input text, e.g. text to translate

### To Reproduce

1. Add custom query shortcut: "en " expansion: "tr en fr "
2. type in flow launcher: "en hello"
3. google translate search "en hello" instead of translate hello to French

### Screenshots

After typing customer query shortcut
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/2509820/9bc72fea-8d39-4302-b28e-5410d5e0712c)

After typing addition text to translate - switch to google search 
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/2509820/c0314a9b-61f0-41f1-81fa-d59716acab32)

The expected:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/2509820/36dec79c-2851-485b-a970-297a4f4efce4)

### Flow Launcher Version

1.16.1

### Windows Build Number

10.0.22621.2134

**Comment by taooceros** [comment]
try `@en hello`

**Comment by bluckholl** [comment]
It works great, thank you :)
I didn't see this option in docs
🙏

**Comment by jjw24** [comment]
> try `@en hello`

If I remember correctly we didn't need to use `@` before?

**Comment by taooceros** [comment]
> > try `@en hello`
> 
> If I remember correctly we didn't need to use `@` before?

@ is for partial shortcut
