### ISSUE TITLE
Specify the type of search results for "everything"

### ISSUE THREAD

**Issue by susanooxyz** [Flow-Launcher/Flow.Launcher#2338]
Hello, can you please add the functionality of "everything" below?
![Snipaste_2023-09-13_10-59-09](https://github.com/Flow-Launcher/Flow.Launcher/assets/6442944/87828ef6-7cd4-419f-a63f-8e10ae514d8d)

**Comment by jjw24** [comment]
Hi there, is this a Everything v1.5 feature?

**Comment by taooceros** [comment]
I think you can still do it by adding a prefix for the type.

**Comment by gisturbance** [comment]
Already mentioned in https://github.com/Flow-Launcher/Flow.Launcher/issues/1831 and https://github.com/Flow-Launcher/Flow.Launcher/issues/2009.
