### ISSUE TITLE
Icon not updated

### ISSUE THREAD

**Issue by vemundha** [Flow-Launcher/Flow.Launcher#2339]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

The icon when searching for "term" ⇒ terminal ⇒ is not updated.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/5e231bdb-2dd2-4ae6-a48a-66b2bb95e17e)

### To Reproduce

1. Alt-space
2. "term"10
See image
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/5e231bdb-2dd2-4ae6-a48a-66b2bb95e17e)

Also see image from Win11 start menu
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/0eaa066b-a862-46d6-b1bc-24de1e5fcd80)

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/5e231bdb-2dd2-4ae6-a48a-66b2bb95e17e)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/0eaa066b-a862-46d6-b1bc-24de1e5fcd80)

### Flow Launcher Version

1.16.1

### Windows Build Number

Microsoft Windows [Version 10.0.22631.2338]

### Error Log

See today's log file
[2023-09-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12594737/2023-09-13.txt)

**Comment by VictoriousRaptor** [comment]
Dup #2345.
