### ISSUE TITLE
BUG: Flow.Launcher.ChangeQuery with requery: true expected to change query while keeping flow launcher visible

### ISSUE THREAD

**Issue by bluckholl** [Flow-Launcher/Flow.Launcher#2346]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow.Launcher.ChangeQuery with requery: true expected to 
1. Change query while keeping flow launcher visible 
2. plugin callback  def query(self, query) with the new query

Actual:
Flow launcher is hidden after action pressed (enter / click), 
Only when I trigger flow launcher again ( via flow launcher hoteky) the new query shows and callback is called

### To Reproduce

Add callback with python:

 "Title": "test1 Hello World, this is where title goes. {}".format(('Your query is: ' + query , query)[query == '']),
    "SubTitle": "This is where your subtitle goes, press enter to open Flow's url",
    "IcoPath": "Images/app.png",
    "JsonRPCAction":{"method":"Flow.Launcher.ChangeQuery", "parameters":[f"testing",True] }

### Screenshots

![Code_xrpgjECad6](https://github.com/Flow-Launcher/Flow.Launcher/assets/2509820/777effb7-9800-4220-824b-084c62101ce6)

### Flow Launcher Version

1.16.1

### Windows Build Number

10.0.19044.3086]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by bluckholl** [comment]
I saw in one plugin there is another parameter **dontHideAfterAction** that is working for this purpose,
the below is working - it change flow launcher query immediately while keeping flow launcher visible:

"Title": "test1 Hello World, this is where title goes. {}".format(('Your query is: ' + query , query)[query == '']),
"SubTitle": "This is where your subtitle goes, press enter to open Flow's url",
"IcoPath": "Images/app.png",
"JsonRPCAction":{"method":"Flow.Launcher.ChangeQuery", "parameters":[f"testing",True],  **"dontHideAfterAction": True** }

**Comment by taooceros** [comment]
This is kindly the limitation of JsonRPC v1 as we always need an execution to trigger a flow api (which will hide according to `dontHideAfterAction`). V2 will make the behavior more consistent #1353 .
