### ISSUE TITLE
Calendarweek in the Date Format picker ISO 8601

### ISSUE THREAD

**Issue by w00kee** [Flow-Launcher/Flow.Launcher#2348]
**Why?**
In German work Environments (and I think internationally as well) it is common to set Deadlines with calendarweeks. Therefore, I quite often need the current calendarweek.

**How?**
I propose the Integration of ISO 8601 calendarweek standard in the Date and Time Feature.
Implementation Details:
Add YYYY-Www and  YYYY-Www-D to the Date Format Picker (maybe Some More Variations That Include Month and Day aswell)

**Describe alternatives you've considered**
This could also be done as a Plugin however I dont need the week to be copyed to my Clipboard or anything. I Just want to know it without visiting https://www.aktuelle-kalenderwoche.org/ ( this is a good reference on how the Calendar week is defined). As there are already different Formats supported for the Date, I think the proposed solution is the cleanest.

**Context:'**
There are other norms for the calendarweek, beside ISO 8601 those should be implemented as well.
They differ in the Day a calendarweek starts (Sat, Sun, Mon). 
And  in what the first calendar week of the year is: 

1. The one containing the 1. Jan starting with it being shorter then the other Calendarweeks 
2. The First week containing at least 4 days of the Year (e.g. if the 1. Jan is a Thursday the 29-31 Dez. are part of the first Calendarweek of the new Year)

**Comment by VictoriousRaptor** [comment]
Hi, if you want extra datetime formats you can navigate to Flow's settings folder (by typing `flow launcher userdata folder` in flow or open in in settings->about), exit Flow and then manually edit `DateFormat` entry.

**Comment by w00kee** [comment]
Sadly C# does not support any Week numbering system. https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings does not List this functionality. Implementation is gonne be a lot more anoying than.
