### ISSUE TITLE
Feature request [24 Hour time format]

### ISSUE THREAD

**Issue by Hellestyle** [Flow-Launcher/Flow.Launcher#2355]
**Is your feature request related to a problem? Please describe.**
No. but,
A 24 hour clock setting should be added.

**Describe the solution you'd like**

A setting in the configuration oage where we can toggle between 12/24 time formats

**Describe alternatives you've considered**

A auto setting that reads time from windows

**Additional context**

instead of 01:54 -> 13:54

**Comment by kubalav** [comment]
There are the settings for 24-time format. All formats start with H or HH are 24 hours format.

**Comment by deefrawley** [comment]
Closing as this functionality is included
