### ISSUE TITLE
BUG: Flow Launcher isn't learning what letters match to a specific program

### ISSUE THREAD

**Issue by theblackrock1845** [Flow-Launcher/Flow.Launcher#2366]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

When I enter ex Excel is number four on the list.  But no matter how many times I arrow down and select Excel Flow Launcher doesn't remember or learn that I want certain programs to open using specific letters.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/7660678/de20155b-6b86-4950-98c1-71dcef480055)

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/7660678/43344997-a38a-4b0b-91ec-8a8a400cf37c)

### Flow Launcher Version

1.16.2

### Windows Build Number

22H2 22621.1555

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by theblackrock1845** [comment]
I am sorry.  I don't understand how to ignore the .link target file extension.

**Comment by VictoriousRaptor** [comment]
> I am sorry. I don't understand how to ignore the .link target file extension.

Nevermind. I mean the linked PR is going to solve this issue. Just wait for our next release.
