### ISSUE TITLE
BUG: Impossible to uninstall a plugin that has been removed from the Plugin Store ('Notion Search')

### ISSUE THREAD

**Issue by oeloo** [Flow-Launcher/Flow.Launcher#2382]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

It is not possible to uninstall a plugin that has been removed from the Plugin Store ('Notion Search') :
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/98819304/754b5e0f-f7e2-414f-ab35-23cbe02a0b0f)

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/98819304/a2d459aa-765d-4faa-9177-ec9066b94a46)

### Flow Launcher Version

1.16.2

### Windows Build Number

Windows 11

### Error Log

This is problematic because this plugin is causing an issue, each time Flow Launcher is started (even though this plugin is turned Off in Flow Launcher, as you can see in the above screenshots):
"Fail to Init Plugins
Plugins: Notion Search - fail to load and would be disabled, please contact plugin creator for help"
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/98819304/6f9f2234-ffcf-49da-958d-1154534dcad8)
The plugin creator is not here for help (the corresponding [url](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch) is no longer working)

**Comment by jjw24** [comment]
Hi there, you need to uninstall it not turn off. Click on the bin icon below the plugin or `pm uninstall notion`.

**Comment by jjw24** [comment]
Closing. Feel free to reopen if problem persists.

**Comment by oeloo** [comment]
Thank you pm uninstall notion worked
