### ISSUE TITLE
isssue in Browser Bookmarks using Brave 

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#2384]
### Discussed in https://github.com/Flow-Launcher/Flow.Launcher/discussions/1618

<div type='discussions-op-text'>

<sup>Originally posted by **logann99** December 12, 2022</sup>
Browser Bookmarks its not working for me in V1.9.5 and 1.9.4
![image](https://user-images.githubusercontent.com/101401329/206919079-276ac8d4-7478-4cfd-8d00-9ca345df29f6.png)
</div>

**Comment by jjw24** [comment]
Closing since this is an old issue, please reopen if still not working.

**Comment by zhj9709** [comment]
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/b4ae4835-e271-4891-872b-70d74b74bbb0)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/3e9064b8-5be2-4db1-836e-7442d13c4e60)

version 1.16.2， I'm using Brave, too.

But when I re-checked Chrome it went back to normal

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/fd96f8e2-0469-420c-9376-913396e70e45)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/e00d548a-d49c-4244-8811-e89261189bde)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/79e0030c-eac5-4b62-8046-d177ab2c165c)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/e0a74ae6-5994-49fb-9426-b8ba6aa5b4d8)
