### ISSUE TITLE
Cannot open some windows apps through Flow Launcher

### ISSUE THREAD

**Issue by GravakeAzure** [Flow-Launcher/Flow.Launcher#2393]
I installed snapchat and spotify from the windows store and they are not showing up in Flow Launcher when I am trying to open them. I do not know why is this happening. I though maybe it was because they are installed through the windows store but whatsapp is opening fine. So I do not know what is the issue here and why it is not able to open those applications from the flow launcher.

**Comment by taooceros** [comment]
Could you try `reload plugin data`?

**Comment by GravakeAzure** [comment]
How can I do that can you guide me as I tried to restart the flow launcher and it still did not work. Whenever I am trying to search Snapchat and some other applications they do not show up in the flow launcher search bar.

**Comment by VictoriousRaptor** [comment]
> How can I do that can you guide me as I tried to restart the flow launcher and it still did not work. Whenever I am trying to search Snapchat and some other applications they do not show up in the flow launcher search bar. And I did not found any documentation on how to reload the plugin data for flow launcher.

Enable System Commands plugin (it's enabled  by default btw) and type `reload plugin data` in Flow. Or just press `F5` in Flow.

**Comment by VictoriousRaptor** [comment]
> Could you try `reload plugin data`?

I guess it's the 

> Could you try `reload plugin data`?

I guess it's related to #2345.

**Comment by GravakeAzure** [comment]
I will try doing that. And see if that fixes the problem, if in case that does not works then what can I do to improve the situation. And also I would like to know if you can tell to open different web searches in different browser using flow. Or how can I get plugins for say firefox, chrome or any other app that I want use in my pc.

**Comment by GravakeAzure** [comment]
> > How can I do that can you guide me as I tried to restart the flow launcher and it still did not work. Whenever I am trying to search Snapchat and some other applications they do not show up in the flow launcher search bar. And I did not found any documentation on how to reload the plugin data for flow launcher.
> 
> Enable System Commands plugin (it's enabled by default btw) and type `reload plugin data` in Flow. Or just press `F5` in Flow.

Hi thank you so much for helping me with that. I reloaded the plugin data and now I can see all the other apps in the flow launcher. It worked.
