### ISSUE TITLE
Extract Colors plugin?

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#240]
**Question**
Extract Colors plugin?

The extracted plugin will be made available as a download via the PluginsManager like all user made plugins.

**Discussion**
Just want to gauge interest in removing the Colors plugin. Do people use it? 

If you are using it and would like to keep, give this a thumbs down please. 

If you agree to extract it, give this a thumbs up please.

**Comment by deefrawley** [comment]
T o be clear do you mean remove it as an internal plugin bundled with Flow and move to an optional user plugin?

**Comment by jjw24** [comment]
yep, exactly. Will not be bundled with flow but still available to be installed via PluginsManager
