### ISSUE TITLE
BUG: reset all settings

### ISSUE THREAD

**Issue by shrek-gabe-itch** [Flow-Launcher/Flow.Launcher#2400]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

After autoupdate from 1.16.1 to 1.16.2 all settings have been reset
I delete flow launcher forever 
thanks)

### To Reproduce

1. update
2. realize that all the settings that you have been setting up for yourself for a long time have been deleted
3. delete 

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.199

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Sorry to hear that. Are you using portable mode?

**Comment by shrek-gabe-itch** [comment]
> Sorry to hear that. Are you using portable mode?

yes

**Comment by taooceros** [comment]
@jjw24 shouldnt we have disabled the auto update for portable mode?

**Comment by jjw24** [comment]
Well unfortunately this is not much info to go on with, I have always been running in portable mode and auto update has not caused any issues.

> @jjw24 shouldnt we have disabled the auto update for portable mode?

I don't think we have disabled it by default.

~~~

It's unfortunate that the settings got reset for whatever reason. As a note flow does do a backup of your settings so there is a chance to roll back to the previous version with the settings intact.
