### ISSUE TITLE
BUG: Quick AccessKeyword Assigned Window

### ISSUE THREAD

**Issue by mdroidian** [Flow-Launcher/Flow.Launcher#2408]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

This just started appearing when I use `Ctrl`+ `Alt` + `D`.

I use that shortcut nearly daily in my workflow on a specific webpage.  As of today this `Quick AccessKeyword Assigned Window` now appears when I use that shortcut.

Is there anywhere I can get more information about what this is?
Specifically how to disable that shortcut?

### To Reproduce

1. Press `Ctrl`+ `Alt` + `D`
2. See window.

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3792666/4ba62fbd-1942-46e1-8f61-b1013146bbbb)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.19044.3086

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
It's because you install the windows walker plugin. You can change that keyword in the plugin setting.

**Comment by mdroidian** [comment]
Ah, there is it!  Thank you kindly @taooceros

**Comment by taooceros** [comment]
You are welcome
