### ISSUE TITLE
BUG: dont start at startup  

### ISSUE THREAD

**Issue by Foxther1** [Flow-Launcher/Flow.Launcher#2409]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

when i startup my laptop it dont start automaticaly, and when i try to turn on the option, windows send me a error 
"requested registry access is not allowed"
how can i fix it?, im at last update

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/112411148/4235a6fe-cf7f-4b36-bb69-e59b45d1ad06)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.2428

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
I guess it is some permission issue and we are not able to fix it. There's another way to make a program autostart when computer starts by putting apps to the startup folder. I guess you can try that

**Comment by taooceros** [comment]
https://superuser.com/questions/1168835/starting-outlook-automatically-in-windows-10
