### ISSUE TITLE
BUG: [ctrl + number] shortcut opens containing folder instead of the application itself

### ISSUE THREAD

**Issue by dyckia** [Flow-Launcher/Flow.Launcher#2425]
### Checks
- [X] I have checked that this issue has not already been reported.
- [X] I am using the latest version of Flow Launcher.

### Problem Description
When setting `Ctrl` as the modifier key to open an application in the search result, FlowLauncher opens the application's containing folder, instead of opening launching the application itself. 

### To Reproduce
1. Set 'Ctrl' to the modifier key for search result. 
1. Type in any keyword to search a program. 
2. Use `Ctrl` + `number` to open the program. 

### Actual Result:
The containing folder is opened. 

### Expected Result:
The program should be opened. 

### Flow Launcher Version
1.16.2

### Windows Build Number
22621.2428

**Comment by deefrawley** [comment]
I can't reproduce this - ALT + NUM launches apps for me. Can you show an example of what you are trying to run?

**Comment by dyckia** [comment]
> I can't reproduce this - ALT + NUM launches apps for me. Can you show an example of what you are trying to run?

Sure. Here is the recording: 

![ezgif com-video-to-gif](https://github.com/Flow-Launcher/Flow.Launcher/assets/23126557/32af50b9-a16b-4bfd-88f2-096b9e49ade7)

**Comment by kubalav** [comment]
That bug is occurring, if you have set modifier key to Ctrl. Is it?

**Comment by dyckia** [comment]
> That bug is occurring, if you have set modifier key to Ctrl. Is it?

@kubalav You're right. I tested using Alt as the modifier key and the issue was gone.
