### ISSUE TITLE
Feature: Support the js and add NodePlugin.cs

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#244]
## Related issues

- https://github.com/Flow-Launcher/plugin-samples/pull/1
- https://github.com/Flow-Launcher/plugin-samples/pull/2

## Enhancement content

Actually, the js developers are the most people in developers.

So, it's better to pull them to stand our side.

The Flow needs to support the `js` and add `NodePlugin.cs`

**Comment by jjw24** [comment]
@Zeroto521 have you tested the js example plugins are working?

**Comment by jjw24** [comment]
Or do we need to fix/add integration

**Comment by Zeroto521** [comment]
Not at all.

Actually, the JSON RPC API list in docs is different from the [code](https://github.com/Flow-Launcher/Flow.Launcher/blob/master/Flow.Launcher.Plugin/IPublicAPI.cs).

The following is missing.

- Flow.Launcher.ShellRun: run shell commands
- Flow.Launcher.CloseApp: close flow launcher
- Flow.Launcher.HideApp: hide flow launcher
- Flow.Launcher.ShowApp: show flow launcher
- Flow.Launcher.StartLoadingBar: start loading animation in flow launcher
- Flow.Launcher.StopLoadingBar: stop loading animation in flow launcher

**Comment by jjw24** [comment]
Hmm ok, will tackle this after python.

**Comment by jjw24** [comment]
Yes, full environment support now.
