### ISSUE TITLE
BUG: Properly handle GPU driver crash/RemoveDevice event

### ISSUE THREAD

**Issue by Ok23** [Flow-Launcher/Flow.Launcher#2454]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When GPU driver crash and restarts interface not updating, freezes in state that been before crash (but inputs work) and taskbar icon context menu not shown

### To Reproduce

1. Cause GPU driver falldown and wait till restart
2. Try to use launcher

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22631.2861

**Comment by taooceros** [comment]
that doesn't seem to be something we can fix unless we force software rendering...and gpu driver crash seems to be some very uncommon event? You might just use Task Manager to kill flow and restart.
