### ISSUE TITLE
BUG: Icons are disappearing/missing, only back after a PC restart

### ISSUE THREAD

**Issue by pinetreemoonlight** [Flow-Launcher/Flow.Launcher#2455]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Icons for FlowLauncher entries are missing. This usually happens after a while of using my computer (including hibernating it etc.). The only "solution" that worked so far is rebooting my computer. I tried restarting FlowLauncher, didn't work. 

### To Reproduce

1. boot PC and use FlowLauncher for a while
2. Icons for FL entries will begin to appear missing 

### Screenshots

![Screenshot 2023-12-15 225203](https://github.com/Flow-Launcher/Flow.Launcher/assets/115622756/b1c4b469-5cb6-42fd-9ca0-98863f9195ce)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22631.2861

### Error Log

Here is one of the entries I guess, please let me know if you need more details from the log though.

```shell

06:01:53.7100+01:00 - ERROR - ImageLoader.Load - Failed to get thumbnail for C:\Users\user\AppData\Roaming\Anki2\user\collection.media\2pNywPxxeKNu-OlM2z4rlkEQwSKbQ1vHt8qjnkwGmatfiE3NMHc_oWPdjvThvsmqhG4mLp9Rwl0U0Ee7p3yda1iMU_ST0C_lUlxOHkVHa3sSWkz4_Dg.png on first try
EXCEPTION OCCURS: System.Runtime.InteropServices.COMException (0x80004005): Error while extracting thumbnail for C:\Users\user\AppData\Roaming\Anki2\user\collection.media\2pNywPxxeKNu-OlM2z4rlkEQwSKbQ1vHt8qjnkwGmatfiE3NMHc_oWPdjvThvsmqhG4mLp9Rwl0U0Ee7p3yda1iMU_ST0C_lUlxOHkVHa3sSWkz4_Dg.png
 ---> System.Runtime.InteropServices.COMException (0x8004B201): 0x8004B201
   at IntPtr Flow.Launcher.Infrastructure.Image.WindowsThumbnailProvider.GetHBitmap(string fileName, int width, int height, ThumbnailOptions options) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs:line 129
   at BitmapSource Flow.Launcher.Infrastructure.Image.WindowsThumbnailProvider.GetThumbnail(string fileName, int width, int height, ThumbnailOptions options) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs:line 120
   at ImageResult Flow.Launcher.Infrastructure.Image.ImageLoader.GetThumbnailResult(ref string path, bool loadFullImage) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Image/ImageLoader.cs:line 236
   at async ValueTask<ImageResult> Flow.Launcher.Infrastructure.Image.ImageLoader.LoadInternalAsync(string path, bool loadFullImage) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Image/ImageLoader.cs:line 160

```
</details>

**Comment by jjw24** [comment]
Hi there's is flow stored on HDD/SSD drive or in OneDrive?

**Comment by HyroGoth** [comment]
i had the same issue a while ago, i reisntaled and everything is normal again, so i assume this is some problem with cached files or something like that. For any dev seeing this, could be worth it to check if this is really the problem, for users with the same problem unistall flow launcher, clear the Flow's folders inside %localappdata% and %appdata" then reintall it. (doig backup fpom your configs is recomended)

**Comment by pinetreemoonlight** [comment]
> Hi there, is flow stored on HDD/SSD drive or in OneDrive?

Hi, it's stored on an M.2 SSD.

**Comment by GamingWithShaurya** [comment]
same thing happening to me as well,
i tried reinstalling also twice, and even cleared localappdata and appdata folders of flow launcher, its still no icons
and the app also freezes if i search a app, then u cannot bring it back using the hotkey, i need to restart it after killing from task manager

**Comment by z1nc0r3** [comment]
I also have the same problem.  It's probably an issue with the **_Program_** plugin.
Running a **_Reindex_** fixed the problem but I'm not sure whether it's temporary or not.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/64279853/a723cfe1-c9d9-4b1f-a4e1-88e1c763e947)

**Comment by Kamilkampfwagen-II** [comment]
I have the same issue, reinstalling, clearing cache, deleting user settings, disabling any of the plugins nor running the Reindex option doesn't fix the issue for me.

I found that killing `DllHost.exe` (which restarts shortly after) fixes the issue without the need to restart the computer.
The command line of said instance is `/Processid:{3AD05575-8857-4850-9277-11B85BDB8E09}`
I found this reddit post about the guid: https://www.reddit.com/r/crowdstrike/comments/pckx20/defense_evasion_via_disable_or_modify_tools/
> This is the static GUID for file operations.

**Comment by felipemldias** [comment]
@Kamilkampfwagen-II Did you ever solve it? Facing the same rn, reindexing also didn't solve it for me

**Comment by Kamilkampfwagen-II** [comment]
> [@Kamilkampfwagen-II](https://github.com/Kamilkampfwagen-II) Did you ever solve it? Facing the same rn, reindexing also didn't solve it for me

I haven't had this issue in a long time. I don't remember what fixed it either.
