### ISSUE TITLE
[Improvement] System commands plugin

### ISSUE THREAD

**Issue by realgooseman** [Flow-Launcher/Flow.Launcher#2459]
### **Is your feature request related to a problem? Please describe.**

The commands in "system commands" plugin are not translated (plugin by qianlifeng)

### **Describe the solution you'd like**

Adding these strings on Crowdin for translation. Or even better and simpler, let users edit these commands.

### **Additional context**

![System commands plugin](https://github.com/Flow-Launcher/Flow.Launcher/assets/64812183/cc15ddcd-adc6-4429-84e5-afa5ef2b2a45)

**Comment by LaserKaspar** [comment]
That would be great! I'd like to add a system command for turning off the screen without hybernating.

This command would do it but a quick way to access it would be great!
```
powershell (Add-Type '[DllImport(\"user32.dll\")]^public static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2) && exit
```
