### ISSUE TITLE
Need Thousand Separator in Calculator Output

### ISSUE THREAD

**Issue by secangel** [Flow-Launcher/Flow.Launcher#2460]
**Is your feature request related to a problem? Please describe.**

I need to work with numbers with Thousand Separators often, i.e. "," in "1,000" or "35,000,000". The current output from the calculator does not have Thousand Separators when I copy them.

**Describe the solution you'd like**

An option to toggle if Thousand Separator can be included in the output will be ideal.

**Describe alternatives you've considered**

Cannot think of other alternatives for now.

**Additional context**

Nothing additional is needed.

Thank you again for your attention.

**Comment by taooceros** [comment]
Actually this is quite simple https://stackoverflow.com/questions/105770/net-string-format-to-add-commas-in-thousands-place-for-a-number

**Comment by marcelmiro** [comment]
I made a custom calculator plugin specifically for this reason. Let me know if it works :)
https://github.com/marcelmiro/Flow.Launcher.Plugin.BetterCalculator

**Comment by VictoriousRaptor** [comment]
> I made a custom calculator plugin specifically for this reason. Let me know if it works :) https://github.com/marcelmiro/Flow.Launcher.Plugin.BetterCalculator

How about submitting it to our plugin repoistory?

**Comment by marcelmiro** [comment]
This is by design as I have never needed the formatted number. If you want, you can submit an issue/PR to include it when copying.
