### ISSUE TITLE
BUG: Unable to evoke QQMusic！

### ISSUE THREAD

**Issue by cc19264997** [Flow-Launcher/Flow.Launcher#2463]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Unable to evoke QQMusic！

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![微信图片_20231225233147](https://github.com/Flow-Launcher/Flow.Launcher/assets/25716656/493d2eb5-d52a-4752-8545-7187af568096)

### Flow Launcher Version

1000.19053.1000.0

### Windows Build Number

WIN10/22H2

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

 Unable to evoke QQMusic！

**Comment by taooceros** [comment]
where is your qqmusic locate? try `reload plugin data`?

**Comment by VictoriousRaptor** [comment]
Please check if your Program plugin is configured correctly.

**Comment by cc19264997** [comment]
The program configuration is normal!


Voter
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Flow-Launcher/Flow.Launcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 上午9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Flow-Launcher/Flow.Launcher] BUG: Unable to evoke QQMusic！ (Issue #2463)





 
Please check if your Program plugin is configured correctly.

**Comment by VictoriousRaptor** [comment]
How is your QQ Music installed? Is it a registry and/or a start menu shortcuts? Please post your config of program plugin.
