### ISSUE TITLE
Direct webpage/search result preview

### ISSUE THREAD

**Issue by Gmemster** [Flow-Launcher/Flow.Launcher#2470]
**Is your feature request related to a problem? Please describe.**

I think searching in Flow and then let it open browser is just a waste of time as it is using more steps than me just seacrhing in browser itself.

**Describe the solution you'd like**

Make Flow able to show preview of the search result in the preview section and show the top( or maybe 2 to 3) search result

**Describe alternatives you've considered**
Search using windows search
**Additional context**

Windows search is just limited to bing and Bing result are not that accurate to me

**Comment by Garulf** [comment]
I meant to comment on this before... showing browser previews can be very tricky, you'd basically need to add a web browser to Flow Launcher. Maybe this can be implemented in the future, but for now I don't think this is planned.

**Comment by jjw24** [comment]
Dup #2725
