### ISSUE TITLE
BUG: Icons hosted by CDNs do not appear in the plugin store or installed plugins list

### ISSUE THREAD

**Issue by SuperAnt220** [Flow-Launcher/Flow.Launcher#2474]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Plugin store doesn't have icons for any plugin. A couple months ago everything was fine. Plugins, that use cdn.jsdelivr for their icons and not the local path, also doesn't have an icon in the installed plugins list. I've tried:
- Restarting the flow launcher
- Reloading plugin data
- Restarting my computer
- Reinstalling the flow launcher
- Exiting the flow launcher, deleting everything in `%APPDATA%/FlowLauncher/Cache` and launching the flow again

executing `ping cdn.jsdelivr.net` in cmd gives this result:
```
Pinging cdn.jsdelivr.net.cdn.cloudflare.net [104.16.87.20] with 32 bytes of data:
Reply from 104.16.87.20: bytes=32 time=18ms TTL=56
Reply from 104.16.87.20: bytes=32 time=3ms TTL=56
Reply from 104.16.87.20: bytes=32 time=3ms TTL=56
Reply from 104.16.87.20: bytes=32 time=13ms TTL=56

Ping statistics for 104.16.87.20:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 18ms, Average = 9ms
```

executing `curl https://cdn.jsdelivr.net/gh/IsaacTay/Flow.Launcher.Plugin.FendCalculator@main/Images/calculator.png` in powershell terminal gives this result:
```
StatusCode        : 200
StatusDescription : OK
Content           : {137, 80, 78, 71...}
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Access-Control-Allow-Origin: *
                    Access-Control-Expose-Headers: *
                    Timing-Allow-Origin: *
                    Cross-Origin-Resource-Policy: cross-origin
                    X-Content-Type-Options: n...
Headers           : {[Connection, keep-alive], [Access-Control-Allow-Origin, *], [Access-Control-Expose-Headers, *], [Timing-Allow-Origin
                    , *]...}                                                                                                -Allow-Origin 
RawContentLength  : 6401
```

executing `curl https://cdn.jsdelivr.net/gh/IsaacTay/Flow.Launcher.Plugin.FendCalculator@main/Images/calculator.png` in cmd gives this result:
```
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ??????? ?????? ?? ?????? ?????????? ???????? ?????? ??? ???????????.
```

### To Reproduce

I don't know how to reproduce it. It just happened at some time in the past 1-2 months, I don't remember the exact day because I wasn't paying attention.

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/92710569/061e00be-2411-4cee-9817-ef24bda009ac)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/92710569/4e1e8792-ce64-4254-88aa-67cbb863b75e)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.18363.778

### Error Log

<details>

I don't think this log contains any errors regarding this problem, but anyway:
[2024-01-11.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13902533/2024-01-11.txt)

</details>

**Comment by taooceros** [comment]
well I think it is cdn issue, which doesn't seem something we can fix

**Comment by jimaek** [comment]
Based on the error it seems to be a local environment error. Consider updating curl and root CA certificates.

It doesn't seem to be a CDN issue

**Comment by taooceros** [comment]
> Based on the error it seems to be a local environment error. Consider updating curl and root CA certificates.
> 
> It doesn't seem to be a CDN issue

we just use the default Image loading from wpf to load the images.

**Comment by Garulf** [comment]
Can you still install plugins?

**Comment by taooceros** [comment]
@SuperAnt220 https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.source?view=winrt-22621#using-files-from-a-network this is how we do it.

**Comment by jimaek** [comment]
Given that in the original issue everything works properly in Powershell and breaks in CMD this means its an env problem, not CDN issue. `next InitializeSecurityContext failed: Unknown error (0x80092012)` points to some kind of incorrect configuration of certificates. 

Incorrect paths, broken binaries, incorrect permissions, anything could affect it
