### ISSUE TITLE
Fody block building

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#248]
I have encountered an issue that I cannot build Flow due to Fody's issue. That can be solved by updating PropertyChangeFody to the latest version. Should we do that?
![image](https://user-images.githubusercontent.com/45326534/103167368-8f6b4200-4865-11eb-8cfa-39e388139984.png)

**Comment by jjw24** [comment]
how are you build flow? is it via VS 2019?

we kept fody version at it is now due runtime problems encountered after updating the version. for references:
https://github.com/Flow-Launcher/Flow.Launcher/pull/35
https://github.com/Flow-Launcher/Flow.Launcher/pull/52

**Comment by taooceros** [comment]
I use Rider to build it, since I am on another computer at that time.
That's strange, since Rider build it well with version 3+.
Is it possible for us to remove Fody in our project as the PR said?

**Comment by jjw24** [comment]
Yeah of course if it improves flow. I did try removing it and the query result list stop registering/showing up. So I think it'likely we need replace fody instead

**Comment by taooceros** [comment]
Seems that Fody plays a quite important job in Flow, by adding property change to every property for binding that extends the BaseModel, which is almost every model in the Flow. Removing it means that we need to manually add the property changes event raise for every property extends the class, which is huge......

**Comment by JohnTheGr8** [comment]
worth mentioning that Fody also breaks running `dotnet publish` on the solution, which prevents us from fully building the project on appveyor

**Comment by taooceros** [comment]
Check around google and github, if we want to remove Fody, there are only a few choices.
1. Use PostSharp, which is not open-source, but free for community edition. It should do similar jobs as Fody by injecting code for IL after build.
2. Most of the repository to help people implementing inotifypropertychange easier is simply use a backward SetProperty Method with an abstract class. It is possible to choose one or implement our own, but both require significant works, since we have quite significant amount of property that raise the event to inform wpf to update their value.

**Comment by JohnTheGr8** [comment]
Hmmm... after some testing, it looks like the newest version of `PropertyChanged.Fody` resolves the runtime issues we saw in the past (#52). Updating also fixes the issues with `dotnet publish`, so I am looking into getting the self-contained build/release working with CI.

Leave this to me for now, I'll get back with a PR or more details...
