### ISSUE TITLE
[Recommendation] Replace windows search on task bar 

### ISSUE THREAD

**Issue by BarterClub** [Flow-Launcher/Flow.Launcher#2480]
I would like to replace the standard Windows search on the bottom with this, like Apple. When you click on the search icon on Mac, it brings the spotlight window up. I would like the same for this. Also, it can be the same when you start searching in the start menu. This can be a toggle feature in the settings for people that want only a few on.

**Comment by taooceros** [comment]
We don't know how to do this though...

**Comment by jonesy-b-dev** [comment]
You can install the `Win Hotkey` plugin https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey
To have it on your windows key which has about the same effect
