### ISSUE TITLE
[Describe Your Feature] Request to add language setting IPublicAPI for multiple languages ​​of external plugins

### ISSUE THREAD

**Issue by MinYn** [Flow-Launcher/Flow.Launcher#2483]
**Is your feature request related to a problem? Please describe.**

--

**Describe the solution you'd like**

Request to add language setting IPublicAPI for multiple languages ​​of external plugins

**Describe alternatives you've considered**

For multi-language support of external plugins, create a function that retrieves language settings from PublicAPI so that the language settings can be retrieved.

**Additional context**

--

**Comment by taooceros** [comment]
For c# plugin you can just retrieve the CurrentThreadCulture, we update that according to flow's language setting (which also causes some issue).
