### ISSUE TITLE
Web search suggestion from actual sources

### ISSUE THREAD

**Issue by Gurrrra** [Flow-Launcher/Flow.Launcher#2484]
When using the different web search functions it would be really nice to have suggestions pop up as well. So in the settings we could have a field for each search engine suggestion URL (if they have any) :)

And come to think of it, getting some actual search results directly in Flow would be awesome as well!

**Comment by taooceros** [comment]
I think we already can do this? 

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/45326534/90e05060-273d-455b-a29e-a1eaece49fc2)


well the ux is a bit hidden.

**Comment by Gurrrra** [comment]
Yeah that one is a bit hidden, but it also relies on either of those three search engines for suggestions which might not be preferable. In most cases this might not matter so much, but in others I think it does, like in this IMDb example below that's filled with random stuff that's not relevant in that type of search.
Though having actual search results directly in Flow is still something that would be really really handy, especially when searching stuff like IMDb (and might make that search suggestion change less needed?).

And if I'm allowed to add a bit more to this it would be nice that when you've written whatever key Flow would then disable the rest of web searches to only focus on that particular one, removed the key and put that particular search image in there instead. Example below :)
![flowimdborg](https://github.com/Flow-Launcher/Flow.Launcher/assets/102324673/21f911ed-4726-4780-9420-2a58d135caaa)
![flowimdb](https://github.com/Flow-Launcher/Flow.Launcher/assets/102324673/f46a89c9-8856-4707-82d1-0774da4309d6)

**Comment by taooceros** [comment]
> Yeah that one is a bit hidden, but it also relies on either of those three search engines for suggestions which might not be preferable. In most cases this might not matter so much, but in others I think it does, like in this IMDb example below that's filled with random stuff that's not relevant in that type of search.
> 
> Though having actual search results directly in Flow is still something that would be really really handy, especially when searching stuff like IMDb (and might make that search suggestion change less needed?).
> 
> 
> 
> And if I'm allowed to add a bit more to this it would be nice that when you've written whatever key Flow would then disable the rest of web searches to only focus on that particular one, removed the key and put that particular search image in there instead. Example below :)
> 
> ![flowimdborg](https://github.com/Flow-Launcher/Flow.Launcher/assets/102324673/21f911ed-4726-4780-9420-2a58d135caaa)
> 
> ![flowimdb](https://github.com/Flow-Launcher/Flow.Launcher/assets/102324673/f46a89c9-8856-4707-82d1-0774da4309d6)
> 
> 

The problem is different websites used different api to encode the suggestion, which makes it rather hard to have a universal configuration. I do think it might be a good idea but implementation wise I don't have a good idea about creating an extensible configuration for different source.

**Comment by Gurrrra** [comment]
Some sites do have a suggest URL, so would be nice with an option for that, or option to use google, or neither :)
