### ISSUE TITLE
BUG: Changing settings on plugins will reset as soon as it's activated

### ISSUE THREAD

**Issue by Gurrrra** [Flow-Launcher/Flow.Launcher#2485]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Whenever I change a setting on any downloaded plugin (except for the action key (as far as I've noticed so far) and then open Flow and activate that plugin with the action key the setting changes back to it's default value. Closing the settings windows don't help, and if I still have Flows settings window open I can even see it change back in real time.
First I thought this was a bug with just CurrencyPP since that was the first I noticed this, but then I noticed it with ChatGPT as well since this bug makes it unusable since I can't add my API key. I've also confirmed that FlowYoutube also have this bug, but all the default plugins that have any settings that I've tried to change seem to work fine. 

### To Reproduce

1. Download a plugin, FlowYoutube for example
2. Change some settings
3. Open Flow Launcher, type action key
4. Have settings revert back :(

### Screenshots

https://github.com/Flow-Launcher/Flow.Launcher/assets/102324673/a7b7d7e8-67ab-4d0d-980d-d4e8f49323c3

### Flow Launcher Version

1.16.2

### Windows Build Number

19045.2486

### Error Log

Got nothing in there

**Comment by taooceros** [comment]
@Garulf is it relate to how you fetch the setting?

@Gurrrra closing the plugin setting might help storing the setting to disk.

**Comment by Gurrrra** [comment]
@taooceros Ah sorry forgot to mention that I of course also tried closing the setting window as well, but it still resets as soon as I trigger any of the downloaded plugins.

**Comment by taooceros** [comment]
Hm does the setting persist if you close and open the setting panel?

**Comment by Gurrrra** [comment]
It does yes, but still resets when I activate a plugin.
I did test to also exit and relaunch Flow and that did actually save it for real and not resetting for at least the FlowYouTube and ChatGPT plugins, but not for CurrencyPP for some reason.

**Comment by taooceros** [comment]
@Garulf get any hint about this?

**Comment by Garulf** [comment]
It is due to Flow Launcher changing how it handles plugin settings in memory only and and undetected bug in Flox, which many Python plugins use. 

This issue is fixed, plugins just need to be upgraded. 

The only work-around is editing the plugin's settings files manually while Flow Launcher is no longer running.
