### ISSUE TITLE
Web Search: Multiple plugins at the same keyword

### ISSUE THREAD

**Issue by anonymousALLDAY** [Flow-Launcher/Flow.Launcher#2491]
**Is your feature request related to a problem? Please describe.**

I'd like to search specific electric component on multiple sites at once, such as Digikey, Mouser, etc

**Describe the solution you'd like**

allow multiple URL for one action keyword (except *)

and all search results are shown with multiple browser tabs at once

**Describe alternatives you've considered**

**Additional context**

**Comment by deefrawley** [comment]
This can be done with the Shortcuts Plugin as per #2097
