### ISSUE TITLE
Option for Web Searches to refocus on active browser after entering query

### ISSUE THREAD

**Issue by Crunchbits** [Flow-Launcher/Flow.Launcher#2495]
**Is your feature request related to a problem? Please describe.**
When browser is NOT focused & then you enter a web search it will focus the browser.
However when the browser IS focused & then you enter a web search it will fail to re-focus onto the browser window.

**Describe the solution you'd like**
Option to refocus automatically after web search.

**Additional context**
Tested on browser: Firefox 121.0.1 (64-bit)

**Comment by z1nc0r3** [comment]
The issue is unclear. Can you add the steps to reproduce the issue?

> fail to re-focus onto the browser window

Do you mean it opens a new browser window instead of using an existing one?

**Comment by Crunchbits** [comment]
No, it'll open in the correct window. But I mean that I'll have to mouse click on the browser right after the new tab is opened to interact with the browser, which is frustrating if you have your hands only on the keyboard.

To show what I mean here is how my browser's window looks in every step:


1. Before opening flow launcher via shortcut (Browser window focused):
![Scrnshot_24 021  2131  21](https://github.com/Flow-Launcher/Flow.Launcher/assets/87384615/08053d4a-de2a-4a76-ad2c-8c21ed7dc501)
2. After opening flow launcher via shortcut (Browser window unfocused):
![Scrnshot_24 021  2132  31](https://github.com/Flow-Launcher/Flow.Launcher/assets/87384615/3b06bc96-3a22-4511-b1c9-eec8251a27d9)
3. After typing and pressing enter on web search query (Browser window still unfocused):
![Scrnshot_24 021  2133  49](https://github.com/Flow-Launcher/Flow.Launcher/assets/87384615/51f172ed-d79e-4fb3-aa05-e1e629ec1db8)


As you can see in step 3, it opens the tab correctly but the browser window is not refocused (as shown by the dimmed window title-bar).

**Comment by z1nc0r3** [comment]
That is odd because I couldn't repro the issue using both Chrome and Firefox. In my case after a web search using FL the browser window and the tab is automatically focused (even the browser is minimized). Did you try changing the _Default Web Browser_?

**Comment by Crunchbits** [comment]
Thanks for the suggestion! I forgot I had my default browser set to a default-browser-picker program. Setting the default browser to my actual browser(Firefox) fixed the issue.
