### ISSUE TITLE
Hello author Flow Launcher please make it so that you can use not only google but also other browsers such as Yandex.

### ISSUE THREAD

**Issue by AXEL257Games** [Flow-Launcher/Flow.Launcher#2498]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AXEL257Games** [comment]
Oh, I'm sorry, I didn't see that it was already available, but please add Yandex browser.

**Comment by deefrawley** [comment]
Hi this already exists. Under Settings - Default Web Browser you can choose any browser installed (you need to provide the path to the executable).
