### ISSUE TITLE
Windows index searching doesn't search any files

### ISSUE THREAD

**Issue by vbccbz** [Flow-Launcher/Flow.Launcher#2499]
I have enabled indexing. If I run Windows 10 search and type find me.txt - I'll see correspond result in Start menu. But if I call Flow and type file name - he won't find any. Explorer plugin is set up to work with Windows Index. What do I wrong?

**Comment by taooceros** [comment]
is the file in Onedrive? The windows index used by flow doesn't seem to work with onedrive.

**Comment by vbccbz** [comment]
> is the file in Onedrive? The windows index used by flow doesn't seem to work with onedrive.
No, simple user's root folder. Reset index settings, removed Flow settings C:\Users\User\AppData\Roaming\FlowLauncher, reinstall and nothing has been changed. 
Strange thing - if I type "txt", then Flow lists *.txt files in C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinRAR. But he doesn't list any files in C:\Users\User\. 
I set up Search in Explorer plugin to "sss", type sss find me.txt - but again nothing happen. And I repeat again - find me.txt is founded by Win + S Windows search. 
I now that we can use Everything, but I am interested in Windows indexing for now)))

**Comment by taooceros** [comment]
I haven't used windows search for a long time, as everything does work better. I will give it a test tomorrow.

**Comment by jjw24** [comment]
Hey @vbccbz is this still an issue? Usually if you see it in windows start menu search you should see it in explorer plugin. Perhaps check in Explorer plugin settings:
- have you set a particular action keyword that need to be triggered first?
- have you by any chance the path via the settings ?
- search engine settings are using windows indexing?

**Comment by deefrawley** [comment]
Last OP comment four months ago so closing. If it's still an issue we can reopen. Thanks
