### ISSUE TITLE
Open Flow settings window after restart if it was open

### ISSUE THREAD

**Issue by jonesy-b-dev** [Flow-Launcher/Flow.Launcher#2504]
When I'm looking through the plugin store and want to install a plugin it restarts Flow Launcher to install it. Now I need to reopen the settings window manually to continue looking through the plugin store or do something else.

It would be nice that Flow Launcher automatically restarts the settings window when Flow Launcher is being restart and the settings window was open. For example when a plugin is installed through the settings window.

**Comment by taooceros** [comment]
There will be an option to not restart immediately after installing plugin in the next release.

**Comment by jonesy-b-dev** [comment]
Amazing!
