### ISSUE TITLE
Some plugin results not showing in global search

### ISSUE THREAD

**Issue by krusse** [Flow-Launcher/Flow.Launcher#2505]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

If I do not use the keywords of certain plugins, they do not show up in the global search despite setting their priority numbers higher than any other.

For example, no bookmarks are suggested unless I precede it with the b keyword. 

Similarly, if I type in a search string that is indeed found with the Obsidian plugin after the keyword ob, it does not show up in the global search without it even when the search results return fewer than the maximum allowed. It will show the associated md file, but not the Obsidian plugin link.

Is this the intended behaviour or am I missing something?

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22623.1325

**Comment by deefrawley** [comment]
If you want a plugins results to show in the global search then you need to change that plugins keyword to an asterisk '*'. Otherwise it will only show its results of you use the defined keyword.
