### ISSUE TITLE
Expand the Spotify from tray

### ISSUE THREAD

**Issue by vbccbz** [Flow-Launcher/Flow.Launcher#2513]
**Is your feature request related to a problem? Please describe.**

Start Spotify. Close it by close button in window control buttons. Spotify will be minimized into the tray.  Call Flow launcher. Enter Spotify  - and nothing will happen. 

**Describe the solution you'd like**

I'd like that Spotify is expands back to the full window.

**Describe alternatives you've considered**

**Additional context**

It's interesting that this problem arises only with Spotify. For example, Telegram is expanded from the tray correctly.

Spotify for Windows (64 bit) 1.2.29.605.g66a43ceb
FW 1.16.2

**Comment by VictoriousRaptor** [comment]
The behavior is controlled by spotify.
