### ISSUE TITLE
BUG: Unable to uninstall

### ISSUE THREAD

**Issue by elieobeid7** [Flow-Launcher/Flow.Launcher#2514]
### Problem Description

can't uninstall flow launcher

### To Reproduce

Windoows 11. related to this issue

https://github.com/Flow-Launcher/Flow.Launcher/issues/1227

I uninstalled it via add or remove program and tried to uninstall it via winget.

I deleted any folder related to flow Launcher in  C/users/name/appdata/roaming and C/users/name/appdata/local

I deleted all follow launcher entries manually one by one from the registry editor.

I restarted the Pc. When I click flow launcher shortcut, the launcher shows up

### Screenshots

<img width="792" alt="image" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/660142/fa0b730a-ec37-4b33-8937-efd27f013ada">

### Flow Launcher Version

I don't know, the setting no longer exists, only the flow launcher search

### Windows Build Number

windows 11

**Comment by VictoriousRaptor** [comment]
Could you please provide a screenshot after pressing the shortcut?

**Comment by elieobeid7** [comment]
@VictoriousRaptor 

<img width="792" alt="image" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/660142/95a6b342-bbf4-4d02-8b07-f48b1f1d1a8a">

**Comment by VictoriousRaptor** [comment]
Looks like it's Powertoys Run, rather than Flow Launcher. If you want to disable it, you can disable it in Powertoys settings.f

**Comment by elieobeid7** [comment]
oh sorry! It didn't occur to me that Powertoys has a flow launcher-like program.
