### ISSUE TITLE
Feature: Add a search bar to any explorer window for quicker searches

### ISSUE THREAD

**Issue by LBF38** [Flow-Launcher/Flow.Launcher#2516]
**Is your feature request related to a problem? Please describe.**
When I'm browsing the Windows explorer for specific files or folders, I would like to type for the name of the folder where the file is in or the filename I know.

**Describe the solution you'd like**
The solution would be to have a search bar below the Explorer window, to quickly type keywords for searching a folder/file.

Then, based on the query, a list of folders/files are suggested and I can select one.
When selected, it directly jumps to it or fills the Explorer input with the selected file.

Inspired by the Quick Switch feature of [Listary](https://listary.com)
![](https://assets-global.website-files.com/643e09c9f19df8579c420d9f/6565abd103c93278540ef014_Listary-quick-switch.svg)

**Describe alternatives you've considered**
Using Listary.

**Additional context**

**Comment by jjw24** [comment]
Dupof https://github.com/Flow-Launcher/Flow.Launcher/issues/1117.
