### ISSUE TITLE
BUG: Flow launcher doesn't show Control Panel settings

### ISSUE THREAD

**Issue by bluntcoder** [Flow-Launcher/Flow.Launcher#2532]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

https://www.flowlauncher.com/public/images/screenshots/bs_windowssettings.png <- this feature doesn't work, with my fresh install of flow launcher, Windows 11 Pro. Windows Settings plugin is correctly installed.

### To Reproduce

1. Install Flow Launcher
2. Type "remove pro"
3. Control Panel > Add & Remove Programs does not show up.

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/2693220/b5606d78-f683-4786-9156-f70f1fb75b9e)

### Flow Launcher Version

1.17

### Windows Build Number

Windows 11 Pro 10.0.22621 Build 22621

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Windows settings is used with a keyword ('s' if I remember rightly). Check the plugin settings.
