### ISSUE TITLE
Disable cleansing on copy-pasting `Ctrl+V`, or provide an option to do so

### ISSUE THREAD

**Issue by jerrygreen** [Flow-Launcher/Flow.Launcher#2534]
When I press `Ctrl+V` into command palette, it replaces everything in the input, no matter if any text was selected.

And although I may understand this may be convenient for some people, I am irritated by this feature because we have keywords for plugins – and when I type a keyword to paste something that I wanna input into this plugin, the keyword gets deleted.

I see two potential solutions both of which work for me, simpler, and smarter one:

1. [Simpler] Just provide an option to disable the paste-cleansing feature
2. [Smarter] When a keyword was typed «just now»*, do not remove it, otherwise – proceed to work as earlier

By «just now» I don't mean we have to count seconds. Instead, the rule should be:

- If input was written in current `Alt+Space`, that's considered just now
- If input was from previous `Alt+Space`, that means it should be replaced upon `Ctrl+V`

On the second thought, when input is from previous `Alt+Space`, it gets automatically selected, which means it will be replaced just like I described in «Smarter» solution anyways. So, I guess... Forget everything and just disable this cleansing feature oh lol 😅

> You get it, right? We don't even need an option to disable it, might as well just disable it. Because of automatic selection, previous input will be replaced anyways. Hence, the only case where automatic cleansing might actually happen – is when you type something then immediately `Ctrl+V`, but such use-case doesn't have any sense at all. This feature is pointless.
>
> To be 100% safe to not ruin somebody's use-case that I might not see, at least provide an option to disable it.

**Comment by jjw24** [comment]
Hi there, this is a bug that came out of the v1.17.0 release. We have a fix that will be going out in the up coming hotfix release to address this issue.

https://github.com/Flow-Launcher/Flow.Launcher/pull/2528

**Comment by jjw24** [comment]
Please update to 1.17.1

**Comment by jerrygreen** [comment]
1.17.1 works smooth as a butter, thanks!
