### ISSUE TITLE
BUG: After recent update File explorer searches/lists aren't  showing up

### ISSUE THREAD

**Issue by a-y-a-n-das** [Flow-Launcher/Flow.Launcher#2535]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

After a recent update, I am not able to search files, docs, videos etc in flow launcher

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.17.0

### Windows Build Number

 10.0.22635.3139

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Dupe of #2530 . Fix on the way

**Comment by jjw24** [comment]
Please update to 1.17.1

**Comment by a-y-a-n-das** [comment]
Yehh! , Resolved.
