### ISSUE TITLE
No easy way to unhide search results from displaying

### ISSUE THREAD

**Issue by rsmyst** [Flow-Launcher/Flow.Launcher#2545]
In the results menu, there's an option to hide a search from displaying. Now, I've mistakenly hidden 2 - 3 searches like that, but can not find a way to unhide them from displaying from anywhere. Maybe add a feature to show what searches are currently being hidden from being displayed ?

**Comment by z1nc0r3** [comment]
There is an option to disable a program from displaying in the **_Program_** plugin. If you accidentally disabled programs from displaying you can clear them on the plugin configurations page.

_Settings > Plugins > Program_ and Select the certain program and click the **Enable** button.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/64279853/e86dd576-c0f1-45cb-96f9-603bb03e20d2)
