### ISSUE TITLE
Always positionally independent CQS

### ISSUE THREAD

**Issue by gisturbance** [Flow-Launcher/Flow.Launcher#2546]
**Is your feature request related to a problem? Please describe.**

Some CQS are always used positionally independent, still requiring the use of an @-prefix, disrupting the search inputs flow.

For example, a CQS named `📁` to prepend Everything Search Filters, triggered by a CQH, would display `@📁` instead, which doesn't look very clean.

**Describe the solution you'd like**

Add a setting to each CQS to make it positionally independent, without the need of an @-prefix.

**Comment by taooceros** [comment]
Sorry could you restate the proposal? It's not clear to me about the meaning of positionally independent

**Comment by VictoriousRaptor** [comment]
In short, an option to allow the @ behavior, without entering @.
