### ISSUE TITLE
Cannot find some control panel functions

### ISSUE THREAD

**Issue by Olddddd** [Flow-Launcher/Flow.Launcher#255]
**Describe the bug/issue**
Already discussed in the Discord but we cannot find actions like "Create a restore point" or "Focus assist" from the control panel in the search bar.

**Your System**
```
Windows build number: 10.0.19041.685
Flow Launcher version: 1.6.0
```

**Comment by pc223** [comment]
I found a potential solution for this issue :smile: 

Turns out the actions like "Create a restore point" are called task links, and default control panel task links are hiding in `shell32.dll`. The task links XML data can be extract using this `win32api.LoadResource(shell32_handle, "XML", 21)`  (I don't know why it's 21, but 21 works 😂 )

This script will print out all these task links. (Windows 10 + python27 + pip install pywin32)
https://gist.github.com/pc223/48e9a24ef595cec4465ed41bf880be5f

The script is modified from this: https://github.com/blackdaemon/enso-launcher-continued/blob/master/enso/contrib/open/platform/win32/control_panel_win7.py

Output:
```
0 | Accommodate learning abilities | control.exe /name Microsoft.EaseOfAccessCenter /page pageQuestionsCognitive
1 | Accommodate low vision | control.exe /name Microsoft.EaseOfAccessCenter /page pageEasierToSee
2 | Change how your keyboard works | control.exe /name Microsoft.EaseOfAccessCenter /page pageKeyboardEasierToUse
3 | Change how your mouse works | control.exe /name Microsoft.EaseOfAccessCenter /page pageEasierToClick
4 | Use screen reader | control.exe /name Microsoft.EaseOfAccessCenter /page pageNoVisual
5 | Change the Narrator voice | %windir%\system32\narrator.exe
...
```

**Comment by pc223** [comment]
Another approach from Wox:

https://github.com/Wox-launcher/Wox/issues/2875

**Comment by taooceros** [comment]
> Another approach from Wox: 🤔
> 
> [Wox-launcher/Wox#2875](https://github.com/Wox-launcher/Wox/issues/2875)

hmmmm I have taken a try on it. It would be successfully for us to retrieve the description of setting based on the file, but when trying to access the highhotkeyword, a accessviolationexception will be thrown.
![image](https://user-images.githubusercontent.com/45326534/103725308-241f1f80-4f8b-11eb-8e13-2eb1cf76c960.png)

**Comment by pc223** [comment]
> > Another approach from Wox: 🤔
> > [Wox-launcher/Wox#2875](https://github.com/Wox-launcher/Wox/issues/2875)
> 
> hmmmm I have taken a try on it. It would be successfully for us to retrieve the description of setting based on the file, but when trying to access the highhotkeyword, a accessviolationexception will be thrown.
> ![image](https://user-images.githubusercontent.com/45326534/103725308-241f1f80-4f8b-11eb-8e13-2eb1cf76c960.png)

So we can't access this? Maybe it needs Admin privilege? 🤔 

```
windows?ms-resource://Windows.UI.SettingsAppThreshold/SearchResources/SystemSettings_Start_LinkToPlacesPage/HighKeywords
```

**Comment by taooceros** [comment]
> > > Another approach from Wox: 🤔
> > > [Wox-launcher/Wox#2875](https://github.com/Wox-launcher/Wox/issues/2875)
> > 
> > 
> > hmmmm I have taken a try on it. It would be successfully for us to retrieve the description of setting based on the file, but when trying to access the highhotkeyword, a accessviolationexception will be thrown.
> > ![image](https://user-images.githubusercontent.com/45326534/103725308-241f1f80-4f8b-11eb-8e13-2eb1cf76c960.png)
> 
> So we can't access this? Maybe it needs Admin privilege? 🤔
> 
> ```
> windows?ms-resource://Windows.UI.SettingsAppThreshold/SearchResources/SystemSettings_Start_LinkToPlacesPage/HighKeywords
> ```

I have tried admin privilege. it doesn't work

**Comment by taooceros** [comment]
The P/Invoke information I found for resolving this (method from @bao-qian )
http://www.pinvoke.net/default.aspx/shlwapi.shloadindirectstring

```c#
[DllImport("Shlwapi.dll", BestFitMapping = false, CharSet = CharSet.Unicode, ExactSpelling = true, SetLastError = false, ThrowOnUnmappableChar = true)]
        static extern int SHLoadIndirectString(string pszSource, StringBuilder pszOutBuf, int cchOutBuf, IntPtr ppvReserved);
```

**Comment by pc223** [comment]
> 
> 
> The P/Invoke information I found for resolving this (method from @bao-qian )
> http://www.pinvoke.net/default.aspx/shlwapi.shloadindirectstring
> 
> ```cs
> [DllImport("Shlwapi.dll", BestFitMapping = false, CharSet = CharSet.Unicode, ExactSpelling = true, SetLastError = false, ThrowOnUnmappableChar = true)]
>         static extern int SHLoadIndirectString(string pszSource, StringBuilder pszOutBuf, int cchOutBuf, IntPtr ppvReserved);
> ```

Nice! :smile: Yeah, @bao-qian did mentioned it in the issue 😂 
> windows 10 settings one. we need use SHLoadIndirectString for description and Glyph for icon.

Can you able to extract keywords of task links as well? With the bao-quan's approach I mean. I updated the Python script, now it can get the keywords for the task links 😋 

```
0  |  Accommodate learning abilities  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageQuestionsCognitive  |  
[[u'accomidate', u'accomodates', u'accomodating', u'adjust', u'for'],
 [u'can', u'not', u'cannot', u"can't", u'difficult', u'to', u'difficulty', u'does', u"doesn't", u'hard', u'not', u'will', u'willnot', u"won't"], [u'disabled', u'handicap', u'handicapped', u'disabilities', u'disability', u'empaired', u'impaired', u'imparied', u'trouble'], [u'cognitive', u'learning']]
```
