### ISSUE TITLE
BUG: FlowYouTube not showing all the options

### ISSUE THREAD

**Issue by uugaabuugaa** [Flow-Launcher/Flow.Launcher#2555]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I am led to believe there should be more options like language, region and most importantly program path for media players than what I can see right now like the screenshot below. Did I miss something? There is no error otherwise and nothing on the log file as well. Everything works fine besides the fact that I cannot change any settings. Posting it here because the dev seems to be more active here.

### Screenshots

![Capture](https://github.com/Flow-Launcher/Flow.Launcher/assets/70348189/f4551877-6a82-4e9f-9029-381012248ec5)

### Flow Launcher Version

1.17.1

### Windows Build Number

10.0.19045.3930

**Comment by uugaabuugaa** [comment]
[This issue leads me to believe the problem is more on Flow Launcher's side than FlowYouTube](https://github.com/Flow-Launcher/Flow.Launcher/issues/2531). Going back to version 1.16.2 has given me a temporary fix. Hopefully it will be fixed in the later versions.

**Comment by jjw24** [comment]
Do you mean 1.16.2 had those additional options you mentioned in the description or was there just a workaround that achieved what you wanted? 

I don't recall that plugin had any additional settings so if it's the workaround, what was it? Can you provide some details please.

**Comment by uugaabuugaa** [comment]
@jjw24 okay maybe I wasn't clear. It showed all the options when I used v1.16.2 of Flow Launcher and kept the newest version of FlowYoutube. Tried with rolling back to previous versions of FlowYoutube with newest Flow Launcher and it didn't work.
[ And the options look like this now](https://github.com/Flow-Launcher/Flow.Launcher/assets/70348189/0bff2702-fa75-4dad-9432-0c72ed269fc5)

**Comment by Garulf** [comment]
Should be fixed by: https://github.com/Flow-Launcher/Flow.Launcher/pull/2559
