### ISSUE TITLE
Customize/Add Built-in Shortcuts (including keypresses, like {tab} and {enter})

### ISSUE THREAD

**Issue by EnigmaSolved** [Flow-Launcher/Flow.Launcher#2561]
It seems like there was perhaps once some consideration (https://github.com/Flow-Launcher/Flow.Launcher/pull/930) for additional enhancements to Built-in Shortcuts, and I would like to propose adding the ability to add various hotkey presses to the list, either by default, or just with the ability to customize it by the user. You could re-use the code that captures hotkey sequences for Custom Query Hotkeys, though there would need to be new code for simulating those hotkey sequences in Windows. 

I imagine there are all sorts of interesting things that could be done with this addition, but a simple immediate example is that adding the `{enter}` key to the Built-in Shortcuts (or enabling the user to add it) would then provide a solution to https://github.com/Flow-Launcher/Flow.Launcher/issues/2213 for Custom Query Hotkeys being able to automatically trigger when called. 

Thanks for considering this idea/request! :)

**Comment by VictoriousRaptor** [comment]
Could you descride your idea with more details? Do you mean by adding `{enter}` automatically presses enter?

**Comment by EnigmaSolved** [comment]
> Could you descride your idea with more details? Do you mean by adding `{enter}` automatically presses enter?

Yup, exactly, and same thing for `{tab}`. And I guess, actually, on a technical level it wouldn't truly be that it has to simulate a true "enter" or "tab" key as much as that the appropriate internal Flow functions that would normally be called by those key presses in those moments/contexts will get called. The goal is to make possible more complex Custom Query Hotkeys (eg, ones that will automatically "trigger" when called, as well as ones that could "tab" one or more times if needed to get the desired end state). I personally don't have a specific end-use case for `{tab}` (or I've forgotten it, LOL), but I think I have some intended goals for `{enter}` and it seemed like adding `{tab}` at the same time could make sense / be more efficient than adding it later when it'll inevitably get requested.

Let me know if more clarifying would be helpful! Thanks much for your inquiry, and work you're able to do on this! :)
