### ISSUE TITLE
Threat detected in application

### ISSUE THREAD

**Issue by robkroef** [Flow-Launcher/Flow.Launcher#2562]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When installing the latest available version of Flow Launcher (1.17.1) I get a threat detection by my Windows Security system. Also detected as malicious via other tools: https://www.virustotal.com/gui/file/5ced06fdb428690ada48cdf3ebd75469b0494b97fff78b92cbea24ebdd21f8be/detection

### To Reproduce

1. Download version 1.17.1
2. Install via .exe or command line
3. Validate Windows Security Protection detection

### Screenshots

![threat detection flow launcher](https://github.com/Flow-Launcher/Flow.Launcher/assets/26417897/aa041205-aae1-43c6-aa79-eae0d21e0741)

### Flow Launcher Version

1.17.1

### Windows Build Number

10.0.22621.3007

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Garulf** [comment]
Please see my response here:

https://github.com/Flow-Launcher/Flow.Launcher/issues/2008#issuecomment-1501007334

**Comment by abhiiguptaa** [comment]
I am also facing the same issue and I have tried it so many times to install this

**Comment by robkroef** [comment]
The portable version also gives an error, which I know could make an exception in Windows Defender. Whitelisting an app isn't as easy on a device that is enrolled and maintained in a corporate environment.

**Comment by Garulf** [comment]
It would seem this user had some progress with Microsoft directly?

https://github.com/Flow-Launcher/Flow.Launcher/issues/2568
