### ISSUE TITLE
Microsoft Defender false-positive has been removed

### ISSUE THREAD

**Issue by Nitrrine** [Flow-Launcher/Flow.Launcher#2568]
Quoting Microsoft Security Intelligence:

> flow-launcher-setup.exe
> 
> Submission ID: ***
> 
> Status: Completed
> 
> Submitted by: ***
> 
> Submitted: Feb 12, 2024 11:46:59 PM
> 
> User Opinion: Incorrect detection
> 
> Analyst comments:
> 
> 
>                 At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
>      1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>      2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>      3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.

**Comment by jjw24** [comment]
Fantastic! Thank you @Nitrrine for helping us submitting to Microsoft Defender 🥇
