### ISSUE TITLE
BUG: Flow hangs up sometimes

### ISSUE THREAD

**Issue by jerrygreen** [Flow-Launcher/Flow.Launcher#2570]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

It just doesn't work, neither from a shortcut, or even if I try to click the program from tray – it doesn't respond.

I'm already using Flow Launcher for a couple of weeks, but just today I started seeing this bug. Already happened to me 3 times in the last hour. All I can do is restart the app – it works for some minutes, then again hangs up.

The bug first appeared before I even updated the app – in 1.17.1

Just in case, I checked the updates and it happened to propose me 1.17.2 update, which I accepted

Then the bug has shown again two times. It almost feels like it even worsened the situation, since before that I didn't have anything like that. In recent days I didn't install any plugins, only a week or two ago when I installed Flow, I installed these two plugins:

- [Games Launcher](https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher)
- [Obsidian Notes](https://github.com/Garulf/Obsidian-Notes)

But it worked fine for many days ahead since then, until suddenly it doesn't work properly anymore.

The app becomes nearly unusable since I always have to restart it.

UPD. Also, a weird behavior I just noticed today: all the default plugins like calculator, web searches etc – all their icons disappeared. Might not be related though, it's just weird. It looks like this:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13215662/6427d48b-f7c5-4c0c-ac75-5a9b17bbd712)

### To Reproduce

Yeah, the issue is... I don't know how exactly that happens.

Hopefully somebody could come here and give a hunch.

### Flow Launcher Version

1.17.2

### Windows Build Number

Windows 10 Pro Version	22H2 (Build 19045.3930)

### Error Log

[2024-02-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14271109/2024-02-13.txt)

**Comment by taooceros** [comment]
Do you mind delete the resource folder and reinstall flow? 

It is normal %appdata%/flowlauncher.

Generally when this happens it is because file corruption.

**Comment by jerrygreen** [comment]
Well, that deletes all my settings. I made a copy just in case.

As for now, I will try to use Flow from a more pure state as see how it goes.

One thing I noticed right away is that icons still do not appear:

- https://github.com/Flow-Launcher/Flow.Launcher/issues/2571

**Comment by jerrygreen** [comment]
For you to know for certain: all my settings were reset. Before I had a custom shortcut, a few «Web Search» shortcuts, and a couple plugins listed – all gone.

This wasn't 100% completely pure state though, as during a few minutes I had the app running I changed:

- I have set up launching shortcut to `Ctrl+Alt+Shift+Space`
- In appearance settings, I disabled the animation (I prefer things fast)

So these might be related.

**Comment by jerrygreen** [comment]
Also, I got this notification, not sure if it's related (I'm having PowerToys installed, it's using `Alt+Space` hotkey)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13215662/0405e00b-21ee-4151-ada2-91df07dc7602)

Right now, I installed it without changing anything at all. What I can say for now already: plugin icons still messed up (not shown).

**Comment by jerrygreen** [comment]
Nope. Even without changing anything, it still hangs up: not responding without anything custom.

**Comment by taooceros** [comment]
Mind restarting the computer for test? Maybe disable the shortcut for powertoy run so that can be registered. Generally icon not loading is hard to debug so I am not sure about the reason...

**Comment by jerrygreen** [comment]
Funnily enough, restarting computer did help.

Right-away I noticed how much faster the app works now. Before that, it had like 0.1-0.2 sec of processing the highlighted list today. Now it feels immediate. I returned my backup settings, – they all work just fine now.

It's interesting how the program requires system restart though, it's not a good sign but solves my issue.
I often do not shut down my computer, but make it go to sleep/hibernate, maybe that's related. Thanks!

**Comment by taooceros** [comment]
Generally no, but there might be weird issue lies in your computer causing flow not able to load the icon, which slows down it? I am not able to understand just from the information...
In fact, a lot of stuff can be solved by a restart so 🤣

**Comment by taooceros** [comment]
I put my computer into sleep and hibernate mostly so I think it won't be an issue

**Comment by jerrygreen** [comment]
Well there's a whole bunch of games. I have Witcher 3 in steam but it isn't installed, so I doubt it's related to Witcher.

In my case, it was just enough to restart the system. The bug never happened to me again since then.

**Comment by atakanvg** [comment]
delete cache file from Users\your user name\AppData\Roaming\FlowLauncher
