### ISSUE TITLE
BUG: Icon missing for some apps on Win11

### ISSUE THREAD

**Issue by vemundha** [Flow-Launcher/Flow.Launcher#2574]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

The icon for some apps are missing in the launcher. The same icon is OK in the Win11 start menu. See attachments and gif attached. 

### To Reproduce

1. Alt-Space to open
2. Search for "Mess..."
3. See missing icon

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/0b39bf8a-4af6-473b-bff7-cb3b1b98c83e)
![IconMissing](https://github.com/Flow-Launcher/Flow.Launcher/assets/1158119/55545ed7-9234-4266-b429-cd74aacaa2a1)

### Flow Launcher Version

1.17.2

### Windows Build Number

10.0.22635.3140

### Error Log

[2024-02-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14280179/2024-02-14.txt)

**Comment by taooceros** [comment]
that's because you install window walker plugin, which doesn't provide icon on that particular version. We've upgraded it to support icon so you may want to update?
