### ISSUE TITLE
How to uninstall this software ?

### ISSUE THREAD

**Issue by Elaws** [Flow-Launcher/Flow.Launcher#2575]
There doesn't seem to be an uninstaller. Thank you.

**Comment by kubalav** [comment]
You can uninstall FL from Windows Settings or Control Panel.

![obrázok_2024-02-14_175710618](https://github.com/Flow-Launcher/Flow.Launcher/assets/37414585/5edcd79c-d9e6-488c-860a-3e3001044c1b)

**Comment by Garulf** [comment]
If you did not install Flow Launcher and used portable mode you would just need to delete the folder that contains Flow Launcher.

**Comment by Elaws** [comment]
Does portable mode install in `AppData/Roaming` ? I uninstalled using Apps & Features, and there are many folders remaining in `AppData/Roaming/FlowLauncher`, and in addition to that, I have a service named `Flow.Launcher` booting at startup.

**Comment by mecampbellsoup** [comment]
> and in addition to that, I have a service named `Flow.Launcher` booting at startup

Same issue - @Elaws were you able to figure out how to remove this?

![Image](https://github.com/user-attachments/assets/9e593aa9-9a40-4145-8359-965bdef22f25)
