### ISSUE TITLE
Some plugin translations are missing

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#258]
![image](https://user-images.githubusercontent.com/45326534/103440024-33e1ef80-4c7d-11eb-9676-654e47a9cd11.png)

**Comment by taooceros** [comment]
I am not able to reproduce that......has anyone encountered the same issue?
@Flow-Launcher/team

**Comment by kubalav** [comment]
Slovak language for Flow Launcher is OK, but plugins stay in English.
![flow-launcher_plugins_translation_issue](https://user-images.githubusercontent.com/37414585/103443879-5830d280-4c63-11eb-940c-87a99faf45e1.gif)

**Comment by JohnTheGr8** [comment]
also notice this: 
![image](https://user-images.githubusercontent.com/697917/103444903-1d846580-4c76-11eb-9bde-7161b6000566.png)

**Comment by JohnTheGr8** [comment]
Updated the title as this is not specific to Slovak, other languages are missing as well. PR with the fix is in.
