### ISSUE TITLE
BUG: File located in C drive is not shown

### ISSUE THREAD

**Issue by ghost** [Flow-Launcher/Flow.Launcher#2583]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

How do I get Flow to find files on disk C? It doesn't see the files on disk C right now. 
An example image is provided below

### To Reproduce

1. ...Install the portable version
2. ...Search for the file located in C drive
3. ...

### Screenshots

<details><summary>Screenshot</summary>

![resim](https://github.com/Flow-Launcher/Flow.Launcher/assets/159805336/32ea3c58-c8ab-4d65-af0d-c6672c342124)

</details>

### Flow Launcher Version

1.17.2

### Windows Build Number

Win 10 22H2

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Are you using Windows Indexing or Everything for your search?

**Comment by deefrawley** [comment]
Flow uses Windows Search or Everything to do the actual file searching. Activate Flow and type in Settings. Then go to Plugins - Explorer and check the options there.
