### ISSUE TITLE
Google search suggestions

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#2584]
**Is your feature request related to a problem? Please describe.**
It would be great if the google search extension could provide google search suggestions like in chrome

Right now there are no suggestions when you type in your query

**Describe the solution you'd like**

![Screenshot 2024-02-24 125501](https://github.com/Flow-Launcher/Flow.Launcher/assets/47380919/0e988933-3be4-4b28-99c4-b1f03e7372ed)

This is a screenshot of the chrome browser address bar results and suggestions when you type without pressing enter.

**Comment by z1nc0r3** [comment]
If you mean suggestions, the **Web Searches** plugin already supports search query autocomplete.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/64279853/2c2268d8-b5e2-46c5-954f-f7cfc01b24a4)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/64279853/8b58a3b8-5478-4646-a690-0170818b86ee)

**Comment by Yusyuriv** [comment]
This doesn't seem feasible to implement without knowing what every piece of data in the response could mean. For example, here's the quick response data for the query `hello in italian`:
```json
[[[null,null,null,null,[],[[["hello"],null,["English"],["həˈlō"]],[["Ciao"],null,["Italian"],[""]]]]]]
```
Here's the same property for the query `10 usd in cad`:
```json
[[[null,null,null,null,[],[[["10 United States Dollar \u003d 13.50 Canadian Dollar"]]]]]]
```

**Comment by jjw24** [comment]
Closing this for now. Feel free to reopen should we need to discuss further.
