### ISSUE TITLE
[Feature Request] Command Line Argument to Toggle Flow Launcher (in same way as Alt-Space)

### ISSUE THREAD

**Issue by EnigmaSolved** [Flow-Launcher/Flow.Launcher#2586]
It might be nifty if there could be a command line argument that would toggle the display of Flow Launcher, in the same way that the hotkey (ie, `Alt-Space`) toggles Flow. Currently, calling `Flow.Launcher.exe` correctly displays Flow Launcher (as opposed to launching a new instance), but there is no way (that I know of!) via the .exe to then hide Flow Launcher again in the way that executing the hotkey `Alt-Space` will hide Flow Launcher.

Granted, in most cases  using the hotkey combo is going to be easiest and best, but there are some circumstances in which there can be a desire to toggle Flow from something other than a hotkey. One example is the recent exploration of using the `Win` key to toggle Flow, which, last I checked, is internally calling `Alt-Space` in order to toggle Flow Launcher:

- https://github.com/Flow-Launcher/Flow.Launcher/discussions/747#discussioncomment-8557199
- https://github.com/Flow-Launcher/Flow.Launcher/issues/662
- https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey

I do not know for certain, but it seems possible to me that it would be cleaner, more direct, perhaps faster(?) if things like the above could directly toggle Flow instead of the user executing a hotkey (ie, `Win`) which then programmatically executes the true hotkey (ie, `Alt-Space`). Additionally, sometimes there can be funky issues with programmatic execution of hotkeys where you end up with stuck hotkeys (eg, the computer things `Shift`, `Alt`, etc are still held down), and a more direct interface for programmatically toggling Flow would avoid this possibility.

In my particular case, I am making use of [HotFrameFx](https://github.com/kruizer23/hotframefx), which has support for some hotkey combos, but not all (currently). I have worked around that limitation by having HotFrameFx execute a simple AutoIt script which in turn executes the `Alt-Space` hotkey. But if there were (or is) a argument I could pass to the Flow .exe (eg, `Flow.Launcher.exe -toggle`) so that it would always toggle the Flow state that would certainly be more efficient in my particular case.

Just some things to consider! I know there are so many ideas to implement, so I do not expect this to be high need/priority. But thought it was worth putting out here. And if there _**is**_ already an argument I can pass to the .exe to toggle Flow that would be awesome to know! :)

**Comment by taooceros** [comment]
interesting! Do you want to file a pr? I can show you where might be the starting point! I don't think we have a good command line argument so maybe that can also be added.

**Comment by EnigmaSolved** [comment]
> interesting! Do you want to file a pr? I can show you where might be the starting point! I don't think we have a good command line argument so maybe that can also be added.

In theory/principle I would love to contribute a PR -- whether I can realistically follow through on that right now time-wise is another story. 😆 But yes, I would be happy to be directed to a starting point in the code and at least my brain can be percolating on it (and any other interested parties will then also have the same starting point to work with as well, in the event someone else is able to get to it before me). :)

**Comment by taooceros** [comment]
The startup code starts at this line https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/App.xaml.cs#L49

and the code handling opening an existing process is here https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/Helper/SingleInstance.cs#L185

https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/App.xaml.cs#L189 and probably some code here might be interesting https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/Helper/SingleInstance.cs#L322-L339

**Comment by EnigmaSolved** [comment]
Looking through that helpful list I would add the following two:

https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/Helper/HotKeyMapper.cs#L29

https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/ViewModel/MainViewModel.cs#L1032

It seems to me that `ToggleFlowLauncher()` is what we'd be wanting to invoke. 

Actually, it occurs to me that the current behavior is that when `Flow.Launcher.exe` is executed the first time (ie, not already loaded) the Flow dialog is not displayed -- it is only on a second execution of `Flow.Launcher.exe` that the dialog is displayed. So in theory, we could just replace the code that is executed on a second `Flow.Launcher.exe` execution with a call to `ToggleFlowLauncher()` and then we do not need a command line at all -- any clicking/executing of the `Flow.Launcher.exe` after it is already running will then automatically toggle it, which seems to me the intuitive result anyway. :)

So I think it _might_ be as simple as replacing `_mainVM.Show();` with `_mainVM.ToggleFlowLauncher();` on the following line:
https://github.com/Flow-Launcher/Flow.Launcher/blob/dfd1b8c66a44d1679415f32eeaae594003602d55/Flow.Launcher/App.xaml.cs#L191

I sadly do not have an environment setup to build and test this, but let me know what you think -- this might be a very simple addition! :)

**Comment by taooceros** [comment]
If you want to change the current behavior we may need extra discussion, in which I personally are not sure about it @Flow-Launcher/team. That may requires you to send different message through the pipe for parsing though.

**Comment by AminSallah** [comment]
Hey there, I noticed that Flow can handle launching a new process while an existing process is running. This means you can initiate a new process to trigger Flow if it's already running, using %localappdata%\FlowLauncher\Flow.Launcher.exe.

**Comment by EnigmaSolved** [comment]
> If you want to change the current behavior we may need extra discussion, in which I personally are not sure about it @Flow-Launcher/team.
> 
> If you want to extend some command line argument then you can manipulate the message sent through the pipe and parse it accordingly to determine which action should be acted.

Hmm, I am reticent to take up mental energy from the Flow Launcher team on something like this that is rather low priority (ie, potentially nice to have, but not necessary). I've also been doing some more thinking and experimenting (in part in response to a side conversation with @AminSallah ), and while I still think it could be a nifty little change (with potentially no downsides), it is probably not going to be as effective for my purposes (and definitely not needed for the Win key plugin) as I was originally thinking. At the moment I could be fine with letting this sit for a bit and/or perhaps closing it for now.

> Hey there, I noticed that Flow can handle launching a new process while an existing process is running. This means you can initiate a new process to trigger Flow if it's already running, using `%localappdata%\FlowLauncher\Flow.Launcher.exe`

Yes, thanks @AminSallah ! That is what I was playing with conceptually, is how to change that from just launching to also being able to toggle. :)

**Comment by jjw24** [comment]
Thanks for the suggestion @EnigmaSolved, sounds like you got the answer/feedback from @AminSallah already, I will close this issue. Feel free to reopen at any point if you want to further the discussion.
