### ISSUE TITLE
BUG: Flow launcher detected as cheats by EAC

### ISSUE THREAD

**Issue by niceEli** [Flow-Launcher/Flow.Launcher#2600]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I was about to play the finals and it had said that I had cheating software installed and prevented me from opening game. After removing Flow Launcher it no longer said I had cheating software installed

### To Reproduce

1. Install flow launcher
2. Install Win Hotkey (this may not matter but it could be caused by it)
3. Launch The Finals On Steam

### Flow Launcher Version

1.17.2

### Windows Build Number

I dont have it installed anymore but it was the one from github releases

### Error Log

There isnt any log as the issue is EAC detecting as cheats

**Comment by deefrawley** [comment]
It is not cheat software.
Was Flow the only thing you removed? Nothing else like AHK??

**Comment by deefrawley** [comment]
Can confirm it's not Flow. I had to exit AHK before the game would run but started up no problems with Flow running

**Comment by niceEli** [comment]
I don't have AHK installed

**Comment by jjw24** [comment]
Win Hotkey plugin v2 uses the AHK library so that may be what's triggering it.

**Comment by vvirtues** [comment]
> Win Hotkey plugin v2 uses the AHK library so that may be what's triggering it.

I noticed this as well, for some reason game mode is ineffective. Any other ways to run the game without EAC getting mad

**Comment by VictoriousRaptor** [comment]
> > Win Hotkey plugin v2 uses the AHK library so that may be what's triggering it.
> 
> I noticed this as well, for some reason game mode is ineffective. Any other ways to run the game without EAC getting mad

Game mode is just about not to trigger Flow when it's enabled, not related to anti-cheat.

**Comment by jjw24** [comment]
Does this still happen if you just have flow installed and nothing else (no additional plugins) ?

**Comment by vvirtues** [comment]
No

**Comment by onesounds** [comment]
It's probably something to do with using AHK related, I have the same problem.
I was frustrated with having to turn off the relevant processes before playing the game, and then having to rerun them after the game was over. so I created and use a simple script for this. Kills certain programs when you launch the game, and re-launches certain programs when you exit the game.

This is powershell script ver.
```
# Filename: launch_game.ps1

Write-Output "Starting the game and closing specific processes..."

# Close Specific process
Stop-Process -Name AutoHotkey -Force
Stop-Process -Name AutoDarkModeSvc -Force
Stop-Process -Name Flow.Launcher -Force

# run game.
Start-Process "C:\Riot Games\Riot Client\RiotClientServices.exe" "--launch-product=league_of_legends --launch-patchline=live"
Start-Process "C:\Users\blahblah\AppData\Local\Programs\Blitz\Blitz.exe" -WindowStyle Minimized

# Medal.exe start with minimized
Start-Process "C:\Users\blahblah\AppData\Local\Medal\app-4.2203.0\Medal.exe" -WindowStyle Minimized -RedirectStandardOutput ([System.IO.StreamWriter]::new([System.IO.Stream]::Null))

# Waiting for exit game
while (Get-Process -Name RiotClientServices -ErrorAction SilentlyContinue) {
    Start-Sleep -Seconds 10
}

Write-Output "Game has exited. Performing cleanup tasks..."

# Relaunch specific programs.
Start-Process "C:\DEV\Flow Launcher\Output\Release\Flow.Launcher.exe"
Start-Process "C:\VolumeScroll.ahk"
Stop-Process -Name Blitz -Force

```
.bat version.

```
@echo off

:launch_game
echo Starting the game and closing specific processes...

REM Exit processes
taskkill /F /IM AutoHotkey.exe
taskkill /F /IM AutoDarkModeSvc.exe
taskkill /F /IM Flow.Launcher.exe

REM Run game
start "" "C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=league_of_legends --launch-patchline=live
start /MIN "" "C:\Users\blah\AppData\Local\Programs\Blitz\Blitz.exe"
start /MIN "" "C:\Users\blah\AppData\Local\Medal\app-4.2203.0\Medal.exe"

REM Wait for game close
:wait_for_game
tasklist /FI "IMAGENAME eq RiotClientServices.exe" 2>NUL | find /I /N "RiotClientServices.exe">NUL
if "%ERRORLEVEL%"=="0" (
    timeout /T 10 /NOBREAK >NUL
    goto wait_for_game
)

:cleanup
echo Game has exited. Performing cleanup tasks...

REM Relaunch
start "" "C:\DEV\Flow Launcher\Output\Release\Flow.Launcher.exe"
start "" "C:\VolumeScroll.ahk"
taskkill /F /IM Blitz.exe
taskkill /F /IM Medal.exe
```

I've considered building this into flow on its own, but flow's official support for winkey would have to come first. However, it's a bit difficult to implement, so this seems like the best way to go for now. I hope this helps.
