### ISSUE TITLE
Ability to select multiple plugins and then install/uninstall

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#2607]
**Is your feature request related to a problem? Please describe.**

Right now if you want to install multiple plugins then you have to install one at a time while restarting after each installation.

**Describe the solution you'd like**

A checkbox type system where you can select multiple plugins at a time and then install/uninstall them.

**Comment by VictoriousRaptor** [comment]
You don't need to restart after each install. But you need to manually enable this feature in Plugin Manager.

**Comment by bodzebod** [comment]
I don't see where to enable this feature in the latest version, there's no such setting in the latest version.

**Comment by VictoriousRaptor** [comment]
> I don't see where to enable this feature in the latest version, there's no such setting in the latest version.

In the settings window, navigate to Plugins->Plugin Manager, "Don't automatically restart after installing/uninstalling plugins".
