### ISSUE TITLE
BUG: Flow Launcher does not open Web Searches in Arc Browser

### ISSUE THREAD

**Issue by pratyakshm** [Flow-Launcher/Flow.Launcher#2614]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When I type a web search query in Flow Launcher and press to open it in the default browser, the browser opens but a new tab concerning the query never opens.

Arc is a new web browser for Windows, currently in closed beta. Should it be necessary for you to use the browser, join the waitlist at https://www.isarconwindowsyet.com/.

### To Reproduce

1. Invoke Flow Launcher and type in a web search query.
2. Press Enter. Now, you expect the query to open in a new tab in the default web browser.
3. Actually, focus is shifted to the default web browser. However, a new tab for the search result of the typed query is never created. Instead, the web browser sits blank and clueless as its last state.

I have run the following command just to determine if the issue lies with in Arc browser itself, and it worked fine.
```powershell
Start-Process https://google.com
```
 Also, all external links to web sites open inside Arc browser as expected. Thus, it's safe to say that the issue lies within Flow Launcher.

### Screenshots

https://github.com/Flow-Launcher/Flow.Launcher/assets/54220235/08a3f541-86f2-4571-bf4b-04fa13351e8c

### Flow Launcher Version

1.17.2

### Windows Build Number

22635.3276

### Error Log

<details>

```shell
23:49:20.7847+05:30 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
23:49:20.7895+05:30 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.17.2
OS Version: 22635.3276
IntPtr Length: 8
x64: True
23:49:21.1729+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <4ms>
23:49:21.1729+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <4ms>
23:49:21.1729+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <2ms>
23:49:21.1804+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <17ms>
23:49:21.1804+05:30 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:49:21.1979+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <27ms>
23:49:21.1979+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <24ms>
23:49:21.2134+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <46ms>
23:49:21.2134+05:30 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <17ms>
23:49:21.2134+05:30 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <160>
23:49:21.2134+05:30 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <70>
23:49:21.2393+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <73ms>
23:49:21.2513+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <54ms>
23:49:21.2659+05:30 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:49:21.2659+05:30 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:49:21.2659+05:30 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
23:49:21.2659+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <105ms>
23:49:21.2659+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <108ms>
23:49:21.4767+05:30 - INFO  - CommunityPluginSource.FetchAsync - Loaded 153 plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:49:21.4767+05:30 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <317ms>
23:49:21.7901+05:30 - INFO  - App.OnStartup - Dependencies Info:
Python Path: C:\Users\Praty\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: 
23:49:22.0948+05:30 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
23:49:22.1038+05:30 - INFO  - App.OnStartup - Startup cost <1477ms>
23:49:22.2514+05:30 - INFO  - ImageLoader.Initialize - Preload images cost <1030ms>
23:49:22.2514+05:30 - INFO  - ImageLoader.Initialize - Number of preload images is <50>, Images Number: 50, Unique Items 17

```
</details>

**Comment by deefrawley** [comment]
Does it work when you specify Arc in the Default Web Browser setting for Flow?

**Comment by pratyakshm** [comment]
@djordjepekic Hi, no, it does not work even after adding a new entry for Arc in the Default Web Browser setting.

Screen shot of the setting:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/54220235/47c16905-d5b0-4ebd-aef9-b26edfedea4b)

**Comment by djordjepekic** [comment]
Wrong @ 😁

**Comment by pratyakshm** [comment]
Oops, sorry about that, @djordjepekic.

Looping in @deefrawley to the ticket.

**Comment by taooceros** [comment]
maybe they shares a slightly different command line arg compared to other browser...

**Comment by taooceros** [comment]
Probably nothing much we can do without a document or at least access to arc....if you understand how their command line interface work we are happy to accept pr.

**Comment by Yusyuriv** [comment]
Keep in mind that Arc for Windows is still very much experimental (latest version is 0.14.1) and lacks a lot of features present in all other browsers. For example, they added closing tabs by pressing Ctrl+F4 only 8 days ago.

**Comment by Yusyuriv** [comment]
That being said, I do have access to it, so if anyone has any ideas, I'm happy to try them.

**Comment by taooceros** [comment]
I downloaded it (with school email). Seems to be interesting. As it is a appx package, it probably requires some additional handling compared to other browser. Also there's no document about the command line usage....

**Comment by taooceros** [comment]
I guess the problem is on their side. There's no command line argument for its app....

**Comment by deefrawley** [comment]
Changing this from a bug to an enhancement as it seems the issue is with the browser, not Flow.

**Comment by pratyakshm** [comment]
Yep, I've contacted them regarding this issue. Hoping that they attend to this.

**Comment by DianP** [comment]
@pratyakshm 

I've been tinkering for awhile for this, and i accidently found this.

This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.

[Untitled-video-Made-with-Clipcha.webm](https://github.com/Flow-Launcher/Flow.Launcher/assets/34946363/223da9e7-a4b5-4b20-a1c7-79dc2b9fb83d)

**Comment by ricktrade** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm


Thanks for posting!
This also worked for me! 

Running Arc Build : 0.17.2.21183 (0000)
OS Version: 10.0.19045
and Flow launcher 1.18.0

**Comment by pratyakshm** [comment]
@DianP that's hilarious and interesting! 😆
quite curious how it works under the hood just like that.

but thanks haha!

**Comment by TheJustinCrow** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm

Thanks for sharing, though this doesn't work for me. Does anyone have any ideas other than this?

**Comment by notashleel** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm

Thank you for sharing this! It works like a charm!

**Comment by jdkcoder** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm

Magic LOL. It worked!!!

**Comment by HaveSomeRubicon** [comment]
wow i did not expect that to work lol

**Comment by IgorWeisss** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm

Works like a charm! Thanks so much!

**Comment by JamexCEO** [comment]
> @pratyakshm
> 
> I've been tinkering for awhile for this, and i accidently found this.
> 
> This is my setup: Basically in the General > Default Browser > Add > and insert the path to some random wording like "Non Existence Path" And it works 😲.
> 
>  Untitled-video-Made-with-Clipcha.webm

Thank you!

**Comment by AbdullahElTiby** [comment]
bro the fix for it is to add any shit in the path and it will work

![Image](https://github.com/user-attachments/assets/0e955688-517b-4d04-8d4f-613687f7a4bf)

**Comment by ysnztrk021** [comment]
Flow Launcher can open Arc Web Browser but It can't make searchs on it

**Comment by MarbDeWcEend** [comment]
> Flow Launcher can open Arc Web Browser but It can't make searchs on it

It somehow does work if you:
- Name the browser Arc
- Put random gibberish in the "browser path" field
