### ISSUE TITLE
BUG: Missing translations

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#2620]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The key `registerHotkeyFailed` isn't used in translations. The error message is displayed in English even if there is a translation. I have tried several languages.

### Flow Launcher Version

1.17.2

### Windows Build Number

10.0.22621.3296

**Comment by taooceros** [comment]
It's used here? https://github.com/Flow-Launcher/Flow.Launcher/blob/18d6f67d285d698eb8980782dcf05631d31b8756/Flow.Launcher/Helper/HotKeyMapper.cs#L47

**Comment by taooceros** [comment]
Could you share a screenshot about the message that is only displayed in english?

**Comment by kubalav** [comment]
> Could you share a screenshot about the message that is only displayed in english?

I cant reproduce this error message. I can provide text only:

> Failed to register hotkey "{0}". The hotkey may be in use by another program. Change to a different hotkey, or exit another program.

**Comment by taooceros** [comment]
Could you recall how to you get this error message? Maybe list about how to reproduce?

**Comment by kubalav** [comment]
I was able to reproduce the error. It is enough if some application has an associated shortcut key like Flow Launcher uses to open the query box. Then you need to launch the Flow Launcher and the error message will be displayed at startup.

**Comment by jjw24** [comment]
@taooceros I think this error msg box is the one where the flow activation hotkey is being used by another program prior to flow registering it for itself. To repro- change flow to alt space hotkey, close flow, open PT Run which should be using the default alt space hotkey, and finally open flow and should see that error message.

**Comment by VictoriousRaptor** [comment]
Are the translations loaded before hotkey registering?
