### ISSUE TITLE
BUG: Failed to register shortcut Alt + Space (Alt + LeftAlt)

### ISSUE THREAD

**Issue by TheBadFalcon** [Flow-Launcher/Flow.Launcher#2622]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

One day I just opend my pc and Flow did not want to start with the shortcut alt+space. I opend to program, changed the opening shortcut to ctrl + space, and than wanted to change it back to alt + space. There are 2 weird thing that happend. 1) It says: Hotkey Unavailable. 2) My Pc says I pressed the buttons Alt + LeftAlt. When I press ctrl + space there is no problem. I checked if Power tools is running, or if wox in running. These are not running. 
I saw some other people with a realated issue, but I have not found anything exactly like this.
If you need anything more from me, I will do what  I can!

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/165212639/22dffcab-2dad-4970-9af5-64fab214f385)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/165212639/779be4ee-4318-48ba-b32f-20197ab96528)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/165212639/7465b3cb-5241-4cd3-a988-5a28c1c513f8)

### Flow Launcher Version

1.17.2

### Windows Build Number

Microsoft Windows [Version 10.0.22631.3296]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Doing some testing I get this when I press only LEFT ALT as the hotkey. Are you sure the space key is registering when using with the ALT combination? Did you try exiting Flow completely, restarting and trying again?

**Comment by TheBadFalcon** [comment]
O, I see. If I only press the left alt key it indeed syas Alt+ Left Alt. But if I Press ctrl + space it says ctrl + space, and if I press shift + space it also says Shift + space. So those two work. 
When I checked a little bit more, I found that the combination ctrl + alt + space does work. (This is also the same as alt gr + space) (the right alt key on my keyboard)

**Comment by deefrawley** [comment]
What keyboard layout and language are you using in Windows. I know some non US//UK English settings has caused other issues in the past.

**Comment by kubalav** [comment]
Have you tried restarting your PC? This is exactly what happened to me recently. After rebooting the computer everything worked again.

**Comment by TheBadFalcon** [comment]
Yes, I have allready tried to restard my Pc, and it did noting.

**Comment by VictoriousRaptor** [comment]
Could you use apps like openark to check if alt+space is already occupied?

**Comment by autoferrit** [comment]
So I am also getting this issue. using "Hotkey Detective" if i hit `alt = space` it just opens up the windows system context menu, and that nothing is taking up this shortcut.

if i set the shortcut to ctrl space it registers fine. if i press ONLY left alt the shortcut box does indeed say "LeftAlt". But if i press `lalt + space` it says the shortcut is `alt + LeftAlt`.

**Comment by deefrawley** [comment]
> So I am also getting this issue. using "Hotkey Detective" if i hit `alt = space` it just opens up the windows system context menu, and that nothing is taking up this shortcut.
> 
> if i set the shortcut to ctrl space it registers fine. if i press ONLY left alt the shortcut box does indeed say "LeftAlt". But if i press `lalt + space` it says the shortcut is `alt + LeftAlt`.

What is your keyboard layout?

**Comment by TheBadFalcon** [comment]
> Could you use apps like openark to check if alt+space is already occupied?

I got the program. But how does it work? Where could I find what hot-keys are occupied?

**Comment by TheBadFalcon** [comment]
I dont know what happend. Maby there was a new flow update. But my problem is now fixed.

**Comment by kubalav** [comment]
In my case, the culprit was the **Samsung Magician**.

**Comment by BillEisenman** [comment]
this still occurs on Windows 11 24H2

**Comment by MrNaughtZero** [comment]
This issue still happens as of of today. Windows 11 24H2

**Comment by CyberGhost13337** [comment]
For me it was powertoys shortcut I disabled and worked

![Image](https://github.com/user-attachments/assets/ad3e7e81-d961-432f-824a-094eda504e82)

**Comment by pnavais** [comment]
A bit late to the party but you can use this app to detect the app using the shortcut  : https://www.ntwind.com/freeware/hotkey-screener.html 

In my case it was Copilot :(
