### ISSUE TITLE
BUG: Flow Launcher Receives Error When Opening Settings

### ISSUE THREAD

**Issue by jeffippy24** [Flow-Launcher/Flow.Launcher#2631]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Every time I open the flow launcher settings I receive an error.

Additionally, lately I have noticed normal functions have stopped working (including basic calculator functions and file search functions)

### To Reproduce

1. ...Open Flow Launcher Settings
2. ...
3. ...

### Flow Launcher Version

1.17.2

### Windows Build Number

10.0.22631.3296

### Error Log

[2024-04-02.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14843990/2024-04-02.txt)

**Comment by taooceros** [comment]
screenshot?

**Comment by jeffippy24** [comment]
![Screenshot 2024-04-02 181001](https://github.com/Flow-Launcher/Flow.Launcher/assets/128951040/a1159d8e-6211-468e-80b8-575c7294e33c)

**Comment by z1nc0r3** [comment]
I couldn't reproduce the issue. Does the bug still exist?

**Comment by z1nc0r3** [comment]
I couldn't reproduce the issue. Does the bug still exist?

**Comment by deefrawley** [comment]
Please update to the latest version and retry. If the problem still exists we can reopen this issue. Thanks
