### ISSUE TITLE
Allow user to change font size to better fit there preference

### ISSUE THREAD

**Issue by Dev123456689** [Flow-Launcher/Flow.Launcher#2632]
**Is your feature request related to a problem? Please describe.**

**Font size is very small** and i am not able to change it, it **very difficult to read and use the software** with such small font.

**Describe the solution you'd like**

Allow the user to change font size on their, so they can change the font size as per their preference. It would be better is there we can control is more granularly then having only 3 presets of 'small' 'medium' and 'large' or something like such.

**Describe alternatives you've considered**

Can't think of any alternative solution.

**Additional context**

N/A

**Comment by onesounds** [comment]
It will be added along with the improvement of the theme function.
