### ISSUE TITLE
SavvyCal Plugin

### ISSUE THREAD

**Issue by perryraskin** [Flow-Launcher/Flow.Launcher#2633]
I just came across Flow Launcher from doing a search for a Raycast Windows alternative, and it looks great, well done!

Wondering how easy it might be to add a plugin that is essentially just a list of the user's SavvyCal meeting links. Screenshot below of how Raycast has it:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/17967465/68bf365c-c193-4121-9158-ef3e6c10e4bf)

**Comment by Yusyuriv** [comment]
This should be a good starting point: https://github.com/Yusyuriv/FlowLauncherCommunity.Plugin.SavvyCallLinkList

Please keep in mind that your API token is not going to be encrypted, it will be saved in a file as plain text. If you're okay with it, you can type the following command to install the plugin built from the repository I provided:
```
pm install https://github.com/Yusyuriv/FlowLauncherCommunity.Plugin.SavvyCallLinkList/releases/download/v1.0.0/FlowLauncherCommunity.Plugin.SavvyCalLinkList.zip
```
If not, you're free to change the source code I provided to fit your needs.

The plugin only lists the first 100 links, but I think the Raycast plugin also only lists the first 100 links. It updates your links every 5 minutes, every time you change your API key in settings, and when you manually press F5 in Flow Launcher's window. By default when you press `Enter` with a link selected, it copies the link:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/2007881a-054d-4a93-bb9b-44ff4fc4c65c)

You can press `Shift + Enter` to open the context menu with additional actions:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/382d31f8-e1f6-46af-a8bf-5b684143196e)
