### ISSUE TITLE
BUG: When Flow Launcher is running as administrator programs opened by it are automalically granted administrator previllage.

### ISSUE THREAD

**Issue by Dev123456689** [Flow-Launcher/Flow.Launcher#2638]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When Flow Launcher runs as an administrator, programs opened through it are automatically granted admin privileges without even prompting the user for permission, introducing a significant security risk by potentially running non-admin programs with elevated permissions. I need to run Flow Launcher as an adminitrator because of a plugin called "WinHotKey" requires administrative access to function properly, and i have no problem in running flow launcher as administrator but not all applications it opens.

Additionally i want to request a feature that given an option to the user in flow launcher setting to always run flow launcher as an administrator at startup because for the above mentioned plugin to run properly i had to manually create a scheduled task to run flow launcher as administrator. **I know it is not a place for feature requests but i wrote it because it is closely linked with the above mentioned bug.**

### To Reproduce

1. Run Flow launcher as administrator
2. Open any program with it (example: cmd, notepad, etc)
3. The program will be automatically ran as administrator **without user promting it to and without promting the use for permission.**

### Flow Launcher Version

1.17.2

### Windows Build Number

10.0.22631.3296

### Error Log

<details>

```shell


Replace this line with the important log contents.

```
</details>
Only found this log file:

[SquirrelSetup.log](https://github.com/Flow-Launcher/Flow.Launcher/files/14897757/SquirrelSetup.log)

**Comment by VictoriousRaptor** [comment]
It's the default behavior of Windows. We'll see if we can revert this behavior.

But why you need to run Flow as admin? I've just tried the plugin, it works without admin privileges.

**Comment by Dev123456689** [comment]
I wrote to work **properly**, it work without running as admin but it doesn't work properly. See [this](https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey/issues/7) issue for why it is needed. But I can summarise it to you, without running as admin winhotkey plugin cannot capture the key pressed when an admin application is in focus.

**Comment by Garulf** [comment]
> @VictoriousRaptor waiting for a response from flow Launcher devs for more than a month. Are devs working on the issue?

I apologize for the delay. 

Running Flow Launcher as admin is not recommended. 
The side effects you are experiencing are default Windows behavior and are not the fault of Flow Launcher.

We appreciate your understanding.
