### ISSUE TITLE
pm install not to show plugins already installed

### ISSUE THREAD

**Issue by deefrawley** [Flow-Launcher/Flow.Launcher#264]
**Is your feature request related to a problem? Please describe.**

The plugin manager command `pm install` shows all plugins whether they are installed or not. If you try and install again, a toaster popup tells you it is already there. It would be good for users to see the status without trying the install again.

**Describe the solution you'd like**

The install command only lists available plugins that aren't already installed.

**Describe alternatives you've considered**

Perhaps change the icon in the query result to indicate plugins that are already installed?

**Comment by taooceros** [comment]
@jjw24 make it as InstallOrUpdate so that it is not quite simply install. The "install" keyword is added later after he has finished the main part. I agree with you that we should put installed plugin out of the install results list. Since it will be quite easy to see them with uninstall or update.
@jjw24 what do you think?

**Comment by jjw24** [comment]
Maybe we can do something like, for installed plugins, if there is new version, show, else exclude

**Comment by taooceros** [comment]
> Maybe we can do something like, for installed plugins, if there is new version, show, else exclude

Maybe with a special sign that it has a new release in SubTitle or Title?

**Comment by jjw24** [comment]
I quite like the icon in the query box to indicate installed as well, but we haven't got anything wired up at the moment for it, there is a similar issue in the pipeline to do something similar, once that's done we can do something like this as well

**Comment by jjw24** [comment]
> > Maybe we can do something like, for installed plugins, if there is new version, show, else exclude
> 
> Maybe with a special sign that it has a new release in SubTitle or Title?

Yeah this will require reconstruct the result though than simply exclude, but either way is fine

**Comment by deefrawley** [comment]
As you are looking at the plugin display result functionality, would it be beneficial to indicate what language the plugin is written in and if Python and Python path isn't set in Flow, show a warning (something that could be extended to other languages down the line)?

**Comment by taooceros** [comment]
Let's write a more comprehensive proposal.

`pm list` results a list of all plugins, both installed & uninstalled.
- [ ] include inbuilt plugin
- Action:
  - installed $\to$
  - -  [ ] uninstall
  - -  [ ] update
  -

**Comment by taooceros** [comment]
@Flow-Launcher/team thoughts?

**Comment by deefrawley** [comment]
I think pm install showing updateable plugins and pm update is redundant. Only need one. I think pm install is a good option if you can make anything requiring an update display first in the results. Also can we please include the plugin version in the plugin description (and the new version for the update entries).

**Comment by taooceros** [comment]
I would consider allowing another optional keyword `pm update` won't be a burden for user. Though, i think it's a good idea to letting users know an update is available with `pm install`.

**Comment by taooceros** [comment]
if `pm install` shows all updatable plugin, probably we should keep `pm list` away from non-installed plugin. Thoughts?

**Comment by jjw24** [comment]
Yes pm list should just show what's currently installed.

**Comment by jjw24** [comment]
I think pm list can show non-installed, is there any complexity in doings so?

**Comment by jjw24** [comment]
Closing this one since no longer relevant. Feel free to reopen if not the case.
