### ISSUE TITLE
BUG: Explorer plugin search with Everything

### ISSUE THREAD

**Issue by DFreezerR** [Flow-Launcher/Flow.Launcher#2656]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Same search prompts in Flow launcher search box and Everything returns different results.  Examples below.
<details>
  <summary>Case 1</summary>
  Trying to search - C:\Downloads\ venc 
  Well basically you can use any full path + word to search with space between them like {path} {word}
  
Results in app:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/9fdf59aa-0a3f-42bc-b3f0-3c2400f6a1c9)

Results in Everything:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/457fb6e4-24f1-4e4a-a758-bc15c77dfd5e)

The results clearly different. BUT it somehow works if we add "" to the path or don use full path
Results in app with "":
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/6c6ce569-090e-490e-a43a-8be5d104ac93)

Results in app without full path:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/953bf018-28f6-4792-a235-471ae8bda66b)

It also works if we use some Everything's functions like "parent:":
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/9f289d8d-9ed5-458b-bd54-a4e49333d6a3)

</details>

<details>
  <summary>Case 2</summary>

Trying to search - C:\Downloads\ *.jpg

Again - can be any extension.
Result in both apps:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/be08e667-7818-4c64-8955-7e9aaae7bbcd)

</details>

To me it looks like plugin tries to use "default" search instead of Everything, and only when "forces" with some syntaxis/keywords it can search with Everything.
Why the exact same query not working in plugin search? 

</details>

<details>
  <summary>Settings in app</summary>

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/3b923e7c-6b97-4347-93eb-df4d0a834cd3)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/66f424c4-d49b-4a41-83cf-cb4c7b6f95d1)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/1558ca3c-88db-45c3-a2fa-d688d64692e9)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/8be5e543-9996-4a53-b256-8a4fa11338cd)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/ff65a0fe-67eb-4b17-8b96-33f24ca5f56c)

</details>

### To Reproduce

1. Install Flow.Launcher (1.17.2)
2. Switch everything in Explorer plugin to Everything app
3. Try searching
4. Install Everything app when asked
5. Try to search with both Flow.Launcher and Everything with examples I provided

### Flow Launcher Version

1.17.2

### Windows Build Number

Windows 11 Pro 22631.3155

**Comment by deefrawley** [comment]
Why are you using a space for the filespec after the folder? `C:\downloads\*.jpg` will find those files

**Comment by DFreezerR** [comment]
> Why are you using a space for the filespec after the folder? `C:\downloads\*.jpg` will find those files

Because I expected consistency in searching with Everything and Everything in Explorer plugin. I believe `C:\downloads\*.jpg` is an example of default Windows masked search, while you can use `C:\downloads\ *.jpg` in Everything. As stated in Everything docs, space used as AND keyword to search for right part and left one, in my example `C:\downloads\` is part of the path and `*.jpg` is file name, and they are combined with logical AND (space). There is a lot of non consistent behavior between Everything and in app plugin - you also can't use something like `C:\downloads\ regex:^read` 

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/60145703/34c4fee3-b40f-4ccc-b6d9-642f56e214d9)

The reason I liked the idea of using Everything with Explorer plugin was because Everything has very convenient search for me. But  it's troubling as I can't use the same thing in Explorer plugin even though I selected Everything everywhere in the settings.

And I hope you can agree with me that the same search not working in plugin is not very ideal thing.

**Comment by deefrawley** [comment]
Flow handles spaces differently to identify keywords and arguments so as to trigger plugins, therefor any functionality of Everything that works with spaces will not work here. I'm not a core developer though so happy for one of them to jump in and confirm or offer alternatives.

**Comment by DFreezerR** [comment]
> Flow handles spaces differently to identify keywords and arguments so as to trigger plugins, therefor any functionality of Everything that works with spaces will not work here. I'm not a core developer though so happy for one of them to jump in and confirm or offer alternatives.

Thanks though for your answer
Yes, me too. I can understand that Flow might handle spaces differently. But even if so, in that particular case I think there is no problem to make space work as in Everything (though I'm also not a dev here). On screenshots above I can tell that plugin recognized which one it should trigger, even with space, but again it "feels" like it's trying to use "default" search instead of Everything (but maybe I'm wrong).
Would be exciting to see if one of core devs can clarify this situation, and maybe there is a way to make this work consistently.

**Comment by deefrawley** [comment]
@jjw24 @taooceros  is this possible? If not, let's close

**Comment by jjw24** [comment]
Probably does make sense to align search behaviour with Everything search engine to the behaviour using native Everything app. The space in-between the two terms is probably the same as using '>' in flow, essentially you are providing a path and you search for 'venc' in that path.

I personally can't promise when I can add this in, but hopefully someone else will be able to in the meantime.
