### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by jonesy-b-dev** [Flow-Launcher/Flow.Launcher#2659]
### Checks

- [X] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

No plugins displaying in the plugin store

### To Reproduce

1. Open settings window
2. Go to plugin store

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/59418915/5e210da9-9940-48fa-9a39-6a8b8e87ffd2)

### Flow Launcher Version

1.16.2

### Windows Build Number

Microsoft Windows [Version 10.0.22631.3447]

### Error Log

[2024-04-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/15060168/2024-04-22.txt)

**Comment by z1nc0r3** [comment]
Please update the FL to the latest version (1.18.0) and try again.

**Comment by jonesy-b-dev** [comment]
Updating fixed the issue, thanks
