### ISSUE TITLE
Feature: index windows settings

### ISSUE THREAD

**Issue by giggio** [Flow-Launcher/Flow.Launcher#266]
**Describe the solution you'd like**

There should be a way to index Windows settings. For example, if I click on the Windows button and type `vpn`, Windows shows me vpn settings:

![vpn search windows](https://user-images.githubusercontent.com/334958/80309801-93faca80-87ad-11ea-9b4f-f1c94e5affed.png)

This does not work with Flow Launcher.

This is similar from https://github.com/Wox-launcher/Wox/issues/2223, but using `> ms-settings:network-vpn` on Flow Launcher also does not work, and it is not searchable.
You get `The filename, directory name, or volume label syntax is incorrect.`.

**Describe alternatives you've considered**

Using Windows regular search. That is not an acceptable, otherwise I wouldn't even use Flow Launcher.

**Additional context**

Brought over from: https://github.com/jjw24/Wox/issues/189

**Comment by jjw24** [comment]
@giggio does `> ms-settings:network-vpn` work with Wox's latest pre-release version?

**Comment by giggio** [comment]
@jjw24 I just tried, and yes, it now works if I use `RunCommand` in the Shell plugin (which is what I normally use). It does not work with CMD or PowerShell.
But it is still not indexable. If I do <kbd>Alt</kbd>+<kbd>Space</kbd> and write `VPN`, it does not find the command, but other vpn programs and files. And If I do <kbd>Alt</kbd>+<kbd>Space</kbd> and write `> VPN` it then finds it.
So, indexing the system settings is still desirable. Maybe it should be a plugin, like the "System Commands" plugin, or similar, that understands Windows Settings.

**Comment by pc223** [comment]
Probaly related:
- https://github.com/Flow-Launcher/Flow.Launcher/issues/255
- https://github.com/Wox-launcher/Wox/issues/2875

**Comment by taooceros** [comment]
Seems that PT-Run is drafting this feature. Will take a look on that later.
https://github.com/microsoft/PowerToys/pull/9137

**Comment by pc223** [comment]
PowerToys just merged 👀 

https://github.com/microsoft/PowerToys/pull/11663

**Comment by taooceros** [comment]
I believe there will be (or already are) quite significant amount of things that are included in 1.8.0, and it has been a while before our last release. Probably we may need to handle this after the release of 1.8.0, or unless another guy is trying to handle this.

**Comment by taooceros** [comment]
I have partially done this job. Once it has been tested, we can moved it to built-in plugin.

**Comment by jjw24** [comment]
Thank you, will assign this to issue to you so no way else will double up on this work

**Comment by taooceros** [comment]
https://github.com/Flow-Launcher/Flow.Plugin.WindowsSettings

**Comment by jjw24** [comment]
@Flow-Launcher/team do we want to merge WindowSettings above with the ControlPanel plugin?

**Comment by pc223** [comment]
> @Flow-Launcher/team do we want to merge WindowSettings above with the ControlPanel plugin?

Yeah, I think we should add this new-style windows settings and hopefully the old school task links to ControlPanel plugin too.

@taooceros About the task links,  what do you think about we generate all the task links out a JSON file similar to how powertoys did with the new-style settings?

So we can use this script to generate all the task links out, and after that use directly the JSON file to query.

https://gist.github.com/pc223/48e9a24ef595cec4465ed41bf880be5f

So we don't have to run Windows APIs on users system every query, only dependencies is a JSON file. (And this API I highly suspect will break in the future).

**Comment by taooceros** [comment]
They do have included control panel item in the json file.

**Comment by pc223** [comment]
> They do have included control panel item in the json file.

I don't see the task links in that JSON file. The task links look like this, It has pages, keywords,... Like the old school "Add or remove programs" task link in the Windows 7/8 times :smile:

```
0  |  Accommodate learning abilities  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageQuestionsCognitive  |  [[u'accomidate', u'accomodates', u'accomodating', u'adjust', u'for'], [u'can', u'not', u'cannot', u"can't", u'difficult', u'to', u'difficulty', u'does', u"doesn't", u'hard', u'not', u'will', u'willnot', u"won't"], [u'disabled', u'handicap', u'handicapped', u'disabilities', u'disability', u'empaired', u'impaired', u'imparied', u'trouble'], [u'cognitive', u'learning']]
1  |  Accommodate low vision  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageEasierToSee  |  [[u'accomidate', u'accomodates', u'accomodating', u'adjust', u'for'], [u'site', u'blindness', u'blurred', u'blurry', u'half', u'legally', u'low', u'vision', u'poor', u'seeing', u'seems', u'sight', u'weak', u'bad', u'eyesight', u'eye-sight'], [u'disabled', u'handicap', u'handicapped', u'disabilities', u'disability', u'empaired', u'impaired', u'imparied', u'trouble'], [u'best', u'better', u'easier', u'easy', u'enhance', u'improvement', u'make', u'more', u'most', u'optimal', u'optimise', u'optimize']]
2  |  Change how your keyboard works  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageKeyboardEasierToUse  |  [[u'switch', u'filterkeys', u'keys', u'stickykeys', u'togglekeys', u'sticky-keys', u'toggle-keys', u'repeat', u'delay', u'hold', u'down', u'rate'], [u'accessibility', u'acessibility', u'ease', u'of'], [u'best', u'better', u'easier', u'easy', u'enhance', u'improvement', u'make', u'more', u'most', u'optimal', u'optimise', u'optimize'], [u'board', u'bord', u'keyboards', u'keyborads', u'keybord']]
3  |  Change how your mouse works  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageEasierToClick  |  [[u'accessibility', u'acessibility', u'ease', u'of'], [u'butons', u'buttons'], [u'adjust', u'ajust', u'alter', u'change', u'edit', u'modify', u'replace', u'reset', u'set', u'switch'], [u'lock', u'clicking', u'doubleclick', u'double-click', u'single-click'], [u'best', u'better', u'easier', u'easy', u'enhance', u'improvement', u'make', u'more', u'most', u'optimal', u'optimise', u'optimize'], [u'move', u'moving', u'shadow', u'speed', u'tails'], [u'mice', u'mouses', u'pointer']]
4  |  Use screen reader  |  control.exe /name Microsoft.EaseOfAccessCenter /page pageNoVisual  |  [[u'adjust', u'ajust', u'alter', u'change', u'edit', u'modify', u'replace', u'reset', u'set', u'switch'], [u'screan', u'readers', u'screenreader', u'windows', u'narrator']]
5  |  Change the Narrator’s voice  |  %windir%\system32\narrator.exe  |  [[u'adjust', u'ajust', u'alter', u'change', u'edit', u'modify', u'replace', u'reset', u'set', u'switch'], [u'sound', u'voices'], [u'screan', u'readers', u'screenreader', u'windows', u'narrator']]
...
```

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/126254959-b4f4104e-bc9a-427c-9348-762a643b5a76.png)
They do have included some, though not all. We can add some of it if we want.

**Comment by taooceros** [comment]
There's one thing the WindowsSettings plugin doesn't provide is the specific icon for different option in control panel.

**Comment by pc223** [comment]
> There're a few things the WindowsSettings plugin doesn't provide in control panel plugin.
> 
> 1. Detail Info Tip for Items
> 2. Different Icon for Items
> 3. Localized Item

Probably we can make do with default icons for now. Maybe 1 icon for new-style settings, 1 for old-style cpanel, 1 for task links?

My script for task links does not include icon either, I haven't found the way to get icon of task links yet. 

About localized, to get the localized task links, I have to change my system's locale to get it, it will pretty laborious to for all language, but I think we could do for 20-30 most popular languages.

**Comment by pc223** [comment]
@taooceros Your current refactor run pretty well on my machine, just need a little fix for namespace the .dll file in plugin.json
<p align="center">
<img src="https://user-images.githubusercontent.com/10551242/126384861-2dca23ba-99d7-48fc-883d-dbdfc7a15f53.gif" width=500 >
</p>

**Comment by taooceros** [comment]
Oh I get your idea about task link. Though, I don't think people will use that in general? Probably make it scoring lower.

**Comment by pc223** [comment]
> Huh? I think it works for me without any change.

I mean this, I have to change this to the new namespace to make it work 😄 

![image](https://user-images.githubusercontent.com/10551242/126430329-57cfb697-f849-4dc5-8ea6-1e9feee28f62.png)

**Comment by taooceros** [comment]
> > Huh? I think it works for me without any change.
> 
> I mean this, I have to change this to the new namespace to make it work 😄 
> 
> ![image](https://user-images.githubusercontent.com/10551242/126430329-57cfb697-f849-4dc5-8ea6-1e9feee28f62.png)
> 

Oh I forget I change the name space 😂

**Comment by pc223** [comment]
> Oh I get your idea about task link. Though, I don't think people will use that in general? Probably make it scoring lower.

Maybe a option for action keyword, to separate old style and new style settings? The task links is fairly popular I think, because many settings still old style, like this request

https://github.com/Flow-Launcher/Flow.Launcher/issues/255

The json for task links can be something like this
https://github.com/pc223/MSWindowsControlPanelTaskLinks/blob/main/2021Jul21T031715-0.0.1-19043.1055-English_United%20Kingdom.json

In this repo is 3 json files for 3 languages and the script to generate them
https://github.com/pc223/MSWindowsControlPanelTaskLinks

**Comment by taooceros** [comment]
Yeah that's true. 
The script looks interesting. Have you checked the json file in WindowsSettings plugin? Probably we can generate something like that, but with different `Type` property, and append it to that. By the way, there're quite a lot duplicate so probably we need to take a check on that as well.

**Comment by pc223** [comment]
> Yeah that's true.
> The script looks interesting. Have you checked the json file in WindowsSettings plugin? Probably we can generate something like that, but with different `Type` property, and append it to that. By the way, there're quite a lot duplicate so probably we need to take a check on that as well.

I think we could check for duplications by compare the command, but should we? The point of task link is actually duplications I think :smile:, like you have more than one way to access a control panel page.

![image](https://user-images.githubusercontent.com/10551242/126496225-74d8d359-7cd7-47f6-a59c-c20863f244fc.png)

**Comment by jjw24** [comment]
PR for this:
https://github.com/Flow-Launcher/Flow.Launcher/pull/741

Transferred from https://github.com/Flow-Launcher/Flow.Plugin.WindowsSettings

Work will continue on the PR rather than the repo which will be archived and deleted.
