### ISSUE TITLE
pm update doesn't work

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#268]
pm update doesn't work

Check the code, seems that it may because Uninstall(pluginmetadata) won't actually uninstall it until next startup, so that the install method cannot do the jobs, but instead the plugin will be uninstalled.

**Comment by taooceros** [comment]
We should change the way of uninstalling plugin or use the way similar to uninstalling to update.

**Comment by jjw24** [comment]
The way it's done with update, is download plugin and appending the folder name with version, then marking the old one for deletion. So when restarted, old is deleted new is loaded.

Is this not the behaviour?

**Comment by taooceros** [comment]
> The way it's done with update, is download plugin and appending the folder name with version, then marking the old one for deletion. So when restarted, old is deleted and new is loaded.
> 
> Is this not the behaviour?

Sorry that works, I have encounted an update fail before so I want to test it, but I forgot to change the folder name but only changes the version number in plugin.json. This leads to the issue. It works, but similar to install method, error handling should be added due to the use of Task.Run.
