### ISSUE TITLE
BUG: No plugins in plugin store

### ISSUE THREAD

**Issue by samve000** [Flow-Launcher/Flow.Launcher#2681]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow launcher doesn't seem to be properly connecting to the plugin store...

### Screenshots

![Flow config](https://github.com/Flow-Launcher/Flow.Launcher/assets/12258003/e3b5b574-e1be-4936-ad7a-ee8b5a2eb9e1)
![nslookup](https://github.com/Flow-Launcher/Flow.Launcher/assets/12258003/d3e1c4e7-f24b-4af8-b430-f34324b27534)
![pm](https://github.com/Flow-Launcher/Flow.Launcher/assets/12258003/58a9876c-63ec-4447-b5bc-3379aadc122d)

### Flow Launcher Version

1.16.2

### Windows Build Number

22631.3527

**Comment by jonesy-b-dev** [comment]
Had the same issue, updating flow launcher fixed it

**Comment by samve000** [comment]
It got fixed by an update.

**Comment by deefrawley** [comment]
Please confirm you have the latest version when raising an issue as per the checkbox you ticked at the top. Thanks
