### ISSUE TITLE
BUG: Sound Effect broken on v1.18

### ISSUE THREAD

**Issue by indigofairyx** [Flow-Launcher/Flow.Launcher#2682]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

theres no longer a sound effect when opening the search box. tired changing the new volume slide. no luck.

### To Reproduce

1. ... open the search box
2. ...
3. ...

### Flow Launcher Version

1.18.0

### Windows Build Number

Microsoft Windows [Version 10.0.19045.4291]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by onesounds** [comment]
Please check if you have deleted Windows Media Player from the system.

**Comment by indigofairyx** [comment]
hmm, yes i have removed WMP, a year ago. and the sound works on v1.17

i tired to leave it but it couldnt handle not being the "default" and keep popping up like a red-head-step-child. sooo oh well i guess?

**Comment by realgooseman** [comment]
I confirm, I deleted WMP years ago and the opening sound effect worked fine till v1.17.
Now, no sound at all even with the setting turned on in `Appearance > Sound effect`

Is it possible to make the sound work without Windows dependencies or at least make it use the system's default player if possible (VLC in my case for example).

**Comment by indigofairyx** [comment]
im not the one to answer this...

 thou. i can say i reverted back to v1.17 and the sound is working as it was, without WMP. so i doubt it that causing the bug. also windows doesn't "remove or uninstall" any features from the "additional features" list, it only hides them, WMP is still in the system, its just not trying to trying to set itself as the default anymore.

**Comment by onesounds** [comment]
@realgooseman @indigofairyx 

We use a framework called WPF, and there are two functions for playing sound. There are two functions: soundplay() and mediaplay(). We used soundplay() until version 1.17, and it didn't have volume control. There was a volume adjustment request pr and we changed the function to mediaplay()(It has a volume control function.) function. But mediaplay relies on WMP to work. this is what happens. 

As @realgooseman said, we can add something to play the sound without any dependencies. But I feel it's unreasonable to put this in just to play "a single sound". Uninstalling WMP is not recommended as it will cause problems for programs other than ours. (Just curious, Why is it so common to uninstall WMP? It is intentionally made inconvenient to delete, and tells you that it may cause problems when deleted.)

We're going to take care of it by putting these warnings in for now.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/6903107/1c55f82c-80b8-4084-b98b-96ffde719e9e)

p.s) While writing this answer, I had an idea. we could just change function to work with soundplay when user don't have WMP (although user won't be able to use volume control)...

**Comment by realgooseman** [comment]
Thanks for clarifying @onesounds,

I like the idea to switch from mediaplay to soundplay if WMP is not detected on the system. One solution that makes everyone happy. Volume control is not a big deal, just leave it at 100% when switching to soundplay.

**Comment by indigofairyx** [comment]
Thanks for the clarification.

As there are many tools to meet an ends in windows. one can override a programs audio volume with something like the system volume mixer or a more robust option https://eartrumpet.app/

As for everyone uninstalling WMP is because.... It sucks.
It never plays anything smoothly or quickly. It's slowed down my windows drm, spyware & telemetry. It's does one of the worst jobs at playing media, out of the 100s of options available. And if it not the default player it's always harassing you to set it as default. 

I've been "turning it off" via the system settings (not uninstalling it) sense the windows 7 days, over a decade, and very, very rarely has it ever caused an issue. This might be first in many years.

**Comment by indigofairyx** [comment]
@onesounds 

> p.s) While writing this answer, I had an idea. we could just change function to work with soundplay when user don't have WMP (although user won't be able to use volume control)...

That's sounds great. It's not a very loud sound effect anyway. Most of the time I almost can't hear it over the clicking of my cherry blue switches mechanical keyboard. 🤣 

Generally I don't like to many sounds from my apps, I change all of windows default notifications sound to softer, more quiet sounds. But I do like the sound effect y'all added to flow so I keep it on. 

**And I love this app! It's better than powertoys and because of it I haven't used windows start menu in months! Doubt I ever will again.** Windows mutilated that back on win8 anyway. 

This is why we use apps other than what windows provides. There are better, quicker, more productive and fun options other than what Microsoft can or will produce. They're in the business of spyware for adds these days, not development. 

Ahh but I'm rambling off top. Lol


In any case **THANK YOU** for you time here and on this app, I love it

**Comment by onesounds** [comment]
@realgooseman @indigofairyx 

Added soundplay() to use if you don't have WMP, with "volume not adjustable" warning. It will play the same way it did in previous versions.

https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/49820434/artifacts

This is test build. Get the portable here, run it, and let me know if it plays sound normally without WMP. (And warning message in setting window) If it works, it will be included in the next release.

**Comment by realgooseman** [comment]
@onesounds 

Tried it, works great and the warning shows up in the settings. Thanks for the update.

> That warning text should also be added to the strings for translation on Crowdin

![Flow Launcher WMP](https://github.com/Flow-Launcher/Flow.Launcher/assets/64812183/f38382f1-8e36-4dee-a6bf-7c083d46644c)

**Comment by indigofairyx** [comment]
yeah! thank you kindly! the sound is working. even with the volume turn down to 0. 

an new but thou. 😆 first time ive noticed this. i just installed two new plugins using this v1.18 and it install and close itself, but then not restart itself as it used to do.

**Comment by onesounds** [comment]
@indigofairyx This is not a production build, so there may be issues with such handling. It is not recommended for mainstream use.
@realgooseman Translations are worked on separately after the merge is complete. It will take a while for it to take effect.

Thank you for testing. We'll apply it after code review.

+) I created this sound feature at first. Because the window is small and its position is not definite, it was difficult to recognize when flow was opened, so I added a sound and an animation to confirm the position. (Both are purely to make it easier for the user to recognize the state and position of the flow).  I'm glad to see this feature is so popular. :)

**Comment by indigofairyx** [comment]
> +) I created this sound feature at first. Because the window is small and its position is not definite, it was difficult to recognize when flow was opened, so I added a sound and an animation to confirm the position. (Both are purely to make it easier for the user to recognize the state and position of the flow). I'm glad to see this feature is so popular. :)

its great! thanks for your hard work. as i said i dont have many sounds going off in my system thou i like this one, very fitting.
