### ISSUE TITLE
BUG: Explorer Plugin - Unable to open custom Files App (third party file explorer)

### ISSUE THREAD

**Issue by ansari2006** [Flow-Launcher/Flow.Launcher#2688]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Hello !

I use Files app as my file explorer and folder editor, and I have entered its path in both Path fields in the plugin settings
Despite this, it doesn't open the folders in the Files app. Afaik Files has already altered my registry to make itself the default file explorer for my system, and other applications like Edge open folder paths in Files by default instead of Windows Explorer.

Despite this, Flow doesn't seem to open folders in Files app and opens a new instance of Windows Explorer every time.

I looked at Files app's support channel and they say I just have to enter the files.exe path in the Path fields in plugin settings, which I already did.
I've tried restarting Flow, I've double-checked that the path is correct. I've even tried restarting windows. Am I doing something wrong? How do I fix this?

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/136502957/e52e0ee1-492e-4eae-a7dc-65ba04477069)
^ Plugin Settings

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/136502957/a10fe205-aaa1-4462-9223-99fde856b4af)
^ Discord Forum Response

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22635.3566

**Comment by ansari2006** [comment]
update: Flow also opens the themes folder in windows explorer rather than my custom files app, even though the registry is edited to always open folders in windows explorer? I have yet to find another program on my device that does this, even task manager opens directories in Files app.

**Comment by Yusyuriv** [comment]
Hello! Could you please open Settings — General — Default File Manager, change it there, and see if that helps?

**Comment by ansari2006** [comment]
I'm a moron! Thanks, it worked 😭
