### ISSUE TITLE
Set default fallback option when pressing key combinations on result.

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [Flow-Launcher/Flow.Launcher#2691]
**Is your feature request related to a problem? Please describe.**

This feature is already in Alfred, basically there is a set of actions you can perform on the current typed input. This can be Ctrl/Alt/option + enter or any of the combinations. Each one can do something different. That might be too complicated for this ask, but my main pain point (and the reason for requesting this) is mainly for an Alt+Enter option. I want Alt+enter to _**always**_ open that result searching google.

For example:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/42372270/2c36a30d-6eeb-478a-a785-0d056befc517)
I realize I can hit alt+2, and this is because my list only has these options. But if this list is more populated it could be Alt+3 or Alt+4 which would take a second for me to have to spend the time to read the text and then perform that key combination. 

The solution I propose is to have an option somewhere in the settings to choose which key a "fallback" option should be, and then within the web search plugin, have this checkbox:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/42372270/8c5421f5-f370-47cb-a6b2-2242cad5925a)

**Comment by onesounds** [comment]
- Behavior is not intuitive. 
- What if a feature other than the webplugin wants to use this setting? 
- What happens when I press ALT ENTER if there are no web search results in the searched results?

This is too complicated. Can you point me to another program that does something similar?

In your use case, we understand that the user tried to do a full search, not a "web search". But the selection is an action to select only "specific actions" (i.e., we're a restaurant and you're a customer. We have two bells: "multi-course meal" and "single dish". You ring "multi-course" to call us, and then you are asking me if there's a way to order a "single dish". I would say ring the "single dish" bell).

I'm sure alfred has a reason for implementing that feature, and I can see that it's some kind of convenience feature that I don't understand. But it's just too much work for too little utility. I want the user to just trigger a web search if they want to do it, and if they're in the middle of a multi-search and need to do a web search, I want them to manually select it. Pressing a shortcut to make it faster is not a very common UX practice.

**Comment by j-a-s-o-n-g** [comment]
I logged into my Mac to take these screenshots from AlfredThis shows the configuration for these actions, much like when you press the right arrow currently.These are the options for each drop-down.To answer your question, what if a a plug-in wants to use this functionality.. that’s probably too complex to add. The options for Alfred are located in the main application configuration so I don’t believe third party plugins have access to this either. It seems like these are the most common actions that can be taken. Shortcuts to functionality that already exists.To answer about no text, it would behave like pressing the right arrow on an empty query, nothing.An alternate solution in my case would be to duplicated the asterisk web search for google and prefix it with an access letter (like g), but it’s inconvenient to have to remember to write “g blah blah” instead of writing “blah blah” and hitting alt+enter to instantly open a web search. On May 6, 2024, at 9:58 PM, DB P ***@***.***> wrote:﻿

Behavior is not intuitive.
What if a feature other than the webplugin wants to use this setting?
What happens when I press ALT ENTER if there are no web search results in the searched results?

This is too complicated. Can you point me to another program that does something similar?
In your use case, we understand that the user tried to do a full search, not a "web search". But the selection is an action to select only "specific actions" (i.e., we're a restaurant and you're a customer. We have two bells: "multi-course meal" and "single dish". You ring "multi-course" to call us, and then you are asking me if there's a way to order a "single dish". I would say ring the "single dish" bell).
I'm sure alfred has a reason for implementing that feature, and I can see that it's some kind of convenience feature that I don't understand. But it's just too much work for too little utility. I want the user to just trigger a web search if they want to do it, and if they're in the middle of a multi-search and need to do a web search, I want them to manually select it. Pressing a shortcut to make it faster is not a very common UX practice.

**Comment by j-a-s-o-n-g** [comment]
I’ll fix my response later, GitHub butchered my email and screenshots

**Comment by j-a-s-o-n-g** [comment]
I logged into my Mac to take these screenshots from Alfred:

<img width="432" alt="image" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/42372270/9de119a8-7363-435e-b9e8-9ac75c403b0d">
This shows the configuration for these actions, much like when you press the right arrow currently.

These are the options for each drop-down.
<img width="266" alt="image" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/42372270/8c9d52fe-37a2-42c5-afe4-45cf071c68a2">

To answer your question, what if a a plug-in wants to use this functionality.. that’s probably too complex to add. The options for Alfred are located in the main application configuration so I don’t believe third party plugins have access to this either. It seems like these are the most common actions that can be taken. Shortcuts to functionality that already exists.

To answer about no text, it would behave like pressing the right arrow on an empty query, nothing.

An alternate solution in my case would be to duplicated the asterisk web search for google and prefix it with an access letter (like g), but it’s inconvenient to have to remember to write “g blah blah” instead of writing “blah blah” and hitting alt+enter to instantly open a web search.
