### ISSUE TITLE
BUG: Launched programs have old environment variables

### ISSUE THREAD

**Issue by nref** [Flow-Launcher/Flow.Launcher#2694]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Programs launched with Flow have the environment variables that were set when Flow started.

### To Reproduce

I was debugging in Visual Studio 2022. My program loads a configuration value from an envrionment variable. When I change the variable and re-launch VS with Flow, the new instance of VS has the old env vars. If I re-launch VS from the Start Menu, it has the new env vars.

### Flow Launcher Version

1.18.0

### Windows Build Number

Microsoft Windows [Version 10.0.22631.3527]

**Comment by nref** [comment]
Thanks for a nice launcher.

**Comment by deefrawley** [comment]
Not a fix, but you can hit F5 to refresh Flow when you know an environment variable has changed.

**Comment by nref** [comment]
Thanks mate. I didn't know about that. I'm totally willing to hit F5.

**Comment by jjw24** [comment]
Just closing this one as it is a dup of #1602 and please track any progress or updates over in that issue.
