### ISSUE TITLE
Non-rounded (rectangle) search bar corners

### ISSUE THREAD

**Issue by monandszy** [Flow-Launcher/Flow.Launcher#2698]
Is this possible with a theme?

**Comment by onesounds** [comment]
It is described in the theme document. You can find the theme file, open it as an editor, and modify it. You can change the value of the window attribute with cornerradius to zero. It's hard to explain in detail because I'm on mobile.

**Comment by VictoriousRaptor** [comment]
The Win10 Theme shipped with Flow has rectangular corners. If you want to customize one you can refer to our doc.
