### ISSUE TITLE
Difficulty accessing plugin settings programmatically with Python

### ISSUE THREAD

**Issue by Attack825** [Flow-Launcher/Flow.Launcher#2705]
Description:
I am facing challenges in retrieving the settings of my plugin using Python code. I need to programmatically access and retrieve the user-defined settings values within my Python script, but I am unsure about the appropriate method or API to accomplish this.
I have reviewed the plugin documentation and explored the available code files, but I haven't found clear instructions on how to fetch the plugin settings using Python. Could you please provide guidance on how to access and retrieve the plugin settings programmatically using Python?

**Comment by jjw24** [comment]
Hi there, what you are after is the JSON RPC settings page:
https://www.flowlauncher.com/docs/#/json-rpc-settings?id=plugin-settings

You can also create with a visual editor.
https://www.flowlauncher.com/docs/#/json-rpc-visual-settingstemplate-editor?id=settingstemplateyaml-editor

Hope this helps, let us know if you are still stuck.

**Comment by Attack825** [comment]
I wanted to extend my heartfelt thanks for your invaluable guidance. the pyflowlauncher library, was immensely helpful in completing my plugin.
