### ISSUE TITLE
BUG: Translation. FL Portable v1.18.0.8643

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#2729]
In Flow Launcher Portable Settings (v1.18.0.8643 / May 27, 2024), except in the Add-ons and Appearance pages, the On/Off options are not translated into Spanish.

![240527 FL Portable v1 18 0 8643_ON-OFF_NOT OK](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/6fda23d8-7a41-464d-9d79-7beb30b4f19d)

![240527 FL Portable v1 18 0 8643_ON-OFF_OK](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/9ed070f9-9e70-4533-9c96-af3799baa74f)

**Comment by onesounds** [comment]
Long time no see. We have fixed this problem, and I will work on the combo boxes that have been delayed soon.

**Comment by dracp** [comment]
Fixed in 240605 Flow-Launcher-Portable v1.18.0.8771. Thanks
