### ISSUE TITLE
Better magnifying glass icon on query window

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#273]
Can do with a better magnifying glass icon, current one is too fuzzy/not a hd image

current:
![image](https://user-images.githubusercontent.com/26427004/103581852-e9889900-4f30-11eb-8b40-801714d041ab.png)

**Comment by taooceros** [comment]
Have you opened the window shadow effect? I think the fuzzy is led by that for this case.
Currently I believe we only load thumbnail of both images and file. We should load the image inside our image folder as image.
