### ISSUE TITLE
BUG: Open “uri schemes” no longer showing up as an option

### ISSUE THREAD

**Issue by checkbert** [Flow-Launcher/Flow.Launcher#2734]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Since a few days, I cannot open a uri scheme prompt anymore. 

I use flow launcher to run system wide uri schemes, for example:

- Microsoft-edge:address
- Dynamicsnav:address 

Last time it worked, Flow launcher showed an option to simply run/open the prompt, or search with a browser. 

Now, it shows only the option to search the prompt within a browser (creates a search within chrome). 

This is the same function, as windows execute (Windows + R, then enter uri scheme prompt).

I don’t know, if this is a bug or if a plugin is changed and I now have to change the plugins settings. 

Thanks in advance for taking a look into this issue. 

### To Reproduce

1. paste in an uri-scheme, for example: `Microsoft-edge:https://www.github.com/flow-launcher`

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22631.3593

**Comment by taooceros** [comment]
Maybe you need to change the shell plugin to `RunCommand`
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/45326534/6dbcaa8c-5add-4ad3-84ca-15e3ce67a504)

**Comment by checkbert** [comment]
@taooceros  Thanks for the suggestion. The issue can be closed, since it has been resolved a few days ago without changing anything at all. 

The reported misbehavior no longer exists.
