### ISSUE TITLE
Hotkey settings semi-working

### ISSUE THREAD

**Issue by sercankd** [Flow-Launcher/Flow.Launcher#277]
**Describe the bug/issue**
Hotkeys are not working as intended, this is an issue even in Wox Launcher

**To Reproduce**
In the settings i set my hotkeys to ALT+R, it works fine but also it works by pressing Winkey+R which is something i dont want to.

**Screenshots**
![image](https://user-images.githubusercontent.com/1024476/103659909-08614c80-4f7e-11eb-8ba2-3df7cfa4583c.png)

**Your System**
```
Microsoft Windows [Version 10.0.17763.1518]
Flow Launcher version: 1.6.0
```
**Flow Launcher Error Log**
Log file is not available in both
%AppData%\FlowLauncher\
and 
%LocalAppData%\FlowLauncher\

These both folders are not even exist.

**Comment by jjw24** [comment]
Would it be you have the setting in She'll plugin set to open with Win + R ticked?

**Comment by sercankd** [comment]
Yes, that seems the issue, i didn't see it there. Thank you very much.
