### ISSUE TITLE
BUG: Translation. FL Portable v1.18.0.8864

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#2781]
In **Settings/Appearance/Fixed Window Height**, the text (On/Off) next to the switch is not translated. The rest of the text next to the switches on all pages of the Settings are correctly translated (Activado/Desactivado).

As a test we have replaced the "es.xaml" file in FL_v1.18.0.8864 (…FlowLauncher\app-1.18.0\Languages\es.xaml) with the "es.xaml" file downloaded directly from Crowdin (green box). The Spanish translation is completely finished.

![240614 FL_v1 18 0 8864 _Activado_Desactivado_NO traducido](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/1b7392f5-bb62-4107-9dbb-aadf640dee09)

**Comment by taooceros** [comment]
I think this should be fixed by some recent merge of Crowdin PRs?

**Comment by dracp** [comment]
> I think this should be fixed by some recent merge of Crowdin PRs?

**FL 1.19.1.9199. Not translated / Crowdin: Spanish 100% Translated**

![240922 FL 1 19 1 9199_Sin traducir](https://github.com/user-attachments/assets/60994a36-c131-4edc-a0b4-e372835369c7)

![240922 FL 1 19 1 9199_Crowdin_100x100 traducido](https://github.com/user-attachments/assets/2ea98f8b-6f77-46ca-88e9-fcac19f143f7)
