### ISSUE TITLE
BUG: Flow Launcher not invoking / opening Tab in QTTabBar in Windows 10

### ISSUE THREAD

**Issue by gauthambhat025** [Flow-Launcher/Flow.Launcher#2790]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I am using windows 10. I use QTTabbar to capture any new opening of windows explorer which very conveniently sets all my tabs in one single window. But when I invoke a folder from flow launcher, it opens in another window altogether. How to make it so that the invoked folder opens as a tab in the already opened window?

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.19045.3758

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
I think you can try to add a custom file manager for qttabbar? I don't know how exactly it needs to make it works.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/45326534/3e591d1c-4f51-4caa-a6de-6b9251271b33)

**Comment by JoyHak** [comment]
I'm currently trying to figure out how to open folders in the current explorer window in a new tab. As I understand it, I need to use some window call cmd command, which qttabbar will intercept

**Comment by gauthambhat025** [comment]
> I'm currently trying to figure out how to open folders in the current explorer window in a new tab. As I understand it, I need to use some window call cmd command, which qttabbar will intercept

Thanks for the reply, any tentative ETA?.
This bug is the only thing holding me back using flow launcher.

**Comment by onesounds** [comment]
I've confirmed that it works in wox (if we open the path with process.start(path), we can open a tab). I didn't expect it to behave this way, so we're discussing a workaround.

**Comment by JoyHak** [comment]
> I've confirmed that it works in wox (if we open the path with process.start(path), we can open a tab). I didn't expect it to behave this way, so we're discussing a workaround.

If Flow Launcher opens a new tab in Files or another file manager, I'll just change file manager

**Comment by VictoriousRaptor** [comment]
```autohotkey
#Requires AutoHotkey v2.0
args := A_Args.Length == 1? A_Args[1] : A_Args[1] . " " . A_Args[2]

if (ErrorCode := ShellExecute(args)) <= 32
    MsgBox ErrorCode

ShellExecute(strArgs:="", nShowCmd:=1) {
    ; MsgBox strArgs
    ;http://msdn.microsoft.com/en-us/library/windows/desktop/bb762153%28v=vs.85%29.aspx
    Return DllCall("shell32\ShellExecuteW"
    , "uint", 0
    , "uint", 0
    , "str", "explorer.exe"
    , "str", strArgs  ; arguments
    , "str", "" ; lpfile
    , "int", nShowCmd    ; specifies how an application is to be displayed when it is opened
    , "uint" )
}
```

An ahk script as a workaround. Set it as default file manager in flow (args are the same as explorer) and it can work.

**Comment by onesounds** [comment]
@gauthambhat025  @JoyHak

https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/50086900/artifacts
The information that it works with WOX was helpful. After you get the portable version from the link above, select the qttabbar item and let us know if it works as you want.

<img src="https://github.com/Flow-Launcher/Flow.Launcher/assets/6903107/dc716f2e-97d4-4678-adf8-08be32f21e47" width="300">

If you don't have an entry for "QTTABBAR"(case insensitive), add one and select. Only the name entry needs to be correct.
<img src="https://github.com/Flow-Launcher/Flow.Launcher/assets/6903107/aabc974d-d985-401a-8c3b-1520a1fa252b" width="400">

**Comment by gauthambhat025** [comment]
> @gauthambhat025 @JoyHak
> 
> https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/50086900/artifacts The information that it works with WOX was helpful. After you get the portable version from the link above, select the qttabbar item and let us know if it works as you want.
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/6903107/342631815-dc716f2e-97d4-4678-adf8-08be32f21e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI0NDAsIm5iZiI6MTcxOTMwMjE0MCwicGF0aCI6Ii82OTAzMTA3LzM0MjYzMTgxNS1kYzcxNmYyZS05N2Q0LTQ2NzgtYWRmOC0wOGJlMzJmMjFlNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDc1NTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQxZGNhNTAzODNmZjg4ZmM2Njc5ZWNjNzI2NTQ3MzNhYjJmMjY4OGI1ZTAyOWZhOTM3OGI4NDVjMDA5YTllNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SfKu2whYRS2d4TgumiHqOWQpfAzc8euDNKF6xUFCT6w">
> If you don't have an entry for "QTTABBAR"(case insensitive), add one and select. Only the name entry needs to be correct. <img alt="" width="400" src="https://private-user-images.githubusercontent.com/6903107/342631958-aabc974d-d985-401a-8c3b-1520a1fa252b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDI0NDAsIm5iZiI6MTcxOTMwMjE0MCwicGF0aCI6Ii82OTAzMTA3LzM0MjYzMTk1OC1hYWJjOTc0ZC1kOTg1LTQwMWEtOGMzYi0xNTIwYTFmYTI1MmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDc1NTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDBjODA5OGNkNjljNzMwMDkzYjdkZGM1NTljY2IwNWEwNjgyYzIzMDUyZTU0MTMzYjE1MjZhNGJlZjQ4ZWE2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KXcsMOdQQLLm3D6tHHRTwFLGS4ASPWriosDYlKa4rqU">

I can confirm this works

**Comment by onesounds** [comment]
> I can confirm this works

It will be in the next release, but it will take a while to get there.

**Comment by JoyHak** [comment]
I can confirm this works, thank you ^^
