### ISSUE TITLE
BUG: Native Context Menu. FL v1.18.0.8920

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#2794]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When options are included in the native context menu, the browser option sheet does not display any native context menu options.

However, when options are excluded from the native context menu, the browser option sheet correctly displays the native context menu options, properly excluding those indicated in the corresponding box of the Configuration.

### To Reproduce

1.- Access the Native Context Menu (Settings>Plugins>Explorer>Native Context Menu).
2.- Check the Display native context menu (experimental).
3.- Enter in the right box options to exclude from Native Context Menu
4.- Check in the Options sheet for a given search result > Correct result.
5.- Enter in left box options to be included in Native Context Menu 
6.- Check in the Options sheet for a given search result > Incorrect result

### Screenshots

![240619 FL v1 18 0 8920_BUG_Menú contextual nativo_01](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/fd3d9075-22fb-4a62-bcb7-a97780798504)
![240619 FL v1 18 0 8920_BUG_Menú contextual nativo_02](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/baefda0f-344b-4c90-a98d-c5582bb509d7)

![240619 FL v1 18 0 8920_BUG_Menú contextual nativo_03](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/75a0a922-7c37-40df-9b30-2a01d574946a)
![240619 FL v1 18 0 8920_BUG_Menú contextual nativo_04](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/9789ef73-eab7-4be1-af58-5179d40f0f08)

### Flow Launcher Version

1.18.0.8920

### Windows Build Number

W11 Pro 23H2 22631.3737

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Yusyuriv** [comment]
Okay, the labels above those text fields are a little unclear.

If you only want to see some items and nothing else, you specify them in the left field. For example, here's what I get after specifying a few lines in that field:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/ff7c3686-5dd4-4ae0-b1f3-d5e41da444a4)

Let's say I also don't want to see anything with the word "shortcut" (I only want the `Cut` item to be able to cut files). This is where the second text field comes in. It allows you to specify items you _don't_ want to see. If I write "shortcut" there, `Send to > Desktop (create shorcut)` and `Create shortcut` will not be displayed.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/5aa27f1e-8dc7-4a75-88a2-61736e066765)

**Comment by dracp** [comment]
> Okay, the labels above those text fields are a little unclear.
> 
> If you only want to see some items and nothing else, you specify them in the left field. For example, here's what I get after specifying a few lines in that field: ![image](https://private-user-images.githubusercontent.com/3993179/341218425-ff7c3686-5dd4-4ae0-b1f3-d5e41da444a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Nzk1NDAsIm5iZiI6MTcxODg3OTI0MCwicGF0aCI6Ii8zOTkzMTc5LzM0MTIxODQyNS1mZjdjMzY4Ni01ZGQ0LTRhZTAtYjFmMy1kNWU0MWRhNDQ0YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTAyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQyZDAwZjZhMzg5YTA3MzQ0NzdlYjYxZTEwNGM4ZWI2MDAxOTI2M2U4OWFhMDQ5ZThiOTMwNDg1OGI2MGRkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qJl9WsqGogE5IZ-obpkYCtGJL-rt85q9JSxRxOIqUIc)
> 
> Let's say I also don't want to see anything with the word "shortcut" (I only want the `Cut` item to be able to cut files). This is where the second text field comes in. It allows you to specify items you _don't_ want to see. If I write "shortcut" there, `Send to > Desktop (create shorcut)` and `Create shortcut` will not be displayed. ![image](https://private-user-images.githubusercontent.com/3993179/341218865-5aa27f1e-8dc7-4a75-88a2-61736e066765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Nzk1NDAsIm5iZiI6MTcxODg3OTI0MCwicGF0aCI6Ii8zOTkzMTc5LzM0MTIxODg2NS01YWEyN2YxZS04ZGM3LTRhNzUtODhhMi02MTczNmUwNjY3NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTAyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ4ZTQwZjUwYzY2MmY1ODc2MzViYjFmNDkwZDljNzdmODVkNThiMmFmMGQ5ZTNmMTNkODcxN2Q0N2UzNDRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dJWl1U5DGiVlqGW58lJ37jE08wwJPVw6V8WGMlxZiQk)

**Comment by dracp** [comment]
Yes, yes, I understand how this option works. But I insist that to me when I include an option in the left box, FlowLauncher stops showing "all" context menu options in the Search option sheet.

**Comment by Yusyuriv** [comment]
Can you show a screenshot of the native context menu with the right text field unchanged and with the left text field containing this?
```
Cortar
Propiedades
```

**Comment by dracp** [comment]
I am trying, but the moment I press PrintScreen the context menu disappears in W11. I'm sorry.

**Comment by Yusyuriv** [comment]
No, I meant the one integrated into Flow Launcher.

**Comment by dracp** [comment]
I don't know if I understood you correctly. Attached W11 and FL context menu.

![240620 FL v1 18 0 8920_Menú contextual W11](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/594a0b7a-8646-458f-9fc0-0d612b22da0a)
![240620 FL v1 18 0 8920_Menú contextual FL_001](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/b43eed5a-289d-4c8b-bef9-633d77f4704f)
![240620 FL v1 18 0 8920_Menú contextual FL_002](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/725964dc-0a12-47ff-b16b-ae1a6110da7c)
![240620 FL v1 18 0 8920_Menú contextual FL_003](https://github.com/Flow-Launcher/Flow.Launcher/assets/102802425/7d6c18e7-5f1c-4314-b2c1-03bf0ca4b3ec)
