### ISSUE TITLE
BUG: the search terms are not highlighted

### ISSUE THREAD

**Issue by ligq** [Flow-Launcher/Flow.Launcher#2809]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The search terms are not highlighted. If I am correct, the search terms used to be highlighted, that was easier to find the target. Is this a bug or my settings are not right?

### Flow Launcher Version

1.18.0 

### Windows Build Number

11.0.26100.1000

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by onesounds** [comment]
what's your version and theme?

**Comment by ligq** [comment]
The theme is the Win11.
I didn't know I could define the highlighted color in the theme. Now I have edited the .yaml file and it works well.
Thank you.
