### ISSUE TITLE
BUG: WebSearch Plugin does not work

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2818]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

If I use any defined websearch keywords, nothing happens. No Suggestions, no action by pressing Enter.

The plugin is enabled and the search keyword is defined as in the plugin's description

### To Reproduce

Just try to use the plugin 😄

### Screenshots

https://github.com/Flow-Launcher/Flow.Launcher/assets/29770761/46521048-453e-4d0f-814e-50a10f8946dc

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/29770761/91f09cf7-193e-49e4-8c2c-fdf67e3f6107)

### Flow Launcher Version

1.18.0

### Windows Build Number

latest win11

**Comment by DRYN07** [comment]
Browser path is set and working with other plugins like "URL".

**Comment by deefrawley** [comment]
In the screen video, what do you press after typing 'g'? Is it just a space then you start typing the search term?

**Comment by DRYN07** [comment]
I tried 3 methods:
- space
- tab
- enter, when the "Search with Google" appears

**Comment by jjw24** [comment]
In the video It looks like the behaviour of typing 'g' then tab, autocompleting to 'Search Google'. What do you get when you just type `g Starbucks`? Can you show a screenshot please.

**Comment by DRYN07** [comment]
I reinstalled the whole stuff and now the searches are working. Honestly, I don't know what was the issue.
