### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SuperNoob230** [Flow-Launcher/Flow.Launcher#2824]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

No results found in Plugin Store

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/174971627/9483246e-8f8b-468f-8a8b-d80a0b7f719a)

### Flow Launcher Version

1.18.0

### Windows Build Number

Microsoft Windows [Version 10.0.22631.3737]

### Error Log

15:48:33.1654-07:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
15:48:33.1654-07:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.18.0
OS Version: 22631.3737
IntPtr Length: 8
x64: True
15:48:34.7170-07:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
15:48:35.8712-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <14ms>
15:48:35.8712-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <12ms>
15:48:35.8712-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <13ms>
15:48:35.9249-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <70ms>
15:48:36.7868-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <936ms>
15:48:36.7868-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <982ms>
15:48:36.8200-07:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
15:48:36.8213-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:48:37.3437-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <1532ms>
15:48:37.3437-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <1492ms>
15:48:37.8022-07:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
15:48:37.8086-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <1957ms>
15:48:37.8086-07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <1022ms>
15:48:37.8086-07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <0>
15:48:37.8086-07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <0>
15:48:37.8086-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <1970ms>
15:48:37.8355-07:00 - INFO  - ImageLoader.Initialize - Preload images cost <2ms>
15:48:37.8490-07:00 - INFO  - ImageLoader.Initialize - Number of preload images is <2>, Images Number: 2, Unique Items 2
15:48:37.9446-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:48:37.9446-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:48:37.9446-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
15:48:38.0012-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <2148ms>
15:48:43.3550-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:43.3550-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
15:48:43.3550-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:43.4655-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:43.4655-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
15:48:43.4655-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.5141-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 0 plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:48:45.5141-07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <9671ms>
15:48:45.5525-07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Win32Program index cost <7738ms>
15:48:45.8642-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloud can't find logo uri for iCloud\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8642-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloud can't find logo uri for iCloud\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8642-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloud can't find logo uri for iCloud\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8642-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloud can't find logo uri for iCloud\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8642-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8642-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPhotoViewer can't find logo uri for Photos\Square44x44Logo.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8642-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPhotoViewer can't find logo uri for Photos\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPhotoViewer can't find logo uri for Photos\Square44x44Logo.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPhotoViewer can't find logo uri for Photos\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPasswords can't find logo uri for PwdMgrUI\Square44x44Logo.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPasswords can't find logo uri for PwdMgrUI\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPasswords can't find logo uri for PwdMgrUI\Square44x44Logo.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:48:45.8693-07:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: AppleInc.iCloud_nzyj5cx40ttqa!iCloudPasswords can't find logo uri for PwdMgrUI\Square44x44Logo.png in package location (can't find specified logo): C:\Program Files\WindowsApps\AppleInc.iCloud_15.0.215.0_x64__nzyj5cx40ttqa
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
15:48:45.8693-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:48:46.5547-07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - UWPProgram index cost <8741ms>
15:48:46.6434-07:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
15:48:49.5751-07:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
15:48:49.5751-07:00 - INFO  - App.OnStartup - Startup cost <16936ms>
15:51:15.4178-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:51:15.4178-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:51:15.4178-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:51:15.4178-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
15:51:15.9333-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 0 plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:54:34.1331-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:54:34.1331-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:54:34.1331-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:54:34.1331-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
15:54:34.2413-07:00 - INFO  - CommunityPluginSource.FetchAsync - Resource https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json has not been modified.
15:56:17.4819-07:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "0F4C15147CCE5AD43CBE27120B61230BB834A32E",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.18.0-full.nupkg",
  "Query": null,
  "Filesize": 105458488,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "0F4C15147CCE5AD43CBE27120B61230BB834A32E FlowLauncher-1.18.0-full.nupkg 105458488",
  "Version": {
    "Version": "1.18.0.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
15:57:45.5263-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:57:45.5263-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:57:45.5263-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
15:57:45.5263-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
15:57:45.6120-07:00 - INFO  - CommunityPluginSource.FetchAsync - Resource https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json has not been modified.
16:10:43.7503-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
16:10:43.7503-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
16:10:43.7503-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
16:10:43.7503-07:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
16:10:43.8957-07:00 - INFO  - CommunityPluginSource.FetchAsync - Resource https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json has not been modified.
16:16:54.5563-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:16:54.5563-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:16:54.5563-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
16:16:54.6239-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:16:54.6239-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:16:54.6239-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
16:17:01.9246-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:17:01.9246-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:17:01.9246-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
16:17:02.0064-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:17:02.0064-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:17:02.0064-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
16:17:06.2601-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:17:06.2601-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:17:06.2601-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
16:17:06.3314-07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
16:17:06.3314-07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
16:17:06.3314-07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------

**Comment by jjw24** [comment]
Hey there what's the actual issue? Was it no plugins loaded in the Plugin Store?

**Comment by TSenter** [comment]
> Hey there what's the actual issue? Was it no plugins loaded in the Plugin Store?

Not OP but I found this issue when I had the same problem. I can't confirm, but it looks like this happens if Flow starts without Internet. I tried searching for a plugin, hitting the button and `Enter` and never got any results. After restarting Flow (and after I got on Internet), I got results and was able to search.

**Comment by jjw24** [comment]
> > Hey there what's the actual issue? Was it no plugins loaded in the Plugin Store?
> 
> Not OP but I found this issue when I had the same problem. I can't confirm, but it looks like this happens if Flow starts without Internet. I tried searching for a plugin, hitting the button and `Enter` and never got any results. After restarting Flow (and after I got on Internet), I got results and was able to search.

Hmm, plugins should show up once you reconnect to internet, at least when the refresh button is clicked. Let's file a separate issue if this is not the case.
