### ISSUE TITLE
BUG: Results windows sometimes too small and not adjusting

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2825]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Results windows sometimes too small and not adjusting.

### To Reproduce

I was playing with fend calculator and some results are too long for flow launcher's results window.

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/29770761/6936afa5-9b11-4bc6-b6e0-1834cf16003a)

### Flow Launcher Version

latest

### Windows Build Number

22631.3737

**Comment by z1nc0r3** [comment]
Hi, I don't know whether we can call this a bug since this is how the result window is implemented. Most plugins do not produce this much long results.

However, I think you can always view the result as a popup on mouse hover if that helps.
