### ISSUE TITLE
option to add separator (or space) between plugins

### ISSUE THREAD

**Issue by Alexnoj** [Flow-Launcher/Flow.Launcher#2833]
Option add separator between plugins. like after Program plugin.

![image](https://github.com/user-attachments/assets/32e16aff-bb8c-4684-9f8b-8b6e33652076)

**Comment by jjw24** [comment]
Is the idea actually for easily identify which result belows to what plugin?

**Comment by Alexnoj** [comment]
The separator can be after the first result.

**Comment by jjw24** [comment]
OK, what's the reason for having a separator after the first result though?

**Comment by DrAnonym666** [comment]
> Option add separator between plugins. like after Program plugin.
> 
> ![image](https://private-user-images.githubusercontent.com/30004592/348169617-32e16aff-bb8c-4684-9f8b-8b6e33652076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTQ4NDksIm5iZiI6MTcyMTM5NDU0OSwicGF0aCI6Ii8zMDAwNDU5Mi8zNDgxNjk2MTctMzJlMTZhZmYtYmI4Yy00Njg0LTlmOGItOGI2ZTMzNjUyMDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEzMDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDMzMTlmZWI4ZTg5ZDE2NjVkMmY4ODE4ZTdlYTIzMjRjYWQ0ZDc4MjgzZTE1ZmY5MGVhMzk2NmM0OTRjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nD9gheM_5sxZ3FGVXiDaO3r8oLj4dbUQferGiSJkCmI)

good idea :)
