### ISSUE TITLE
BUG: case sensitive on breakers plugins

### ISSUE THREAD

**Issue by indigofairyx** [Flow-Launcher/Flow.Launcher#2846]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Use CAPS on on plugin commands breakers plugins from functioning.

Eg, "url github.com"  works. While "URL github.com" wont. 

Same for my web plugins, I use "goo" to search Google, if I use "GOO", in caps, it won't send to the browser.

This seems to effect eternal plugins too. 

Just saw this post from a 3rd party plugin https://github.com/Garulf/Steam-Search/issues/65

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.18. Pre release 

### Windows Build Number

10. Current 

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
This is not a bug but a feature. Keywords are supposed to be case sensitive. That way users have more options to create keywords.

**Comment by onesounds** [comment]
> This is not a bug but a feature. Keywords are supposed to be case sensitive. That way users have more options to create keywords.

 No. This hinders fast input because it makes the user distinguish case. We are right not to distinguish this.  At least it should be provided as an option.

**Comment by deefrawley** [comment]
Then let's change it to an enhancement not a bug.

**Comment by stefanroelofs** [comment]
I agree that a new option: 'Enable case insensitive keywords' would be a very nice to have. 

It is possible for a plugin to register multiple keywords, but this is not ideal.
For this change the following line in the plugin.json file:

`"ActionKeywords": ["pro", "Pro", "PRO"],`
