### ISSUE TITLE
Everything filters

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2849]
Should these work in Explorer plugin if Everything is enabled?

https://www.voidtools.com/support/everything/searching/

**Comment by deefrawley** [comment]
No not with the current Everything API. The next version from Voidtools should enable access to these and they can then be included in Flow. You can use custom shortcuts to achieve the same thing. I've posted a few answers showing how if you search the issues (I'm on my phone so can't find easily)

**Comment by DRYN07** [comment]
It's okay, thanks for the answer. I will search for those :)

**Comment by deefrawley** [comment]
Custom Query Shortcuts

![image](https://github.com/user-attachments/assets/5c467a2c-cfab-4269-9f9f-d73c2eb692ac)

Use the at symbol to invoke

![image](https://github.com/user-attachments/assets/9f4fb38d-455e-4da2-ae22-8873a6005c19)

**Comment by DRYN07** [comment]
What I wanted to achieve is to specify a folder I want to search in. In everything it is "\folder searchterm". Can I do this here somehow?

**Comment by deefrawley** [comment]
Yeah use `folder:` before your search term

**Comment by DRYN07** [comment]
Is it worth (or possible) to use Everything 1.5a?
