### ISSUE TITLE
Trim in publishing

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#285]
**Question**
Why don't we trim in publishing profile? In dotnet 5 environment, although it takes time to do the job, it can reduce the output size from 92MB to about 58MB

@JohnTheGr8 @jjw24

**Comment by jjw24** [comment]
That would be good to trim down the size, I just haven't had time to look into it

**Comment by JohnTheGr8** [comment]
Trimming is still experimental afaik.

Also, curiously, self-contained `net5.0-windows` output is actually larger than the `netcoreapp3.1` equivalent: 84mb vs 78mb for the executable...

**Comment by taooceros** [comment]
> Trimming is still experimental afaik.
> 
> Also, curiously, self-contained `net5.0-windows` output is actually larger than the `netcoreapp3.1` equivalent: 84mb vs 78mb for the executable...

Maybe that is because of the large WinRT runtime. Around 26mb.

**Comment by taooceros** [comment]
hmmm seems that trimming break Flow to work as intended. Need more testing.

**Comment by jjw24** [comment]
A couple more suggestions to try:
https://ianqvist.blogspot.com/2018/01/reducing-size-of-self-contained-net.html

https://medium.com/@singhsukhpinder/how-to-reduce-net-core-app-size-90045757cd99

https://stackoverflow.com/questions/48009976/optimizing-net-core-self-contained-deployment
