### ISSUE TITLE
BUG: Explorer does not find files and folders

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2856]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I don't think it's a bug, rather some settings issue.

My main problem is that it does not find specific index-ed files or folders (google drive for desktop folder).

In this picture you can see that:
- the folder is added to everything's Index options
- in the explorer the "Karrier.psd" is selected
- FL can not find it

![image](https://github.com/user-attachments/assets/7fffe7e8-f841-4f3b-af1b-e18f7f6c738e)

In this picture you can see that I am searching for "x_EGYEB" folder, which you can see in the results folder path, but the folder itself not showing. So the SYNC folder is indexed and FL can can see those, but it does not show what I was searching for.

![image](https://github.com/user-attachments/assets/7e66a3e7-e848-4ef3-8c6a-46e12e8977b8)

If I search for anything from "Quick Access Links", then it works
![image](https://github.com/user-attachments/assets/0e4d2477-b209-4f65-9376-47e177e9861a)

I don't really know what is happening... Any help would be appreciated.

Some other setting you should know:
![image](https://github.com/user-attachments/assets/79a1f5d6-11a9-40a3-90b6-cc034897fb65)

![image](https://github.com/user-attachments/assets/1279bdbf-5e75-4019-8d4e-73edbbbd4b4a)

### Flow Launcher Version

Latest

### Windows Build Number

Latest

### Error Log

[2024-07-22.txt](https://github.com/user-attachments/files/16331251/2024-07-22.txt)

**Comment by DRYN07** [comment]
Another weird thing:

I use Flow Launcher Portable in a synced folder and on the other computer it works fine... Theoretically the files must be identical.

**Comment by jjw24** [comment]
That is certainly strange. I thought searching for x_EGYEB folder would bring up that other result due to path matching as I can see that result path has the same name, but in your settings the 'Search Full Path' option is off. So not sure at this stage.

1. What version of Everything are you using?
2. Are you able to test by using a fresh portable flow and let flow install Everything when prompted.

**Comment by DRYN07** [comment]
I switched to the regular installed version, and I feel it is much faster, more stable, and everything works properly. I hope there will be some "sync settings" solution in the future because it's a bit inconvenient to keep transferring settings if someone uses multiple computers.

**Comment by jjw24** [comment]
>I switched to the regular installed version, and I feel it is much faster, more stable, and everything works properly

As in the installed version? There is no difference between installed and portable version though.

>I hope there will be some "sync settings" solution in the future because it's a bit inconvenient to keep transferring settings if someone uses multiple computers.

Does it work well if you sync the portable version between computers?

**Comment by DRYN07** [comment]
The installed version loads much faster than the portable one. I use Google Drive and the whole folder is set to Local. Unfortunately, this is not very usable this way, I assume because one of the two machines is a laptop that is hibernated during the day. Sometimes one doesn't see the changes made by the other, and after a while, it becomes impossible to track what has been synchronized and what hasn't, even though they are using the same folder. Strange.

So yes, it might be that the Drive folder itself is the problem :/
