### ISSUE TITLE
BUG: it works but a window appears

### ISSUE THREAD

**Issue by Hadrienbbd** [Flow-Launcher/Flow.Launcher#2857]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

[2024-07-22.txt](https://github.com/user-attachments/files/16335068/2024-07-22.txt)

Flow launcher did what he should but a stranger window appears.
Maybe it is the Spotify's plugin ?

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![Capture d’écran 2024-07-22 161939](https://github.com/user-attachments/assets/19175ab2-506d-4f9f-9dbb-9caea60971e9)

### Flow Launcher Version

1.18.0

### Windows Build Number

22631.3880

### Error Log

09:20:16.8092+02:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
09:20:16.8092+02:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.18.0
OS Version: 22631.3447
IntPtr Length: 8
x64: True
09:20:20.2645+02:00 - INFO  - ImageLoader.Initialize - Preload images cost <2808ms>
09:20:20.2776+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <74ms>
09:20:20.2776+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <51ms>
09:20:20.2897+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <85ms>
09:20:20.2897+02:00 - INFO  - ImageLoader.Initialize - Number of preload images is <70>, Images Number: 70, Unique Items 44
09:20:20.2897+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <113ms>
09:20:20.3166+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <144ms>
09:20:20.3166+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <SpotifyPremium> is <112ms>
09:20:20.3444+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <143ms>
09:20:20.4637+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <296ms>
09:20:20.4637+02:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
09:20:20.4801+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <644ms>
09:20:20.5813+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Google Calendar> is <100ms>
09:20:20.6389+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <ChatGPT> is <293ms>
09:20:20.6389+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <FlowYouTube> is <175ms>
09:20:20.7182+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <503ms>
09:20:20.7768+02:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
09:20:20.7768+02:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
09:20:20.7768+02:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
09:20:20.9978+02:00 - ERROR - BinaryStorage.Deserialize - Deserialize error for file <C:\Users\maril\AppData\Roaming\FlowLauncher\Cache\Win32.cache>
EXCEPTION OCCURS: MemoryPack.MemoryPackSerializationException: Sequence reached end, reader can not provide more buffer.
   at void MemoryPack.MemoryPackSerializationException.ThrowSequenceReachedEnd()
   at ref byte MemoryPack.MemoryPackReader.GetNextSpan(int sizeHint)
   at string MemoryPack.MemoryPackReader.ReadUtf8(int utf8Length)
   at void Flow.Launcher.Plugin.Program.Programs.Win32.MemoryPack.IMemoryPackable<Flow.Launcher.Plugin.Program.Programs.Win32>.Deserialize(?) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.Program/MemoryPack.Generator/MemoryPack.Generator.MemoryPackGenerator/Flow.Launcher.Plugin.Program.Programs.Win32.MemoryPackFormatter.g.cs:line 236
   at void MemoryPack.Formatters.MemoryPackableFormatter<T>.Deserialize(ref MemoryPackReader reader, ref T value)
   at void MemoryPack.Formatters.ArrayFormatter<T>.Deserialize(ref MemoryPackReader reader, ref T[] value)
   at int MemoryPack.MemoryPackSerializer.Deserialize<T>(in ReadOnlySequence<byte> buffer, ref T value, MemoryPackSerializerOptions options) x 2
   at async ValueTask<T> MemoryPack.MemoryPackSerializer.DeserializeAsync<T>(Stream stream, MemoryPackSerializerOptions options, CancellationToken cancellationToken)
   at async ValueTask<T> Flow.Launcher.Infrastructure.Storage.BinaryStorage<T>.DeserializeAsync(Stream stream, T defaultData) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs:line 65

09:20:20.9978+02:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <693ms>
09:20:20.9978+02:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <0>
09:20:20.9978+02:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <54>
09:20:20.9978+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <977ms>
09:20:21.2286+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <1051ms>
09:20:21.4496+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:21.4496+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
InnerException number: 1
Exception message: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
Possible resolution: Not yet known
09:20:21.4496+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:21.7684+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:21.7684+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
InnerException number: 1
Exception message: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
Possible resolution: Not yet known
09:20:21.7684+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:22.4057+02:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 156 plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
09:20:22.4242+02:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <2301ms>
09:20:23.0576+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: XeroxCorp.PrintExperience_f7egpvdyrs2a8!PrintExperience can't find logo uri for Assets\ApplicationIcons\AppIcon\AppIcon.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
09:20:23.0576+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: XeroxCorp.PrintExperience_f7egpvdyrs2a8!PrintExperience can't find logo uri for Assets\ApplicationIcons\AppIcon\AppIcon.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
09:20:23.0576+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: XeroxCorp.PrintExperience_f7egpvdyrs2a8!PrintExperience can't find logo uri for Assets\ApplicationIcons\AppIcon\AppIcon.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
09:20:23.0576+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:23.0576+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: LogoPathFromUri
Program path: C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: XeroxCorp.PrintExperience_f7egpvdyrs2a8!PrintExperience can't find logo uri for Assets\ApplicationIcons\AppIcon\AppIcon.png in package location (logo name or directory not found): C:\Program Files\WindowsApps\XeroxCorp.PrintExperience_8.110.13.0_x64__f7egpvdyrs2a8
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
09:20:23.0576+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:24.0419+02:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: C:\Users\maril\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
09:20:24.4440+02:00 - INFO  - Flow.Launcher.Plugin.Program.Main - UWPProgram index cost <3439ms>
09:20:25.0582+02:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
09:20:25.0582+02:00 - INFO  - App.OnStartup - Startup cost <9075ms>
09:20:26.7184+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:26.7184+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
09:20:26.7184+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:26.7916+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:20:26.7916+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
09:20:26.7916+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:20:27.3540+02:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "0F4C15147CCE5AD43CBE27120B61230BB834A32E",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.18.0-full.nupkg",
  "Query": null,
  "Filesize": 105458488,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "0F4C15147CCE5AD43CBE27120B61230BB834A32E FlowLauncher-1.18.0-full.nupkg 105458488",
  "Version": {
    "Version": "1.18.0.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
09:20:29.6225+02:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Win32Program index cost <8618ms>
14:20:27.3107+02:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "0F4C15147CCE5AD43CBE27120B61230BB834A32E",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.18.0-full.nupkg",
  "Query": null,
  "Filesize": 105458488,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "0F4C15147CCE5AD43CBE27120B61230BB834A32E FlowLauncher-1.18.0-full.nupkg 105458488",
  "Version": {
    "Version": "1.18.0.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
15:45:51.2086+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:45:51.2086+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
InnerException number: 1
Exception message: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\msrdc.exe
Possible resolution: Not yet known
15:45:51.2086+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:45:52.1319+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:45:52.1319+02:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
InnerException number: 1
Exception message: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe\wslg.exe
Possible resolution: Not yet known
15:45:52.1319+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:46:06.3039+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:46:06.3039+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
15:46:06.3039+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
15:46:06.6516+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
15:46:06.6516+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
15:46:06.6516+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
20:12:49.6083+02:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "0F4C15147CCE5AD43CBE27120B61230BB834A32E",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.18.0-full.nupkg",
  "Query": null,
  "Filesize": 105458488,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "0F4C15147CCE5AD43CBE27120B61230BB834A32E FlowLauncher-1.18.0-full.nupkg 105458488",
  "Version": {
    "Version": "1.18.0.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>

**Comment by z1nc0r3** [comment]
Do you have any steps to reproduce the issue?

**Comment by jjw24** [comment]
This looks like a potential settings load issue. Have you been modifying the settings json file by any chance?

**Comment by Hadrienbbd** [comment]
No, I didn't.
The window appears when I launch a command to Spotify (like "next track" or "play").

(Sorry for my English. I'm French and I'm not a developer 😅)

**Comment by amzon-ex** [comment]
Got the same problem. Action gets executed but error window pops up.

```
Flow Launcher version: 1.18.0
OS Version: 26120.1330
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 07/31/2024 00:32:40
Exception:
System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: E. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Post(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.SkipNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Skip() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 207
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass37_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 568
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by z1nc0r3** [comment]
it seems like an issue with the exception handling in the plugin and it tries to generate results after the task execution. Does this happen only with the Spotify plugin or any others?

**Comment by jessgibs18** [comment]
I also get this. After I get it a few times then the plugin does stop working or hang.

Flow Launcher version: 1.18.0
OS Version: 22631.3880
IntPtr Length: 8
x64: True

Python Path: C:\Users\jgibson\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 08/16/2024 13:54:04
Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Z. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.ResumePlayback()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Play() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 149
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass37_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 568
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi all this is an issue with Spotify Premium plugin, please track over at https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/issues/41
