### ISSUE TITLE
Search window settings

### ISSUE THREAD

**Issue by caphefalumi** [Flow-Launcher/Flow.Launcher#2859]
**Is your feature request related to a problem? Please describe.**
Yes. The windows setting plugin does not work at all, I cant find the storage sense setting nor activation setting and pretty much everything else

**Describe the solution you'd like**
I want to find all window settings just like when I search with Window search bar

<img width="563" alt="image" src="https://github.com/user-attachments/assets/147dccd3-fd95-467f-b395-996192bc26d3">

![image](https://github.com/user-attachments/assets/77724adb-e630-4148-affe-bd69bea4c7b7)

**Comment by z1nc0r3** [comment]
couldn't reproduce. Could you check whether you have added an Action Keyword or not?

- with Action Keyword
![image](https://github.com/user-attachments/assets/7115e0d6-6418-4c1f-b16c-cd5875c167a9)

- without Action Keyword
![image](https://github.com/user-attachments/assets/a64697f8-f1d5-40e8-a1eb-80dd98232bda)
