### ISSUE TITLE
BUG: Environment Variables Setting not available

### ISSUE THREAD

**Issue by xd003** [Flow-Launcher/Flow.Launcher#2860]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

These options from Windows setting namely - "Edit the system environment variables" & "Edit the environment variables for your account" are not searchable/visible in Flow Launcher

### To Reproduce

Just search for "environment". It would show up fine in the windows search

### Flow Launcher Version

v1.18.0

### Windows Build Number

Microsoft Windows [Version 10.0.26100.1000]

### Screenshot

![image](https://github.com/user-attachments/assets/f1a160ef-54b4-4ebc-90e6-9783774b1d63)

**Comment by kubalav** [comment]
It's system settings. You have to add "s" before query (shortcut for Windows Settings plugin), like this:

> s environment

**Comment by xd003** [comment]
> It's system settings. You have to add "s" before query (shortcut for Windows Settings plugin), like this:
> 
> > s environment

Thanks for the heads up, can confirm it works. I realised i could also change from s to * to make it work directly
