### ISSUE TITLE
BUG: Bookmarks in other browsers ( not edge ) 

### ISSUE THREAD

**Issue by ShayanKhodadadian** [Flow-Launcher/Flow.Launcher#2868]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Hey there, 
i recently installed flow launcher and i discovered we have problem in read bookmarks in chrome browsers and it does not work with theme , ill be happy if someone check this issue please 
have a nice day 

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![Screenshot 2024-08-01 124545](https://github.com/user-attachments/assets/823a4792-9999-45b0-9892-5304d67c8ea0)

### Flow Launcher Version

1.18.0

### Windows Build Number

22635.4000

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment]
Hi, sorry didn't get what you mean by "_does not work with theme..."_. 
Also, please check the **bookmarks** plugin configs to ensure you have checked the **Chrome** browser.

**Comment by ShayanKhodadadian** [comment]
Hey there, 
Sorry i didn't mentioned something important 
I'm using chrome browser , but **BETA VERSION** , i guess that's the reason that is not working properly 
is it solvable or not ?

**Comment by z1nc0r3** [comment]
You can add your browser through here. Have you tried it already?

![image](https://github.com/user-attachments/assets/3e4c4ab0-671f-4cda-bef6-93ae9798d084)
_Others > Add_ ( keep the engine as it is )

**Comment by ShayanKhodadadian** [comment]
yeah i tried , and its still not working properly 
![Screenshot 2024-08-03 002228](https://github.com/user-attachments/assets/5e1a9944-8ede-4b66-884d-acd8eafca40a)

**Comment by ShayanKhodadadian** [comment]
i founded the solution , ty for helps
