### ISSUE TITLE
Can't report log error : There was an error creating your Issue: body is too long (maximum is 65536 characters).

### ISSUE THREAD

**Issue by ft-fk** [Flow-Launcher/Flow.Launcher#2869]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

All in title, I just got an error with a log : I can't upload it because it's too long

### Flow Launcher Version

1.18.0

### Windows Build Number

22000.2538

**Comment by ft-fk** [comment]
Just to be clear : 
In the section of the new issues of github where logs are supposed to be copy-paste, it is not possible to do so because it's too long

**Comment by Garulf** [comment]
> Just to be clear : In the section of the new issues of github where logs are supposed to be copy-paste, it is not possible to do so because it's too long

Please try and paste what you can here: https://gist.github.com/
