### ISSUE TITLE
BUG: Last query doesn't clear after using Drag n Drop a file

### ISSUE THREAD

**Issue by z1nc0r3** [Flow-Launcher/Flow.Launcher#2872]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

After using a file _Drag n Drop_ through the FL window to move a file, the **last query and results doesn't clear automatically** even with the `Last Query Style` set to `Empty Last Query`. This only happens when **moving a file**, and works fine after copying a file.

https://github.com/user-attachments/assets/c93bec1b-7ab1-453e-b218-7faec66326b2

_Moving a file between folders on the same Drive. When I open FL again, the last query stays_
don't

### To Reproduce

1. Make sure `Last Query Style` is set to `Empty Last Query` in General settings
2. Search any file _(didn't check with the folders)_
3. Drag and Drop the file from the results to a folder on the same Drive as the file already in _(to make sure the file is moving instead of copying)_
4. Open the FL again and you'll see the last query and results

### Flow Launcher Version

1.18.0

### Windows Build Number

22631.3958

**Comment by rahulnoir** [comment]
I have noticed this bug as well. I found it useful sometimes. But nonetheless, it should behave as per the query preserve settings set in the app settings.

**Comment by z1nc0r3** [comment]
> #2618

So, is the FL window originally supposed to come back automatically after the move is done?

**Comment by VictoriousRaptor** [comment]
> > #2618
> 
> So, is the FL window originally supposed to come back automatically after the move is done?

Yeah, originally it was.
