### ISSUE TITLE
[general->last query style -> select clipboard]

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#2875]
**Is your feature request related to a problem? Please describe.**

It's always frustrating when I have to constantly press Control + V to search for something.

**Describe the solution you'd like**

I want to automate the process so that when I press Alt + Space, it automatically selects the content of my clipboard.
![image](https://github.com/user-attachments/assets/8c599c1b-2887-4d21-bc96-9d16122719f4)

**Describe alternatives you've considered**

I can achieve this by creating custom shortcuts, but it is inconvenient.

**Comment by VictoriousRaptor** [comment]
Hi, an alternative way is to assign a dedicated hotkey in custom hotkey settings, and assign it's query to `{clipboard}`.
