### ISSUE TITLE
Set default settings to mute sound, no animation, and use system theme

### ISSUE THREAD

**Issue by amitkulk123** [Flow-Launcher/Flow.Launcher#2884]
**Is your feature request related to a problem? Please describe.**

I always change those options everytime I install Flow Launcher. I'm pretty sure most people do the same because it gets annoying after a while and the default behavior in Powertoys Run, Wox, and Spotlight Search in macOS don't have sounds or animations. 

**Describe the solution you'd like**

I'd like the default settings to at least mute sound and follow the system theme. Disable animation would also be a plus. Changing these default settings will prevent distractions whenever typing a program name or query.

**Describe alternatives you've considered**

N/A Flow Launcher is still my go-to since it's considerably faster than Powertoys Run 

**Additional context**
<img width="564" alt="Screenshot 2024-08-10 110804" src="https://github.com/user-attachments/assets/c04759f5-6fb6-4b20-8581-93361c09098f">

<img width="568" alt="Screenshot 2024-08-10 110741" src="https://github.com/user-attachments/assets/f7785a55-61d9-48d3-882c-c26b203a2cb0">

**Comment by Garulf** [comment]
Hi @amitkulk123,

May I recommend using Flow Launchers portable feature? With this mode you are able to share Flow Launchers and all your previous settings between multiple computers. You'll never have to turn off sound effects or change the theme again.

**Comment by jjw24** [comment]
Thumbs up if you also would like this, otherwise this will be parked until we get a good response on how many prefer this.

Portable mode as Garulf mentioned is good for this. Or another alternative is to transfer your existing UserData folder (has all the settings and plugins) to your new install.
