### ISSUE TITLE
[feature request] Enhanced Window Closing: Control Which App Windows to Close

### ISSUE THREAD

**Issue by nanoraptor** [Flow-Launcher/Flow.Launcher#2893]
### **Process Killer** - A More Targeted Approach

The current "Process Killer" command terminates all processes associated with an application. While this is useful in some cases, it can be problematic when users like me who want to close only specific windows or instances of an application without killing all its background processes. For example, killing all Teams processes closes the tray icon and other essential background services.

![Screenshot](https://github.com/user-attachments/assets/9e43b6ea-f741-4b22-a161-bc418c20e475)

### **Proposed Feature**: Similar to the "Quit" command in Alfred

- **Keyword Trigger**: When the command keyword is typed, it should list all running applications.
- **Closing All Windows**: If the user types the keyword followed by an application name (e.g., `kill teams`), it should close all active windows for that application but keep background processes like the tray icon intact.
- **Selective Window Closure**: If the user types the keyword followed by an application name and a space (e.g., `kill teams {window_name}`), it should list all open windows of that application, displaying their titles and a preview in the preview panel. The user can then select specific windows to close.

### **Improvisation and Edge Cases**:
- If a window has no title, display it with a generic label (e.g., "Untitled Window").
- If multiple windows with the same title exist, list them with additional identifiers (e.g., window position or creation time).

Any suggestions or improvements on this feature would be greatly appreciated.

**Comment by jjw24** [comment]
The window walker plugin has a hidden feature for closing application I believe, it's done via either Ctrl + Enter or Alt + Enter. See if that works. 

What you are describing is for closing a window, Process Killer plugin is more geared toward terminating processes.

**Comment by nanoraptor** [comment]
It works perfectly fine. Thanks!
