### ISSUE TITLE
Save Quick Look Preview position

### ISSUE THREAD

**Issue by DRYN07** [Flow-Launcher/Flow.Launcher#2896]
The Quick Look window always opens in the center of the screen and covers the Flow Launcher window, which also opens centrally. Is there a way to save the position and size of the Quick Look window to avoid this overlap?

![image](https://github.com/user-attachments/assets/b774c2ef-d57e-4db7-99ff-2dfe7de0bc76)

**Comment by jjw24** [comment]
This would be a great option to have but unfortunately it is something that only QuickLook can implement. Perhaps best to see if they would be interested in adding this option.

Closing since not something we can do on our side. Feel free to request reopen if require further discussion.

**Comment by Sneakpeakcss** [comment]
There's already a PR implementing this on QuickLook repo: https://github.com/QL-Win/QuickLook/pull/1338. I've been using the test build for a long time, but at this point my QL use so sporadic that i can't say if it intriduced any issues with it. The feature itself works fine on Win10.

**Comment by DRYN07** [comment]
@Sneakpeakcss thanks, I will definitely try this out!
