### ISSUE TITLE
Add Support for Everything search syntax (High Priority)

### ISSUE THREAD

**Issue by swishlabby** [Flow-Launcher/Flow.Launcher#2898]
### Enhance 'Everything' Plugin with Advanced Search Features (Regex, Syntax, etc.)

**Summary:**
I’m proposing an enhancement to Flow Launcher’s 'Everything' plugin to include advanced search features, such as regex and other powerful search syntax, similar to the implementation in PowerToys Run. This would significantly improve the search capabilities for users, making Flow Launcher an even more versatile and powerful tool.

**Context:**
I recently came across the 'Everything' plugin implementation in the PowerToys Run repository and was impressed with its handling of regex and advanced search syntax. These features allow users to refine their searches more precisely and would be a valuable addition to Flow Launcher.

**Why This Matters:**

- **Enhanced Search Functionality:** Bringing these advanced search features to Flow Launcher would provide users with more powerful tools to refine their searches. Even a simple syntax like audio:file_name doesn't work.
- **Will serve the plugin name aptly:** Since this plugin's aim is to eliminate opening up eveything app as much as possible. This will do exactly that. The mere drawback of not being able to use some above basic syntax in the launcher is a big let down for the plugin name. Some syntax that works with windows search doesn't even work with this (e.g. p*n for starting and terminating letters of the file)

**Proposal:**

- **Reference the PowerToys Run Implementation:** The current implementation of this plugin in PowerToys Run could serve as a blueprint for integrating similar features into Flow Launcher. We have an option to enable regex in the plugin settings. It does miss some keywords that come with colon and similar characters. But, it could be improvised here.
- **Collaborative Development (Maybe?) :** Perhaps there could be a collaboration or shared effort between the development teams to bring this feature to Flow Launcher, ensuring consistency and quality. I find this would make the feature arrival even quicker.

**Request:**
I would love to see these advanced features ported over to Flow Launcher's plugin, leveraging the strong foundation built in PowerToys Run. This could be a significant enhancement for the Flow Launcher community, providing a seamless and powerful search experience.

**Comment by nanoraptor** [comment]
I would highly vote for this to be implemented in the inbuilt everything plugin. I currently use **PowerToys**'s Everything [plugin](https://github.com/lin-ycv/EverythingPowerToys) for just the file searching as I find myself using a lot of keyword syntax in the search bar. In fact, I was about to raise this feature request myself. I request the developers to quickly look into this and push an update as soon as possible.

**Comment by swishlabby** [comment]
I see this being discussed somewhat in [#2656](https://github.com/Flow-Launcher/Flow.Launcher/issues/2656). But there was no convincing response from the dev @jjw24. I have also seen the request you made in [#769](https://github.com/Flow-Launcher/Flow.Launcher/issues/769).

**Comment by jjw24** [comment]
Thanks for the thorough issue write up and letting us know about PT's Everything implementation of the advanced search, it will help us in implementing this feature.

I think this is a great feature add, but I personally won't be able to provide a timeline when I can get to this, hopefully others will be able to help.

**Comment by swishlabby** [comment]
> Thanks for the thorough issue write up and letting us know about PT's Everything implementation of the advanced search, it will help us in implementing this feature.
> 
> I think this is a great feature add, but I personally won't be able to provide a timeline when I can get to this, hopefully others will be able to help.

Hopefully Soon.... as most people use flow launcher for this purpose alone.

**Comment by nanoraptor** [comment]
@jjw24 I asked this question to the creator of the Everything plugin for PT [@lin-ycv](https://github.com/lin-ycv). His reply to that ([#128](https://github.com/lin-ycv/EverythingPowerToys/issues/128)) was that he could offer some help but he was not clear with how the code works. Maybe there could be a collaboration betweeen the two to implement this feature as soon as possible. What do you think?

**Comment by jjw24** [comment]
Thanks for putting this forward, I think whoever picks up this up can reach out to lin-ycv if needing help. For now, I would like to but really won't be able to commit to making this due to other commitments.

**Comment by indigofairyx** [comment]
I up vote this! 

I use Dopus as a file manager. They have integrated everything seamlessly into the the file explorer. Not only everything syntax, I can also search my "bookmarks" and filters thru the location bar of the explorer. It's amazing.

https://docs.dopus.com/doku.php?id=release_history:opus13_detailed:everything

That short highlights page doesn't do it justice. 

The community on their forums is great. It's it any help go check them out. 

Alas I'm not a programmer or I'd be jumping in on this one.

The everything integration is new for v13 this year. Before that there was this side project from a dopus user, which they incorporated into the software. 
https://github.com/TheZoc/EverythingDopus

I don't know if the language are similar thou hopefully that could help.

Thank you for flow! It's in my top 5 fav functional softwares with dopus, everything and autohotkey. 


Off topic to sing the praises of dopus and everything. I, with very simple syntax, created a function in dopus that allows me to send a system index content search thru everything which is displayed back in dopus near instantly! It wonderful... https://resource.dopus.com/t/search-content-in-windows-system-index-via-everything/51646

**Comment by soul4feels** [comment]
I'm using Everything 1.5.0.1383a. All the advanced search features work for me. Is this still an issue?

![Screenshot 2024-09-06 130342](https://github.com/user-attachments/assets/8592bc1e-0a45-4f0a-9d79-c7fb408a0f8d)
![Screenshot 2024-09-05 170415](https://github.com/user-attachments/assets/6710a27c-5b00-4d84-b09b-3b
![Rcy7ls5](https://github.com/user-attachments/assets/72b067ba-9b54-43f2-bcc3-dac58361e41e)
259093f84b)

**Comment by nanoraptor** [comment]
> I'm using Everything 1.5.0.1383a. All the advanced search features work for me. Is this still an issue?

No, the issue is still open and it only works on the alpha version and not the regular Everything version. It seems that there is a filter rework that was done in the alpha version.

**Comment by swishlabby** [comment]
It appears that some filter revisions have been implemented in the latest alpha version of Everything. Therefore, it's clear that the issue originated from Everything's end. I am closing this issue for now, as it will be resolved automatically when users upgrade to the alpha version or when the new version is released. Thank you to @soul4feels for highlighting this. For those who have trouble setting up the Everything 1.5a, you can see this [solved issue](https://github.com/Flow-Launcher/Flow.Launcher/issues/1716) from GitHub.

**Comment by swishlabby** [comment]
It appears that some filter revisions have been implemented in the latest alpha version of Everything. Therefore, it's clear that the issue originated from Everything's end. I am closing this issue for now, as it will be resolved automatically when users upgrade to the alpha version or when the new version is released. Thank you to @soul4feels for highlighting this. For those who have trouble setting up everything 1.5a, you can see this [solved issue](https://github.com/Flow-Launcher/Flow.Launcher/issues/1716) in GitHub.
