### ISSUE TITLE
VIRUS: My Avast find a virus

### ISSUE THREAD

**Issue by alunogmfs2** [Flow-Launcher/Flow.Launcher#2909]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

My Avast found a virus

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

I have no screenshot

### Flow Launcher Version

1.19.0

### Windows Build Number

10.0.22631.4037

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment]
Please check the pinned issue.
