### ISSUE TITLE
BUG: Wrong alignment since 1.19.0

### ISSUE THREAD

**Issue by CUR5EDFLVME** [Flow-Launcher/Flow.Launcher#2910]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I noticed that flowlauncher search bar isn't centered when I open it on the monitor with my mouse cursor on.
It started after the update on new 1.19.0 version.
I have two monitors, one 4k primary(scale 150%), and laptop 1080p screen(scale 100%).
![image](https://github.com/user-attachments/assets/a9a7ab0f-aad9-44b9-b9f5-f9b6f9a60cf8)

### To Reproduce

1. Hover mouse over monitor 1
2. Hit Open Flow launcher shortcut
3. Hover mouse over monitor 2
4. Hit Open Flow launcher shortcut
(repeat until your search window fly outside your apartment)

### Screenshots

![NVIDIA_Overlay_g83VmciPTp](https://github.com/user-attachments/assets/a63a7849-3d5a-46df-9a70-918749f1fa10)
![Flow Launcher_9mUx1ZFPh2](https://github.com/user-attachments/assets/639c2922-805e-427e-98aa-6fc4cc998a74)

### Flow Launcher Version

1.19.0

### Windows Build Number

10.0.22631.4037

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by MattFor** [comment]
This is insanely annoying on monitors with a high resolution difference, basically cannot see what you're typing.

**Comment by manzup3r** [comment]
guess i'm not the only one

**Comment by jjw24** [comment]
@manzup3r @CUR5EDFLVME  and anyone with this issue please help test this fix - https://ci.appveyor.com/api/buildjobs/yclbaj2dfg38e94k/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

Let us know if the issue is resolved.

**Comment by manzup3r** [comment]
> @manzup3r @CUR5EDFLVME and anyone with this issue please help test this fix - https://ci.appveyor.com/api/buildjobs/yclbaj2dfg38e94k/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
> 
> Let us know if the issue is resolved.

the issue is resolved. thank u!

**Comment by manzup3r** [comment]
> > @manzup3r @CUR5EDFLVME and anyone with this issue please help test this fix - https://ci.appveyor.com/api/buildjobs/yclbaj2dfg38e94k/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
> > Let us know if the issue is resolved.
> 
> the issue is resolved. thank u!

i found a very fringe case were a plugin called winflow breaks the position of the launcher again. to reproduce u have to use the plugin's "click to maximize all windows" feature. this maximizes flow launcher as well and, afterward, when launched, it's resized to take up the whole width of the screen, and docked at the very top of the monitor. this is probably an issue with the plugin itself, not flow launcher, only worth mentioning for anybody testing or fiddling around and accidentally stumbling on this, like i did. it's easy enough to troubleshoot, though

**Comment by CUR5EDFLVME** [comment]
> @manzup3r @CUR5EDFLVME and anyone with this issue please help test this fix - https://ci.appveyor.com/api/buildjobs/yclbaj2dfg38e94k/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
> 
> Let us know if the issue is resolved.

Works good for me, good job my dude!!

**Comment by jjw24** [comment]
> > > @manzup3r @CUR5EDFLVME and anyone with this issue please help test this fix - https://ci.appveyor.com/api/buildjobs/yclbaj2dfg38e94k/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
> > > Let us know if the issue is resolved.
> > 
> > 
> > the issue is resolved. thank u!
> 
> i found a very fringe case were a plugin called winflow breaks the position of the launcher again. to reproduce u have to use the plugin's "click to maximize all windows" feature. this maximizes flow launcher as well and, afterward, when launched, it's resized to take up the whole width of the screen, and docked at the very top of the monitor. this is probably an issue with the plugin itself, not flow launcher, only worth mentioning for anybody testing or fiddling around and accidentally stumbling on this, like i did. it's easy enough to troubleshoot, though

Sounds like an issue with plugin maybe, will keep in mind. Best to let the plugin dev know so can investigate.
