### ISSUE TITLE
[Describe Your Feature] live search results like fluent search

### ISSUE THREAD

**Issue by ThinkSalat** [Flow-Launcher/Flow.Launcher#2911]
Fluent search shows a live updated embedded google search - this actually has the benefit of giving you all of google's built in niceties like unit conversion, currency conversion, translation (though not as good as the translation plugins), as well as just getting quick answers

This alone gives access to countless useful utilities

**Screenshot examples**
Unit conversion
![image](https://github.com/user-attachments/assets/554ed8d7-78b6-4392-acec-8f3605f0edbc)
![image](https://github.com/user-attachments/assets/344a0445-6e8b-4bd8-a6ce-e84d77e011ba)

currency conversion
![image](https://github.com/user-attachments/assets/6eec7775-d9a3-4f90-a828-7551fc80d5bc)

Ad hoc search
![image](https://github.com/user-attachments/assets/10ac3b23-6232-44e8-8649-b16aa1f863a0)
![image](https://github.com/user-attachments/assets/e754dc8a-fa98-4712-bb34-7f6dcf80260c)
![image](https://github.com/user-attachments/assets/f4970d52-3897-486c-acc3-55d3c367ab5b)

**Comment by jjw24** [comment]
Hi there, thanks for putting this forward. We already have an issue with this feature, so please follow for any updates - https://github.com/Flow-Launcher/Flow.Launcher/issues/2725
