### ISSUE TITLE
[Explorer Plugin] Allow Folder search with an extra actionkeyword

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#292]
Folder search with a special action keyword.
Sometimes we want to open a specific folder, but the result doesn't show it because too much other item that fulfill the requirement has been found.

**Comment by jjw24** [comment]
Is this basically using an action keyword to search for folders only?

**Comment by taooceros** [comment]
yes, so that we can use index search with a keyword and still access folders without action keyword
