### ISSUE TITLE
BUG: Settings Window

### ISSUE THREAD

**Issue by 1208nn** [Flow-Launcher/Flow.Launcher#2935]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

![image](https://github.com/user-attachments/assets/f81ec227-3da5-4909-a009-f9e233aa625e)

only the 3 buttons(min,max,close) can click

### To Reproduce

use control+i to open the window and this randomly happens

### Flow Launcher Version

1.19

### Windows Build Number

win10 22H2 professional workstation 19045.4780

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Could you upload the log when this happens again please.

**Comment by 1208nn** [comment]
i can't find any related logs

but i can tell you that i found this must happen when you have pressed `win+L` and came back

**Comment by Kylotan** [comment]
Most likely a dupe of #2969

**Comment by 1208nn** [comment]
This problem solved at 1.19.5.
