### ISSUE TITLE
BUG: Flow Launcher Crashes on typing in numbers (triggering calculator)

### ISSUE THREAD

**Issue by wynhou** [Flow-Launcher/Flow.Launcher#2937]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Since the latest version, every time I enter a number to trigger the calculator (the second I type * or /) it seems to crash completely.

Starting a new instance of the app rebooks the calculator

### To Reproduce

1. Type number, trigger a calculation, app crashes

### Flow Launcher Version

1.19.0

### Windows Build Number

22631.4108

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi. I can't reproduce this. Can you list the plugins you have installed that don't have a keyword set (in settings the keyword is a '*'). Thanks.
