### ISSUE TITLE
Is it possible to develope as a UWP app?

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#294]
For Flow, it has any possible to develope as a [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) app.

**Comment by taooceros** [comment]
Seems that UWP doesn't allow loading assembly on runtime, which means the current plugin system won't work.

**Comment by jjw24** [comment]
@Zeroto521 what are your thoughts on developing flow as an UWP app though?

**Comment by Zeroto521** [comment]
> @Zeroto521 what are your thoughts on developing flow as an UWP app though?

Not much, I don't know about UPW technology details, but I want to say some from some general user view.

- for download & update part. I could manage all software from one place. We don't need to care about how to download or install it. And even global users can direct it with the max downloading speed.
- for the UI part. Actually, I hate that. It's hard both for developers to design and general users to use.

**Comment by jjw24** [comment]
Yeah ok, fair enough. 

I personally don't have experience in building uwp apps or looked into what's involved in publishing it, but I am definitely open to upgrading to uwp provided thats something that will provide benefits. Same goes for UI as well, happy for another refresh as always.

Will close this question for now and happy to reopen for discussion for later if needed.
