### ISSUE TITLE
(plugin dev) set different IcoPath for dark theme

### ISSUE THREAD

**Issue by adielBm** [Flow-Launcher/Flow.Launcher#2942]
is there a way to determine if the theme is dark (or retrieve the background of `QueryBoxStyle`) so that I can set a different `IcoPath` accordingly? I haven't been able to find information on how to achieve this. thanks!

**Comment by Garulf** [comment]
Sorry there isn't any mechanism for this. I'd recommend using glyphs instead of icons if possible. Glyphs are are colored based on the font color and will change according to theme.
