### ISSUE TITLE
[Describe Your Feature] Blacklist results

### ISSUE THREAD

**Issue by Chaoscontrol** [Flow-Launcher/Flow.Launcher#2946]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when some plugins show a quite generic result on top. Specifically, the Notion plugin tends to show the "Create ..." whatever is your query as a page. This is a result I never want to see, as this is not the way I create pages. Most of the time I'm searching for something else. 

**Describe the solution you'd like**

Just like a "Set as top most result" exists, I'd like a "Never show this result" option. Where that result gets blacklisted. 

Ideally we'd have a space in settings to see all blacklisted results in case we want to recover them at some point. 

**Describe alternatives you've considered**

Just changing keyword for the annoying plugins, so they're not showing results as often.

**Comment by deefrawley** [comment]
You can set prioruty of plugins, is this what you mean?

**Comment by Chaoscontrol** [comment]
I had forgotten about that option and will give it a go with that to see if it helps. But no, the feature request is slightly different. Just a blacklisted specific result, within a plugin. 

I was just prompted by Garulf on Discord to post it here as he found it an interesting and useful suggestion.

**Comment by Chaoscontrol** [comment]
![image](https://github.com/user-attachments/assets/4e281f2c-28d2-435a-9c94-d45dd6280a6f)

For example. Explorer and Programs have both higher priority here. Notion has 0. And this result is not set to top. For some damn reason this f'ing result keeps showing first even when there are some clear more fitting candidates down there. 

A "Create..." kind of query should only be interesting when nothing else fits.

**Comment by deefrawley** [comment]
For the Notion plugin issue check this setting

![image](https://github.com/user-attachments/assets/e71d5321-4717-4618-8e56-82a7647f9e23)

**Comment by Chaoscontrol** [comment]
Thanks @deefrawley but I don't have that option. 

![image](https://github.com/user-attachments/assets/56b2d0e0-6898-4620-9025-140d2c4f22c3)

I think there's a different Notion plugin, but I prefer this one as it has extra options related to databases. 

I found a workaround by setting priority -100 for now, so I'm living pain free now at least.

**Comment by deefrawley** [comment]
It's the same pluigin but you are several versions behind the latest.  Try `pm update` in Flow to see available plugin updates.

**Comment by Chaoscontrol** [comment]
Lol you're so right. But look... 

![image](https://github.com/user-attachments/assets/1016047f-e03b-4885-b05b-36852e348cec)

I'll try to do a manual install. Thanks for the heads up.
