### ISSUE TITLE
Move to recycle bin/trash instead of permanent delete

### ISSUE THREAD

**Issue by galantra** [Flow-Launcher/Flow.Launcher#2947]
**Is your feature request related to a problem? Please describe.**

The context menu for files and folders only has an action to permanently delete it.

**Describe the solution you'd like**

A setting to configure whether the action should permanently delete it or only send it to trash.

**Describe alternatives you've considered**

Perhaps Flow Launcher could follow the setting of Windows Explorer.

**Additional context**

![image](https://github.com/user-attachments/assets/06eb29f4-79bd-49dd-899e-ac460d97a0b7)

**Comment by nanoraptor** [comment]
You can use native context menu by using the keybinding alt+enter. Make sure you have native context menu enabled in the explorer plugin settings. You can temporarily delete files from there.

**Comment by nanoraptor** [comment]
@jjw24 This issue can be closed now.

**Comment by nanoraptor** [comment]
I think the issue can be closed now?
