### ISSUE TITLE
Add multiple search to web searches plugin

### ISSUE THREAD

**Issue by Nyox-x** [Flow-Launcher/Flow.Launcher#2956]
I want a function that can search different sites in one action word.
For example,
[search ‘Amy’ in both facebook and twitter,
action word:          so
url:           https://www.facebook.com/search/?q={q}
                https://twitter.com/search?q={q}
]
use the same url formate and separate them like write them line by line.（Or use other characters to separate them?)

**Comment by jjw24** [comment]
The Shortcuts plugin is now built for this request, please try the plugin. 

Dup of https://github.com/Flow-Launcher/Flow.Launcher/issues/2097
