### ISSUE TITLE
A Way To Install Plugins Without Restarting Every Time

### ISSUE THREAD

**Issue by y0himba** [Flow-Launcher/Flow.Launcher#2961]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an inconvenience...

It is frustrating to restart flow launcher every time I install a plugin.

**Describe the solution you'd like**
Either a package of all current plugins that can be downloaded and moved to the directory, or a way to install multiple plugins, then restart when finished, unless absolutely necessary to restart.

Select multiple plugins and install at once, then restart, or install each plugin then restart after all are installed.

**Describe alternatives you've considered**
A large downloadable file containing all the plugins and instructions where to place them.  Then the ability to select only the ones you wish to use. 

See above. 

**Additional context**
None needed.  On first run, customizing, then installing plugins, it is very tedious to need to restart the launcher each time.

**Comment by VictoriousRaptor** [comment]
It's already implemented. There's a checkbox in plugins manger that allows you to install/uninstall multiple plugins then restart.

**Comment by y0himba** [comment]
Thank you!  Sorry to bother.

**Comment by Martinspire** [comment]
> Thank you! Sorry to bother. I cannot seem to find that one?

Settings > Plugins > Plugins Manager > expand it > Uncheck "Automatically restart Flow Launcher after installing/uninstalling/updating plugins"

What would be neat is a restart button on top of the plugin manager to restart the application... If any devs are watching...

**Comment by VictoriousRaptor** [comment]
> > Thank you! Sorry to bother. I cannot seem to find that one?
> 
> Settings > Plugins > Plugins Manager > expand it > Uncheck "Automatically restart Flow Launcher after installing/uninstalling/updating plugins"
> 
> What would be neat is a restart button on top of the plugin manager to restart the application... If any devs are watching. But now if you uncheck it, you have to close and open the application manually.

You may just type restart in Flow (provided by the built-in System plugin) to restart Flow.
