### ISSUE TITLE
Why is the tray icon useless???

### ISSUE THREAD

**Issue by starringer** [Flow-Launcher/Flow.Launcher#2972]
It's extremely frustrating that when I don't quite remember how to use Flow, trying to use the tray icon is an exercise in futility. Sometimes I just plain forget the shortcut. If the tray icon is going to be there, right-clicking on it should at least TRY to show me something that'll help me use it.

**Comment by deefrawley** [comment]
Hi. Right clicking on the tray icon does show the following menu

![image](https://github.com/user-attachments/assets/f9e01f62-ffdd-4b0a-bc2d-46946ad5a572)

**Comment by starringer** [comment]
Ok, then can you explain how even after I've now re-installed Flow twice, there is still no reaction whatsoever when I right-click the tray icon?
