### ISSUE TITLE
Improve search by settings and system app

### ISSUE THREAD

**Issue by Nireallki** [Flow-Launcher/Flow.Launcher#2974]
At the moment, this is poorly implemented relative to system settings. It works only in English and does not understand requests to Windows settings. For example, Check for updates (Windows), Create and format hard disk partitions, StartUp, etc. Therefore, sometimes you still have to use the native Windows search.
![Untitled](https://github.com/user-attachments/assets/2a84b346-9f97-45b3-9878-ef15f992a1d6)

Stardock tried to implement an adequate search (even by system language) with its Start11. In their folder in appdata, they have a folder with a huge number of links to all these settings (with the desired language and icon)
It would be cool to see this here.

It would also be nice to have a function to disable the ability to increase and decrease the search field. Now you can always do this when hovering the cursor over the frame, this sometimes gets in the way

**Comment by deefrawley** [comment]
Hi. System commands are a plugin that has a keyword of 's' by default. So for Windows update type `s update1 and you will see it. You can of course change this It's always best to have a good look through the settings if you find you can't do something in Flow.

**Comment by jjw24** [comment]
Is this issue actually not able to search windows settings by language? I can see I the screenshot you can find the start up control panel items and I was able to search the start up item in windows settings.
