### ISSUE TITLE
Sort Search Results by Frequency of Use

### ISSUE THREAD

**Issue by lucius346346** [Flow-Launcher/Flow.Launcher#2987]
I didn't find anything like that in settings. I'd like to prioritize search results based on how frequently a user selects certain items. Something like run count in "Everything".

**Comment by deefrawley** [comment]
Hi. This is default behaviour of Flow. It's not a setting, it just happens.

**Comment by jjw24** [comment]
Fyi it may take a couple of times selecting the same result before it is prioritised high in the list.
