### ISSUE TITLE
Use cancellation with Explorer's DirectorySearch

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#299]
The all files and folders search with Explorer's DirectorySearch seems to run quite long, can we add the use of cancellation token to stop when next query comes in.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/104977291-2331c780-5a3a-11eb-91dc-b1a81c318c57.png)
Do you mean this one?

**Comment by jjw24** [comment]
yep that's the one :)

**Comment by taooceros** [comment]
A question toward searching within directory.
Since we don't set a limit here, shall we also remove the 100 item limit when using index search for file inside directory?
