### ISSUE TITLE
BUG: 1.19.2 doesnot work on my Win11

### ISSUE THREAD

**Issue by BedBug2479** [Flow-Launcher/Flow.Launcher#2994]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I cannot start the app 1.19.2 through exe or through portable file in my current windows (attached the setup log)

But 1.19.1 is working fine

### To Reproduce

Both portable and installer for 1.19.2 is not working I have attached the setup log

### Flow Launcher Version

1.19.2

### Windows Build Number

10.0.22631.4169

### Error Log

[SquirrelSetup.log](https://github.com/user-attachments/files/17124674/SquirrelSetup.log)

**Comment by Kamran-Haiderr** [comment]
Can confirm the same issue on the latest version of Windows 10 .V 1.19.2 doesn't launch by any methods.

**Comment by alexvik** [comment]
Feel exactly the same issue on Windwos 7 x64. Tried to remove and reinstall v1.19.2 again but with no success.
And have to rollback to v1.19.1.

**Comment by deefrawley** [comment]
Hi All. The team will need logs, screenshots, error messages etc. to diagnose so please provide here. Thanks

**Comment by z1nc0r3** [comment]
Can you confirm whether you can install/run the `v1.19.3` version without issues?

**Comment by BedBug2479** [comment]
> Can you confirm whether you can install/run the `v1.19.3` version without issues?

cannot confirm for time being as the system is not with me until next month

**Comment by alexvik** [comment]
Yes, it looks like version `v1.9.3` as well as `v1.9.4` are working fine for me now (at Windows 7 and Windows 8.1). 🚀

**Comment by BedBug2479** [comment]
> Can you confirm whether you can install/run the `v1.19.3` version without issues?

v1.19.4 is working fine now 
closing the issue
