### ISSUE TITLE
Restart Flow Launcher when I install all the plugin I need

### ISSUE THREAD

**Issue by bkbprod** [Flow-Launcher/Flow.Launcher#2999]
Just like the title,like I use a lot of plugins and across many computers. So restarting Flow Launcher everytime I want to install a single plugin can be a hassle

**Comment by VictoriousRaptor** [comment]
Dup [#2961. ](https://github.com/Flow-Launcher/Flow.Launcher/issues/2961#issuecomment-2333163674).

There's a checkbox in plugins manger that allows you to install/uninstall multiple plugins then restart.
