### ISSUE TITLE
BUG: Youtube Downloader

### ISSUE THREAD

**Issue by adapmal** [Flow-Launcher/Flow.Launcher#3001]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Couldn't download youtube video by plugin

### To Reproduce

Tried to download video; "Flow launcher got an error" messa pops up. 

### Flow Launcher Version

1.19.2

### Windows Build Number

22631.4169

### Error Log

[2024-09-28.txt](https://github.com/user-attachments/files/17175352/2024-09-28.txt)

**Comment by nanoraptor** [comment]
It would be best to post this issue on the github issues of the [plugin's page](https://github.com/DeepVoyager253/FlowLauncherYTDownload/issues/new). You can close the issue from the issue section of flow launcher. As I see the plugin hasn't really been updated for sometime.
