### ISSUE TITLE
BUG: Memory usage explodes while opening FL Settings

### ISSUE THREAD

**Issue by hermanocabral** [Flow-Launcher/Flow.Launcher#3008]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When opening the FL settings window from FL itself, the memory usage keeps growing until it uses all the free memory on the machine, then the process crashes, gets recycled, and the cycle repeats until the FL is closed/terminated.

### To Reproduce

1. Open FL settings from FL
2. Settings windows shows up but is unresponsive
3. Watch memory go kaput

### Screenshots

![image](https://github.com/user-attachments/assets/1555e960-fdef-411c-bf30-173148d5294e)

### Flow Launcher Version

1.19.2

### Windows Build Number

22631.4169

### Error Log

<details>

```shell

21:31:38.7547+07:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
21:31:38.7547+07:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
21:31:38.7547+07:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------

```
</details>

**Comment by deefrawley** [comment]
Cannot reproduce on Windows 10. Memory stays steady with Settings open. Slight increase as I clicked through the different settings tabs

![image](https://github.com/user-attachments/assets/3dd563f5-331b-40c4-8f4b-d6f0db7e5edf)

**Comment by hermanocabral** [comment]
![image](https://github.com/user-attachments/assets/d1e5feaf-59bc-4083-8121-d1fc1c469649)

![image](https://github.com/user-attachments/assets/bf64eba9-9246-48e1-9958-5aefa0be98d2)
On latest Windows 11.

**Comment by deefrawley** [comment]
Apart from that settings screenshot looking wrong - is 32GB of memory on your system only 44% of total?!?!?

**Comment by hermanocabral** [comment]
> Apart from that settings screenshot looking wrong - is 32GB of memory on your system only 44% of total?!?!?

Yes, I have 96gigs in total.

**Comment by hermanocabral** [comment]
Managed to track it down to a plugin: Clipboard+, uninstalling it solved all the problems.
