### ISSUE TITLE
Re-index programs automatically/periodically

### ISSUE THREAD

**Issue by skjerns** [Flow-Launcher/Flow.Launcher#303]
I often leave my computer running for days without restarting Flow.Launcher. In the meantime I install new programs, however, each time I'm forced to manually reindex the programs content. 

Would it not be possible to automatically do this in certain intervals?

Also I feel like not all programs show up there all the time, i.e. not all paths where programs are found are added to the index automatically.

**Comment by taooceros** [comment]
It is designed to reindex every 3 days, although this will only be triggered when restarting flow. I think we should add it to query method as well.

Thank you for suggestion.

**Comment by taooceros** [comment]
> Also I feel like not all programs show up there all the time, i.e. not all paths where programs are found are added to the index automatically.

Are those programs lies within start menu or the default program file folder? If not, you may need to manually add the folder to index it.

**Comment by jjw24** [comment]
> It is designed to reindex every 3 days, although this will only be triggered when restarting flow. I think we should add it to query method as well.
> 
> Thank you for suggestion. 

That's a good idea actually, kick off the index in the background if certain conditions are met.

**Comment by skjerns** [comment]
Great that this was implemented. However, could the interval be a bit shorter? 3 days seems a bit infrequent. Either it could be a setting, or else every few hours?
