### ISSUE TITLE
BUG: Preview Inconsistency in using QuickLook Plugin

### ISSUE THREAD

**Issue by nanoraptor** [Flow-Launcher/Flow.Launcher#3030]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I have raised the same issue on the plugin's page. I don't think I am gonna get any reply there. So, I'm duplicating the issue here. 
### Description
The inbuilt preview panel in flow launcher and preview from `QuickLook Plugin` makes an inconsistency in previwing files in Flow Launcher. (The preview for programs and other non-file contents are still seen). This also 'forces' me to disable always preview setting in Flow Launcher while having the QLplugin enabled.
### Possible Solution
**Disable Inbuilt preview while QuickLook is on and vice versa**
See QuickLook is a plugin to preview files and explorer related contents. For example, when I jump from a file result to a program result (When QL preview window is already open), it should not trigger the preview of that program in the flow launcher's preview panel even if the user has set always preview on, then those programs can only previewed by disabling QL (Using alt+P)(incase of always preview being on, else it should not turn the preview on). This can be done by separating the shortcuts/call for QL preview and Inbuilt preview of Flow Launcher. 
- **Conditions**
Even If the inbuilt preview is enabled it should not trigger QuickLook and similarly when QL is on it should disable inbuilt preview even if it is turned on already and should return the setting of default preview(on/off) when it is turned off
It even makes sense logically as when we are previewing files we don't want the inbuilt preview to interrupt us by showing preview of a program which is useless in that context as the icon of the program is already visible.

**Always preview should not trigger QuickLook**
It's simple and I guess by following the above steps this will be automatically factored in. QL can only be enabled by only the shortcut. There should be a setting for always preview for QL else it has to be enabled everytime the launcher opens.

***Additional Feature**
There should be a shortcut in which holding down the keybinding enables preview and letting it go will close the preview window. Just like what holding down the spacebar in File Explorer does using QL. This reduces jumpiness of the previews and not having to close the QL window everytime to see the file blocked by the window. This should be in addition to what I requested earlier.

An additional thing would be to allow third party plugins to use quicklook as well. So, that it is not only limited to explorer plugin. Ignore this if this is already available.
Any improvisations or ideas for this issue will be highly useful to the developer.

Original Issue: [#3](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.QuickLook/issues/3)
### Flow Launcher Version

1.19.2

### Windows Build Number

19045.5011

**Comment by deefrawley** [comment]
Please don't duplicate issues - keep the history and previous discussions in the one place. If you want to alert the dev team, jump on our Discord and discuss there.

**Comment by VictoriousRaptor** [comment]
Thank you for summarizing. I've copied your summary to the original issue so we can continue discussing.
