### ISSUE TITLE
BUG: Flow launcher loosing cursor/text input focus

### ISSUE THREAD

**Issue by MainWire** [Flow-Launcher/Flow.Launcher#3036]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Bug desc :
When using the win shortcut to trigger flow launcher search bar, it sometimes looses focus, and I have to click on the search bar to be able to write. Even if I press win shortcut again, text input won't be focused on the search bar.

### Expected behavior :
- Stop loosing text focus when triggering search bar
- Or take input focus again when closing and reopening

### Ver. details :
- 1.19.2
- Windows 11

### To Reproduce
I haven't found any way to get that bug on purpose but it sometimes happens when using flow launcher

### Plugin list
![image](https://github.com/user-attachments/assets/ae500190-076f-47a1-9634-a34895a270ad)
![image](https://github.com/user-attachments/assets/b2f24afa-a643-4dd8-92bd-9c39b1803c3b)

### Flow Launcher Version

1.19.2

### Windows Build Number

10.0.22631.4169

**Comment by deefrawley** [comment]
This isn't a common issue so may be isolated to your setup. What takes focus instead of Flow?

**Comment by MainWire** [comment]
Any app that was in foreground before the flowlauncher search bar. Should I try to reinstall FL. ? How do I completely clean everything ?

**Comment by deefrawley** [comment]
Is the "Hide Flow when focus is lost" option turned on? Try toggling that

**Comment by taooceros** [comment]
You would need to contact the author in the win short cut plugin. Flow does not provide native win key support (although @jjw24 has an ongoing project on it), so we don't have much to do here.

**Comment by sweco-begertjanvdb** [comment]
just as an FYI I'm also getting this issue.
Worked like a charm when I installed FL, but after my first reboot the window never gets focus when it launches. Very peculiar.
