### ISSUE TITLE
Can you add a clipboard

### ISSUE THREAD

**Issue by STVGecko** [Flow-Launcher/Flow.Launcher#3045]
As spotlight in mac, can you add a clipboard in the app?

![{EA251F30-36BF-4A59-8EAC-BE2E9F62668E}](https://github.com/user-attachments/assets/970eb5c3-922a-46e5-ba8e-551283bee630)

**Comment by deefrawley** [comment]
There are plugins to manage the clipboard. Check the Plugin Store
