### ISSUE TITLE
BUG: I can open batch with it anymore

### ISSUE THREAD

**Issue by 3C0D** [Flow-Launcher/Flow.Launcher#3048]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

I can't find a *.bat in Documents. Then I created a symbolic link(with less depth in folders...) but even this is not found anymore. Recents updates killed it.

### Flow Launcher Version

latest

### Windows Build Number

11111111111111

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by 3C0D** [comment]
uninstalling...

**Comment by deefrawley** [comment]
If you actually want help with this, please provide some detaiil such as version of Flow, if you are using Windows Index or Everything for file search, what you are searching for and what gets displayed versus what you expect.

**Comment by 3C0D** [comment]
last version it's fixed. I was only using it to run script. but for a reason I uninstalled it and the update was still there. So I updated read your comment deefrawley and it's working. I was fed up to loose settings at any update but I guess it's needed. And at least it's working now
