### ISSUE TITLE
BUG: VirusTotal

### ISSUE THREAD

**Issue by coderstarrer** [Flow-Launcher/Flow.Launcher#3051]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I know this has been already reported but i'm checking again as this time its 2 sources reported not 1 and i don't know whether they are trustworthy or not(the antiviruses Zillya and Trapmine)

### To Reproduce

1. ...Go to virustotal.com
2. ...Put the setup.exe
3. ...Scan

### Screenshots

![Screenshot 2024-10-28 184932](https://github.com/user-attachments/assets/5c664e47-e96e-46d9-bd49-3897c57a95eb)

### Flow Launcher Version

1.19.3

### Windows Build Number

Microsoft Windows [Version 10.0.26100.2033]

**Comment by deefrawley** [comment]
Hi. It's still not a trojan and the points in the pinned issue around this are still valid. Thanks for checking
