### ISSUE TITLE
How do I disable this window :: Quick AccessKeyboard Assigned Window

### ISSUE THREAD

**Issue by TheDataSeneschal** [Flow-Launcher/Flow.Launcher#3066]
What is this Quick AccessKeyboard Assigned Window, and how do I stop it from coming up?

![Quick AccessKeyboard](https://github.com/user-attachments/assets/9851ee62-35b4-4f06-a43f-dbf5cbe47ec9)

**Comment by deefrawley** [comment]
Hi. This is part of the Window Walker plugin. If you go to its settings you can change the hotkey or disable this.
