### ISSUE TITLE
System.IO.InvalidDataException: Pytube VideoUnavailable Exception in Youtube Downloader Plugin

### ISSUE THREAD

**Issue by izzroni** [Flow-Launcher/Flow.Launcher#3068]
Flow Launcher version: 1.19.4
OS Version: 22631.4317
IntPtr Length: 8
x64: True

Python Path: C:\Users\ronit\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: (not specified)
Date: 11/11/2024 10:18:11

Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\ronit\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 93, in <module>
    YoutubeDownload()
  ...
[Uploading 2024-11-11.txt…]()

**Comment by deefrawley** [comment]
Hi, can you please raise this in the plugin repo? Thanks.

https://github.com/DeepVoyager253/FlowLauncherYTDownload/issues
