### ISSUE TITLE
BUG: I cannot change the width of the search box

### ISSUE THREAD

**Issue by patrik-martinko** [Flow-Launcher/Flow.Launcher#3077]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The search box became very narrow after updating to the latest version (1.19.4):
![image](https://github.com/user-attachments/assets/6afe5e75-186a-409f-9898-f8f34aa4502c)
I wanted to make it wider, so I changed the Width property in the Theme.xaml file but it didn't help:
![image](https://github.com/user-attachments/assets/c4c86329-391d-4bda-8c21-1bbe90e7deaa)
How can I change the with of the search box back to a normal size?

### Flow Launcher Version

1.19.4

### Windows Build Number

10.0.26100.2314

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by NoPlagiarism** [comment]
Default hotkeys for adjusting window width are `Ctrl [` and `Ctrl ]`

For more hotkeys see `Settings -> Hotkeys -> Hotkey Presets`

**Comment by patrik-martinko** [comment]
Thank you. Resolved.
