### ISSUE TITLE
BUG: Bookmars opening in the wrong browser (not the default one or the configured one)

### ISSUE THREAD

**Issue by Likver** [Flow-Launcher/Flow.Launcher#3078]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

So i made all my bookmarks on a Chromium based browser (Thorium if that matters) and not too long ago decided to test Firefox for multiple reasons, but without uninstalling the other browser i was using.

I already tried restarting Flow and my pc, making Firefox my default browser, imported the bookmarks to Firefox and removed them from the Chromium based browser, making new bookmarks directly from Firefox, configuring the browser bookmarks plugin, adding the data directory path, etc..

None of that worked and when i want to open any bookmark from Flow, it just opens the bookmark on the old browser (the Chromium based one) and i dont want to uninstall it just yet because im still not 100% sure if i will make the switch, but at the same time because i have a lot of configs and stuff i still have to move to Firefox, am i missing something? did i do something wrong?

My Firefox version is 115.17.0esr (64-bit)

### To Reproduce

1. Make a bookmark on a Chromium based browser or just make a new one on Firefox
2. Try to open it on Flow
3. Either it shows up (if made on Chromium based browser) or it doesnt if made on Firefox
4. If it does show up, it will be open in the wrong browser (the non-default one)

### Screenshots

Bookmarks plugin config
![Flow Launcher_n3owUWhMN3](https://github.com/user-attachments/assets/aa950e73-647d-4aff-9652-6df60c25500f)
Bookmark data config
![firefox_L7WnRwGUHE](https://github.com/user-attachments/assets/bfc85ea6-2409-44d6-b150-07e357e0e3f1)
Data directory path
![Flow Launcher_XUoebyeOb8](https://github.com/user-attachments/assets/fc5f5748-06c4-457a-a283-b92e347a025b)
(Yes, that is the correct path of the profile i am currently using in Firefox)

I also tried making the "Data Directory path" directly to the bookmarks folder, same result 

### Flow Launcher Version

1.19.4

### Windows Build Number

6.3.9600

**Comment by deefrawley** [comment]
The Firefox profile path you have there is the location of the places.sqlite file?

**Comment by Likver** [comment]
> Have you tried changing this option in Flow Launcher's settings? ![image](https://private-user-images.githubusercontent.com/3993179/386851166-d19b82ce-7fbd-4209-8a41-83f5c21bc253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0ODk2OTQsIm5iZiI6MTczMjQ4OTM5NCwicGF0aCI6Ii8zOTkzMTc5LzM4Njg1MTE2Ni1kMTliODJjZS03ZmJkLTQyMDktOGE0MS04M2Y1YzIxYmMyNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjRUMjMwMzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU2OGVhY2MwOGRmMDQxM2I2NDZkODUxOGJmZTdmZTZkODE2N2UyYTVlYjdmNmM0Y2EzMDM2ZDUzNzU2YjE0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3i1jtYDIn_SwfUuZ8twyVjSIAY7Ct2ddaBQPJy_RdGs)

i feel so dumb right now... this was it

i completely missed that setting even existed in the general settings tab

**Comment by deefrawley** [comment]
Glad you solved it. Will close the issue.
