### ISSUE TITLE
Set up CI/CD pipeline for Flow

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#31]
- [x] Build pipeline - AppVeyor
- [x]  Deployment pipeline for new releases- See screenshot below

**Comment by jjw24** [comment]
![image](https://user-images.githubusercontent.com/26427004/81117407-627ebd80-8f6a-11ea-8465-92e88dcc97ff.png)

**Comment by taooceros** [comment]
I think this is already done, so close it.
