### ISSUE TITLE
[FEATURE REQUEST] Add dd.MM.yyyy date format to Flow Launcher

### ISSUE THREAD

**Issue by Wuerfelhusten** [Flow-Launcher/Flow.Launcher#3128]
- Add support for dd.MM.yyyy date format.
    - December 14th 2024 = 14.12.2024
    - Widely used in Germany, Austria, Switzerland, and other European countries.
        - Improves usability for European users.

**Comment by Yusyuriv** [comment]
Thank you for the suggestion. These options should be available in the next release.
