### ISSUE TITLE
Plugins Manager check connection message pops up despite manifest loaded

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#313]
@taooceros getting this message occasionally despite plugins manager's manifest is loaded, any idea why?

https://github.com/Flow-Launcher/Flow.Launcher/blob/5dd12d212b57d2c752c09e8539752d1138be326b/Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs#L41-L52

**Comment by jjw24** [comment]
i wonder maybe if the task status is something other than t.IsCompletedSuccessfully

**Comment by taooceros** [comment]
Yeah, I agree with you. I believe this can be solved by using Task.IsFault to invert the condition check. Let me investigate more about completesuccessfully.

**Comment by taooceros** [comment]
hmmm from my testing, I didn't see the message pop out when the manifest is loaded successfully.

**Comment by taooceros** [comment]
@jjw24 Would you please create a breaking point within the continueWith method to check t.IsCompletedSuccessfully, t.IsCompleted, and t.IsFaulted when the error message pop out unexpectly?
Or you can simply check t.Status and check which status it is in.

**Comment by jjw24** [comment]
Yeah I got it writing to log including status, will update if I hit it again, it's quite random

**Comment by taooceros** [comment]
ok, thank you!
