### ISSUE TITLE
BUG: Setting Window Freeze Issue after System Sleeping

### ISSUE THREAD

**Issue by Jack251970** [Flow-Launcher/Flow.Launcher#3139]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When you change the system to sleep mode, and the settings window will possibly freeze.

In `SettingWindows.xaml.cs`,
`
private void OnLoaded(object sender, RoutedEventArgs e)
{
    RefreshMaximizeRestoreButton();
    // Fix (workaround) for  (Win+L)
    // https://stackoverflow.com/questions/4951058/software-rendering-mode-wpf
    HwndSource hwndSource = PresentationSource.FromVisual(this) as HwndSource;
    HwndTarget hwndTarget = hwndSource.CompositionTarget;
    hwndTarget.RenderMode = RenderMode.Default;

    InitializePosition();
}
`
these codes are used for `the window freezes after lock screen`, but it seems that these codes cannot fix the problem when the system goes to the sleep mode.

This is probably the correct reason of the issue of PR #3088.

### To Reproduce

1. Sleep Windows.
2. Start Windows.
3. Open settings window, and the window is frozen.

### Screenshots

https://github.com/user-attachments/assets/faaea9be-83a2-4a4d-8852-65002e242352

When the settings window is frozen, the main window can still work but the right context menu of the search will freeze.

And the `NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)` event in `SettingWindows.xaml.cs` can still be triggered when you click the menu item but the interface will not refresh at all.

### Flow Launcher Version

1.19.4

### Windows Build Number

10.0.22631.4037

**Comment by taooceros** [comment]
I think it's related to the hardware acceleration of WPF. There are some underlying issue of the framework.

**Comment by Jack251970** [comment]
It seems that I cannot find any way to stably reproduce this.
