### ISSUE TITLE
BUG: Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by yuanbi** [Flow-Launcher/Flow.Launcher#3142]
### Problem Description

![image](https://github.com/user-attachments/assets/c1d870f7-1636-40e7-be47-25d7fc326e28)

I tested many settings but couldn't find the reason why the memory usage reaches around 400 MB when I start the software, and then increases to 600 MB after using it for a few hours. Could this problem be causing it?

### Flow Launcher Version

1.19.4

### Windows Build Number

Win11 23H2 22631.4602

### Error Log

14:05:41.5065+08:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
14:05:41.5065+08:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.19.4
OS Version: 22631.4602
IntPtr Length: 8
x64: True
14:05:41.6163+08:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
14:05:44.8211+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <106ms>
14:05:44.8211+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <82ms>
14:05:44.8211+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <127ms>
14:05:44.8211+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <94ms>
14:05:44.8503+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <216ms>
14:05:44.8755+08:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
14:05:44.8858+08:00 - INFO  - BinaryStorage.TryLoad - Cache file not exist, load default data
14:05:44.8858+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <15ms>
14:05:44.8858+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <0>
14:05:44.8858+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <0>
14:05:44.8858+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <364ms>
14:05:45.0081+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:05:45.0472+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <542ms>
14:05:45.0549+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <498ms>
14:05:45.0549+08:00 - INFO  - ImageLoader.Initialize - Preload images cost <1ms>
14:05:45.0726+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <259ms>
14:05:45.1149+08:00 - INFO  - ImageLoader.Initialize - Number of preload images is <2>, Images Number: 2, Unique Items 2
14:05:45.1304+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <400ms>
14:05:45.1547+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:05:45.1547+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:05:45.1547+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
14:05:45.1894+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Visual Studio Launcher> is <489ms>
14:05:45.2146+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <555ms>
14:05:46.8797+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 209 plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:05:46.8943+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <2312ms>
14:05:47.2267+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - UWPProgram index cost <2330ms>
14:05:48.3425+08:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
14:05:49.3553+08:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
14:05:49.3701+08:00 - INFO  - App.OnStartup - Startup cost <8196ms>
14:05:55.1102+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
14:05:55.1102+08:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
14:05:55.1102+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
14:05:55.1467+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
14:05:55.1467+08:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
14:05:55.1467+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
14:05:56.1170+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Win32Program index cost <11061ms>
14:11:08.3289+08:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
14:11:08.3289+08:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.19.4
OS Version: 22631.4602
IntPtr Length: 8
x64: True
14:11:08.5728+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <1ms>
14:11:08.5728+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <2ms>
14:11:08.5728+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <0ms>
14:11:08.5728+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <10ms>
14:11:08.5824+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:11:08.5824+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <21ms>
14:11:08.6088+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <37ms>
14:11:08.6088+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <37ms>
14:11:08.6088+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <42ms>
14:11:08.6151+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <6ms>
14:11:08.6151+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <157>
14:11:08.6151+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <48>
14:11:08.6151+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:11:08.6151+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:11:08.6151+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
14:11:08.6398+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <71ms>
14:11:08.6398+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <74ms>
14:11:08.6398+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <74ms>
14:11:08.6585+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Visual Studio Launcher> is <86ms>
14:11:08.8301+08:00 - INFO  - ImageLoader.Initialize - Preload images cost <249ms>
14:11:08.8355+08:00 - INFO  - ImageLoader.Initialize - Number of preload images is <20>, Images Number: 20, Unique Items 12
14:11:09.3584+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 210 plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
14:11:09.3584+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <791ms>
14:11:09.5889+08:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
14:11:09.8840+08:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
14:11:09.8840+08:00 - INFO  - App.OnStartup - Startup cost <1621ms>

**Comment by Jack251970** [comment]
This error `Error HRESULT E_FAIL has been returned from a call to a COM component` happens normally when it comes to get desc from certain system applications.

As for the memory usage, it could be the cache of the query results. (common in most cases)
