### ISSUE TITLE
BUG: Clicking on a Google Web search Doesn't Do Anything 

### ISSUE THREAD

**Issue by OdyAsh** [Flow-Launcher/Flow.Launcher#3143]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Downloading the latest portable version (1.19.4), when clicking on a Google Web search, nothing happens (I.e., no new tab/window appears). 

Moreover, I tried changing these settings as much as possible, with nothing working except (MS Edge) option, as can be seen in screenshot 1

plugins list is mentioned in screenshot 2

### To Reproduce

1. Use the latest portable version (apparently)

### Screenshots

screenshot 1:

![image](https://github.com/user-attachments/assets/0954714f-ec2c-44a3-8674-2bb8edb23b02)

screenshot 2:

![image](https://github.com/user-attachments/assets/6d734222-c832-4ba0-9e28-c902827f3630)

![image](https://github.com/user-attachments/assets/b41748d1-7c1c-427c-aea4-091a02cebc04)

![image](https://github.com/user-attachments/assets/c9e6eee7-9d1a-43e3-88e8-a56a578930ba)

![image](https://github.com/user-attachments/assets/852ef36f-06f9-4531-b39e-3d7797d1a043)

Pressing enter (or clicking) here doesn't do anything:

![image](https://github.com/user-attachments/assets/0227b642-95dd-412e-bb39-ee6c5586e74c)

Same thing when I remove the "g" action keyword (i.e., replace it with "*"):

![image](https://github.com/user-attachments/assets/b6ea40d1-28bd-46d0-b352-73f4ff691df7)

### Flow Launcher Version

1.19.4

### Windows Build Number

10.0.26100.2605

### Error Log

[2024-12-21.txt](https://github.com/user-attachments/files/18217601/2024-12-21.txt)

**Comment by deefrawley** [comment]
Can you post a screenshot of when you type "g <search phrase>"?

**Comment by OdyAsh** [comment]
Done 👍 (edited above)

**Comment by OdyAsh** [comment]
Fixed it; Had to restart the PC :]

**Comment by deefrawley** [comment]
Glad you got it working. For future reference you can hit F5 to reload all plugins and their settings in Flow, and of course can restart Flow (type Restart Flow in Flow itself) though I'm sure you tried those.
