### ISSUE TITLE
Is it possible to sort Everything query results by date modified?

### ISSUE THREAD

**Issue by thunderousleader10** [Flow-Launcher/Flow.Launcher#317]
How do I sort results by date modified?

I am aware of the dm: functions but the results with this criteria are still sorted by name. I am looking to be able to simply sort the results by most recently modified.

This is easy in the stand-alone Everything app as there are column headers but I can't find how to replicate this in FlowLauncher...

Any ideas?

**Comment by taooceros** [comment]
Yes, it is possible.
So, it is about the everything plugin? If so, maybe you can open an issue on the plugin page.
https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything

**Comment by thunderousleader10** [comment]
Yes the question is about the Everything plugin and I have asked the same question on that page. Could you help me please? thanks!

**Comment by taooceros** [comment]
Close because we shall investigate this more on https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything.
