### ISSUE TITLE
Main window's result list does not collapse

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#347]
hm looks like result list box is not collapsing, ran into this occasionally.

![image](https://user-images.githubusercontent.com/26427004/108036419-504eb580-708c-11eb-90b8-91f4f1baeaf9.png)

@taooceros any ideas? Nothing in the logs, and not sure how to repro reliably yet

**Comment by jjw24** [comment]
removed one letter- 's'
![image](https://user-images.githubusercontent.com/26427004/108037070-29dd4a00-708d-11eb-97be-5c23de36aac6.png)

**Comment by jjw24** [comment]
subsequent results do not fill the entire result list box. This only resets if the activation hot key or esc is pressed

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/108038793-1def7a80-6ff0-11eb-9598-5091b56d94d6.png)
Weird, I didn't get the same result.

**Comment by jjw24** [comment]
Revisit when we can properly repro
