### ISSUE TITLE
A config file for Flow Launcher

### ISSUE THREAD

**Issue by hongyuanjia** [Flow-Launcher/Flow.Launcher#365]
It would be great if Flow Launcher has a config file that describes the plugins installed and other settings. Users can import that file to automatically recover Flow Launcher to the state that they like. This could be very useful when I reinstall Windows on my PC.

Besides a config file, it would be good if Flow Launcher provides some guides on how to backup as an alternative.

BTW, thanks for this great software!

**Comment by taooceros** [comment]
That's a great idea! For now, we don't support plugins recover, but it will be quite possible to backup the config files and user histroy by saving the files lies within %appdata%\FlowLauncher\Settings.

**Comment by jjw24** [comment]
Backing up this entire folder %appdata%\FlowLauncher, would return your flow back to how it was, with the exception of the saved folder and file path maybe incorrect if those locations change.

I think it's a good idea to have a button somewhere to open this data folder location, I will out in an issue for future add.

**Comment by jjw24** [comment]
Documentation for back and restore your settings:
https://flow-launcher.github.io/docs/#/usage-tips

**Comment by hongyuanjia** [comment]
Thanks. Bakcuping `%appdata%\FlowLauncher` works perfectly for me. Feel free to close this issue.

**Comment by taooceros** [comment]
Since that backing up the whole folder should work, I think we don't need something special action to recovery the plugins, right? @jjw24

**Comment by jjw24** [comment]
Nah no need for special action to recover the plugins

**Comment by taooceros** [comment]
> Nah no need for special action to recover the plugins

So close this?😛

**Comment by jjw24** [comment]
Yeah let's close it
