### ISSUE TITLE
Dev branch: PackageManager error

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#366]
@taooceros getting this error after merging to dev. Never experienced it in the PR:

![image](https://user-images.githubusercontent.com/26427004/108905519-e9289680-7673-11eb-8b41-4ce558579705.png)

**Comment by taooceros** [comment]
> @taooceros getting this error after merging to dev. Never experienced it in the PR:
> 
> ![image](https://user-images.githubusercontent.com/26427004/108905519-e9289680-7673-11eb-8b41-4ce558579705.png)
> 

This is the error I mention from CsWinRT. Let me take a look soon.

**Comment by jjw24** [comment]
Yeah I know, but strange I never hit it in the pr, only after merging.

**Comment by taooceros** [comment]
I try to checkout to the pr branch, but the issue still exists. I think CsWinRT has released the fix toward our issue in 5.0.103. Is it possible that their fix makes our issue persistent instead of happening once🤣🤣🤣?

**Comment by taooceros** [comment]
The weird thing is that when the program stop, I can successfully create an instance of package manager in vs (not work in vscode debug console)
![Uploading image.png…]()

**Comment by taooceros** [comment]
I have taken a try on initialize the package manager in the main thread, and no error is thrown.
Maybe this issue is the same as the STA issue of the one in PluginsManager. Let me take a try on that.

**Comment by taooceros** [comment]
No the issue cannot be resolved by STA.....But why do mainthread works as expected?

**Comment by taooceros** [comment]
> @taooceros, this can also occur if there are multiple versions of winrt.runtime.dll loaded in process, each with their own static instance of registration state. Do you have a repro project?

According from @Scottj1s, I have tried publish our project (which will delete duplicate dll), and the issue resolve. Therefore, it will only appears on debug. Let me check if there's any way to remove extra dll refrence.

**Comment by taooceros** [comment]
@jjw24 Is it possible to not load assembly that is already loaded in Flow in pluginLoader?
We don't have any dependency in Flow.Launcher.Plugin except Jetbrain.notation, which I think won't have issue.
![image](https://user-images.githubusercontent.com/45326534/108944671-2bfb6600-7696-11eb-8a6d-4389af9b4cec.png)

**Comment by taooceros** [comment]
I change that to Flow.Launcher.dll, and it works. However, I think it would be better to only not load assembly with the same version.

**Comment by jjw24** [comment]
ok so this problem is from having Microsoft.Windows.SDK.NET.dll output in both parent directory and Program plugin's directory
