### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by m3Lith** [Flow-Launcher/Flow.Launcher#371]
From the time Windows desktop appears after boot, to the time that the launcher input appears, it takes almost 2 minutes.

I guess that's a bit unusual?

Anything I can do to see what's causing this?

**Comment by taooceros** [comment]
Have you installed any plugin? If the programs index hasn't been cached, it may take some time to do that job before startup. However, it shouldn't be as long as 2 minutes.

**Comment by jjw24** [comment]
> Anything I can do to see what's causing this?

You can restart your comp and once Flow has loaded, upload your logs here, we can take a look if any errors or unusual is going on. Having said this, my flow sometimes is last to start up and sometimes takes a minute or two to load after a reboot.

**Comment by m3Lith** [comment]
Hmm, and you haven't figured out what's the problem in your case?

My logs form last startup: https://pastebin.com/sDCP9NUH

**Comment by taooceros** [comment]
> Hmm, and you haven't figured out what's the problem in your case?
> 
> My logs form last startup: https://pastebin.com/sDCP9NUH
> 
> 

I take a look on the log, and the initialization time of most Plugins are a bit longer, but should only takes a few seconds to be done. Therefore, I think the possible reason for the slow startup is the indexing of Program plugin.

@jjw24 should we stop waiting the program plugin indexing if there are existing Win32 & UWP program that is preloaded? (this happens every three day)

**Comment by jjw24** [comment]
> @jjw24 should we stop waiting the program plugin indexing if there are existing Win32 & UWP program that is preloaded? (this happens every three day)

I think it works better if already preloaded (assuming this means exists in cache data) then do not wait, use cache until indexing is finished

**Comment by jjw24** [comment]
> Hmm, and you haven't figured out what's the problem in your case?

I rarely restart my laptop and and usually Flow finishes starting up after the others so I didn't really register it as an issue in my mind.

**Comment by jjw24** [comment]
@m3Lith could you give this build from PR 381 a go and let me know if it's fixed the slow start up issue:
https://ci.appveyor.com/api/buildjobs/gqqmqu2k9bo2ame3/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe

**Comment by m3Lith** [comment]
I don't think it did, still takes a while.. Latest log: https://pastebin.com/GUgurrGy

**Comment by taooceros** [comment]
> I don't think it did, still takes a while.. Latest log: https://pastebin.com/GUgurrGy

@m3Lith how long do you wait until the program startup? As the logs indicates, it takes about 5-10 seconds to do the initialization jobs I think?

**Comment by m3Lith** [comment]
Sure, anything I can do to help: https://pastebin.com/YJgEGRiG

**Comment by taooceros** [comment]
Found the issue, the long startup time is due to the plugin loading (not initialization). Let's investigate it more. 
`2021-03-10 18:34:57.1686|INFO|App.OnStartup| Plugin Load<57120ms>`

**Comment by taooceros** [comment]
https://ci.appveyor.com/api/buildjobs/1w4mnyl93bnaae6h/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe
I move some debug message available, so would you please log again?

**Comment by m3Lith** [comment]
https://pastebin.com/gfDR8Gnm

Regarding AV: no, I don't use anything apart stock Windows 10 security/defender.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/110840966-51b47c00-82e0-11eb-8248-afd544d9def6.png)

Another weird thing I found is that the time has passed for about 1 minutes between loading image and the first loaded time of plugin in log file, but there shouldn't be something that is causing so much time between them.....

**Comment by taooceros** [comment]
@m3Lith Sorry for requiring you to do that again, would you please install this, and log again? https://ci.appveyor.com/api/buildjobs/t62s0wofiqocwgvt/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe

**Comment by m3Lith** [comment]
https://pastebin.com/d8LKz3rc

**Comment by taooceros** [comment]
```
2021-03-11 22:47:01.7726|INFO|ImageLoader.Initialize|Preload images cost <52ms>
2021-03-11 22:47:15.4048|INFO|ImageLoader.Initialize|Number of preload images is <2>, Images Number: 2, Unique Items 2
```

Why do this part consume 15 seconds?

These two logs should appear side by side without any time consuming.
https://github.com/Flow-Launcher/Flow.Launcher/blob/8577dbe3bf73d2707839f2d6c5a913a0d064dc48/Flow.Launcher.Infrastructure/Image/ImageLoader.cs#L49-L58

```
2021-03-11 22:47:19.2800|FATAL|FaultyLogger|Wrong logger message format <Loading plugins manifest start>
2021-03-11 22:47:36.6899|FATAL|FaultyLogger|Wrong logger message format <Loading plugins manifest end>
```
Another thing is that plugin manifest loading cause about 17 seconds.
@jjw24 Is there anything that can cause the loading of plugin.json takes long time?

@m3Lith is your disk a HDD or SSD? Seems that the enumeration of file systems are causing the long start up.

**Comment by m3Lith** [comment]
I have both. System files/programs on an SSD, and most of the media on an HDD.

**Comment by taooceros** [comment]
> I have both. System files/programs on an SSD, and most of the media on an HDD.

If that's the case, the enumeration of file shouldn't be slow... because Flow installer is default installed in %localappdata%\FlowLauncher, which supposed to be in C:.

https://ci.appveyor.com/api/buildjobs/wi890d8pmole6h24/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe

I make a small improvement (move init of BrowserBookmark to initialization instead of loading to allow parallelism, since it seems take long to load based on your log) and add some logs for manifest loading. Would you please do that again?

Thanks!

**Comment by jjw24** [comment]
> @jjw24 Is there anything that can cause the loading of plugin.json takes long time?

@taooceros Could this be the same issue you had previously slow connection to github? @m3Lith do you experience any slowness accessing github?

**Comment by taooceros** [comment]
> > @jjw24 Is there anything that can cause the loading of plugin.json takes long time?
> 
> @taooceros Could this be the same issue you had previously slow connection to github? @m3Lith do you experience any slowness accessing github?

It is not supposed to, because at the time we load plugins' manifest (the plugin.json from each plugin folder), we should not have any internet connection with github. The downloading of pluginsmanifest is done in intialization and the auto update is done after starting up.

**Comment by jjw24** [comment]
Oh sorry I misread your question, for some reason I was thinking PluginsManager. I am not aware of anything that could cause the slowness in loading plugin.json

**Comment by m3Lith** [comment]
Latest logs: https://pastebin.com/5Wj6FiVA

I have also noticed that the first entry in the logs is already about ~30s delayed after I login to desktop (I measured it with clock). So where it says `Startup cost <25933ms>`, in reality it's 2x that - can some other processes be blocking the init/startup?

**Comment by taooceros** [comment]
> Latest logs: https://pastebin.com/5Wj6FiVA
> 
> I have also noticed that the first entry in the logs is already about ~30s delayed after I login to desktop (I measured it with clock). So where it says `Startup cost <25933ms>`, in reality it's 2x that - can some other processes be blocking the init/startup?

I didn't restart my computer frequently, so I just check the log of Flow, and it takes `2021-03-17 08:20:37.9669|INFO|App.OnStartup|Startup cost <14363ms>` which seems long. So, I would like to ask whether this only appears on the first startup after rebooting or it is slow for every startup. Seems that I haven't noticed that rebooting can cause behavior different.

**Comment by taooceros** [comment]
> I have also noticed that the first entry in the logs is already about ~30s delayed after I login to desktop (I measured it with clock). 

Is possible that you have quite a lot startup application to do, and Flow is queued at the end so that it needs to wait for other application startup and then startup? I am not sure how windows handle auto startup……so not sure whether my assumption is right or not😂.

**Comment by jjw24** [comment]
Maybe to get accurate result, you need to test this on a vanilla windows environment, @m3Lith do you know how to boot up Windows Sandbox? You can do the test there that will give us a accurate baseline to work with

**Comment by jjw24** [comment]
Sorry if you have already mentioned this, is there a big difference between the start up time for a restarting computer and just restarting flow?

**Comment by m3Lith** [comment]
> So, I would like to ask whether this only appears on the first startup after rebooting or it is slow for every startup.
> is there a big difference between the start up time for a restarting computer and just restarting flow?
Only after the PC reboot. If I manually quite and launch flow again, it starts in a few seconds.

> do you know how to boot up Windows Sandbox? You can do the test there that will give us a accurate baseline to work with
I'll try that.

**Comment by m3Lith** [comment]
Okay, so I guess you can't emulate a reboot cycle on Windows Sandbox? I've tried it and it just exits completely. Otherwise, the normal Flow startup is fast, but it's also fast on mine.

I guess I'll try experimenting with disabling other startup programs..

**Comment by taooceros** [comment]
https://github.com/nushell/nushell/issues/4050 is this possible related to the slow startup?

**Comment by jjw24** [comment]
Are u referring to cert signing part in that issue?

**Comment by jjw24** [comment]
This still a problem?

**Comment by m3Lith** [comment]
No, it has been fine for quite a while. Closing.
