### ISSUE TITLE
Format issue for Plugin Directory

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#375]
![image](https://user-images.githubusercontent.com/45326534/109500484-476cd380-7ad1-11eb-8f19-c95154aebcbc.png)

We should align this with more compatible way.

**Comment by jjw24** [comment]
Seems less affected with current prd release, could this due to the .Net 5 upgrade?

**Comment by taooceros** [comment]
> Seems less affected with current prd release, could this due to the .Net 5 upgrade?

Not sure, will check that out later.
