### ISSUE TITLE
Add command to view installation error logs.

### ISSUE THREAD

**Issue by jeremymeyers** [Flow-Launcher/Flow.Launcher#379]
Getting this error on startup (will create separate reports for them), but having a 'pm open errorlog' or something would be helpful since there is otherwise no indication of where the logs reside or what they are called.
![Screenshot 2021-03-05 12 54 03](https://user-images.githubusercontent.com/3514095/110154618-74abd100-7db2-11eb-8024-95ac8ef29c9b.png)

**Comment by taooceros** [comment]
> Getting this error on startup (will create separate reports for them), but having a 'pm open errorlog' or something would be helpful since there is otherwise no indication of where the logs reside or what they are called.
> ![Screenshot 2021-03-05 12 54 03](https://user-images.githubusercontent.com/3514095/110154618-74abd100-7db2-11eb-8024-95ac8ef29c9b.png)
> 

Good idea. I also sometimes feel messy to find the log place.
This error means that the plugin cannot be loaded. (probably because it is a wox plugin?)

**Comment by jeremymeyers** [comment]
They are both the Flow versions as ported by @jjw24 ..

**Comment by jeremymeyers** [comment]
@taooceros where are the error logs, precisely?

**Comment by taooceros** [comment]
%appdata%\flowlauncher\FlowLauncher\Logs

**Comment by jjw24** [comment]
thats strange, they have been loading for me. Let me know if this is still an issue.

**Comment by jeremymeyers** [comment]
@jjw24 is an issue, and nothing has been updated, so still an issue.

**Comment by jeremymeyers** [comment]
@jjw24 updated ticket with error log

**Comment by jjw24** [comment]
@jeremymeyers can you upload the log, I don't see it in the issue.

**Comment by jeremymeyers** [comment]
@jjw24 https://github.com/jjw24/Wox.Plugin.Todoist/issues/2
