### ISSUE TITLE
Does the flow launcher web search plugin support url schemes from other applications? 

### ISSUE THREAD

**Issue by Warden20** [Flow-Launcher/Flow.Launcher#385]
Does the flow launcher web search plugin support url schemes from other applications? 
I am trying to use the url scheme of the obsidian program through the web search plugin (www.obsidian.md). When I use it with flow launcher it works, it opens the program and performs the action, but the problem is that it leaves my internet browser open. Try to do the same with Ueli and it manages to do the action without opening the browser. My question is the plugin supports url schemes from other applications or what happens?

**Comment by taooceros** [comment]
#214 change the way to access the link to default browser, so the answer is if you can access the link with your browser, it will work, though the browser won't close.

**Comment by jjw24** [comment]
![image](https://user-images.githubusercontent.com/26427004/111080933-fdfe9880-8554-11eb-881b-5a9ce8964044.png)

This is a typo, this PR 386 is not related to this issue.

**Comment by jjw24** [comment]
hey @Warden20 , not quite understand what you mean by 'support url schemes from other applications'. The link is opened by flow fine with the default browser. 

For my understanding also, how does Ueli 'manages to do the action without opening the browser'?

**Comment by jjw24** [comment]
Closing, the functionality is working/needs further explaination. Feel free to reopen for further discussion if required.
