### ISSUE TITLE
Migrate Direct call to PluginJsonStorage to API.save()

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#388]

**Comment by taooceros** [comment]
We haven't finish this part, actually 😂.

**Comment by jjw24** [comment]
Oh ok, I thought this is for allowing calling save function via api which is implemented right

**Comment by taooceros** [comment]
> Oh ok, I thought this is for allowing calling save function via api which is implemented right

No, this should move original direct use for JsonStorge for internal plugin to API.save
