### ISSUE TITLE
Flow.Launcher.Plugin.DirectTranslate plugin migrated

### ISSUE THREAD

**Issue by Drimix20** [Flow-Launcher/Flow.Launcher#392]
I've updated and migrated DirectTranslate plugin (original one is https://github.com/RomanKornev/Translate). It supports more languages than currently existing translating plugins.

Source of the migrated plugin is there https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate. I would like to register this plugin as available plugin for Flow Launcher.

Thank you.

Drimix20

**Comment by taooceros** [comment]
Thank you so much for porting the plugin!
Would you please follow the instruction in https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest to create pr and update the plugin manifest there.

**Comment by taooceros** [comment]
@Drimix20 I have checked the repo and it seems really good! Would you please wrap the whole repo into a zip file and create a release with it?

By the way, I notice that there is a typo in the requirement.txt.txt, which should be requirement.txt actually.

**Comment by Drimix20** [comment]
> 
> 
> @Drimix20 I have checked the repo and it seems really good! Would you please wrap the whole repo into a zip file and create a release with it?
> 
> By the way, I notice that there is a typo in the requirement.txt.txt, which should be requirement.txt actually.

Thank you for review. I fixed typo and released 1.0.0 version.

**Comment by Drimix20** [comment]
> 
> 
> Thank you so much for porting the plugin!
> Would you please follow the instruction in https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest to create pr and update the plugin manifest there.

Thank you. I created pull request into Flow.Launcher.PluginsManifest repository https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/41 as you mentioned.

**Comment by taooceros** [comment]
Merged it, thanks!
