### ISSUE TITLE
Score bump with query

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#394]
Currently the score bumping is based on the selection of a certain result. However, I would think it would be better to only bump score when not only the result has been matched, but also the query has been match.
This will help users to separate the use of query for different high score results that both can be matched with separated query.

For example, I have a program named WeiXin: Wechat, and another one named Windows Terminal. When I want WeiXin with wx, it will be fine, but when I want Windows Terminal with acronym wt, it will sometimes move Weixin higher than Windows Terminal.

**Comment by jjw24** [comment]
Yes agree

**Comment by jjw24** [comment]
Just to clarify, essentially you are saying only apply the score bump when not only the result has been matched, but also the query has been matched, right?

**Comment by taooceros** [comment]
> Just to clarify, essentially you are saying only apply the score bump when not only the result has been matched, but also the query has been matched, right?

Yes
