### ISSUE TITLE
Test Plugin Compatibility before Release 1.8.0

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#397]
We may need to test the compatibiltiy with numerous plugin before release, as well as whether the new JsonStorageAPI works as intended for the IPublicAPI.

**Comment by jjw24** [comment]
Yep. I know Everything plugin and one other one won't be compatible. Any plugins that embedded the infra dll basically.

**Comment by jjw24** [comment]
We will need to make flow itself compatible if possible with these plugins though, because the plugin load will fail and user won't even be able to update.

**Comment by jjw24** [comment]
tested most c# plugins and all python plugins. all good
