### ISSUE TITLE
Everything "voidtools"

### ISSUE THREAD

**Issue by mragtronx8** [Flow-Launcher/Flow.Launcher#399]
everything "https://www.voidtools.com/" search indexing support

**Comment by taooceros** [comment]
We do have an everything plugin. You can install it via `pm install everything`.

By the way, what do you think is lacking in the explorer plugin which provides similar functionality based on windows index?

**Comment by mragtronx8** [comment]
hi taooceros
am new to this
please advice how to install everything plugin, and please advise how to search other volumes beside C drive

**Comment by taooceros** [comment]
> hi taooceros
> am new to this
> please advice how to install everything plugin, and please advise how to search other volumes beside C drive

Hi, just type `pm install everything` in the flow query windows, and hit enter, and it will prompt you to install it.

I think you may need to include specific path in the windows search that is not included. I believe it only index a few document location likes Document or Download by default.

**Comment by mragtronx8** [comment]
thanx.
Please may i ask when r u going to release version 1.8

am currently using listary
does flow has "find as you type" feature

**Comment by taooceros** [comment]
> thanx.
> Please may i ask when r u going to release version 1.8

I am not sure about the release date for 1.8.0, but most major changes have been merged, so after we finish some last part of the code and finish testing, it will be available. Are you expecting any feature that may be released in 1.8.0?
And actually, the current everything plugin won't work for version 1.8.0 because some dependency change that has been used for everything plugin, and we will fix that after the releases of the new plugin interface and api.


> am currently using listary
> does flow has "find as you type" feature

Well, if you mean finds any files via typing, everything plugin will be the one you want, since the windows index are not expected to include everything.

**Comment by taooceros** [comment]
The plugin page for everything plugin.
https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything

**Comment by mragtronx8** [comment]
thanx alot :)

for version 1.8.0, i was wishing to have the feature "FIND as you TYPE" from Listary App.
This feature is very handy.
also i was searching for a launcher that has a feature to have FAVOURITE Folders/Files List, that can be accessed from anywhere in windows.

**Comment by taooceros** [comment]
> thanx alot :)
> 
> for version 1.8.0, i was wishing to have the feature "FIND as you TYPE" from Listary App.
> This feature is very handy.
> also i was searching for a launcher that has a feature to have FAVOURITE Folders/Files List, that can be accessed from anywhere in windows.
> 

I guess for find as you type, you don't have to wait the 1.8.0, but instead try using the everything plugin.

For the second one, we do have that supported with the Explorer plugin, which is already included in Flow. You can check that out by going to the Explorer plugin setting page and checkout quick access link and add your favorite files or folder.

**Comment by taooceros** [comment]
Do you have any other question? If no, could I close it? @mragtronx8

**Comment by mragtronx8** [comment]
:)
