### ISSUE TITLE
New logo for Flow Launcher

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#4]

**Comment by Kalaschnik** [comment]
I was playing around with Illustrator earlier this day (ignore the Edge logo in it, I just like the color theme)... maybe this one possible direction?  However, not sure if it is salient for people to recognize that the L in FL is mirrored F⅃. Could be easily confused with a J. 

![image](https://user-images.githubusercontent.com/9831678/79977814-25f98f00-849f-11ea-8866-24a96cc7ae25.png)

**Comment by jjw24** [comment]
Love it, you are a legend! The color scheme is on point. I like the first one too, I can see what you mean with the 'L' but what draws me to it is that it sort of flows back around all connected. Looks like a water drop.

Or I think the 'fl' below the edge logo is pretty good as well.

**Comment by Kalaschnik** [comment]
Thank you, I had some "flowyness" in mind while doing the first. Typographically, "fl" forms also a ligature, maybe this can also be used. I can up with some other stuff on the weekend.

**Comment by SysC0mp** [comment]
These logos look awesome!

**Comment by JohnTheGr8** [comment]
@Kalaschnik any progress on these?

**Comment by Kalaschnik** [comment]
@JohnTheGr8 had some busy last week, I’ll continue on the weekend / polish the existing one, and will post it here.

**Comment by JohnTheGr8** [comment]
@Kalaschnik awesome, thank you

**Comment by Kalaschnik** [comment]
Sorry folks that it took a while. I just created a PR. The logos (svg, png, and the resource illustrator file love in the `Doc/Logo/` directory. Here is a preview:

![image](https://user-images.githubusercontent.com/9831678/85008739-a82fc800-b15d-11ea-96d2-6a605eb3727e.png)

**Comment by Kalaschnik** [comment]
Let me if you need other formats or design variations — I also added some logo variation (only in the `preview.pdf`) which you can find here: https://github.com/Flow-Launcher/Flow.Launcher/blob/fc2cf51b1f0177bb6726d831c9b5b9e48a33593f/Doc/Logo/preview.pdf

**Comment by JohnTheGr8** [comment]
> 
> 
> Let me if you need other formats or design variations — I also added some logo variation (only in the `preview.pdf`) which you can find here: https://github.com/Flow-Launcher/Flow.Launcher/blob/fc2cf51b1f0177bb6726d831c9b5b9e48a33593f/Doc/Logo/preview.pdf

Hey - do you suggest that we use the first (more square as you say) logo variation for icons? (if so, we will need it in .ico and .png)

**Comment by Kalaschnik** [comment]
Sure. We should, however, be consistent with the use of logos, imo. So, if we go for the squre version, I would not use the the rotated one seen above. What do you think?

**Comment by jjw24** [comment]
> Sure. We should, however, be consistent with the use of logos, imo. So, if we go for the square version, I would not use the rotated one at other places seen above.
> 
> [UPDATE]
> The more I look at the square version the more I like it. I also update the the square version so it is is actually a perfect square... What do you think? Shall we go for square?
> ![image](https://user-images.githubusercontent.com/9831678/85053429-c49e2580-b19a-11ea-8149-602349ddcb5f.png)
> 
> What formats and size are required for the project? A preliminary list:
> 
> * ico (w/ embedded sizes 32, 64, 128, 256, 512)
> * png (256 & 512)
> * svg
> 
> anything else?

Hey, i am not too across how logos are done. I would say a suitable size for a splash screen should we need one in the future, and a suitable one for putting on the readme.

**Comment by jjw24** [comment]
I am ok with the 'more squre' or the tear drop. I cant really 100% square because it may confuse with J but i can settle for either. So up to you guys.

**Comment by JohnTheGr8** [comment]
> 
> 
> I am ok with the 'more square' or the tear drop. I cant really 100% say yes to square because it may confuse with J but i can settle for either one. So up to you guys.

Most people will either overlook the fact that it looks like a J or get a bit confused for a second and never think about it again. (my guess, anyway)

I have a feeling the teardrop will not look very good in small size, for example in the tray etc. So I'm leaning towards the square one as well.

@Kalaschnik if you can create the formats you listed, we can quickly add the icon to the project and see how it looks...

**Comment by jjw24** [comment]
hey @Kalaschnik is #76 continuation of #69? All changes are in #76 and we can close #69?

**Comment by Kalaschnik** [comment]
Correct, I just closed #69. #76 are all new files.

**Comment by Kalaschnik** [comment]
![image](https://user-images.githubusercontent.com/9831678/85662690-816f1580-b6b8-11ea-8733-69c1100744e9.png)

I just created a fresh #81 — However, @jjw24 suggested for the error state just to use a frowning face... or maybe sort of both:
![image](https://user-images.githubusercontent.com/9831678/85663552-82ed0d80-b6b9-11ea-8e41-031492cf4564.png)

@Flow-Launcher/team — what do you think?

**Comment by jjw24** [comment]
> ![image](https://user-images.githubusercontent.com/9831678/85662690-816f1580-b6b8-11ea-8733-69c1100744e9.png)
> 
> I just created a fresh #81 — However, @jjw24 suggested for the error state just to use a frowning face... or maybe sort of both:
> ![image](https://user-images.githubusercontent.com/9831678/85663552-82ed0d80-b6b9-11ea-8e41-031492cf4564.png)
> 
> @Flow-Launcher/team — what do you think?

Hey @Kalaschnik frowning face + logo in the background looks good :) could you commit this image to the current pr #81 please, i will update it for the launcher to use.

**Comment by Kalaschnik** [comment]
@jjw24 done.
