### ISSUE TITLE
Dev branch: PR398 resets user selected records

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#402]
Hey @taooceros just realised #398 resets user selected records and maybe top most record too:

![image](https://user-images.githubusercontent.com/26427004/114322077-a8bca380-9b61-11eb-99a0-2c9f7c0c8a82.png)

Any way we can migrate them across to hash code?

**Comment by taooceros** [comment]
hmmm I do think that we can migrate it. However, I guess PR 398 is going to change the selected record query based? How shall we deal with the not exist query on the previous record?

Do you think it will be useful to keep a legacy record, and remove it after a few version?

**Comment by jjw24** [comment]
what about loading the old record then hash it and save it as the new record used by PR389. and make a todo comment to remove it in the later version

**Comment by taooceros** [comment]
Yeah that makes sense. However, how should we dealing with the query for the old one? The new one create hash based on both query and results title, so if query is not present, the hashcode won't be the matched for anything.

**Comment by jjw24** [comment]
I suppose just bring across what we can, whatever that doesn't match, dont think we can do anything about, what do you think?

**Comment by taooceros** [comment]
> I suppose just bring across what we can, whatever that doesn't match, dont think we can do anything about, what do you think?

Yeah I guess we can keep the old one as well, so that users can creates some records on the new one, and after a few version, we can remove the old one.
