### ISSUE TITLE
Shell plugin cmd history does not get saved

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#403]
Shell plugin cmd history does not get saved. Currently it seems only saved in memory, once flow exists, history is lost.

Fix to save to json file.

**Comment by taooceros** [comment]
Just to clarify, are to talking about the selected history?

I guess it will be hard for people to remember the keyword for the selected history (I forget it now 😂)

**Comment by jjw24** [comment]
nah, just cmd history, what's been ran before:
![image](https://user-images.githubusercontent.com/26427004/114337877-4aa9b380-9b95-11eb-938b-4ff08918cfc1.png)

**Comment by taooceros** [comment]
Got you

**Comment by jjw24** [comment]
lol just realised i meant shell plugin not sys plugin. Will update the PR details
