### ISSUE TITLE
Should we hide 'Should Use Pinyin' option for non-Chinese language display?

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#405]
'Should Use Pinyin' option is for Chinese users intending to search with Pinyin.

To avoid confusion for non-Chinese language users, should this be hidden and only show when Chinese is selected as the display language?

![image](https://user-images.githubusercontent.com/26427004/114360130-0aa7f800-9bb8-11eb-8d6b-2466a354fe1f.png)

**Comment by taooceros** [comment]
hmmm I guess no? I guess there are still people who would like to display in English but want to use the pinyin feature.

**Comment by jjw24** [comment]
Fair point, perhaps put a tooltip to explain what it is

**Comment by taooceros** [comment]
even someone is confused about the option, open it won't have side effect except for a slightly slower search

**Comment by taooceros** [comment]
> Fair point, perhaps put a tooltip to explain what it is

That seems great
