### ISSUE TITLE
Dev branch: Error- Operation not legal 

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#406]
Have been getting this error three times with the Bookmarks plugin dll loading during start up. This new one with Mages dll.

![image](https://user-images.githubusercontent.com/26427004/114361215-37a8da80-9bb9-11eb-92bc-e9b922a1b929.png)

All instances however is intermittent and goes away with a restart of flow.

**Comment by taooceros** [comment]
I have also got the similar issue. It doesn't happen every time restarting flow.

**Comment by taooceros** [comment]
I guess this can be due to the dynamic assembly loading within the plugin initialization process, which will result in a enumeration to the stored loaded assembly, leading to the enumeration error.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/114363588-1f31c380-9bab-11eb-996a-0e411b512930.png)
We have used a linq option here to check, I guess change that to an opeation that can be concurrently access will resolve this issue.

**Comment by taooceros** [comment]
I guess using a hashset will be better this situation. Simply checking contains the fullname of the assembly is what we are doing here, so we don't need to store the whole assembly object.

However, the concurrentHashSet is on the future path, so what do you think will be better, ConcurrentDictionary or a lock machism? @jjw24

**Comment by jjw24** [comment]
ConcurrentDictionary please :)
