### ISSUE TITLE
Hide hotkey text when title is too long

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#41]
Hide hotkey text from displaying when title is too long (or some other means), otherwise looks like a mess

![image](https://user-images.githubusercontent.com/26427004/81389175-c4067e00-915c-11ea-8a1a-50e5c38ee701.png)

**Comment by deefrawley** [comment]
@jjw24 - is this done and can we close? I don't see hotkeys in results for current version.

**Comment by onesounds** [comment]
Fixed with a layout fix.
