### ISSUE TITLE
Fix ci hanging on md file changes

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#428]
AppVeyor ci build hangs when only changes are MD files

**Comment by JohnTheGr8** [comment]
We have configured AppVeyor [to skip commits that only change markdown files](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/appveyor.yml#L17), because building those isn't really necessary... Is this an issue?

**Comment by jjw24** [comment]
Yeah I think it is still an issue, will test later

**Comment by jjw24** [comment]
nop still no good 
![image](https://user-images.githubusercontent.com/26427004/118892562-69455c00-b944-11eb-8ccd-711cbf26e617.png)

**Comment by jjw24** [comment]
![image](https://user-images.githubusercontent.com/26427004/118892607-81b57680-b944-11eb-82b6-a7c3b773049a.png)

**Comment by JohnTheGr8** [comment]
I knew what you meant, you didn't need to test it... This is more or less expected behavior, AppVeyor never starts a build for these commits, and Github waits for a build success notification that never comes.

If you feel this is a big annoyance, we can remove the lines I mentioned earlier from `appveyor.yml`... Or you can use your superpowers to force merge such PRs, they only come once in a while anyway...

**Comment by jjw24** [comment]
If we remove that line, AppVeyor will build for md changes and return a status?

**Comment by jjw24** [comment]
Let's do that

**Comment by taooceros** [comment]
Is it possible to simply return success when only md is changed is appveyor?

**Comment by JohnTheGr8** [comment]
> 
> 
> Is it possible to simply return success when only md is changed is appveyor?

Seems like there is no standard way to do that, no.

> 
> 
> Let's do that

In my opinion this is a minor annoyance that happens rarely enough that it can be overlooked... it only affects PRs whose last commit changes markdown files only. By removing the skip of such commits, we will be stressing a free service unnecessarily on every commit that simply changes the Readme, etc. I think it's a small price to pay...

**Comment by jjw24** [comment]
yeah that's fine

**Comment by taooceros** [comment]
We can do something like this.
https://github.com/appveyor/ci/issues/1848#issuecomment-712738861

**Comment by deefrawley** [comment]
Old issue with many CI updates since. If still a problem reopen.
