### ISSUE TITLE
Option to Turn Off App Descriptions in Result List

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#430]
Please implement this feature as it's badly needed. 

**THE PROBLEM**: In current state, Flow Launcher is pulling the Description of all apps/shortcuts into the results field.  This is really _unnecessary_ as power users tend to name their shortcuts appropriately. It clutters up the results list, makes it more difficult to read & identify the needed app.   I try to avoid comparing Flow Launcher to other apps, but most apps don't append additional text to the end.

![image](https://user-images.githubusercontent.com/1836362/118591092-7271d580-b758-11eb-8ec3-78c62938e8fa.png)
![image](https://user-images.githubusercontent.com/1836362/118591527-283d2400-b759-11eb-9957-90b9aa8e41b7.png)

![image](https://user-images.githubusercontent.com/1836362/118591190-a1884700-b758-11eb-99ee-212a1a86510a.png)

**THE SOLUTION**

Give the user the option of turning this off as few may like it, especially newer users.
![image](https://user-images.githubusercontent.com/1836362/118591436-0643a180-b759-11eb-9086-5f127f823822.png)

Once turned off, the results will display like this: 
![image](https://user-images.githubusercontent.com/1836362/118591721-8407ad00-b759-11eb-9331-e0227eedb317.png)

**Comment by mochigithub** [comment]
This is **HANDS DOWN** the most badly needed feature in Flow Launcher.   Any developers monitoring this, please please consider this for next release.

**Comment by jjw24** [comment]
The program plugin does the search on the app description as well, when switched off, do we still want to do the description search and just not append description to title results or switch off completely including the description search?

**Comment by taooceros** [comment]
> The program plugin does the search on the app description as well, so when the option is switched off, do we still want to do the description search and just not append description to title results or switch off completely including the description search?

I would consider to remove the description search if we want to do that.

**Comment by mochigithub** [comment]
> The program plugin does the search on the app description as well, so when the option is switched off, do we still want to do the description search and just not append description to title results or switch off completely including the description search?

Yes, absolutely the setting for searching the description should also be disabled if the display is disabled.
