### ISSUE TITLE
Multiple UX/UI enhancements to WebSearch 1.3.2

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#431]
![image](https://user-images.githubusercontent.com/1836362/118592133-4fe0bc00-b75a-11eb-9e17-1cefe70405d3.png)

**3 IMPORTANT UX/UI IMPROVEMENTS NEEDED**
1) Add Column for the "Title" of the web search
2) Be able to double click an entry to edit it.  Right click menu to edit should be considered as well but double click is absolutely critical as standard human interface design
3) Be able to click on the column to sort by that column

4) [Optional] If DuckDuckGo search suggestions are available, people might appreciate the extra privacy...

**Comment by taooceros** [comment]
Thank you for providing the idea of improvement!

> Add Column for the "Title" of the web search
> Be able to double click an entry to edit it. Right click menu to edit should be considered as well but double click is absolutely critical as standard human interface design
> Be able to click on the column to sort by that column

I will take a look on them after finishing current work. The first one will be easy, but not sure for the later two.

> [Optional] If DuckDuckGo search suggestions are available, people might appreciate the extra privacy...

I have no idea about DuckDuckGo's api about search suggestion. Contribution is welcome!

**Comment by mochigithub** [comment]
> Thank you for providing the idea of improvement!
> 
> > Add Column for the "Title" of the web search
> > Be able to double click an entry to edit it. Right click menu to edit should be considered as well but double click is absolutely critical as standard human interface design
> > Be able to click on the column to sort by that column
> 
> I will take a look on them after finishing current work. The first one will be easy, but not sure for the later two.
> 
> > [Optional] If DuckDuckGo search suggestions are available, people might appreciate the extra privacy...
> 
> I have no idea about DuckDuckGo's api about search suggestion. Contribution is welcome!


If you want to prioritize the issues based on my vaaaast experience:
1. Add sort option. This is badly needed
2. Add column for the "Title" of the web search
3. Double click option is very important
4. Right click is EXTRA.  Do not focus on this
5. DuckDuckGo is EXTRA. Do not focus on this.

**Comment by lemonnuggets** [comment]
> > [Optional] If DuckDuckGo search suggestions are available, people might appreciate the extra privacy...
> 
> I have no idea about DuckDuckGo's api about search suggestion. Contribution is welcome!
]
https://github.com/philc/vimium/blob/master/background_scripts/completion_engines.js

In vimium they use a bunch of search engines that the user can choose between for search suggestions. In this file is where they define the endpoints they use for getting the search suggestions. Is this what you're looking for when referring to the DuckDuckGo api for search suggestions? I think you'll find the endpoints for a few more services on here as well.

**Comment by taooceros** [comment]
Sure, check out the files under this directory https://github.com/Flow-Launcher/Flow.Launcher/tree/dev/Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources.

**Comment by taooceros** [comment]
Also remember to add it here https://github.com/Flow-Launcher/Flow.Launcher/blob/f160f3c7ab1573dc48c47ab3c3874c393ea4881c/Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs#L197-L201

**Comment by lemonnuggets** [comment]
Okay thanks. I'll see what I can do.
