### ISSUE TITLE
Portable installation support for Everything & Bookmarks  Plugins?

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#434]
Everything v1.4.9 plugin
Browser Bookmarks  v1.3.2
Flow  v1.7.2

This could be operator error, but is there support for **portable** installation support for  Chrome and Everything installs?  None of my bookmarks or Everything seem to be working.  For Everything, portable would mean no service installed.

![image](https://user-images.githubusercontent.com/1836362/118593913-5f153900-b75d-11eb-8fba-07f16e37b070.png)

![image](https://user-images.githubusercontent.com/1836362/118593914-60defc80-b75d-11eb-9c17-ac572cf7f974.png)

**Comment by jjw24** [comment]
Hey how's it going. Currently both don't support portable version. 

If I remmeber correctly, bookmarks plugin has a hard coded chrome database path, so to support portable we can expose that path.

For everything portable, I think should be able to support it with some sort of workaround I read somewhere which may also work with Flow, if not probably can also update it to.

Good suggestions

**Comment by mochigithub** [comment]
> Hey how's it going. Currently both don't support portable version.
> 
> If I remmeber correctly, bookmarks plugin has a hard coded chrome database path, so to support portable we can expose that path.
> 
> For everything portable, I think should be able to support it with some sort of workaround I read somewhere which may also work with Flow, if not probably can also update it to.
> 
> Good suggestions

Hello Jeremy! @jjw24    Going well, thanks for asking. How are you?

1. For the Google Chrome portable support, this is where my Google Chrome Portable install lives: D:\Applications\Chrome\
In the folder has: 
![image](https://user-images.githubusercontent.com/1836362/118766349-26df2a80-b831-11eb-987c-2e3bea0b73c8.png)

I tried setting different folders and couldn't get to it work.  Any suggestions on which folder/app to point it to?
![image](https://user-images.githubusercontent.com/1836362/118766413-3ceceb00-b831-11eb-9908-bd498646a24b.png)


2. For everything portable, please let me know if there's any workarounds you want me to try.  This is honestly more important to me than item  one in this list.

**Comment by taooceros** [comment]
Hey, here's how's going.
> For the Google Chrome portable support, this is where my Google Chrome Portable install lives: D:\Applications\Chrome
In the folder has:

This path is only use for changing the browser path when trying to opening url. There's no association for it with the bookmark. We don't have the feature for portable browsers for now. Maybe in the future, we can add a place to add custom browser path for searching bookmark.

> For everything portable, please let me know if there's any workarounds you want me to try. This is honestly more important to me than item one in this list.

I think everything portable should work? If the everything's service is available, you are able to use the everything plugin. I don't think portable matters. 
What's the current behavior for now? Do everything plugin shows "everything service is not available" even you have started the portable everything?

**Comment by mochigithub** [comment]
You're right I think Everything portable works, but only if service is turned on.  Is there no way to not run service and have it work with Flow Launcher?

**Comment by taooceros** [comment]
> You're right I think Everything portable works, but only if service is turned on.  Is there no way to not run service and have it work with Flow Launcher?

No, it depends on it.

**Comment by mochigithub** [comment]
> > You're right I think Everything portable works, but only if service is turned on.  Is there no way to not run service and have it work with Flow Launcher?
> 
> No, it depends on it.

That explains it then. I'll just have to run everything service.
