### ISSUE TITLE
Prioritizing  Program Entries in Results

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#435]
Somewhere on the site/documentation I read there's a way to prioritize certain plugins' results over others.

For example: I want Program plugin's results **ALWAYS**  prioritized at the top over Everything plugin's results. Wouldn't it be nice if one could drag the plugin above that one indicating your results will mimic the order of the plugins! 

EDIT: I know about the CTRL + O entry to move to top but I'm looking for a more global solution way to prioritize the results of ENTIRE plugins.
![image](https://user-images.githubusercontent.com/1836362/118612662-da351a00-b772-11eb-8e6d-8f81fbd99dda.png)

**Comment by taooceros** [comment]
Check the priority option in plugin pages. Higher priority will bump the result of specific plugin. I am afk now, so I am not able to provide picture now.

I will reach out after I have my computer.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/118656560-35234b80-b81d-11eb-8007-4c22fef9dcc7.png)

**Comment by mochigithub** [comment]
Thank you so much!!!  I never noticed this so I am incredibly relieved.

**Comment by taooceros** [comment]
> Thank you so much!!! I never noticed this so I am incredibly relieved.

No Problem. I agree that this feature may not look obvious. Maybe we need to update the document later?

**Comment by mochigithub** [comment]
@taooceros   I put in a request to adjust the design. See my new post.  At the minimum, should be included in documentation, but this feature is so important for people to know about, I recommend the option be a bit more obvious. See here:
