### ISSUE TITLE
MULTI MONITOR REQ: Launch Flow Launcher on monitor where cursor is

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#448]
Listary did this and I really miss it!

It will check where the cursor is (which monitor) and when hotkey is pressed, it will launch the Flow Launcher window there.

**Comment by taooceros** [comment]
I do think flow has this feature. It will check the current focus (not really the cursor is) and open the window there. It works fine for me.

**Comment by mochigithub** [comment]
> I do think flow has this feature. It will check the current focus (not really the cursor is) and open the window there.

Is it a setting or something I  might have missed. Dual 27" here and it doesn't do for either focused window or mouse

**Comment by taooceros** [comment]
> > I do think flow has this feature. It will check the current focus (not really the cursor is) and open the window there.
> 
> Is it a setting or something I might have missed. Dual 27" here and it doesn't do for either focused window or mouse

Probably this one?
![image](https://user-images.githubusercontent.com/45326534/119250406-74adb700-bbd2-11eb-9668-7e8bb2f4ab5e.png)
Close this works for me.

**Comment by mochigithub** [comment]
Thank you @taooceros
