### ISSUE TITLE
Adaptive Results (Ranking) based on previously opened items

### ISSUE THREAD

**Issue by hced** [Flow-Launcher/Flow.Launcher#453]
## Problem

Each time I'm opening a file (in this case it's called `Due.url`) I have to scroll far down to open it.

## Suggestion

Would love to see ranked search results based on recency and/or frequency. Blueprint: e.g. how Launchbar on macOS works; you open an item among the search results, and if nothing else exist that resembles its name closer (and is higher-ranked), the item you picked will be the first search result the next time you search for it! I think this is a decent example of the term *recency*, which is a weighted ranking-system based on how many times you've chosen an item (frequency) but also including how recently you've chosen an item, in the equation.

If anything, simple frequency ranking is the base feature I wish in Flow-Launcher!

**Comment by taooceros** [comment]
Hey, here's how's going. We do have a frequency based ranking system, but if the original result lies really low, it won't show effect until a large number of choosing.

The idea of scoring bumping based on recent choosing is interesting. Let's see how shall we implement it.

**Comment by taooceros** [comment]
Related to #19

**Comment by hced** [comment]
> We do have a frequency based ranking system, but if the original result lies really low, it won't show effect until a large number of choosing.

Great! I managed to bump it to rank 1 after about 20 re-openings. (Happy to see there'a rank feature!) However ... the rank only stayed for the current session. When I quit Flow and relaunched it, the search result wasn't number one. In fact, it wasn't even there in the whole list!

The result in question is `D:\Dropbox\Henrik\GLUB\Links\Due.url` and it's a weblink shortcut. I'm running Flow in Portable mode from `C:\Portable\Flow Launcher\FlowLauncher\Flow.Launcher.exe`. Checked to see if the file was gone, but it's still there.

**Comment by jjw24** [comment]
When you quite Flow, did you type 'Exit' to quite? 

you can also check the result and its ranking at: 
(portable by default): %localappdata%\FlowLauncher\app-<VersionOfYourFlowLauncher>\UserData\Settings\UserSelectedRecord.json

if you are searching Due.url file, i dont see why it's not come up as the first rank result when you type 'due', is this not the case?

**Comment by hced** [comment]
Odd, after a system restart the result come up #1 ranked again. Which clears this issue for now.

However, the `%localappdata%\FlowLauncher\app-\UserData\Settings\UserSelectedRecord.json` or this director, doesn't exist on my system. Can it have another location? I'm on the portable install version.

**Comment by jjw24** [comment]
A system restart? That shouldn't be the case.

Try C:\Portable\FlowLauncher\app-1.7.2\UserData\Settings\UserSelectedRecord.json

**Comment by jjw24** [comment]
@hced is the ranking stabilised for you or still not working?

**Comment by hced** [comment]
@jjw24 So sorry for late reply but Yes! It's stable now. (Have a beautiful summer!)

**Comment by manusgeek** [comment]
I have the same problem. No matter on how many times i click on a result down the list, it  will never show up higher in the list when i type the first letters. I really have to type the full script name for it to show as the first result. Launchy is/was better for that.
