### ISSUE TITLE
Custom Keywords

### ISSUE THREAD

**Issue by hced** [Flow-Launcher/Flow.Launcher#454]
(Disclaimer: Sorry if this was requested before. Tried searching for `abbreviation`, `label` and `tag` without anything.)

I'd like to be able to add an abbreviation/word for any given search result and then be able to search for that abbreviation to have them show up first in future searches. This is very useful for nudging a launcher to become more like how you want it to be. ;)

**Comment by jjw24** [comment]
Is this where you would assign abbreviation/tag to several results and then search that abbreviation/tag to have those results come up?

**Comment by hced** [comment]
It's for a single search result. Assigning your own abbreviation/word can sometimes be quite useful. E.g. `zzz` for system sleep, or similar.

**Comment by jjw24** [comment]
Hmm if you are assigning to a single result, how come you don't just search for that result? Is this for scenario where you would remember the assigned custom keyword but not the actual name of the item you are looking for?

Would this be for searching apps or files/folders ?

**Comment by deefrawley** [comment]
If it is a search result for a single command then the Plugin Runner plugin can do this can't it?

**Comment by jjw24** [comment]
not sure, i havent tried. 

I am considering this will have another use case where you can label/tag your commonly used search results so one label/tag will bring them up and you can select from the result set or do additional search within the set

**Comment by hced** [comment]
Actually, my personal reason for adding often different keywords than the actual search term, is just personal preference. In examples like above, I find it a much easier mnemonic to just type `zzz` for System
Sleep. I think that’s a key ingredient in making a launcher become excellent: the launcher should adapt to the user, rather than the user having to remember what each particular function or file was called again. You know, sometimes it just won’t stick :-) And *that’s* the real reason for why custom keywords are great.

**Comment by deefrawley** [comment]
If the target is an executable or script then Plugin Runner can do this.  To shutdown the PC (not quite sleep mode but easier to explain) you add a new Plugin Runner command, pick the c:\windows\system32\shutdown.exe file, give it the shortcut 'zzz' and save. Then in FL just type 'r' to activate the plugin and should list all your shortcuts and you can type 'zzz' or choose with the arrow keys.  If you want a shortcut to a search result set, say C:\MyPics\*.jpg then Plugin Runner won't work.

**Comment by taooceros** [comment]
I think @deefrawley 's idea is quite great. Just a few addon, you can open Files like "C:\MyPics*.jpg" with plugin runner, but by doing that you may need to use a shell to open it.
For example, the command maybe `powershell -c & "C:\MyPics.jpg"`. If you don't want a powershell window open up, you can search for args to hide powershell window, which I believe there's one. The Plugin Runner is highly Customized, which is quite an interesting plugin.

**Comment by deefrawley** [comment]
If you have Everything installed (standalone or as part of the Everything Flow plugin) then you can create Plugin Runner shortcuts to use Everything's extensive command line arguments to run a search and display the results in the Everything GUI too.
