### ISSUE TITLE
Please update the Python documentation for building plugins

### ISSUE THREAD

**Issue by AnthonMS** [Flow-Launcher/Flow.Launcher#459]
**Question**
Why is the documentation so bad?

**Discussion**
I am trying to make a python plugin... I know I know, you guys prefer C#. But since you support creating and using python plugins, why is the documentation so poor for creating python plugins?
I am trying to make a very simple plugin, but every time I get a success, everything stops working after a couple of tests.

For example, I am trying to get JsonRPC to work when a query is clicked, but how do I know it works? Is there a log function in the FlowLauncherAPI or something else? I tried just "logging" to a file by opening it and writing a line and saving it. It didn't work the first time a tried it. BUT after some playing around, I actually got it to log to a file when a query was clicked. Then I wanted to make the code a bit prettier and removed some commented out code and suddenly it didn't work again. Whyyyy, is it this bad creating plugins?

Where is the documentation? Because [this](https://flow-launcher.github.io/docs/#/?id=welcome) is severely lacking everything... How many people use this and how many people create plugins? Because I think a large amount of people who want to make a plugin, gives up after a week of trying,  simply because there is no documentation, the only way to create a python plugin is by trial and error. And when it sometimes work but most of the time don't and there's no way of debugging, how do you suppose people create plugins?

**Comment by taooceros** [comment]
Hi, sorry that our documents are not fully complete for now. The page you indicates is only the API reference, which doesn't include the instruction toward creating a python plugin.
Currently, you can reference from https://github.com/deefrawley/Flow.Launcher.Plugin.Currency to create a plugin. Or if you don't want to be so complicate, I believe it is possible to directly use sys.env to get argument and parse them based on the document style.
![image](https://user-images.githubusercontent.com/45326534/120594769-0095cd80-c474-11eb-81e2-9438e2d7e971.png)
And use print to print the json output, which will be read by flow.

**Comment by AnthonMS** [comment]
Thank you for the help. I have taken a look, and it looks way more complicated than my plugin needs to be. But I will try to work my way from that. And who knows, maybe my plugin will be a lot more complicated than I think it will.

I don't know if I should close the issue or not. So I'll let that be up to the devs. I have gotten some answers, but I, and probably many other people, would still like a more complete documentation on creating plugins.

But thanks for the reply, I hope it will make more sense after going through the code.

**Comment by taooceros** [comment]
Hi, maybe you can take a look on this one.&nbsp;plugin-samples/HelloWorldPython at master · Flow-Launcher/plugin-samples · GitHub&nbsp;It is the sample python plugin for flow, and I guess this is much simpler and easy to understand than the currency converter.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Flow-Launcher/Flow.Launcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 凌晨0:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Flow-Launcher/Flow.Launcher] Please update the documentation (#459)





 
Thank you for the help. I have taken a look, and it looks way more complicated than my plugin needs to be. But I will try to work my way from that. And who knows, maybe my plugin will be a lot more complicated than I think it will.
 
I don't know if I should close the issue or not. So I'll let that be up to the devs. I have gotten some answers, but I, and probably many other people, would still like a more complete documentation on creating plugins.
 
But thanks for the reply, I hope it will make more sense after going through the code.

**Comment by taooceros** [comment]
Oh there's a python template for Flow in our repo. I personally didn't get involved in that repo so I didn't notice that before. You can check out that one.
https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate

**Comment by AnthonMS** [comment]
@taooceros Hey, I have looked at the HelloWorldPython. And worked from that. But I can't get JsonRPC methods working. Or I should rather say, I couldn't get it working, then suddenly it started working, and then it stopped and I haven't been able to get it working again, even though I went back to the exact same code, that did work... Which I found very very annoying...

I haven't stumpled upon the PythonTemplate though, but it's basically the same as the currency plugin, just without the functionality from currency plugin. But maybe it will be eaier to work out from. So I'll take a look at it, thanks.

**Comment by AnthonMS** [comment]
Can you tell me why [this ](https://pastebin.com/dSU9sE7b) doesn't work?
I tried making it with the template files and copy and all that, but the flow logs threw a ton of errors. And I will never, ever, evers implement different languages.

I'm just trying to make it as simple as possible to start with. But I can't for the life of me, get JsonRPCAction to work and I'm so close to just giving up. It's really not worth this much trouble to be honest.

**Comment by Zeroto521** [comment]
You could debug in the console via print function.

**Comment by taooceros** [comment]
> Can you tell me why [this ](https://pastebin.com/dSU9sE7b) doesn't work?
> I tried making it with the template files and copy and all that, but the flow logs threw a ton of errors. And I will never, ever, evers implement different languages.
> 
> I'm just trying to make it as simple as possible to start with. But I can't for the life of me, get JsonRPCAction to work and I'm so close to just giving up. It's really not worth this much trouble to be honest.

I try your file, and it works partially. Flow doesn't throw a tons of error when trying to access it. Would you please upload the log so I can check what is being wrong? Have you installed the dependency?

**Comment by taooceros** [comment]
Unable to exercute callback is a bug brought by previous Json library changed, and I have posted a fix to that.

**Comment by jjw24** [comment]
@AnthonMS agree, we need to give Python documentation more love, I personally have yet to build a Python plugin so would not know the exact details of what needs to be added to the documentation. 

For now if you have any questions just throw them here, hopefully the @Flow-Launcher/team can help you out. We can update the documentation based on the issues here so the next person can benefit.

**Comment by deefrawley** [comment]
Just to add here - I used Zero's full Python template as a learning exercise more than out of necessity. It absolutely can be done simpler if needed. I'm also an amateur Python programmer so was just happy to get something working. There are a lot of moving parts to developing and innovating Flow Launcher and realistically Python plugin development, and Python documentation, is a little lower than the core code and C# plugin development at the moment. I'm happy to help however I can to improve this and to learn where I can from those more accomplished than me. @AnthonMS if you could help with documenting your Python plugin journey perhaps that could be really useful to the project?

**Comment by AnthonMS** [comment]
> Just to add here - I used Zero's full Python template as a learning exercise more than out of necessity. It absolutely can be done simpler if needed. I'm also an amateur Python programmer so was just happy to get something working. There are a lot of moving parts to developing and innovating Flow Launcher and realistically Python plugin development, and Python documentation, is a little lower than the core code and C# plugin development at the moment. I'm happy to help however I can to improve this and to learn where I can from those more accomplished than me. @AnthonMS if you could help with documenting your Python plugin journey perhaps that could be really useful to the project?

I would love to contribute to the project by writing some Python Plugin Development Documentation, when I finally get something working. I have only just heard of JsonRPCAction after starting to use Flow Launcher, so there's still some functionality I can't explain in details. But I would love to write something I do know, and you guys can maybe add some of the more in depth technical stuff htat happens in Flow Launcher when JsonRPCAction is being used.

**Comment by jjw24** [comment]
@AnthonMS  just going to update this PR's title to 'Please update the Python documentation' to better represent the discussion taking place here.

**Comment by pc223** [comment]
For now, I think we can organically grow the docs by help people fixing their plugins (Q&A). Maybe a separate repo to make issues to Q&A about plugin-dev?...Seems better than _Discord_, because we can link to that Q&A later in Wiki.

My experience with Flow's python plugins is pretty much just use the plugin-template of Zero
- Read other people plugin
- Observe Flow's log files in `UserData` folder
- If see an error => read the traceback, find the line of code causing the problem
- Put some `print('')` here and there
- Run the test.py file

Something like that, pretty easy :D

**Comment by jjw24** [comment]
repo might be a bit overkill, maybe a pinned issue perhaps.

**Comment by jjw24** [comment]
python doco is now live https://flow-launcher.github.io/docs/#/py-develop-plugins

let's create issues in the docs repo for improvements.
