### ISSUE TITLE
Two CI?

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#467]
**Question**
Why do some pull requests have two CI build? I believe both checks are the same?
@Flow-Launcher/team

**Comment by JohnTheGr8** [comment]
One is a build of the PR branch, one is a build of the PR merged into the target branch... (if that's what you mean)

**Comment by taooceros** [comment]
Yeah that's what I mean. However, sometimes both ci will be triggered (pr from main repo's branch). I believe both are doing the same job, so is it possible to only trigger it once?

**Comment by JohnTheGr8** [comment]
> 
> 
> Yeah that's what I mean. However, sometimes both ci will be triggered (pr from main repo's branch). I believe both are doing the same job, so is it possible to only trigger it once?

We can use `skip_branch_with_pr: true` to avoid building `continuous-integration/appveyor/branch` for PRs. However, I am not sure what happens when there are merge conflicts that need to be resolved, I assume that no build will start in that case until the conflict gets resolved.

**Comment by taooceros** [comment]
I remember if merge conflicts is happening, the pr will automatically fails, so should not be a big deal?

**Comment by JohnTheGr8** [comment]
> 
> 
> I remember if merge conflicts is happening, the pr will automatically fails, so should not be a big deal?

Yes, but you won't know if the branch builds successfully until the conflicts are resolved, which could be annoying in the case of a WIP pr for example.

**Comment by taooceros** [comment]
> Yes, but you won't know if the branch builds successfully until the conflicts are resolved, which could be annoying in the case of a WIP pr for example.

Shouldn't a WIP pr based on dev branch? It will finally need to merge dev, so I don't think this should be annoying.

**Comment by JohnTheGr8** [comment]
> 
> 
> Shouldn't a WIP pr based on dev branch? It will finally need to merge dev, so I don't think this should be annoying.

Let's say you open a PR from `feat/whatever` to `dev` which is a WIP, and at some point you introduce conflicts. Normally, you'd be able to continue working on the PR, and only resolve conflicts later when it is ready to review/merge. If we add `skip_branch_with_pr: true` to our CI config, we will not get any CI builds for new commits to the `feat/whatever` branch until the conflicts are resolved.

That said, I'm only pointing this out, I don't mind either way... @taooceros you are more involved with PRs so if waiting ~3 extra minutes for the extra CI build to finish is a bigger annoyance, then let's configure appveyor to skip it.

**Comment by taooceros** [comment]
Thanks for pointing that out. 
I personally don't mind for 3 more minutes for the Ci build.  In most situation, waiting the ci build won't stop us from doing things. However, just as you have mentioned before, this is kindly wasting a free service. It will  not only queue the work twice, but upload the same artifact twice.

**Comment by JohnTheGr8** [comment]
Agreed. Wanna open a PR to update appveyor.yml ?

**Comment by taooceros** [comment]
> Agreed. Wanna open a PR to update appveyor.yml ?

Do you want to do that by yourself?
