### ISSUE TITLE
Shadows are getting cut off when being enabled

### ISSUE THREAD

**Issue by lzl1918** [Flow-Launcher/Flow.Launcher#471]
**Describe the bug/issue**
When enabling the window shadow, the shadow does not display at the top and bottom.
Suggest to add margins when shadows are enabled.

And here is a proposed commit: https://github.com/lzl1918/Flow.Launcher/commit/ef73c926d02cd674277bfa8c04562dd4d30d2897

**To Reproduce**
1. Enable the window shadow in theme settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/6960434/121779726-bc22d400-cbcf-11eb-899f-36c370a222bf.png)
If you check the bottom right corner carefully you may notice the shadows being cut off at the top and bottom.

**Comment by taooceros** [comment]
Why not create a pull request for the commit?

**Comment by lzl1918** [comment]
I would create a PR once it is considered as a real issue/bug. 😂

**Comment by taooceros** [comment]
>  I would create a PR once it is considered as a real issue/bug. 😂

Haha got you. Could you add comparison before and after the pr in the  pr description? I didn't use that feature a lot so am not quite sure about your description.

**Comment by lzl1918** [comment]
> > I would create a PR once it is considered as a real issue/bug. 😂
> 
> Haha got you. Could you add comparison before and after the pr in the pr description? I didn't use that feature a lot so am not quite sure about your description.

Thanks for the reminder. Pics are attached.

**Comment by taooceros** [comment]
Thank you, I will review it tomorrow.

**Comment by jjw24** [comment]
closed by https://github.com/Flow-Launcher/Flow.Launcher/pull/472
