### ISSUE TITLE
Plugin.Shell: The query box is not auto-focused when its hotkey is invoked

### ISSUE THREAD

**Issue by lzl1918** [Flow-Launcher/Flow.Launcher#490]
**Describe the bug/issue**
The shell plugin listens for the win+r hotkey and shows the query box when the hotkey is invoked.
However, the main window does not gain input focus.
And the user has to manually click on the query box to start typing commands.

**To Reproduce**
1. Make sure the shell plugin is enabled, and has assigned a hotkey
2. Press the hotkey
3. The query box does not have user focus

**Comment by lzl1918** [comment]
A potential fix to the bug: #489

**Comment by medlir** [comment]
Thank you for fixing this!  This had been bugging me for quite a while now, and I was going to look into if I could find/fix the issue myself when I found you already had... using dev build for now solely to have this fix.  :)
