### ISSUE TITLE
A Wiki page/Website page/Discussion topic for Early access builds/beta testing?

### ISSUE THREAD

**Issue by pc223** [Flow-Launcher/Flow.Launcher#492]
Should we do something similar like this?  🤔  (like a Wiki page, or Flow's website page or Discussion topic?)

https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

We got automatic CI artifacts so it seems not too hard to do.

I think we only need a couple of main builds:
- A `dev branch` build
- A `next release build` (like `1.8.0`)
- Some `PR build` (builds of a big PRs, e.g. PR #470)

**Why:**
- For people want to test new improvements
- For testing new ideas
- Early feedback, early bug report

**Comment by jjw24** [comment]
i dont know if there are enough interests atm to test builds. the builds can always be accessed via the build results in each PR, perhaps when there are more requests we can put it in a discussion section or wire up the ci for it

**Comment by pc223** [comment]
> i dont know if there are enough interests atm to test builds. the builds can always be accessed via the build results in each PR, perhaps when there are more requests we can put it in a discussion section or wire up the ci for it

I think people will try it out if we provide them the builds clearly (like what that build is for, and where to post testing-results), right now the builds are buried in PR which is not many people aware of and not sure what to do with it.

Early feedback is the whole point of CI/CD stuff, I think we need early feedback on big PRs like PR-#470 or big releases like 1.8.0, or feedback about style (PR-#495) (those tend to be fairly subjective)

And the last release of Flow is like 4 months now. Many users not able to try out all the improvement that exists for months seems a bit ...sad 😅 

I think, for now, we can just keep it really simple, 1 topic (discussion) for it, listed 3 builds: a weekly-dev-builds, a 1.8.0 build, a big PR build. And we ask people to try them out. 

In terms of maintenance, for now we can do manual, weekly edit that topic, later we can write some CI to automate if people like it.

**Comment by jjw24** [comment]
The release pr will constantly have changes merged in, which will be quite manual to keep up with the latest builds in discussion, (I'm afk) I wonder if there is something in AppVeyor to provide a link to the latest build of a pr constantly.

Version from builds are still the production release version, for currently it is 1.7.2, I don't know if we need to mark them as pre-release and how.

**Comment by jjw24** [comment]
Also how is this discussion abt adding early access builds in Discussions not already in Discussions 😛

**Comment by pc223** [comment]
> Also how is this discussion abt adding early access builds in Discussions not already in Discussions 😛

Haha hold up, lemme convert this real quick, kind of itchy to try it 😝
