### ISSUE TITLE
dev branch: empty path during logging

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#536]
@taooceros , hitting this issue when logging, the path is empty, causing the logger to throw another exception. Let me know if it's intended or is addressed in the other pr.

I can replicate with querying 'windows', not sure if it's the same for you.

![image](https://user-images.githubusercontent.com/26427004/123955931-88c4af80-d9ed-11eb-86b6-00ecbe7026a3.png)

**leads to**

![image](https://user-images.githubusercontent.com/26427004/123956399-012b7080-d9ee-11eb-83f6-2bcf522f5de3.png)

**Comment by taooceros** [comment]
I do have reproduce similar issues before when I test the logging in #470. I guess we can add a check for empty path. 
Though, if it is unavailable, should we do a reload like what's proposed #152? However, it is possible that the icon is consistent unavailable, like the PWA apps from Edge.

**Comment by jjw24** [comment]
the reload could be costly in terms of performance though?

**Comment by taooceros** [comment]
> the reload could be costly in terms of performance though?

Yes, but it will only take a few seconds. This shouldn't happen every time. Though, if we want to do that, we may need to make a record so same app won't trigger multiple reload. Let's delay that, and fix the current issue in a quick way.

**Comment by jjw24** [comment]
Agree. 

Reload still sounds like a patch rather than addressing the root issue.
