### ISSUE TITLE
Change Actionkeyword for folder search

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#539]
We should change the actionkeyword for folder search when the index search keyword is different from the path search keyword, or else the results will be weird.

**Comment by jjw24** [comment]
can you show me you mean please

**Comment by taooceros** [comment]
if we search a folder with index search (while index search's actionkeyword is e), when we click on the result, we will result a query text e pathToFolder, which may act weird when we have other path search actionkeyword.

**Comment by jjw24** [comment]
Hmm I find it actually good that I am able to go I to the folder, doesn't feel weird. What would be the behaviour then when clicking on it?

**Comment by jjw24** [comment]
Oh I think I know what you mean, the path is suppose to the after the actionkeyword of the path search

**Comment by jjw24** [comment]
and it doesnt resolve the path with the index search action keyword. gotcha. Yes need to fix this

**Comment by taooceros** [comment]
> and it doesnt resolve the path with the index search action keyword. gotcha. Yes need to fix this

What if user disable both index search and path search (though I won't think that's a general case).

**Comment by taooceros** [comment]
> What if user disable both index search and path search (though I won't think that's a general case).

I will direct that to directly open the folder

**Comment by jjw24** [comment]
> > and it doesnt resolve the path with the index search action keyword. gotcha. Yes need to fix this
> 
> What if user disable both index search and path search (though I won't think that's a general case).

In the PR you have directed to the general search action keyword so will cover this case, which is good
