### ISSUE TITLE
Change the magnifying glass icon to plugin icon when all plugins the same

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#54]
Change the magnifying glass icon to plugin icon when all plugins the same:
![image](https://user-images.githubusercontent.com/26427004/82174052-c910bd80-9912-11ea-9303-ad525814a76d.png)

**Comment by JohnTheGr8** [comment]
Perhaps an even better idea: the magnifying glass icon could be replaced by the icon of the plugin that matches the selected result.

So if there's query results from multiple plugins, you can select and of them with the arrow buttons and the icon on the top right will tell you what plugin was responsible for that result.

**Comment by thanhmssl10** [comment]
Maybe integrate the loading icon too? Right now, I think, the Wox's loading UI is too small and not clear. It's should be something like Google chrome loading icon, clearly so when loading when done.

**Comment by jjw24** [comment]
> Maybe integrate the loading icon too? Right now, I think, the Wox's loading UI is too small and not clear. It's should be something like Google chrome loading icon, clearly show when loading when done. 
> 
> So... Rotating stars? Circle around stars? :star2: :thinking: :smile:

Yeah, of course. It's just in a separate issue.

**Comment by jjw24** [comment]
Completed and available in pre-release/upcoming v1.10.0
