### ISSUE TITLE
Feature to disable or edit quick access keyword hotkey(ctrl+alt+d)

### ISSUE THREAD

**Issue by MagnusCaesar** [Flow-Launcher/Flow.Launcher#540]
### **Problem: Non customizable hotkey**

It is quite the trouble to not be able to change the default hotkey, it tends to interfere with the functioning with other apps, and I'm forced to quit the app or disable shortcuts in full screen

**Fix: Add Feature to customize quick access keyword**

Make it such that all hotkeys(only the **_quick access keyword_** is left out, as far as I've seen) are customizable as not being able to interferes with the functioning of other apps

**Comment by jjw24** [comment]
Hey is this hotkey from the WindowWalker plugin?

**Comment by MagnusCaesar** [comment]
Oh yes, it stops when the plug in is uninstalled, I'm really sorry for not checking it out exhaustively before opening an issue

That said, the hotkey worked even after disabling the window walker plugin(+restarting flow) when I'd opened the issue(still does), so, I was under the impression it's a hotkey of the launcher itself

Sorry again for wasting your time, But thanks for the response

**Comment by jjw24** [comment]
no all good, i will transfer this issue over to the repo and investigate there.
