### ISSUE TITLE
PluginManifest constantly updating

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#549]
In debug mode, 

1. plugins manager is constantly updating when i just query pm install windowwalker:

![image](https://user-images.githubusercontent.com/26427004/124380790-19f39900-dd02-11eb-8a84-8dea36134339.png)

This is coming from the task status being always in  cancelled status:

![image](https://user-images.githubusercontent.com/26427004/124380833-5de69e00-dd02-11eb-81db-975bb9eb8831.png)

2. might also be related, the last update time is never set, even after several updates:

![image](https://user-images.githubusercontent.com/26427004/124380892-bd44ae00-dd02-11eb-938c-66ccb22e5774.png)

@taooceros is this expected?

**Comment by taooceros** [comment]
I think this has been reported before?
However, I still don't understand why this task will be considered as cancelled. Let me take a debug trial.

**Comment by taooceros** [comment]
I think I found the issue of the cancelled task. It's because of the error handling......

**Comment by taooceros** [comment]
Silly bug😂

**Comment by jjw24** [comment]
does it address the cancellation issue though?

**Comment by taooceros** [comment]
> does it address the cancellation issue though?

Yes, because I previous direct the field to the continuous error handling task, which will be canceled if no bugs happens.
