### ISSUE TITLE
 Plugin.Program should not index file with empty extension implicitly

### ISSUE THREAD

**Issue by pc223** [Flow-Launcher/Flow.Launcher#551]
With setting like this:
```
appref-ms;exe;lnk;url;
```

The Plugin.Program will index files with empty extension, which is a lot of them. I think the plugin should ignore empty string after `Split(";")`

<img src="https://user-images.githubusercontent.com/10551242/124383871-e6f8d780-dcf8-11eb-814d-6a8efc88c3df.png" width="400">

**Comment by taooceros** [comment]
Will it? I cannot reproduce it by creating a file with empty extension.

**Comment by taooceros** [comment]
Oh my program setting is different from yours. Probably because you have added the unexpected ; at the end unexpected? Though, I think it is reasonable to remove empty entry.
