### ISSUE TITLE
Flow don't stop after typing exit

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#560]
Flow don't stop after typing exit
I can still see the process in task explorer

**Comment by taooceros** [comment]
Probably related to clipboard plugins. Let me take a test

**Comment by jjw24** [comment]
Closed because it's related to clipboard plugin?

**Comment by taooceros** [comment]
Yes, but we still need to add a process of disposing plugin when closing.

**Comment by jjw24** [comment]
Is this a dev issue or prd issue as well do you know?

**Comment by taooceros** [comment]
> Is this a dev issue or prd issue as well do you know?

It should be prd issue.
