### ISSUE TITLE
Unable to load Sqlite.Interop.dll

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#564]
Unable to load Sqlite.Interop.dll lies within runtime folder

**Comment by taooceros** [comment]
Let see whether we can resolve this, or else we can post the issue to Dictionary plugin to address it by moving target platform to windows.

**Comment by jjw24** [comment]
shall we close this now that's it's merged?

**Comment by taooceros** [comment]
I think maybe after the dotnet template has added the powershell script?
