### ISSUE TITLE
plugins deleted on upgrade from 1.7.2 to 1.8 

### ISSUE THREAD

**Issue by katchy3132** [Flow-Launcher/Flow.Launcher#578]
**Describe the bug/issue**
after upgrading from 1.7.2 to 1.8 and running plugin update the plugins are deleted. 

**To Reproduce**

1. I auto upgraded from 1.7.1 to 1.8 then ran "pm update" it listed 4 plugins as needing update even though version number did not change 
-  putty plugin
-  window walker
- todoist
-  plugin runner
2. updated each one
3. result was couldn't update but will "delete plugin for consistence" then delete fails
4. plugins are no longer installed 
5. "pm install" fails 

**Screenshots**

**Your System**
```
Microsoft Windows [Version 10.0.19043.1110]
1.8
```
**Flow Launcher Error Log**

[2021-07-19.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6838497/2021-07-19.txt)

**Comment by taooceros** [comment]
I found the bug. Related to PluginsManifest changes. Will fix that soon.

**Comment by taooceros** [comment]
@katchy3132 Fix it. You can check by typing and clicking `reload plugin data`

**Comment by katchy3132** [comment]
is this what you meant? nothing came up to click. I was able to reinstall by restarting FlowLauncher and doing " pm install " 
![image](https://user-images.githubusercontent.com/3707138/126125306-e874581e-327a-408c-b06e-09b1abd1ea56.png)

**Comment by katchy3132** [comment]
BTW even after install all plugins still show up as installable . I seem to remember that previously only plugins that were not installed were listed as installable .

**Comment by taooceros** [comment]
I mean you can use this to reload the loaded manifest, which has been fixed for this issue.
![image](https://user-images.githubusercontent.com/45326534/126125694-d7bbbf41-cf51-41ba-a5e9-82ecf08c1943.png)

**Comment by taooceros** [comment]
> BTW even after install all plugins still show up as installable . I seem to remember that previously only plugins that were not installed were listed as installable .

It's because the unexpected 'v' before the versions in the manifest.

**Comment by katchy3132** [comment]
> I mean you can use this to reload the loaded manifest, which has been fixed for this issue.
> ![image](https://user-images.githubusercontent.com/45326534/126125694-d7bbbf41-cf51-41ba-a5e9-82ecf08c1943.png)

that didn't show up for me (see above)

**Comment by taooceros** [comment]
That's weird.......Do you have command `restart Flow Launcher`?

**Comment by katchy3132** [comment]
> That's weird.......Do you have command `restart Flow Launcher`?

no

**Comment by katchy3132** [comment]
> > That's weird.......Do you have command `restart Flow Launcher`?
> 
> no

ah I had the System Commands plugin disabled (BTW can you make a way to turn off individual commands? I turned it off so that I dont accidentaly shut down my computer ;)

**Comment by taooceros** [comment]
Ah, you can open a discussion for that. 😉

**Comment by taooceros** [comment]
Does the `pm update` performs as expected now?

**Comment by katchy3132** [comment]
> Does the `pm update` performs as expected now?

yes
