### ISSUE TITLE
add ability to turn off  individual commands in "System Commands" plugin

### ISSUE THREAD

**Issue by katchy3132** [Flow-Launcher/Flow.Launcher#580]
**Describe the solution you'd like**
Please allow toggling on/off of individual commands. I don't want to be able to accidentally do things like restart or shutdown computer .

**Comment by jjw24** [comment]
Fair enough, I myself had an accidental restart of my computer instead of restarting flow 🤣

**Comment by JohnTheGr8** [comment]
Maybe adding a confirmation to a these commands would be better? That should also benefit those that would not want to hide them completely...

**Comment by jjw24** [comment]
restart computer already has confirmation, that time my fingers went too quick and my brain was on auto. we can do something like the Explorer plugin where you can toggle on/off the commands

**Comment by pc223** [comment]
Or add a action keyword for sensitive operations like restart/shutdown?

**Comment by jjw24** [comment]
> Or add a action keyword for sensitive operations like restart/shutdown?

As in like a default action keyword for actual system commands shutdown restart sleep lock?

**Comment by pc223** [comment]
> for actual system commands shutdown restart sleep lock?

Yeah, but I'm not too sure about this yet, the problem with default action keyword it tends to hide the feature for users don't like tinkering.

Confirm Msgbox like John said is a possible solution too.

Maybe default behavior is confirming msgbox, and have options for set action keyword for sensitive system commands?

**Comment by taooceros** [comment]
I think if it is too annoying, just assign a action keyword for the whole plugin. Sys doesn't contain some results that needs to be triggered frequently.

**Comment by deefrawley** [comment]
@taooceros @jjw24 we have the system commands with a keyword - does that solve this issue and can we close it?

**Comment by jjw24** [comment]
Happy to just close it for now. Feel free to reopen if needs further discussion.
