### ISSUE TITLE
Everytime I open Flow Launcher after reboot it asks for python install

### ISSUE THREAD

**Issue by Failip420** [Flow-Launcher/Flow.Launcher#593]
Everytime I open Flow Launcher after reboot it asks for python installation
It's really damn annoying I have to pick location where I have installed python
Why can't it remember the location???
[Image](https://i.imgur.com/Q5TSEv7.png)

**Comment by taooceros** [comment]
It should. Try saving the setting by typing `Save Settings`?

**Comment by Failip420** [comment]
ohh thanks lol

**Comment by taooceros** [comment]
No Problem. @Flow-Launcher/team Should we add a cycle setting save to prevent situation like this?

**Comment by jjw24** [comment]
Sorry what's a cycle setting? This is happening as I just found out too, likely because after the path is set, it didn't do a save, so it's not written to disk. We only save when Setting window is closed.

**Comment by taooceros** [comment]
Oh I just mean that we save setting every a few hours or every 10 minutes, etc. .

**Comment by jjw24** [comment]
Nah that's just overkill. Call save after path is set up, keep it simple
