### ISSUE TITLE
Python plugin: Flow Launcher hangs on stream output larger than buffer

### ISSUE THREAD

**Issue by Garulf** [Flow-Launcher/Flow.Launcher#598]
**Describe the bug/issue**

**To Reproduce**
1. Any python plugin that returns more then 5 results causes FLow Launcher to never return results
2. Flow Launcher stays in infinite loading state

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.100]
Flow Launcher version: 1.8.0
```
**Flow Launcher Error Log**
No error is ever logged

**Comment by taooceros** [comment]
Do you have a sample python plugin for us to test?

**Comment by Garulf** [comment]
I'm working on a simple example now.

**Comment by taooceros** [comment]
I create a python plugin with 6 results, and it works fine.🤔

**Comment by Garulf** [comment]
```
# -*- coding: utf-8 -*-
import os.path
import json



from flowlauncher import FlowLauncher
from flowlauncher import FlowLauncherAPI as API


class Test(FlowLauncher):
       
    def add_item(self, title, subtitle='', icon=None, method=None, parameters=None, context=None, hide=False):

        item = {
            "Title": title,
            "SubTitle": subtitle,
            "IcoPath": icon,
            "ContextData": context,
            "JsonRPCAction": {}
        }    
        self.results.append(item)


    def query(self, query):
        self.results = []
        for _ in range(50):
            
            self.add_item(
                title=str(_),
                subtitle=query
            )

        return self.results


if __name__ == "__main__":
    Test()
```
it just hanges for no reason. I think the json is getting cut off

**Comment by Garulf** [comment]
> I create a python plugin with 6 results, and it works fine.🤔

Yeah my sample works with 6+ but hangs on 50

**Comment by taooceros** [comment]
I see. Interesting. 49 works fine, but 50 will cause the issue. Will investigate now.

**Comment by taooceros** [comment]
I found the issue. Probably because the buffer exceed, so the process hang when waiting Flow to read the data.

**Comment by taooceros** [comment]
Hmmm to fix this may require a larger refactor. I will handle it recently, but probably not able to finish it up today.

**Comment by Garulf** [comment]
> I found the issue. Probably because the buffer exceed, so the process hang when waiting Flow to read the data.

Sounds like that is the issue. On very large json it only took 5+ items to cause this behavior.
