### ISSUE TITLE
Add how to use the launcher

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#6]
How to use the launcher for an absolute beginner, this can be:
- a page on the documentation site, or
- a pop up window when flow launches for the first time to guide the user on changing the default hotkey, etc.

**Comment by Zeroto521** [comment]
I thought this issue could be closed.

**Comment by jjw24** [comment]
well we dont have proper documentation on how to use the launcher for a beginner, it doesnt have to be a wiki, can even be a screen pop up or in the doco site, but for someone who is brand new to Flow, there is no guidance.

**Comment by jjw24** [comment]
@deefrawley i think i read somewhere you are working on a doco page for this?

**Comment by deefrawley** [comment]
> @deefrawley i think i read somewhere you are working on a doco page for this?

I'm currently organising and updating the usage tips page of the doco site but we could add a 'getting started' page for the first steps basics. Perhaps have Flow popup a dialog box after each install asking if the user would like to open that page in their default browser to learn how to start using Flow?

**Comment by Garulf** [comment]
Added by @onesounds in https://github.com/Flow-Launcher/Flow.Launcher/pull/849
