### ISSUE TITLE
Please go to the new Discussions tab for general discussions/questions/ideas

### ISSUE THREAD

**Issue by pc223** [Flow-Launcher/Flow.Launcher#600]
Please go to the new Discussions tab for general discussions/questions/ideas.

https://github.com/Flow-Launcher/Flow.Launcher/discussions

**Comment by pc223** [comment]
@jjw24 @taooceros What are the things should be post on Issues? Safe to say "When in doubt go to the new Discussions"?

**Comment by taooceros** [comment]
I would consider confirmed bug goes into issue, but discussion can be converted to issue so go to discussion is also fine.

**Comment by jjw24** [comment]
Yeah if not a confirmed bug or solution design for a feature, and there are some doubts that need clarification, then use discussions.
