### ISSUE TITLE
Settings window issue

### ISSUE THREAD

**Issue by kumar007git** [Flow-Launcher/Flow.Launcher#607]
**Describe the bug/issue**
When I click settings from the tray icon these two things happen (at different times):
1. The settings window shows up but, I cannot click on any of the tabs.
2. The settings window shows up but, the windows is all white (like a clean slate) screen - no controls show.

**To Reproduce**
1. Right click on Flow Launcher tray icon
2. Click on settings

**Screenshots**

**Your System**
```
Windows build number: (run "ver" at a command prompt)
Flow Launcher version: (Settings => About) 
```
**Flow Launcher Error Log**

**Comment by taooceros** [comment]
I have experienced this before, but cannot consistently reproduce it.

**Comment by taooceros** [comment]
@kumar007git what's your flow version?

**Comment by jjw24** [comment]
I haven't experienced this before, @kumar007git could you also let us know your windows version please:
run "ver" at a command prompt

**Comment by kumar007git** [comment]
This issue happens randomly and suddenly.

Windows 10.0.19043.1110

**Comment by taooceros** [comment]
Are you on the latest version of Flow?

**Comment by kumar007git** [comment]
I was when this issue occurred. I just now downloaded 1.8.1 which was released 5 days ago. I'll see if the issue reoccurs in 1.8.1.

**Comment by pc223** [comment]
Sounds really similar to this https://github.com/Flow-Launcher/Flow.Launcher/discussions/543. But it suppose to be fixed by https://github.com/Flow-Launcher/Flow.Launcher/pull/544 already 👀

**Comment by taooceros** [comment]
@kumar007git does it reproducible in the latest flow? If not, I will close it.

**Comment by jjw24** [comment]
closing. if problem persists feel free to reopen.
