### ISSUE TITLE
Updating portable version is not user friendly at all and it very confusing.

### ISSUE THREAD

**Issue by kumar007git** [Flow-Launcher/Flow.Launcher#608]
**Is your feature request related to a problem? Please describe.** -  I use portable mode and every time I have to update to a new version I have to manually transfer the user data folder from old version to new version because of the folder structure which has version number in it. Furthermore, I'm not sure what additional files I should copy over to the new version portable folder. This is ridiculous.

**Describe the solution you'd like** - Remove the version number from the folder 'app' and that way I can simply copy new portable version folders and overwrite existing files instead of trying to figure out what files and folders to copy. If you could implement this in the next version or implement it and release a new version quickly that would help. Please remedy this immediately.

**Describe alternatives you've considered** - There is no alternative.
Thanks.

**Comment by jjw24** [comment]
Hey @kumar007git, you can still update with portable mode. By update I mean use the check update command or via settings window. The update will sort out your user data by copying them into the new version folder.

Only is an issue if you are in portable mode, your flow is in the %localappdata% and you use the installer which will indeed override everything in your flow folder. But this shouldn't be the way you update anyway. 

So in essence your user data should be taken care of regardless in portable or non-portable mode if you update via the app, you don't need to do anything further.

**Comment by jjw24** [comment]
Closing. Reopen if there is an issue
