### ISSUE TITLE
intranet folder location shuts bar down and throws exception

### ISSUE THREAD

**Issue by ulspot** [Flow-Launcher/Flow.Launcher#617]
Hi,
Often, when I put in a folder location into the flow bar it shuts down. But I don't know if it is even meant to work with a file location. There is never a result for these and I always end up using the windows menue for it. Is this a bug or just no feature at all?

Anyways, here are the logfile for the exceptions:
[2021-07-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6898424/2021-07-29.txt)
[2021-07-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6898427/2021-07-28.txt)

Many thanks for this brilliant and helpful app. 👍 
Keep up the good work!
Kind regards, Ulf

**Comment by jjw24** [comment]
Hi @ulspot, glad you like it. 

I am assuming you are pasting the folder path into Flow's query window right? Do you have an example of this path?

**Comment by ulspot** [comment]
Hi Jeremy, 
thanks for the quick response. Here an example: "P:\EJOT\DSP10894_EJOT_CG_7SV_L3\06_Production_QA\_Repository\20210727"
The bar shuts down immediately after input.

**Comment by ulspot** [comment]
I see in the feature gif, there is a folder plugin. Where do I get this one? thx

**Comment by jjw24** [comment]
It's called Explorer plugin, you should see it in your ugin list of you got to the settings window => Plugins tab

I will take a look at your issue soon

**Comment by ulspot** [comment]
Maybe, this is not necessary anymore. I discovered the path option within in the explorer plugin was disabled. 
Now it is enabled and it works like a charm. ( ͡° ͜ʖ ͡°)
This is so great!

**Comment by jjw24** [comment]
This error is due to your Windows Search turned off. Can you upgrade to 1.8.1 and test it how you originally were using it? you should no longer get the crash.

**Comment by jjw24** [comment]
Same as #581

**Comment by ulspot** [comment]
Thanks!
