### ISSUE TITLE
Remove `wpm` plugin from Flow

### ISSUE THREAD

**Issue by NickSeagull** [Flow-Launcher/Flow.Launcher#62]
I think that given that the Wox package repository is not our "official" way, perhaps we should remove the plugin from the installation so the users don't get confused.

A starting point for searching for plugins could be a repo like https://github.com/learn-anything/alfred-workflows

We can call the Flow plugins "Flows" 😄 

I can work on that repo if no one is against so

**Comment by jjw24** [comment]
Hey @NickSeagull could you expand a little more on what you mean.

I think something like that Alfred workflow repo is good. But I am not sure exactly what you mean by removing wpm. My perspective is flow in the future can support wox, pt run or any other launcher's plugin, it doesn't have to have the name flow before it.

Until we rewrite wpm, we still need the functionality or a means of installing plugins right?

**Comment by NickSeagull** [comment]
Yep, I just realized that if one needed to install Wox plugins, still the `wpm` plugin is needed. I meant the remote part that connects with the Wox package repo. Got this completely wrong, closing
