### ISSUE TITLE
interface sizes

### ISSUE THREAD

**Issue by Or-Fadlon** [Flow-Launcher/Flow.Launcher#624]
in comparison to WOX, 
it looks like Flow menu interface is bigger than the WOX one.
the search box font in Flow looks like a stretched version of WOX.

any way to fix it?
i think it can improve the Flow UI so much!

![image](https://user-images.githubusercontent.com/63373097/127752644-57dd2daa-23e3-4e25-bf29-bd553513b821.png)
![image](https://user-images.githubusercontent.com/63373097/127752665-81fdf237-0a97-4086-bcae-51c22ba792e0.png)
![image](https://user-images.githubusercontent.com/63373097/127752669-940650b0-a535-4178-9e06-b768e652eb73.png)

**Comment by jjw24** [comment]
Hey @Or-Fadlon how's it going.

It's never the intention to align the looks with Wox, perhaps specific suggestions on which part of UI could do with some improvements with some examples please.

**Comment by jjw24** [comment]
The upcoming 1.9.0 release will drastically change the look and feel with this pr https://github.com/Flow-Launcher/Flow.Launcher/pull/704, so will close this now
