### ISSUE TITLE
Settings Reset Automatically

### ISSUE THREAD

**Issue by rpawar0703** [Flow-Launcher/Flow.Launcher#641]
After 3 to 4 weeks, all the settings reset itself. All the custom web search settings and other settings get erased and set to default, including theme.

**System**
```
Windows build number: Version 10.0.19043.1151
Flow Launcher version: 1.8.1
```
**Flow Launcher Error Log**
[2021-08-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6954729/2021-08-09.txt)

**Comment by taooceros** [comment]
The log suggests that the saved setting or cache is changed to unexpected value. Could you please take a look on json files under %appdata%\FlowLauncher\Settings\, and check whether those json files present properly.

Though Flow may override them if you have set a setting.

```
17:48:08.1046+05:30 - ERROR - JsonStorage.Deserialize - Deserialize error for json <C:\Users\HomePC\AppData\Roaming\FlowLauncher\Settings\Settings.json>
EXCEPTION OCCURS: System.Text.Json.JsonException: '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```
I don't understand why the json file will start with 0x00

**Comment by jjw24** [comment]
flow will do a backup of all the json setting files it is unable to load, so you should have a backup file next to the regenerated file in those settings folder.

**Comment by taooceros** [comment]
I do reproduce once for this. It happens when the computer shutdown in an unexpected way. It creates weird json file in binary format.

**Comment by taooceros** [comment]
https://stackoverflow.com/questions/25366534/file-writealltext-not-flushing-data-to-disk

I think it happens really occasionally.

**Comment by jjw24** [comment]
@rpawar0703 did this happen after a unexpected computer shutdown by any chance?

@taooceros I think let's not put through a fix untill we can reliably repro this issue.

**Comment by arnishbaruah** [comment]
It happens to me as well, I used to think it resets when it updates

**Comment by arnishbaruah** [comment]
How can I help in fixing this?

**Comment by taooceros** [comment]
Does it happen to you consistently?

**Comment by arnishbaruah** [comment]
It happened to me 2-3 times.

**Comment by jjw24** [comment]
we need a consist way of repro these, if you can may be list the steps.

**Comment by jjw24** [comment]
Also please upload the log after the issue occurs.
