### ISSUE TITLE
Enable Flowlauncher on Window 11 made File Explorer very slow and crash.

### ISSUE THREAD

**Issue by betty2310** [Flow-Launcher/Flow.Launcher#642]
**Describe the bug/issue**
So when I enable Flow Launcher, my File Explorer is very slow. Drag and drop file, create file or delete file,... are delay so much. 
But if I disable it, everything is normal.

**Your System**
```
Windows build number: Win 11 10.0.22000.120
Flow Launcher version:  1.8.1
```

**Comment by pc223** [comment]
I don't think we support Windows 11 yet 😅

**Comment by taooceros** [comment]
I don't think win11 don't support wpf, so flow should work fine. But your behavior is so weird. Probably it is some bug from win 11.
Could you share the log? Typing "open log location" to find it.

**Comment by betty2310** [comment]
> I don't think win11 doesn't support wpf, so flow should work fine. But your behavior is so weird. Probably it is some bug from win 11.
> Could you share the log? Typing "open log location" to find it.

Because I don't understand all of it, so I don't know I should give you what information you need, so I give all of it:

06:14:10.6509+07:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
06:14:10.6509+07:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.8.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True
06:14:10.9516+07:00 - INFO  - ImageLoader.Initialize - Preload images cost <100ms>
06:14:10.9516+07:00 - INFO  - ImageLoader.Initialize - Number of preload images is <2>, Images Number: 2, Unique Items 2
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <61ms>
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <56ms>
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <51ms>
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <63ms>
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Runner> is <53ms>
06:14:13.1245+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <SpotifyPremium> is <94ms>
06:14:13.1423+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <142ms>
06:14:13.2063+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Google Search Plus> is <131ms>
06:14:13.2124+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <194ms>
06:14:13.2124+07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <71ms>
06:14:13.2124+07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <195>
06:14:13.2124+07:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <66>
06:14:13.2124+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <219ms>
06:14:13.2124+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <178ms>
06:14:13.4719+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <406ms>
06:14:13.6105+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <574ms>
06:14:13.7818+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <762ms>
06:14:14.5166+07:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Control Panel> is <1456ms>
06:14:15.6090+07:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
06:14:15.9279+07:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
06:14:15.9279+07:00 - INFO  - App.OnStartup - Startup cost <5802ms>
06:14:18.1812+07:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "D5CBF439E752CECFB6E3C29F8428FA3B566AC267",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.8.1-full.nupkg",
  "Query": null,
  "Filesize": 90471966,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "D5CBF439E752CECFB6E3C29F8428FA3B566AC267 FlowLauncher-1.8.1-full.nupkg 90471966",
  "Version": {
    "Version": {
      "Major": 1,
      "Minor": 8,
      "Build": 1,
      "Revision": 0,
      "MajorRevision": 0,
      "MinorRevision": 0
    },
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
11:14:17.3776+07:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "D5CBF439E752CECFB6E3C29F8428FA3B566AC267",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.8.1-full.nupkg",
  "Query": null,
  "Filesize": 90471966,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "D5CBF439E752CECFB6E3C29F8428FA3B566AC267 FlowLauncher-1.8.1-full.nupkg 90471966",
  "Version": {
    "Version": {
      "Major": 1,
      "Minor": 8,
      "Build": 1,
      "Revision": 0,
      "MajorRevision": 0,
      "MinorRevision": 0
    },
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>

**Comment by taooceros** [comment]
Probably similar to this https://github.com/Wox-launcher/Wox/issues/3503.

Try not using blur theme? I think it is win11 bug.

**Comment by betty2310** [comment]
> Probably similar to this [Wox-launcher/Wox#3503](https://github.com/Wox-launcher/Wox/issues/3503).
> 
> Try not using blur theme? I think it is win11 bug.

Oh thank you very much, I use opacity theme and the error is gone.

**Comment by jjw24** [comment]
Since this may be a Win 11 and not a Flow bug at this stage, will be closing.
