### ISSUE TITLE
Explorer plugin- previous directory hotkey keyboard combo

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#655]
Hotkey keyboard combo for going back to previous level directory, from c:\temp to c:\

Hotkey keyboard combo for going back to previous directory you were in.

E.g. in c:\temp, use keyboard combo alt+back arrow to go back previous level - c:\ then another combo alt + right arrow key to go back to previous directory you were in- c:\temp.

This saves user from constantly modifying the query to go back and forth.

**Comment by taooceros** [comment]
Probably `Ctrl+Backspace` is almost equal to the feature and `Ctrl+z` is equal to the restore. Though it may need to type more than once with space.

**Comment by taooceros** [comment]
Probably `Ctrl+Backspace` is almost equal to the feature and `Ctrl+z` is equal to the restore. Though it may need to type more than once with space.

**Comment by jjw24** [comment]
they dont work exactly well. We can have the hotkey editable.

**Comment by jjw24** [comment]
Closed by
