### ISSUE TITLE
About project itself suggestion: pr merged commit should add github number

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#659]
![image](https://user-images.githubusercontent.com/25895405/129827803-78d105a1-2190-40ce-bce6-250a3122a75b.png)

To this one, it should be "Rename discussion.md to discussion.md.not_used (#501)".

## Why add this?

Well, when we click "Rename discussion.md to discussion.md.not_used" text in github, we could see the difference.
But we more care about PR, it contains more.

You may say the following page has the github number (red marked one), but it's too tiny to find.
![image](https://user-images.githubusercontent.com/25895405/129828549-30881807-66ee-439f-8fa1-a63e631bfe3a.png)

## How to add?

Like the following one, I thought a pr title should be the commit, not the branch.

![image](https://user-images.githubusercontent.com/25895405/129828906-ff4d853e-44e2-4040-bd9e-6fcfad119ddc.png)

**Comment by JohnTheGr8** [comment]
Are you suggesting adding the PR number in every commit of the PR? This could be tricky when it comes to the first commits of the PR... 

Or do you suggest using more helping commit messages when merging PRs? If that's the case, I fully agree...

The commit history of this repo is a bit messy right now, just open the commits page and you get:

![image](https://user-images.githubusercontent.com/697917/129936916-061a1f15-5975-4f8f-8f11-20dec3af2f64.png)

4 out of the 5 top commits are merge commits that provide almost no information on first glance... Using more informative commit messages in the merge commits along with the PR number would be helpful here.

**Comment by jjw24** [comment]
Adding a pr number to each commit is an overkill, a better practice is to make commit messages more descriptive. To find the pr the commit is associated with, you can click on the commit and it will show you the pr number link.

Dont know there is anything we can do with those merge commits because the time it's merged is different to the time the commit is checked in, but the branch should describe what the pr is addressing.

**Comment by Zeroto521** [comment]
This issue's main aim is to patch PR number.

> This could be tricky when it comes to the first commits of the PR...

Notice PR number is added by PR's author. It's added by who merges this PR into project's branch.
That says PR number should be added by us.

Like the following one. When this everything is ok, before merged, github default pr info is `Merge pull request #30 from Zeroto521/python-plugin-template`. But we should change to `Let Flow-Launcher/Flow.Launcher.Plugin.PythonTemplate readme could show (#30)`, PR title + PR number.

This image should be correct. PR is https://github.com/Flow-Launcher/docs/pull/30.
![image](https://user-images.githubusercontent.com/25895405/130072304-e6f42420-f1a5-4220-a0f9-8147676f2e9a.png)

**Comment by Zeroto521** [comment]
> Or do you suggest using more helping commit messages when merging PRs? If that's the case, I fully agree...

Yes, I also have this means.
Now we should do "PR title + PR number" first.

Later we could specific "PR title" should be what.

Such as using the standard acronyms to start the commit message.
- EHN: enhancement
- DOC: documentation
- STY: style fix
- DEP: deprecate something, or remove a deprecated object
- PLUGIN: about plugin development
- CI: CI/CD
- BLD: about build workflow
- TST: addition or modification of tests
- REL: related to releasing
- ...

**Comment by Zeroto521** [comment]
An easy way could use 'squash and merge' action in github.

![image](https://user-images.githubusercontent.com/25895405/178401841-fa916e81-9f48-4e0d-b042-84a8c87190cb.png)

**Comment by jjw24** [comment]
We can use squash, although because we require pr for changes, in general it's much easier just to look at the associated or because that we give more context on the change and the driver behind it.

**Comment by Zeroto521** [comment]
And we could set 'squash and merge' as the only option.
![image](https://user-images.githubusercontent.com/25895405/178403400-9dd45ae8-f7ea-412b-9098-e6f96d4fd51b.png)
