### ISSUE TITLE
How do I hide the magnifier icon in the main window?

### ISSUE THREAD

**Issue by r3db34rd0** [Flow-Launcher/Flow.Launcher#661]
Just hate it and love original minimalistic wox interface

**Comment by jjw24** [comment]
Hi @r3db34rd0, this is the identifiable design aesthetic of flow, the magnifying glass can be enhanced with a better image but we won't be removing it.

What we can do is give the option for users to manually remove it from the theme file, but won't be building this in as an actual option to remove it.

**Comment by r3db34rd0** [comment]
Ok, ok, let it be, but, please, can you give this option or via theme?
