### ISSUE TITLE
Search for Files and Folders only in the folder which is currently open 

### ISSUE THREAD

**Issue by ms-2525** [Flow-Launcher/Flow.Launcher#676]
Add a feature whereby we can search the files and folders in the folder which is currently open.
Say i have my onedrive folder in C drive open, now i want the flow launcher to help me find the files in the onedrive folder (which is currently open and active on the screen) only and then there should be an option at the end to search in all files and folders.

That way i could be very useful as I can open a folder, press the flow launcher hotkey and find the files and folders in that folder very quickly

**Comment by deefrawley** [comment]
I don't think Flow hooks in to open windows to know what Explorer window is open and what folder it is browsing. Given the speed and flexibility of the Everything and Explorer plugins it is just as easy to search for files from anywhere. You can also add shortcuts to favourite locations (like OneDrive).

**Comment by r3db34rd0** [comment]
I could use option if wox could pass previous active window to the plugin, I have lots of ideas on how this could be used.

**Comment by jjw24** [comment]
this is the same as https://github.com/Flow-Launcher/Flow.Launcher/issues/760, further comments please go there

**Comment by jjw24** [comment]
This feature has actually been implemented for a while.
