### ISSUE TITLE
add windows safemode 

### ISSUE THREAD

**Issue by super-lurker** [Flow-Launcher/Flow.Launcher#678]
being able to just type safemode (with network) in the laucher would be a huge time saver, right now I do:

start>hold shift > click restart > start up option > press 4

**Comment by kubalav** [comment]
You can make cmd file with following command:
`shutdown.exe /r /o`

**Comment by jjw24** [comment]
Hi @super-lurker , this will be added with the v1.9.0 release. You can download the early access version [here](https://github.com/Flow-Launcher/Flow.Launcher/discussions/640)

**Comment by super-lurker** [comment]
> Hi @super-lurker , this will be added with the v1.9.0 release. You can download the early access version [here](https://github.com/Flow-Launcher/Flow.Launcher/discussions/640)

thats good to hear! cant wait to get it on stable release. thanks
