### ISSUE TITLE
Discussion: Removal of result highlighting

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#68]
Just wanting to get some thoughts on whether we should remove result highlighting. 

It was introduced as a way of combating the messy search results back then in Wox, but over the many iterations this has been improved to the point I dont think it's a necessity any more, and results now is clear enough. Any missed results would be more or less edge cases which we should just take as opportunity to further improve search experience.

Thoughts? @Flow-Launcher/team + anyone else

**Comment by jjw24** [comment]
Also want to add- removal of search precision option in Settings tab. Regular is a good standard and 'Low' + 'None' is not utilised much.

Anyone out there still use the other two options?

**Comment by JohnTheGr8** [comment]
> 
> 
> Just wanting to get some thoughts on whether we should remove result highlighting.
> 
> It was introduced as a way of combating the messy search results back then in Wox, but over the many iterations this has been improved to the point I dont think it's a necessity any more, and results now is clear enough. Any missed results would be more or less edge cases which we should just take as opportunity to further improve search experience.
> 
> Thoughts? @Flow-Launcher/team + anyone else

Does highlighting cause any problems other than the icon flickering issue (which is probably fixable)? Whatever performance/complexity overhead it adds is probably negligible.

I agree with what you said, it's not really a necessity any more... the core plugins could do without highlighting. But, at the same time, I think it's a nice to have, and that there could be potential use-cases for it from 3rd-party plugins that we haven't considered.

I'd vote to keep it.

**Comment by thanhmssl10** [comment]
I think the whole point of highlighting is for helping user to understand **why** Wox return those results. Maybe we can expand from that idea, let highlighting is a feature for debugging or advanced user mode. And add more features (even simple as log more detail info) to help user understand the search algorithm (why this item have lower point than that result etc ...)

For my personal usage, I have to do this to debug the "grading algorithm" and observe the performance of plugins :D

![image](https://user-images.githubusercontent.com/10551242/85016431-e6e07500-b193-11ea-8482-853434282e32.png)

**Comment by Kalaschnik** [comment]
Just to be clear we are talking about this:
![image](https://user-images.githubusercontent.com/9831678/85023161-a9202400-b174-11ea-901d-680ab354e4cd.png)

**Comment by jjw24** [comment]
> Just to be clear we are talking about this:
> ![image](https://user-images.githubusercontent.com/9831678/85023161-a9202400-b174-11ea-901d-680ab354e4cd.png)

Hey sorry if i am not clear. I am referring the highlighting of results from the query search, in the screenshot, it is the bolding of 'Code' in results such as "Visual Studio Code" and "Codec Config 3: Codec Config"

**Comment by Kalaschnik** [comment]
Ah I see. I actually like that feature. Just to verify how my query was matched...

**Comment by jjw24** [comment]
Result highlighting will be kept as per your feedback. I may add an option to toggle it on/off as a personal preference.
