### ISSUE TITLE
Query.Terms should not include actionkeyword

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#680]
Query.Terms should not include actionkeyword. Too much extra logic is used to handle it.

**Comment by taooceros** [comment]
It will be a breaking change for those who use Query.Terms.

**Comment by jjw24** [comment]
What is query terms mainly used for?

**Comment by taooceros** [comment]
Used to split terms in query search. For example, `query.FirstSearch`, `query.SecondSearch`, `query.SecondToEndSearch` etc.
