### ISSUE TITLE
auto-completer incorrectly change my query keyword

### ISSUE THREAD

**Issue by a224515a** [Flow-Launcher/Flow.Launcher#687]
**Describe the bug/issue**
The default keyword of Plugins Manager is "**pm**".
I've set it as "**fpm**" and used "**pm**" for searching in a website called 'PubMed'.
When I typed in 'fpm inst' to install plugins, the auto-completer change the query as "pm install", which searches 'install' in the PubMed site.

**To Reproduce**
1. set keyword of Plugins Manager as anything but 'pm', for example, 'fpm'.
2. set 'pm' as the keyword of other plugin, for example, Web Searchers.
3. install/ uninstall/ update plugins, the auto-completer change the "fpm ins" as "pm install".

**Your System**
```
Windows build number: 10.0.19043.1202
Flow Launcher version: 1.8.2, 1.8.3
```

**Comment by a224515a** [comment]
I have notice that in the Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs line 81, the query was fixed to "pm install ".

**Comment by jjw24** [comment]
Hey thanks for raising this. This is indeed a bug, and yep I think it was hardcoded. Do u want to have a go at fixing or like us to fix it? (I am ok either way, just asking so don't double up)

**Comment by a224515a** [comment]
ha, I am not good at coding.
hope you can fix this issue. I am appreciate the work

**Comment by deefrawley** [comment]
This is a very old issue with many updates since. Please update and retest. If this is still a problem we can reopen. Thanks
