### ISSUE TITLE
[Can't find the newly added bookmarks] 

### ISSUE THREAD

**Issue by LogicQuant** [Flow-Launcher/Flow.Launcher#688]
**Describe the bug/issue**
I added a new bookmark in chrome, then I search it in Flow Launcher but can't found the newly added bookmarks.

**To Reproduce**
1. Added n new bookmark in chrome
2. Search that bookmark in Flow Launcher
3. Can't found that book mark :(

**Screenshots**
![image](https://user-images.githubusercontent.com/50329121/132788965-20ce0b54-8953-4714-aff6-e31ed65c2829.png)

![image](https://user-images.githubusercontent.com/50329121/132788888-701a487d-ca37-4f91-ad6a-6c4248113b95.png)

![image](https://user-images.githubusercontent.com/50329121/132788834-0b384772-5c37-4fbc-a4df-301d9cb18878.png)

**Your System**
![image](https://user-images.githubusercontent.com/50329121/132789131-b27ff94f-a5c1-44ca-bd67-bdbb432fa245.png)
![image](https://user-images.githubusercontent.com/50329121/132789224-3ad197d9-8c20-4a76-b887-56bbbc3e9f03.png)

**Comment by taooceros** [comment]
try typing `reload plugin data`.

**Comment by jjw24** [comment]
@YouMoeYi you can also press F5 when the query window is open to reload. 

Newly added bookmarks won't be added into flow straight away, so you need to reload the data to get them.

@taooceros do U remember if we added auto reload bookmarks/plugin data or was it just for Program plugin?

**Comment by taooceros** [comment]
Only for program plugin.

**Comment by YouMoeYi** [comment]
> try typing `reload plugin data`.

Thx a lot, but I think if it can automatically reload, it gonna be better~

**Comment by taooceros** [comment]
> > try typing `reload plugin data`.
> 
> Thx a lot, but I think if it can automatically reload, it gonna be better~

Let's see whether there's some way to detect file change.
