### ISSUE TITLE
New Windows Terminal can not be opened as Admin

### ISSUE THREAD

**Issue by Neolize** [Flow-Launcher/Flow.Launcher#690]
**Describe the bug/issue**
I want to be able to open the new Windows Terminal as an Admin with Flow, but whenever I search and press Shift+Enter there is no "Open as Admin" option as there is for other software. 

Is there something I am missing?

**To Reproduce**
1. Open Flow
2. Search "Terminal" 
3. Choose first one 
4. Press Shift+Enter 
5. No option for "open as Admin".

**Your System**
```
Windows build number:  10.0.19043.1165
Flow Launcher version: 1.8.3

**Comment by jjw24** [comment]
Hey, at the moment uwp apps do not support running as admin, but this will be added via the upcoming 1.9.0 release. You can get early access via https://github.com/Flow-Launcher/Flow.Launcher/discussions/640

**Comment by jjw24** [comment]
Closed, please reopen if not resolved.

**Comment by Neolize** [comment]
Hey, 
Thank you for the quick response. I think that I am going to wait for the 1.9.0 release. 

Thanks for your efforts with Flow Launcher. I have recommended it to many friends already. :)

**Comment by jjw24** [comment]
thank you, great to hear you are enjoying it :)
