### ISSUE TITLE
Clipboard Exception on Startup

### ISSUE THREAD

**Issue by Positron010** [Flow-Launcher/Flow.Launcher#693]
**Describe the bug/issue**
I have Flow starting on machine startup. Each time I restart my PC, I get this .NET error when Flow starts. I then get a dialog to either quit Flow, or continue. If I continue, Flow works normally. Here is the exception text:

```
Clipboard Operation Failed

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Your System**
```
Windows build number: Windows 11 Insider Dev - 22458.1000
Flow Launcher version: 1.8.3
```
**Flow Launcher Error Log**
[2021-09-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7189732/2021-09-18.txt)

**Comment by taooceros** [comment]
It is caused by the clipboard plugin. Is it reproducible everytime starting flow?

**Comment by Positron010** [comment]
Hi,
Thanks for your reply.
It happens whenever Flow starts with OS startup.

It doesn't happen if I start Flow after staring the OS. However, there are situations where Flow won't launch if the OS is already running until I restart. 

Thanks

**Comment by taooceros** [comment]
I found the exception has been reported before. https://github.com/Xenolphthalein/Flow.Launcher.Plugin.ClipboardHistory/issues/3
Let me see whether we can get the author of the plugin to fix it.

**Comment by jjw24** [comment]
> However, there are situations where Flow won't launch if the OS is already running until I restart.

Hey @Positron010, what do you mean by this? I found when using Flow with Clipboard plugin, that when you close flow and relaunch it, flow seems not to start up, but going into task manager, you actually see flow has a process running and terminating it will then allow flow to launch. Is this the problem you are experiencing also?

**Comment by Positron010** [comment]
Hi @jjw24,
I didn't notice that the task is still running, but I just checked now, and yes, that is indeed what is happening. I quit Flow from the tray icon, but apparently it doesn't quits, so doesn't start when I try to launch it.

**Comment by jjw24** [comment]
Yep, these are the issues coming from the clipboard plugin. We will see if we or the author can sort it out. In the mean time feel free to continue using it with the terminating task work around or uninstall the plugin.

**Comment by jjw24** [comment]
This issue should have been addressed if I am not mistaken. If not the case please reopen.

**Comment by deefrawley** [comment]
Tested on latest Flow version and no issues. @Positron010 please update Flow and if the issue is still occurring re-open the issue. Thanks
