### ISSUE TITLE
Consider changing plugin switch text

### ISSUE THREAD

**Issue by Positron010** [Flow-Launcher/Flow.Launcher#700]
**Is your feature request related to a problem? Please describe.**

The switch that enables a plugin or disables it has a somehow misleading text. When it is **on** it says **Enable**, & when it is **off** it says **disable**, which is misleading at times except that the color of the switch gives a clue, because it gives the believe that if you press the switch it will **Enable** the plugin.

**Describe the solution you'd like**

I think the text should be changed to **Enabled** & **Disabled**, to reflect the present state of the plugin, rather than as a verb.

**Comment by Garulf** [comment]
Fixed in 1.9.0, Plugins use on/off
