### ISSUE TITLE
Icon Image little cut

### ISSUE THREAD

**Issue by onesounds** [Flow-Launcher/Flow.Launcher#710]
**Describe the bug/issue**
The icon looks subtly cut.

**To Reproduce**
1. Just use

**Screenshots**
![iconcutting](https://user-images.githubusercontent.com/6903107/135073675-f9158589-d5be-40d6-b62b-6a70355f31f1.png)

I looked closely, but I don't know the cause. The problem is solved by deliberately lowering the icon size, but the desired size could not be accurately expressed.

**Comment by Zeroto521** [comment]
A simple way to test this problem is that pick up a demo plugin from https://github.com/Flow-Launcher/plugin-samples and change a bigger icon/png.

**Comment by taooceros** [comment]
Is it possible that we load the icon in a little larger size than the icon panel?

**Comment by onesounds** [comment]
I Fix it . There was no stretch attribute in the image. I added 'uniformtofill' property.
**Reference**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.stretch?view=net-5.0
