### ISSUE TITLE
Proposed enhancements to the web search plugin

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#719]
Add a translation function on top of the existing function, similar to https://english.sogou.com/, input non-English keywords, and automatically translate them into English as search keywords to open the search page.

Application Scenario.
Newbie just learn programming, search some programming related issues, often need to translate into English first and then search, very tedious.

Translated with www.DeepL.com/Translator (free version)

网页搜索插件功能增强建议（输入非英文关键词→翻译成英文→搜索英文关键词）

在现有功能基础上增加一个翻译功能，类似https://english.sogou.com/，输入非英文关键词，自动翻译成英文作为搜索关键词 打开搜索页面。

应用场景：
新手刚学编程，搜索一些编程相关的问题，经常需要先翻译成英文后再搜索，很繁琐。

**Comment by taooceros** [comment]
Please use the discussion page for feature request so people can vote for it.

请把改进建议发到github discussion来进行投票和讨论

**Comment by jjw24** [comment]
discussion: https://github.com/Flow-Launcher/Flow.Launcher/discussions/721
