### ISSUE TITLE
Default File Manager in Setting

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#730]
### Discussed in https://github.com/Flow-Launcher/Flow.Launcher/discussions/729

<div type='discussions-op-text'>

<sup>Originally posted by **sim186** October  6, 2021</sup>
Hi,

I just started to used flow launcher. Is that possibile to open a directory after the search with a different file manager?</div>

Add open with third party file manager like Everything plugin

**Comment by onesounds** [comment]
Plan
- "Default file manager" item is added to the setting window.
- file path / arg is global config
- Everything, Programs, Explorer
  - remove 'customize explorer' config.
  - using global setting
- input menu with Dropdown menu 
   - simply select 3rdparty file manager
   - Files , Total Commander, Dopus
