### ISSUE TITLE
Quick switch function when opening a file

### ISSUE THREAD

**Issue by fhwid** [Flow-Launcher/Flow.Launcher#738]
![image](https://user-images.githubusercontent.com/32697778/136406096-5584e4a4-9e1f-423f-9ec1-cc7d9fea8e0c.png)
Please consider to add a quick switch function, like the function in listary.
For example, when I want to open a file(the case in the picture), I could quickly find the file using listary. It would be very convenient.

**Comment by onesounds** [comment]
I think so too. this is the function that made the listary the no.1.
the team should make this. But It is difficult to answer that it is possible because it is a fairly complex structure.

**Comment by fanhwid** [comment]
> I think so too. this is the function that made the listary the no.1. the team should make this. But It is difficult to answer that it is possible because it is a fairly complex structure.

fluent search now support "in app search" now. Please consider add this feature

**Comment by onesounds** [comment]
> > I think so too. this is the function that made the listary the no.1. the team should make this. But It is difficult to answer that it is possible because it is a fairly complex structure.
> 
> fluent search now support "in app search" now. Please consider add this feature

Sorry, I also want this function. but team still continuing to investigate and discuss for the work. It is difficult to confirm when it will be possible.

**Comment by jjw24** [comment]
Dup of #1118
