### ISSUE TITLE
Get previous active window to plugin

### ISSUE THREAD

**Issue by r3db34rd0** [Flow-Launcher/Flow.Launcher#760]
Hello there!

I write plugins and it would be great if the plugin could get previous active window before calling flow (window header).

Thank you for your work!

**Comment by r3db34rd0** [comment]
Oh, thanks for quick reply, but I'm not that good at win api or C#, it would be handy to get it through the flow api.

**Comment by taooceros** [comment]
> Oh, thanks for quick reply, but I'm not that good at win api or C#, it would be handy to get it through the flow api.

Sorry this may not be quite possible because this is not a common api, and also the api will be hard to design due to nature is pinvoke. I think it would be better to use pinvoke directly in plugin to handle that.

It's not really hard though. https://stackoverflow.com/questions/9468476/switch-to-last-active-application-like-alt-tab/9469057#9469057

**Comment by r3db34rd0** [comment]
> 

Can you please give me a working plugin code (C# or something) which can get previous active window (before flow appear) and do something.
Still don't understand how to do this by the plugin

**Comment by taooceros** [comment]
> > 
> 
> 
> 
> Can you please give me a working plugin code (C# or something) which can get previous active window (before flow appear) and do something.
> 
> Still don't understand how to do this by the plugin 
> 
> 

Sorry i missed the message. You can check the windowswalker plugin, which includes a feature to get the previously active window. However, it use hotkey to prevent flow get to the foreground, which may not be something you want. 

I personally have limited idea how to implement this feature when i try to write that feature.

**Comment by jjw24** [comment]
Closing, feel free to reopen if further discussion is required.
