### ISSUE TITLE
Keep the order of the results

### ISSUE THREAD

**Issue by stax76** [Flow-Launcher/Flow.Launcher#768]
The order which Flow Launcher gives is not helpful for me. The current way seems arbitrary and also don't seem to be documented, I don't understand how it works. I tried the move to top feature for a while, but it did not help in the end. I rather would like to keep the order which the plugin gives, I would prefer the following order:

1. Search multiple space separated keywords in title (AND search)
2. Search multiple space separated keywords in subtitle (AND search)
3. Search uppercase characters in title, ff does find FireFox
4. Search at the start of the title
5. Search in the title
6. Search in the subtitle

That's how it worked in my [KeyLauncher](https://github.com/stax76/KeyLauncher) app, which I have used 15 years and now finally gave up. It also works like this in my new [Favorites plugin](https://github.com/stax76/Flow.Launcher.Plugin.Favorites).

1+2 AND search should also be supported by the browser bookmarks plugin, this type of searching is highly popular, used by many apps like Everything.

In wox keeping the order is supported:

https://github.com/Wox-launcher/Wox/issues/1857

It would be a great help if the plugin API would support it. I prefer to only type 2 characters when I search something, and I prefer the item that I search for being at the top of the results.

**Comment by jjw24** [comment]
>1. Search multiple space separated keywords in title (AND search)
>2. Search multiple space separated keywords in subtitle (AND search)
>3. Search uppercase characters in title, ff does find FireFox
>4. Search at the start of the title
>5. Search in the title
>6. Search in the subtitle

These should already be supported. Feel free to reopen this issue if still not addressed

**Comment by jjw24** [comment]
Feature is now available in prerelease. Can turn selection count off via result class. #3144
