### ISSUE TITLE
Copy File / Folder Path in `Context Menu`

### ISSUE THREAD

**Issue by johnathanz** [Flow-Launcher/Flow.Launcher#772]
**Is your feature request related to a problem? Please describe.**

when attaching a file to a website / SaaS requiring file upload, the Open Dialog will need a file path.

Right now to get the file or folder path, we'd have to:
1. Search for the file / folder path
2. `Ctrl+O` to bring up `Context Menu`
3. Choose the option to Open the folder containing the file
4. In File Explorer, Copy and path
5. Go to the Open Dialog and paste the folder path

**Describe the solution you'd like**

We can reduce step (3) and (4) down to a single step if there's an option in the `Context Menu` to `Copy path to Clipboard`. 

For files, this could copy the file path

For folders, this could copy the folder path

**Describe alternatives you've considered**

Alternate solution in my original Problem state above

**Additional context**

This is how Alfred currently works on the Mac.

**Comment by jjw24** [comment]
this already exists:

![image](https://user-images.githubusercontent.com/26427004/142115762-17144727-7354-4c4d-ab71-20c105aca10a.png)

but no shortcut for it though i think.
