### ISSUE TITLE
wrong case insensitive with websearch plugin

### ISSUE THREAD

**Issue by onesounds** [Flow-Launcher/Flow.Launcher#792]
**Describe the bug/issue**
When using a web search plug-in, 'case sensitive' function operates strangely.

**To Reproduce**
1. add netflix with action keywornd 'netflix' in webserach plugin
2. search netflix app
3. result.

**Screenshots**

<Img src="https://user-images.githubusercontent.com/6903107/140612952-520cfa95-654f-44ac-91d8-310fae400732.png" width="400">

<Img src="https://user-images.githubusercontent.com/6903107/140612955-4325cd7b-0465-43b8-848c-00760cfdbb9e.png" width="400">

<Img src="https://user-images.githubusercontent.com/6903107/140612962-8e4274be-7a79-425a-8908-caa2ad954290.png" width="400">

result when remove 'netflix' action keyword 

<img src="https://user-images.githubusercontent.com/6903107/140613005-9dff32d4-3df2-4859-8cc9-c3a0c4d7fddc.png" width="400">

**Comment by taooceros** [comment]
action keyword is not case insensitive. Probably we can make it case insensitive?

**Comment by deefrawley** [comment]
Old issue - closing

**Comment by jjw24** [comment]
Relates to https://github.com/Flow-Launcher/Flow.Launcher/issues/2846
