### ISSUE TITLE
update giphy for the readme app preview

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#806]
with the new UI in the upcoming 1.9.0 release, lets update the giphy used in the readme.

If there are good features that have been missed in the current giphy and should be included in this update, please list them.

If you are going to work on this please let us know/assign yourself in this issue.

**Comment by onesounds** [comment]
Since there are still functions under work, I will do it when 1.9 is almost done.
I plan to make gif short. and use a lot of images to introduce functions.

**Comment by jjw24** [comment]
As in putting images in readme? If so if we put too many wouldn't it me the readme too long?

**Comment by onesounds** [comment]
> As in putting images in readme? If so if we put too many wouldn't it make the readme too long?

If the gif is long, people don't pay attention. It is not easy to know what function it is explaining just by looking at gif now.  And Visitor have to wait see all gif.  Users who have visited github would not want to watch YouTube videos.

I think ueli's readme is a very good example, ( https://github.com/oliverschwendener/ueli ) and  Anyone who reads readme on github must be interested in what functions they have, and the content doesn't matter if it's long. I remember reading the readme carefully when I first found the flow, and the flow lacked the most explanation. 

One of the most important skills in my job is to deliver incredibly long content in 10 seconds. it's my best skill in the world. Trust me.
