### ISSUE TITLE
Error When Copying File using Everything Plugin

### ISSUE THREAD

**Issue by robertoleonardo** [Flow-Launcher/Flow.Launcher#809]
Hi - i'm getting the error in the attached log when i try to copy a flow result using the everything plugin.  i've tried reinstall the plugin, and resetting all the settings to default - no luck.  I also tried disabling teracopy entirely, but that also didn't help.  Any ideas? 
[Everything Error.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7523784/Everything.Error.txt)

**Comment by taooceros** [comment]
Hi the log suggests that it fails to open clipboard. Probably something is using clipboard at the time?

**Comment by robertoleonardo** [comment]
AH HA.  Its xyplorer and it's weird custom copy command.  if i close xy 
- it works again.  i'm sure i can figure out what settings to disable 
such that i can leave xy open and it still work right.  thanks for 
pointing me in teh right direction!

------ Original Message ------
From: "Kevin Zhang" ***@***.***>
To: "Flow-Launcher/Flow.Launcher" ***@***.***>
Cc: "robertoleonardo" ***@***.***>; "Author" 
***@***.***>
Sent: 11/11/2021 3:25:02 PM
Subject: Re: [Flow-Launcher/Flow.Launcher] Error When Copying File using 
Everything Plugin (Issue #809)

**Comment by taooceros** [comment]
No Problem. If you need any help, just @me.
