### ISSUE TITLE
The settings dialog is too high, it starts out of screen bounds

### ISSUE THREAD

**Issue by stax76** [Flow-Launcher/Flow.Launcher#813]
**Describe the bug/issue**

Using a 4K/UHD monitor at 288 DPI (300 % zoom) the settings dialog always starts out of working area bounds because the dialog height is slightly too high.

![Screenshot (9)](https://user-images.githubusercontent.com/11410540/141659913-f2df1225-1e8d-40c8-8bd2-693a30e3abf1.png)

**Comment by onesounds** [comment]
fixed. https://github.com/Flow-Launcher/Flow.Launcher/pull/810

**Comment by jjw24** [comment]
Once it's merged in, you can pick up the pre-release version with the fix from the discussion area. Also GitHub auto closes issue when pr linked is merged :)
