### ISSUE TITLE
1.8.3 configuration is lost, the plug-in can not be used

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#816]
Yesterday, a window popped up when I turned on the computer to specify the path to python, but later I realized it was from Flow-Launcher, and the original configuration information was gone when I opened the software settings screen. How can I solve the problem that the web search plugin does not work?

windows version 21H1 (OS internal version 19043.1348)

Translated with www.DeepL.com/Translator (free version)

1.8.3配置丢失，插件不能使用
昨天开机时突然弹出一个要指定python路径的窗口，后来才知道是来自Flow-Launcher，打开软件设置界面原来的配置信息都不在了，插件的设置还在，但是网页搜索插件不能使用。请问该如何解决这个网页搜索插件不能使用的问题？

**Comment by onesounds** [comment]
程序正常运行吗？ 如果可以的话，只有网页搜索插件有问题吗？
如有发生错误的log，请上传。
settings.json完全初始化了吗？ 请用编辑器确认配置文件内容。 如按现有设置请上传。
4. 如果马上使用有问题，请完全删除settings.json，重新使用。 或者尝试其他版本。https://github.com/Flow-Launcher/Flow.Launcher/discussions/640

**Comment by photkey** [comment]
1.

**Comment by photkey** [comment]
1.程序正常运行，其它插件我都没有用过，只用网页搜索这一个插件；刚试了一下计算器的功能是正常的。
3.settings.json看了一下，发生错误前的那个版本备份文件是空的，我把1.7.2的settings.json这个文件复制过来网页搜索插件可以使用；
4.我完全删除settings.json还是不能用网页搜索插件，重新配置，网页搜索插件里面的信息还在，但还是不能用。

我决定全部删除重新配置。

**Comment by taooceros** [comment]
网页搜索的配置在settings/plugins/flow. Launcher.plugin.websearch里面，你可以看看里面的数据是否是正常的。
