### ISSUE TITLE
Error notification 'Plugin Manifest Download Failed'

### ISSUE THREAD

**Issue by stax76** [Flow-Launcher/Flow.Launcher#819]
**Describe the bug/issue**

My PC starts much faster than my cable modem, because of that I don't have internet when Flow Launcher starts, my cable modem needs 2-3 minutes to get all services online. I'm getting an error notification every start: 'Plugin Manifest Download Failed', I get this error notification even though I've Plugin Manager and Plugin Indicator disabled.

It seems to be a common app problem, I use another app called 'Unified Remote' that won't even work because of that, I had to delay the start with a powershell script. I can work around it that way too, but wonder for what the manifest is needed? Connecting to the internet without explicitly asking before is uncommon I think, I don't remember if there was a question.

**Comment by onesounds** [comment]
The problem seems to have been missed because it was not tested offline. We will add processing when offline.

**Comment by onesounds** [comment]
- [ ] Do not inquire the plug-in list when running a flow.
- [ ] When opening the settings window, try to import the plug-in list.
- [ ] If the network is not connected, display No Connection in the plug-in store menu.

![image](https://user-images.githubusercontent.com/6903107/141884042-35f87de8-5a6b-46a2-bb6c-23141cfb74d9.png)

**Comment by stax76** [comment]
Thanks for fixing it.

I will probably leave all notifications disabled because when I refresh the catalog with F5 (which I often do because of the Favorites plugin) it creates a notification, problem is the taskbar shows now that there is a new notification, which I find disturbing, so I confirm and hide it with a bunch of clicks. This issue is also common, and other apps solve it by letting the user customize which notifications are shown. It's a very little issue and something I could address in the Favorites plugin.
