### ISSUE TITLE
Youtube Plugin causes Error, yet it works

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#82]
When Flow starts (after a (re)boot) it prompts me:

![image](https://user-images.githubusercontent.com/9831678/85929406-c069ba80-b8b4-11ea-8e0e-de2b800c77b8.png)

However the plugin itself is working

**Comment by jjw24** [comment]
Hey @Kalaschnik , Flow already has youtube search in the Web Searches plugin. Is there any functionalities that you want from Youtube Query plugin?

The Youtube Query plugin actually failed to load and you were using the Web Searches plugin instead.

At the moment Flow is yet supporting non-Flow plugins (different plugin model). I am still working on that. I will open an discussion on how to support them.

If there is any plugins from Wox you would like and find useful, put it through as an issue and i will convert it to Flow's plugin model.

**Comment by Kalaschnik** [comment]
🤦‍♂️
