### ISSUE TITLE
Force Restart/Shutdown Cause Unexpected Setting Saved

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#820]
前天反馈同样的问题，使用的是 1.8.3版本，win10系统 21H1；
我一气之下就把之前的软件全删了，重新下载的v1.9.0 从零开始配置，并且系统也升级到了win11 21H2，结果出现了完全一样的问题，网页搜索插件设置的信息还在，但配置文件中不见了。
发现两次出问题时 setting.json都被清空了。

这次我我把log、网页搜索插件、setting.json、插件的截图，一起打包上传上来了。
[Log+setting.json+插件截图.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/7548221/Log%2Bsetting.json%2B.zip)

**Comment by photkey** [comment]
表述不够清楚，补充一下：网页搜索插件还在，只是我自己添加的条目不能使用，只能使用默认自带的那些。

**Comment by taooceros** [comment]
是重启之后的问题？还是直接加也不行

**Comment by photkey** [comment]
重启之后的问题，刚添加上是可以使用的，重启几次以后才发生的这种情况。

**Comment by taooceros** [comment]
有可能是你重启的时候强制重启了，导致flow保存出错，目前不确定怎么解决这个问题

**Comment by taooceros** [comment]
你可以帮忙看看有没有办法稳定重现

**Comment by jjw24** [comment]
maybe see if this occurs when in Windows Sandbox? Need to isolate if the problem is related to your computer's environment.

**Comment by taooceros** [comment]
@jjw24 i wonder how can we fix this? Create a backup system? It's hard to reproduce and hard to track what's the reason behind it.

**Comment by jjw24** [comment]
See if it is still happening with 1.9.3? @taooceros have you had it happen to you? I have never had this issue before. 

A backup system is way too much effort I feel with an error like this, you need to add intermittently writing to disk with a timer that runs in the background, and also may have to eventually expose to the ui the setting for adjusting how long the autosave should be.

Building a special debug version might be simpler if the user is still having this issue.

**Comment by taooceros** [comment]
It happens only once. I don't believe we have introduced any change that may fix this. I also think it is a bit too much to build a backup system. Maybe we can follow chromium bookmark save process to kindly prevent this happening.
1. Create a alternative file
2. Write change to that file
3. Delete Original File
4. Rename new file to original file

Therefore, it maybe more robust in this kind of situation.

**Comment by jjw24** [comment]
Yeah this sounds ok.

**Comment by photkey** [comment]
@jjw24 @taooceros 
这个问题在1.9.3依然发生过，而且是在我旧电脑（重做过系统）以及新电脑都上有发生过。以至于我一度放弃使用Flow，但因为换其它软件 实在是没用Flow用着顺手，又换回来了……
最近一次的配置丢失，我发现是配置文件还在，但是配置文件里面都是一堆不可读的乱码。
我现在用的时候 都是每次对Folw做了任何配置修改 都及时的全部打包备份一次，以防万一。

我觉得创建配置文件备份应该也是不错的选择，起码比整体打包备份要好一些。

另外，如果只在我一个人身上发生过，我觉得合有可能是跟我电脑上的某个软件冲突了，要不然不可能在我的新旧电脑、新旧系统上都发生同样的事情。或者其它人也遇到过，只是没提issue……

**Comment by jjw24** [comment]
> It happens only once. I don't believe we have introduced any change that may fix this. I also think it is a bit too much to build a backup system. Maybe we can follow chromium bookmark save process to kindly prevent this happening.
> 
> 1. Create a alternative file
> 2. Write change to that file
> 3. Delete Original File
> 4. Rename new file to original file
> 
> Therefore, it maybe more robust in this kind of situation.

I think this solution will be the best way forward.

**Comment by deefrawley** [comment]
@jjw24 - has this been implemented?

**Comment by jjw24** [comment]
Yes, we have redone our setting file save logic. Please reopen if issue still occurs.
