### ISSUE TITLE
Clearing Launcher Hotkey does not disable existing hotkey

### ISSUE THREAD

**Issue by jeremymeyers** [Flow-Launcher/Flow.Launcher#821]
**Describe the bug/issue**
After hitting the "X" button on "Flow Launcher Hotkey" in the config screen, the hotkey you just cleared will still bring up the Launcher

**To Reproduce**
1. Navigate to the "Hotkey" section of setup
2. Assign a hotkey (like Home button)
3. Hit the X button (it will say "Success"
4. Press the old hotkey

**Screenshots**

**Your System**
```
Windows build number: 10.0.19043 N/A Build 19043
Flow Launcher version: 1.8.3

**Comment by onesounds** [comment]
I'll check. 
You were trying to make a situation where there was no shortcut key at all, right?

I'm planning If the focus is lost without any content, I considering opening a confirmation window to "remove the shortcut key at all?". or whole redesign hotkey like powertoy.

**Comment by jjw24** [comment]
maybe the behaviour on clicking X should be returning it to the previously set hotkey, because you always need a hotkey to trigger flow, unless we allow no hotkey configuration.

**Comment by onesounds** [comment]
> maybe the behaviour on clicking X should be returning it to the previously set hotkey, because you always need a hotkey to trigger flow, unless we allow no hotkey configuration.

true. But I think there will be some situations where it needs to be removed. (powertoy : impossible / fluent and etc : possible) Of course, the easy way is just block the way to remove it.

If there is no problem removing the shortcut, I will work on some UIs. (confrim popup, warning UI, etc.) also I think there will be necessary situations when playing games, so it would be good to have a temporary deactivation function through the tray menu. I'll think about it because the priority is low.

**Comment by jjw24** [comment]
ok sounds good

**Comment by jeremymeyers** [comment]
> I'll check. You were trying to make a situation where there was no shortcut key at all, right?
> 
> I'm planning If the focus is lost without any content, I considering opening a confirmation window to "remove the shortcut key at all?". or whole redesign hotkey like powertoy.

Well more like i'd accidently set the hotkey to the spacebar and needed to clear it out.  

My original goal was to set the hotkey to windowskey+SpaceBar but that doesn't seem possible.

Would also like to suggest (Tho this might need its own report) that if you arent actually able to manually type into the hotkey box (like if i wanted to just type "Alt + Spacebar") that there should be some visual cue that it is not a standard textbox as used elsewhere in the config

**Comment by deefrawley** [comment]
@jjw24 fixed recently? Ok to close?

**Comment by onesounds** [comment]
> @jjw24 fixed recently? Ok to close?
It's not fixed yet - I putting it off because we need to fix the hotkey registration UI overall. t's a lot of work.

**Comment by deefrawley** [comment]
No worries, let's leave it open

**Comment by VictoriousRaptor** [comment]
Should have been fixed. Feel free to reopen if still persists.
