### ISSUE TITLE
win11 v1.9.0 命令行窗口运行完不能自动关闭

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#828]
**Describe the bug/issue**
命令行插件，共有两个问题

1：运行完不能自动关闭，在Flow之前版本、Win10系统下 是没有问题的。

2.我设置了相当于bash下的alias，比方 “enso = python D:\path\xxx.py $*”，直接是从系统打开cmd 可以使用没问题，但是从Flow的命令行插件运行时，这个别名的设置无效。

说一下这个的使用场景：因为实在是不会写Flow插件，我就想了个曲线救国的办法，用命令行插件，执行python脚本（实现输入中文 自动翻译成英文 并同时从github、google等打开搜索链接），但是输入“python D:\path\xxx.py”  太麻烦了，虽然可以通过设置快捷键 解决输入麻烦的问题，但是太长了看起来也不舒服。所以就设置了个别名，也就发现这个问题了。
设置别名的资料来自：https://mlog.club/article/2597370

![Snipaste_2021-11-26_02-26-20](https://user-images.githubusercontent.com/60434581/143488279-532c0dd6-d371-4b2f-9619-6d42785d200a.png)
![设置](https://user-images.githubusercontent.com/60434581/143488373-b5e88ccf-0718-4ce0-bb28-1cb10a6545c8.png)

Windows11 版本 21H2 (OS 内部版本 22000.348)，v1.9.0

**Comment by taooceros** [comment]
Check this build https://ci.appveyor.com/project/JohnTheGr8/flow-launcher/builds/41671808/artifacts
