### ISSUE TITLE
Different Flow Icon for missing App Icon

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#84]
I would propose a different and more neutral Icon, if an app icon was not found. I actually thought that `app_error.png` was used for more critical conditions.
![image](https://user-images.githubusercontent.com/9831678/85940507-1ffbb080-b91d-11ea-87ff-e3e736b70f79.png)

This indicated that something is wrong with Spotify, maybe a question mark is the better choice here?!

**Comment by jjw24** [comment]
Good idea

**Comment by ArttuLai** [comment]
For example PowerToys Run uses a generic window icon for missing apps and I think it works well — not that it means you should use one too. I also think the red sad face looks like shouldn't press that button, and it looks like warning.

<img width="541" alt="ptrunGenericAppIcon" src="https://user-images.githubusercontent.com/42007282/91642331-36b0a780-ea33-11ea-9207-1278ae4f9674.png">

Maybe it could be something like that? I even made a quick mockup just to show what I was thinking 🙂

![genericApp (128x128)](https://user-images.githubusercontent.com/42007282/91642450-31a02800-ea34-11ea-9b07-fa0afcb1f506.png)

**Comment by ArttuLai** [comment]
<img width="641" alt="genericAppMockup" src="https://user-images.githubusercontent.com/42007282/91642794-e63b4900-ea36-11ea-9fe8-f6c1ea3a0d17.png">

**Comment by Kalaschnik** [comment]
I prefer your version over the MDL2 Icons, which are here for reference:
https://github.com/microsoft/PowerToys/tree/master/src/modules/launcher/PowerLauncher/Images

However, it looks a bit macOSish — is this your asset/can you modify it to look more Windows-like?

**Comment by ArttuLai** [comment]
> However, it looks a bit macOSish — is this your asset/can you modify it to look more Windows-like?

I agree, it looks kinda Mac-like now that you said it 😅 I was going for something like the new Fluent app icons by Microsoft. But it's mine and I can modify it / see what I can do.

**Comment by Kalaschnik** [comment]
> @Kalaschnik I agree, it looks kinda Mac-like now that you said it 😅 I was going for something like the new Fluent app icons by Microsoft. 

That’s cool. I had the same intension for the Flow logo :)

**Comment by ArttuLai** [comment]
@Kalaschnik OK I made some variants:

https://1drv.ms/u/s!Aj_Hiawo_tA7iMJxSZdKcKN2RPwhGg?e=DKrWQb

Anyone is free to use these. And do tell if you want them at more proper sizes/filetypes, I have no idea what I'm doing. There's one PNG and one SVG of each picture at 2000x2000 resolution.

**Comment by jjw24** [comment]
I quite  dig this one (although havent tried how it looks in Flow)
![image](https://user-images.githubusercontent.com/26427004/91707943-ea48a180-ebc3-11ea-9169-5b72dd254d72.png)

**Comment by Kalaschnik** [comment]
I second jjw24’s preference, although if the icon is shown within small dimensions, the windows logo is not easy to spot, maybe bump it up just a bit more?
![image](https://user-images.githubusercontent.com/9831678/91724201-3f24f180-eb9d-11ea-9180-d670ad35d293.png)

Thank you!

**Comment by ArttuLai** [comment]
Yeah it's a bit dim. I'll post a new icon to the folder soon.

**Comment by jjw24** [comment]
> Yeah it's a bit dim. I'll post a new icon to the folder soon.
> 
> EDIT: Done. Yeah didn't realize exporting somehow messes with transparency and it doesn't look like it does in Affinity.

Hey thanks so much for them @ArttuLai. Do you think you can chuck them into a PR?

We will need to update the code to point to the image file, let's call it 'app_missing_iconimg'- would you be able to make the changes @ArttuLai ?

**Comment by ArttuLai** [comment]
@jjw24 @Kalaschnik No problem, happy to contribute!

Also I'm extremely noob at this so don't laugh if I messed up the PR 🙂

**Comment by ArttuLai** [comment]
@Kalaschnik @jjw24 Would it be correct if I do following:

1. Upload 'app_missing_img.png' (256x256 px like the original) to Flow.Launcher/Flow.Launcher/Images/
2. Update Constant.cs (in Flow.Launcher/Flow.Launcher.Infrastructure/) to point to said image. Like this:

![constantcs](https://user-images.githubusercontent.com/42007282/92014540-1432cd00-ed58-11ea-882e-6b81095f000e.png)

If that's not how you do it, then idk, probably easier if you guys just use the files I shared and do it properly. I can figure it out otherwise (I think!). I already made a PR but that doesn't have everything in it — I thought at first you meant I should upload the image only.

**Comment by jjw24** [comment]
> @jjw24 @Kalaschnik No problem, happy to contribute!
> 
> Also I'm extremely noob at this so don't laugh if I messed up the PR 🙂

All good, always happy to help out if needed as well.

> If that's not how you do it, then idk, probably easier if you guys just use the files I shared and do it properly. I can figure it out otherwise (I think!). I already made a PR but that doesn't have everything in it — I thought at first you meant I should upload the image only.

Yep that's what I meant, throw in a PR with all the files, then if you are familiar with the code then update it to use it. If not we can merge the PR first.

I am working on something else at the moment, once done I can update the code to use your image.

**Comment by jjw24** [comment]
All done, thanks again. Will update the code later to utilise it

**Comment by jjw24** [comment]
PR is in https://github.com/Flow-Launcher/Flow.Launcher/pull/154
