### ISSUE TITLE
App Icon missing

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#85]
Although Spotify is installed, its icon is missing:

![image](https://user-images.githubusercontent.com/9831678/85940645-dd86a380-b91d-11ea-9e77-59b5f89625e5.png)

What is going on here? I think I had the same experience in some Apps for Wox...

**Comment by jjw24** [comment]
Let me see if I can repro. I have. Ever installed Spotify on PC before, did you get it from the Microsoft store or downloaded from their website?

**Comment by jjw24** [comment]
tested on a new vm, seems to be fine for me
![image](https://user-images.githubusercontent.com/26427004/85958826-d4f4a280-b9db-11ea-8ea8-8a4c9f8fb10a.png)

can you 'Reload Plugin Data' and see if it is fixed.

**Comment by Kalaschnik** [comment]
💡 Re-indixing was fixing the missing icons!

I wonder if re-indexing could be run automatically from time to time? Or if this could be event triggered by an installation?

**Comment by jjw24** [comment]
> 💡 Re-indixing was fixing the missing icons!
> 
> I wonder if re-indexing could be run automatically from time to time? Or if this could be event triggered by an installation?

it runs reindex after start up if hasnt been run  > 3 days since last one.

it would be ideal but hard to do something like a trigger run after a program installation.

i will close this for now. Let me know if you want to reopen  :)
