### ISSUE TITLE
Flow Icon is pixelated

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#86]
![image](https://user-images.githubusercontent.com/9831678/85940681-16267d00-b91e-11ea-9894-22c6d03f295b.png)

I try to figure out why this is happening... maybe it is an issue with the ico containing multiple sizes? Maybe a 16×16 ico might fix this...

This is also happening in the taskbar, compared to its neighbours:
![image](https://user-images.githubusercontent.com/9831678/85940721-6b628e80-b91e-11ea-8b83-d2b837444a05.png)

The tray icon seems fine to me though...

**Comment by jjw24** [comment]
That's interesting pick up. Can you put in a 16 X 16 ico in or and I will test it out.

I haven't notice the pixelation on my machine though.

**Comment by jjw24** [comment]
Closing, please reopen if still an issue.
