### ISSUE TITLE
Redundant colon in plugin info

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#861]
![obrázok_2021-12-04_110705](https://user-images.githubusercontent.com/37414585/144705600-409f15c3-7780-4aa0-b5ad-54d9de480479.png)

Author contain redundant colon.

**Comment by onesounds** [comment]
I checked. but I think it's better to leave the Title part and get rid of Author and website.
What do you all think? @jjw24 @taooceros @kubalav @Garulf

**Comment by kubalav** [comment]
Website isn't clickable, it can be removed.

**Comment by taooceros** [comment]
I think it would be better to let enter go to the plugin website?

**Comment by Garulf** [comment]
```
Title: Plugin: <Plugin Name>
SubTitle: By <Author name>
```
Example:
```
Plugin: Steam Search
By Garulf
```
Takes you to Plugin's website on click

**Comment by onesounds** [comment]
We can go to the website, but I don't think it's meaningful to move with in this situation.
(Who is visiting the plug-in website in this situation?)
It is meaningful to tell you what plug-in is working, but other than that, it is meaningless.
These are unnecessary information. It feels like handing over the responsibility to the plug-in developer functionally, I think eliminating such information can give plug-in developers a feeling that they are included in the software.

**Comment by onesounds** [comment]
It would be better to open the setting window of the plug-in.

**Comment by Garulf** [comment]
> 2. open the setting panel of plugin when run this item.

Good idea, I like this option even better.

**Comment by jjw24** [comment]
> It would be better to open the setting window of the plug-in.
> 
> This is my conclusion.
> 
> 1. Remove Subtitle text (author and website or only leave author)
> 2. open the setting panel of plugin when run this item.
> 
> Does anyone have any dissenting opinions? If not, I will proceed like this.

Sounds good.

**Comment by taooceros** [comment]
For 1.9, I think it would be better to simply remove the extra colon and do the rest of work in the future.

**Comment by jjw24** [comment]
sounds good

**Comment by kubalav** [comment]
Fixed.
