### ISSUE TITLE
Error when activate translate plugin Direct Traslate

### ISSUE THREAD

**Issue by 7yang7** [Flow-Launcher/Flow.Launcher#884]
**Describe the bug/issue**

An error appears when activating the plugin

**To Reproduce**
1. Press Alt+Space
2. I type tr and press Space to activate the plugin 

**Screenshots**
![image](https://user-images.githubusercontent.com/71559582/145382653-7318eaee-98c9-440f-85fd-449fa4000760.png)

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.22000.348
Flow Launcher version: 1.9.0 
```
**Flow Launcher Error Log**

[2021-12-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7684420/2021-12-09.txt)

**Comment by deefrawley** [comment]
This is actually an error with the plugin. I have created [this](https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate/pull/10) PR to assist the author in fixing the issue.

**Comment by Garulf** [comment]
Please see https://github.com/Flow-Launcher/Flow.Launcher/issues/889 for temporary fix.
