### ISSUE TITLE
Strings not translatable

### ISSUE THREAD

**Issue by smarquespt** [Flow-Launcher/Flow.Launcher#901]
After reviewing my work in Flow Launcher translation, I've found ou some strings that are not translatable. Please check below screenshots:

![screen1](https://user-images.githubusercontent.com/1302668/145903343-a8682127-a677-4408-8485-6d8903271052.png)

_Settings - General_

![screen2](https://user-images.githubusercontent.com/1302668/145903346-8f4608c1-cb98-454e-912b-b7ebb6ad6fd1.png)
![screen3](https://user-images.githubusercontent.com/1302668/145903347-68190c93-3895-44cb-a816-82c1494672c1.png)

*Windows Settings - Tooltip*

![screen4](https://user-images.githubusercontent.com/1302668/145903349-d16d96a3-556c-4843-809e-51965d012360.png)

*Browser Bookmarks*

![screen5](https://user-images.githubusercontent.com/1302668/145903350-4c81bb3a-249a-48d3-b2f6-7aa64925bb7b.png)

**Comment by taooceros** [comment]
Some translation hasn't been merged. Details are here.
https://github.com/Flow-Launcher/Flow.Launcher/pull/885

You can try the CI build here. I will merge dev to trigger that soon.

**Comment by taooceros** [comment]
Portable:
https://ci.appveyor.com/api/buildjobs/0ye1nljxvue5ilw6/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
Setup:
https://ci.appveyor.com/api/buildjobs/0ye1nljxvue5ilw6/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

**Comment by smarquespt** [comment]
I've also found some strings that do not fit in available space. Any change to work on this padding?

*Settings - General - Last Query Style*

![screen1](https://user-images.githubusercontent.com/1302668/145904166-4df2b53c-5cec-4d1e-bdec-e4d7c7250292.png)

*Settings - Plugins - Shell Plugin*

![screen2](https://user-images.githubusercontent.com/1302668/145904364-d94abe83-1ea2-467d-a1cc-d2a2493ae396.png)

*Settings - Plugins - Explorer Plugin*

![screen3](https://user-images.githubusercontent.com/1302668/145904471-04339ab7-8a59-4aa6-89ea-1bef2f80a2a6.png)

*Settings - Plugins - Plugin Manager*

![screen4](https://user-images.githubusercontent.com/1302668/145904583-7d0c14af-9401-4305-88dc-b95c24c01917.png)

*Settings - Plugins - Program Plugin*

![screen5](https://user-images.githubusercontent.com/1302668/145904762-3acca429-a514-49c3-ab0a-4ac5999da1df.png)

**Comment by smarquespt** [comment]
> Some translation hasn't been merged. Details are here. #885
> 
> You can try the CI build. I will merge dev to trigger that soon.

That is not the case. The strings don't exist in source files.

**Comment by taooceros** [comment]
> > Some translation hasn't been merged. Details are here. #885
> > You can try the CI build. I will merge dev to trigger that soon.
> 
> That is not the case. The strings don't exist in source files.

Oh I see. I will take a look on that tonight. Probably they are hardcoded now.

> I've also found some strings that do not fit in available space. Any change to work on this padding?

@onesounds

**Comment by smarquespt** [comment]
Great. Thanks

**Comment by onesounds** [comment]
![image](https://user-images.githubusercontent.com/6903107/145990576-490b5f62-d6cf-4d0f-bd5a-98042c05e3fb.png)

- The first item is supposed to be tailored to the language of os. You can fix it to use translation, but in this case, all other languages have to be added, so there is a lot of work. If I think this part is necessary later, I will fix it other pr.

@taooceros  you should check 3.
- Default Web Browser Item in general / and window Strings (In xaml, it appears to be translatable.)
- Last Query Style not reflecting real time. (only in UI display, setting works in realtime.)
- need plugin's version bump?

**Comment by taooceros** [comment]
> Last Query Style not reflecting real time. (only in UI display, setting works in realtime.)

You mean language?

**Comment by smarquespt** [comment]
Web Browser Plugin is not on Crowdin.

![image](https://user-images.githubusercontent.com/1302668/146043805-4d584cb7-ffa4-4059-b037-16168dfea7dc.png)

**Comment by onesounds** [comment]
> > Last Query Style not reflecting real time. (only in UI display, setting works in realtime.)
> 
> You mean language?

https://user-images.githubusercontent.com/6903107/146057470-009d6448-de02-4e57-8c15-5fd345be2f97.mp4

**Comment by onesounds** [comment]
- In addition, several places with size problems were identified and corrected.
- It was confirmed that the Context menu did not change depending on the language. This was also changed so that it could be changed to a string.

**Comment by smarquespt** [comment]
@onesounds 

"Priviate Mode" should also be changed to "Private Mode".

**Comment by onesounds** [comment]
> "Priviate Mode" should be changed to "Private Mode" "Bookmmark Data" should be changed to "Bookmark Data"

😂 I checked and Fixing in https://github.com/Flow-Launcher/Flow.Launcher/pull/922 
Thanks. Feel free to let me know if you find more.

**Comment by taooceros** [comment]
> Last Query Style not reflecting real time. (only in UI display, setting works in realtime.)

This is hard, and the solution is a bit hacky, so just leave it like that.

**Comment by smarquespt** [comment]
![screen1](https://user-images.githubusercontent.com/1302668/147351802-d074daa4-f423-4119-a8b9-56073e7b66e0.png)
![screen2](https://user-images.githubusercontent.com/1302668/147351805-894abb3b-b205-4c9e-9cce-691207e6a21a.png)
![screen3](https://user-images.githubusercontent.com/1302668/147351806-b3d8ca45-095d-4700-b79b-2b6c6413d7c9.png)
![screen4](https://user-images.githubusercontent.com/1302668/147351807-0bb5c949-c9f1-4a12-8240-b64d956672d6.png)

**Comment by smarquespt** [comment]
All others reported seem finge. Great job @onesounds

**Comment by taooceros** [comment]
> Not related but should't this be the opposite? Enabled to the right and disabled to the left?

![image](https://user-images.githubusercontent.com/45326534/147570414-66fbbcc9-4399-4c07-a420-3b32b0d84646.png)

I think the latest version has revised that to on/off.


> These strings are in #880 so I'm not sure whats the problem here? Maybe I've got wrong appveyor artifact?

I will take a look on that now.

**Comment by taooceros** [comment]
I will fix the NewTab and New Window. The "default" is harder to fix because it is hard coded, so just leave it there for now.

**Comment by smarquespt** [comment]
> > Not related but should't this be the opposite? Enabled to the right and disabled to the left?
> 
> ![image](https://user-images.githubusercontent.com/45326534/147570414-66fbbcc9-4399-4c07-a420-3b32b0d84646.png)
> 
> I think the latest version has revised that to on/off.
> 
The issue is not the text but the switch. If Off, switch to the left and vice-versa.

![image](https://user-images.githubusercontent.com/1302668/148042306-898937c7-998e-4ad1-a4f2-ceee833c1e05.png)

**Comment by onesounds** [comment]
> > > Not related but should't this be the opposite? Enabled to the right and disabled to the left?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45326534/147570414-66fbbcc9-4399-4c07-a420-3b32b0d84646.png)
> > I think the latest version has revised that to on/off.
> 
> The issue is not the text but the switch. If Off, switch to the left and vice-versa.
> 
> ![image](https://user-images.githubusercontent.com/1302668/148042306-898937c7-998e-4ad1-a4f2-ceee833c1e05.png)

https://github.com/Flow-Launcher/Flow.Launcher/pull/952 Done. It will be revised in the next version.

**Comment by onesounds** [comment]
> The issue is not the text but the switch. If Off, switch to the left and vice-versa.

 #952 Done. It will be revised in the next version.

**Comment by taooceros** [comment]
Closing until further issue.

**Comment by smarquespt** [comment]
@taooceros with Portuguese language, on first usage of the app, text is cutted. Is it possible a fix or should I try to reduce string size?

![Image](https://github.com/user-attachments/assets/f9af3afc-8cad-48e3-9b6f-874424f1100b)

**Comment by smarquespt** [comment]
And in image below, part of the letter p is also cutted:

![Image](https://github.com/user-attachments/assets/5c27edaf-a4f0-4fde-ad79-6283f2cbb6d1)

**Comment by smarquespt** [comment]
On settings, maybe also a problem?

![Image](https://github.com/user-attachments/assets/b1515dd4-275d-4b54-900c-5b1e5d2e0c91)

On Crowdin:

![Image](https://github.com/user-attachments/assets/a9d30147-5803-4924-b9a8-54fd2b84b9e8)

**Comment by onesounds** [comment]
@smarquespt I've checked the issues, and I'll work on them myself. If you discover any additional issues or want to track progress separately, please create a new issue post. (I tend not to revisit closed posts.)

+) Fixed in #3683
