### ISSUE TITLE
[Feature request] Jump to last open explorer folder

### ISSUE THREAD

**Issue by privacy-advo** [Flow-Launcher/Flow.Launcher#906]
**Problem**
It's very annoying and time consuming to copy and paste a path or manually click trough windows explorer once you are in e.g. another program or eg an upload popup on a website.  It's blazing fast to have a shortcut and cuts a lot of clicking everyday. 

**Solution**
I would love to jump via a shortcut (ctrl+g) to the last opened explorer folder. 

**Describe alternatives**
Using Listary - even though it's outdated and has a horrible high dpi scaling.

**Comment by onesounds** [comment]
I like the function very much, too.  There is a plan for the Listary function work. It is currently under discussion. The exact schedule has not been set.

**Comment by wu-yue-yu** [comment]
To be honest, that's why I'm still using listary.
I like Flow.Luancher a lot. I'm looking foward to replacing listary with Flow.Luancher.
Thanks for developing such an amazing software😄.
Listary has already been abandoned by its developer.

**Comment by taooceros** [comment]
The feature has been implemented, but hasn't been brought to flow (although not as perfect as listary because of the limited documentation). We may try to integrate it soon.

**Comment by jjw24** [comment]
Dup of #1117
