### ISSUE TITLE
Blur effect extends beyond boundaries of launcher window

### ISSUE THREAD

**Issue by EliSadaka** [Flow-Launcher/Flow.Launcher#92]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Select the BlurBlack or BlurWhite theme with the default settings
2. Activate the launcher to see the blur effect extending beyond the launcher window
3. Switch to a non-blur theme to see that the bug is still visible
4. Restart Flow Launcher to see that the bug is now gone until a blur theme is selected again

### Flow Launcher Error Window text

None

### Detailed logs

[2020-06-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/4847567/2020-06-29.txt)

### Screenshots (optional)

![flow2](https://user-images.githubusercontent.com/35779188/86045660-e3fa4580-ba19-11ea-8b7e-626f527053c2.jpg)

![flow3](https://user-images.githubusercontent.com/35779188/86046305-ff198500-ba1a-11ea-906c-5f740208ef7f.jpg)

**Comment by jjw24** [comment]
I was able to fix it by delete the userdata folder and let flow recreate it. After which I was not able to repro the bug again. Can you see if it is the same for you?

**Comment by EliSadaka** [comment]
Deleting the userdata folder did fix the issue, but once I closed and restarted Flow Launcher the issue returned.

**Comment by jjw24** [comment]
Could I get you to do a clean install of v1 and test , including removing the userdata folder. You can also back up the user data folder somewhere else as well

**Comment by EliSadaka** [comment]
Here are the steps I took to reproduce the issue:

1. Uninstalled Flow Launcher and deleted the userdata folders in both Local and Roaming
2. Reinstalled the Flow Launcher and set the theme to BlurBlack
3. Closed Flow Launcher and relaunched it
4. The blur bug is visible

I still have Wox installed on my machine in case you think that might be conflicting somehow. It wasn't running when I was testing this though.

**Comment by jjw24** [comment]
> Here are the steps I took to reproduce the issue:
> 
> 1. Uninstalled Flow Launcher and deleted the userdata folders in both Local and Roaming
> 2. Reinstalled the Flow Launcher and set the theme to BlurBlack
> 3. Closed Flow Launcher and relaunched it
> 4. The blur bug is visible
> 
> I still have Wox installed on my machine in case you think that might be conflicting somehow. It wasn't running when I was testing this though.

Hey how's it going. I am able to repro now. Thanks for taking the time to explain.

To repro, select BlurBlack (for my case, it didnt have the blur extend beyond the window), close and then start up Flow, this is when the blur is extended beyond the window.
