### ISSUE TITLE
[Bug/Feature request] Currency convertor returns values after a small delay

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#924]
I would consider this a Bug/Feature request hybrid for the currency convertor plugin.

Currently the currency convertor has a small delay before it returns the converted value.

I used to use a plugin on Wox which used to give instant results.

Wanted to ask if the same would be possible in the currency convertor plugin included with flow.

Thanks.

**Comment by deefrawley** [comment]
Hi,
I'm the author of the plugin. The delay is the plugin going and downloading the XML file of currency rates. It won't do this if the file was downloaded within the last two hours (subsequent calls should be quicker). I can look at adding a windows notification through Flow of the download, extend the shelf life of the XML file or both. Probably best to open this issue in the plugin repo - https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/issues . Thanks

**Comment by rp1231** [comment]
Hi,
Thanks,
I'll open an issue in the plugin repo.
