### ISSUE TITLE
Localized badge in readme showing 0%

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#943]
Localized badge in readme showing 0%, last time I recall was at 43%

**Comment by JohnTheGr8** [comment]
I noticed this just recently:

![image](https://user-images.githubusercontent.com/697917/147851676-127452d2-631c-4d6d-96e2-fc7a0be7d736.png)

**Comment by taooceros** [comment]
I guess if that branch is merged, it will be cleared.

**Comment by taooceros** [comment]
That's a bit weird. Let me check that later. But the file can be restored so not a large issue.

**Comment by JohnTheGr8** [comment]
> I guess if that branch is merged, it will be cleared.

probably because the branch got deleted, not because the PR was merged...

**Comment by taooceros** [comment]
> > I guess if that branch is merged, it will be cleared.
> 
> probably because the branch got deleted, not because the PR was merged...

oh we still delete the crowdin branch...🤣 it shouldn't be deleted

**Comment by JohnTheGr8** [comment]
branch restored, translations restored

@jjw24 branch protection for `add_crowdin_translations` please 😄

**Comment by jjw24** [comment]
@JohnTheGr8 @taooceros i will switch it to dev branch form now on for Crowdin
