### ISSUE TITLE
Windows + R bringing up Flow Launcher even when not set as the hotkey

### ISSUE THREAD

**Issue by STaRDoGG** [Flow-Launcher/Flow.Launcher#950]
**Describe the bug/issue**

I've got my trigger hotkey set to ctrl + space .... when I press Winkey + r the FL search bar pops up. This prevents me from using the standard Windows Run hotkey.

**To Reproduce**
Press Winkey + R ...

**Screenshots**

![image](https://user-images.githubusercontent.com/1524526/147930083-51b5e706-f658-4f02-a5a0-3b95aec36800.png)

**Your System**
```
Windows build number: (run "ver" at a command prompt)
Microsoft Windows [Version 10.0.19043.1415]

Flow Launcher version: (Settings => About) 
1.9.1

```
**Flow Launcher Error Log**

[2022-01-03.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7801886/2022-01-03.txt)

**Comment by onesounds** [comment]
![image](https://user-images.githubusercontent.com/6903107/147930962-a580b7b0-3624-4f07-af89-403047f59649.png)

- Turn off "Replace Win+R" in Shell Plugin.

**Comment by STaRDoGG** [comment]
@onesounds aha! ty! Didn't pour through all the settings hard enough I guess.

**Comment by onesounds** [comment]
I've experienced the same confusion as you at first. First of all, I don't think it's a big problem because it indicates that the ">" mark is intended to appear. I'll think about how to add a simple guide.

And that plug-in is a plug-in that allows you to use shell commands. Try to get used to it.
- Turn On " Do not close command prompt after command excution"
- and try this. "> start shell:RecycleBinFolder" or "> ipconfig"

**Comment by STaRDoGG** [comment]
@onesounds Maybe FL can detect if the Shell plugin is enabled/installed/Replace Win + R is enabled, and if so, add a text link under the normal hotkey mentioning it, and clicking the link navigates to that plugin's setting.  That would make it more intuitive for people like me, lol.

Another think I just noticed that I'm not sure is intended or not; the `>` was automatically being added to the search bar when the bar was opened, and selected (highlighted), with nothing after it, presumably to make it a bit easier to run commands. But in order to run a command you'd have to first unhighlight it either manually with a mouse click, or a right arrow, and then start typing. And if you hit the delete/backspace while the `>` is selected when the bar comes up, it gets deleted, and doesn't get auto-added the next time the bar comes up. Sort of inconsistent behavior imho.

**Comment by taooceros** [comment]
It is not supposed to select the > key. I will check soon.

**Comment by taooceros** [comment]
I couldn't reproduce that flow will select > when pressed `win+r`. Could you restart flow and try again?

**Comment by STaRDoGG** [comment]
@taooceros I will try to create a short vid of it later when I get time. It seems that it's got something to do with FL keeping whatever was previously entered in the search bar in between bringing it up, whether with win+r or the regular hotkey.

For example: if I enter: `> start shell:RecycleBinFolder` and run it. the bar closes. Then if I bring it up again with any hotkey, `> start shell:RecycleBinFolder` is all automatically selected. I'm not sure if thatrs intended or not, but I think it is, so you don't have to delete the previous line.

**Comment by taooceros** [comment]
Yeah that's intended. You can config it in the setting panel. I think the option named Last Query Style.
