### ISSUE TITLE
Total commander support

### ISSUE THREAD

**Issue by fanhwid** [Flow-Launcher/Flow.Launcher#958]
I set the total commander like this:
![image](https://user-images.githubusercontent.com/72638192/148318680-12e447b7-ea21-4577-8e2b-400debd71786.png)

But when I open a folder, It didn't work. It still using windows explorer.

**Comment by taooceros** [comment]
everything plugin? it hasn't utilized the new api.

**Comment by fanhwid** [comment]
> everything plugin? it hasn't utilized the new api.

even if I disable the everything plugin, It still use explorer.

**Comment by taooceros** [comment]
> > everything plugin? it hasn't utilized the new api.
> 
> even if I disable the everything plugin, It still use explorer.

Could you share the query you type? I would like to check which plugin is handling that.

**Comment by fanhwid** [comment]
> 

![image](https://user-images.githubusercontent.com/72638192/148320054-68cf6041-ef5a-499a-b82f-d4a304bfd49f.png)
Like this.

**Comment by fanhwid** [comment]
> onedrive is a program, which will not be accessed with the directory call. You can config the quickaccess for onedrive in explorer plugin setting, and access it via that way.

OK, need I open an issue in Everything plugin page?

**Comment by taooceros** [comment]
> > onedrive is a program, which will not be accessed with the directory call. You can config the quickaccess for onedrive in explorer plugin setting, and access it via that way.
> 
> OK, need I open an issue in Everything plugin page?

no, it's in progress. Just hasn't been merged.🤓

**Comment by jjw24** [comment]
Closing since will be everything implementation, if further questions feel free to repoen.
