### ISSUE TITLE
Suggestion: move hello-world plugins to their own repository

### ISSUE THREAD

**Issue by JohnTheGr8** [Flow-Launcher/Flow.Launcher#96]
I see no reason to ship the 3 hello-world plugins with the launcher... I suggest that we move them to a separate repository, something like `plugin-samples`, and simply mention them in the plugin-development docs.

For a potential plugin developer looking for a sample plugin to base their work on, it would be much simpler this way.

**Comment by jjw24** [comment]
Agree

**Comment by JohnTheGr8** [comment]
Cool, will get to it tomorrow...
