### ISSUE TITLE
Flow.Laucher Portable - Browser Bookmarks plugin crashes at init

### ISSUE THREAD

**Issue by lostping** [Flow-Launcher/Flow.Launcher#962]
When starting Flow.Launcher the Browser Bookmarks plugin has an exception at initialisation.

**To Reproduce**
1. Start freshly extracted FlowLauncher Portable instance

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38543812/148430830-454866d7-e7c6-4e32-a6bd-574d81af44ae.png)

**System**
```
Windows build number: Microsoft Windows [Version 10.0.19044.1415]
Flow Launcher version: 1.9.1
```
**Flow Launcher Error Log**
[2022-01-06.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7823899/2022-01-06.txt)

**Comment by taooceros** [comment]
Could you share the  Bookmark files of your chrome? It should be %localappdata%\Google\Chrome\User Data\Bookmarks

**Comment by lostping** [comment]
That folder structure doesn't exist. I don't have Chrome installed.
I had Chrome Canary for some test reasons (years ago) but it's uninstalled.

**Comment by taooceros** [comment]
Well Boormarks is not a directory, it is a file😂.
Probably it happens because the canary version has a different layout of bookmark storage. ~~~~
