### ISSUE TITLE
Instead of opening a new window, can it switch to the opened window??

### ISSUE THREAD

**Issue by github2099** [Flow-Launcher/Flow.Launcher#979]
[Feature Request]

**Comment by deefrawley** [comment]
Hi github2099 - can you give us some more detail please? What action are you performing? Is it with a plugin?

**Comment by onesounds** [comment]
He's probably talking about the web search plug-in. It depends on what web browser you use. It can probably be further set in the parameter.

**Comment by taooceros** [comment]
or windows walker plugin? https://github.com/taooceros/Flow.Plugin.WindowWalker

**Comment by github2099** [comment]
Say I have "Document" folder opened. When I search for "File Explorer", it shows me "Document" folder before a new instance of File Explorer.

**Comment by jjw24** [comment]
you will be able to do this with window walker (pm install window walker):

![image](https://user-images.githubusercontent.com/26427004/149743020-9b8b3b0f-ad05-4f13-a621-3400929d572c.png)

Closing, feel free to reopen if you have further questions.

**Comment by taooceros** [comment]
I think his idea is to let active explorer window switch to the folder just selected?
