### ISSUE TITLE
Create WinGet package

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#98]
Similar to #90 @jjw24 you really should consider adding a manifest.json into the WinGet repo:
https://github.com/microsoft/winget-pkgs

**Comment by jjw24** [comment]
Added to winget: https://github.com/microsoft/winget-pkgs/pull/15722

Todo:
update ci for publishing new releases to winget

**Comment by jjw24** [comment]
Closing. Remaining to do will be tracked in #463
