### ISSUE TITLE
Pinyin transformation does not cover query

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#995]
![Favorite](https://user-images.githubusercontent.com/60434581/150991748-a0aa9f53-7574-4d8a-b7c7-6b13e3a23db9.gif)

```
Windows build number:版本 21H2 (OS 内部版本 22000.434)
Flow Launcher version: 1.9.1
```

**Comment by taooceros** [comment]
I guess you enable pinyin search. Currently if that is enabled, pinyin search will override Chinese search

**Comment by photkey** [comment]
I just wanted to give feedback, and sure enough, it doesn't seem to make sense.

**Comment by taooceros** [comment]
> I just wanted to give feedback, and sure enough, it doesn't seem to make sense.

Yeah I agree. We may recover that in next patch.
